<?php

/**
 * View -- of Report/AccountsreportController/plsAction
 */
$title = "Profit Loss Statement";
?>
<div class="right_col" role="main">
    <div class="">
        <div class="col-md-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </ul>
                    <div class="clearfix"></div>
                </div><!--end of x-title-->
                <div class="pull-right"></div>

                <div class="x_content">
                    <form data-toggle="validator" method="post"
                          action="<?php echo $this->url('report', array('action' => 'profitloss')); ?>"
                          enctype="multipart/form-data">
                        <div class="row">
                            <div class="form-group col-lg-2">
                                <label for="tier" class="control-label">Tier</label>
                                <select name="tier" id="tier" class="form-control" data-paceholder="Select">
                                    <option value=""></option>
                                    <?php

                                    $st1 = ($data["tier"] == 1) ? 'selected' : '';
                                    $st2 = ($data["tier"] == 2) ? 'selected' : '';
                                    $st3 = ($data["tier"] == 3) ? 'selected' : '';
                                    $st4 = ($data["tier"] == 4) ? 'selected' : '';
                                    ?>
                                    <option value="4" <?php echo $st4; ?> > Class</option>
                                    <option value="3" <?php echo $st3; ?>> Group</option>
                                    <option value="2" <?php echo $st2; ?>> Ledger</option>
                                    <option value="1" <?php echo $st1; ?>> Sub Ledger</option>
                                </select>
                            </div>
                            <div class="form-group col-lg-2">
                                <label class="control-label" for="organisation">Organisation</label>
                                <select class="form-control" name="organisation" id="organisation"
                                        data-placeholder="select">
                                    <?php

                                    $rowsets = $this->serviceObj->getDatabyParam('organisation', array('id' => $data['organisation']), null);

                                    foreach ( $rowsets as $row ):
                                        $selected_org = ($row['id'] == $data['organisation']) ? "selected" : "";
                                        ?>
                                        <option value="<?php echo $row['id']; ?>" <?php echo $selected_org; ?>>
                                            <?php echo $row['organisation_name']; ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                            <div class="form-group col-lg-2">
                                <label class="control-label" for="start_date">Start Date</label>

                                <input type="text"
                                       name="start_date"
                                       class="form-control fa fa-calender-o"
                                       id="start_date"
                                       value="<?php echo $data['start_date']; ?>"
                                       placeholder="Start Date"
                                       readonly
                                       required
                                >

                                <!-- <div class="date input-group" id="start_date" data-date="<?php /*echo date('Y-m-d'); */ ?>"
                                     data-date-format="yyyy-mm-dd">
                                    <input class="form-control span2" name="start_date" id="start_date" type="text"
                                           placeholder="Start Date" value="<?php /*echo $data['start_date']; */ ?>" readonly
                                           required>
                                    <span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
                                </div>-->
                            </div>
                            <div class="form-group col-lg-2">
                                <label class="control-label" for="end_date">End Date</label>

                                <input type="text"
                                       name="end_date"
                                       class="form-control fa fa-calender-o"
                                       id="end_date"
                                       value="<?php echo $data['end_date']; ?>"
                                       placeholder="End Date"
                                       readonly
                                       required
                                >

                                <!-- <div class="date input-group" id="end_date" data-date="<?php /*echo date('Y-m-d'); */ ?>"
                                     data-date-format="yyyy-mm-dd">
                                    <input class="form-control span2" name="end_date" id="end_date" type="text"
                                           placeholder="End Date" value="<?php /*echo $data['end_date']; */ ?>" readonly
                                           required>
                                    <span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
                                </div>-->
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <button type="submit" class="btn btn-sm btn-success pull-right"><i
                                            class="fa fa-gear"></i> Generate
                                </button>
                            </div>
                        </div>
                    </form>
                    <div class="clearfix">
                        <label> <i class="orange fa fa-map-marker"></i> organisation: </label>
                        <span>
                            <?php

                            $organisationName = $this->serviceObj->getDatabyParam('organisation', $data["organisation"], 'organisation_name');

                            echo $org = ($data["organisation"] == -1) ? "All Organisation" : $organisationName[0]['organisation_name'];
                            ?>
                        </span>
                    </div>

                    <?php foreach ( $this->classObj as $classrow ): ?>
                        <div class="col-md-6">
                            <table class="table table-bordered table-striped table-condensed" id="example">
                                <thead>
                                <tr>
                                    <th>Particulars</th>
                                    <?php if ( $data['tier'] > 0 ): ?>
                                        <th> <?php echo "From" . " " . $data['start_date'] . " " . "to" . " " . $data['end_date']; ?> </th>
                                    <?php else: ?>
                                        <th> <?php echo "No Peroid Found"; ?></th>
                                    <?php endif; ?>
                                </tr>
                                </thead>
                                <tbody id="trial_balance">
                                <?php

                                $total_pres_expenditure = $total_pres_income = array();
                                $grand_pres_total_expenditure = $grand_pres_total_income = [0];

                                if ( $data['tier'] <= 4 ):
                                    if ( $data['tier'] <= 4 ): ?>
                                        <tr class="classrow">
                                        <td><?php echo $classrow['name']; ?> </td>
                                    <?php
                                    endif;
                                    $pres_closing_balance = $this->transactiondetailObj->getClosingBalanceforPresPLS($data['organisation'], $data['start_date'], $data['end_date'], $classrow['id'], 4);
                                    $pres_closing_balance = ($pres_closing_balance < 0) ? -$pres_closing_balance : $pres_closing_balance;
                                    if ( $classrow['id'] == 3 ):
                                        $total_pres_income[] = $pres_closing_balance;
                                    elseif ( $classrow['id'] == 4 ):
                                        $total_pres_expenditure[] = $pres_closing_balance;
                                    endif;
                                    ?>
                                    <td></td>
                                    <?php

                                    if ( $data['tier'] <= 4 ): ?>
                                        </tr>
                                    <?php endif; ?>
                                    <?php

                                    if ( $data['tier'] <= 3 ):
                                        foreach ( $this->serviceObj->getDataByFilter('getTransactionGroupforPLS', 'accounts_group', array('organisation' => $data['organisation'], 'start_date' => $data['start_date'], 'end_date' => $data['end_date'], 'where' => array('class' => $classrow['id'])), null) as $grouprow ):// group
                                            ?>
                                            <tr class="grouprow">
                                                <td><?php echo $grouprow['name']; ?></td>
                                                <?php

                                                $pres_closing_balance = $this->transactiondetailObj->getClosingBalanceforPresPLS($data['organisation'], $data['start_date'], $data['end_date'], $grouprow['id'], 3);
                                                $pres_closing_balance = ($pres_closing_balance < 0) ? -$pres_closing_balance : $pres_closing_balance;
                                                ?>
                                                <td style="text-align:right"><?php echo number_format($pres_closing_balance, 2, '.', ','); ?></td>
                                            </tr>
                                            <?php

                                            if ( $data['tier'] <= 2 ):
                                                foreach ( $this->serviceObj->getDataByFilter('getTransactionHeadforPLS', 'accounts_head', array('organisation' => $data['organisation'], 'start_date' => $data['start_date'], 'end_date' => $data['end_date'], 'where' => array('group' => $grouprow['id'])), null) as $headrow ): // head
                                                    ?>
                                                    <tr class="headrow">
                                                        <td><?php echo $headrow['name']; ?></td>
                                                        <?php

                                                        $pres_closing_balance = $this->transactiondetailObj->getClosingBalanceforPresPLS($data['organisation'], $data['start_date'], $data['end_date'], $headrow['id'], 2);
                                                        $pres_closing_balance = ($pres_closing_balance < 0) ? -$pres_closing_balance : $pres_closing_balance;
                                                        ?>
                                                        <td style="text-align:right"><?php echo number_format($pres_closing_balance, 2, '.', ','); ?></td>
                                                    </tr>
                                                    <?php

                                                    if ( $data['tier'] <= 1 ):
                                                        foreach ( $this->serviceObj->getDataByFilter(
                                                            'getTransactionSubheadforPLS',
                                                            'accounts_sub_head',
                                                            array(
                                                                'organisation' => $data['organisation'],
                                                                'start_date' => $data['start_date'],
                                                                'end_date' => $data['end_date'],
                                                                'where' => array('head' => $headrow['id'])
                                                            ), null) as $subheadrow ): // subhead
                                                            ?>
                                                            <tr class="subheadrow">
                                                                <td><?php echo $subheadrow['name']; ?></td>
                                                                <?php

                                                                $pres_closing_balance = $this->transactiondetailObj->getClosingBalanceforPresPLS($data['organisation'], $data['start_date'], $data['end_date'], $subheadrow['id'], 1);
                                                                $pres_closing_balance = ($pres_closing_balance < 0) ? -$pres_closing_balance : $pres_closing_balance;
                                                                ?>
                                                                <td style="text-align:right"><?php echo number_format($pres_closing_balance, 2, '.', ','); ?></td>
                                                            </tr>
                                                        <?php
                                                        endforeach;
                                                    endif;
                                                endforeach;
                                            endif;
                                        endforeach;
                                    endif;
                                    ?>
                                    <tr class="classrow">
                                        <td> Total <?php echo $classrow['name']; ?>:</td>
                                        <?php

                                        if ( $classrow['id'] == 3 ):
                                            $grand_pres_total = $total_pres_income;
                                            if ( !empty($total_pres_income) ) :
                                                $grand_pres_total_income = (array) null;
                                                $grand_pres_total_income = $total_pres_income;
                                            endif;
                                        elseif ( $classrow['id'] == 4 ):
                                            $grand_pres_total = $total_pres_expenditure;
                                            if ( !empty($total_pres_expenditure) ) :
                                                $grand_pres_total_expenditure = (array) null;
                                                $grand_pres_total_expenditure = $total_pres_expenditure;
                                            endif;
                                        endif;
                                        ?>
                                        <?php

                                        foreach ( $grand_pres_total as $total ): ?>
                                            <td style="text-align:right"><?php echo number_format($total, 2, '.', ','); ?></td>
                                        <?php
                                        endforeach; ?>
                                    </tr>
                                <?php
                                endif;
                                ?>
                                <?php

                                foreach ( $grand_pres_total_income as $grand_pres_total_income1 ): endforeach;
                                foreach ( $grand_pres_total_expenditure as $grand_pres_total_expenditure1 ): endforeach;
                                ?>
                                <?php if ( $data['tier'] > 0 ): ?>
                                    <tr class="red classrow">
                                        <td> Profit/Loss before Tax</td>
                                        <td style="text-align:right"><?php echo number_format(($grand_pres_total_income1 - $grand_pres_total_expenditure1), 2, '.', ','); ?></td>
                                    </tr>
                                <?php endif; ?>
                                </tbody>
                            </table>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(function () {
        /* $('#start_date').datepicker();
         $('#end_date').datepicker();*/

        $('#start_date').daterangepicker({
            singleDatePicker: true,
            singleClasses: "picker_2",
            locale: {
                format: 'YYYY-MM-DD'
            }
        });

        $('#end_date').daterangepicker({
            singleDatePicker: true,
            singleClasses: "picker_2",
            locale: {
                format: 'YYYY-MM-DD'
            }
        });
    });

    $('#start_date').on('changeDate', function () {
        $('form').formValidation('revalidateField', $(this).attr('id'));
    });
    $('#end_date').on('changeDate', function () {
        $('form').formValidation('revalidateField', $(this).attr('id'));
    });
    /*** Form Validation ***/
    $('form').formValidation({
        framework: 'bootstrap',
        excluded: ':disabled',
        message: 'This value is not valid',
        fields: {
            'start_date': {
                validators: {
                    notEmpty: {
                        message: 'Please select start date'
                    }
                }
            },
            'end_date': {
                validators: {
                    notEmpty: {
                        message: 'Please select end date'
                    }
                }
            },
            'tier': {
                validators: {
                    notEmpty: {
                        message: 'Please select tier'
                    }
                }
            },
        }
    }).on('success.field.fv', function (e, data) {
        if (data.fv.getInvalidFields().length > 0) {    // There is invalid field
            data.fv.disableSubmitButtons(true);
        }
    });
</script>
