<?php

$title = 'Generate Student Stipend PDF';
$this->headTitle($title);
$key = $this->keyphrase;

//if ( !isset($form) ):

    //echo $this->render('student-stipend/student-stipend/pdf-table.phtml');

//else: ?>
    <div class="right_col" role="main">
        <div class="">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2><?php echo $this->escapeHtml($title); ?></h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>

                    <?php

                    if ( $this->message == NULL && $this->flashMessenger()->hasMessages() ) {
                        echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                        echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                        $messages = $this->flashMessenger()->getMessages();
                        foreach ( $messages as $message ) {
                            echo '<strong>Success!</strong>' . $message;
                        }
                        echo '</div>';
                    } else if ( $this->message == 'Failure' && $this->flashMessenger()->hasMessages() ) {
                        echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                        echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                        $messages = $this->flashMessenger()->getMessages();
                        foreach ( $messages as $message ) {
                            echo '<strong>Failure!</strong>' . $message;
                        }
                        echo '</div>';
                    }
                    ?>
                    <div class="x_content">
                        <h5><i>Instructions goes here.</i></h5><br/>
                        <?php

                        $form->prepare();
                        echo $this->form()->openTag($form);
                        $form->get('organisation_id')->setValueOptions($this->organizationSelectData);
                        $form->get('year')->setValueOptions($this->year);
                        $form->get('month')->setValueOptions($this->month);
                        ?>

                        <div class="row">
                            <div class="col-md-4 col-sm-12 col-xs-12 form-group">
                                <label>Organisation</label>
                                <?php echo $this->formRow($form->get('organisation_id')); ?>
                            </div>

                            <div class="col-md-4 col-sm-12 col-xs-12 form-group">
                                <label>Year</label>
                                <?php echo $this->formRow($form->get('year')); ?>
                            </div>


                            <div class="col-md-4 col-sm-12 col-xs-12 form-group">
                                <label>Month</label>
                                <?php echo $this->formRow($form->get('month')); ?>
                            </div>

                        </div>

                        <div class="form-group">
                            <div class="ln_solid"></div>
                            <div class="form-group text-center">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <?php

                                    echo $this->formHidden($form->get('csrf'));
                                    echo $this->formSubmit($form->get('submit'));
                                    ?>
                                </div>
                            </div>
                        </div>
                        <?php

                        echo $this->form()->closeTag();
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        function validationMessage(type) {
            var message = "";

            switch (type) {
                case 'digits':
                    message = "The input must contain only numbers and two decimal digits";
                    break;
                case 'required':
                    message = "This input field should not be left blank";
                    break;
                default:
            }

            if (message.length > 0) {
                return "<ul class='not-valid'><li>" + message + "</li></ul>";
            }

            return true;
        }

        function isNumber(evt, element) {
            var regex = /^[0-9]*(?:\.\d{1,2})?$/;

            return regex.test($(element).val());
        }

        function getNetAmount() {
            var sAmount = $("#StudentStipendAmount").val();

            var hr = $("#StudentStipendHR").val() || 0;

            var ebill = $("#StudentStipendEBill").val() || 0;

            var netAmount = parseFloat(sAmount) + parseFloat(hr) + parseFloat(ebill);

            $("#StudentStipendNetAmount").val(netAmount);
        }

        $(document).ready(function () {

            $("#StudentStipendAmount, #StudentStipendHR, #StudentStipendEBill, #StudentStipendNetAmount").change(function (e) {
                var isValid = isNumber(e, this);

                if (isValid === false) {
                    $(this).parent().find('.not-valid').remove();
                    $(this).after(validationMessage('digits'));

                    $('input[name="submit"]').prop('disabled', true);
                } else {
                    $(this).parent().find('.not-valid').remove();

                    if ($(".not-valid").length === 0) {
                        $('input[name="submit"]').prop('disabled', false);
                    }

                    getNetAmount();
                }
            });


            $(".deleteStudentStipend").on('click', function () {
                if (confirm('Are you sure you want to delete this record?')) {
                    window.location = "/public/student-stipend/delete/" + $(this).data('id');
                }
            });
        });

    </script>
<?php //endif; ?>
