<?php
$title = 'Class';
$this->headTitle($title);

$key = $this->keyphrase;

function my_encrypt($data, $key) {
    $encryption_key = base64_decode($key);
    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}
?>
<div class="right_col" role="main">
    <div class=" ">
        <div class="col-md-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="pull-right"></div>
                <a class="pull-right btn btn-primary" href="<?php echo $this->url('chartaccount', array('action' => 'addclass')); ?>">
                    <span class="white"><i class="fa fa-plus"></i> <span class="hidden-sm hidden-xs">&nbsp;Add Bank Account </span></span>
                </a>
                <?php echo $this->partial('/accounts/chartaccount/partial.phtml', array('active' => 'class')); ?>
                <div class="x_content">
                    <div class="table-responsive">
                        <table id="datatable" class="table table-striped jambo_table bulk_action">
                            <thead>
                                <tr class="headings">
                                    <th class="column-title">Sl No</th>
                                    <th class="column-title" >Class</th>
                                    <th class="column-title">Code</th>
                                    <th class="column-title">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $i = 1;
                                foreach ($this->class as $row): ?>
                                    <tr>
                                        <td><?php echo $i++; ?> </td>
                                        <td><b><?php echo $row['name']; ?></b></td>
                                        <td><?php echo $row['code']; ?></td>
                                        <td>
                                            <div class="btn-group">
                                                <a class="btn btn-xs btn-info " href="<?php echo $this->url('chartaccount', array('action' => 'editclass', 'id' => my_encrypt($row['id'],$key))); ?>" >
                                                    <i class="fa fa-pencil bigger-120"></i> Edit <span class="hidden-lg hidden-xs"></span>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- for modal -->
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        </div>
    </div>
</div>