<?php
$title = 'Journal';
$this->headTitle($title);

$key = $this->keyphrase;

function my_encrypt($data, $key) {
    $encryption_key = base64_decode($key);
    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}
?>
<div class="right_col" role="main">
    <div class=" ">
        <div class="col-md-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="pull-right tableTools-container"></div>
                <a class="pull-right btn btn-primary" href="<?php echo $this->url('chartaccount', array('action' => 'addjournal')); ?>">
                    <span class="white"><i class="fa fa-plus"></i> <span class="hidden-sm hidden-xs">&nbsp;Add Journal </span></span>
                </a>
                <div class="pull-right"></div>
                <?php echo $this->partial('/accounts/chartaccount/partial.phtml', array('active' => 'journal')); ?>
                <?php $flashMessenger = $this->flashMessenger('error'); ?>
                <?php if ($flashMessenger->hasMessages()): ?>
                    <div class="alert alert-danger alert-dismissible fade in" role="alert">
                        <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                        <?php foreach ($flashMessenger->getMessages() as $message): ?>
                            <?php echo $message ?>
                        <?php endforeach ?>
                    </div>
                <?php endif; ?>
                <?php $flashMessenger->setNamespace('success'); ?>
                <?php if ($flashMessenger->hasMessages()): ?>
                    <div class="alert alert-success alert-dismissible fade in" role="alert">
                        <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                        <?php foreach ($flashMessenger->getMessages() as $message): ?>
                            <?php echo $message ?>	
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>
                <div class="x_content">
                    <div class="table-responsive">
                        <table id="datatable" class="table table-striped jambo_table bulk_action">
                            <thead>
                                <tr class="headings">
                                    <th>SL. No. </th>
                                    <th>Journal</th>
                                    <th>Code</th>
                                    <th>Prefix</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $i = 1;
                                foreach ($this->journal as $journal): ?>
                                    <tr>
                                        <td><?php echo $i++; ?> </td>
                                        <td><b><?php echo $journal['journal']; ?></b></td>
                                        <td><?php echo $journal['code']; ?></td>
                                        <td><?php echo $journal['prefix']; ?></td>
                                        <td>
                                            <div class="btn-group">
                                                <a class="btn btn-xs btn-info " href="<?php echo $this->url('chartaccount', array('action' => 'editjournal', 'id' => my_encrypt($journal['id'],$key))); ?>" >
                                                    <i class="fa fa-pencil bigger-120"></i> Edit <span class="hidden-lg hidden-xs"></span>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- for modal -->
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        </div>
    </div>
</div>