<?php
 // module/EmployeeDetail/view/employee-detail/employee-detail/emppersonaldetail.phtml:

 $title = 'Staff Personal Details';
 $this->headTitle($title);
 
 ?>
 <div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                
                    </ul>
                  <div class="clearfix"></div>
                  </div>
              
                  <div class="x_content">
                      
                    <form>   
                 <div class="row">
                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Staff Name</label>
                    <input type="text" placeholder="Staff Name hints.." class="form-control">
                  </div>

                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Staff ID</label>
                    <input type="text" placeholder="Staff ID..." class="form-control">
                  </div>

                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Position Title</label>
                    <input type="text" placeholder="Job Title..." class="form-control">
                  </div>

                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Position Category</label>
                    <input type="text" placeholder="Type for hints..." class="form-control">
                  </div>
                </div>
                    <div class="row">
                      <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Supervisor Name</label>
                    <input type="text" placeholder="Type Supervisor Name hints.." class="form-control">
                  </div>
                      </div>
                      <div class="ln_solid"></div>
                      <div class="form-group">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                          <button type="submit" class="btn btn-success">Search</button>
                          <button type="reset" class="btn btn-default">Reset</button>
                        </div>
                      </div>
                      </form>
                </div>
                  </div>
              
               <!--<p>Add class <code>bulk_action</code> to table for bulk actions options on row select</p>-->
             <div class="x_panel"> 
            <div class="x_content">
                    <div class="table-responsive">
                      <table class="table table-striped jambo_table bulk_action"> 
                         <div class="form-group">   
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <a href="addemployee"> <button type="submit" class="btn btn-success">Add</button></a>
                                  <div class="ln_solid"></div>
                        </div>      
                      </div> 
                         <thead>
                          <tr class="headings">
                        <th>
                          <input type="checkbox" id="check-all" class="flat">
                        </th>                          
                         <th class="column-title">Sl. No. </th>
                         	<th class="column-title"> Employee ID </th>
                            <th class="column-title"> Name </th>
                            <th class="column-title">DOB</th>
                            <th class="column-title">Position Title </th>
                            <th class="column-title">Position Category </th>
                            <th class="column-title">Employment Status</th>
                            <th class="column-title">Supervisor </th>
                            <th class="column-title no-link last"><span class="nobr">Action</span>
                            </th>
                            <th class="bulk-actions" colspan="7">
                              <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                            </th>
                         </tr>
                        </thead>
                         <?php foreach ($this->employees as $employee) : ?>
                          <tr class="even pointer">
                            <td class="a-center ">
                              <input type="checkbox" class="flat" name="table_records">
                            </td>
                            <td class=" "><?php echo $this->escapeHtml($employee->getId());?></td>
                            <td class=" "><?php echo $this->escapeHtml($employee->getEmp_Id());?></td>
                            <td class=" "><?php echo $this->escapeHtml($employee->getFirst_Name()) . ' ';
												echo $this->escapeHtml($employee->getMiddle_Name()) . ' ';
												echo $this->escapeHtml($employee->getLast_Name());
										  ?></td>
                            <td class=" "><?php echo $this->escapeHtml($employee->getDate_Of_Birth());?></td></td>
                            <td class=" "></td>
                            <td class=" "><?php echo $this->escapeHtml($employee->getCid());?></td>
                            <td class=" "><?php echo $this->escapeHtml($employee->getDate_Of_Birth());?></td>
                            <td class=" "></td>
                            <td class=" last"> <a href="<?php echo $this->url('emppersonaldetails', array('id' => $employee->getId()));?>">View Details</a></td>
                          </tr>
                          <?php endforeach; ?>
                          </table>
                    </div>
            </div></div></div></div></div>
            
         
              
       
                