<?php
 $title = 'Student List';
 $this->headTitle($title);
?>

 <div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
            
                <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                     <div class="clearfix"></div>
                    </div>
                    <br/>
                        <!-- Student List-->
                        <div class="col-md-12 col-xs-12">
                          <div class="x_panel">
                            <div class="x_title">
                              <h2><?php echo $this->escapeHtml("Search for Student")?></h2>
                                <ul class="nav navbar-right panel_toolbox">
                                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                  </li>
                            
                                </ul>
                             <div class="clearfix"></div>
                          
                            </div>
                               
                            <div class="x_content">
                            <h5><i>*(In order to view the student information, first search for the Student and then select the Student from the table below to view the information. Input as many fields as possible to narrow the search.)<br />
                                            **Also note, search by name is done by "First Name" only and Student ID should be full.</i></h5>
                                      <br />
                               <?php
                                // Opening of the form tag
                                $form->prepare();
                                echo $this->form()->openTag($form);
                              ?>
                            
                              <div class="row">
                                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Student Name</label>
                                    <?php echo $this->formRow($form->get('student_name')); ?>
                                  </div>
                                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Student ID</label>
                                    <?php echo $this->formRow($form->get('student_id')); ?>
                                  </div>
                                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Programme</label>
                                    <?php echo $this->formRow($form->get('programme')); ?>
                                  </div>
                               </div>
                             
                             <div class="row">
                                <div class="ln_solid"></div>
                                <div class="form-group">
                                    <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                                      <?php
                                       echo $this->formHidden($form->get('csrf'));
                                       echo $this->formSubmit($form->get('submit')); 
                                       echo $this->form()->closeTag(); 
                                    ?>
                                </div>
                            </div>
                              
                          </div>
                        </div>
                       </div>     
                              
                          
                        <div class="col-md-12 col-sm-12 col-xs-12">
                          <div class="x_panel">
                            <div class="x_title">
                              <h2><?php echo $this->escapeHtml("List of Student(s)"); ?></h2>
                              <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                </li>
                              </ul>
                              <div class="clearfix"></div>
                            </div>
            
                            <div class="x_content">
                              <div  class="table-responsive">
                                <table id="datatable" class="table table-striped responsive-utilities jambo_table bulk_action table-bordered">
                                    <thead>
                                        <th class="column-title">Sl No </th>
                                        <th class="column-title">Name </th>
                                        <th class="column-title">Student ID </th>
                                        <th class="column-title">Gender</th>
                                        <th class="column-title">CID </th>
                                        <th class="column-title">Programme</th>
                                        <th class="column-title">Student Type</th>
                                        <th class="column-title">Student Category</th>
                                        <th class="column-title">Admission Year</th>                        
                                        <th class="column-title no-link last"><span class="nobr">Action</span></th>
                                        <th class="bulk-actions" colspan="7">
                                            <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                                        </th>
                                    </thead>
              
                                  <tbody>
                                  <?php $i=1; ?>
                                    <?php foreach ($this->studentList as $studentList) : ?>
                                    <tr class="even pointer">
                                      <td class=" "><?php echo $i; ?></td>
                                      <td class=" "><?php echo $this->escapeHtml($studentList['first_name']) . ' ' .
                                                               $this->escapeHtml($studentList['middle_name']) . ' ' .
                                                               $this->escapeHtml($studentList['last_name']);?></td>
                                      <td class=" "><?php echo $this->escapeHtml($studentList['student_id']);?></td>
                                      <td class=" "><?php echo $this->escapeHtml($studentList['gender']); ?></td>
                                      <td class=" "><?php echo $this->escapeHtml($studentList['cid']); ?></td>
                                      <td class=" "><?php echo $this->escapeHtml($studentList['programme_name']); ?></td>                                      
                                      <td class=" "><?php echo $this->escapeHtml($studentList['student_type']); ?></td>
                                      <td class=" "><?php echo $this->escapeHtml($studentList['student_category']); ?></td>
                                      <td class=" "><?php echo $this->escapeHtml($studentList['enrollment_year']); ?></td>
                                      <td class=" last"> <a href="<?php echo $this->url('student-personal-details', array('id' => $studentList['id']));?>" class="btn btn-primary btn-xs"><i class="fa fa-eye"></i> View Details </a></td>
                                    </tr>
                                    <?php $i++; ?>
                                    <?php endforeach; ?>
                                  </tbody>
                                </table>
                              </div>
                            </div>
                          </div>
                        </div>
                        </div>
                      </div>
                  </div>
                </div>
              
