<?php
 $title = 'Supplementary Budget Proposal Form';
 $this->headTitle($title);
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                  </ul>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                <!-- blockquote -->
                <blockquote>
                  <h4><i>Please select the appropriate details to be able to select the Chart of Accounts and apply for supplmentary budget amount.</i></h4>
                </blockquote>
                <br />
                <!--start of reappropriation details -->
                <div class="x_panel">
                <div class="x_title">
                  <h2><i><?php echo $this->escapeHtml('Supplementary Budget'); ?></i></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                  </ul>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                   <?php
                    // Opening of the form tag
                    $form->setAttribute();
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    //need to get the organisation id
                    $form->get('organisation_id')->setValue($this->organisation_id);
                  ?>
                <div class="row">    
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Programme (Ledger Name)<span class="required">*</span></label>
                    <div class="col-md-7 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($form->get('from_budget_ledger_head_id')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Activity / Accounts Group Head<span class="required">*</span></label>
                    <div class="col-md-7 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($form->get('from_accounts_group_head_id')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Chart of Accounts<span class="required">*</span></label>
                    <div class="col-md-7 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($form->get('from_chart_of_accounts_id')); ?>
                    </div>
                  </div>
                </div>

                </div>
              </div>
              <!-- End of Supplementary From Details box-->
              
                   <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                        <?php
                           echo $this->formHidden($form->get('organisation_id'));
                           echo $this->formHidden($form->get('csrf'));
                           echo $this->formSubmit($form->get('submit')); 
                           echo $this->form()->closeTag();
                        ?>
                    	</div>
                    </div>
               </div>
              
              <!-- End of Supplementary To Details-->
             </div>
        </div>
       
              	
    
          </div>
          <!-- After the Supplementary Details are selected -->
          <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                  </ul>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                  <?php
                    // Opening of the form tag
                    $budgetForm->setAttribute('action', $this->url('insertcurrentsupplementarybudget', array('action' => 'insertCurrentSupplementaryBudget')));
                    $budgetForm->prepare();
                    echo $this->form()->openTag($budgetForm);
                    $budgetForm->get('organisation_id')->setValue($this->organisation_id);
                    $budgetForm->get('budget_type')->setValue('Current Budget');
                    echo $this->formHidden($budgetForm->get('organisation_id'));
                    echo $this->formHidden($budgetForm->get('budget_type'));
                  ?>
                  <div class="row">    
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Reference No<span class="required">*</span></label>
                        <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                        <?php  echo $this->formRow($budgetForm->get('reference_no')); ?>
                        </div>
                        <label class="control-label col-md-2 col-sm-3 col-xs-12">Reference Date<span class="required">*</span></label>
                        <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                        <?php  echo $this->formRow($budgetForm->get('reference_date')); ?>
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Reasons<span class="required">*</span></label>
                        <div class="col-md-7 col-sm-6 col-xs-12">
                          <?php  echo $this->formRow($budgetForm->get('reasons')); ?>
                        </div>
                      </div>
                 </div>
                 <br />
                <!--start of supplementary details -->
                <div class="x_panel">
                <div class="x_title">
                  <h2><i><?php echo $this->escapeHtml('Budget Withdrawal Details: '); ?></i></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                  </ul>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                <h5><i>**Please note that any empty or zero values will be ignored.</i></h5>
                  <br />
                    <table class="table table-bordered">
                            <thead>
                              <tr class="headings">
                                <th class="column-title">Budget Ledger Head</th>
                                <th class="column-title">Accounts Group Head</th>
                                <th class="column-title">Chart of Accounts</th>
                                <th class="column-title">Budget</th>
                                <th class="column-title">Expenditure</th>
                                <th class="column-title">Balance</th>
                                <th class="column-title">Withdrawal Amount</th>
                              </tr>
                            </thead>
                            <tbody>
                          <tr>
                             <?php $i =0; foreach ($this->fromDataDetails as $data) : ?>
                              <tr class="even pointer">
                                <?php echo $this->formHidden($budgetForm->get('from_proposal_id')->setValue($data['id'])); ?>
                                <td class=" "><?php echo $this->escapeHtml($data['ledger_head']);?></td>
                                <td class=" "><?php echo $this->escapeHtml($data['group_head']);?></td>
                                <td class=" "><?php echo $this->escapeHtml($data['account_code']);?></td>
                                <td class=" "><?php echo $this->escapeHtml($data['budget_amount_approved']);?></td>
                                <td class=" "><?php echo "expenditure"; ?></td>
                                <td class=" "><?php echo $this->escapeHtml($data['balance']);?></td>
                                <td class=" "><?php echo $this->formRow($budgetForm->get('amount')); ?></td>
                              </tr>
                              <?php endforeach; ?>
                          </tr>
                         </tbody>
                       </table>
                </div>
              </div>
              <br />
              <!-- End of Reappropriation From Details box-->
              
                   <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                        <?php
                           //echo $this->formHidden($budgetForm->get('organisation_id'));
                           echo $this->formHidden($budgetForm->get('csrf'));
                           echo $this->formSubmit($budgetForm->get('submit')); 
                        ?>
                    	</div>
                    </div>
               </div>
              
              <!-- End of Supplementary To Details-->
             </div>
        </div>
       
              	
    
          </div>
        </div> 
     </div>