<?php
 $title = 'WorkForce Proposal Form';
 $this->headTitle($title);
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                  </ul>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                   <?php
                   $form->prepare();
                   echo $this->form()->openTag($form);
				   $proposal = $form->get('hrmplan');
                   echo $this->formHidden($proposal->get('id'));
				   $proposal->get('proposal_status')->setValue('Not Submitted'); 
				   echo $this->formHidden($proposal->get('proposal_status'));
				   $proposal->get('department_name')->setValueOptions($this->departmentList);
				   $form->get('position_category_id')->setValueOptions($this->positionCategory);
				   $form->get('position_title_id')->setValueOptions($this->positionTitle);
				   $form->get('position_level_id')->setValueOptions($this->positionLevel);
				   $proposal->get('five_year_plan')->setValue($proposalDetail->getFive_Year_Plan());
				   $proposal->get('working_agency')->setValue($proposalDetail->getWorking_Agency()); 
				   $proposal->get('proposal_submission_date')->setValue($proposalDetail->getProposal_Submission_Date());
				   $proposal->get('approval_date')->setValue($proposalDetail->getApproval_Date());
				   $proposal->get('department_name')->setValue($proposalDetail->getDepartment_Name());
				   $proposal->get('existing_no')->setValue($proposalDetail->getExisting_No());
				   $proposal->get('required_no')->setValue($proposalDetail->getRequired_No());
				   $proposal->get('remarks')->setValue($proposalDetail->getRemarks());
				   $proposal->get('requirement_year_1')->setValue($proposalDetail->getRequirement_Year_1());
				   $proposal->get('requirement_year_2')->setValue($proposalDetail->getRequirement_Year_2());
				   $proposal->get('requirement_year_3')->setValue($proposalDetail->getRequirement_Year_3());
				   $proposal->get('requirement_year_4')->setValue($proposalDetail->getRequirement_Year_4());
				   $proposal->get('requirement_year_5')->setValue($proposalDetail->getRequirement_Year_5());
				   $form->get('position_title_id')->setValue($proposalDetail->getPosition_Title_Id());
				   $form->get('position_category_id')->setValue($proposalDetail->getPosition_Category_Id());
				   $form->get('position_level_id')->setValue($proposalDetail->getPosition_Level_Id());				   
				   echo $this->formHidden($proposal->get('working_agency'));
				   echo $this->formHidden($proposal->get('approval_date'));
				   echo $this->formHidden($proposal->get('proposal_submission_date'));
                ?>
                <div class="row">
                <div class="form-group">  
                    <label class="control-label col-md-2 col-sm-2 col-xs-12">Five Year Plan<span class="required">*</span></label>
                   <div class="col-md-3 col-sm-3 col-xs-12">
                      <?php echo $this->formRow($proposal->get('five_year_plan')); ?>
                    </div>
                    <label class="control-label col-md-2 col-sm-2 col-xs-12">Department<span class="required">*</span></label>
                   <div class="col-md-3 col-sm-3 col-xs-12">
                      <?php echo $this->formRow($proposal->get('department_name')); ?>
                    </div>
                </div>
                </div>
                <br />
                <div class="row"> 
                <h4><i>HR Details:</i></h4>
                <div class="form-group">  
                   <label class="control-label col-md-2 col-sm-2 col-xs-12">Occupation Group<span class="required">*</span></label>
                   <div class="col-md-3 col-sm-3 col-xs-12">
                      <?php echo $this->formRow($form->get('occupational_group')); ?>
                    </div>
                   <label class="control-label col-md-2 col-sm-2 col-xs-12">Position Category<span class="required">*</span></label>
                   <div class="col-md-3 col-sm-3 col-xs-12">
                      <?php echo $this->formRow($form->get('position_category_id')); ?>
                    </div>
                </div>
                </div>
                <div class="row">
                <div class="form-group">  
                   <label class="control-label col-md-2 col-sm-2 col-xs-12">Position Title<span class="required">*</span></label>
                   <div class="col-md-3 col-sm-3 col-xs-12">
                      <?php echo $this->formRow($form->get('position_title_id')); ?>
                    </div>
                   <label class="control-label col-md-2 col-sm-2 col-xs-12">Position Level<span class="required">*</span></label>
                   <div class="col-md-3 col-sm-3 col-xs-12">
                      <?php echo $this->formRow($form->get('position_level_id')); ?>
                    </div>
                </div>
                </div>
                <br />
                <div class="row">
                <h4><i>Requirement Details:</i></h4>
                <div class="form-group">  
                    <label class="control-label col-md-2 col-sm-2 col-xs-12">Existing No:<span class="required">*</span></label>
                   <div class="col-md-3 col-sm-3 col-xs-12">
                      <?php echo $this->formRow($proposal->get('existing_no')); ?>
                    </div>
                   <label class="control-label col-md-2 col-sm-2 col-xs-12">Required No:<span class="required">*</span></label>
                   <div class="col-md-3 col-sm-3 col-xs-12">
                      <?php echo $this->formRow($proposal->get('required_no')); ?>
                    </div>
                </div>
                </div>
                <div class="row">
                <div class="form-group">  
                   <label class="control-label col-md-2 col-sm-2 col-xs-12">Remarks<span class="required">*</span></label>
                   <div class="col-md-8 col-sm-8 col-xs-12">
                      <?php echo $this->formRow($proposal->get('remarks')); ?>
                    </div>
                </div>
                </div>
                <br />
                <div class="row">
                <h4><i>Implementation Plan (Breakdown of Requirements Mentioned Above):</i></h4>
                <div class="form-group">  
                    <label class="control-label col-md-1 col-sm-1 col-xs-12">Year 1<span class="required">*</span></label>
                   <div class="col-md-1 col-sm-1 col-xs-12">
                      <?php  echo $this->formRow($proposal->get('requirement_year_1')); ?>
                    </div>
                    <label class="control-label col-md-1 col-sm-1 col-xs-12">Year 2<span class="required">*</span></label>
                   <div class="col-md-1 col-sm-1 col-xs-12">
                      <?php  echo $this->formRow($proposal->get('requirement_year_2')); ?>
                    </div>
                   <label class="control-label col-md-1 col-sm-1 col-xs-12">Year 3<span class="required">*</span></label>
                   <div class="col-md-1 col-sm-1 col-xs-12">
                      <?php  echo $this->formRow($proposal->get('requirement_year_3')); ?>
                    </div>
                    <label class="control-label col-md-1 col-sm-1 col-xs-12">Year 4<span class="required">*</span></label>
                   <div class="col-md-1 col-sm-1 col-xs-12">
                      <?php  echo $this->formRow($proposal->get('requirement_year_4')); ?>
                    </div>
                    <label class="control-label col-md-1 col-sm-1 col-xs-12">Year 5<span class="required">*</span></label>
                   <div class="col-md-1 col-sm-1 col-xs-12">
                      <?php  echo $this->formRow($proposal->get('requirement_year_5')); ?>
                    </div>
                </div>
                </div>          
               
                <div class="row">
                        <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                              <div class="col-md-6 col-sm-6 col-xs-12">
                     <?php 
					 echo $this->formHidden($form->get('csrf'));
					 echo $this->formInput($proposal->get('submit')); ?>
                    </div>
                    </div>
                    </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                </div>
              </div>
        </div>
      </div>
     </div>
   </div>
  
