<?php
 $title = 'WorkForce Proposal Form ';
 $this->headTitle($title);
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                  
             
                  
 <form>   
                 <div class="row">
                      <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Five Year Plan</label>
                    <input type="text" placeholder="2016" class="form-control" readonly="readonly"/>
                  </div>
                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Department Name </label>
                    <input type="text" placeholder="Finance" class="form-control" readonly>
                  </div>

                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Position Title </label>
                    <input type="text" placeholder="2" class="form-control" readonly>
                  </div>

                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Position Category</label>
                    <input type="text" placeholder="Long Term Training" class="form-control" readonly>
                  </div>
                      <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Position Level</label>
                    <input type="text" placeholder="GOI" class="form-control" readonly>
                  </div>
               
                      <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Existing No.:</label>
                    <input type="text" placeholder="18months" class="form-control" readonly>
                  </div>
                        <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Required No.</label>
                    <input type="text" placeholder="Car" class="form-control" readonly>
                  </div>
                      </div>
                      
                      </form>
                  
                      <div class="row" > 
                        <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Remarks</label>
                    <textarea class="form-control"></textarea>
                  </div></div>
                   <div class="row" > 
                           
                        <div class="ln_solid"></div>
                    <div class="form-group">
                      <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                       <button type="submit" class="btn btn-success">Approve</button>
                       <button type="submit" class="btn btn-danger">Reject</button>
                      </div>
                    </div>  </div>
            
                </div>
              </div>
        </div>
 
            </div>
         
          </div>
        </div> 

              
              
   
            
    