<?php
 $title = 'Student Medical Records';
 $this->headTitle($title);
 $student_records = array();
 foreach($this->studentRecords as $record){
	 $student_records[] = $record;
	 $student_name = $record['first_name']. ' '.$record['middle_name']. ' '.$record['last_name'];
	 $student_id = $record['student_id'];
	 $student_programme = $record['programme_name'];
	 $student_year = $record['enrollment_year'];
 }

 $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    //IDEA-CBC
    //Original
    //$iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('aes-256-cbc'));

    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));

    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}
 ?>
<div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                  </div>
                    
                  <div class="x_content">
                    <br/>
					<?php
					// Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    ?>
                    <div class="row">
                      <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Student Name:</label>
                        <div class="col-md-3 col-sm-3 col-xs-12">
                       		<input type="text" placeholder="<?php echo $student_name; ?>" class="form-control col-md-7 col-xs-12" disabled="disabled">
                        </div>
                      <label class="control-label col-md-2 col-sm-2 col-xs-12">Student ID:</label>
                        <div class="col-md-3 col-sm-3 col-xs-12">
                        	<input type="text" placeholder="<?php echo $student_id; ?>" class="form-control col-md-7 col-xs-12" disabled="disabled">
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Programme Name:</label>
                        <div class="col-md-3 col-sm-3 col-xs-12">
                       		<input type="text" placeholder="<?php echo $student_programme; ?>" class="form-control col-md-7 col-xs-12" disabled="disabled">
                        </div>
                      <label class="control-label col-md-2 col-sm-2 col-xs-12">Enrollment Year:</label>
                        <div class="col-md-3 col-sm-3 col-xs-12">
                        	<input type="text" placeholder="<?php echo $student_year; ?>" class="form-control col-md-7 col-xs-12" disabled="disabled">
                        </div>
                      </div>
                    </div>
                    <br />
                    <div class="ln_solid"></div>
                    <br />
                     <!-- start work experience -->
                            <table class="table jambo_table table-striped no-margin">
                              <thead>
                                <tr>
                                  <th>SL No</th>
                                  <th>Medical Problem</th>
                                  <th>From Date</th>
                                  <th>To Date</th>
                                  <th>Remarks</th>
                                  <th>Action</th>
                                </tr>
                              </thead>
                              <tbody>
								            <?php $i=1; foreach ($student_records as $student) : ?>
                                 <tr>
                                    <td><?php echo $i++;?></td>
                                    <td><?php echo $this->escapeHtml($student['medical_problem']);?></td>
                                    <td><?php echo $this->escapeHtml($student['from_date']);?></td>
                                    <td><?php echo $this->escapeHtml($student['to_date']);?></td>
                                    <td><?php echo $this->escapeHtml($student['remarks']);?></td>
                                    <td>
                                    <a href="<?php echo $this->url('editmedicalrecord', array('id' => my_encrypt($student['id'], $key)));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit</a>
                                    <?php if($student['medical_proof']){?>
                                    <a href = "/<?php echo $student['medical_proof'];?>" target="_blank" class="btn btn-success btn-xs"><i class="fa fa-download"></i> Download File</a>
                                    <?php } else { ?>
                                      <p><i>Medical Proof Not Uploaded!</i></p>
                                   <?php }?>
                                    </td>
                                  </tr>
                                  <?php endforeach; ?>
                                </tbody>
                            </table>
                            <!-- end work experience -->            
                          <div class="row">
                            <div class="ln_solid"></div>
                              <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                                  <div class="col-md-3 col-sm-3 col-xs-12">
                                  <?php
                                    echo $this->formHidden($form->get('csrf')); 
                                    echo $this->form()->closeTag();
                                  ?>
                                  </div>
                              </div>
                          </div>
                 
                 </div>
              </div>
           </div>
        </div>
     </div>