<?php
 $title = 'Capital Budget Proposal';
 $this->headTitle($title);
 
 $organisations = array();
 foreach($this->organisationList as $key=>$value){
	 $organisations[$key] = $value;
 }
 
 $budgetProposal = array();
 foreach($this->budgetDetails as $detail){
	 $budgetProposal['id'] = $detail['id'];
	 $budgetProposal['five_year_plan'] = $detail['five_year_plan'];
	 $budgetProposal['financial_year'] = $detail['financial_year'];
	 $budgetProposal['activity_name'] = $detail['activity_name'];
	 $budgetProposal['proposed_budget_amount'] = $detail['proposed_budget_amount'];
	 $budgetProposal['write_up'] = $detail['write_up'];
	 $budgetProposal['organisation_id'] = $detail['organisation_id'];
	 $budgetProposal['departments_id'] = $detail['departments_id'];
	 $budgetProposal['object_code_id'] = $detail['object_code_id'];
	 $budgetProposal['object_name'] = $detail['object_name'];
	 $budgetProposal['broad_head_name_id'] = $detail['broad_head_name_id'];
	 $budgetProposal['broad_head_name'] = $detail['broad_head_name'];
 }
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                  </ul>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				    $proposal = $form->get('capitalbudgetproposal');
                    echo $this->form()->openTag($form);
				  ?>  
                <div class="row">    
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Five Year Plan</label>
                    <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <input type="text" class="form-control" disabled="disabled" placeholder="<?php echo $budgetProposal['five_year_plan']; ?>">
                    </div>
                    <label class="control-label col-md-2 col-sm-3 col-xs-12">Financial Year</label>
                    <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <input type="text" class="form-control" disabled="disabled" placeholder="<?php echo $budgetProposal['financial_year']; ?>">
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">OVC/College</label>
                    <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <input type="text" class="form-control" disabled="disabled" placeholder="<?php echo $organisations[$budgetProposal['organisation_id']]; ?>">
                    </div>
                    <label class="control-label col-md-2 col-sm-3 col-xs-12">Office/Department</label>
                    <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <input type="text" class="form-control" disabled="disabled" placeholder="<?php echo $budgetProposal['departments_id']; ?>">
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Activity List<span class="required">*</span></label>
                    <div class="col-md-7 col-sm-6 col-xs-12">
                      <input type="text" class="form-control" disabled="disabled" placeholder="<?php echo $budgetProposal['activity_name']; ?>">
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Broad Head Name<span class="required">*</span></label>
                    <div class="col-md-7 col-sm-6 col-xs-12">
                      <input type="text" class="form-control" disabled="disabled" placeholder="<?php echo $budgetProposal['broad_head_name']; ?>">
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Object Code<span class="required">*</span></label>
                    <div class="col-md-7 col-sm-6 col-xs-12">
                      <input type="text" class="form-control" disabled="disabled" placeholder="<?php echo $budgetProposal['object_name']; ?>">
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Budget Type<span class="required">*</span></label>
                    <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($proposal->get('budget_type')); ?>
                    </div>
                    <label class="control-label col-md-2 col-sm-3 col-xs-12">Proposed Budget (Amount)<span class="required">*</span></label>
                    <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <input type="text" class="form-control" disabled="disabled" placeholder="<?php echo $budgetProposal['proposed_budget_amount']; ?>">
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Write Up<span class="required">*</span></label>
                    <div class="col-md-7 col-sm-6 col-xs-12">
                      <textarea class="form-control" rows="3" disabled="disabled" placeholder='<?php echo $budgetProposal['write_up']; ?>'></textarea>
                    </div>
                  </div>
                </div> 
                  
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                    	</div>
                    </div>
               </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                </div>
              </div>
        <!-- Start of table listing budget ledgers -->
        <div class="x_panel">
            <div class="x_title">
                  <h2><?php echo $this->escapeHtml('Capital Budget Proposal List'); ?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                  </ul>
                 <div class="clearfix"></div>
                </div>
                <h5><i>*The following are the list of the proposals to be submitted by the Department. You can view/edit/delete the proposal before submitting
                  			to the HRO of the College/Organisation. Once submitted, then you will not be able to edit the proposal</i></h5>
                  <br />
                <div class="x_content">
                     <div class="table-responsive">
                      <table class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Sl. No. </th>
                            <th class="column-title">Activity Name</th>
                            <th class="column-title">Broad Head Name</th>
                            <th class="column-title">Object Code</th>
                            <th class="column-title">Description</th>
                            <th class="column-title">Proposed Amount</th>
                            <th class="column-title">Actions</th>
                          </tr>
                        </thead>  
                        <tbody>
                      <tr>
                         <?php $i =1; foreach ($this->budgetProposals as $proposal) : ?>
                          <tr class="even pointer">
                            <td class=" "><?php echo $i++; ?></td>
                            <td class=" "><?php echo $this->escapeHtml($proposal['activity_name']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($proposal['broad_head_name_id']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($proposal['object_code_id']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($proposal['write_up']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($proposal['proposed_budget_amount']);?></td>
                            <td class=" "><a href="<?php echo $this->url('viewcapitalbudgetproposal', array('id' => $proposal['id'])); ?>" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i>View</a>
                            			  <a href="<?php echo $this->url('editcapitalbudgetproposal', array('id' => $proposal['id'])); ?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a>
                                          <a href="<?php echo $this->url('deletecapitalbudgetproposal', array('id' => $proposal['id'])); ?>" class="btn btn-danger btn-xs"><i class="fa fa-thrash-o"></i>Delete</a>
                                    </td>
                          </tr>
                          <?php endforeach; ?>
                      </tr>
                      </tbody>
                      </table>
                     </div>
                 </div>
              </div>
              	
    
          </div>
        </div> 
     </div>