<?php
 $title = 'Add Goods Received';
 $this->headTitle($title);
?>

<div class="right_col" role="main">
    <div class="">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                </div>
                    <!-- Start of Tab-->
                <div class="" role="tabpanel" data-example-id="togglable-tabs">
                    <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                        <li role="presentation" class="active"><a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">Goods Received Purchased</a>
                        </li>
                        <li role="presentation" class=""><a href="#tab_content2" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false">Goods Received Donation</a>
                        </li>
                    </ul>
                    <div id="myTabContent" class="tab-content">
                        <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab">
                            <br/>
                            <!-- Adding Item Category-->
                            <div class="col-md-12 col-xs-12">
                                <div class="x_panel">
                                    <div class="x_title">
                                      <h2><?php echo $this->escapeHtml("Add Goods Received Purchased")?></h2>
                                        <ul class="nav navbar-right panel_toolbox">
                                          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                          </li>
                                    
                                        </ul>
                                     <div class="clearfix"></div>
                                  
                                    </div>
                                       
                                    <div class="x_content">
                                      <br />
                                       <?php
                                        // Opening of the form tag
                                        $goodsreceivedpurchasedForm->setAttribute('action', $this->url('addgoodsreceivedpurchased', array('action' => 'addGoodsReceivedPurchased')));
                                        $goodsreceivedpurchasedForm->prepare();
                                        echo $this->form()->openTag($goodsreceivedpurchasedForm);
                                        $goodspurchasedentry = $goodsreceivedpurchasedForm->get('goodsreceivedpurchased');
                                        echo $this->formHidden($goodspurchasedentry->get('id'));

                                       // $goodspurchasedentry->get('item_category_type')->setValueOptions($this->itemCategory);
                                       // $goodspurchasedentry->get('item_received_by')->setValue($this->username);
                                        //$goodspurchasedentry->get('item_sub_category_id')->setValueOptions($this->itemSubCategory);
                                        //$goodspurchasedentry->get('item_name_id')->setValueOptions($this->itemName);
                                       
                                        $goodspurchasedentry->get('supplier_details_id')->setValueOptions($this->itemSupplier);


                    
                                        $received_type = 'Purchased';
                                        $goodspurchasedentry->get('item_received_type')->setValue($received_type);

                                        $goods_entry_date = date('Y-m-d');
                                        $goodspurchasedentry->get('item_entry_date')->setValue($goods_entry_date);

                                      ?>
                                    
                                      <div class="form-group">           
                                        <label class="control-label col-md-2 col-sm-2 col-xs-12" for="item_received_type">Item Received Type</label>
                                        <div class="col-md-8 col-sm-8 col-xs-12">
                                            <?php  echo $this->formRow($goodspurchasedentry->get('item_received_type')); ?>
                                        </div>
                                      </div>

                                      <div class="form-group">           
                                        <label class="control-label col-md-2 col-sm-2 col-xs-12" for="supplier_details_id">Supplier</label>
                                        <div class="col-md-3 col-sm-3 col-xs-12">
                                            <?php  echo $this->formRow($goodspurchasedentry->get('supplier_details_id')); ?>
                                        </div>
                                        <label class="control-label col-md-2 col-sm-2 col-xs-12" for="reference_no">Reference Number</label>
                                        <div class="col-md-3 col-sm-3 col-xs-12">
                                            <?php  echo $this->formRow($goodspurchasedentry->get('reference_no')); ?>
                                        </div>
                                      </div>              
                
                                      <div class="form-group">           
                                        <label class="control-label col-md-2 col-sm-2 col-xs-12" for="reference_date">Reference Date</label>
                                        <div id="datepicker" class="date-picker col-md-3 col-sm-3 col-xs-12">
                                            <?php  echo $this->formRow($goodspurchasedentry->get('reference_date')); ?>
                                        </div>
                                        <label class="control-label col-md-2 col-sm-2 col-xs-12" for="supplier_order_no">Supplier Order Number</label>
                                        <div class="col-md-3 col-sm-3 col-xs-12">
                                            <?php  echo $this->formRow($goodspurchasedentry->get('supplier_order_no')); ?>
                                        </div>
                                      </div>

                                      <div class="form-group">
                                        <label class="control-label col-md-2 col-sm-2 col-xs-12" for="item_received_date">Item Received Date</label>
                                        <div class="col-md-3 col-sm-3 col-xs-12">
                                            <?php  echo $this->formRow($goodspurchasedentry->get('item_received_date')); ?>
                                        </div>           
                                        <label class="control-label col-md-2 col-sm-2 col-xs-12" for="item_entry_date">Item Entry Date</label>
                                        <div class="col-md-3 col-sm-3 col-xs-12">
                                            <?php  echo $this->formRow($goodspurchasedentry->get('item_entry_date')); ?>
                                        </div>
                                      </div>

                                      <div class="form-group">           
                                        <label class="control-label col-md-2 col-sm-2 col-xs-12" for="item_received_by">Item Received By</label>
                                        <div class="col-md-3 col-sm-3 col-xs-12">
                                            <?php  echo $this->formRow($goodspurchasedentry->get('item_received_by')); ?>
                                        </div>
                                        <label class="control-label col-md-2 col-sm-2 col-xs-12" for="item_updated_by">Item Verified By</label>
                                        <div class="col-md-3 col-sm-3 col-xs-12">
                                            <?php  echo $this->formRow($goodspurchasedentry->get('item_verified_by')); ?>
                                        </div>
                                    </div><br/><br/>

                                    <div class="clear"></div>
                                    <h2><?php echo $this->escapeHtml("Item Purchased Details"); ?></h2>
                                    <div class="clear"></div>
                                    <div class="ln_solid"></div>

                                    <div class="form-group">
                                       
                                        <!-- Dynamically adding rows -->  
                    
                                        <br /><br />
                                        <div class="clear"></div>
                                        <h2><?php echo $this->escapeHtml("Item Details"); ?></h2>
                                        <div class="clear"></div>
                                        <div class="ln_solid"></div>
                                           <?php   echo $this->formCollection($goodsreceivedpurchasedForm->get('goodsreceiveddetails')); ?>
                                            <button class="btn btn-success" type="button"  onclick="return add_goodsreceived()"> Add More Item</button>

                                    <!-- End of Dynamically added rows --> 
                
                                    <div class="form-group">
                                        <div class="ln_solid"></div>
                                        <div class="form-group">
                                            <label class="control-label col-md-12 col-sm-12 col-xs-12"></label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                            <?php  
                                            echo $this->formRow($goodsreceivedpurchasedForm->get('csrf'));
                                            echo $this->formRow($goodspurchasedentry->get('submit')); 
                                            ?>
                                            </div>
                                        </div>
                                    </div>
                                    <?php echo $this->form()->closeTag(); ?>                                       
                                    </div>
                                </div>
                            </div>                           
                                <!-- End of Add Goods Received Purchased-->
                        </div>

                        <div role="tabpanel" class="tab-pane fade" id="tab_content2" aria-labelledby="profile-tab">
                                <br/>
                                <!-- Adding Item Sub Category-->
                            <div class="col-md-12 col-xs-12">
                                <div class="x_panel">
                                    <div class="x_title">
                                      <h2><?php echo $this->escapeHtml("Add Goods Received Donation")?></h2>
                                        <ul class="nav navbar-right panel_toolbox">
                                          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                          </li>
                                    
                                        </ul>
                                     <div class="clearfix"></div>
                                  
                                    </div>
                                       
                                    <div class="x_content">
                                      <br />
                                       <?php
                                        // Opening of the form tag
                                        $goodsreceiveddonationForm->setAttribute('action', $this->url('add-goods-received-donation', array('action' => 'addGoodsReceivedDonation')));
                                        $goodsreceiveddonationForm->prepare();
                                        echo $this->form()->openTag($goodsreceiveddonationForm);
                                        $goodsdonationentry = $goodsreceiveddonationForm->get('goodsreceiveddonation');
                                        echo $this->formHidden($goodsdonationentry->get('id'));
                                        
                                       // $goodsdonationentry->get('item_category_type')->setValueOptions($this->itemCategory);
                                        $goodsdonationentry->get('item_received_by')->setValue($this->username);
                                        $goodsdonationentry->get('item_sub_category_id')->setValueOptions($this->itemSubCategory);
                                        $goodsdonationentry->get('item_name_id')->setValueOptions($this->itemName);
                                        $goodsdonationentry->get('donation_id')->setValueOptions($this->itemDonor);

                    
                                        $received_type = 'Donation';
                                        $goodsdonationentry->get('item_received_type')->setValue($received_type);

                                        $goods_entry_date = date('Y-m-d');
                                        $goodsdonationentry->get('item_entry_date')->setValue($goods_entry_date);
                                        ?> 

                                    <div class="form-group">           
                                        <label class="control-label col-md-2 col-sm-2 col-xs-12" for="item_received_type">Item Received Type</label>
                                        <div class="col-md-8 col-sm-8 col-xs-12">
                                            <?php  echo $this->formRow($goodsdonationentry->get('item_received_type')); ?>
                                        </div>
                                    </div>

                                    <div class="form-group">           
                                        <label class="control-label col-md-2 col-sm-2 col-xs-12" for="donation_id">Item Donar</label>
                                        <div class="col-md-8 col-sm-8 col-xs-12">
                                            <?php  echo $this->formRow($goodsdonationentry->get('donation_id')); ?>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label col-md-2 col-sm-2 col-xs-12" for="item_received_date">Item Received Date</label>
                                        <div class="col-md-3 col-sm-3 col-xs-12">
                                            <?php  echo $this->formRow($goodsdonationentry->get('item_received_date')); ?>
                                        </div>           
                                        <label class="control-label col-md-2 col-sm-2 col-xs-12" for="item_entry_date">Item Entry Date</label>
                                        <div class="col-md-3 col-sm-3 col-xs-12">
                                            <?php  echo $this->formRow($goodsdonationentry->get('item_entry_date')); ?>
                                        </div>
                                    </div>

                                    <div class="form-group">           
                                        <label class="control-label col-md-2 col-sm-2 col-xs-12" for="item_received_by">Item Received By</label>
                                        <div class="col-md-3 col-sm-3 col-xs-12">
                                            <?php  echo $this->formRow($goodsdonationentry->get('item_received_by')); ?>
                                        </div>
                                        <label class="control-label col-md-2 col-sm-2 col-xs-12" for="item_updated_by">Item Verified By</label>
                                        <div class="col-md-3 col-sm-3 col-xs-12">
                                            <?php  echo $this->formRow($goodsdonationentry->get('item_verified_by')); ?>
                                        </div>
                                    </div><br/><br/>

                                    <div class="clear"></div>
                                    <h2><?php echo $this->escapeHtml("Item Donation Details"); ?></h2>
                                    <div class="clear"></div>
                                    <div class="ln_solid"></div>

                                    <div class="form-group">
                                        <div class="col-md-4 col-sm-12 col-xs-12">
                                            <label>Item Category</label>
                                                <?php echo $this->formRow($goodsdonationentry->get('item_category_type')); ?>
                                        </div>
                                        <div class="col-md-4 col-sm-12 col-xs-12">
                                            <label>Item Sub Category</label>
                                            <?php echo $this->formRow($goodsdonationentry->get('item_sub_category_id')); ?>
                                        </div>
                                        <div class="col-md-4 col-sm-12 col-xs-12">
                                            <label>Item Name</label>
                                            <?php echo $this->formRow($goodsdonationentry->get('item_name_id')); ?>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="col-md-6 col-sm-12 col-xs-12">
                                            <label>Quantity</label>
                                            <?php echo $this->formRow($goodsdonationentry->get('item_quantity')); ?>
                                        </div>
                                        <div class="col-md-6 col-sm-12 col-xs-12">
                                            <label>Item Cost</label>
                                            <?php echo $this->formRow($goodsdonationentry->get('item_purchasing_rate')); ?>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="col-md-6 col-sm-12 col-xs-12">
                                            <label>Item Specification</label>
                                            <?php echo $this->formRow($goodsdonationentry->get('item_specification')); ?>
                                        </div>
                                        
                                        <div class="col-md-6 col-sm-12 col-xs-12">
                                            <label>Remarks</label>
                                            <?php echo $this->formRow($goodsdonationentry->get('remarks')); ?>
                                        </div>
                                    </div>
                
                                    <div class="form-group">
                                        <div class="ln_solid"></div>
                                        <div class="form-group">
                                            <label class="control-label col-md-12 col-sm-12 col-xs-12"></label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <?php  
                                                //echo $this->formHidden($form->get('csrf'));
                                                echo $this->formRow($goodsdonationentry->get('submit')); 
                                                echo $this->form()->closeTag();
                                                ?>
                                            </div>
                                        </div>
                                    </div>
                                    </div>
                                </div>
                            </div>
                            <!--End of Add Goods Received Donation-->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
      $(document).ready(function() {
        $('#datepicker').daterangepicker({
          singleDatePicker: true,
          calender_style: "picker_4"
        }, function(start, end, label) {
          console.log(start.toISOString(), end.toISOString(), label);
        });
      });
    </script>


     <script>
     function add_goodsreceived() {
         var currentCount = $('form > fieldset > fieldset').length;
         var template = $('form > fieldset > span').data('template');
         template = template.replace(/__index__/g, currentCount);

         $('form > fieldset').append(template);

         return false;
     }

     function remove_addsreceived(){
        $('form > fieldset > fieldset').last().remove();
        return false;
     }
 </script>
                                      
                                  
                                