<?php
 // Inventory/Inventory/view/goods-transaction/goods-transaction/add-item-donar.phtml:

 $title = 'Add Item Donor';
 $this->headTitle($title);

  $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));
    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}
?>

<div class="right_col" role="main">
    <div class=" ">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
			  <div class="x_title">
				<h2><?php echo $this->escapeHtml($title); ?></h2>
				<ul class="nav navbar-right panel_toolbox">
				  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
				  </li>
				 </ul>
			  <div class="clearfix"></div>
              <h5><i>Add Item Donor form. You can maintain your own organisation/ college item donor.</i></h5>
			  </div>

              <?php 
                    if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                        echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                        echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                        $messages = $this->flashMessenger()->getMessages();
                        foreach($messages as $message) {
                            echo '<strong>Success!</strong>'. $message;
                        }
                        echo '</div>';
                    }

                    else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                        echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                        echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                        $messages = $this->flashMessenger()->getMessages();
                        foreach($messages as $message) {
                            echo '<strong>Failure!</strong>'. $message;
                        }
                        echo '</div>';
                    }

                ?>  
		  
			  <div class="x_content">
				  <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				    $itemdonor = $form->get('additemdonor');
                    echo $this->form()->openTag($form);
                    $itemdonor->get('organisation_id')->setValue($this->organisation_id);
                    echo $this->formHidden($itemdonor->get('id'));
                    echo $this->formHidden($itemdonor->get('organisation_id'));
                 ?>            
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="donor_name">Donor Name<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                            <?php  echo $this->formRow($itemdonor->get('donor_name')); ?>
                    </div>
                </div>
                
                <div class="form-group">           
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="remarks">Remarks</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                            <?php  echo $this->formRow($itemdonor->get('remarks')); ?>
                    </div>
                </div>
                
                <div class="form-group">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                       <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                       <div class="col-md-6 col-sm-6 col-xs-12">
						   <?php  
                            echo $this->formHidden($form->get('csrf'));
                            echo $this->formSubmit($itemdonor->get('submit')); ?>
                        </div>
                    </div>
                </div> 

                    <?php 
                //closing the form tag  
                 echo $this->form()->closeTag();
                 ?>

			  </div> <!-- End of x-content -->
            </div>

            
<?php
 // Inventory/Inventory/view/goods-transaction/goods-transaction/view-item-donar.phtml:

 $title = 'Donor Lists';
 $this->headTitle($title);
?>     
            <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                  <h5><i>List of your organisation/ college item donor added.</i></h5>
                </div>

                <div class="x_content">
                    <div class="table-responsive">
                        <table id="datatable" class="table table-striped responsive-utilities jambo_table bulk_action table-bordered">
                            <thead>
                                <tr class="headings">
                                    <th class="column-title">Sl. No</th>
                                    <th class="column-title">Donor Name </th>
                                    <th class="column-title">Remarks </th>
                                    <th class="column-title">Action</th>
                                </tr>
                            </thead>

                            <tbody>
                            <?php $i=1; ?>
                            <?php foreach ($this->itemDonorList as $donorList) : ?>
                                <tr class="even pointer">
                                    <td class=" "><?php echo $i; ?></td>
                                    <td class=" "><?php echo $this->escapeHtml($donorList->getDonor_Name()); ?></td>
                                    <td class=" "><?php echo $this->escapeHtml($donorList->getRemarks()); ?></td>
                                    <th class=" ">
                                    <a href="<?php echo $this->url('edit-item-donor', array('id' => my_encrypt($donorList->getId(), $key))); ?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit </a>
                                    </th>
                                </tr>
                            <?php $i++; ?>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!--
 <script>
     function add_category() {
         var currentCount = $('form > fieldset > fieldset').length;
         var template = $('form > fieldset > span').data('template');
         template = template.replace(/__index__/g, currentCount);

         $('form > fieldset').append(template);

         return false;
     }
 </script>-->
