<?php
 // module/GoodsTransaction/view/goods-transaction/goods-transaction/add-goods-recieved-purchased.phtml:

 $title = 'Supplied Goods Lists';
 $this->headTitle($title);

 $supplierGoods = array();
 foreach($this->supplierDetails as $goodsDetails)
 {
  
    $supplierGoods['organisation_name'] = $goodsDetails['organisation_name'];
    $supplierGoods['address'] = $goodsDetails['address'];
    $supplierGoods['supplier_name'] = $goodsDetails['supplier_name'];
    $supplierGoods['supplier_address'] = $goodsDetails['supplier_address'];
    $supplierGoods['reference_date'] = $goodsDetails['reference_date'];
    $supplierGoods['reference_no'] = $goodsDetails['reference_no'];
    $supplierGoods['supplier_order_no'] = $goodsDetails['supplier_order_no'];
    $supplierGoods['receipt_voucher_no'] = $goodsDetails['receipt_voucher_no'];
 }

 $storeDetails = array();
 foreach($this->storeManagerDetails as $details)
 {
  $storeDetails['name'] = $details['first_name'].' '.$details['middle_name'].' '.$details['last_name'];
 }

 function numtowords($num){ 
  $decones = array( 
              '01' => "One", 
              '02' => "Two", 
              '03' => "Three", 
              '04' => "Four", 
              '05' => "Five", 
              '06' => "Six", 
              '07' => "Seven", 
              '08' => "Eight", 
              '09' => "Nine", 
              10 => "Ten", 
              11 => "Eleven", 
              12 => "Twelve", 
              13 => "Thirteen", 
              14 => "Fourteen", 
              15 => "Fifteen", 
              16 => "Sixteen", 
              17 => "Seventeen", 
              18 => "Eighteen", 
              19 => "Nineteen", 
              );
  $ones = array( 
              0 => " ",
              1 => "One",     
              2 => "Two", 
              3 => "Three", 
              4 => "Four", 
              5 => "Five", 
              6 => "Six", 
              7 => "Seven", 
              8 => "Eight", 
              9 => "Nine", 
              10 => "Ten", 
              11 => "Eleven", 
              12 => "Twelve", 
              13 => "Thirteen", 
              14 => "Fourteen", 
              15 => "Fifteen", 
              16 => "Sixteen", 
              17 => "Seventeen", 
              18 => "Eighteen", 
              19 => "Nineteen" 
              ); 
  $tens = array( 
              0 => "",
              2 => "Twenty", 
              3 => "Thirty", 
              4 => "Forty", 
              5 => "Fifty", 
              6 => "Sixty", 
              7 => "Seventy", 
              8 => "Eighty", 
              9 => "Ninety" 
              ); 
  $hundreds = array(
              "Hundred", 
              "Thousand", 
              "Million", 
              "Billion", 
              "Trillion", 
              "Quadrillion" 
              ); //limit t quadrillion 
  $num = number_format($num,2,".",","); 
  $num_arr = explode(".",$num); 
  $wholenum = $num_arr[0]; 
  $decnum = $num_arr[1]; 
  $whole_arr = array_reverse(explode(",",$wholenum)); 
  krsort($whole_arr); 
  $rettxt = ""; 
  foreach($whole_arr as $key => $i){ 
      if($i < 20){ 
          $rettxt .= $ones[$i]; 
      }
      elseif($i < 100){ 
          $rettxt .= $tens[substr($i,0,1)]; 
          $rettxt .= " ".$ones[substr($i,1,1)]; 
      }
      else{ 
          $rettxt .= $ones[substr($i,0,1)]." ".$hundreds[0]; 
          $rettxt .= " ".$tens[substr($i,1,1)]; 
          $rettxt .= " ".$ones[substr($i,2,1)]; 
      } 
      if($key > 0){ 
          $rettxt .= " ".$hundreds[$key]." "; 
      } 

  } 
  $rettxt = $rettxt." Ngultrum";

  if($decnum > 0){ 
      $rettxt .= " and "; 
      if($decnum < 20){ 
          $rettxt .= $decones[$decnum]; 
      }
      elseif($decnum < 100){ 
          $rettxt .= $tens[substr($decnum,0,1)]; 
          $rettxt .= " ".$ones[substr($decnum,1,1)]; 
      }
      $rettxt = $rettxt." chhertum"; 
  } 
  return $rettxt." Only";
}

 ?>
    <div class=" ">
        <div class="col-md-12 col-sm-12 col-xs-12">

            <!-- Start of table listing item to issue -->
                <div class="x_panel">
                  <div class="x_title">
                    <div class="form-group">
                      <div style="float: left;"><label class="control-label col-md-2 col-sm-2 col-xs-12">Reference Date:</label>
                        <?php echo $supplierGoods['reference_date'];?></div>
                        <div style="float: right;"><label class="control-label col-md-2 col-sm-2 col-xs-12">Voucher No:</label>
                          <?php echo $supplierGoods['receipt_voucher_no'];?></div>
                    </div>
                    <br/>
                    <hr><br/>
                <div class="right_col" role="main"><h2><center><u><?php echo $this->escapeHtml('RECEIPT VOUCHER'); ?></u></center></h2>
                    <div class="clearfix"></div>
                  </div>
                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12"></label>
                        <center><b><?php echo $supplierGoods['organisation_name']; ?><br/>
                          <?php echo $supplierGoods['address']; ?>
                        </b></center>
                    </div>
                    <br>
                    <hr>
                    <div class="form-group">
                        <div style="float: left;><label class="control-label col-md-2 col-sm-2 col-xs-12">Supplier:</label>
                          <?php echo $supplierGoods['supplier_name'];?>, 
                          <?php echo $supplierGoods['supplier_address'];?>
                        </div>
                        <div style="float: right; width: 33%; text-align: left;"><label class="control-label col-md-2 col-sm-2 col-xs-12">Reference No:</label>
                          <?php echo $supplierGoods['reference_no'];?>
                        </div>
                    </div><br/>
                    <br>
                    <div class="form-group">
                      <div style="float: left;"><label class="control-label col-md-2 col-sm-2 col-xs-12">Supply Order No:</label>
                          <?php echo $supplierGoods['supplier_order_no'];?> 
                        </div>                        
                        <div style="float: right; width: 33%; text-align: left;"><label class="control-label col-md-2 col-sm-2 col-xs-12">Created On:</label>
                          <?php echo date('Y-m-d');?>
                        </div>
                    </div>
                  </div><br/>
                  <hr>
                  <br/>
                    
                  <div class="x_content">
                    <!-- <div class="table-responsive">-->
                      <table class="table table-striped table-bordered" border="1px" width="100%" cellpadding="1" cellspacing="0">
                        <thead>
                          <tr>     
                            <th>Sl.No. </th>
                            <th width="60%">Item (s)</th>
                           <th>Item Quantity</th>
                            <th>Item Rate (Nu)</th>
                            <th>Total Amount (Nu)</th>
                          </tr>
                        </thead>
                        <tbody>
                        <?php $i=1; ?>
                         <?php $total_item_quantity = 0; $total_item_purchasing_rate = 0; $total_item_amount = 0; ?>
                        <?php foreach ($this->suppliedGoodsList as $suppliedGoods) : ?>
                            <tr>
                                  <td width="1%"><?php echo $i; ?></td>
                                  <td><?php echo $this->escapeHtml($suppliedGoods['item_name']);?></td>
                                   <td><?php echo $this->escapeHtml($suppliedGoods['item_quantity']);?></td>
                                   <td><?php echo $this->escapeHtml($suppliedGoods['item_purchasing_rate']);?></td>
                                   <td><?php echo $this->escapeHtml($suppliedGoods['item_amount']);?></td>
                            </tr>
                         
                            <?php $i++; ?>
                            <?php 
                            $total_item_quantity += $suppliedGoods['item_quantity'];
                            $total_item_purchasing_rate += $suppliedGoods['item_purchasing_rate'];
                            $total_item_amount += $suppliedGoods['item_amount']; 
                            ?>
                         <?php endforeach; ?>
                         <tr style="border-top:1px solid #ddd;border-bottom:1px solid #ddd;">
                            <th colspan="4" style="font-size:13px"> Total : </th>
                            <th style="font-size:13px;">Nu. <?php  echo number_format((float)$total_item_amount, 2, '.', ',');?></th>
                        </tr>
                        <tr style="border-top:1px solid #ddd;border-bottom:1px solid #ddd;">
                         <th colspan="5" style="font-size:13px; text-align:left">Total: <i> (<?php  echo numtowords((string) $total_item_amount);?>)</i></th>
                        </tr>
                        </tbody>
                        
                      </table>
                     <br/>
                     <hr><br/><br/><br/>

                     <div class="form-group">
                      <div style="float: left;"><label class="control-label col-md-2 col-sm-2 col-xs-12">Verified By:</label>
                          
                        </div>                        
                        <div style="float: right; width: 33%; text-align: left;"><label class="control-label col-md-2 col-sm-2 col-xs-12">Prepared By: <?php echo $storeDetails['name'].' ('.$this->userrole.')';?></label>
                        </div>
                    </div>
                 </div>                 
             </div>
        </div> 
    </div>
</div>


