
<?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Supplier List';
 $this->headTitle($title);
?>     
<div class="right_col" role="main">
    <div class="">             
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>

                <div class="col-md-12 col-sm-12 col-xs-12" align="right">
                  <a href="<?php echo $this->url('add-item-supplier', array('action'=>'addItemSupplier')); ?>"> <button type="submit" class="btn btn-primary"><i class="fa fa-plus"></i>Add new supplier</button></a>
                </div>

                <div class="x_content">
                    <div class="table-responsive">
                        <table class="table table-striped responsive-utilities jambo_table bulk_action table-bordered">
                            <thead>
                                <tr class="headings">
                                    <th class="column-title">Sl. No</th>
                                    <th class="column-title">Supplier Name </th>
                                    <th class="column-title">Supplier TPN No </th>
                                    <th class="column-title">Supplier Bank Account No </th>
                                    <th class="column-title">Supplier Address </th>
                                    <th class="column-title">Action</th>
                                </tr>
                            </thead>

                            <tbody>
                            <?php $i=1; ?>
                            <?php foreach ($this->itemSupplier as $supplier) : ?>
                                <tr class="even pointer">
                                    <td class=" "><?php echo $i; ?></td>
                                    <td class=" "><?php echo $this->escapeHtml($supplier->getSupplier_Name()); ?></td>
                                    <td class=" "><?php echo $this->escapeHtml($supplier->getSupplier_Tpn_No()); ?></td>
                                    <td class=" "><?php echo $this->escapeHtml($supplier->getSupplier_Bank_Acc_No()); ?></td>
                                    <td class=" "><?php echo $this->escapeHtml($supplier->getSupplier_Address()); ?></td>
                                    <th class=" "><a href="<?php echo $this->url('edit-item-supplier', array('id' => $supplier->getId())); ?>"><span class="fa fa-pencil"></span></a>&nbsp;&nbsp;&nbsp;

                                           <a href="<?php echo $this->url('delete-item-supplier', array('id' => $supplier->getId())); ?>"><span class="fa fa-trash"></span></a>
                                    </th>
                                </tr>
                            <?php $i++; ?>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>