<?php

 $title = 'Offence Categories';
 $this->headTitle($title);
 
 $disciplineCategory = array();
 foreach($this->discipline as $discipline)
 {
	 $disciplineCategory['discipline_category'] = $discipline['discipline_category'];
	 $disciplineCategory['description'] = $discipline['description'];
 }
 
 ?>
<div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                  </div>
                    
                  <div class="x_content">
                    <br/>
                       <?php
						// Opening of the form tag
						$form->prepare();
						echo $this->form()->openTag($form);
						$discipline = $form->get('disciplinecategory');
						echo $this->form()->openTag($form);
						echo $this->formHidden($discipline->get('id')); 
					  ?>
                      <div class="row">    
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12"> Discipline Category: <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                              <input type="text" class="form-control" disabled="disabled" placeholder="<?php  echo $disciplineCategory['discipline_category']; ?>">
                            </div>
                        </div>
                        </div>
                        <div class="row">    
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12"> Short Description of Category: <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                              <textarea class="form-control" rows="3" disabled="disabled" placeholder='<?php  echo $disciplineCategory['description']; ?>'></textarea>
                            </div>
                        </div>
                        </div> 
                          
                        <div class="row">
                            <div class="ln_solid"></div>
                       </div>
                            <?php
                            echo $this->form()->closeTag();
                            ?>
                        </div>
                      </div>
                </div>
               </div>
            </div>
          </div>
        </div> 
     </div>