<?php
$title = 'Add Hostel';
$this->headTitle($title);
?>                      
           
               <div class="col-md-6 col-sm-12 col-xs-12">
                              <div class="x_panel">
                    
                  <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    
                  <div class="clearfix"></div>
                  </div>
              
                  <div class="x_content"><br/>
                      
                      <?php
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        
                        echo $this->formHidden($form->get('id'));
                        ?>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Hostel Type<span class="required">*</span>
                        </label>
                              <div class="col-md-9 col-sm-9 col-xs-12">
                        <?php
                        echo $this->formRow($form->get('hostel_type'));
                        ?>
                          </div>
                        </div>  
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Hostel Category<span class="required">*</span>
                        </label>
                              <div class="col-md-9 col-sm-9 col-xs-12">
                        <?php
                        echo $this->formRow($form->get('hostel_category'));
                        ?>
                          </div>
                        </div> 
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Hostel Name<span class="required">*</span>
                        </label>
                              <div class="col-md-9 col-sm-9 col-xs-12">
                        <?php
                        echo $this->formRow($form->get('hostel_name'));
                        ?>
                          </div>
                        </div> 
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Hostel Address<span class="required">*</span>
                        </label>
                              <div class="col-md-9 col-sm-9 col-xs-12">
                        <?php
                        echo $this->formRow($form->get('hostel_address'));
                        ?>
                          </div>
                        </div>  
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Hostel Phone No<span class="required">*</span>
                        </label>
                              <div class="col-md-9 col-sm-9 col-xs-12">
                        <?php
                        echo $this->formRow($form->get('hostel_contact_no'));
                        ?>
                          </div>
                        </div>  
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Provost Name<span class="required">*</span>
                        </label>
                              <div class="col-md-9 col-sm-9 col-xs-12">
                        <?php
                        echo $this->formRow($form->get('provost_name'));
                        ?>
                          </div>
                        </div> 
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Provost Address<span class="required">*</span>
                        </label>
                              <div class="col-md-9 col-sm-9 col-xs-12">
                        <?php
                        echo $this->formRow($form->get('provost_address'));
                        ?>
                          </div>
                        </div>  
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Provost Contact No<span class="required">*</span>
                        </label>
                              <div class="col-md-9 col-sm-9 col-xs-12">
                        <?php
                        echo $this->formRow($form->get('provost_contact_no'));
                        ?>
                          </div>
                        </div>  
                      
                 
                        
                    
                      <div class="ln_solid"></div>
                      <div class="form-group">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <button type="submit" class="btn btn-success"><i class="fa fa-save"></i>Save</button>
                        </div>
                      </div>
                      
                       <?php
                    echo $this->form()->closeTag();
                    ?>
                  </div>
                              </div></div>
                  
<?php
$title = 'Hostel List';
$this->headTitle($title);
?>
               <div class="col-md-6 col-sm-12 col-xs-12">
              <div class="x_panel"> 
                 <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    
                  <div class="clearfix"></div>
                  </div>
            <div class="x_content">
                              
                    <div class="table-responsive">
                      <table class="table table-striped jambo_table bulk_action"> 
                        <thead>
                          <tr class="headings">
                           <!-- <th>
                              <input type="checkbox" id="check-all" class="flat">
                            </th>-->
                            <th class="column-title">SL No </th>
                            <th class="column-title">Hostel Name</th>
                            <th class="column-title">Hostel Type</th>
                            <th class="column-title">Hostel Category</th>
                            <th class="column-title no-link last"><span class="nobr">Action</span>
                            </th>
                            <th class="bulk-actions" colspan="7">
                              <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                            </th>
                          </tr>
                        </thead>
                        
                        <tbody>
                     
                                                  
                        </tbody>
                          </table>
                      
                    </div>
            </div></div></div>
                          
                  

                        
                      
            
         
              
       
                