<?php
 $title = 'Edit Current Withdrawal Budget Details';
 $this->headTitle($title);
 $budgetDetail = array();
 foreach ($this->withdrawalBudget as $key=>$value){
	 $budgetDetail[$key] = $value;
 }
?>
<div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title)?></h2>
                   <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                    </ul> 
                 <div class="clearfix"></div>
                </div>
                  <div class="x_content">
                	<br/>
                     <?php
                        // Opening of the form tag
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        $form->get('id')->setValue($this->id);
                        $form->get('reference_no')->setValue($budgetDetail[0]['reference_no']);
                        $reference_date = explode("-", $budgetDetail[0]['reference_date']);
                        $form->get('reference_date')->setValue($reference_date[01].'/'.$reference_date[02].'/'.$reference_date[00]);
                        $form->get('reasons')->setValue($budgetDetail[0]['reasons']);
                        $form->get('amount')->setValue($budgetDetail[0]['amount']);
                        $form->get('budget_type')->setValue($budgetDetail[0]['budget_type']);
                        $form->get('from_proposal_id')->setValue($budgetDetail[0]['from_proposal_id']);
                        $form->get('status')->setValue($budgetDetail[0]['status']);
                        $form->get('organisation_id')->setValue($budgetDetail[0]['organisation_id']);
                        $form->get('submit')->setValue('Update');
                        echo $this->formHidden($form->get('budget_type'));
                        echo $this->formHidden($form->get('from_proposal_id'));
                        echo $this->formHidden($form->get('status'));
                        echo $this->formHidden($form->get('organisation_id'));
                        echo $this->formHidden($form->get('id'));
					            ?>
                    <div class="row">    
                          <div class="form-group">
                            <label class="control-label col-md-2 col-sm-3 col-xs-12">Budget Ledger Head<span class="required">*</span></label>
                            <div class="col-md-8 col-sm-6 col-xs-12">
                              <input type="text" class="form-control" disabled="disabled" placeholder="<?php  echo $budgetDetail[0]['ledger_head']; ?>">
                            </div>
                          </div>
                          <div class="form-group">
                            <label class="control-label col-md-2 col-sm-3 col-xs-12">Accounts Group Head<span class="required">*</span></label>
                            <div class="col-md-8 col-sm-6 col-xs-12">
                              <input type="text" class="form-control" disabled="disabled" placeholder="<?php  echo $budgetDetail[0]['group_head']; ?>">
                            </div>
                          </div>
                          <div class="form-group">
                            <label class="control-label col-md-2 col-sm-3 col-xs-12">Chart of Accounts<span class="required">*</span></label>
                            <div class="col-md-8 col-sm-6 col-xs-12">
                              <input type="text" class="form-control" disabled="disabled" placeholder="<?php  echo $budgetDetail[0]['head_of_accounts']; ?>">
                            </div>
                          </div>
                     </div>
                     <div class="row">
                        <div class="form-group">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12">Reference No<span class="required">*</span></label>
                            <div class="col-md-3 col-sm-3 col-xs-12">
                                <?php  echo $this->formRow($form->get('reference_no')); ?>
                            </div>
                            <label class="control-label col-md-2 col-sm-2 col-xs-12">Reference Date<span class="required">*</span></label>
                            <div class="col-md-3 col-sm-3 col-xs-12">
                                <?php  echo $this->formRow($form->get('reference_date')); ?>
                            </div>
                        </div>
                     </div>
                     <div class="row">
                        <div class="form-group"> 
                            <label class="control-label col-md-2 col-sm-2 col-xs-12">Reasons<span class="required">*</span> </label>
                            <div class="col-md-8 col-sm-8 col-xs-12">
                                <?php  echo $this->formRow($form->get('reasons')); ?>
                           </div>
                        </div>
                     </div>
                     <div class="row">
                        <div class="form-group">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12">Approved Budget<span class="required">*</span></label>
                            <div class="col-md-3 col-sm-3 col-xs-12">
                              <input type="text" class="form-control" disabled="disabled" placeholder="<?php  echo $budgetDetail[0]['budget_amount_approved']; ?>">
                            </div>
                            <label class="control-label col-md-2 col-sm-2 col-xs-12">Balance<span class="required">*</span></label>
                            <div class="col-md-3 col-sm-3 col-xs-12">
                              <input type="text" class="form-control" disabled="disabled" placeholder="<?php  echo $budgetDetail[0]['balance']; ?>">
                            </div>
                        </div>
                     </div>
                     <div class="row">
                        <div class="form-group">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12">Expenditure<span class="required">*</span></label>
                            <div class="col-md-3 col-sm-3 col-xs-12">
                              <input type="text" class="form-control" disabled="disabled" placeholder="<?php  echo 'Expenditure'; ?>">
                            </div>
                            <label class="control-label col-md-2 col-sm-2 col-xs-12">Withdrawal Budget<span class="required">*</span></label>
                            <div class="col-md-3 col-sm-3 col-xs-12">
                                <?php  echo $this->formRow($form->get('amount')); ?>
                            </div>
                        </div>
                     </div>
                     <div class="row">
                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                <?php
                                    echo $this->formHidden($form->get('csrf'));
                                    echo $this->formSubmit($form->get('submit')); 
                                    echo $this->form()->closeTag();
                                    ?>
                                </div>
                            </div>
                       </div>
                        </div>
                      </div>
                </div>

             </div>
           </div>
          </div>
        </div> 
     </div>
     
     