<?php
 $title = 'List of Capital Withdrawal Budget College/ OVC Budgeting Officer';
 $this->headTitle($title);

 $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    //IDEA-CBC
    //Original
    //$iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('aes-256-cbc'));

    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));

    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                <?php 
                    if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                        echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                        echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                        $messages = $this->flashMessenger()->getMessages();
                        foreach($messages as $message) {
                            echo '<strong>Success!</strong>'. $message;
                        }
                        echo '</div>';
                    }

                    else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                        echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                        echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                        $messages = $this->flashMessenger()->getMessages();
                        foreach($messages as $message) {
                            echo '<strong>Failure!</strong>'. $message;
                        }
                        echo '</div>';
                    }

                ?>
                     <div class="table-responsive">
                      <table id="datatable" class="table table-striped responsive-utilities jambo_table bulk_action table-bordered">
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Sl. No</th>
                            <th class="column-title">Activity Name</th>
                            <th class="column-title">Broad Head Name</th>
                            <th class="column-title">Object Code</th>
                            <th class="column-title">Approved Amount</th>
                            <th class="column-title">Supplementary Amount</th>
                            <th class="column-title">Status</th>
                            <th class="column-title">Action</th>
                          </tr>
                        </thead>  
                        <tbody>
                         <?php $i = 1; foreach ($this->budgetWithdrawal as $budget) : ?>
                          <tr class="even pointer">
                            <td class=" "><?php echo $i++;?></td>
                            <td class=" "><?php echo $this->escapeHtml($budget['activity_name']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($budget['broad_head_name']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($budget['object_name']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($budget['budget_amount_approved']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($budget['amount']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($budget['status']);?></td>
                            <td class=" last">
                            <?php if($budget['status'] == 'Submitted'){ ?>
                            <a href="<?php echo $this->url('editcapitalbudgetwithdrawal', array('id' => my_encrypt($budget['id'], $key)));?>" class="btn btn-success btn-xs"><i class="fa fa-pencil"></i> Edit</a>
                            <?php } ?>
                              <a href="<?php echo $this->url('viewcapitalbudgetwithdrawal', array('id' => my_encrypt($budget['id'], $key)));?>" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> View Details</a>
                              </td>
                          </tr>
                          <?php endforeach; ?>
                      </tbody>
                      </table>
                     </div>
                  </div>
               </div>
             </div>
        
        
    
          </div>
        </div> 
     </div>
