<?php
 $title = 'Add Budget Ledger';
 $this->headTitle($title);
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                  </ul>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				    $ledger = $form->get('budgetledger');
                    echo $this->form()->openTag($form);
					$ledger->get('organisation_id')->setValue($this->organisation_id);
					$ledger->get('departments_id')->setValue('1');
                    echo $this->formHidden($ledger->get('id'));
				  ?>  
                <div class="row">    
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">OVC/College</label>
                    <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($ledger->get('organisation_id')); ?>
                    </div>
                    <label class="control-label col-md-2 col-sm-3 col-xs-12">Office/Department</label>
                    <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($ledger->get('departments_id')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Programme (Ledger Name)<span class="required">*</span></label>
                    <div class="col-md-7 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($ledger->get('ledger_head')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Remarks<span class="required">*</span></label>
                    <div class="col-md-7 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($ledger->get('remarks')); ?>
                    </div>
                  </div>
                </div> 
                  
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
						<?php
						   echo $this->formHidden($form->get('csrf'));
						   echo $this->formSubmit($ledger->get('submit')); 
                        ?>
                    	</div>
                    </div>
               </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                </div>
              </div>

        
        <!-- Start of table listing budget ledgers -->
        <div class="x_panel">
            <div class="x_title">
                  <h2><?php echo $this->escapeHtml('Budget Ledger'); ?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                  </ul>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                     <div class="table-responsive">
                      <table class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Sl. No. </th>
                            <th class="column-title">University / College </th>
                            <th class="column-title">Office / Dept. </th>
                            <th class="column-title">Programme / Ledger Name</th>
                            <th class="column-title">Action</th>
                          </tr>
                        </thead>  
                        <tbody>
                      <tr>
                         <?php $i =1; foreach ($this->ledgerHeads as $ledgerHead) : ?>
                          <tr class="even pointer">
                            <td class=" "><?php echo $i++; ?></td>
                            <td class=" "><?php echo $this->escapeHtml($ledgerHead['organisation_name']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($ledgerHead['department_name']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($ledgerHead['ledger_head']);?></td>
                            <td class=" last"><a href="<?php echo $this->url('viewbudgetledger', array('id' => $ledgerHead['id']));?>" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i>View</a>
                            	<a href="<?php echo $this->url('editbudgetledger', array('id' => $ledgerHead['id']));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a>
                                <a href="<?php echo $this->url('deletebudgetledger', array('id' => $ledgerHead['id']));?>" class="btn btn-danger btn-xs"><i class="fa fa-thrash-o"></i>Delete</a></td>
                          </tr>
                          <?php endforeach; ?>
                      </tr>
                      </tbody>
                      </table>
                     </div>
                 </div>
              </div>
    
          </div>
        </div> 
     </div>
    </div>
   </div>
   