<?php
 $title = 'Budget Re-Appropriation Proposal (College Finance Officer)';
 $this->headTitle($title);
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                  </ul>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                  <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				    $proposal = $form->get('budgetproposal');
                    echo $this->form()->openTag($form);
                    echo $this->formHidden($proposal->get('id')); 
					$proposal->get('five_year_plan')->setValue('12th Five Year Plan');
					$proposal->get('departments_id')->setValueOptions($this->departments);
					$proposal->get('organisation_id')->setValue('College of Science and Technology');
					$proposal->get('budget_proposal_status')->setValue('Not Submitted');
					$proposal->get('budget_ledger_head_id')->setValueOptions($this->ledgerHeads);
					$proposal->get('accounts_group_head_id')->setValueOptions($this->accountGroupHeads);
					$proposal->get('chart_of_accounts_id')->setValueOptions($this->chartAccounts);
				  ?>
                  <div class="row">    
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Budget Type<span class="required">*</span></label>
                        <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                        <?php  echo $this->formRow($proposal->get('budget_type')); ?>
                        </div>
                        <label class="control-label col-md-2 col-sm-3 col-xs-12">Proposed Budget (Amount)<span class="required">*</span></label>
                        <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                        <?php  echo $this->formRow($proposal->get('proposed_budget_amount')); ?>
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Write Up<span class="required">*</span></label>
                        <div class="col-md-7 col-sm-6 col-xs-12">
                          <?php  echo $this->formRow($proposal->get('write_up')); ?>
                        </div>
                      </div>
                 </div> 
                <!--start of reappropriation details -->
                <div class="x_panel">
                <div class="x_title">
                  <h2><i><?php echo $this->escapeHtml('Reappropriation From Details'); ?></i></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                  </ul>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				    $proposal = $form->get('budgetproposal');
                    echo $this->form()->openTag($form);
                    echo $this->formHidden($proposal->get('id')); 
					$proposal->get('five_year_plan')->setValue('12th Five Year Plan');
					$proposal->get('departments_id')->setValueOptions($this->departments);
					$proposal->get('organisation_id')->setValue('College of Science and Technology');
					$proposal->get('budget_proposal_status')->setValue('Not Submitted');
					$proposal->get('budget_ledger_head_id')->setValueOptions($this->ledgerHeads);
					$proposal->get('accounts_group_head_id')->setValueOptions($this->accountGroupHeads);
					$proposal->get('chart_of_accounts_id')->setValueOptions($this->chartAccounts);
				  ?>  
                <div class="row">    
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Five Year Plan</label>
                    <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($proposal->get('five_year_plan')); ?>
                    </div>
                    <label class="control-label col-md-2 col-sm-3 col-xs-12">Financial Year</label>
                    <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($proposal->get('financial_year')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">OVC/College</label>
                    <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($proposal->get('organisation_id')); ?>
                    </div>
                    <label class="control-label col-md-2 col-sm-3 col-xs-12">Office/Department</label>
                    <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($proposal->get('departments_id')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Programme (Ledger Name)<span class="required">*</span></label>
                    <div class="col-md-7 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($proposal->get('budget_ledger_head_id')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Activity / Accounts Group Head<span class="required">*</span></label>
                    <div class="col-md-7 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($proposal->get('accounts_group_head_id')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Chart of Accounts<span class="required">*</span></label>
                    <div class="col-md-7 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($proposal->get('chart_of_accounts_id')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Budget Type<span class="required">*</span></label>
                    <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($proposal->get('budget_type')); ?>
                    </div>
                    <label class="control-label col-md-2 col-sm-3 col-xs-12">Proposed Budget (Amount)<span class="required">*</span></label>
                    <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($proposal->get('proposed_budget_amount')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Write Up<span class="required">*</span></label>
                    <div class="col-md-7 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($proposal->get('write_up')); ?>
                    </div>
                  </div>
                </div> 
                  
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                </div>
              </div>
              <!-- End of Reappropriation From Details box-->
              
              <div class="x_panel">
                <div class="x_title">
                  <h2><i><?php echo $this->escapeHtml('Reappropriation To Details'); ?></i></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                  </ul>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				    $proposal = $form->get('budgetproposal');
                    echo $this->form()->openTag($form);
                    echo $this->formHidden($proposal->get('id')); 
					$proposal->get('five_year_plan')->setValue('12th Five Year Plan');
					$proposal->get('departments_id')->setValueOptions($this->departments);
					$proposal->get('organisation_id')->setValue('College of Science and Technology');
					$proposal->get('budget_proposal_status')->setValue('Not Submitted');
					$proposal->get('budget_ledger_head_id')->setValueOptions($this->ledgerHeads);
					$proposal->get('accounts_group_head_id')->setValueOptions($this->accountGroupHeads);
					$proposal->get('chart_of_accounts_id')->setValueOptions($this->chartAccounts);
				  ?>  
                <div class="row">    
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Five Year Plan</label>
                    <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($proposal->get('five_year_plan')); ?>
                    </div>
                    <label class="control-label col-md-2 col-sm-3 col-xs-12">Financial Year</label>
                    <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($proposal->get('financial_year')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">OVC/College</label>
                    <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($proposal->get('organisation_id')); ?>
                    </div>
                    <label class="control-label col-md-2 col-sm-3 col-xs-12">Office/Department</label>
                    <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($proposal->get('departments_id')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Programme (Ledger Name)<span class="required">*</span></label>
                    <div class="col-md-7 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($proposal->get('budget_ledger_head_id')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Activity / Accounts Group Head<span class="required">*</span></label>
                    <div class="col-md-7 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($proposal->get('accounts_group_head_id')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Chart of Accounts<span class="required">*</span></label>
                    <div class="col-md-7 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($proposal->get('chart_of_accounts_id')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Budget Type<span class="required">*</span></label>
                    <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($proposal->get('budget_type')); ?>
                    </div>
                    <label class="control-label col-md-2 col-sm-3 col-xs-12">Proposed Budget (Amount)<span class="required">*</span></label>
                    <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($proposal->get('proposed_budget_amount')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Write Up<span class="required">*</span></label>
                    <div class="col-md-7 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($proposal->get('write_up')); ?>
                    </div>
                  </div>
                </div> 
                  
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                </div>
              </div>
                   <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
						<?php
                           echo $this->formHidden($proposal->get('budget_proposal_status'));
						   echo $this->formHidden($form->get('csrf'));
						   echo $this->formSubmit($proposal->get('submit')); 
                        ?>
                    	</div>
                    </div>
               </div>
              
              <!-- End of Reappropriation To Details-->
             </div>
        </div>
       
              	
    
          </div>
        </div> 
     </div>