<?php
 $title = 'Generate Student ID by programme wise';
 $this->headTitle($title);
?>

 <div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
            
                <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                     <div class="clearfix"></div>
                    </div>
                    <br/> 
                    <div class="col-md-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2><?php echo $this->escapeHtml("Select programme to generate student ID in Bulk")?></h2>
                            <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                            </ul>
                            <div class="clearfix"></div>
                  
                        </div>

                        <?php 
                          if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                              echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                              echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                              $messages = $this->flashMessenger()->getMessages();
                              foreach($messages as $message) {
                                  echo '<strong>Success!</strong>'. $message;
                              }
                              echo '</div>';
                          }

                          else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                              echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                              echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                              $messages = $this->flashMessenger()->getMessages();
                              foreach($messages as $message) {
                                  echo '<strong>Failure!</strong>'. $message;
                              }
                              echo '</div>';
                          }
                      ?>
                       
                        <div class="x_content">
                            <h5><i>In order to generate student ID for those who have reported to the college, you have to select programme from drop down list and Click on Generate Bulk Student ID button to generate student ID by programme wise. Generation of Student ID is based on programme wise in alphabetical order of current year. Once student ID has been generated you can't generate again and again for particular student or students of particular programme. <br/><br/>
                            *** At the same time their USERNAME and PASSWORD will be also generated ***</i></h5>
                                  <br />
                            <?php
                            // Opening of the form tag
                            $form->prepare();
                            echo $this->form()->openTag($form);
                            ?>
                        
                            <div class="row">
                                <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Programme</label>
                                    <?php echo $this->formRow($form->get('programmes_id')); ?>
                                </div>
                            </div>                         
                            <div class="row">
                                <div class="ln_solid"></div>
                                <div class="form-group">
                                    <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                                      <?php
                                       echo $this->formHidden($form->get('csrf'));
                                       echo $this->formSubmit($form->get('submit')); 
                                       echo $this->form()->closeTag(); 
                                    ?>
                                </div>
                            </div>                          
                        </div>
                    </div>
                </div>   
                              
                          
                        <div class="col-md-12 col-sm-12 col-xs-12">
                          <div class="x_panel">
                            <div class="x_title">
                              <h2><?php echo $this->escapeHtml("List of Student(s) with new generated Student ID"); ?></h2>
                              <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                </li>
                              </ul>
                              <div class="clearfix"></div>
                              <h5><i>List of Students with new generated student ID. At the same <b>USERNAME</b> and <b>PASSWORD</b> of each student has been generated. Please provide them their <b>USERNAME</b> and <b>PASSWORD</b>. <b>USERNAME:-</b> Newly generated <b> STUDENT ID</b> and <b>PASSWORD:-</b> Newly generated <b> STUDENT ID</b></i></h5>
                                  <br />
                            </div>
            
                            <div class="x_content">
                              <div  class="table-responsive">
                                <table id="datatable-buttons" class="table table-striped responsive-utilities jambo_table bulk_action table-bordered">
                                  <thead>
                                      <th class="column-title">Sl No </th>
                                      <th class="column-title">Student Name </th>
                                      <th class="column-title">Student ID </th>
                                      <th class="column-title">CID </th>
                                      <th class="column-title">DOB </th>
                                      <th class="column-title">Gender </th>
                                      <th class="column-title">Programme </th>
                                      <th class="column-title">Admission Year </th>
                                      <th class="column-title">Scholarship Type </th>
                                  </thead>
              
                                  <tbody>
                                  <?php $i=1; ?>
                                    <?php foreach ($this->generatedStudentIdList as $studentList) : ?>
                                    <tr class="even pointer">
                                      <td class=" " width="5%"><?php echo $i; ?></td>
                                      <td class=" " width="20%"><?php echo $this->escapeHtml($studentList['first_name']) . ' ' .
                                                               $this->escapeHtml($studentList['middle_name']) . ' ' .
                                                               $this->escapeHtml($studentList['last_name']);?></td>
                                      <td class=" " width="12%"><?php echo $this->escapeHtml($studentList['student_id']);?></td>
                                      <td class=" " width="12%"><?php echo $this->escapeHtml($studentList['cid']);?></td>
                                      <td class=" " width="10%"><?php echo $this->escapeHtml($studentList['date_of_birth']); ?></td>
                                      <td class=" " width="5%"><?php echo $this->escapeHtml($studentList['gender']); ?></td>
                                      <td class=" " width="30%"><?php echo $this->escapeHtml($studentList['programme_name']); ?></td>
                                      <td class=" " width="8%"><?php echo $this->escapeHtml($studentList['enrollment_year']); ?></td>
                                      <td class=" " width="10%"><?php echo $this->escapeHtml($studentList['student_type']); ?></td>
                                    </tr>
                                    <?php $i++; ?>
                                    <?php endforeach; ?>
                                  </tbody>
                                </table>
                              </div>
                            </div>
                          </div>
                        </div>
                        </div>
                      </div>
                  </div>
                </div>
              
