<?php

 $title = 'Edit Employee Task Record';
 $this->headTitle($title);
 $employeetaskRecord['from_date']='';
 $employeetaskRecord['to_date']= '';
 $employeetaskRecord = array();
 foreach($this->employeetask as $employeetask)
 {
  $employeetaskRecord['id'] = $employeetask['id'];
  $employeetaskRecord['staff_id'] = $employeetask['staff_id'];
  $employeetaskRecord['employeetask_type'] = $employeetask['employeetask_type'];
  $employeetaskRecord['employeetask_category_id'] = $employeetask['employeetask_category_id'];
   $employeetaskRecord['employeetask_details'] = $employeetask['employeetask_details'];
   //$employeetaskRecord['record_date'] = $employeetask['record_date'];
   $employeetaskRecord['from_date'] = date("m-d-Y", strtotime(substr($employeetask['from_date'],0,10)));
   $employeetaskRecord['to_date'] = date("m-d-Y", strtotime(substr($employeetask['to_date'],0,10)));
   $employeetaskRecord['from_time'] = $employeetask['from_time'];
   $employeetaskRecord['to_time'] = $employeetask['to_time'];
   $employeetaskRecord['status'] = $employeetask['status'];
   $employeetaskRecord['recorded_by'] = $employeetask['recorded_by'];
   $employeetaskRecord['evidence_file'] = $employeetask['evidence_file'];
   
 }
 ?>
<div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                  </div>
                  <?php 
                            if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                                echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                $messages = $this->flashMessenger()->getMessages();
                                foreach($messages as $message) {
                                    echo '<strong>Success!</strong>'. $message;
                                }
                                echo '</div>';
                            }

                            else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                                echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                $messages = $this->flashMessenger()->getMessages();
                                foreach($messages as $message) {
                                    echo '<strong>Failure!</strong>'. $message;
                                }
                                echo '</div>';
                            }
                        ?>
                    
                  <div class="x_content">
                    <br/>
                       <?php
                        //get the EmployeetaskCategory ID with their id
                        //$data = $this->selectData;
                        //$employeetask->get('employeetask_category_id')->setValueOptions($data);
                        // Opening of the form tag
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        $employeetask = $form->get('employeetask');
                        echo $this->form()->openTag($form);
                        $employeetask->get('id')->setValue($this->id);
                        //$employeetask->get('id')->setValue($employeetaskRecord['id']);
                        $employeetask->get('staff_id')->setValue($employeetaskRecord['staff_id']);
                        echo $this->formHidden($employeetask->get('staff_id'));
                        $employeetask->get('employeetask_type')->setValue($employeetaskRecord['employeetask_type']);
                        echo $this->formHidden($employeetask->get('employeetask_type'));
                        
                        $employeetask->get('employeetask_category_id')->setValue($employeetaskRecord['employeetask_category_id']);
                        echo $this->formHidden($employeetask->get('employeetask_category_id'));
                        $employeetask->get('employeetask_details')->setValue($employeetaskRecord['employeetask_details']);
                        $employeetask->get('from_date')->setValue($employeetaskRecord['from_date']);
                        $employeetask->get('to_date')->setValue($employeetaskRecord['to_date']);
                        //echo $this->formHidden($employeetask->get('record_date'));
                        $employeetask->get('from_time')->setValue($employeetaskRecord['from_time']);
                        $employeetask->get('to_time')->setValue($employeetaskRecord['to_time']);
                        $employeetask->get('status')->setValue($employeetaskRecord['status']);
                        $employeetask->get('recorded_by')->setValue($employeetaskRecord['recorded_by']);
                        echo $this->formHidden($employeetask->get('recorded_by'));
                        echo $this->formHidden($employeetask->get('id')); 
                        
                        ?>
                    <div class="row">
                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">APA/Task/Project Activity Details <span class="required">*</span>
                        </label>
                        <div class="col-md-8 col-sm-8 col-xs-12">
                          <?php 
                         echo $this->formRow($employeetask->get('employeetask_details'));
                        ?>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">From Date<span class="required">*</span></label>
                        <div class="col-md-2 col-sm-2 col-xs-12">
                          <?php
                          echo $this->formRow($employeetask->get('from_date'));
                          ?>
                        </div>
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">To Date<span class="required">*</span></label>
                        <div class="col-md-2 col-sm-2 col-xs-12">
                          <?php
                          echo $this->formRow($employeetask->get('to_date'));
                          ?>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">From Time<span class="required">*</span></label>
                        <div class="col-md-2 col-sm-2 col-xs-12">
                          <?php
                          echo $this->formRow($employeetask->get('from_time'));
                          ?>
                        </div>
                        <label class="control-label col-md-2  col-sm-2 col-xs-12">To Time<span class="required">*</span></label>
                        <div class="col-md-2 col-sm-2 col-xs-12">
                          <?php
                          echo $this->formRow($employeetask->get('to_time'));
                          ?>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="form-group">
                        <label class="control-label col-md-2  col-sm-2 col-xs-12">Status<span class="required">*</span></label>
                        <div class="col-md-4 col-sm-2 col-xs-12">
                          <?php
                          echo $this->formRow($employeetask->get('status'));
                          ?>
                        </div>
                        <?php
                          if($employeetaskRecord['evidence_file']) {
                            $employeetask->get('evidence_file')->setValue($employeetaskRecord['evidence_file']);
                            echo $this->formHidden($employeetask->get('evidence_file'));
                          }
                          else{ ?>
                          <label class="control-label col-md-2 col-sm-3 col-xs-12">Scanned Copy of Pass Certificate<span class="required">*</span></label>
                          <div class="col-md-4 col-sm-12 col-xs-12 form-group">
                          <?php
                           echo $this->formRow($employeetask->get('evidence_file'));
                          }
                          ?>
                        </div>
                      </div>
                    </div>
                  </div>
                    <div class="ln_solid"></div>
                    <div class="row">
                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                        <?php
                          echo $this->formRow($form->get('csrf'));
                          echo $this->formSubmit($employeetask->get('submit')); 
                        ?>
                        </div>
                    </div>
                    </div>  
                            <?php
                            echo $this->form()->closeTag();
                            ?>
                        </div>
                      </div>
                </div>
              
                
                 </div>
            </div>
          </div>
        </div> 
     </div>