<?php
 $title = 'Staff Details';
 $this->headTitle($title);
 
 $staffDetail = array();
 foreach($this->staffGoodsRequisition as $goodsRequisition)
 {
     $staffDetail['name'] = $goodsRequisition['first_name'] . ' '. $goodsRequisition['middle_name'] . ' ' .$goodsRequisition['last_name'];
     $staffDetail['emp_id'] = $goodsRequisition['emp_id'];
     $staffDetail['department_name'] = $goodsRequisition['department_name'];
     $staffDetail['unit_name'] = $goodsRequisition['unit_name'];
 }

 $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    //IDEA-CBC
    //Original
    //$iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('aes-256-cbc'));

    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));

    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}

 ?>
<div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                  </div>
                    
                  <div class="x_content">
                    <br/>
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
                            $staffDetails = $form->get('goodsrequisitionapproval');
                    echo $this->form()->openTag($form);
                    $staffDetails->get('emp_id')->setValue($this->id);
                            echo $this->formHidden($staffDetails->get('id'));
                            echo $this->formHidden($staffDetails->get('emp_id'));
                    
                  ?>  
                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Staff Name</label>
                        <div class="col-md-3 col-sm-3 col-xs-12">
                            <input type="text" placeholder="<?php echo $staffDetail['name']; ?>" class="form-control col-md-7 col-xs-12" disabled="disabled">
                        </div>
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Staff ID</label>
                        <div class="col-md-3 col-sm-3 col-xs-12">
                            <input type="text" placeholder="<?php echo $staffDetail['emp_id']; ?>" class="form-control col-md-7 col-xs-12" disabled="disabled">
                        </div>
                      </div>
                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Depatment</label>
                        <div class="col-md-3 col-sm-3 col-xs-12">
                            <input type="text" placeholder="<?php echo $staffDetail['department_name']; ?>" class="form-control col-md-7 col-xs-12" disabled="disabled">
                        </div>
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Department Unit</label>
                        <div class="col-md-3 col-sm-3 col-xs-12">
                            <input type="text" placeholder="<?php echo $staffDetail['unit_name']; ?>" class="form-control col-md-7 col-xs-12" disabled="disabled">
                        </div>
                      </div>              
                   
                    <div class="ln_solid"></div>
                   <?php
                    echo $this->form()->closeTag();
                    ?>
                       
                    
                  </div>
                </div>

                <!-- Start of table listing item to issue -->
                <div class="x_panel">
                  <div class="x_title">
                    <h2><?php echo $this->escapeHtml('Goods Requisition List Details'); ?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <h5><i>*The following are the list of the item applied for requisition by above particualr selected staff</i></h5>
                  <br />
                  <?php 
                  ?>
                  <div class="x_content">
                     <div class="table-responsive">
                      <table id="datatable" class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">     
                            <th class="column-title">Sl.No. </th>
                            <th class="column-title">Item Name</th>
                            <th class="column-title">Quantity Type</th>
                            <th class="column-title">Quantity</th>
                            <th class="column-title">Applied Date</th>
                            <th class="column-title">Action</th>
                          </tr>
                        </thead>
                        <tbody>
                        <?php $i=1; ?>
                        <?php foreach ($this->staffGoodsRequisitionList as $goodsRequisitionList) : ?>
                            <tr>
                                 <td class=" "><?php echo $i; ?></td>
                                   <td class=" "><?php echo $this->escapeHtml($goodsRequisitionList['item_name']);?></td>
                                   <td class=" "><?php echo $this->escapeHtml($goodsRequisitionList['item_quantity_type']);?></td>
                                   <td class=" "><?php echo $this->escapeHtml($goodsRequisitionList['requisition_item_quantity']);?></td>
                                   <td class=" "><?php echo $this->escapeHtml($goodsRequisitionList['requisition_date']);?></td>
                                    <td class="last" width="12%"> <a href="<?php echo $this->url('requisition-approval', array('id' => my_encrypt($goodsRequisitionList['id'], $key)));?>" class="btn btn-primary btn-xs"><i class="fa fa-eye"></i> View </button></a>
                                      <a href="<?php echo $this->url('approvegoodsrequisition', array('id' => my_encrypt($goodsRequisitionList['id'], $key)));?>" class="btn btn-success btn-xs"> Approve </button></a>
                                    </td>
                                                                       
                            </tr>
                            <?php $i++; ?>
                         <?php endforeach; ?>
                        </tbody>
                      </table>
                     </div>
                 </div>
             </div>
              </div>
           </div>
         </div>
