<?php
 $title = 'Capital Budget Re-Appropriation Proposal (College Finance Officer)';
 $this->headTitle($title);
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                  </ul>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                      <!-- blockquote -->
                      <blockquote>
                        <h4><i>Please select the "Reappropriation From" and "Reappropriation To" fields. Once you have selected the "From" and "To" Details,
                  			you will be able to select the Chart of Accounts and reappropriate the approved budget amount.</i></h4>
                      </blockquote>
                      <br />
                <!--start of reappropriation details -->
                <div class="x_panel">
                <div class="x_title">
                  <h2><i><?php echo $this->escapeHtml('Reappropriation Details'); ?></i></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                  </ul>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                   <?php
                    // Opening of the form tag
                    $form->setAttribute();
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    //need to get the organisation id
                    $form->get('organisation_id')->setValue($this->organisation_id);
                    ?>
                
                <h2><i><u><?php echo $this->escapeHtml('Reappropriation From Details'); ?></u></i></h2>
                <div class="row">    
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Activity Name<span class="required">*</span></label>
                    <div class="col-md-7 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($form->get('from_activity_name_id')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Broad Head Name<span class="required">*</span></label>
                    <div class="col-md-7 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($form->get('from_broad_head_name_id')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Object Code<span class="required">*</span></label>
                    <div class="col-md-7 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($form->get('from_object_code_id')); ?>
                    </div>
                  </div>
                </div>
                <br />
                <h2><i><u><?php echo $this->escapeHtml('Reappropriation To Details'); ?></u></i></h2>
                 <div class="row">    
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Activity Name<span class="required">*</span></label>
                    <div class="col-md-7 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($form->get('to_activity_name_id')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Broad Head Name<span class="required">*</span></label>
                    <div class="col-md-7 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($form->get('to_broad_head_name_id')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Object Code<span class="required">*</span></label>
                    <div class="col-md-7 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($form->get('to_object_code_id')); ?>
                    </div>
                  </div>
                </div> 

                </div>
              </div>
              <!-- End of Reappropriation From Details box-->
              
                 
                   <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                        <?php
                           echo $this->formHidden($form->get('organisation_id'));
                           echo $this->formHidden($form->get('csrf'));
                           echo $this->formSubmit($form->get('submit'));
                           echo $this->form()->closeTag(); 
                        ?>
                    	</div>
                    </div>
               </div>
              
              <!-- End of Reappropriation To Details-->
             </div>
                
             
        </div>
          </div>
              
          <!-- After the submission of the form -->  
          <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                  </ul>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                  <?php
                    // Opening of the form tag
                    $budgetForm->setAttribute('action', $this->url('updatecapitalbudgetreappropriation', array('action' => 'updateCapitalBudgetReappropriation')));
                    $budgetForm->prepare();
                    echo $this->form()->openTag($budgetForm);
					
                    ?>
                  <div class="row">    
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Reference No<span class="required">*</span></label>
                        <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                        <?php  echo $this->formRow($budgetForm->get('reference_no')); ?>
                        </div>
                        <label class="control-label col-md-2 col-sm-3 col-xs-12">Reference Date<span class="required">*</span></label>
                        <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                        <?php  echo $this->formRow($budgetForm->get('reference_date')); ?>
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Purpose<span class="required">*</span></label>
                        <div class="col-md-7 col-sm-6 col-xs-12">
                          <?php  echo $this->formRow($budgetForm->get('purpose')); ?>
                        </div>
                      </div>
                 </div>
                 <br />
                <!--start of reappropriation details -->
                <div class="x_panel">
                <div class="x_title">
                  <h2><i><?php echo $this->escapeHtml('Reappropriation From Details: '); ?></i></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                  </ul>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                <h5><i>**Please note that any empty or zero values will be ignored.</i></h5>
                  <br />
                    <table class="table table-bordered">
                            <thead>
                              <tr class="headings">
                                <th class="column-title">Activity Name</th>
                                <th class="column-title">Broad Head Name</th>
                                <th class="column-title">Object Code</th>
                                <th class="column-title">Budget</th>
                                <th class="column-title">Expenditure</th>
                                <th class="column-title">Balance</th>
                                <th class="column-title">Amount To Reappropriate</th>
                              </tr>
                            </thead>
                            <tbody>
                          <tr>
                             <?php $i =0; foreach ($this->fromDataDetails as $data) : ?>
                              <tr class="even pointer">
                                <td class=" "><?php echo $this->escapeHtml($data['activity_name']);?></td>
                                <td class=" "><?php echo $this->escapeHtml($data['broad_head_name_id']);?></td>
                                <td class=" "><?php echo $this->escapeHtml($data['object_code_id']);?></td>
                                <td class=" "><?php echo $this->escapeHtml($data['budget_amount_approved']);?></td>
                                <td class=" "><?php echo "expenditure"; ?></td>
                                <td class=" "><?php echo $this->escapeHtml($data['balance']);?></td>
                                <td class=" "><?php echo $this->formRow($budgetForm->get('to_proposal_id')); ?></td>
                              </tr>
                              <?php endforeach; ?>
                          </tr>
                         </tbody>
                       </table>
                </div>
              </div>
              <br />
              <!-- End of Reappropriation From Details box-->
              
                  <div class="x_panel">
                    <div class="x_title">
                      <h2><i><?php echo $this->escapeHtml('Reappropriation To Details:'); ?></i></h2>
                      <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                      </ul>
                     <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                    <h5><i>**Please note that any empty or zero values will be ignored.</i></h5>
                      <br />
                    <table class="table table-bordered">
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Activity Name</th>
                            <th class="column-title">Broad Head Name</th>
                            <th class="column-title">Object Code</th>
                            <th class="column-title">Budget</th>
                            <th class="column-title">Expenditure</th>
                            <th class="column-title">Balance</th>
                            <th class="column-title">Amount to Reappropriate</th>
                          </tr>
                        </thead>  
                        <tbody>
                      <tr>
                         <?php $i =0; foreach ($this->toDataDetails as $data) : ?>
                          <tr class="even pointer">
                                <td class=" "><?php echo $this->escapeHtml($data['activity_name']);?></td>
                                <td class=" "><?php echo $this->escapeHtml($data['broad_head_name_id']);?></td>
                                <td class=" "><?php echo $this->escapeHtml($data['object_code_id']);?></td>
                                <td class=" "><?php echo $this->escapeHtml($data['budget_amount_approved']);?></td>
                                <td class=" "><?php echo "expenditure"; ?></td>
                                <td class=" "><?php echo $this->escapeHtml($data['balance']);?></td>
                                <td class=" "><?php echo $this->formRow($budgetForm->get('to_proposal_id')); ?></td>
                              </tr>
                          <?php endforeach; ?>
                      </tr>
                     </tbody>
                   </table>
                  
                </div>
              </div>
                   <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                        <?php
                           //echo $this->formHidden($budgetForm->get('organisation_id'));
                           echo $this->formHidden($budgetForm->get('csrf'));
                           echo $this->formSubmit($budgetForm->get('submit'));
                           echo $this->form()->closeTag(); 
                        ?>
                    	</div>
                    </div>
               </div>
              
              <!-- End of Reappropriation To Details-->
             </div>
        </div>
       
              	
    
          </div>
          <!-- End of Reappropiration details after submission of form -->
        </div> 
     </div>