<?php
 $level = 'Add/Edit Employee Profile Picture';
 $this->headTitle($level);
 ?>
<div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2><?php echo $this->escapeHtml($level); ?></h2>
                    <div class="clearfix"></div>
                  </div>
                    
                  <div class="x_content">
                  <h5><i>*Uploading Profile Picture will replace the previous profile picture uploaded< or add new if you have not yet uploaded/i></i></h5>
                    <br/>
					       <?php
					       // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				            $level = $form->get('profilepicture');
                    $level->get('employee_details_id')->setValue($this->id);
                    echo $this->formHidden($level->get('id')); 
					           echo $this->formHidden($level->get('employee_details_id'));
                    ?>
                    <?php if($this->message == NULL && $this->flashMessenger()->hasMessages()) {
							       echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
							       echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
        							$messages = $this->flashMessenger()->getMessages();
        							foreach($messages as $message) {
        								echo '<strong>Success!</strong>'. $message;
        							}
        							echo '</div>';
                    	} else if($this->message =='Failure' && $this->flashMessenger()->hasMessages()) {
                            echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                            echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                            $messages = $this->flashMessenger()->getMessages();
                            foreach($messages as $message) {
                                echo '<strong>Warning!</strong>'. $message;
                            }
                            echo '</div>';
                     }  ?>
                     <div class="col-md-3 col-sm-3 col-xs-12 profile_left">
                      <div class="profile_img">
                        <div id="crop-avatar">
                          <?php 
                          $image = $this->profilePicture; 

                          if(!empty($image))
                          {?>
                            <img class="img-responsive avatar-view" src="<?php echo '../../'.$image; ?>" alt="Avatar"  title="Change the avatar">
                         <?php } else{?>

                          <?php
                          echo "There is no profile picture uploaded. Please upload it.";
                        }?>
                        </div>                        
                      </div>                       
                     </div>

                     <div class="col-md-9 col-sm-9 col-xs-12">
                      <div class="profile_title">
                        <div class="col-md-6">
                          <h2>Upload Profile Picture</h2>
                        </div>
                      </div><br>

                      <div class="row">
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-2 col-xs-12">Staff Name <span class="required">*</span></label>
                        <div class="col-md-3 col-sm-3 col-xs-12">
                          <input type="text" placeholder="<?php echo $this->employees->getFirst_Name(). ' '.$this->employees->getMiddle_Name(). ' '.$this->employees->getLast_Name(); ?>" class="form-control col-md-7 col-xs-12" disabled="disabled">
                        </div>
                      </div>
                    </div>
                    <div class="row">
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-2 col-xs-12">Staff ID <span class="required">*</span></label>
                        <div class="col-md-3 col-sm-3 col-xs-12">
                          <input type="text" placeholder="<?php echo $this->employees->getEmp_Id(); ?>" class="form-control col-md-7 col-xs-12" disabled="disabled">
                        </div>
                      </div>
                    </div>
                    <br />
                    <div class="row"> 
                       <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Upload Profile Picture<span class="required">*</span></label>
                         <div class="col-md-3 col-sm-3 col-xs-12">
                         <?php echo $this->formRow($level->get('profile_picture')); ?>
                         </div>
                       </div>
                    </div>
                    <div class="row">
                       <div class="ln_solid"></div>
                        <div class="form-group">
                           <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                            <div class="col-md-12 col-sm-12 col-xs-12">
                            <?php
                               echo $this->formHidden($form->get('csrf')); 
                                echo $this->formSubmit($level->get('submit'));
                               echo $this->form()->closeTag();
?>
<a href="<?php echo $this->url('empprofilepicture');?>"><span class="btn btn-primary">Back / Cancel</span></a>
			    </div>
                      <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
                        <script type="text/javascript">
                            $(window).on('beforeunload', function () {
                                $("input[type=submit], input[type=button]").prop("disabled", "disabled");
                            });
                        </script>
			</div>
                     </div>
                       
                     </div>                 
                 </div>
              </div>
           </div>
        </div>
     </div>
