
     
<?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Application for College Research Publication';
 $this->headTitle($title);
?>
	<div class="right_col" role="main">
          <div class="">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                      <div class="x_title">
                        <h2><?php echo $this->escapeHtml($title); ?></h2>
                        <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"></a>
                      </li>
                      </ul>
                      <div class="clearfix"></div>
                      </div>
                      <div class="x_content">
                         <form class="form-horizontal form-label-left input_mask"><br/>

                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">First Name</label>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                          <input type="text" class="form-control" placeholder="First Name">
                        </div>
                      </div>
                              <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Middle Name</label>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                          <input type="text" class="form-control" placeholder="Middle Name">
                        </div>
                              </div>
                        <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Last Name</label>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                          <input type="text" class="form-control" placeholder="Last Name">
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">College</label>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                          <input type="text" class="form-control" placeholder="Name of the college">
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Position level</label>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                          <input type="text" class="form-control" placeholder="P1">
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Sex</label>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                          <input type="text" class="form-control" placeholder="Gender">
                        </div>
                      </div>         
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">E-mail</label>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                          <input type="text" class="form-control" placeholder="enter your email">
                        </div>
                      </div>         
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Contact No.</label>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                          <input type="text" class="form-control" placeholder="enter your phone no">
                        </div>
                      </div>
                             <div class="form-group">
                         <label class="control-label col-md-3 col-sm-3 col-xs-12">Upload Publication</label>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                          <input type="file" class="form-control" placeholder="">
                        </div>
                        </div>
                             <br>
                             <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-4">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <button type="submit" class="btn btn-success">Cancel</button>
                      </div>
                </form> 
                      </div>
                    </div></div></div></div>     
<
      
              
