<?php
 $title = 'Human Resource Report';
 $this->headTitle($title);
 $position_category = array();
 $position_level = array();
 $i=1;
 foreach($this->positionCategory as $category){
     $position_category[$i++] = $category;
 }
 $i=1;
 foreach($this->positionLevel as $level){
     $position_level[$i++] = $level;
 }
 
 $organisation_list = array();
foreach($this->organisationList as $key=>$organisation){
    if($key != 1){
        $organisation_list[$key] = $organisation;
    }
}

?>

 <div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
            
                <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                     <div class="clearfix"></div>
                    </div>
                    
                        <!-- Search Employees-->
                        <div class="col-md-12 col-xs-12">
                          <div class="x_panel">
                            <div class="x_title">
                              <h2><?php echo $this->escapeHtml("Report")?></h2>
                                <ul class="nav navbar-right panel_toolbox">
                                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                                </ul>
                             <div class="clearfix"></div>
                            </div>
                            <div class="x_content">
                               <?php
                                // Opening of the form tag
                                $form->prepare();
                                echo $this->form()->openTag($form);
                                $form->get('report_name')->setValueOptions($this->report_list);
                                $form->get('organisation')->setValueOptions($this->organisationList);
                                $form->get('five_year_plan')->setValueOptions($this->fiveYearPlanList);
                                $form->get('report_type')->setValue('list');
                                echo $this->formHidden($form->get('report_type'));
                              ?>
                            
                              <div class="row">
                                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Report Type</label>
                                    <?php echo $this->formRow($form->get('report_name')); ?>
                                  </div>
                                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Agency/College</label>
                                    <?php echo $this->formRow($form->get('organisation')); ?>
                                  </div>
                                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Five Year Plan</label>
                                    <?php echo $this->formRow($form->get('five_year_plan')); ?>
                                  </div>
                                  
                             </div>
                             <div class="row">
                                <div class="ln_solid"></div>
                                <div class="form-group">
                                    <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                                      <?php
                                       echo $this->formHidden($form->get('csrf'));
                                       echo $this->formSubmit($form->get('submit')); 
                                       echo $this->form()->closeTag(); 
                                    ?>
                                </div>
                            </div>
                          </div>
                        </div>
                       </div>     
                          
                        <?php 
                            if(!empty($this->report_details) && $this->report_details['report_name'] == 'separation_agencies_position'){
                                    echo $this->partial('separation_agencies_position.phtml', 
                                                            array( 
                                                                'hr_report' => $this->hr_report, 
                                                                'five_year_plan' => $this->five_year_plan,
                                                                'position_category' => $position_category, 
                                                                'position_level' => $position_level)); 
                            } else if(!empty($this->report_details) && $this->report_details['report_name'] == 'recruitment_separation'){
                                    echo $this->partial('recruitment_separation.phtml', 
                                                            array( 
                                                                'hr_report' => $this->hr_report, 
                                                                'five_year_plan' => $this->five_year_plan,
                                                                'organisationList' =>  $this->organisationList,
                                                                'position_category' => $position_category)); 
                            } else if(!empty($this->report_details) && $this->report_details['report_name'] == 'staff_transfer_details'){
                                    echo $this->partial('recruitment_separation.phtml', 
                                                            array( 
                                                                'hr_report' => $this->hr_report, 
                                                                'five_year_plan' => $this->five_year_plan,
                                                                'organisationList' =>  $this->organisationList,
                                                                'position_category' => $position_category));
                            } else if(!empty($this->report_details) && $this->report_details['report_name'] == 'staff_promotion_details'){
                                    echo $this->partial('staff_promotion_details.phtml', 
                                                            array( 
                                                                'hr_report' => $this->hr_report, 
                                                                'five_year_plan' => $this->five_year_plan,
                                                                'organisationList' =>  $this->organisationList,
                                                                'position_category' => $position_category));
                            } else if(!empty($this->report_details) && $this->report_details['report_name'] == 'staff_separation_details'){
                                    echo $this->partial('staff_separation_details.phtml', 
                                                            array( 
                                                                'hr_report' => $this->hr_report, 
                                                                'five_year_plan' => $this->five_year_plan,
                                                                'organisationList' =>  $this->organisationList,
                                                                'position_category' => $position_category));
                            } else if(!empty($this->report_details) && $this->report_details['report_name'] == 'staff_apa_details'){
                                    echo $this->partial('staff_apa_details.phtml', 
                                                            array( 
                                                                'hr_report' => $this->hr_report, 
                                                                'five_year_plan' => $this->five_year_plan,
                                                                'organisationList' =>  $this->organisationList,
                                                                'position_category' => $position_category));
                            } else if(!empty($this->report_details) && $this->report_details['report_name'] == 'staff_by_dzongkhag'){
                                    echo $this->partial('staff_by_dzongkhag.phtml', 
                                                            array( 
                                                                'hr_report' => $this->hr_report, 
                                                                'five_year_plan' => $this->five_year_plan,
                                                                'organisationList' =>  $this->organisationList,
                                                                'position_category' => $position_category));
                            } else if(!empty($this->report_details) && $this->report_details['report_name'] == 'staff_by_nationality'){
                                    echo $this->partial('staff_by_nationality.phtml', 
                                                            array( 
                                                                'hr_report' => $this->hr_report, 
                                                                'five_year_plan' => $this->five_year_plan,
                                                                'organisationList' =>  $this->organisationList,
                                                                'position_category' => $position_category));
                            } else if(!empty($this->report_details) && $this->report_details['report_name'] == 'staff_by_religion'){
                                    echo $this->partial('staff_by_religion.phtml', 
                                                            array( 
                                                                'hr_report' => $this->hr_report, 
                                                                'five_year_plan' => $this->five_year_plan,
                                                                'organisationList' =>  $this->organisationList,
                                                                'position_category' => $position_category));
                            } else if(!empty($this->report_details) && $this->report_details['report_name'] == 'staff_by_gender'){
                                    echo $this->partial('staff_by_gender.phtml', 
                                                            array( 
                                                                'hr_report' => $this->hr_report, 
                                                                'five_year_plan' => $this->five_year_plan,
                                                                'organisationList' =>  $this->organisationList,
                                                                'position_category' => $position_category));
                            } else if(!empty($this->report_details) && $this->report_details['report_name'] == 'staff_by_organisation'){
                                    echo $this->partial('staff_by_organisation.phtml', 
                                                            array( 
                                                                'hr_report' => $this->hr_report, 
                                                                'five_year_plan' => $this->five_year_plan,
                                                                'organisationList' =>  $this->organisationList,
                                                                'position_category' => $position_category));
                            } else if(!empty($this->report_details) && $this->report_details['report_name'] == 'staff_by_department'){
                                    echo $this->partial('staff_by_department.phtml', 
                                                            array( 
                                                                'hr_report' => $this->hr_report, 
                                                                'five_year_plan' => $this->five_year_plan,
                                                                'organisationList' =>  $this->organisationList,
                                                                'position_category' => $position_category));
                            } else if(!empty($this->report_details) && $this->report_details['report_name'] == 'staff_by_employeetype'){
                                    echo $this->partial('staff_by_employee_type.phtml', 
                                                            array( 
                                                                'hr_report' => $this->hr_report, 
                                                                'five_year_plan' => $this->five_year_plan,
                                                                'organisationList' =>  $this->organisationList,
                                                                'position_category' => $position_category));
                             } else if(!empty($this->report_details) && $this->report_details['report_name'] == 'overall'){
                                    echo $this->partial('overall.phtml', 
                                                            array( 
                                                                'hr_report' => $this->hr_report, 
                                                                'five_year_plan' => $this->five_year_plan,
                                                                'organisationList' =>  $this->organisationList,
                                                                'position_category' => $position_category,
                                                                'occupationalGroup' => $occupationalGroup,
                                                                'organisationList' => $organisationList,
                                                                'gender' => $gender,
                                                                 'emp_type' => $emp_type));
                            }else if(!empty($this->report_details) && $this->report_details['report_name'] == 'emptypestats'){
                                    echo $this->partial('emp_type_stats.phtml', 
                                                            array( 
                                                                'hr_report' => $this->hr_report, 
                                                                'five_year_plan' => $this->five_year_plan,
                                                                'organisationList' =>  $this->organisationList,
                                                                'organisationList' => $organisationList,
                                                                'gender' => $gender,
                                                                'emp_type' => $emp_type));
                            } else if(!empty($this->report_details) && $this->report_details['report_name'] == 'staff_by_section'){
                                    echo $this->partial('staff_by_section.phtml', 
                                                            array( 
                                                                'hr_report' => $this->hr_report, 
                                                                'five_year_plan' => $this->five_year_plan,
                                                                'organisationList' =>  $this->organisationList,
                                                                'position_category' => $position_category));
                            } else if(!empty($this->report_details) && $this->report_details['report_name'] == 'staff_by_maritialstatus'){
                                    echo $this->partial('staff_by_maritial_status.phtml', 
                                                            array( 
                                                                'hr_report' => $this->hr_report, 
                                                                'five_year_plan' => $this->five_year_plan,
                                                                'organisationList' =>  $this->organisationList,
                                                                'position_category' => $position_category));
                            } else if(!empty($this->report_details) && $this->report_details['report_name'] == 'staff_by_positiontitle'){
                                    echo $this->partial('staff_by_position_title.phtml', 
                                                            array( 
                                                                'hr_report' => $this->hr_report, 
                                                                'five_year_plan' => $this->five_year_plan,
                                                                'organisationList' =>  $this->organisationList,
                                                                'position_category' => $position_category));
                            } else if(!empty($this->report_details) && $this->report_details['report_name'] == 'staff_by_positionlevel'){
                                    echo $this->partial('staff_by_position_level.phtml', 
                                                            array( 
                                                                'hr_report' => $this->hr_report, 
                                                                'five_year_plan' => $this->five_year_plan,
                                                                'organisationList' =>  $this->organisationList,
                                                                'position_category' => $position_category));
                            } else if(!empty($this->report_details) && $this->report_details['report_name'] == 'staff_by_bloodgroup'){
                                    echo $this->partial('staff_by_blood_group.phtml', 
                                                            array( 
                                                                'hr_report' => $this->hr_report, 
                                                                'five_year_plan' => $this->five_year_plan,
                                                                'organisationList' =>  $this->organisationList,
                                                                'position_category' => $position_category));
                            } 
                        ?>
                  </div>
                </div>
              </div>
            </div>
           </div>
     </div>