<?php
/**
 *  pay head report---Hr/ReportController/htpitreport  
 */
	$this->headTitle($this->title);
?>
<?php echo $this->partial('accounts/payroll-report/partial.phtml', array('active' => 'htpitreport')); ?><br/>
<?php	
	$earningHead = $this->payheadObj->get(array('deduction'=>0));
	$earning=ceil(count($earningHead)); //no of earning columns
	$earning = $earning - 1;
?>
<div class="widget widget-box transparent">
	<div class="widget-header">
		<h4 class="widget-title"> 	
			Health Tax & Personal Income Tax Report
		</h4>
		<div class="pull-right tableTools-container"></div>
	</div>	
	<div class="widget-body">
		<div class="widget-main">
			<form >
				<div class="row">
					<div class="col-md-2">
						<label for="month" class="control-label">Month </label>
						<select class="form-control" name="month" id="month" data-placeholder="Select" required >
							<option value=""></option>
							<?php 
								for($m=1;$m<=12;$m++):
									$selected = ($data['month'] == $m)?'selected':'';
							?>
								<option value="<?php echo $m;?>" <?php echo $selected;?>>
									<?php echo date("F", strtotime(date("d-$m-y"))); ?>
								</option>
							<?php endfor; ?>
						</select>
					</div>
					<div class="col-md-2">
						<label for="year" class="control-label">Year </label>
						<select class="form-control" name="year" id="year" data-placeholder="Select" required >
							<option value=""></option>
							<?php $minYear = $this->payrollObj->getMin('year');
                            $minYear = ($this->minYear > 0)?$this->minYear:date('Y');?>
							<?php for($y=date('Y');$y >= $minYear; $y--):
								$selected = ($data['year'] == $y)?'selected':'';?>
								<option value="<?php echo $y;?>" <?php echo $selected;?>>
									<?php echo $y; ?>
								</option>
							<?php endfor; ?>
						</select>
					</div>
					<div class="form-group col-lg-2">
						<label for="organisation" class="control-label">Organisation</label>
						<select class="form-control" id="organisation" name="organisation" data-placeholder="Select" required >
							<?php 
							foreach ($organisations as $row):
							?>
								<?php $selected = ($row['id'] == $data['organisation'])?'selected':'';?>
								<option value="<?php echo $row['id'];?>" <?php echo $selected;?>>
									<?php echo $row['organisation_name'];?>
								</option>
							<?php
							endforeach;
							?>
						</select>
					</div>
					<div class="col-md-4">
						<div class="space-10"></div>
						<label for="redirect" class="control-label">&nbsp;</label>
						<button type="button" class="btn btn-sm btn-success" onclick="redirect();"><i class="fa fa-refresh"></i> refresh </button>
					</div>
				</div>
			</form>
			<div class="row"><div class="space-12"></div></div>
			<div class="row">
				<div class="col-lg-12">
					<input type="hidden" name="ptpit_date" id="ptpit_date" value="<?php echo date("F", strtotime(date("d-$month-y"))).','.$data['year'];?>" />
					<strong>For the Month of : <?php $month = $data['month']; echo date("F", strtotime(date("d-$month-y"))); ?>, <?php echo $data['year']; ?>
					<?php
						$filter = array(
							'year'=>$data['year'], 
							'month'=>$data['month'], 
							'pr.status'=>'1'									
						);
						if($data['organisation'] > 0):
							$filter['emp.organisation_id'] = $data['organisation']; 
						endif;
						$payrolls = $this->payrollObj->getforReport($filter);
						if(sizeof($payrolls) > 0):
							//Payroll Generated
						else:
							$temp_payrolls = $this->temppayrollObj->getforReport($filter);
							if(sizeof($temp_payrolls) > 0)://Draft?>
					<span class="label label-danger">DRAFT</span>
					<?php	else: //Not Generated ?>
								<span class="label label-warning"><i class="fa fa-exclamation-triangle"></i> NOT PREPARED</span>
					<?php	endif;
						endif;
					?>
					</strong>
					<span class="pull-right"> Date:  <?php echo date('d/m/Y');?></span>
				</div>
			</div>	
			<div class="space-12"></div>
			<table class="table table-condensed table-bordered" id="example">
				<thead>
					<tr>
						<th rowspan="2">#</th>
						<th rowspan="2">NAME OF EMPLOYEE</th>
						<th rowspan="2">CID NO.</th>
						<th rowspan="2">TAX PAYER NO.</th>
						<th rowspan="2">BASIC SALARY</th>
						<th colspan="<?php echo $earning;?>" style="text-align:center">BENIFITS/ALLOWANCES</th>
						<th rowspan="2">GROSS SALARY</th>
						<th rowspan="2">SALARY TAX</th>
						<th rowspan="2">HEALTH CONTRIB.</th>
						<th rowspan="2">TOTAL TAX</th>
					</tr>
					<tr>
						<!-- Earnings columns -->
						<?php foreach($earningHead as $key => $row):
								if($row['id'] != 1):?>
								<th><?php echo $row['code'];?></th>
						<?php endif;
							endforeach;?> 
					</tr>
				</thead>
				<tbody>
					<?php $i = 1; 
					$filter = array(
							'year'=>$data['year'], 
							'month'=>$data['month'], 
							'pr.status'=>'1'									
					);
					if($data['organisation'] > 0):
						$filter['emp.organisation_id'] = $data['organisation']; 
					endif;
					$tot_earning = array();
					$tot_deduction = array();
					$tot_basic_salary = 0;
					$tot_gross_salary = 0;
					$tot_salary_tax = 0;
					$tot_health_tax = 0;
					$tot_total_tax = 0;
					$pay_rolls = $this->payrollObj->getforReport($filter);
					if(sizeof($pay_rolls) > 0):
					foreach ($pay_rolls as $pay_roll):?>
						<tr>
							<td style="border-top: 1px solid #5add55;"><?php echo $i++; ?> </td>
							<td style="border-top: 1px solid #5add55;" ><?php echo $pay_roll['first_name']." ".$pay_roll['middle_name']." ".$pay_roll['last_name']; ?></td>
							<td style="border-top: 1px solid #5add55;"><?php echo $pay_roll['cid']; ?></td>
							<td style="border-top: 1px solid #5add55;"><?php
								$pit_tax_no = $this->paydetailObj->getColumn(array('pay_roll' => $pay_roll['id'], 'pay_head' => '10'), 'ref_no');
								if($pit_tax_no == ''):
									echo $ht_tax_no = $this->paydetailObj->getColumn(array('pay_roll' => $pay_roll['id'], 'pay_head' => '12'), 'ref_no');
								else:
									echo $pit_tax_no;
								endif;
							?></td>
							<td style="border-top: 1px solid #5add55;"><?php 
								$basic_salary = $this->paydetailObj->getColumn(array('pay_roll' => $pay_roll['id'], 'pay_head' => '1'), 'amount');
								echo $this->decimal($basic_salary);
								$tot_basic_salary +=$basic_salary;
							?></td>
							<!-- values for earning column -->
							<?php foreach ($earningHead as $key => $row): if($row['id'] != 1):?>
								<td style="border-top: 1px solid #5add55;"><?php
									$amount = (int)$this->paydetailObj->getColumn(array('pay_roll' => $pay_roll['id'], 'pay_head' => $row['id']), 'amount');
									echo $this->decimal($amount);
									$tot_earning[$key] += $amount;
								?></td>
							<?php endif; endforeach;?>
							<td style="border-top: 1px solid #5add55;">
							<?php
								$gross_salary = (int)$this->payrollObj->getColumn(array('employee_details' => $pay_roll['employee_details'], 'year' => $data['year'], 'month' => $data['month']), 'gross');
								echo $this->decimal($gross_salary);
								$tot_gross_salary +=$gross_salary;
							?></td>
							<td style="border-top: 1px solid #5add55;"><?php 
								$salary_tax = $this->paydetailObj->getColumn(array('pay_roll' => $pay_roll['id'], 'pay_head' => '10'), 'amount');
								echo $this->decimal($salary_tax);
								$tot_salary_tax +=$salary_tax;
							?></td>
							 <td style="border-top: 1px solid #5add55;"><?php 
								$health_tax = $this->paydetailObj->getColumn(array('pay_roll' => $pay_roll['id'], 'pay_head' => '12'), 'amount');
								echo $this->decimal($health_tax);
								$tot_health_tax +=$health_tax;
							?></td>
							 <td style="border-top: 1px solid #5add55;"><?php 
								$total_tax = $salary_tax + $health_tax;
								echo $this->decimal($total_tax);
								$tot_total_tax +=$total_tax;
							?></td>
						<tr>
					<?php endforeach;
					else:
					$temp_payrolls = $this->temppayrollObj->getforReport($filter);
					foreach($temp_payrolls as $temp_payroll):
					?>
						<tr>
							<td style="border-top: 1px solid #5add55;" ><?php echo $i++; ?> </td>
							<td style="border-top: 1px solid #5add55;"><?php echo $temp_payroll['first_name']." ".$temp_payroll['middle_name']." ".$temp_payroll['last_name']; ?></td>
							<td style="border-top: 1px solid #5add55;"><?php echo $temp_payroll['cid']; ?></td>
							<td style="border-top: 1px solid #5add55;"><?php 
								$pit_tax_no = $this->paystructureObj->getColumn(array('employee_details' => $temp_payroll['employee_details'], 'pay_head' => '10'), 'ref_no');
								if($pit_tax_no == ''):
									echo $ht_tax_no = $this->paystructureObj->getColumn(array('employee_details' => $temp_payroll['employee_details'], 'pay_head' => '12'), 'ref_no');
								else:
									echo $pit_tax_no;
								endif;
							?></td>
							<td style="border-top: 1px solid #5add55;"><?php 
								$basic_salary = $this->paystructureObj->getColumn(array('employee_details' => $temp_payroll['employee_details'], 'pay_head' => '1'), 'amount');
								echo $this->decimal($basic_salary);
								$tot_basic_salary +=$basic_salary;
							?></td>
							<!-- values for earning column -->
							<?php foreach ($earningHead as $key => $row): if($row['id'] != 1):?>
								<td style="border-top: 1px solid #5add55;"><?php
									$amount = (int)$this->paystructureObj->getColumn(array('employee_details' => $temp_payroll['employee_details'], 'pay_head' => $row['id']), 'amount');
									echo $this->decimal($amount);
									$tot_earning[$key] += $amount;
								?></td>
							<?php endif; endforeach;?>
							<td style="border-top: 1px solid #5add55;">
							<?php
								$gross_salary = (int)$this->temppayrollObj->getColumn(array('employee_details' => $temp_payroll['employee_details'], 'year' => $data['year'], 'month' => $data['month']), 'gross');
								echo $this->decimal($gross_salary);
								$tot_gross_salary +=$gross_salary;
							?></td>
							<td style="border-top: 1px solid #5add55;"><?php 
								$salary_tax = $this->paystructureObj->getColumn(array('employee_details' => $temp_payroll['employee_details'], 'pay_head' => '15'), 'amount');
								echo $this->decimal($salary_tax);
								$tot_salary_tax +=$salary_tax;
							?></td>
							 <td style="border-top: 1px solid #5add55;"><?php 
								$health_tax = $this->paystructureObj->getColumn(array('employee_details' => $temp_payroll['employee_details'], 'pay_head' => '12'), 'amount');
								echo $this->decimal($health_tax);
								$tot_health_tax +=$health_tax;
							?></td>
							 <td style="border-top: 1px solid #5add55;"><?php 
								$total_tax = $salary_tax + $health_tax;
								echo $this->decimal($total_tax);
								$tot_total_tax +=$total_tax;
							?></td>
						</tr>
					<?php endforeach;
					endif;?>	
				     <tr>
						<td></td>
						<td></strong></td>
						<td></td>
						<td> <strong>Total:   </strong></td>
						<td><strong><?php echo $this->decimal($tot_basic_salary);?></strong></td>
						<!-- values for earning column -->
						<?php foreach($earningHead as $key => $row): if($row['id'] != 1):?>
							<td><strong><?php echo $this->decimal($tot_earning[$key]); ?></strong></td>
						<?php endif; endforeach;?>
						<td><strong><?php echo $this->decimal($tot_gross_salary);?></strong></td>
						<td><strong><?php echo $this->decimal($tot_salary_tax);?></strong></td>
						<td><strong><?php echo $this->decimal($tot_health_tax);?></strong></td>
						<td><strong><?php echo $this->decimal($tot_total_tax);?></strong></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>
<script type="text/javascript">
	var title_table = 'PTPIT for the Month : '+$('#ptpit_date').val();
	$('#example').DataTable( {
		scrollX:        true,
		ordering: false,
		dom: 'Bfrtip',
		/*buttons: [
			'copy', 'csv', 'excel', 'pdf', 'print'
		]*/
		lengthMenu: [
			[ 25, 50, -1 ],
			[ '25 rows', '50 rows', 'Show all' ]
		],
		columnDefs: [ {
			visible: false
		} ],
		buttons: [
			{
				extend: 'copy',
				exportOptions: {
					columns: ':visible'
				},
				text: '<i class="fa fa-files-o"></i> Copy',
				titleAttr: 'Copy'
			},
			{
				extend: 'excel',
				title: title_table,
				exportOptions: {
					columns: ':visible'
				},
				text: '<i class="fa fa-file-excel-o"></i> Excel',
				titleAttr: 'Excel'
			},
			{
				extend: 'pdfHtml5',
				title: title_table,
				exportOptions: {
					columns: ':visible'
				},
				orientation: 'landscape',
				pageSize: 'LEGAL',
				text: '<i class="fa fa-file-pdf-o"></i> Pdf',
				titleAttr: 'PDF'
			},
			{
				extend: 'print',
				title: title_table,
				exportOptions: {
					columns: ':visible'
				},
				text: '<i class="fa fa-print"></i> Print',
				titleAttr: 'Print'
			},
			'pageLength','colvis'
		],
		select:true
	} );
	$('form select').chosen({ allow_single_deselect: true });
	function redirect(){
		var id = $('#organisation').val()+'&'+$('#year').val()+'&'+$('#month').val();
		location.href="<?php echo $this->url('preport', array('action'=>'htpitreport'));?>/"+id;
	}
</script>
