     
<?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Bank Statement ';
 $this->headTitle($title);
?>
	<div class="right_col" role="main">
          <div class="">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                      <div class="x_title">
                        <h2><?php echo $this->escapeHtml($title); ?></h2>
                        <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"></a>
                      </li>
                      </ul>
                        <div class="clearfix"></div>
                      </div>
                      <div class="x_content">
   
            
      <div class="x_panel">
                               
                <div class="x_content">
                    
                     <div class="table-responsive">
                                  <label class="control-label col-md-2 col-sm-3 col-xs-12" for="second-name">Select Date: <span class="required">*</span>
                      </label>
                      <div class="col-md-3 col-sm-6 col-xs-12">
                          <input type="date" id="verified_name" class="form-control col-md-7 col-xs-12"  placeholder="Wangchuk">
                      </div>
                         <label class="control-label col-md-2 col-sm-3 col-xs-12" for="second-name">Account No: <span class="required">*</span>
                      </label>
                      <div class="col-md-3 col-sm-6 col-xs-12">
                            <select class="form-control">
                                <option>--Select Bank a/c no--</option>
                                <option>BoB - 201231</option>
                                <option>BNB - 333423423</option>
                                
                                
                            </select>
                        </div>
                         <br><br><br>
                      <table class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Sl.No </th>
                            <th class="column-title">Book Number </th>
                            <th class="column-title">Cheque Number </th>
                            <th class="column-title">Cheque Amount </th>
                            <th class="column-title">Issue Date </th>
                            <th class="column-title">Encashment Date </th>
                            
                            <th class="column-title">Action</th>
                            
                            
                             </tr>
                        </thead>  
                        <tbody>
                      <tr>
                        <td>1</td>
                        <td>23123</td>
                        <td>65001</td>
                        <td>50000</td>
                        <td>20/03/2017</td>
                        <td><input type="date"></td>
                        
                        <td><button>edit/delete</button></td>
                        
                      </tr>
                      <tr>
                        <td>2</td>
                        <td>23123</td>
                        <td>65001</td>
                        <td>50000</td>
                        <td>20/03/2017</td>
                        <td><input type="date"></td>
                        
                        <td><button>edit/delete</button></td>
                        
                      </tr>
                      <tr>
                        <td>3</td>
                        <td>23123</td>
                        <td>65001</td>
                        <td>50000</td>
                        <td>20/03/2017</td>
                        <td><input type="date"></td>
                        
                        <td><button>edit/delete</button></td>
                        
                      </tr>
                      <tr>
                        <td>4</td>
                        <td>23123</td>
                        <td>65001</td>
                        <td>50000</td>
                        <td>20/03/2017</td>
                        <td><input type="date"></td>
                        
                        <td><button>edit/delete</button></td>
                        
                      </tr>
                      
                      </tbody>
                                            
                      </table>
                         <div class="col-md-3 col-sm-6 col-xs-12">
                             <button class="btn btn-primary">Save</button>
                             <button class="btn btn-danger">Cancel</button>
                      </div>
                     </div></div></div></div></div></div> </div>  </div>    


	  
          

	