<?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Voucher Approval List ( Finance Officer)';
 $this->headTitle($title);
?>

  <div class="right_col" role="main">
          <div class="">          
      <div class="clearfix"></div>

            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                        <h2><?php echo $this->escapeHtml($title); ?></h2>
                        <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"></a>
                      </li>
                      </ul>
                      <div class="clearfix"></div>
                      </div>
                <div class="x_content">


                  <div class="" role="tabpanel" data-example-id="togglable-tabs">
                    <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                      <li role="presentation" class="active"><a href="#voucherapproval" id="voucherapproval-tab" role="tab" data-toggle="tab" aria-expanded="true">Voucher Approval Lists</a>
                      </li>
                     <!-- <li role="presentation" class=""><a href="#printvoucher" role="tab" id="printvoucher-tab" data-toggle="tab" aria-expanded="false">Print Approved Voucher Lists </a>
                      </li> -->
                      
                      
                    </ul>
                    <div id="myTabContent" class="tab-content">
                      <div role="tabpanel" class="tab-pane fade active in" id="voucherapproval" aria-labelledby="voucherapproval-tab">
                          <br>
                          <div class="x_panel">
                          <div table class="responsive"> 
                              
                      <table class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                             <th>
                              <input type="checkbox" id="check-all" class="flat">
                            </th> 
                            <th class="column-title">Voucher No </th>
                            <th class="column-title">Voucher Date </th>
                            <th class="column-title">Voucher Type </th>
                            <th class="column-title">Amount </th>
                            <th class="column-title">Payee Name </th>
                            <th class="column-title">Approval Date </th>
                            
                            <th class="column-title">Action</th>
                            <th class="column-title">Remarks</th>
                            <th class="bulk-actions" colspan="7">
                              <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                            </th>
                             </tr>
                        </thead>  
                        <tbody>
                      <tr class="even pointer">
                         <th>
                              <input type="checkbox" id="check-all" class="flat">
                            </th> 
                        <td>000001</td>
                        <td>03/04/2017</td>
                        <td>Payment</td>
                        <td>20000</td>
                        <td>Dorji Wangmo</td>
                        <td><input type="date"></td>
                        
                        <td><select class="form-control">
                                <option>Select</option>
                                <option>Approve</option>
                                <option>Reject</option>
                                
                            </select></td>
                       <td><input type="text"></td>
                      </tr>
                      
                      <tr class="odd pointer">
                        <th>
                              <input type="checkbox" id="check-all" class="flat">
                            </th>  
                        <td>000002</td>
                        <td>05/02/2017</td>
                        <td>Journal</td>
                        <td>40000</td>
                        <td>Norgay</td>
                        <td><input type="date"></td>
                        
                        <td><select class="form-control">
                                <option>Select</option>
                                <option>Approve</option>
                                <option>Reject</option>
                                
                            </select></td>
                        <td><input type="textarea"></td>
                         
                      </tr>
                      
                      </tbody>
                                            
                      </table>
                     </div></div></div>
                    
                    
                  <!--    <div role="tabpanel" class="tab-pane fade" id="printvoucher" aria-labelledby="printvoucher-tab">
                        <br>
                          <div class="x_panel">
                          <div table class="responsive"> 
                              <table class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                              
                            
                            <th class="column-title">Voucher No </th>
                            <th class="column-title">Voucher Date </th>
                            <th class="column-title">Prepared by </th>
                            <th class="column-title">Voucher Print </th>
                            
                            <th class="bulk-actions" colspan="7">
                              <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                            </th>
                             </tr>
                        </thead>  
                        <tbody>
                      <tr class="even pointer">
                          
                        
                        <td>2323123</td>
                        <td>05/04/2017</td>
                        <td>Dorji Wangmo</td>
                        <td><a href="http://localhost/rub/images/voucher_print.jpg" target="_blank"> <img src="http://localhost/rub/images/print.gif" width="22" height="22" alt="print"/></a>
                        </td>
                        
                        
                      </tr>
                      
                      <tr class="odd pointer">
                          
                        
                        <td>55322</td>
                        <td>06/04/2017</td>
                        <td>Norgay</td>
                        <td><img src="http://localhost/rub/images/print.gif" width="22" height="22" alt="print"/></td>
                        
                         
                      </tr>
                      
                      </tbody>
                                            
                      </table>
                          </div></div>
                      </div> -->
                      
                       <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-4">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <button type="cancel" class="btn btn-success">Cancel</button>
                      </div>
                    </div>
                  

              <div id="custom_notifications" class="custom-notifications dsp_none">
    <ul class="list-unstyled notifications clearfix" data-tabbed_notifications="notif-group">
    </ul>
    <div class="clearfix"></div>
    <div id="notif-group" class="tabbed_notifications"></div>
              </div></div></div>