<?php
 // module/EmployeeDetail/view/employee-detail/employee-detail/emppersonaldetail.phtml:

 $title = 'Fee Collection';
 $this->headTitle($title);
 ?>
 <div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                    
                    </ul>
                  <div class="clearfix"></div>
                  </div>
              
                  <div class="x_content">
                      
                <div class="x_content">
                  <br />
                   <?php
                   $form->prepare();
                   echo $this->form()->openTag($form);

                   echo $this->formHidden($form->get('id'));   
                ?>
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-12 col-xs-12">Course: <span class="required">*</span>
                    </label>
                    <div class="col-md-3 col-sm-12 col-xs-12">
                      <?php  echo $this->formRow($form->get('course')); ?>
                    </div>
                </div>
                </div> 
                  
                 <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-12 col-xs-12">Semester: <span class="required">*</span>
                    </label>
                    <div class="col-md-3 col-sm-12 col-xs-12">
                      <?php  echo $this->formRow($form->get('semester')); ?>
                    </div>
                </div>
                </div>   
                  
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-12 col-xs-12">Student: <span class="required">*</span>
                    </label>
                    <div class="col-md-3 col-sm-12 col-xs-12">
                      <?php  echo $this->formRow($form->get('student')); ?>
                    </div>
                    </div>
                    </div>
                
                <div class="row">
                        <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12"></label>
                              <div class="col-md-3 col-sm-3 col-xs-12">
                    <?php
                        echo $this->formSubmit($form->get('submit')); 
                      ?>
                    </div>
                    </div>
                    </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                       
               <!--<p>Add class <code>bulk_action</code> to table for bulk actions options on row select</p>-->
             <div class="x_panel"> 
            <div class="x_content">
                              
                    <div class="table-responsive">
                      <table class="table table-striped jambo_table bulk_action"> 
                       
                         <thead>
                          <tr class="headings">
                           <!-- <th>
                              <input type="checkbox" id="check-all" class="flat">
                            </th>-->
                            <th class="column-title">SL No </th>
                            <th class="column-title">Course </th>
                            <th class="column-title">Semester </th>
                            <th class="column-title">Student</th>
                            <th class="column-title">Payment Status </th>
                            <th class="column-title no-link last"><span class="nobr">Action</span>
                            </th>
                            <th class="bulk-actions" colspan="7">
                              <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                            </th>
                          </tr>
                        </thead>
                        
                        <tbody>
                     <!--   <?php foreach ($albums as $album) : ?>-->
                          <tr>
                            <!--<td>
                              <input type="checkbox" class="flat" name="table_records">
                            </td>-->
                            <!--<td class=" "><?php echo $this->escapeHtml($album->first_name);?></td>
                            <td class=" "><?php echo $this->escapeHtml($album->last_name);?></td>-->
                           <!-- <td class=" last"> <a href="<?php echo $this->url('album', array('action'=>'edit', 'id' => $album->id));?>">Edit</a>
                            				   <a href="<?php echo $this->url('album', array('action'=>'delete', 'id' => $album->id));?>">Delete</a>
                            </td>-->
                          </tr>
                         <?php endforeach; ?>
                        </tbody>
                          </table>
                      
                    </div>
           </div></div></div></div></div>
            
         
              
       
                