
<?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Transfer of Goods';
 $this->headTitle($title);
?>     
<div class="top_nav">
    <div class="nav_menu">              
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>

                <div class="x_content">
                    <div class="table-responsive">
                        <table class="table table-striped responsive-utilities jambo_table bulk_action table-bordered">
                            <thead>
                                <tr class="headings">
                                    <th class="column-title">Sl. No</th>
                                    <th class="column-title">Department Head From </th>
                                    <th class="column-title">Department Head To </th>
                                    <th class="column-title">Transfer Date</th>
                                    <th class="column-title">Item Name</th>
                                    <th class="column-title">Item Quantity</th>
                                    <th class="column-title">Rate</th>
                                    <th class="column-title">Amount</th>
                                    <th class="column-title">Remarks</th>
                                </tr>
                            </thead>

                            <tbody>
                            <?php $i=1; ?>
                            <?php foreach ($this->transferGoods as $goods) : ?>
                                <tr class="even pointer">
                                    <td class=" "><?php echo $i; ?></td>
                                    <td class=" "><?php echo $this->escapeHtml($goods->getDepartment_Head_From()); ?></td>
                                    <td class=" "><?php echo $this->escapeHtml($goods->getDepartment_Head_To()); ?></td>
                                    <td class=" "><?php echo $this->escapeHtml($goods->getTransfer_Date()); ?></td>
                                    <td class=" "><?php echo $this->escapeHtml($goods->getItem_Name_Id()); ?></td>
                                    <td class=" "><?php echo $this->escapeHtml($goods->getItem_Quantity()); ?></td>
                                    <td class=" "><?php echo $this->escapeHtml($goods->getRate()); ?></td>
                                    <td class=" "><?php echo $this->escapeHtml($goods->getAmount()); ?></td>
                                    <td class=" "><?php echo $this->escapeHtml($goods->getRemarks()); ?></td>
                                </tr>
                            <?php $i++; ?>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>