<?php
 $title = 'Delete Attendance of Students(Daily & Module wise)';
 $this->headTitle($title);
 
 $dates = NULL;
 $day = NULL;
 foreach($this->timetable_dates as $key=>$value){
	 $dates = $key;
	 $day = $value;
 }
 
?>
<div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                        <!-- Adding Attendance Record-->
                        <div class="col-md-12 col-xs-12">
                          <div class="x_panel">
                            <div class="x_title">
                              <h2><?php echo $this->escapeHtml($title)?></h2>
                                <ul class="nav navbar-right panel_toolbox">
                                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                  </li>
                            
                                </ul>
                             <div class="clearfix"></div>
                          
                            </div>
                               
                            <div class="x_content">
                            <h5><i>*(Delete "attendance" for date in a module.)<br />
                            *(Attendance can be deleted if attendance has been added. If attendance is empty then it will gives you a message that "Attendance For Selected Date has not been entered")</i></h5>
                              <br />
                               <?php
                                // Opening of the form tag
                                $form->prepare();
                                echo $this->form()->openTag($form);
                                $form->get('section')->setValueOptions($this->sectionList);
                								$form->get('to_date')->setValue(date('Y-m-d'));
                								echo $this->formHidden($form->get('to_date'));
                              ?>
                            <?php if($this->message == NULL && $this->flashMessenger()->hasMessages()) {
            								echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
            								echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
            								$messages = $this->flashMessenger()->getMessages();
            								foreach($messages as $message) {
            									echo '<strong>Success!</strong>'. $message;
            								}
            								echo '</div>';
            								} else if($this->message =='Failure' && $this->flashMessenger()->hasMessages()) {
            									echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
            									echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
            									$messages = $this->flashMessenger()->getMessages();
            									foreach($messages as $message) {
            										echo '<strong>Warning!</strong>'. $message;
            									}
            									echo '</div>';
            							   } ?>
                              <div class="row">
                                  <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                                    <label>Module</label>
                                    <?php echo $this->formRow($form->get('module')); ?>
                                  </div>
                                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                      <label>Section <small><i>(if no section, use 'A')</i></small></label>
                                    <?php echo $this->formRow($form->get('section')); ?>
                                  </div>
                                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Date</label>
                                    <?php echo $this->formRow($form->get('from_date')); ?>
                                  </div>
                               </div>
                             
                             <div class="row">
                                <div class="ln_solid"></div>
                                <div class="form-group">
                                    <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                                      <?php
                                       echo $this->formHidden($form->get('csrf'));
                                       echo $this->formSubmit($form->get('submit')); 
                                       echo $this->form()->closeTag(); 
                                    ?>
                                </div>
                            </div>
                              
                          </div>
                        </div>
                       </div>     
                          
                        <div class="col-md-12 col-sm-12 col-xs-12">
                          <div class="x_panel">
                            <div class="x_title">
                              <h2><?php echo $this->escapeHtml("List of Period(s)"); ?></h2>
                              <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                </li>
                              </ul>
                              <div class="clearfix"></div>
                            </div>
                            <?php
                                    if($this->attendanceForm != NULL){
                                    // Opening of the form tag
                                     $attendanceForm->setAttribute('action', $this->url('updatedeletedstudentattendance', array('action' => 'updateDeletedStudentAttendance')));
                                     $form->prepare();
                                     echo $this->form()->openTag($attendanceForm);
                                     $attendanceForm->get('employee_details_id')->setValue($this->employee_details_id);
                                     $attendanceForm->get('programme_id')->setValue($this->programme_id);
                                     $attendanceForm->get('academic_modules_id')->setValue($this->academic_modules_id);
                                     $attendanceForm->get('from_date')->setValue($this->from_date);
                                     $attendanceForm->get('to_date')->setValue($this->to_date);
									                   $attendanceForm->get('section')->setValue($this->section);
                                     echo $this->formHidden($attendanceForm->get('employee_details_id'));
                                     echo $this->formHidden($attendanceForm->get('programme_id'));
                                     echo $this->formHidden($attendanceForm->get('academic_modules_id'));
                                     echo $this->formHidden($attendanceForm->get('from_date'));
                                     echo $this->formHidden($attendanceForm->get('to_date'));
									                   echo $this->formHidden($attendanceForm->get('section'));
                            ?>
                            <div class="x_content">
                            <h4><i class="green">You are Deleting Attendance for</i>&nbsp;&nbsp;
                            <b>	&nbsp;&nbsp;<i class="blue">Programme: <?php echo $this->programme_name?></i>&nbsp;&nbsp;
                            	&nbsp;&nbsp;<i class="blue">Module: <?php echo $this->module_code?></i>&nbsp;&nbsp;
                              &nbsp;&nbsp;<i class="blue">Of Date: <?php echo $this->attendance_date?></i>
                            </b></h4>
                            <br />
                            <div  class="table-responsive">
                              <table class="table table-striped responsive-utilities jambo_table bulk_action table-bordered">
                                <thead>
                                  <tr class="headings">
                                    <td class="column-title">Period (s) <br>
                                      (<?php echo $day; ?><br>
                                      <?php 
                                      $tmp_keys = explode('_', $dates);
                                      $date = $tmp_keys[0];
                                      echo $date; ?>)
                                    </td>
                                    <td class="column-title" width="50%">Action <br><small>(If there is more than one period for the particular date then please check for which period you want to delete or either for all periods if you want.)</small></td>
                                  </tr>
                                </thead>
                                <tbody>
                                  <?php foreach($this->timetable_dates as $key=>$value):?>
                                  <tr class="even pointer">
                                      <td class=" "><?php 
                                      $tmp_keys = explode('_', $key);
                                      $time = $tmp_keys[1];
                                      echo $time; 
                                      ?></td>
                                      <td class="a-center"><?php echo $this->formRow($attendanceForm->get('attendance_'.$key)); ?></td>
                                  </tr>
                                  <?php endforeach; ?>
                                </tbody>
                              </table>
                            </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="row">
                                    <div class="ln_solid"></div>
                                    <div class="form-group">
                                    <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                                      <?php
                                       echo $this->formHidden($attendanceForm->get('csrf'));
                                       echo $this->formSubmit($attendanceForm->get('submit')); 
                                       echo $this->form()->closeTag(); 
                                       
                                    }//closing of if loop
                                    ?>
                                    </div>
                                </div>
                          </div>
                        </div>
                            
                           		<!-- End of Attendance-->
                        </div>
                      </div>
                  </div>
                </div>
              
<script>
$(function(){
    $('.datepicker').datepicker({
        format: 'mm-dd-yyyy',
        //startDate: '+0d',
		endDate: '+0d',
        autoclose: true
    });
});
</script>