<?php
 $title = 'Organisation Configuration & Settings';
 $this->headTitle($title);
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="col-md-12 col-xs-12">
                          <div class="x_panel">
                            <div class="x_title">
                              <h2><?php echo $this->escapeHtml("Edit Department")?></h2>
                                <ul class="nav navbar-right panel_toolbox">
                                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                  </li>
                            
                                </ul>
                             <div class="clearfix"></div>
                            </div>
                            <div class="x_content">
                   
                <?php
                   // Opening of the form tag
					         $form->prepare();
                    echo $this->form()->openTag($form);
				            $department = $form->get('departments');
          					$department->get('id')->setValue($this->departmentDetail->getId());
          					$department->get('department_name')->setValue($this->departmentDetail->getDepartment_Name());
          					$department->get('organisation_id')->setValueOptions($this->organisationList);
          					$department->get('organisation_id')->setValue($this->departmentDetail->getOrganisation_Id());
                    echo $this->formHidden($department->get('id'));   
                ?>
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Organisation/College Name<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php echo $this->formRow($department->get('organisation_id')); ?>
                    </div>
                </div>
                </div> 
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Deparment Name: <span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($department->get('department_name')); ?>
                    </div>
                </div>
                </div>
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                        <?php 
          						   echo $this->formHidden($form->get('csrf'));
          						   echo $this->formSubmit($department->get('submit')); 
          						?>
                        </div>
                    </div>
                </div>
                    
				<?php echo $this->form()->closeTag(); ?>
                    
                </div>
                </div> 
                
			</div> 
                
   		 </div>
 		</div>
	</div>
  </div>
            
