<?php
 $title = 'Organisation Configuration & Settings';
 $this->headTitle($title);
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="col-md-12 col-xs-12">
                          <div class="x_panel">
                            <div class="x_title">
                              <h2><?php echo $this->escapeHtml("Edit Unit")?></h2>
                                <ul class="nav navbar-right panel_toolbox">
                                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                  </li>
                            
                                </ul>
                             <div class="clearfix"></div>
                            </div>
                            <div class="x_content">
                <?php
                   // Opening of the form tag
					        $form->prepare();
                  echo $this->form()->openTag($form);
				         // $unit = $form->get($form); 
        					$form->get('id')->setValue($this->unitDetail->getId());
        					$form->get('unit_name')->setValue($this->unitDetail->getUnit_Name());
        					$form->get('organisation_id')->setValueOptions($this->organisationList);
        					$form->get('organisation_id')->setValue($this->unitDetail->getOrganisation_Id());
        					$form->get('departments_id')->setValueOptions($this->departmentList);
        					$form->get('departments_id')->setValue($this->unitDetail->getDepartments_Id());
                            echo $this->formHidden($form->get('id'));   
                ?>
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Organisation/College Name:<span class="required">*</span>
                    </label>
                    <div class="col-md-5 col-sm-5 col-xs-12">
                      <?php  echo $this->formRow($form->get('organisation_id')); ?>
                    </div>
                </div>
                </div> 
                  
                 <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm- col-xs-12">Department Name:<span class="required">*</span>
                    </label>
                    <div class="col-md-5 col-sm-5 col-xs-12">
                      <?php  echo $this->formRow($form->get('departments_id')); ?>
                    </div>
                </div>
                </div>   
                  
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Unit Name:<span class="required">*</span>
                    </label>
                    <div class="col-md-5 col-sm-5 col-xs-12">
                      <?php  echo $this->formRow($form->get('unit_name')); ?>
                    </div>
                </div>
                </div>
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                        <?php 
          						   echo $this->formHidden($form->get('csrf'));
          						   echo $this->formSubmit($form->get('submit')); 
                         echo $this->form()->closeTag();
          						?>
                        </div>
                    </div>
                </div>                    
                </div>
                </div> 
              
			</div> 
                
   		 </div>
 		</div>
	</div>
  </div>
            
