<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
 //  'CareerOpportunity\Module'                        => __DIR__ . '/Module.php',
   //'CareerOpportunity\Controller\EmployeeDetailController' => __DIR__ . '/src/CareerOpportunity/Controller/EmployeeDetailController.php',
    
);
