<?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Create Alumni FAQs';
 $this->headTitle($title);
?>
<div class="right_col" role="main">
    <div class="">
        <div class="col-md-12 col-xs-12">
            <div class="x_panel">
			   <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                 </div><!--end of x-title-->
                   <div class="x_content">
                    <br />
                    <?php
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        $alumnifaqs = $form->get('alumnifaqs');
                        echo $this->formHidden($alumnifaqs->get('id')); 
                                    
            						$alumnifaqs->get('organisation_id')->setValue($this->organisation_id);
            						 echo $this->formHidden($alumnifaqs->get('organisation_id'));
                     ?>

                     <?php 
                            if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                                echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                $messages = $this->flashMessenger()->getMessages();
                                foreach($messages as $message) {
                                    echo '<strong>Success!</strong>'. $message;
                                }
                                echo '</div>';
                            }

                            else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                                echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                $messages = $this->flashMessenger()->getMessages();
                                foreach($messages as $message) {
                                    echo '<strong>Failure!</strong>'. $message;
                                }
                                echo '</div>';
                            }
                        ?>
                            
                            <div class="form-group">
                                <label class="control-label col-md-2 col-sm-2 col-xs-12">Questions:<span class="required">*</span></label>
                                    <div class="col-md-8 col-sm-8 col-xs-12">
                                        <?php  echo $this->formRow($alumnifaqs->get('faq_questions')); ?>
                                    </div>
                            </div> 
                            <div class="form-group">
                                <label class="control-label col-md-2 col-sm-2 col-xs-12"> Answers:<span class="required">*</span></label>
                                        <div class="col-md-8 col-sm-8 col-xs-12">
                                            <?php  echo $this->formRow($alumnifaqs->get('faq_answers')); ?>
                                        </div>
									  
                            </div>
                           <div class="ln_solid"></div>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                        <?php 
                                                     echo $this->formHidden($form->get('csrf'));
                                                      echo $this->formSubmit($alumnifaqs->get('submit')); ?>
                                        </div>
                                </div>
                    </div>
                     <?php
                         echo $this->form()->closeTag();
                     ?>
					 
		     </div> 
		</div>  
    </div>
        <div class="col-md-12 col-sm-12 col-xs-12">
           <div class="x_panel"> 
                  <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                  <div class="clearfix"></div>
                  </div>
				  
              <div class="x_content">
                    <div class="table-responsive">
                      <table id="datatable-responsive" class="table table-striped responsive-utilities jambo_table bulk_action table-bordered"> 
                         <thead>
                          <tr class="headings">
                      <!--  <th>
                          <input type="checkbox" id="check-all" class="flat" disabled>
                        </th>-->                          
                          <th style="width: 1%">Sl.No. </th>
                          <th style="width: 40%">Questions</th>
                          <th style="width: 59%">Answers</th>
                         
                         </tr>
                        </thead>
                         <?php $i=1; ?>
                         <?php foreach ($this->faqslist as $faqslist) : ?>
                          <tr class="even pointer">
                             <td class=" "><?php echo $i; ?></td>
                                                  <td class=" "><?php echo $this->escapeHtml($faqslist->getFaq_Questions());?></td>
                                                  <td class=" "><?php echo $this->escapeHtml($faqslist->getFaq_Answers());?></td>
                                                                                                    
                          </tr>
                          <?php $i++; ?>
                          <?php endforeach; ?>
                       </table>
                    </div>
		        </div>
	      </div><!--end of x-Panel-->
    </div><!--end of col-md-12 col-xs-12-- >
  </div><!--end of ""-->
  
</div><!--end of right_col-- >




 

 