<?php
 // module/EmployeeDetail/view/employee-detail/employee-detail/emppersonaldetail.phtml:

    $title = 'Registered Alumni Member List';
    $this->headTitle($title);
 
?>
<div class="right_col" role="main">
    <div class="">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </ul>
                    <div class="clearfix"></div>
                </div>

                <div class="col-md-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2><?php echo $this->escapeHtml("Search for List of Registered Alumni Members")?></h2>
                            <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                            </ul>
                            <div class="clearfix"></div>
                  
                        </div>
                       
                        <div class="x_content">
                            <h5><i>*(In order to view the registered student list, either enter organisation name or programme name or admission year or gender or reporting status and click on search button. Input as many fields as possible to narrow the search.)<br />
                                        **Possible reporting status to type are Pending, Reported and Not Reported** </i></h5>
                                  <br />
                            <?php
                            // Opening of the form tag
                            $form->prepare();
                            echo $this->form()->openTag($form);
                            ?>
                        
                            <div class="row">
                                
                                <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Programme</label>
                                    <?php echo $this->formRow($form->get('programme')); ?>
                                </div>
                                <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Graduation Year</label>
                                    <?php echo $this->formRow($form->get('graduation_year')); ?>
                                </div>
                                <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Name</label>
                                    <?php echo $this->formRow($form->get('name')); ?>
                                </div>
                            </div>
                                                     
                            <div class="row">
                                <div class="ln_solid"></div>
                                <div class="form-group">
                                    <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                                      <?php
                                       echo $this->formHidden($form->get('csrf'));
                                       echo $this->formSubmit($form->get('submit')); 
                                       echo $this->form()->closeTag(); 
                                    ?>
                                </div>
                            </div>                          
                        </div>
                    </div>
                </div>
                

                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2><?php echo $this->escapeHtml("List of Registered Alumnies"); ?></h2>
                            <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                            </ul>
                            <div class="clearfix"></div>
                        </div>
                                 
                        <div class="x_content">
                            <div  class="table-responsive">
                                <table id="datatable" class="table table-striped responsive-utilities jambo_table bulk_action table-bordered">  
                                    <thead>
                                        <tr class="headings">
                                                                      
                                            <th class="column-title">Sl.No. </th>
                                            <th class="column-title"> Name </th>
											<th class="column-title">CID No.</th>
                                            <th class="column-title"> Date of Birth </th>
											<th class="column-title">Programme</th>
                                            <th class="column-title">Graduation Year</th>
                                            
                                            
                                        </tr>
                                    </thead>
                                   <!-- <?php $i=1; ?> -->
                                    <?php foreach ($this->registeredMemberList as $regList) : ?>
                                        <tr class="even pointer">                                            
                                            <!--<td class=" "><?php echo $i; ?></td> -->
                                            <td class=" "><?php echo $this->escapeHtml($regList['first_name']).' '; 
                                                                echo $this->escapeHtml($regList['middle_name']).' ';
                                                                echo $this->escapeHtml($regList['last_name']);?></td>
											<td class=" "><?php echo $this->escapeHtml($regList['cid']);?></td>					
                                            <td class=" "><?php echo $this->escapeHtml($regList['date_of_birth']);?></td>
											 <td class=" "><?php echo $this->escapeHtml($regList['programme_name']);?></td>
                                            <td class=" "><?php echo $this->escapeHtml($regList['graduation_year']);?></td>
                                            
                                            
                                        </tr>
                                                                 
                                   <!-- <?php $i++; ?> -->
                                    <?php endforeach; ?>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>      
</div>           
       
                