<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
<div class="menu_section">
<br><br><br>
<ul class="nav side-menu">
	<li><a><i class="fa fa-home"></i>Home<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a href="<?php echo $this->url('index') ?>">Dashboard</a></li>
		</ul>
	</li>
	<li><a><i class="fa fa-users"></i>Human Resource<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>HR Administration<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>Leave<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('leavestatus') ?>">Apply Leave</a></li>
						<li><a href="<?php echo $this->url('staffleavestatus') ?>">My Leave Status</a></li>
						<li><a href="<?php echo $this->url('applyonbehalfleave') ?>">Apply Leave On Behalf</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Leave Encashment<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('empleaveencashmentapplication') ?>">Leave Encashment</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Department Filing<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('viewfilingdocument') ?>">View Documents</a></li>
					</ul>
					</li>
			</ul>
			</li>
			<li><a><i class=""></i>HR Development<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>Long Term Trainings<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('longtermplannedlist') ?>">Planned</a></li>
					</ul>
					</li>
					<li><a href="<?php echo $this->url('applytrainings') ?>">Apply Trainings & Workshops</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Staff Lifecycle<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>Transfer<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('applytransferform') ?>">Apply Transfer</a></li>
						<li><a href="<?php echo $this->url('stafftransferstatus') ?>">My Transfer Status</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Promotion<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('empapplypromotion') ?>">Apply Promotion</a></li>
						<li><a href="<?php echo $this->url('empmeritoriouspromotion') ?>">Meritorious Promotion</a></li>
						<li><a href="<?php echo $this->url('staffpromotionstatus') ?>">My Promotion Status</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Separation<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('empresignation') ?>">Apply Resignation</a></li>
						<li><a href="<?php echo $this->url('staffresignationstatus') ?>">My Resignation Status</a></li>
					</ul>
					</li>
			</ul>
			</li>
			<li><a><i class=""></i>PMS<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>Appraisals<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('administrativeappraisal') ?>">Administrative Appraisal</a></li>
					</ul>
					</li>
			</ul>
			</li>
			<li><a><i class=""></i>Recruitment<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('appliedjobapplicationstatus') ?>">Individual Job Applicant Status</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Staff Tour<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('onbehalfemptravelauthorization') ?>">On behalf Travel Authorization </a></li>
					<li><a href="<?php echo $this->url('emptravelauthorization') ?>">Travel Authorization</a></li>
					<li><a href="<?php echo $this->url('emptravelorder') ?>">Travel Order</a></li>
					<li><a href="<?php echo $this->url('stafftourstatus') ?>">Travel Status</a></li>
			</ul>
			</li>
		</ul>
	</li>
</ul>
</div>
</div>
