<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
<div class="menu_section">
<br><br><br>
<ul class="nav side-menu">
	<li><a><i class="fa fa-home"></i>Home<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a href="<?php echo $this->url('index') ?>">Dashboard</a></li>
		</ul>
	</li>
	<li><a><i class="fa fa-users"></i>Human Resource<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>HR Planning<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>HRD Planning<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('hrdproposal') ?>">HRD Proposal</a></li>
						<li><a href="<?php echo $this->url('hrdapprovallist') ?>">HRD Plan Approval List</a></li>
						<li><a href="<?php echo $this->url('hrdapprovedlist') ?>">HRD Plan Approved List</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>HRM Planning<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('hrmapprovallist') ?>">Work Force Approval List</a></li>
						<li><a href="<?php echo $this->url('hrmapprovedlist') ?>">Work Force Approved List</a></li>
						<li><a href="<?php echo $this->url('updatehrmapprovedlist') ?>">Update Work Force Approved List</a></li>
					</ul>
					</li>
			</ul>
			</li>
			<li><a><i class=""></i>Recruitment<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>Announce Vacancy<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('viewannouncedvacancy') ?>">Edit/View Announced Vacancy</a></li>
					</ul>
					</li>
					<li><a href="<?php echo $this->url('addnewemployee') ?>">Add New Staff</a></li>
					<li><a href="<?php echo $this->url('employeeonprobation') ?>">Regularize Staff</a></li>
					<li><a href="<?php echo $this->url('newemployeelist') ?>">Generate Staff ID</a></li>
					<li><a href="<?php echo $this->url('listvacancy') ?>">List Job Vacancies</a></li>
					<li><a href="<?php echo $this->url('jobapplicantstatus') ?>">Job Applicant Status & Recruitment</a></li>
					<li><a href="<?php echo $this->url('viewappliedapplicantmarks') ?>">View Applicant Marks</a></li>
					<li><a href="<?php echo $this->url('jobregistrantdetails') ?>">View/Edit Job Registrant Details</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>HR Administration<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>Leave<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('leavestatus') ?>">Apply Leave</a></li>
						<li><a href="<?php echo $this->url('staffleavestatus') ?>">My Leave Status</a></li>
						<li><a href="<?php echo $this->url('empleavedetaillist') ?>">Staff Leave Balance</a></li>
						<li><a href="<?php echo $this->url('applyonbehalfleave') ?>">Apply Leave On Behalf</a></li>
						<li><a href="<?php echo $this->url('empapprovedleavelist') ?>">Cancel Approved Leave</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Attendance<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('viewempattendance') ?>">Staff Attendance</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Leave Encashment<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('empleaveencashmentapplication') ?>">Leave Encashment</a></li>
						<li><a href="<?php echo $this->url('empleaveencashmentlist') ?>">Leave Encashment List</a></li>
						<li><a href="<?php echo $this->url('empleaveencashmentorder') ?>">Leave Encashment Order</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Staff Task<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('employeetaskcategory') ?>">Add Task/Project</a></li>
						<li><a href="<?php echo $this->url('addempemployeetaskrecord') ?>">Add Self Activities</a></li>
						<li><a href="<?php echo $this->url('employeetaskrecord') ?>">Add Other Staff Activities</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Department Filing<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('viewfilingdocument') ?>">View Documents</a></li>
					</ul>
					</li>
					<li><a href="<?php echo $this->url('employeepaydetails') ?>">Staff Pay Details</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>HR Development<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>Long Term Trainings<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('longtermplannedlist') ?>">Planned</a></li>
						<li><a href="<?php echo $this->url('longtermadhoc') ?>">Adhoc</a></li>
					</ul>
					</li>
					<li><a href="<?php echo $this->url('applytrainings') ?>">Apply Trainings & Workshops</a></li>
					<li><a href="<?php echo $this->url('updatestudystatus') ?>">Update Training Status</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Staff Lifecycle<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>Transfer<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('applytransferform') ?>">Apply Transfer</a></li>
						<li><a href="<?php echo $this->url('transferfromapproval') ?>">From Org/College Approval</a></li>
						<li><a href="<?php echo $this->url('transfertoapproval') ?>">To Org/College Approval</a></li>
						<li><a href="<?php echo $this->url('transferapplicationstatus') ?>">Transfer Applicantion Status</a></li>
						<li><a href="<?php echo $this->url('approvedtransfers') ?>">Approved Transfers</a></li>
						<li><a href="<?php echo $this->url('stafftransferstatus') ?>">My Transfer Status</a></li>
						<li><a href="<?php echo $this->url('transferstaff') ?>">Transfer Staff</a></li>
						<li><a href="<?php echo $this->url('empdepartmentsearch') ?>">Transfer Department</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Promotion<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('empapplypromotion') ?>">Apply Promotion</a></li>
						<li><a href="<?php echo $this->url('empmeritoriouspromotion') ?>">Meritorious Promotion</a></li>
						<li><a href="<?php echo $this->url('promotionapplicantstatus') ?>">Update Promoted Applicants</a></li>
						<li><a href="<?php echo $this->url('staffpromotionstatus') ?>">My Promotion Status</a></li>
						<li><a href="<?php echo $this->url('emppromotionsearch') ?>">Promotion Via Open Competition</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Separation<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('empresignation') ?>">Apply Resignation</a></li>
						<li><a href="<?php echo $this->url('resignationapprovallist') ?>">Resignation Approval</a></li>
						<li><a href="<?php echo $this->url('resignationrecord') ?>">Dues Record</a></li>
						<li><a href="<?php echo $this->url('staffresignationstatus') ?>">My Resignation Status</a></li>
						<li><a href="<?php echo $this->url('recordresignedemployee') ?>">Add Compulsory Separation</a></li>
						<li><a href="<?php echo $this->url('separationrecord') ?>">Issue Relieving Order</a></li>
						<li><a href="<?php echo $this->url('separationrecordlist') ?>">Separation Record List</a></li>
					</ul>
					</li>
			</ul>
			</li>
			<li><a><i class=""></i>PMS<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>Appraisals<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('administrativeappraisal') ?>">Administrative Appraisal</a></li>
					</ul>
					</li>
			</ul>
			</li>
			<li><a><i class=""></i>Staff Tour<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('emptravelauthorization') ?>">Travel Authorization</a></li>
					<li><a href="<?php echo $this->url('onbehalfemptravelauthorization') ?>">On behalf Travel Authorization </a></li>
					<li><a href="<?php echo $this->url('stafftourstatus') ?>">Travel Status</a></li>
					<li><a href="<?php echo $this->url('emptravelorder') ?>">Travel Order</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Staff Management<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('addemployee') ?>">Add Missing Staff</a></li>
					<li><a href="<?php echo $this->url('employeelist') ?>">Staff List</a></li>
					<li><a href="<?php echo $this->url('empprofilepicture') ?>">Staff Profile Picture</a></li>
					<li><a href="<?php echo $this->url('updateempinitialdetails') ?>">Update Staff Details</a></li>
					<li><a href="<?php echo $this->url('emprelationdetail') ?>">Staff Relation Details</a></li>
					<li><a href="<?php echo $this->url('empworkexperience') ?>">Staff Work Experience</a></li>
					<li><a href="<?php echo $this->url('empeducation') ?>">Staff Education</a></li>
					<li><a href="<?php echo $this->url('emptrainingdetail') ?>">Staff Trainings</a></li>
					<li><a href="<?php echo $this->url('emppublication') ?>">Staff Publications</a></li>
					<li><a href="<?php echo $this->url('empresponsibility') ?>">Staff Responsibilities</a></li>
					<li><a href="<?php echo $this->url('empcontribution') ?>">Staff Contributions</a></li>
					<li><a href="<?php echo $this->url('empaward') ?>">Staff Awards</a></li>
					<li><a href="<?php echo $this->url('editstaffdepartment') ?>">Change Department</a></li>
					<li><a href="<?php echo $this->url('empcommunityservice') ?>">Staff Community Service</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>HR Reports<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('hrplanningreports') ?>">Staff Planning Reports</a></li>
					<li><a href="<?php echo $this->url('hrrecruitmentreports') ?>">HR Recruitment Report</a></li>
					<li><a href="<?php echo $this->url('hradministrationreports') ?>">HR Administration Report</a></li>
					<li><a href="<?php echo $this->url('hrdevelopmentreports') ?>">HR Development Report</a></li>
					<li><a href="<?php echo $this->url('hrlifecyclereports') ?>">HR Lifecycle Report</a></li>
			</ul>
			</li>
		</ul>
	</li>
</ul>
</div>
</div>
