
<?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Wel Come to Parent Portal - College of Science & Technology';
 $this->headTitle($title);
?>

  <div class="right_col" role="main">
          <div class="">          
      <div class="clearfix"></div>

            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                        <h2><?php echo $this->escapeHtml($title); ?></h2>
                        <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"></a>
                      </li>
                      </ul>
                      <div class="clearfix"></div>
                      </div>
                <div class="x_content">


                  <div class="" role="tabpanel" data-example-id="togglable-tabs">
                    <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                      <li role="presentation" class="active"><a href="#std_profile" id="std_profile-tab" role="tab" data-toggle="tab" aria-expanded="true">User Profile</a>
                      </li>
                      <li role="presentation" class=""><a href="#semester" role="tab" id="semester-tab" data-toggle="tab" aria-expanded="false">Semester Result </a>
                      </li>
                      <li role="presentation" class=""><a href="#fees" role="tab" id="fees-tab" data-toggle="tab" aria-expanded="false">Fees </a>
                      </li>
                      <li role="presentation" class=""><a href="#time_table" role="tab" id="time_table-tab" data-toggle="tab" aria-expanded="false">Time Table </a>
                      </li>
                      <li role="presentation" class=""><a href="#academic_calender" role="tab" id="academic_calender-tab" data-toggle="tab" aria-expanded="false">Academic Calender </a>
                      </li>
                      
                    </ul>
                    <div id="myTabContent" class="tab-content">
                      <div role="tabpanel" class="tab-pane fade active in" id="std_profile" aria-labelledby="std_profile-tab">
                          <br>
                          <div class="x_panel">
                          <div table class="responsive"> 
                             
  <!-- page content -->
      <div class="" role="main">

        <div class="">
          
          <div class="clearfix"></div>

          <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
              
                
                <div class="x_content">

                  <div class="col-md-3 col-sm-3 col-xs-12 profile_left">

                    <div class="profile_img">

                      <!-- end of image cropping -->
                      <div id="crop-avatar">
                        <!-- Current avatar -->
                        <div class="avatar-view" title="Change the profile">
                          <img src="../images/subba.jpg" alt="Subba">
                        </div>

                        <!-- Cropping modal -->
                        <div class="modal fade" id="avatar-modal" aria-hidden="true" aria-labelledby="avatar-modal-label" role="dialog" tabindex="-1">
                          <div class="modal-dialog modal-lg">
                            <div class="modal-content">
                              <form class="avatar-form" action="crop.php" enctype="multipart/form-data" method="post">
                                <div class="modal-header">
                                  <button class="close" data-dismiss="modal" type="button">&times;</button>
                                  <h4 class="modal-title" id="avatar-modal-label">Change Picture</h4>
                                </div>
                                <div class="modal-body">
                                  <div class="avatar-body">

                                    <!-- Upload image and data -->
                                    <div class="avatar-upload">
                                      <input class="avatar-src" name="avatar_src" type="hidden">
                                      <input class="avatar-data" name="avatar_data" type="hidden">
                                      <label for="avatarInput">Local upload</label>
                                      <input class="avatar-input" id="avatarInput" name="avatar_file" type="file">
                                    </div>

                                    
                                    
                                    
                                  </div>
                                </div>
                                
                                  
                                  
                                  
                              </form>
                            </div>
                          </div>
                        </div>
                        <!-- /.modal -->

                        <!-- Loading state -->
                        <div class="loading" aria-label="Loading" role="img" tabindex="-1"></div>
                      </div>
                      <!-- end of image cropping -->

                    </div>
                    <h3>MangYukHang Subba</h3>

                    <ul class="list-unstyled user_data">
					<li>
                        <i class="fa fa-education"></i> I Semester 2017
                      </li>
                      
                      <li>
                        <i class="fa fa-tasks user-profile-icon"></i> B.sc Computer Science
                      </li>

                      <li class="m-top-xs">
                        <i class="fa fa-external-link user-profile-icon"></i>
                        <a href="#" target="_blank">www.cst.edu.bt</a>
                      </li>
                    </ul>

                    <br />


                  </div>
                  <div class="col-md-9 col-sm-9 col-xs-12">

                    <div class="profile_title">
                      <div class="col-md-6">
                        <h2>User Activity Report</h2>
                      </div>
                        
                      <div class="col-md-6">
                        <div id="reportrange" class="pull-right" style="margin-top: 5px; background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #E6E9ED">
                          <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>
                          <span>Feburary 05, 2017 - December, 2017</span> <b class="caret"></b>
                        </div>
                      </div>
                    </div>
                      <br>
                    <!-- start of user-activity-graph -->
                    <div id="graph_bar" style="width:100%; height:280px;">
                        
                        
                        <div class="col-md-6 col-sm-6 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2>Pie Graph</h2>
                  <ul class="nav navbar-right panel_toolbox">
                   
                  </ul>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">
<!-- pie chart -->
                    
                 <div class="col-md-6 col-sm-6 col-xs-12">
            <div>
              
              <div class="x_content">

                <table class="" style="width:100%">
                  <tr>
                    <th style="width:15%;">
                      Attendance %
                    </th>
                    
                  </tr>
                  <tr>
                      <td><img src="../images/att.jpg" width="180" height="180"></td>
                    
                    <td>
                      <table class="tile_info">
                        <tr>
                          <td>
                            <p><i class="fa fa-square blue"></i>Presnt </p>
                          </td>
                          <td>90%</td>
                        </tr>
                        <tr>
                          <td>
                            <p><i class="fa fa-square red"></i>Absent </p>
                          </td>
                          <td>10%</td>
                        </tr>
                        
                      </table>
                    </td>
                  </tr>
                </table>
              </div>
            </div>
          </div>   
                    
                    
               <!-- end pae chart -->     
                 

                </div>
              </div>
            </div>
                        
                        <div class="col-md-6 col-sm-6 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2>Bar Graph</h2>
                  <ul class="nav navbar-right panel_toolbox">
                      
                  </ul>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    
                    <table>
                        <tr>
                    <th style="width:15%;">
                      Academic Performance
                    </th>
                    
                  </tr>
                    <tr>
                      <td><img src="../images/std_activites.jpg" width="190" height="190"></td>
                    
                    <td>
                      
                    </td>
                  </tr>
                    </table>
                  

                      
                </div>
              </div>
            </div>
                        
                    </div>
                    <!-- end of user-activity-graph -->
                    <br>
                    
                  </div>
                    <div class="col-md-12 col-sm-12 col-xs-12">
                    
                    <div class="" role="tabpanel" data-example-id="togglable-tabs">
                      <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                        <li role="presentation" class="active"><a href="#recent_activity" role="tab" id="recent_activity-tab"  data-toggle="tab" aria-expanded="true">Recent Activity</a>
                        </li>
                        <li role="presentation" class=""><a href="#assignment" role="tab" id="assignment-tab" data-toggle="tab" aria-expanded="false">Assignments</a>
                        </li>
                        <li role="presentation" class=""><a href="#others" role="tab" id="others-tab" data-toggle="tab" aria-expanded="false">Others</a>
                        </li>
                        
                      </ul>
                      <div id="myTabContent" class="tab-content">
                        <div role="tabpanel" class="tab-pane fade active in" id="recent_activity" aria-labelledby="recent_activity-tab">
<div class="container">
  
  
  <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
    <strong>Activity 1!</strong> You should <a href="#" class="alert-link">read this message</a>.
  </div>
  <div class="alert alert-info">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
    <strong>Activity 2!</strong> You should <a href="#" class="alert-link">read this message</a>.
  </div>
  
  
</div>
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="assignment" aria-labelledby="assignment-tab">
<div class="container">
  
  
  <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
    <strong>Assignment 1!</strong> You should <a href="#" class="alert-link">read this message</a>.
  </div>
  <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
    <strong>Assignment 2!</strong> You should <a href="#" class="alert-link">read this message</a>.
  </div>
</div>

                        </div>
                          <div role="tabpanel" class="tab-pane fade" id="others" aria-labelledby="others-tab">


-------

            
                        </div>
                        
                      </div>
                    </div>
                  </div>
                </div>
              
            </div>
          </div>
        </div>

        
      </div>
      <!-- /page content -->                            
                              
                              
                              
                              
                              
                              
                              
                              
                              
                          </div></div>
                    
                      </div>
                      <div role="tabpanel" class="tab-pane fade" id="semester" aria-labelledby="semester-tab">
                        <br>
                          <div class="x_panel">
                          <div table class="responsive"> 
                              <table class="table table-striped jambo_table bulk_action" boder="2">
   
 
                     
 
<div class="row">
           <button class="btn btn-primary">Content Coming Soon</button>
           </div>
 <div class="row">                                 
 
     
 </div>
                              </table>
                          </div></div>
                      </div>
                      
                        
                        <div role="tabpanel" class="tab-pane fade" id="fees" aria-labelledby="fees-tab">
                        <br>
                          <div class="x_panel">
                          <div table class="responsive"> 
                              <table class="table table-striped jambo_table bulk_action" boder="2">
   
 
  
         
             <div class="row">
           <button class="btn btn-danger">Content Coming Soon</button>
           </div>
 <div class="row">                                 

     
 </div>
                              </table>
                          </div></div>
                      </div>
                        
                        
                        <div role="tabpanel" class="tab-pane fade" id="time_table" aria-labelledby="time_table-tab">
                        <br>
                          <div class="x_panel">
                          <div table class="responsive"> 
                              <table class="table table-striped jambo_table bulk_action" boder="2">
   
 
         
             <div class="row">
                 
             <div class="x_content">

            <div class="table-responsive">
                  <table class="table   table-striped responsive-utilities jambo_table bulk_action table-bordered">
                    <thead>
                      <tr class="headings">
                        </th>
                        <th class="column-title">Time</th>
                        <th class="column-title">Monday</th>
                        <th class="column-title">Tuesday</th>
                        <th class="column-title">Wednesday</th>
                         <th class="column-title">Thursday</th>
                        <th class="column-title">Friday</th>
                          <th class="column-title">Saturday</th>
                        <th class="bulk-actions" colspan="7">
                          <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                        </th>
                      </tr>
                    </thead>

                    <tbody>
                      <tr class="even pointer">
                       <td class=" ">9:00AM to 10:00AM</td>
                       <td class=" ">9:00AM - 10:00AM,<br>Module:C++,<br/>Tutor:Dorjee,<br/>Class Room</td>
                      <td class=" ">9:00AM - 10:00AM,<br>Module:C++,<br/>Tutor:Dorjee,<br/>Class Room</td>
                       <td class=" "></td>
                        <td class=" ">9:00AM - 10:00AM,<br>Module:C++,<br/>Tutor:Dorjee,<br/>Class Room</td>
                         <td class=" "></td>
                          <td class=" ">9:00AM - 10:00AM,<br>Module:C++,<br/>Tutor:Dorjee,<br/>Class Room</td>
                      </tr>
                      <tr class="even pointer">
                       <td class=" ">10:30AM to 11:30AM</td>
                       <td class=" "></td>
                      <td class=" ">10:30AM - 11:30AM,<br>Module:C++,<br/>Tutor:Dorjee,<br/>Class Room</td>
                       <td class=" "></td>
                        <td class=" ">10:30AM - 11:30AM,<br>Module:C++,<br/>Tutor:Dorjee,<br/>Class Room</td>
                         <td class=" "></td>
                          <td class=" ">10:30AM - 11:30AM,<br>Module:C++,<br/>Tutor:Dorjee,<br/>Class Room</td>
                      </tr>
                      <tr class="even pointer">
                       <td class=" ">11:30AM to 12:30PM</td>
                       <td class=" ">11:30AM - 12:30AM,<br>Module:C++,<br/>Tutor:Dorjee,<br/>Class Room</td>
                      <td class=" "></td>
                       <td class=" ">11:30AM - 12:30AM,<br>Module:C++,<br/>Tutor:Dorjee,<br/>Class Room</td>
                        <td class=" "></td>
                         <td class=" ">11:30AM - 12:30AM,<br>Module:C++,<br/>Tutor:Dorjee,<br/>Class Room</td>
                          <td class=" "></td>
                      </tr>
                      <tr class="even pointer">
                       <td class=" ">2:00PM to 3:00PM</td>
                       <td class=" "></td>
                      <td class=" ">2:00PM - 3:00PM,<br>Module:C++,<br/>Tutor:Dorjee,<br/>Class Room</td>
                       <td class=" "></td>
                        <td class=" ">2:00PM - 3:00PM,<br>Module:C++,<br/>Tutor:Dorjee,<br/>Class Room</td>
                         <td class=" "></td>
                          <td class=" ">2:00PM - 3:00PM,<br>Module:C++,<br/>Tutor:Dorjee,<br/>Class Room</td>
                      </tr>
                      <tr class="even pointer">
                       <td class=" ">3:00PM to 4:00PM</td>
                       <td class=" ">3:00PM - 4:00PM,<br>Module:C++,<br/>Tutor:Dorjee,<br/>Class Room</td>
                      <td class=" "></td>
                       <td class=" ">3:00PM - 4:00PM,<br>Module:C++,<br/>Tutor:Dorjee,<br/>Class Room</td>
                        <td class=" "></td>
                         <td class=" ">3:00PM - 4:00PM,<br>Module:C++,<br/>Tutor:Dorjee,<br/>Class Room</td>
                          <td class=" "></td>
                      </tr>
                      
                    </tbody>
                  </table>
                </div>
                </div>
            </div>
                      
              
                                  
                                  
                                  
                                  
                                  <div role="tabpanel" class="tab-pane fade" id="academic_calender" aria-labelledby="academic_calender-tab">
                        <br>
                          <div class="x_panel">
                          <div table class="responsive"> 
                              <table class="table table-striped jambo_table bulk_action" boder="2">
   
 
         
             <div class="row">
                 
             <div class="x_content">

            <div class="table-responsive">
                  <table class="table   table-striped responsive-utilities jambo_table bulk_action table-bordered">
                    <thead>
                      <tr class="headings">
                        </th>
                        <th>Sl.No</th>
                        <th>Date</th>
                        <th>Activities</th>
                        <th>Responsible Person</th>
                         <th>Status</th>
                        
                        <th class="bulk-actions" colspan="7">
                          <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                        </th>
                      </tr>
                    </thead>

                    <tbody>
                      <tr>
                       <td class=" ">1</td>
                       <td class=" "></td>
                      <td class=" "></td>
                       <td class=" "></td>
                        <td class=" ">Complete</td>
                         
                      </tr>
                      <tr>
                       <td class=" "></td>
                       <td class=" "></td>
                      <td class=" "></td>
                       <td class=" "></td>
                        <td class=" ">Pending</td>
                         
                      </tr>
                      <tr>
                       <td class=" "></td>
                       <td class=" "></td>
                      <td class=" "></td>
                       <td class=" "></td>
                        <td class=" ">Ongoing</td>
                         
                      </tr>
                      
                      
                      
                    </tbody>
                  </table>
                </div>
                </div>
            </div>
                                  
          </div>
        </div>
                  </div>
          
 
                

           </div>
 <div class="row">                                 

     
 </div>
                              </table>
                          </div></div>
                      </div>
                        
                        
                    </div>
                  </div>

                </div>
              </div>
            </div></div></div>
              <div id="custom_notifications" class="custom-notifications dsp_none">
    <ul class="list-unstyled notifications clearfix" data-tabbed_notifications="notif-group">
    </ul>
    <div class="clearfix"></div>
    <div id="notif-group" class="tabbed_notifications"></div>
  </div>
  
 