<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
<div class="menu_section">
<br><br><br>
<ul class="nav side-menu">
	<li><a><i class="fa fa-home"></i>Home<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a href="<?php echo $this->url('index') ?>">Dashboard</a></li>
		</ul>
	</li>
	<li><a><i class="fa fa-graduation-cap"></i>Academic<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>Timetable<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('viewtimetable') ?>">View Student Timetable</a></li>
			</ul>
			</li>
		</ul>
	</li>
	<li><a><i class="fa fa-user"></i>Student Service<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>Hostel Management<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('hostelchangeapplication') ?>">Apply for Hostel Change</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Leave Management<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('applystdleave') ?>">Leave Application</a></li>
			</ul>
			</li>
		</ul>
	</li>
	<li><a><i class="fa fa-user"></i>Counseling Service<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a href="<?php echo $this->url('counselingappointment') ?>">Seek Appointment</a></li>
		</ul>
	</li>
	<li><a><i class="fa fa-users"></i>Alumni<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a href="<?php echo $this->url('viewalumnifaqslist') ?>">View Alumni FAQs List</a></li>
			<li><a href="<?php echo $this->url('viewalumniresourcelist') ?>">View Alumni Resource List</a></li>
		</ul>
	</li>
</ul>
</div>
</div>
