<?php

$basepath = $this->basePath();
$this->headScript()
    ->appendFile($basepath . '/js/jquery/dist/jquery.min.js')
    ->appendFile($basepath . '/js/jquery-validation/dist/jquery.validate.js')
    ->appendFile($basepath . '/js/user/forgot-password.js');
?>

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>RUB-IMS | Forgot Password</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

</head>

<body class="hold-transition login-page">

<div class="login-box">
    <div class="login-logo">
        <a href="#">
            <font color="green">Forgot Password</font>
        </a>
    </div>

    <div class="login-box-body">

        <p class="login-box-msg">
            Please Enter Your Registered Username and Email ID.
        </p>

        <form role="form" class="form-horizontal" method="post" id="forgotPasswordForm"
              data-url="<?= $this->basePath(); ?>">
            <div class="form-group has-feedback"><label>Username: <font color="red">*</font></label>
                <input tabindex="4"
                       type='text'
                       placeholder='Username'
                       id="username"
                       class="email_input form-control"
                       value="" name="username"
                       required
                >
                <span class="glyphicon glyphicon-user form-control-feedback"></span>
            </div>

            <div class="form-group has-feedback"><label>Email ID: <font color="red">*</font></label>
                <input tabindex="4"
                       type='email'
                       placeholder='Email ID'
                       id="email"
                       class="email_input form-control"
                       value="" name="email"
                       required
                >
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            </div>

            <div class="form-group has-feedback"><label>Necessary to check your user type<font color="red">*</font></label><br/>
                <label class="radio-inline">
                    <input tabindex="1"
                           type="radio"
                           name="user_type"
                           value="1"
                           id="radio1"
                           required
                    />&nbsp;STAFF
                </label>

                <label class="radio-inline">
                    <input tabindex="2"
                           type="radio"
                           name="user_type"
                           value="2"
                           id="radio2"
                    />&nbsp;STUDENT
                </label>
		<label class="radio-inline">
                    <input tabindex="4"
                           type="radio"
                           name="user_type"
                           value="4"
                           id="radio4"
                    />&nbsp;JOB APPLICANT
                </label>
            </div>

            <div class="row">
              <div class="col-xs-8">
                 <button type="submit" id='forgotPasswordBtn' tabindex="5" class="btn btn-primary" data-spinner="right"><i class="fa fa-send"></i> Update</button>
              </div>
            <!-- /.col -->
            <div class="col-xs-4">
               <a href="<?= $this->url('auth') . '/view-login'; ?>" tabindex="6" class="btn btn-default" data-spinner="right"><i class="fa fa-arrow-circle-right"></i> Login</a>
            </div><br>
            <br>Note:</b> For Job Applicant - Your registered Email ID is your USERNAME.
        <!-- /.col -->
      </div>

        </form>

    </div>

</div>

</body>
</html>
