<?php
 // module/EmployeeDetail/view/employee-detail/employee-detail/emppersonaldetail.phtml:

 $title = 'Leave Category';
 $this->headTitle($title);
 ?>
<div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                     <!-- <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                     <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>-->
                    </ul>
                  <div class="clearfix"></div>
                  </div>
                
              
               <!--<p>Add class <code>bulk_action</code> to table for bulk actions options on row select</p>-->
              
            <div class="x_content">

               <?php 
                    if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                        echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                        echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                        $messages = $this->flashMessenger()->getMessages();
                        foreach($messages as $message) {
                            echo '<strong>Success!</strong>'. $message;
                        }
                        echo '</div>';
                    }

                    else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                        echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                        echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                        $messages = $this->flashMessenger()->getMessages();
                        foreach($messages as $message) {
                            echo '<strong>Failure!</strong>'. $message;
                        }
                        echo '</div>';
                    }

                ?> 
                
                    <div class="table-responsive">
                      <table class="table table-striped jambo_table bulk_action"> 
                         <div class="form-group">   
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <a href="addplanningcategory"> <button type="submit" class="btn btn-success">Add</button></a>
                                  <div class="ln_solid"></div>
                        </div>      
                      </div> 
                        <thead>
                          <tr class="headings">
                           <th>
                              <input type="checkbox" id="check-all" class="flat">
                            </th>
                            <th class="column-title">Leave Gategory </th>
                            
                            <th class="column-title no-link last"><span class="nobr">Action</span>
                            </th>
                            <th class="bulk-actions" colspan="7">
                              <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                            </th>
                          </tr>
                        </thead>
                        
                        <tbody>
                     <!--   <?php foreach ($albums as $album) : ?>-->
                          <tr>
                            <!--<td>
                              <input type="checkbox" class="flat" name="table_records">
                            </td>-->
                            <td>1</td>
                            <td></td>
                            <tdl</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <!--<td class=" "><?php echo $this->escapeHtml($album->first_name);?></td>
                            <td class=" "><?php echo $this->escapeHtml($album->last_name);?></td>-->
                           <!-- <td class=" last"> <a href="<?php echo $this->url('album', array('action'=>'edit', 'id' => $album->id));?>">Edit</a>
                            				   <a href="<?php echo $this->url('album', array('action'=>'delete', 'id' => $album->id));?>">Delete</a>
                            </td>-->
                          </tr>
                         <?php endforeach; ?>
                        </tbody>
                          </table>
                      
                    </div>
            </div></div></div></div></div>
            
         
              
       
                