<?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Transfer Applicant Status Update';
 $this->headTitle($title);
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                   <div class="" role="tabpanel" data-example-id="togglable-tabs">
                    <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                      <li role="presentation" class="active"><a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">Transfer Approval List</a>
                      </li>
                      <li role="presentation" class=""><a href="#tab_content2" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false">Transfer Approved List</a>
                      </li>
                      <li role="presentation" class=""><a href="#tab_content4" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false">Update Transferlist</a>
                      </li>
                    </ul>
                    <div id="myTabContent" class="tab-content">
                      <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab">
                       <br/> 
                       <p> <div class="x_panel"> 
            <div class="x_content">
                <div class="row">  
                <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Working Agency
                    </label>
                <?php  echo $this->formRow($form->get('working_agency')); ?>
                    </div> </div><br/>
                    <table class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                            
                             <th class="column-title">Sl.No. </th>
                              <th class="column-title">Working Agency </th>
                              <th class="column-title">Staff Name </th>
                               <th class="column-title">Staff ID </th>
                             <th class="column-title">Application Receive Date </th>
                            <th class="column-title no-link last"><span class="nobr">Approval</span>
                            </th>
                           
                          </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>1</td>
                                <td>Sherubtse College</td>
                                <td>Dorji</td>
                                <td>RUB231</td>
                                <td>12/2/2016</td>
                                <td><a href="transferapproval"><u>Click here<u/></a></td>
                            </tr>
                             <tr>
                                <td>2</td>
                                <td>Gedu College</td>
                                <td>Sangay</td>
                                <td>RUB238</td>
                                <td>1/2/2016</td>
                                <td><a href="transferapproval"><u>Click here<u/></a></td>
                            </tr>
                             <tr>
                                <td>3</td>
                                <td>Samtse College</td>
                                <td>Pema</td>
                                <td>RUB239</td>
                                <td>2/2/2016</td>
                                <td><a href="transferapproval"><u>Click here<u/></a></td>
                            </tr>
                        </tbody>
                      </table>
            </div></div>
                     </p>
                      </div>
                      <div role="tabpanel" class="tab-pane fade" id="tab_content2" aria-labelledby="profile-tab">
                        <p>
                         
                        <div class="x_panel"> 
            <div class="x_content">
                 <div class="row"> 
                <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Working Agency
                    </label>
                <?php  echo $this->formRow($form->get('working_agency')); ?>
                    </div> </div><br/>
                    <table class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                            
                             <th class="column-title">Sl.No. </th>
                              <th class="column-title">Working Agency </th>
                              <th class="column-title">Staff Name </th>
                               <th class="column-title">Staff ID </th>
                             <th class="column-title">Application Receive Date </th>
                            <th class="column-title">Remarks </th>
                            <th class="column-title no-link last"><span class="nobr">Update</span>
                            </th>
                           
                          </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>1</td>
                                <td>Sherubtse College</td>
                                <td>Dorji</td>
                                <td>RUB231</td>
                                <td>12/2/2016</td>
                                <td></td>
                                <td><a href="">Click here(transfer order in pdf print)</a></td>
                            </tr>
                             <tr>
                                <td>2</td>
                                <td>Gedu College</td>
                                <td>Sangay</td>
                                <td>RUB238</td>
                                <td>1/2/2016</td>
                                <td></td>
                                <td><a href="">Click here</a></td>
                            </tr>
                             <tr>
                                <td>3</td>
                                <td>Samtse College</td>
                                <td>Pema</td>
                                <td>RUB239</td>
                                <td>2/2/2016</td>
                                <td></td>
                                <td><a href="">Click here</a></td>
                            </tr>
                        </tbody>
                      </table>
            </div></div>
                </div>
                        
                        
                        <div role="tabpanel" class="tab-pane fade" id="tab_content4" aria-labelledby="profile-tab">
                        <p>
                          <div class="x_panel">  
                        <div class="x_content">
                  <br />
             <?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Employee Details ';
 $this->headTitle($title);
?> 
              
                   <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title)?></h2>
                   <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                    </ul> 
                 <div class="clearfix"></div>
              
                </div>
                   
                <div class="x_content">
                <form>   
                 <div class="row">
                  <div class="col-md-4 col-sm-12 col-xs-12 form-group">
                      <label>Employee Name</label>
                    <input type="text" placeholder="Dorjee  Wangmo Wangda" class="form-control" readonly>
                  </div>

                  <div class="col-md-4 col-sm-12 col-xs-12 form-group">
                      <label>Employee ID</label>
                    <input type="text" placeholder="RUB2345" class="form-control" readonly>
                  </div>

                  <div class="col-md-4 col-sm-12 col-xs-12 form-group">
                      <label>Position Title</label>
                    <input type="text" placeholder="Finance Officer" class="form-control" readonly>
                  </div>

                  
                </div>
                    <div class="row">
                        <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Citizenship  Identity  Card</label>
                    <input type="text" placeholder="10504050409" class="form-control" readonly>
                  </div>
                      <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Date of Birth</label>
                    <input type="text" placeholder="03-04-1979" class="form-control" readonly>
                  </div>
                        <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Agency Location</label>
                    <input type="text" placeholder="Thimphu" class="form-control" readonly>
                  </div>
                 <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Contact No.</label>
                    <input type="text" placeholder="18734532" class="form-control" readonly>
                  </div>
                        
                      </div>
                    <div class="row">
                        <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Permanent Address</label>
                    <input type="text" placeholder="Nobgang,Samar,Haa" class="form-control" readonly>
                  </div>
                      <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Current Working Agency</label>
                    <input type="text" placeholder="OVC" class="form-control" readonly>
                  </div>
                        <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Current Major Occupational Group</label>
                    <input type="text" placeholder="ICT" class="form-control" readonly>
                  </div>
                 <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Current Sub Occupational Group</label>
                    <input type="text" placeholder="Network Administrator" class="form-control" readonly>
                  </div>
                        
                      </div>
                    <div class="row">
                        <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Current Position Category</label>
                    <input type="text" placeholder="Executive" class="form-control" readonly>
                  </div>
                      <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Current Position Title</label>
                    <input type="text" placeholder="ICT Officer" class="form-control" readonly>
                  </div>
                        <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Current Position Level</label>
                    <input type="text" placeholder="Grade-6" class="form-control" readonly>
                  </div>
                 <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Current Pay Scale</label>
                    <input type="text" placeholder="Nu.30,000" class="form-control" readonly>
                  </div>
                      </div>
                     
                      </form>
                  
          </div>
        </div>
                  </div>
              
              <?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'New Location (OVC/College)';
 $this->headTitle($title);
?>
              
              
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title)?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                    </ul>
                 <div class="clearfix"></div>
              
                </div>
                   
                <div class="x_content">
                  <br />
                   <?php
                   $form->prepare();
                   echo $this->form()->openTag($form);

                   echo $this->formHidden($form->get('id'));   
                ?>
                <div class="row"> 
                   
                 <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Transfer Order No. 
                    </label>
                <?php  echo $this->formRow($form->get('transfer_order_no')); ?>
                </div>
            
                 <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Transfer Order Date 
                    </label>
                <?php  echo $this->formRow($form->get('transfer_order_date')); ?>
                    </div>
                   <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Date of Joining this Agency
                    </label>
                <?php  echo $this->formRow($form->get('joining_date_this_agency')); ?>
                    </div>   
                  
                 <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Date of Joining New Agency
                    </label>
                <?php  echo $this->formRow($form->get('joining_date_new_agency')); ?>
                    </div>
                     </div>
                    
                     <div class="row">    
                 <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Working Agency
                    </label>
                <?php  echo $this->formRow($form->get('working_agency')); ?>
                    </div>
                      
                 <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Position Category
                    </label>
                <?php  echo $this->formRow($form->get('position_category')); ?>
                    </div>
                   <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Position Title
                    </label>
                <?php  echo $this->formRow($form->get('position_title')); ?>
                    </div>
                 <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Position Level
                    </label>
                <?php  echo $this->formRow($form->get('position_level')); ?>
                    </div>      
                     </div>
                    
                     <div class="row"> 
                    
                    
                 <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Pay Scale
                    </label>
                <?php  echo $this->formRow($form->get('pay_scale')); ?>
                    </div>
                   
                 <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Transfer Reasons 
                    </label>
                <?php  echo $this->formRow($form->get('transfer_reasons')); ?>
                    </div>
                 </div>
                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Upload transfer order
                    </label>
              <?php  echo $this->formRow($form->get('upload')); ?>
                    </div>
                 </div>   
                  
                <div class="row">
                        <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                              <div class="col-md-6 col-sm-6 col-xs-12">
                                  <?php
                        echo $this->formSubmit($form->get('submit')); 
                      ?>
                    </div>
                    </div>
                    </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
          </div>
        </div>
                  </div>
       </div></div>
                </div>
                </div>
              </p>
             </div>
          </div>
        </div>
       </div>
   </div>
 </div>
            

