<?php
 // module/EmployeeDetail/view/employee-detail/employee-detail/emppersonaldetail.phtml:

 $title = 'Update Plan Monitoring Status';
 $this->headTitle($title);
 ?>
<div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                  </div>
                    
                  <div class="x_content">
                    <br/>
                   
                        
                        
                        <?php
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        
                        echo $this->formHidden($form->get('id'));
                        ?>
                        <div class="row">
                            
                          <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Plan Category<span class="required">*</span>
                        </label>
                              <div class="col-md-4 col-sm-4 col-xs-12">
                        <?php
                        echo $this->formRow($form->get('planning_category'));
                        ?>
                          </div>
                          </div>  
                        </div>  
                    <div class="row">
                        <div class="form-group">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12">Staff Department<span class="required">*</span>
                        </label>
                              <div class="col-md-4 col-sm-4 col-xs-12">
                        <?php
                        echo $this->formRow($form->get('staff_department'));
                        ?>
                          </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12">Staff Name<span class="required">*</span>
                        </label>
                              <div class="col-md-4 col-sm-4 col-xs-12">
                        <?php
                        echo $this->formRow($form->get('staff_name'));
                        ?>
                          </div>
                        </div>
                    </div>
                    <div class="row">
                            
                          <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Uploaded Plan<span class="required">*</span>
                        </label>
                              <div class="col-md-4 col-sm-4 col-xs-12">
                        <?php
                        echo $this->formRow($form->get('planning_document'));
                        ?>
                          </div>
                        </div>  
                        </div>  
                    <div class="row">
                            
                          <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Monitoring Status</label>
                              <div class="col-md-4 col-sm-4 col-xs-12">
                        <?php
                        echo $this->formRow($form->get('plan_monitoring_status'));
                        ?>
                          </div>
                        </div>  
                        </div>       
                    <div class="row">
                        <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12"></label>
                              <div class="col-md-4 col-sm-4 col-xs-12">
                    <?php
                        echo $this->formSubmit($form->get('submit')); 
                        echo $this->formSubmit($form->get('reset')); 
                      ?>
                    </div>
                    </div>
                    </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                       
                    
                  </div></div>
                </div></div></div>
            
         
              
       
                