<?php
 // module/EmployeeDetail/view/employee-detail/employee-detail/emppersonaldetail.phtml:

 $title = 'Evaluator Ratings (DSA/Provosts/PLs/HoDs)';
 $this->headTitle($title);
 ?>
<div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                     <!-- <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                     <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>-->
                    </ul>
                  <div class="clearfix"></div>
                  </div>
              
                  <div class="x_content">
                      
                    <form>   
                 <div class="row">
                
                  <div class="col-md-3 form-group">
                      <label class="control-label">Programme</label>
                      <select class="form-control">
                          <option>--Select--</option>
                          
                      </select>
                  </div>
                     <div class="col-md-3 form-group">
                         <label class="control-label"> Year of Admission</label>
                       <select class="form-control">
                          <option>--Select--</option>
                          
                      </select>
                     </div> 
                      </div>
                      <div class="ln_solid"></div>
                      <div class="form-group">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                          <button type="submit" class="btn btn-success">Search</button>
                        </div>
                      </div>
                      </form>
                </div>
                  </div>
              
               <!--<p>Add class <code>bulk_action</code> to table for bulk actions options on row select</p>-->
             <div class="x_panel"> 
            <div class="x_content">
                    <div class="table-responsive">
                      <table class="table table-striped jambo_table bulk_action"> 
                        <thead>
                          <tr class="headings">
                           <!-- <th>
                              <input type="checkbox" id="check-all" class="flat">
                            </th>-->
                            <th class="column-title"> Sl.No.</th>
                            <th class="column-title">Student Name </th>
                            <th class="column-title">Punctuality </th>
                            <th class="column-title">Discipline</th>
                            <th class="column-title">Creativity</th>
                            <th class="column-title">Honesty & Integrity</th>
                            <th class="column-title">Respect for others</th>
                            <th class="column-title">Team Spirit</th>
                            <th class="column-title no-link last"><span class="nobr">Action</span>
                            </th>
                            <th class="bulk-actions" colspan="7">
                              <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                            </th>
                          </tr>
                        </thead>
                        <tbody>
                      <tr class="even pointer">
                       <td class=" ">1</td>
                       <td class=" ">Dorjee</td>
                       <td>Very Good</td>
                       <td>Outstanding</td>
                       <td>Very Good</td>
                       <td>Outstanding</td>
                       <td>Outstanding</td>
                       <td>Outstanding</td>
                       <td> <button class="btn btn-success">submitted</button></td>
                      </tr>
                      <tr class="even pointer">
                       <td class=" ">2</td>
                       <td class=" ">DoWang</td>
                       <td><input type="text" class="form-control"></td>
                       <td><input type="text" class="form-control"></td>
                       <td><input type="text" class="form-control"></td>
                       <td><input type="text" class="form-control"></td>
                       <td><input type="text" class="form-control"></td>
                       <td><input type="text" class="form-control"></td>
                       <td> <button class="btn btn-success">submit</button></td>
                      </tr>
                      <tr class="even pointer">
                       <td class=" ">3</td>
                       <td class=" ">Pema</td>
                       <td><input type="text" class="form-control"></td>
                       <td><input type="text" class="form-control"></td>
                       <td><input type="text" class="form-control"></td>
                       <td><input type="text" class="form-control"></td>
                       <td><input type="text" class="form-control"></td>
                       <td><input type="text" class="form-control"></td>
                       <td> <button class="btn btn-success">submit</button></td>
                      </tr>
                      <tr class="even pointer">
                       <td class=" ">4</td>
                       <td class=" ">Tashi</td>
                       <td><input type="text" class="form-control"></td>
                       <td><input type="text" class="form-control"></td>
                       <td><input type="text" class="form-control"></td>
                       <td><input type="text" class="form-control"></td>
                       <td><input type="text" class="form-control"></td>
                       <td><input type="text" class="form-control"></td>
                       <td> <button class="btn btn-success">submit</button></td>
                      </tr>
                    </tbody>
                          </table>
                      <div class="row">
                        <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-6 col-sm-6 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                    <button class="btn btn-default">Save & Close</button>
                    <button class="btn btn-success">Submit</button>
                 </div>
                </div>
               </div>
                    </div>
            </div></div></div></div></div>
            
         
              
       
                