<?php
/**
 * 
 * View -- of Accounts/AssetController/edittransactionAction
 * 
 */
?>
<?php 
    $title ="Advance Salary Booking Adjustment";
	$total_debit = 0;
	$total_credit = 0;
	
?>
<div class="right_col" role="main">
    <div class="">
        <div class="col-md-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
					<ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>  
                    </ul>
					<div class="clearfix"></div>
                </div><!--end of x-title-->
				<div class ="x_content">
					<form id="transForm" method="post" action="<?php echo $this->url('payroll', array('action' => 'bookadvancesalary')); ?>"  enctype="multipart/form-data" >
					<?php
						$data = array(
							'year' => $this->data['year'],
							'month' => $this->data['month'],
						);
						$sad_employees = $this->payrollObj->getSADEmp($data);
						$Yes_subhead = array();
						$No_subhead = array();
						//print_r($sad_employees); exit;
						foreach($sad_employees as $sad_emp):
							$master_dtls = $this->masterDtlObj->get(array('md.sub_head'=>'28','md.type'=>'5','md.ref_id'=>$sad_emp['employee_details']));
							if(sizeof($master_dtls)>0):
								array_push($Yes_subhead,$sad_emp['employee_details']);
							else:
								array_push($No_subhead,$sad_emp['employee_details']);
							endif;
						endforeach;
						if(sizeof($No_subhead)>0):
					?>
					<div>
						<i class="fa fa-check"></i><strong class="yellow">Salary Booking has been inappropriate.</strong><br>
						<a class="btn btn-xs pull-right btn-danger" id="print" title="Print">
							<i class="ace-icon fa fa-file-pdf-o bigger-120"></i>
						</a>
						<div id="report-print">
						<strong class="yellow">Following <?php echo sizeof($No_subhead);?> Employees doesn't have Advance Salary Subhead for booking in Finance:</strong><br>
						<div class="space-6"></div>
						
						<table class="table table-condensed table-bordered table-striped">
							<thead>
								<tr>
									<th>#</th>
									<th>Employee</th>
									<th>Position</th>
									<th>Organisation</th>
									<th>Department</th>
									<th>Position Level</th>
									<th>Emp Type</th>
								</tr>
							</thead>
							<tbody>
							<?php $j = 1;
								for($sh=0;$sh<sizeof($No_subhead);$sh++):
								$employee = $this->employeeObj->get($No_subhead[$sh]);
								foreach($employee as $emp);
								$emplPr = $this->pemplObj->get(array('employee_details'=>$emp['id']));
								foreach($emplPr as $his);
							?>
								<tr>
									<td><?php echo $j++;?></td>
									<td><?php echo $emp['first_name']." ".$emp['middle_name']." ".$emp['last_name'];?></td>
									<td><?php echo $this->postitleObj->getColumn($emp['position_title_id'],'position_title');?></td>
									<td><?php echo $emp['organisation'];?></td>
									<td><?php echo $emp['department_name'];?></td>
									<td><?php echo $this->postlevelObj->getColumn($emp['position_level_id'],'position_level');?></td>
									<td><?php echo $this->etypeObj->getColumn($his['emp_type_id'],'employee_type');?></td>
								</tr>
							<?php endfor;?>
							</tbody>
						</table>
						<strong class="yellow">Please create Subheads for these employees for advance salary booking. And try again.</strong>
						</div>
					</div>
					<?php else:?>   
						<div class="row"> 
							<div class="col-lg-4">    
								<div class="form-group">
									<label for="voucher_date" class="control-label">Voucher Date</label>
									<div class="date input-group" id="voucher_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
										<input class="form-control span2" name="voucher_date" id="voucher_date" type="text" placeholder="Voucher Date" value="<?php echo date('Y-m-d');?>" readonly required>
										<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
									</div>
								</div>
							</div>
							<div class="col-lg-4">
								<label for="voucher_type" class="control-label">Voucher Type</label>
								<select id="voucher_type" name="voucher_type" class="form-control" data-placeholder="Select" required >
									<option value=""></option>
									<?php 
									foreach ($journals as $journal):
									?>
										<option value="<?php echo $journal['id'];?>">
										<?php echo $journal['journal']; ?>
										</option>
									<?php 
									endforeach;
									?>
								</select>
							</div>					
							<div class="col-lg-4">
								<div class="form-group">
									<label for="voucher_amount">Voucher Amount(<?php echo $this->currency_code();?>)</label>
									<input type="text" class="form-control" name="voucher_amount" id="voucher_amount" value="" required  readonly > 
								</div>
							</div>    
						</div>
						<div class="row">
							<div class="col-lg-12"> 
								<label>Transaction Details</label>
								<table id="trdetails_table" class="table small-padding">
									<thead>
										<tr>
											<th>Details</th>
											<th>Debit(<?php echo $this->currency_code();?>)</th>
											<th>Credit(<?php echo $this->currency_code();?>)</th>
											<th>&nbsp;</th>
										</tr>
									</thead>
									<tbody>
										<?php 
										$rownum = 1;
										foreach($this->organisations as $org_row):
												$data = array(
													'year' => $this->data['year'],
													'month' => $this->data['month'],
													'organisation' => $org_row['organisation_id'],
												);
												$master_dtls = $this->payrollObj->salaryAdvanceMasterDtls($data);
												$sum_debit = 0;
												foreach($master_dtls as $master_dtls_row):
													$payroll_id = $this->payrollObj->getColumn(array('employee_details' =>$master_dtls_row['ref_id'],'organisation_id'=>$org_row['organisation_id'],'year'=>$data['year'],'month'=>$data['month']),'id');
													$amt = $this->paydetailObj->getColumn(array('pay_roll'=>$payroll_id,'pay_head'=>'16'),'amount');
													
													if((int)$amt > 0):
														$credit_amt = $amt;
														$debit_amt = '0.00';
														$total_debit += $debit_amt;
														$total_credit += $credit_amt;
													?>
														<tr id="<?php echo $rownum;?>">
															<td class="col-lg-3">
																<?php echo $master_dtls_row['name']; ?>
															</td>
															<td class="col-lg-2">
																<?php echo $debit_amt;?>      
															</td>
															<td class="col-lg-2"> 
																<?php echo $credit_amt;?>        
															</td>
															<td width="30px;">
															</td>
														</tr>
														<?php $rownum++;?>
													<?php endif;
													$sum_debit +=$amt;
												endforeach;//end of subhead foreach
										endforeach;//end of location foreach
										?>
										<tr id="<?php echo $rownum; ?>">
											<td class="col-lg-4">
												<div class="form-group">
													<select id="sub_head" name="sub_head[]" class="form-control" data-placeholder="Select">
														<option value=""></option>
														<?php 
														foreach($bankdetls as $row);
														foreach ($this->materdtlsObj->get(array('md.ref_id'=>$row['id'],'md.type'=>'2')) as $mast_row):
														$selected = ($row['id']= $mast_row['ref_id'])?'selected':'';?>
															<option value="<?php echo $mast_row['id']; ?>" <?php echo $selected;?>>
																<?php echo $mast_row['sub_head']; ?>
															</option>
														<?php  endforeach; ?>
													</select>
												</div>
											</td>											
											<td class="col-lg-4">
												<div class="form-group">
													<input type="text" class="form-control tr_debit" name="debit[]" id="debit" value="<?php echo $sum_debit;?>"  >
												</div>     
											</td>
											<td class="col-lg-4">
												<div class="form-group">
													<input type="text" class="form-control tr_credit" name="credit[]" id="credit" value="0.00" >
												</div>      
											</td>
											<td width="30px;">
											</td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-6"></div>
							<div class="col-lg-3">
								<div class="form-group">
									<label for="total_debit">Total Debit(<?php echo $this->currency_code();?>)</label>
									<input type="text" class="form-control" name="total_debit" id="total_debit" data-match="#total_credit" value="<?php echo $total_debit;?>" readonly />
									<div class="help-block with-errors"></div> 
								</div>
							</div> 
							<div class="col-lg-3">
								<div class="form-group">
									<label for="total_credit">Total Credit(<?php echo $this->currency_code();?>)</label>
									<input type="text" class="form-control" name="total_credit" id="total_credit"  value="<?php echo $total_credit?>" readonly />
									<div class="help-block with-errors"></div> 
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-12">
								<div class="form-group">
									<label for="remarks">Remark</label>
									<?php $remark = "Being the Advance Salary Deduction for the month of ".date('F Y',strtotime($this->data['year'].'-'.$this->data['month'].'-01'));?>
									<textarea class="form-control" name="remark" id="remark" ><?php echo $remark;?></textarea>  
								</div>
							</div>
						</div>
						<input type="hidden" name="year" id="year" value="<?php echo $this->data['year'];?>"/>
						<input type="hidden" name="month" id="month" value="<?php echo $this->data['month'];?>"/>
						<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
					<?php endif;?>
						<button type="button" class="btn btn-warning" onclick="javascript:history.back();"><i class="fa fa-times"></i> Cancel </button> 
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	//$('form select').chosen({ allow_single_deselect:false});
	$(function() {
		$('#voucher_date').datepicker();		
		$('#trdetails_table').salarytransaction({
		    getMatDetail:'<?php echo $this->url("transaction", array("action" => "getmasterdtl"));?>',
			tot_debit: '<?php echo $total_debit;?>',
			tot_credit:'<?php echo $total_credit;?>',
		});	
		//formValidation
		$('form')         
		.formValidation({
			framework: 'bootstrap',
	        excluded: ':disabled',
	        message: 'This value is not valid',
	        fields: {
	            'voucher_date': {
	                validators: {
	                    notEmpty: {
	                        message: 'Please enter voucher date'
	                    }
	                }
	            },
	            'voucher_type': {
	                validators: {
	                    notEmpty: {
	                        message: 'Please select voucher type'
	                    }
	                }
	            },
	            'voucher_amount': {
	                validators: {
	                    callback: {
	                        message: 'Transaction cannot happen without any amount',
	                        callback: function(value, validator, $field) {
	                            // Get the selected options
	                            var value = validator.getFieldElements('voucher_amount').val();
	                            return (value != null && value > 0);
	                        }
	                    }
	                }
	            }, 
	            'location[]': {
	                validators: {
	                    notEmpty: {
	                        message: 'Please select location'
	                    }
	                }
	            },
	            'sub_head[]': {
	                validators: {
	                    notEmpty: {
	                        message: 'Please select subhead'
	                    }
	                }
	            }, 
	            'total_debit': {
	                validators: {
	                	 identical: {
	                         field: 'total_credit',
	                         message: 'Total credit must be equal to total dedit'
	                     }
	                }
	            }, 
	            'total_credit': {
	                validators: {
	                	 identical: {
	                         field: 'total_debit',
	                         message: 'Total debit must be equal to total credit'
	                     }
	                }
	            },           
	        }
		})
		.on('success.field.fv', function(e, data) {
            if (data.fv.getInvalidFields().length > 0) {    // There is invalid field
                data.fv.disableSubmitButtons(true);
            }
        });
		$('#voucher_date').on('changeDate',function(){
			$('form').formValidation('revalidateField', $(this).attr('id'));
		});
	
	});// end of my function
</script> 
