<?php
/**
 *
 * Index -- of Payroll
 *
 */
$this->headTitle($title);

$key = $this->keyphrase;
 
function my_encrypt($data, $key) {
    $encryption_key = base64_decode($key);
    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}
?>
<div class="right_col" role="main">
    <div class=" ">
        <div class="col-md-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="">
                        <a class="btn btn-success" style="float: right;" href="<?php echo $this->url('payroll', array('action' => 'bulkadd')); ?>"> Add Bulk Payrolls</a>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <br/>
                <div class="col-md-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2><?php echo $this->escapeHtml("Search for Employee") ?></h2>
                            <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                </li>
                            </ul>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <h5><i>*(In order to view the employee information, first select the Organisation and then search for the Employee name or Employee Id and select the Employee from the table below to view the information. Input as many fields as possible to narrow the search.)<br />
                                    **Also note, search by name is done by "First Name" only and Employee ID should be full.</i></h5>
                            <br />
                            <?php
                            // Opening of the form tag
                            $form->prepare();
                            echo $this->form()->openTag($form);
                            ?>
                            <div class="row">
                                <div class="col-md-4 col-sm-12 col-xs-12 form-group">
                                    <label>Organisation</label>
                                    <?php echo $this->formRow($form->get('organisation_id')
                                            ->setAttribute('options', $this->organisation_lists)); ?>
                                </div>
                                <div class="col-md-4 col-sm-12 col-xs-12 form-group">
                                    <label>Employee Name</label>
                                    <?php echo $this->formRow($form->get('employee_name')); ?>
                                </div>
                                <div class="col-md-4 col-sm-12 col-xs-12 form-group">
                                    <label>Employee ID</label>
                                    <?php echo $this->formRow($form->get('employee_id')); ?>
                                </div>
                            </div>
                            <div class="row">
                                <div class="ln_solid"></div>
                                <div class="form-group">
                                    <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                                    <?php
                                        echo $this->formSubmit($form->get('submit'));
                                        echo $this->form()->closeTag();
                                    ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2><?php echo $this->escapeHtml("List of Employee(s)"); ?></h2>
                            <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                </li>
                            </ul>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <div  class="table-responsive">
                                <table id="datatable-buttons" class="table table-striped responsive-utilities jambo_table bulk_action table-bordered">
                                    <thead>
                                        <th class="column-title">Sl No </th>
                                        <th class="column-title">Name </th>
                                        <th class="column-title">Employee ID </th>
                                        <th class="column-title">Department</th>
                                        <th class="column-title" width="280">Designation</th>
                                        <th class="column-title last">Action</th>
                                    </thead>
                                    <tbody>
                                        <?php $i = 1;
                                        foreach ($this->employeelist as $employee) : ?>
                                            <tr class="even pointer">
                                                <td class=" "><?php echo $i; ?></td>
                                                <td class=" "><?php echo $this->escapeHtml($employee['employee_full_name']); ?></td>
                                                <td class=" "><?php echo $this->escapeHtml($employee['emp_id']); ?></td>
                                                <td class=" "><?php echo $this->escapeHtml($employee['role']); ?></td>
                                                <td class=" "><?php echo $this->escapeHtml($employee['department_name']); ?></td>
                                                <td class=" last">
                                                    <a href="<?php echo $this->url('payroll', array('action' => 'viewemployeedetail' , 'id' => my_encrypt($employee['id'], $key))); ?>" class="btn btn-primary btn-xs"><i class="fa fa-eye"></i> View Detail</a>
                                                    <br>
                                                    <a href="<?php echo $this->url('payroll', array('action' => 'addempearningdeduction' , 'id' => my_encrypt($employee['id'], $key))); ?>" class="btn btn-success btn-xs"><i class="fa fa-eye"></i> Earning/Deduction</a>
                                                </td>
                                            </tr>
                                            <?php $i++;
                                        endforeach;   ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
