<?php

/**
 *
 * View -- of Asse/PayrollController/viewpayrollemployeeAction
 *
 */
$this->headTitle($this->title);

$key = $this->keyphrase;

function my_encrypt($data, $key) {
    $encryption_key = base64_decode($key);
    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}

$empl_jps = []; 
//foreach ( $this->payroll as $payroll ) ;

foreach ( $this->payrollService->getEmployeeDetailsData($this->employeeDetail['id']) as $employee_details ) ;

$organisation_name = $this->payrollService->getOrganisationDataColumn($employee_details['organisation_id'],'organisation_name');

foreach ( $this->payrollService->getJobProfileData(array('employee_details' => $this->employeeDetail['id'])) as $empl_jps ) ;
?>
<div class="right_col" role="main">
    <div class=" ">
        <?php if ( empty($this->employee_earning_data) || empty($empl_jps) ) { ?>
            <div class="col-lg-12">
                <div class="alert alert-danger">
                    <?php if ( empty($this->employee_earning_data) && empty($empl_jps) ): ?>
                        Please add employee Earnings and Deduction & Job Profile
                    <?php elseif ( empty($empl_jps) ): ?>
                        Please add employee Job Profile
                    <?php elseif ( empty($this->employee_earning_data) ): ?>
                        Please add employee Earnings and Deduction
                    <?php endif; ?>
                </div>
            </div>
        <?php } ?>
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->title; ?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <!--end of x-title-->

                <div class="clearfix"></div>

                <?php $flashMessenger = $this->flashMessenger(); ?>

                <?php if ( ($this->message_status == 'Success' || $this->message_status == '') && $flashMessenger->hasMessages() ): ?>
                    <div class="alert alert-success alert-dismissible fade in" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                        <?php foreach ( $flashMessenger->getMessages() as $msg ): ?>
                            <strong>Success!</strong> <?php echo $msg ?>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>

                <?php if ( $this->message_status == 'Failure' && $flashMessenger->hasMessages() ): ?>
                    <div class="alert alert-danger alert-dismissible fade in" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                        <?php foreach ( $flashMessenger->getMessages() as $msg ): ?>
                            <strong>Failure!</strong> <?php echo $msg ?>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>
                <a class="pull-right btn btn-primary"
                   href="<?php echo $this->url('payroll', array('action' => 'addempearningdeduction', 'id' => my_encrypt($employee_details['id'], $key))); ?>">
                    <span class="white"><i class="fa fa-plus"></i> <span class="hidden-sm hidden-xs">&nbsp;Add Earnings & Deductions </span></span>
                </a>
                <div class="x_content">
                    <form id="form" method="post">

                        <h5 class="widget-title">
                            Payroll of
                            <strong><?php echo $employee_details['first_name'] . " " . $employee_details['middle_name'] . " " . $employee_details['last_name']; ?></strong>
                           <!-- <?php echo $this->status(0); ?> -->
                        </h5>

                        <div class="row">
                            <div class="col-lg-4">
                                <ul class="list-unstyled spaced">
                                    <li>
                                        <i class="ace-icon fa fa-caret-right blue"></i>
                                        Name: <b class="red">
                                            <a class="red"
                                               href="javascript:void(0);">
                                                <?php echo $employee_details['first_name'] . " " . $employee_details['middle_name'] . " " . $employee_details['last_name']; ?>
                                            </a>
                                        </b>
                                    </li>

                                    <li>
                                        <i class="ace-icon fa fa-caret-right blue"></i>
                                        Cid No: <b class="red"> <?php echo $employee_details['cid']; ?></b>
                                    </li>
                                </ul>
                            </div>

                            <div class="col-lg-4">
                                <ul class="list-unstyled spaced">
                                    <li>
                                        <i class="ace-icon fa fa-caret-right blue"></i>
                                        Employee ID: <b class="red"> <?php echo $employee_details['emp_id']; ?></b>
                                    </li>

                                    <li>
                                        <i class="ace-icon fa fa-caret-right blue"></i>
                                        Position Level: <b
                                                class="red"> <?php echo (isset($empl_jps['position_title_id'])) ? $this->payrollService->getPositionTitleDataColumn($empl_jps['position_title_id'], 'position_title') : '-'; ?> </b>
                                    </li>
                                </ul>
                            </div>

                            <div class="col-lg-4" id="convert-tb1">
                                <ul class="list-unstyled spaced">
                                    <li>
                                        <i class="ace-icon fa fa-caret-right blue"></i>
                                        Position Title: <b
                                                class="red"> <?php echo (isset($empl_jps['position_level_id'])) ? $this->payrollService->getPositionLevelDataColumn($empl_jps['position_level_id'], 'position_level') : '-'; ?> </b>
                                    </li>

                                    <li>
                                        <i class="ace-icon fa fa-caret-right blue"></i>Organisation: <b
                                                class="red"> <?php echo $organisation_name; ?> </b>
                                    </li>
                                </ul>
                            </div>

                        </div>

                        <div class="hr dotted"></div>

                        <div class="row">
                            <div class="col-lg-2">
                                <label for="month" class="control-label">Month </label>
                                <select class="form-control" name="month" id="month" data-placeholder="Select" required>
                                    <?php $selectedMonth = date('m'); 
                                    
                                    ?>
                                    <?php for ( $m = 1; $m <= 12; $m++ ): ?>
                                        <option value="<?php echo $m; ?>" <?php echo ($selectedMonth == $m) ? 'selected="selected"' : '' ?> >
                                            <?php echo date("F", strtotime(date("d-$m-y"))); ?>
                                        </option>
                                    <?php endfor; ?>
                                </select>
                            </div>

                            <div class="col-lg-1">
                                <label for="year" class="control-label">Year </label>
                                <select class="form-control" name="year" id="year" data-placeholder="Select" required>
                                    <?php for ( $y = date('Y'); $y > 2005; $y-- ): ?>
                                        <option value="<?php echo $y; ?>">
                                            <?php echo $y; ?>
                                        </option>
                                    <?php endfor; ?>
                                </select>
                            </div>

                            <div class="form-group col-lg-2">
                                <label for="working_days" class="control-label">Working Days</label>
                                <input type="text" name="working_days" id="working_days" value="<?php echo date('t'); ?>" class="form-control" placeholder="Working days" required/>
                            </div>

                            <div class="form-group col-lg-2">
                                <label for="leave_without_pay" class="control-label">Leave Without Pay</label>
                                <input type="text" name="leave_without_pay" id="leave_without_pay" class="form-control" value="<?php echo isset($payroll['leave_without_pay']) ? $payroll['leave_without_pay'] : 0 ?>"
                                />
                            </div>

                            <div class="form-group col-lg-2">
                                <label for="status" class="control-label">Status</label>
                                <div class="rm-form-control-width">
                                    <input type="checkbox" name="status" id="status" class="" value="1">
                                </div>
                            </div>

                        </div>

                        <div class="hr dotted"></div>

                        <div class="row">
                            <div class="col-lg-6">
                                <?php echo $this->render('accounts/payroll/add-payroll/earning-lists.phtml') ?>
                            </div>

                            <div class="col-lg-6">
                                <?php echo $this->render('accounts/payroll/add-payroll/deduction-lists.phtml') ?>
                            </div>
                        </div>

                        <div class="hr dotted"></div>

                        <div class="row">
                            <div class="form-group col-lg-3">
                                <label for="earning_dlwp" class="control-label">LWP Amount from
                                    Earnings(<?php echo $this->currency_code(); ?>)</label>
                                <input type="text"
                                       name="earning_dlwp"
                                       id="earning_dlwp"
                                       class="form-control"
                                       placeholder="LWP Amount from Earnings"
                                       value="<?php //echo $payroll['earning_dlwp']; ?>"
                                       readonly
                                />
                            </div>

                            <div class="form-group col-lg-3">
                                <label for="gross" class="control-label green"><b>Gross
                                        Pay</b>(<?php echo $this->currency_code(); ?>)</label>
                                <input type="text"
                                       name="gross"
                                       id="gross"
                                       class="form-control"
                                       value=""
                                       readonly
                                />
                            </div>
                            <div class="form-group col-lg-3">
                                <label for="deduction_dlwp" class="control-label">LWP Amount from
                                    Deduction(<?php echo $this->currency_code(); ?>)</label>
                                <input type="text"
                                       name="deduction_dlwp"
                                       id="deduction_dlwp"
                                       class="form-control"
                                       placeholder="LWP Amount from Deduction"
                                       value="<?php //echo $payroll['deduction_dlwp']; ?>"
                                       readonly
                                />
                            </div>
                            <div class="form-group col-lg-3">
                                <label for="total_deduction" class="control-label red"><b>Total
                                        Deduction</b>(<?php echo $this->currency_code(); ?>)</label>
                                <input type="text"
                                       name="total_deduction"
                                       id="total_deduction"
                                       class="form-control"
                                       value="" readonly
                                />
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group col-lg-3">
                                <label for="bonus" class="control-label">Bonus(<?php echo $this->currency_code(); ?>
                                    )</label>
                                <input type="text"
                                       name="bonus"
                                       id="bonus"
                                       class="form-control"
                                       placeholder="bonus"
                                       value="<?php echo isset($payroll['bonus']) ? $payroll['bonus'] : 0; ?>"
                                />
                            </div>
                            <div class="form-group col-lg-3">
                                <label for="leave_encashment" class="control-label">Leave
                                    Encashment(<?php echo $this->currency_code(); ?>)</label>
                                <input type="text"
                                       name="leave_encashment"
                                       id="leave_encashment"
                                       class="form-control"
                                       placeholder="leave encashment"
                                       value="<?php echo isset($payroll['leave_encashment']) ? $payroll['leave_encashment'] : 0; ?>"
                                />
                            </div>
                            <div class="form-group col-lg-3">
                                <label for="net_pay" class="control-label blue"><b>Net
                                        pay</b>(<?php echo $this->currency_code(); ?>)</label>
                                <input type="text"
                                       name="net_pay"
                                       id="net_pay"
                                       class="form-control"
                                       value=""
                                       readonly
                                />
                            </div>
                            <div class="col-lg-3">
                                <label>&nbsp;</label>
                                <div>
                                    <?php if ( !empty($this->employee_earning_data) && !empty($empl_jps) ) { ?>
                                        <button type="submit"
                                                class="btn btn-success">
                                            <i class="fa fa-check"></i> Save
                                        </button>
                                    <?php } ?>
                                    <a class="btn btn-warning"
                                       onclick="window.history.go(-1); return false;">
                                        <i class="fa fa-times"></i> Cancel
                                    </a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>

            </div>

            <div class="x_panel">
                <div class="x_title">
                    <h2>List</h2>

                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                    </ul>

                    <div class="clearfix"></div>

                </div><!--end of x-title-->

                <?php echo $this->render('accounts/payroll/add-payroll/payroll-lists.phtml') ?>

            </div>
        </div>
    </div>
</div>

<?php echo $this->partial('accounts/payroll/add-payroll/js.phtml') ?>
