<?php
 $title = 'Generation of Consolidated Attendance for Students';
 $this->headTitle($title);

  $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    //IDEA-CBC
    //Original
    //$iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('aes-256-cbc'));

    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));

    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}
?>

 <div class="right_col" role="main">
      <div class="">
        <!-- Search for students-->
        <div class="col-md-12 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
              <h2><?php echo $this->escapeHtml($title)?></h2>
                <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                  </li>
                </ul>
             <div class="clearfix"></div>
            </div>
            <div class="x_content">
            <h5><i>*Note: The table list is limited. Use the Search Function to search by Programme and Year</i></h5>
              <br />
               <?php
                // Opening of the form tag
                $form->prepare();
                echo $this->form()->openTag($form);
				//$form->get('programmes_id')->setValueOptions($this->programmeList);
				//$form->get('year')->setValueOptions($this->yearList);
                ?>
            
              <div class="row">                  
                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label>Programme</label>
                    <?php echo $this->formRow($form->get('programmes_id')); ?>
                  </div>
                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label>Year</label>
                    <?php echo $this->formRow($form->get('year')); ?>
                  </div>
               </div>
             
             <div class="row">
                <div class="ln_solid"></div>
                <div class="form-group">
                    <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                      <?php
                       echo $this->formHidden($form->get('csrf'));
                       echo $this->formSubmit($form->get('submit')); 
                       echo $this->form()->closeTag(); 
                    ?>
                </div>
            </div>
              
          </div>
        </div>
       </div>   
    </div>
  </div>
              
