<?php
 $title = 'View Attendance of Students(Daily & Module wise)';
 $this->headTitle($title);
 
 $dates = array();
 $absent_data = array();
 $periods = array();
 $class_type = array();
 foreach($this->attendanceRecordDate as $attendance_dates){
	 $dates[] = $attendance_dates['attendance_date'];
	 $periods[] = $attendance_dates['period'];
	 $class_type[] = $attendance_dates['period'].$attendance_dates['attendance_type'];
 }
 foreach($this->absentData as $data){
	 //$absent_data[$data['student_id']][$data['period']] = $data['period'];
	 //$absent_data[$data['student_id']][$data['attendance_date']] = $data['attendance_date'];
	 $absent_data[$data['student_id']][$data['attendance_date']."_".$data['period']] = $data['attendance_date'];
 }

?>
<div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
            
                <div class="x_panel">
                    <br/>
                        <!-- Adding Medical Record-->
                        <div class="col-md-12 col-xs-12">
                          <div class="x_panel">
                            <div class="x_title">
                              <h2><?php echo $this->escapeHtml("View Attendance for Student")?></h2>
                                <ul class="nav navbar-right panel_toolbox">
                                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                  </li>
                            
                                </ul>
                             <div class="clearfix"></div>
                          
                            </div>
                               
                            <div class="x_content">
                            <h5><i>*(Add "attendance" for Students in a module.)<br /></i></h5>
                              <br />
                               <?php
                                // Opening of the form tag
                                $form->prepare();
                                echo $this->form()->openTag($form);
								$form->get('year')->setValueOptions($this->yearList);
								//$form->get('section')->setValueOptions($this->sectionList);
								$form->get('year')->setValue('1');
								$form->get('class_type')->setValue('Scheduled');
                                ?>
                            <?php if($this->message == NULL && $this->flashMessenger()->hasMessages()) {
								echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
								echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
								$messages = $this->flashMessenger()->getMessages();
								foreach($messages as $message) {
									echo '<strong>Success!</strong>'. $message;
								}
								echo '</div>';
								} else if($this->message =='Failure' && $this->flashMessenger()->hasMessages()) {
									echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
									echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
									$messages = $this->flashMessenger()->getMessages();
									foreach($messages as $message) {
										echo '<strong>Warning! </strong>'. $message;
									}
									echo '</div>';
							 } ?>
                              <div class="row">
                                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Module</label>
                                    <?php echo $this->formRow($form->get('module')); ?>
                                  </div>
                                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Section</label>
                                    <?php echo $this->formRow($form->get('section')); ?>
                                  </div>
                                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Date</label>
                                    <?php echo $this->formRow($form->get('from_date')); ?>
                                  </div>
                                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>To Date</label>
                                    <?php echo $this->formRow($form->get('to_date')); ?>
                                  </div>
                               </div>
                             
                             <div class="row">
                                <div class="ln_solid"></div>
                                <div class="form-group">
                                    <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                                      <?php
                                       echo $this->formHidden($form->get('class_type'));
									   echo $this->formHidden($form->get('year'));
									   echo $this->formHidden($form->get('csrf'));
                                       echo $this->formSubmit($form->get('submit')); 
                                       echo $this->form()->closeTag(); 
                                    ?>
                                </div>
                            </div>
                              
                          </div>
                        </div>
                       </div>     
                              
                          
                        <div class="col-md-12 col-sm-12 col-xs-12">
                          <div class="x_panel">
                            <div class="x_title">
                              <h2><?php echo $this->escapeHtml("List of Student(s)"); ?></h2>
                              <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                </li>
                              </ul>
                              <div class="clearfix"></div>
                            </div>
            
                             <?php
								if($this->attendanceForm != NULL){
								// Opening of the form tag
								 $attendanceForm->setAttribute('action', $this->url('recordstudentattendance', array('action' => 'recordStudentAttendance')));
								 $form->prepare();
								 echo $this->form()->openTag($attendanceForm);
								 $attendanceForm->get('employee_details_id')->setValue($this->employee_details_id);
								 $attendanceForm->get('programme_id')->setValue($this->programme_id);
								 $attendanceForm->get('academic_modules_id')->setValue($this->academic_modules_id);
								 $attendanceForm->get('from_date')->setValue($this->from_date);
								 $attendanceForm->get('to_date')->setValue($this->to_date);
								 $attendanceForm->get('year')->setValue($this->year);
								 echo $this->formHidden($attendanceForm->get('employee_details_id'));
								 echo $this->formHidden($attendanceForm->get('programme_id'));
								 echo $this->formHidden($attendanceForm->get('academic_modules_id'));
								 echo $this->formHidden($attendanceForm->get('from_date'));
								 echo $this->formHidden($attendanceForm->get('to_date'));
								 echo $this->formHidden($attendanceForm->get('year'));
							?>
                            <div class="x_content">
                            <h4>&nbsp;&nbsp;<i class="blue">(S): Scheduled/Regular</i>&nbsp;&nbsp;
                            	&nbsp;&nbsp;<i class="blue">(E): Extra Class</i>
                            </b></h4>
                              <div class="table-responsive">
                              <table class="table table-striped responsive-utilities jambo_table bulk_action table-bordered">
                                <thead>
                                <tr>
                                    <td class="column-title" style="width:15%" rowspan="2">Date/Day </td>
                                    <?php for($i=0; $i< count($dates); $i++) {?>
                                    <td style="width: 2%" class="column-title"><?php echo substr($dates[$i],5,5); ?></td>
                                    <?php }?>
                                </tr>
                                <tr>
									<?php for($i=0; $i< count($dates); $i++) {?>                                  
                                    <td style="width: 2%" class="column-title"><?php echo substr(date("D", strtotime($dates[$i])),0,3); ?></td>
                                    <?php }?>
                                </tr>
                                <tr>
                                    <td class="column-title" style="width:15%">Student Name </td>
									<?php for($i=0; $i< count($dates); $i++) {?>                                  
                                    <td style="width: 2%" class="column-title"><?php echo substr($periods[$i],0,11)."<br>(".substr($class_type[$i],11,1).")"; ?></td>
                                    <?php }?>
                                </tr>
                                </thead>
                                <tbody>
                                  <?php foreach ($this->studentList as $id => $name) : ?>
                                  <tr class="even pointer">
                                  	<td><?php echo $name.' ('.$id.')'; ?></td>
                                    <?php 
											for($i=0; $i< count($dates); $i++){ ?>
                                    <td>
											<?php	
												if(array_key_exists($id, $absent_data)){
													$dates_periods = $dates[$i]."_".$periods[$i];
													if(array_key_exists($dates_periods, $absent_data[$id])) {
														?><span class="label label-danger">A</span><?php 
													} else {
														?><span class="label label-success">P</span><?php
													}
												}
												else {
													?><span class="label label-success">P</span><?php
												} ?>
                                    </td>
                                    <?php } ?>
                                  </tr>
                                  <?php endforeach; ?>
                                </tbody>
                              </table>
                            </div>
                            <div class="clearfix"></div>
                            <div class="row">
                                    <div class="ln_solid"></div>
                                    <div class="form-group">
                                    <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                                      <?php
                                       echo $this->form()->closeTag(); 
                                       
									}//closing of if loop
                                    ?>
                                    </div>
                                </div>
                             </div>
                          </div>
                        </div>
                            
                           		<!-- End of Attendance-->
                        </div>
                      </div>
                  </div>
                </div>
              
