<?php
 $title = 'Edit Position Category';
 $this->headTitle($title);
?>
<div class="right_col" role="main">
      <div class="">
        <div class="col-md-12 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
              <h2><?php echo $this->escapeHtml($title); ?></h2>
             <div class="clearfix"></div>
            </div>
            <div class="x_content">
            <br />
            <div class="" role="tabpanel" data-example-id="togglable-tabs">
            <div id="myTabContent" class="tab-content">
              <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="profile-tab">
               <br/> 
               <p> 
                <div class="x_panel"> 
                <div class="x_content">
                <br />
                   
                <?php
                   // Opening of the form tag
					$form->prepare();
                    echo $this->form()->openTag($form);
				    $pay = $form->get('payscale');
					//$pay->get('position_level')->setValueOptions($this->positionLevel);
					$pay->get('id')->setValue($this->payDetails->getId());
					$pay->get('position_level')->setValue($this->payDetails->getPosition_Level());
					$pay->get('minimum_pay_scale')->setValue($this->payDetails->getMinimum_Pay_Scale());
					$pay->get('increment')->setValue($this->payDetails->getIncrement());
					$pay->get('maximum_pay_scale')->setValue($this->payDetails->getMaximum_Pay_Scale());
          $pay->get('status')->setValue($this->payDetails->getStatus());
          echo $this->formHidden($pay->get('position_level')); 
                    echo $this->formHidden($pay->get('id'));   
                ?>
                  
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Position Level: <span class="required">*</span>
                    </label>
                    <div class="col-md-5 col-sm-5 col-xs-12">
                      <input type="text" value="<?php  echo $this->payDetails->getPposition_Level(); ?>" class="form-control" readonly="readonly">
                    </div>
                </div>
                </div> 
                  
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm- col-xs-12">Minimum Pay Scale: <span class="required">*</span>
                    </label>
                    <div class="col-md-5 col-sm-5 col-xs-12">
                      <?php  echo $this->formRow($pay->get('minimum_pay_scale')); ?>
                    </div>
                </div>
                </div>   
                  
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Increment<span class="required">*</span>
                    </label>
                    <div class="col-md-5 col-sm-5 col-xs-12">
                      <?php  echo $this->formRow($pay->get('increment')); ?>
                    </div>
                </div>
                </div>
                       
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Maximum Pay Scale: <span class="required">*</span>
                    </label>
                    <div class="col-md-5 col-sm-5 col-xs-12">
                      <?php  echo $this->formRow($pay->get('maximum_pay_scale')); ?>
                    </div>
                    </div>
                    </div>
                    <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Status: <span class="required">*</span>
                    </label>
                    <div class="col-md-5 col-sm-5 col-xs-12">
                      <?php  echo $this->formRow($pay->get('status')); ?>
                    </div>
                    </div>
                    </div>
                       
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                        <?php 
						   echo $this->formHidden($form->get('csrf'));
						   echo $this->formSubmit($pay->get('submit')); 
						?>
                        </div>
                    </div>
                </div>
                    
				<?php  echo $this->form()->closeTag(); ?>
                    
                </div>
                </div> 
                    
              
                <div class="x_panel">
                <div class="x_content">
                     <div class="table-responsive">
                      <table id="example-datatable" class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Position Level </th>
                            <th class="column-title">Minimum PayScale</th>
                            <th class="column-title">Increment</th>
                            <th class="column-title">Maximum PayScale </th>
                            <th class="column-title">Action </th>
                          </tr>
                        </thead>  
                        <tbody>
                      	<?php foreach ($this->pay_scale as $pay): ?>
                          <tr>
                            <td><?php echo $this->escapeHtml($pay->getPosition_Level());?></td>
                            <td><?php echo $this->escapeHtml($pay->getMinimum_Pay_Scale());?></td>
                            <td><?php echo $this->escapeHtml($pay->getIncrement());?></td>
                            <td><?php echo $this->escapeHtml($pay->getMaximum_Pay_Scale());?></td>
                            <td><a href="<?php echo $this->url('editpayscale', array('id' => $pay->getId()));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a></td>
                          </tr>
                         <?php endforeach; ?>
						</tbody>
                      </table>
                     </div>
					</div>
				</div>
				</div>
                <!-- End of tabs-->        
                
   		 </div>
 		</div>
	</div>
</div>
</div>
            
