<?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Add Goods Received Purchased';
 $this->headTitle($title);
?>

<div class="right_col" role="main">
    <div class=" ">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
			  <div class="x_title">
				<h2><?php echo $this->escapeHtml($title); ?></h2>
				<ul class="nav navbar-right panel_toolbox">
				  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
				</ul>
			  <div class="clearfix"></div>
			  </div>
		  
			  <div class="x_content">
				  <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				    $goodspurchasedentry = $form->get('itemreceivedpurchased');
                    echo $this->form()->openTag($form);
                    echo $this->formHidden($goodspurchasedentry->get('id'));
                    $goodspurchasedentry->get('supplier_details_id')->setValueOptions($selectData4);

                 ?> 

                 <div class="form-group">           
                    <label class="control-label col-md-2 col-sm-2 col-xs-12" for="supplier_details_id">Item Received Type</label>
                    <div class="col-md-8 col-sm-8 col-xs-12">
                            <?php  echo $this->formRow($goodspurchasedentry->get('supplier_details_id')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2 col-sm-2 col-xs-12" for="reference_no">Item Received Date</label>
                    <div class="col-md-3 col-sm-3 col-xs-12">
                            <?php  echo $this->formRow($goodspurchasedentry->get('reference_no')); ?>
                    </div>           
                    <label class="control-label col-md-2 col-sm-2 col-xs-12" for="reference_date">Item Entry Date</label>
                    <div class="col-md-3 col-sm-3 col-xs-12">
                            <?php  echo $this->formRow($goodspurchasedentry->get('reference_date')); ?>
                    </div>
                </div>

                <div class="form-group">           
                    <label class="control-label col-md-2 col-sm-2 col-xs-12" for="supplier_order_no">Item Received By</label>
                    <div class="col-md-3 col-sm-3 col-xs-12">
                            <?php  echo $this->formRow($goodspurchasedentry->get('supplier_order_no')); ?>
                    </div>
                </div><br/><br/>
                
                <div class="form-group">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                       <label class="control-label col-md-2 col-sm-2 col-xs-12"></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
						   <?php  
                            //echo $this->formHidden($form->get('csrf'));
                            echo $this->formRow($goodspurchasedentry->get('submit')); ?>
                        </div>
                    </div>
                </div> 

                    <?php 
                //closing the form tag  
                 echo $this->form()->closeTag();
                 ?>

			  </div> <!-- End of x-content -->
            </div> 
        </div> 
    </div>
</div>


 <script>
     function add_goodsreceived() {
         var currentCount = $('form > fieldset > fieldset').length;
         var template = $('form > fieldset > span').data('template');
         template = template.replace(/__index__/g, currentCount);

         $('form > fieldset').append(template);

         return false;
     }

     function remove_addsreceived(){
        var currentCount = $('form > fieldset > fieldset').length;
        var template = $('form > fieldset >span').data('template');
        template = template.replace(/__index__/g, currentCount);

        $('form > fieldset').prepend(template);
     }
 </script>
