<?php
 $title = 'OVC Objectives & Weightage';
 $this->headTitle($title);
 $five_year = array();
 $temp_message = NULL;
 foreach($this->five_year_plan as $key => $value){
	$five_year['id'] = $key; 
	$five_year['five_year_plan_id'] = $value; 
 } 
 if($this->flashMessenger()->hasMessages()){
    
         $temp_message = $this->flashMessenger()->getMessages();
         $temp_message = $temp_message[0];
 }
 
 $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));
    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}

?>
<div class="right_col" role="main">
         <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title)?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                    </ul>
                 <div class="clearfix"></div>
              
                </div>
                 <?php if($this->organisation_id == 1){ ?>  
                <div class="x_content">
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				            $objectives = $form->get('ovcobjectiveweightage');
                    $objectives->get('five_year_plan_id')->setValue($five_year['five_year_plan_id']);
                    $objectives->get('organisation_id')->setValue($this->organisation_id);
                    $objectives->get('rub_objectives_id')->setValueOptions($this->rub_objectives);
                    $objectives->get('departments_id')->setValueOptions($this->departments);
                    echo $this->formHidden($objectives->get('organisation_id')); 
                    echo $this->formHidden($objectives->get('id')); 
          				  ?>

                    <?php 
                            if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                                echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                $messages = $this->flashMessenger()->getMessages();
                                foreach($messages as $message) {
                                    echo '<strong>Success!</strong>'. $message;
                                }
                                echo '</div>';
                            }

                            else if ($this->message == 'Error' && $this->flashMessenger()->hasMessages()) {
                                echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                $messages = $this->flashMessenger()->getMessages();
                                foreach($messages as $message) {
                                    echo '<strong>Failure!</strong>'. $message;
                                }
                                echo '</div>';
                            }

                            else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                                echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                $messages = $this->flashMessenger()->getMessages();
                                foreach($messages as $message) {
                                    echo '<strong>Failure!</strong>'. $message;
                                }
                                echo '</div>';
                            }
                        ?>
                
                    <p><i>***Please select department and objectives correctly. You have to select department and objective in order to add weightage since for same objective different department is having different weightage. You have to add this objective based on department and objective once at the begining of every five year and at one go weightage for every financial year for the particular five year will be added automaticually. If you want to edit the weightage then click on edit but you are allow to edit only the current financial year weightage.</i></p> 
                  <div class="row">    
                   <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"> Five Year Plan: <span class="required">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <?php  echo $this->formRow($objectives->get('five_year_plan_id')); ?>
                        </div>
                    </div>
                  </div>
                  <div class="row"> 
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Departments:<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($objectives->get('departments_id')); ?>
                    </div>
                  </div>
                  </div>
                  <div class="row"> 
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Objectives:<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($objectives->get('rub_objectives_id')); ?>
                    </div>
                  </div>
                  </div>
                  <div class="row"> 
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Weightage:</label>
                    <div class="col-md-2 col-sm-2 col-xs-12">
                          <?php  echo $this->formRow($objectives->get('weightage')); ?>
                    </div>
                  </div>
                  </div>
                  
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
						<?php
                           //need to set it as 'id' rather than Five Year Plan
						   $objectives->get('five_year_plan_id')->setValue($five_year['id']);
						   echo $this->formHidden($objectives->get('five_year_plan_id'));
						   echo $this->formHidden($form->get('csrf'));
						   echo $this->formSubmit($objectives->get('submit')); 
						   echo $this->form()->closeTag(); 
                        ?>
                    </div>
                </div>
                </div>
                </div>
                </div>
                    
                  
          <!-- Start of table listing mission and vision -->
        <div class="x_panel">
        	<div class="x_title">
                  <h2><?php echo $this->escapeHtml('OVC Objectives with Weightages'); ?><small>(Weightage of different departments heads)</small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                  </ul>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                     <div class="table-responsive">
                      <table id="datatable-buttons" class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                            <th class=" ">Sl No</th>
                            <th class="column-title">Financial Year</th>
                            <th class="column-title">Objectives</th>
                            <th class="column-title">Weightage</th>
                            <th class="column-title">Departments</th>
                            <th class="column-title">Action</th>
                            
                             </tr>
                        </thead>  
                        <tbody>
                         <?php $i =1; foreach ($this->objectives as $objectives) : ?>
                          <tr class="even pointer">
                            <td><?php echo $i++; ?></td>
                            <td class=" "><?php echo $this->escapeHtml($objectives['financial_year']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($objectives['objectives']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($objectives['weightage']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($objectives['department_name']);?></td>
                            <td class=" "><a href="<?php echo $this->url('editovcobjectiveweightage', array('id' => my_encrypt($objectives['id'], $key)));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a></td>
                          </tr>
                          <?php endforeach; ?>
                      </tbody>
                      </table>
                     </div>
                   </div>
                </div>
              <?php } else {?>
                <div class="x_content">
                  <?php 
                            
                     echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert"></button>';
                    echo '<strong>Alert! You are not eligible to add or view this page.</strong>';
                    echo '</div>';
                  ?>
                </div>
              <?php } ?>
          </div>
        </div> 
      </div>
    </div>