<?php
 $title = 'Evaluate APA';
 $this->headTitle($title);
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                   <?php
                   $form->prepare();
                   echo $this->form()->openTag($form);

                   echo $this->formHidden($form->get('id'));   
                ?>
               <div class="row">
                 <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Five Year Plan</label>
               <select class="form-control"><option>--select--</option></select>
                  </div>
                   <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Objectives</label>
                 <select class="form-control"><option>--select--</option></select>
                  </div>
                   <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Administrative Units</label>
                 <select class="form-control"><option>--select--</option></select>
                  </div>
                    <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Activities</label>
                <select class="form-control"><option>--select--</option></select>
                  </div>
                   <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Financial Year</label>
                <select class="form-control"><option>--select--</option></select>
                  </div>
                        <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Success Indicator</label>
               <select class="form-control"><option>--select--</option></select>
                  </div>
                  
                </div> 
                    
                  <div class="row">
                        <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                              <div class="col-md-6 col-sm-6 col-xs-12">
                                  <button type="button" class="btn btn-success">Save</button>
                    </div>
                    </div>
                    </div>
    
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                </div>
              </div>
        </div>
   
          </div>
        </div> 

              
              
   
            
    