<?php
 $title = 'Performance Management System - Academic Appraisal';
 $this->headTitle($title);
 $api_output = array();
 $academic_activities = array();
 $api = array();
 foreach($this->kpi as $kpi){
	 $academic_activities[$kpi['category']][$kpi['activity_name']][]= $kpi;
	 $api_output[$kpi['category']][] = $kpi['activity_name'];
	 $api[$kpi['pms_nature_activity_id']] = $kpi['nature_of_activity'];
 }

$appraisal_details = array();
 foreach($this->appraisalDetail as $detail){
	 $appraisal_details = $detail;
 }
?>

<div class="right_col" role="main">
          <div class="">
              
         <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title)?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                
                    </ul>
                 <div class="clearfix"></div>
              
                </div>
                   
                <div class="x_content">
                  <br />
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
					         $data = $this->selectData;
        				    $awpa = $form->get('academicappraisal');
        				  ?>
                
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">College Output<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                     <input type="text" class="form-control" disabled="disabled" placeholder="<?php  echo $this->objectivesSelect[$appraisal_details['awpa_objectives_activity_id']]; ?>">
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Nature of Activity<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <textarea class="form-control" rows="3" disabled="disabled" placeholder='<?php  echo $appraisal_details['pms_nature_activity_id'];  ?>'></textarea>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Maximum API</label>
                    <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                    <textarea class="form-control" rows="3" disabled="disabled" placeholder='<?php  echo $appraisal_details['maximum_api'];  ?>'></textarea>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Minimum API </label>
                    <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                    <textarea class="form-control" rows="3" disabled="disabled" placeholder='<?php  echo $appraisal_details['minimum_api'];  ?>'></textarea>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Status </label>
                    <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                    <input type="text" class="form-control" disabled="disabled" placeholder="<?php  echo $appraisal_details['status']; ?>">
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Remarks from Supervisor</label>
                    <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                    <input type="text" class="form-control" disabled="disabled" placeholder="<?php  echo $appraisal_details['remarks']; ?>">
                    </div>
                  </div>
                 
                 <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                          <?php
						   echo $this->form()->closeTag(); 
                        ?>
                    </div>
                </div>
                  
          </div>
        </div>
         </div>
        </div>
       </div> 
      </div>
