<?php
 $title = 'Administrative Appraisal for Staff';
 $this->headTitle($title);
 $staff = array();
 foreach($this->employee_details as $emp){
	 $staff = $emp;
 }
?>

<div class="right_col" role="main">
          <div class="">
         <!-- List the KPI Of the Supervisor-->
         <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml("Key Performance Indicator (KPI) of Supervisor")?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                    </ul>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <div class="table-responsive">
                  <table id= "datatable" class="table table-striped responsive-utilities jambo_table bulk_action table-bordered">
                        <thead>
                          <tr class="headings">
                             <th style="width:5%" class="column-title">Sl.No.</th>
                             <th style="width:90%" class="column-title">Activity Name</th>
                          </tr>
                        </thead>
                        <tbody>
                          <?php
                          $i=1;  foreach($this->supervisor_activities as $activity): ?>
                          <tr class="even pointer">
                            <td class=" "><?php echo $i++;?></td>
                            <td class=" "><?php echo $activity;?></td>
                          </tr>
                          <?php endforeach; ?>
                        </tbody>
                      </table>
                     
           </div>
          </div>
        </div>
      </div> 
      <!-- End of Supervisor KPI-->
     <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
            <h2><?php echo $this->escapeHtml($title); ?></h2>
             <div class="clearfix"></div>
            </div>
            <br/>
            <form>   
             <div class="row">
                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                  <label>Appraisal Period</label>
                  <input type="text" placeholder="2017-2018" class="form-control" readonly>
                  </div>
                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                  <label>Employee Name</label>
                  <input type="text" placeholder="<?php echo $staff['first_name'].' '.$staff['middle_name'].' '.$staff['last_name']; ?>" class="form-control" readonly>
                  </div>
                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                  <label>Employee ID No.</label>
                  <input type="text" placeholder="<?php echo $staff['emp_id']; ?>" class="form-control" readonly>
                  </div>
                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                  <label>Position Title</label>
                  <input type="text" placeholder="Finance Officer" class="form-control" readonly>
                  </div>
             </div>
             <div class="row">
                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                  <label>Position Level</label>
                  <input type="text" placeholder="Grade 8" class="form-control" readonly>
                  </div>
                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                  <label>OVC / College</label>
                  <input type="text" placeholder="OVC" class="form-control" readonly>
                  </div>
                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                  <label>Department/Division</label>
                  <input type="text" placeholder="IT Division" class="form-control" readonly>
                  </div>
             </div>
            </form>
            <br />
            <?php
				// Opening of the form tag
				$form->prepare();
				echo $this->form()->openTag($form);
			  ?> 
            <div class="ln_solid"></div>
            <br />
            <div class="table-responsive">
              <table class="table table-striped responsive-utilities jambo_table bulk_action table-bordered">
                    <thead>
                      <tr class="headings">
                        </th>
                         <th style="width:2%" class="column-title">Sl.No.</th>
                         <th style="width:10%" class="column-title">Sub Activity Name</th>
                         <th style="width:15%" class="column-title">Outstanding Description </th>
                         <th style="width:15%" class="column-title">Very Good Description</th>
                         <th style="width:15%" class="column-title">Good Description</th>
                         <th style="width:15%" class="column-title">Needs Improvement Description</th>
                         <th style="width:15%" class="column-title">Remarks</th>
                         <th style="width:8%" class="column-title">Status</th>
                      </tr>
                    </thead>

                    <tbody>
                      <?php
					  $i=1;  foreach($this->administrativeAppraisal as $appraisal): ?>
                      <tr class="even pointer">
                        <td class=" "><?php echo $i;?></td>
                        <td class=" "><?php echo $appraisal['subactivity_name'];?></td>
                        <td class=" "><?php echo $appraisal['outstanding_description'];?></td>
                        <td class=" "><?php echo $appraisal['very_good_description'];?></td>
                        <td class=" "><?php echo $appraisal['good_description'];?></td>
                        <td class=" "><?php echo $appraisal['needs_improvement_description'];?></td>
                        <td class=" ">
							<?php
								if($appraisal['status'] == "Approved" || $appraisal['status'] == "Evaluation Complete"){
									echo $appraisal['remarks'];
									$form->get('remarks'.$appraisal['id'])->setValue($appraisal['remarks']);
									echo $this->formHidden($form->get('remarks'.$appraisal['id']));
								}
								else 
									echo $this->formRow($form->get('remarks'.$appraisal['id'])); 
							?>
                        </td>
                        <td class=" ">
							<?php 
								if($appraisal['status'] == "Approved" || $appraisal['status'] == "Evaluation Complete"){
									echo $appraisal['status'];
									$form->get('status'.$appraisal['id'])->setValue($appraisal['status']);
									echo $this->formHidden($form->get('status'.$appraisal['id']));
								}
								else
									echo $this->formRow($form->get('status'.$appraisal['id'])); ?>
                        </td>
                      </tr>
                      <?php endforeach; ?>
                    </tbody>
                  </table>
           </div>
           <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
						<?php
						   echo $this->formHidden($form->get('csrf'));
						   echo $this->formSubmit($form->get('submit')); 
						   echo $this->form()->closeTag();
                        ?>
                    	</div>
                    </div>
               </div>
        </div>
      </div>
    </div>
  </div>
 </div>