<?php
 $title = 'Administrative Appraisal for Staff';
 $this->headTitle($title);
 $staff = array();
 foreach($this->employee_details as $emp){
	 $staff = $emp;
 }

?>

 <div class="right_col" role="main">
  <div class="">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
            <h2><?php echo $this->escapeHtml($title); ?></h2>
             <div class="clearfix"></div>
            </div>
            <br/>
            <form>   
             <div class="row">
                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                  <label>Appraisal Period</label>
                  <input type="text" placeholder="2017-2018" class="form-control" readonly>
                  </div>
                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                  <label>Employee Name</label>
                  <input type="text" placeholder="<?php echo $staff['first_name'].' '.$staff['middle_name'].' '.$staff['last_name']; ?>" class="form-control" readonly>
                  </div>
                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                  <label>Employee ID No.</label>
                  <input type="text" placeholder="<?php echo $staff['emp_id']; ?>" class="form-control" readonly>
                  </div>
                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                  <label>Position Title</label>
                  <input type="text" placeholder="Finance Officer" class="form-control" readonly>
                  </div>
             </div>
             <div class="row">
                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                  <label>Position Level</label>
                  <input type="text" placeholder="Grade 8" class="form-control" readonly>
                  </div>
                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                  <label>OVC / College</label>
                  <input type="text" placeholder="OVC" class="form-control" readonly>
                  </div>
                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                  <label>Department/Division</label>
                  <input type="text" placeholder="IT Division" class="form-control" readonly>
                  </div>
             </div>
            </form>
            <br />
            <?php
				// Opening of the form tag
				$form->prepare();
				echo $this->form()->openTag($form);
			  ?> 
            <div class="ln_solid"></div>
            <br />
            <h4><?php echo $this->escapeHtml('List of Peer Nominations'); ?></h4>
            <br />
            <div class="table-responsive">
              <table class="table table-striped responsive-utilities jambo_table bulk_action table-bordered">
                    <thead>
                      <tr class="headings">
                        </th>
                         <th style="width:2%" class="column-title">Sl.No.</th>
                         <th style="width:10%" class="column-title">Nomination</th>
                         <th style="width:15%" class="column-title">Staff ID</th>
                         <th style="width:15%" class="column-title">Designation</th>
                         <th style="width:8%" class="column-title">Action</th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php
					  $i=1;  foreach($this->peerList as $peer): ?>
                      <tr class="even pointer">
                        <td class=" "><?php echo $i;?></td>
                        <td class=" "><?php echo $this->escapeHtml($peer['first_name'].' '.$peer['middle_name'].' '.$peer['last_name']);?></td>
                        <td class=" "><?php echo $this->escapeHtml($peer['emp_id']);?></td>
                        <td class=" "><?php echo $this->escapeHtml('');?></td>
                        <td class=" ">
                        	<?php if($peer['status'] == 'Pending'){ 
                            echo $this->formRow($form->get('peer'.$i++)); 
                             } ?></td>
                      </tr>
                      <?php endforeach; ?>
                    </tbody>
                  </table>
           </div>
           <h4><?php echo $this->escapeHtml('List of Subordinate Nominations'); ?></h4>
            <br />
            <div class="table-responsive">
              <table class="table table-striped responsive-utilities jambo_table bulk_action table-bordered">
                    <thead>
                      <tr class="headings">
                        </th>
                         <th style="width:2%" class="column-title">Sl.No.</th>
                         <th style="width:10%" class="column-title">Nomination</th>
                         <th style="width:15%" class="column-title">Staff ID</th>
                         <th style="width:15%" class="column-title">Designation</th>
                         <th style="width:8%" class="column-title">Action</th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php
					  $i=1;  foreach($this->subordinateList as $subordinate): ?>
                      <tr class="even pointer">
                        <td class=" "><?php echo $i;?></td>
                        <td class=" "><?php echo $this->escapeHtml($subordinate['first_name'].' '.$subordinate['middle_name'].' '.$subordinate['last_name']);?></td>
                        <td class=" "><?php echo $this->escapeHtml($subordinate['emp_id']);?></td>
                        <td class=" "><?php echo $this->escapeHtml('');?></td>
                        <td class=" ">
                        	<?php if($peer['status'] == 'Pending'){ 
                            echo $this->formRow($form->get('subordinate'.$i++)); 
                             } ?></td>
                      </tr>
                      <?php endforeach; ?>
                    </tbody>
                  </table>
           </div>
           <h4><?php echo $this->escapeHtml('List of Beneficiary Nominations'); ?></h4>
            <br />
            <div class="table-responsive">
              <table class="table table-striped responsive-utilities jambo_table bulk_action table-bordered">
                    <thead>
                      <tr class="headings">
                        </th>
                         <th style="width:2%" class="column-title">Sl.No.</th>
                         <th style="width:10%" class="column-title">Nomination</th>
                         <th style="width:15%" class="column-title">Staff ID</th>
                         <th style="width:15%" class="column-title">Designation</th>
                         <th style="width:8%" class="column-title">Action</th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php
					  $i=1;  foreach($this->beneficiaryList as $beneficiary): ?>
                      <tr class="even pointer">
                        <td class=" "><?php echo $i;?></td>
                        <td class=" "><?php echo $this->escapeHtml($beneficiary['first_name'].' '.$beneficiary['middle_name'].' '.$beneficiary['last_name']);?></td>
                        <td class=" "><?php echo $this->escapeHtml($beneficiary['emp_id']);?></td>
                        <td class=" "><?php echo $this->escapeHtml('');?></td>
                        <td class=" ">
                        	<?php if($peer['status'] == 'Pending'){ 
                            echo $this->formRow($form->get('beneficiary'.$i++)); 
                             } ?></td>
                      </tr>
                      <?php endforeach; ?>
                    </tbody>
                  </table>
           </div>
           <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                        <?php
						   echo $this->formHidden($form->get('csrf'));
						   echo $this->formSubmit($form->get('submit')); 
						   echo $this->form()->closeTag();
                        ?>
                    	</div>
                    </div>
               </div>
        </div>
      </div>
    </div>
  </div>
 </div>
