<?php
 $title = 'Edit Teaching Allowance';
 $this->headTitle($title);
?>
<div class="right_col" role="main">
      <div class="">
        <div class="col-md-12 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
              <h2><?php echo $this->escapeHtml($title); ?></h2>
             <div class="clearfix"></div>
            </div>
            <div class="x_content">
            <br />
            <div class="" role="tabpanel" data-example-id="togglable-tabs">
            <div id="myTabContent" class="tab-content">
              <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="profile-tab">
               <br/> 
               <p> 
                <div class="x_panel"> 
                <div class="x_content">
                <br />
                   
                <?php
                   // Opening of the form tag
					         $form->prepare();
                    echo $this->form()->openTag($form);
				            $teaching = $form->get('teachingallowance');
          					//$teaching->get('position_level')->setValueOptions($this->positionLevel);
          					$teaching->get('id')->setValue($this->allowanceDetails->getId());
          					$teaching->get('position_level')->setValue($this->allowanceDetails->getPosition_Level());
          					$teaching->get('years_in_service')->setValue($this->allowanceDetails->getYears_In_Service());
          					$teaching->get('teaching_allowance')->setValue($this->allowanceDetails->getTeaching_Allowance());
                    echo $this->formHidden($teaching->get('position_level'));   
                    echo $this->formHidden($teaching->get('id'));   
                ?>
                  
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Position Level: <span class="required">*</span>
                    </label>
                    <div class="col-md-5 col-sm-5 col-xs-12">
                      <input type="text" value="<?php  echo $this->allowanceDetails->getPposition_Level(); ?>" class="form-control" readonly="readonly">
                    </div>
                </div>
                </div> 
                  
                 <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm- col-xs-12">No. of year in Service: <span class="required">*</span>
                    </label>
                    <div class="col-md-5 col-sm-5 col-xs-12">
                      <?php  echo $this->formRow($teaching->get('years_in_service')); ?>
                    </div>
                </div>
                </div>   
                  
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Allowance:<span class="required">*</span>
                    </label>
                    <div class="col-md-5 col-sm-5 col-xs-12">
                      <?php  echo $this->formRow($teaching->get('teaching_allowance')); ?>
                    </div>
                </div>
                </div>
                       
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                        <?php 
						   echo $this->formHidden($form->get('csrf'));
						   echo $this->formSubmit($teaching->get('submit')); 
						?>
                        </div>
                    </div>
                </div>
                    
				<?php  echo $this->form()->closeTag(); ?>
                    
                </div>
                </div> 
                    
              
                <div class="x_panel">
                <div class="x_content">
                     <div class="table-responsive">
                      <table id="example-datatable" class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Position Level </th>
                            <th class="column-title">No.of year in service</th>
                            <th class="column-title">Allowance</th>
                            <th class="column-title">Action</th>
                          </tr>
                        </thead>  
                        <tbody>
                      	<?php foreach ($this->teaching_allowance as $teaching): ?>
                          <tr>
                            <td><?php echo $this->escapeHtml($teaching->getPosition_Level());?></td>
                            <td><?php echo $this->escapeHtml($teaching->getYears_In_Service());?></td>
                            <td><?php echo $this->escapeHtml($teaching->getTeaching_Allowance());?></td>
                            <td><a href="<?php echo $this->url('editteachingallowance', array('id' => $teaching->getId()));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a>
                                </td>
                          </tr>
                         <?php endforeach; ?>
						</tbody>
                      </table>
                     </div>
					</div>
				</div>
				</div>
                <!-- End of tabs-->        
                
   		 </div>
 		</div>
	</div>
</div>
</div>
            
