<?php 
    $this->headLink()->appendStylesheet($this->basePath('bower_components/bootstrap/dist/css/bootstrap.min.css'));
    $this->headLink()->appendStylesheet($this->basePath('bower_components/font-awesome/css/font-awesome.min.css'));
    $this->headLink()->appendStylesheet($this->basePath('bower_components/Ionicons/css/ionicons.min.css'));
    $this->headLink()->appendStylesheet($this->basePath('dist/css/AdminLTE.min.css'));
    $this->headLink()->appendStylesheet($this->basePath('dist/css/skins/_all-skins.min.css'));
    
    // Add a JavaScript file
    $this->headScript()->appendFile('js/rub-ajax/ajax.js', 'text/javascript');

    $key1 = $this->keyphrase; 
    function my_encrypt($data, $key1) { 
        // Remove the base64 encoding from our key
        $encryption_key = base64_decode($key1);
        // Generate an initialization vector
        $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));
        // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
        $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
        // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
        return bin2hex(base64_encode($encrypted . '::' . $iv));
    }
        
?>

<!-- page content -->
        <div class="right_col" role="main">
          <!-- Main content -->
            <section class="content">
               <!-- Small boxes (Stat box) -->
               <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                  <div class="col-lg-3 col-xs-6">
                    <!-- small box -->
                    <div class="small-box bg-aqua">
                      <div class="inner">
                        <h4>Result</h4>
                      </div>
                      <div class="icon">
                        <i class="fa fa-pencil-square-o"></i>
                      </div>
                      <a href="viewstudentconsolidatedmarks" class="small-box-footer">Semester Result <i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                  </div>
                  <!-- ./col -->
                  <div class="col-lg-3 col-xs-6">
                    <!-- small box -->
                    <div class="small-box bg-green">
                      <div class="inner">
                        <h4>Leave Management</h4>
                      </div>
                      <div class="icon">
                        <i class="fa fa-bars"></i>
                      </div>
                      <a href="applystdleave" class="small-box-footer">Apply Leave <i class="fa fa-arrow-circle-right"></i></a>
                      <a href="applystdouting" class="small-box-footer">Apply Outing <i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                  </div>
                  <!-- ./col -->
                  <div class="col-lg-3 col-xs-6">
                    <!-- small box -->
                    <div class="small-box bg-yellow">
                      <div class="inner">
                        <h4>Counseling Services</h4>
                      </div>
                      <div class="icon">
                        <i class="fa fa-flag-o"></i>
                      </div>
                      <a class="small-box-footer"></a>
                      <a href="counselingappointment" class="small-box-footer">Seek Appointment <i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                  </div>
                  <!-- ./col -->
                  <div class="col-lg-3 col-xs-6">
                    <!-- small box -->
                    <div class="small-box bg-red">
                      <div class="inner">
                        <h4>Student Services</h4>
                      </div>
                      <div class="icon">
                        <i class="fa fa-bell-o"></i>
                      </div>
                      <a href="hostelchangeapplication" class="small-box-footer">Apply Hostel Change<i class="fa fa-arrow-circle-right"></i></a>
                      <a href="poststdsuggestions" class="small-box-footer">Post Suggestion <i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                  </div>
                  <!-- ./col -->
                </div>
                <!-- /.row -->
              </div>
              <!-- First row Start -->
              <div class="row">
                <!-- First Left Column Start -->
                <div class="col-md-6 col-sm-6 col-xs-6 ">
                  <div class="col-md-12 col-sm-12 col-xs-12 profile_details">
                    <div class="well profile_view">
                      <?php
                      $details = array();
                      foreach ($this->studentDetails as $sdetail): { 
                        $details['name'] = $sdetail['first_name'].' '.$sdetail['middle_name'].' '.$sdetail['last_name'];
                        $details['student_id'] = $sdetail['student_id'];
                        $details['programme_name'] = $sdetail['programme_name'];
                        $details['semester'] = $sdetail['semester'];
                        $details['programme_year_id'] = $sdetail['programme_year_id'];
                        $details['enrollment_year'] = $sdetail['enrollment_year'];
                        $img_location = $sdetail['profile_picture'];
                      }
                      ?>
                      <div class="col-sm-12">
                        <h4 class="brief"><i><?php echo $details['programme_name']; ?></i></h4>
                        <div class="left col-xs-7">
                          <h2><?php echo $details['name']; ?></h2>
                          <p><strong>Programme: </strong> <?php echo $details['programme_name']; ?> </p>
                          <ul class="list-unstyled">
                            <li><strong>Year of Enrolment:</strong> <?php echo $details['enrollment_year']; ?> </li>
                            <li><strong>Current Year:</strong> <?php echo $details['programme_year_id'].' Year'; ?> </li>
                            <li></i><strong>Current Semester:</strong> <?php echo $details['semester'].' Semester'; ?></li>
                            <li></i><strong>Hostel Detail:</strong> 
                              <a href="<?php echo $this->url('studentselfhostel', array('action' => 'studentSelfHostel')); ?>" class="btn btn-primary btn-xs"><i class="fa fa-user"> </i> View Hostel Detail</a>
                            </li>
			  </ul>
                        </div>
                        <div class="right col-xs-5 text-center">
                         <?php if(!empty($img_location)){?>
                            <img src="<?php echo '../'.$img_location; ?>" alt="..." class="img-circle profile_img">
                          <?php } else{?>
                            <p><i>Notice: No profile image uploaded!</i></p>
                          <?php }?>
                        </div>
                      </div>
                      <div class="col-xs-12 bottom text-center">
                        <div class="col-xs-12 col-sm-6 emphasis">
                          For Detail Click View Profile Button
                        </div>
                        <div class="col-xs-12 col-sm-6 emphasis">
                            <a href="<?php echo $this->url('studentprofile', array('action' => 'studentProfile')); ?>" class="btn btn-primary btn-xs"><i class="fa fa-user"> </i> View Profile</a>
                        </div>
                      </div>
                    <?php endforeach; ?>
                    </div>
                  </div>
                  <div class="col-md-12 col-sm-12 col-xs-12 profile_details">
                    <div class="x_panel">
                      <div class="x_title">
                        <h2>News and Information</h2>
                        <ul class="nav navbar-right panel_toolbox">
                          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                          <li><a class="close-link"><i class="fa fa-close"></i></a></li>
                        </ul>
                        <div class="clearfix"></div>
                      </div>
                      <div class="x_content">
                        <!-- Type you text Here -->
                               <div class="table-responsive">
                              <table class="table table-striped jambo_table table-bordered">
                                <thead>
                                  <tr class="headings">
                                    <th class="column-title">News Paper</th>
                                  </tr>
                                </thead>
                                <tbody>
                                  <tr class="even pointer">
                                    <td><a href="<?php echo $this->url('newspaperinformation', array('action' => 'newspaperInformation')); ?>" class="btn btn-primary btn-xs"><i class="fa fa-user"> </i>Newspaper</a></td>
                                  </tr>
                                </tbody>
                              </table>
                            </div>
                      </div>
                    </div>
                  </div>
                </div><!-- First Left Column End -->
                <!-- First Right Column Start -->
                <div class="col-md-6 col-sm-6 col-xs-6">
                  <div class="col-md-12 col-sm-12 col-xs-12 profile_details">
                    <div class="x_panel">
                      <div class="x_title">
                        <h2>Your Attendance</h2>
                        <ul class="nav navbar-right panel_toolbox">
                          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                          <li><a class="close-link"><i class="fa fa-close"></i></a></li>
                        </ul>
                        <div class="clearfix"></div>
                      </div>
                      <div class="x_content">
                        
                        <div class="table-responsive">
                          <table class="table table-striped responsive-utilities jambo_table bulk_action table-bordered">
                        <thead class="headings">
                            <tr>
                              <th>Sl/No</th>
                              <th>Module Code</th>
                              <th>Module Name</th>
                              <th>Class Delivered</th>
                              <th>Class Attended</th>
                              <th>Action</td>
                            </tr>
                          </thead>
                          <tbody>
                            <?php $i= 1; foreach($this->absenteeModuleList as $key => $module): ?>
                              <tr>
                                <td><?php echo $i++; ?></td>
                                <td><?php echo $module['module_code']; ?></td>
                                <td><?php echo $module['module_title']; ?></td>
                                <td><?php echo $module['total_lectures_delivered']; ?></td>
                                <td><?php echo $module['total_lectures_delivered']-$module['total_lectures_missed']; ?></td>
                                <td>
                                <a href="<?php echo $this->url('individualstdmoduleabsentdetails', array('id' => my_encrypt($key,$key1)));?>" class="btn btn-primary btn-xs"><i class="fa fa-eye"></i> Details</a>
                                </td>
                              </tr>
                          <?php endforeach; ?>
                          </tbody>
                        </table>
                      </div>
                      </div>
                    </div>
                  </div>
                </div><!-- First Right Column End -->

                <!-- Second Column Start -->
                <div class="col-md-12 col-sm-12 col-xs-12 profile_details">
                  <div class="x_panel">
                    <div class="x_title">
                      <h2>Current Semester Assessment Weightage Detail</h2>
                      <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                        <li><a class="close-link"><i class="fa fa-close"></i></a></li>
                      </ul>
                      <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                      <?php 
                      $assessment_component_weightage = array();
                      $assessment_types = array();
                      $academic_module_id = array();
                      $module_name = array();
                      $module_code = array();

                      foreach($this->stdCurrentSemesterDet as $key=>$value){
                        foreach($value as $key2=>$value2){
                          $assessment_types[$key] = $key;
                          $academic_module_id[$key2] = $key2;
                          $assessment_component_weightage[$key2][$key] = $value2;
                        }
                      }

                      foreach ($this->moduleList as $key=>$value) {
                        foreach($value as $key2=>$value2){
                         // var_dump($value2); die();
                         $module_name[$key] = $value2;
                         $module_code[$key] = $key2;
                        }
		      } 
                      ?>
                      <div class="table-responsive">
                          <table class="table table-striped responsive-utilities jambo_table bulk_action table-bordered">
                        <thead class="headings">
                          <tr>
                            <th class="column-title">Sl/No</th>
                            <th class="column-title">Module Code</th>
                            <th class="column-title">Module Name</th>
                            <?php foreach($assessment_types as $type): ?>
                            <th style="width: 8%" class="column-title"><?php echo $type; ?></th>
                            <?php endforeach; ?>
                          </tr>                          
                        </thead>
                        <tbody>
                            <?php $i=1; foreach($assessment_component_weightage as $key=>$value):?>
                            <tr>
                            <td><?php echo $i++; ?></td>
                            <td><?php echo  $module_code[$key]; ?></td>
                            <td><?php echo $module_name[$key]; ?></td>
                            <?php foreach($assessment_types as $type): ?>
                            <td class=" "><?php echo $value[$type]; ?></td>
                            <?php endforeach; ?>
                            
                          </tr>
                          <?php endforeach; ?>
                        
                        </tbody>
                      </table>
                    </div>
                    </div>
                </div><!-- Second Column End -->
              </div>

                <!-- Second Column Start -->
                <div class="col-md-12 col-sm-12 col-xs-12 profile_details">
                  <div class="x_panel">
                    <div class="x_title">
                      <h2>Current Semester Continuous Assessment Results</h2>
                      <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                        <li><a class="close-link"><i class="fa fa-close"></i></a></li>
                      </ul>
                      <div class="clearfix"></div>
                    </div>
                    <?php 
                    $assessment_component_weightage = array();
                      $assessment_types = array();
                      $academic_module_id = array();
                      $module_name = array();
                      $module_code = array();

                      foreach($this->studentCADetails as $key=>$value){
                        foreach($value as $key2=>$value2){ 
                          $assessment_types[$key] = $key;
                          $academic_module_id[$key2] = $key2;
                          $assessment_component_weightage[$key2][$key] = $value2;
                        }
                      }
                      
                    foreach ($this->moduleList as $key=>$value) {
                        foreach($value as $key2=>$value2){
                         // var_dump($value2); die();
                         $module_name[$key] = $value2;
                         $module_code[$key] = $key2;
                        }
		    } 
                    ?>
                    <div class="x_content">
                      <div class="table-responsive">
                          <table class="table table-striped responsive-utilities jambo_table bulk_action table-bordered">
                        <thead>
                          <tr>
                            <th>Sl/No</th>
                            <th>Module Code</th>
                            <th>Module Name</th>
                            <?php foreach($assessment_types as $type): ?>
                            <th style="width: 8%" class="column-title"><?php echo $type.' (Weightage)'; ?></th>
                            <?php endforeach; ?>
                            <th>Action</th>
                          </tr>
                        </thead>
                        <tbody>
                            <?php $i=1; foreach($assessment_component_weightage as $key=>$value): ?>
                            <tr>
                            <td><?php echo $i++; ?></td>
                             <td><?php echo $module_code[$key]; ?></td>
                            <td><?php echo $module_name[$key]; ?></td>
                            <?php foreach($assessment_types as $type): ?>
                            <td class=" "><?php echo $value[$type]; ?></td>
                            <?php endforeach; ?>
                            <td>
                           	<a href="<?php echo $this->url('individualstdmodulecadetails', array('id' => my_encrypt($key,$key1)));?>" class="btn btn-primary btn-xs"><i class="fa fa-eye"></i> Details</a>
                            </td>
                          </tr>
                          <?php endforeach; ?>
                        </tbody>
                      </table>
                    </div>
                    </div>
                  </div>
                </div>

                
                <div class="col-md-12 col-sm-12 col-xs-12 profile_details">
                  <div class="x_panel">
                    <div class="x_title">
                      <h2>Academic Timetable (MT - Module Tutor and MC - Module Coordinator)</h2>
                      <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                        <li><a class="close-link"><i class="fa fa-close"></i></a></li>
                      </ul>
                      <div class="clearfix"></div>
                    </div>
                    <!-- Second Column Start -->
                <?php 
                 $days_week = array(
                    'Monday' => 'Monday',
                    'Tuesday' => 'Tuesday',
                    'Wednesday' => 'Wednesday',
                    'Thursday' => 'Thursday',
                    'Friday' => 'Friday'
                   );
                   
                   $timetable_data = array();
                   foreach($this->stdAcademicTimetable as $table){
                     $timetable_data[$table['day']][$table['from_time'].'-'.$table['to_time']][] = $table['module_code']
                                                      .'<br>(MT-'.$table['first_name'].' '.$table['middle_name'].' '.$table['last_name'].')'.'<br>(MC-'.$table['mcfirst_name'].' '.$table['mcmiddle_name'].' '.$table['mclast_name'].')'.'<br>(Room-'.$table['classroom'].')';

		   }
                ?>
                    <div class="x_content">
                              <table class="table   table-striped responsive-utilities jambo_table bulk_action table-bordered">
                                <thead>
                                    <th style="width: 15%" class="column-title"></th>
                                    <?php foreach($this->timetableTimings as $key=>$value): ?>
                                    <th class="column-title"><?php echo substr($value,0,5).'-'.substr($value,9,5); ?></th>
                                    <?php endforeach; ?>
                                </thead>
                                <tbody>
                                  <?php 
                                  foreach($days_week as $day):
                                  foreach($timetable_data as $key=>$value):
                                  if($day == $key) { ?>
                                    <tr class="even pointer">
                                      <td><?php echo $key; ?></td>
                                    <?php for($i=0; $i<count($this->timetableTimings); $i++){ ?>
                                      <td align="center"><?php if(array_key_exists($this->timetableTimings[$i], $value))
                                    echo $value[$this->timetableTimings[$i]][0]; 
                                    else
					    echo " "; 
                                  ?></td>
                                    <?php } ?>
                                    </tr>
                                  <?php 
                                  } //end if loop
                                endforeach;
		      endforeach; ?>
                                </tbody>
                              </table>
                            </div>
                  </div>
                </div>

              </div>
            </section>
          </div>
