<?php

 $title = 'Assign Invigilator';
 $this->headTitle($title);
 ?>
<div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                  </div>
                    
                  <div class="x_content">
                    <br/>
                   
                        
                        
                        <?php
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        
                        echo $this->formHidden($form->get('id'));
                        ?>
                        <div class="row">
                            
                          <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Hall Name<span class="required">*</span>
                        </label>
                              <div class="col-md-9 col-sm-9 col-xs-12">
                        <?php
                        echo $this->formRow($form->get('exam_hall_name'));
                        ?>
                          </div>
                        </div>  
                        </div>  
                    <div class="row">
                            
                          <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Hall No<span class="required">*</span>
                        </label>
                              <div class="col-md-9 col-sm-9 col-xs-12">
                        <?php
                        echo $this->formRow($form->get('exam_hall_no'));
                        ?>
                          </div>
                        </div>  
                        </div>    
                    <div class="row">
                            
                          <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Employee Name<span class="required">*</span>
                        </label>
                              <div class="col-md-9 col-sm-9 col-xs-12">
                        <?php
                        echo $this->formRow($form->get('employee_name'));
                        ?>
                          </div>
                        </div>  
                        </div>  
                    <div class="row">
                            
                          <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Employee Date<span class="required">*</span>
                        </label>
                              <div class="col-md-9 col-sm-9 col-xs-12">
                        <?php
                        echo $this->formRow($form->get('exam_date'));
                        ?>
                          </div>
                        </div>  
                        </div>    
                    <div class="row">
                            
                          <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Employee Time<span class="required">*</span>
                        </label>
                              <div class="col-md-9 col-sm-9 col-xs-12">
                        <?php
                        echo $this->formRow($form->get('exam_time'));
                        ?>
                          </div>
                        </div>  
                        </div>    
                    <div class="row">
                        <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                              <div class="col-md-9 col-sm-9 col-xs-12">
                    <?php
                        echo $this->formSubmit($form->get('submit')); 
                        echo $this->formSubmit($form->get('reset')); 
                      ?>
                    </div>
                    </div>
                    </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                       
                    
                  </div></div></div>
              <?php
 $title = 'Exam Invigilators';
 $this->headTitle($title);
 ?>
              <div class="col-md-12 col-xs-12">
                  
                  <div class="x_panel">
                      <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                  </div>
                
                    <div class="x_content">
                        <div class="table-responsive">
                      <table class="table table-striped jambo_table bulk_action"> 
                         <div class="form-group">      
                      </div> 
                        <thead>
                          <tr class="headings">
                           <!--<th>
                              <input type="checkbox" id="check-all" class="flat">
                            </th>-->
                              <th class="column-title">Sl. No</th>
                            <th class="column-title">Employee Name </th>
                            <th class="column-title">Hall Name </th>
                            <th class="column-title">Hall No </th>
                            <th class="column-title">Exam Date </th>
                            <th class="column-title">Exam Time </th>
                            
                            <th class="column-title no-link last"><span class="nobr">Manage</span>
                            </th>
                            <th class="bulk-actions" colspan="7">
                              <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                            </th>
                          </tr>
                        </thead>
                        
                        <tbody>
                     
                          <tr>
                            <!--<td>
                              <input type="checkbox" class="flat" name="table_records">
                            </td>-->
                              <td></td>
                              <td></td>
                              <td></td>
                              <td></td>
                              <td></td>
                              <td></td>
                            <td class="fa fa-pencil"></td><td class="fa fa-close"></td>
                            
                            
                          </tr>
                         
                        </tbody>
                          </table>
                      
                    </div>
                    </div>
                
                </div></div></div></div>
            
         
              
       
                