<?php

 $title = 'Allocate Modules to An Academic Year';
 $this->headTitle($title);

  $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    //IDEA-CBC
    //Original
    //$iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('aes-256-cbc'));

    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));

    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}
?>
<div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title)?></h2>
                   <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                    </ul> 
                 <div class="clearfix"></div>
                </div>
                <?php 
					if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
						echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
						echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
						$messages = $this->flashMessenger()->getMessages();
						foreach($messages as $message) {
							echo '<strong>Success!</strong>'. $message;
						}
						echo '</div>';
					}
	
					else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
						echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
						echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
						$messages = $this->flashMessenger()->getMessages();
						foreach($messages as $message) {
							echo '<strong>Failure!</strong>'. $message;
						}
						echo '</div>';
                    }
                        ?>                  
                   <div class="x_content">
                	<br/>
                 	<?php
						// Opening of the form tag
						$form->prepare();
						echo $this->form()->openTag($form);
					?>
                    <h4><i>*In this process of "Module Allocation" for an academic year, all the modules that have been defined in the programme/module description
                    		will be allocated to the academic year. If the allocation has already been done, no allocation will take place.<br /><br />
                           **Also note, if there are changes in the module allocation as compared to the previous academic year, then you could:<br />
                           	1. Allocate the modules individually. In that case, all modules will then have to be allocated individually. <br />
                            2. Allocate all and then "edit" the modules to make the necessary changes.
                           </i></h4>
                    
                     <div class="row">
                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                <?php
                                   echo $this->formHidden($form->get('csrf'));
                                   echo $this->formSubmit($form->get('allocate')); 
                                ?>
                                </div>
                            </div>
                       </div>
                            <?php
                            echo $this->form()->closeTag();
                            ?>
                        </div>
                      </div>
                </div>
               <?php
				 $title = 'Academic Modules for Academic Year';
				 $this->headTitle($title);
			  ?>
              <div class="col-md-12 col-xs-12">
                  
                  <div class="x_panel">
                    <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                  </div>
                
                    <div class="x_content">
                        <div class="table-responsive">
                      <table id="datatable-buttons" class="table table-striped jambo_table table-bordered">
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Sl. No</th>
                            <th class="column-title">Programme Name</th>
                            <th class="column-title">Module Title</th>
                            <th class="column-title">Module Code</th>
                            <th class="column-title">Credits</th>
                            <th class="column-title">Module Type</th>
                            <th class="column-title">Year</th>
                            <th class="column-title">Semester</th>
                            <th class="column-title">Session</th>
                            <th class="column-title">Academic Year</th>
                            <th class="column-title no-link last"><span class="nobr">Action</span>
                            </th>
                          </tr>
                        </thead>
                        <tbody>
                            <?php $i=1; foreach ($this->moduleAllocated as $module) : ?>
                          <tr class="even pointer">
                            <td class=" "><?php echo $i++;?></td>
                            <td class=" "><?php echo $this->escapeHtml($module['programme_name']); ?></td>
                            <td class=" "><?php echo $this->escapeHtml($module['module_title']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($module['module_code']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($module['module_credit']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($module['module_type']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($module['year']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($module['semester']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($module['academic_session']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($module['academic_year']);?></td>
			    <td><a href="<?php echo $this->url('editacademicyearmodule', array('id' => my_encrypt($module['id'], $key)));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit (<?php echo($module['id']); ?>)</a></td>
                          </tr>
                          <?php endforeach; ?>
                        </tbody>
                      </table>
                    </div>
                    </div>
                
                </div>
              </div>
            </div>
           </div>  
          </div>
        </div> 
     </div>
