<?php
 $title = 'Update Programme';
 $this->headTitle($title);

  //need to convert programme duration to months/years
 if(floor($this->programmeDetails->getProgramme_Duration()) == $this->programmeDetails->getProgramme_Duration()) {
   $programme_duration = $this->programmeDetails->getProgramme_Duration();
   $duration_units = 'years';
 } else {
   $programme_duration = $this->programmeDetails->getProgramme_Duration() * 12;
   $duration_units = 'months';
 }
?>
<div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title)?></h2>
                   <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                    </ul> 
                 <div class="clearfix"></div>
                </div>
                  <div class="x_content">
                	<br/>
                 	<?php
						// Opening of the form tag
						$form->prepare();
						echo $this->form()->openTag($form);
						$programme = $form->get('programme');
						//need to set all preset values
						$programme->get('id')->setValue($this->programmeDetails->getId());
						$programme->get('organisation_id')->setValue($this->programmeDetails->getOrganisation_Id());
						$programme->get('programme_name')->setValue($this->programmeDetails->getProgramme_Name());
						$programme->get('programme_leader')->setValueOptions($this->tutorList);
						$programme->get('academic_session_id')->setValueOptions($this->academicSession);
						$programme->get('programme_leader')->setValue($this->programmeDetails->getProgramme_Leader());
						$programme->get('programme_duration')->setValue($this->programmeDetails->getProgramme_Duration());
            $programme->get('duration_units')->setValue($this->programmeDetails->getDuration_Units());
						$programme->get('mode_of_study')->setValue($this->programmeDetails->getMode_Of_Study());
            			$programme->get('programme_description')->setValue($this->programmeDetails->getProgramme_Description());
						$programme->get('programme_approval_date')->setValue(date("m-d-y",strtotime($this->programmeDetails->getProgramme_Approval_date())));
						$programme->get('programme_apmr_date')->setValue(date("m-d-y",strtotime($this->programmeDetails->getProgramme_Apmr_Date())));
						$programme->get('programme_ccr_date')->setValue(date("m-d-y",strtotime($this->programmeDetails->getProgramme_Ccr_Date())));
						$programme->get('academic_session_id')->setValue($this->programmeDetails->getAcademic_Session_Id());
						$programme->get('programme_code')->setValue($this->programmeDetails->getProgramme_Code());
						$programme->get('status')->setValue($this->programmeDetails->getStatus());
						echo $this->formHidden($programme->get('id'));
						echo $this->formHidden($programme->get('organisation_id'));
					?>
                      <div class="row">
                        <div class="form-group">  
                           <label class="control-label col-md-2 col-sm-2 col-xs-12">Programme Name <span class="required">*</span></label>
                           <div class="col-md-3 col-sm-3 col-xs-12">
                              <?php echo $this->formRow($programme->get('programme_name')); ?>
                            </div>
                           <label class="control-label col-md-2 col-sm-2 col-xs-12">Programme Leader<span class="required">*</span></label>
                           <div class="col-md-3 col-sm-3 col-xs-12">
                              <?php echo $this->formRow($programme->get('programme_leader'));?>
                            </div>
                        </div>
                     </div>
                     <div class="row">
                        <div class="form-group">  
                           <label class="control-label col-md-2 col-sm-2 col-xs-12">Programme Duration <span class="required">*</span></label>
                           <div class="col-md-2 col-sm-3 col-xs-12">
                              <?php echo $this->formRow($programme->get('programme_duration')); ?>
                            </div>
                           <div class="col-md-2 col-sm-3 col-xs-12">
                              <?php echo $this->formRow($programme->get('duration_units')); ?>
                            </div>
                           <label class="control-label col-md-2 col-sm-2 col-xs-12">Mode of Study<span class="required">*</span></label>
                           <div class="col-md-2 col-sm-3 col-xs-12">
                              <?php echo $this->formRow($programme->get('mode_of_study'));?>
                            </div>
                        </div>
                     </div>
                     <div class="row">
                        <div class="form-group">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12">Programme Approval Date<span class="required">*</span></label>
                            <div class="col-md-3 col-sm-3 col-xs-12">
                              <?php echo $this->formRow($programme->get('programme_approval_date')); ?>
                            </div>
                            <label class="control-label col-md-2 col-sm-2 col-xs-12">Programme APMR Date<span class="required">*</span></label>
                            <div class="col-md-3 col-sm-3 col-xs-12">
                              <?php echo $this->formRow($programme->get('programme_apmr_date')); ?>
                            </div>
                        </div>
                     </div>
                     <div class="row">
                        <div class="form-group">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12">Programme Complete Cycle Review Date<span class="required">*</span></label>
                            <div class="col-md-3 col-sm-3 col-xs-12">
                              <?php echo $this->formRow($programme->get('programme_ccr_date')); ?>
                            </div>
                            <label class="control-label col-md-2 col-sm-2 col-xs-12">Upload Approved DPD<span class="required">*</span></label>
                            <div class="col-md-3 col-sm-3 col-xs-12">
                              <?php echo $this->formRow($programme->get('programme_approved_dpd')); ?>
                            </div>
                        </div>
                     </div>
                     <div class="row">
                        <div class="form-group">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12">Start of Academic Session <span class="required">*</span></label>
                            <div class="col-md-3 col-sm-3 col-xs-12">
                              <?php echo $this->formRow($programme->get('academic_session_id')); ?>
                            </div>
                            <label class="control-label col-md-2 col-sm-2 col-xs-12">Prg. Code/Short Name <span class="required">*</span></label>
                           <div class="col-md-3 col-sm-3 col-xs-12">
                              <?php echo $this->formRow($programme->get('programme_code')); ?>
                            </div>
                        </div>
                     </div>
                     <div class="row">
                        <div class="form-group">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12">Status of Programme<span class="required">*</span></label>
                            <div class="col-md-3 col-sm-3 col-xs-12">
                              <?php echo $this->formRow($programme->get('status')); ?>
                            </div>
                        </div>
                     </div>
                     <div class="row">
                        <div class="form-group"> 
                            <label class="control-label col-md-2 col-sm-2 col-xs-12">Programme Description (Brief)<span class="required">*</span> </label>
                            <div class="col-md-8 col-sm-8 col-xs-12">
                              <?php echo $this->formRow($programme->get('programme_description')); ?>
                           </div>
                        </div>
                     </div>

                     <div class="row">
                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                <?php
                                   echo $this->formHidden($form->get('csrf'));
                                   echo $this->formSubmit($programme->get('update')); 
                                ?>
                                </div>
                            </div>
                       </div>
                            <?php
                            echo $this->form()->closeTag();
                            ?>
                        </div>
                      </div>
                </div>
               <?php
				 $title = 'Programme List';
				 $this->headTitle($title);
			  ?>
              <div class="col-md-12 col-xs-12">
                  
                  <div class="x_panel">
                      <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                  </div>
                
                    <div class="x_content">
                        <div class="table-responsive">
                      <table class="table table-striped jambo_table bulk_action" width="100%"> 
                         <div class="form-group">      
                      </div> 
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Sl. No</th>
                            <th class="column-title">Programme Name</th>
                            <th class="column-title">Programme Leader</th>
                            <th class="column-title no-link last"><span class="nobr">Action</span>
                            </th>
                            <th class="bulk-actions" colspan="7">
                              <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                            </th>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <?php $i=1; foreach ($this->programmes as $programme) : ?>
                          <tr class="even pointer">
                            <td class=" "><?php echo $i++;?></td>
                            <td class=" "><?php echo $this->escapeHtml($programme['programme_name']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($programme['programme_leader']);?></td>
                            <td><a href="<?php echo $this->url('viewprogramme', array('id' => $programme['id']));?>" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i>View</a>
                            	<a href="<?php echo $this->url('updateprogramme', array('id' => $programme['id']));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Update</a></td>
                          </tr>
                          <?php endforeach; ?>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                    </div>
                
                </div>
              </div>
             </div>
           </div>
          </div>
        </div> 
     </div>
     
     