<?php
 $title = 'Research Grant Announcement (DRER / DRIL)';
 $this->headTitle($title);
 $announcementDetails = array();
 foreach($this->grantDetail as $detail){
	 $announcementDetails = $detail;
 }
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
        				    $research = $form->get('researchannouncement');
        					$research->get('id')->setValue($announcementDetails['id']);
        					//$research->get('research_grant_type')->setValueOptions($this->researchTypes);
        					$research->get('research_grant_type')->setValue($announcementDetails['research_grant_type']);
                  $start_date = explode("-", $announcementDetails['start_date']);
        					$research->get('start_date')->setValue($start_date[01].'/'.$start_date[02].'/'.$start_date[00]);
                  $end_date = explode("-", $announcementDetails['end_date']);
        					$research->get('end_date')->setValue($end_date[01].'/'.$end_date[02].'/'.$end_date[00]);
                  echo $this->formHidden($research->get('research_grant_type')); 
                    echo $this->formHidden($research->get('id')); 
				          ?>  
                <div class="row">    
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Research Grant Type</label>
                    <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <input type="text" class="form-control" value="<?php  echo $announcementDetails['grant_type']; ?>" readonly="readonly">
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Start Submission Date </label>
                    <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($research->get('start_date')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">End Submission Date </label>
                    <div class="col-md-3 col-sm-12 col-xs-12">
                      <?php  echo $this->formRow($research->get('end_date')); ?>
                    </div>
                  </div>
                </div> 
                  
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
						<?php
                           
						   echo $this->formHidden($form->get('csrf'));
						   echo $this->formSubmit($research->get('submit')); 
                        ?>
                    	</div>
                    </div>
               </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                </div>
              </div>
        <!-- Start of table listing publication type -->
        <div class="x_panel">
                <div class="x_content">
                     <div class="table-responsive">
                      <table class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Sl. No</th>
                            <th class="column-title">Research Grant Type</th>
                            <th class="column-title">Start Date</th>
                            <th class="column-title">End Date</th>
                            
                             </tr>
                        </thead>  
                        <tbody>
                      <tr>
                         <?php $i = 1; foreach ($this->grantAnnouncement as $announcement) : ?>
                          <tr class="even pointer">
                            <td class=" "><?php echo $i++;?></td>
                            <td class=" "><?php echo $this->escapeHtml($announcement['grant_type']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($announcement['start_date']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($announcement['end_date']);?></td>
                          </tr>
                          <?php endforeach; ?>
                      </tr>
                      </tbody>
                      </table>
                     </div>
                  </div>
               </div>
             </div>
          </div>
        </div> 
     </div>
    </div>
