<?php
 $title = 'Duly Filled Promotion Application Form for Approval';
 $this->headTitle($title);
 $personal = array();
 foreach($this->personalDetails as $detail){
	 $personal = $detail;
 }

 $last_promotion = array();
 foreach($this->lastPromotion as $last){
  $last_promotion = $last;
 }

 ?>
  <div class="right_col" role="main">
          <div class="">
              <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
				            <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
          					$form->get('id')->setValue($this->id);
          					echo $this->formHidden($form->get('id')); 
                 ?> 
                  <div class="clearfix"></div>
                  <!-- Personal Details Information-->
                  <h2 class="StepTitle">Personal Details</h2>
                  <div class="row">
                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Name:</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <h4 class="blue"><i><?php echo $personal['first_name'].' '.$personal['middle_name'].' '.$personal['last_name']; ?></i></h4>
                        </div>
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Gender:</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <h4 class="blue"><i><?php echo $personal['emp_id']; ?></i></h4>
                        </div>
                    </div>
                  </div>
                  <br />
                  <!-- End of Personal Details Information-->
                  <!-- Present Job Details Information-->
                  <h2 class="StepTitle">Present Job Identification</h2>
                  <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Position Title:</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <h4 class="blue"><i><?php echo $this->employmentDetails['position_title']; ?></i></h4>
                        </div>
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Position Level:</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <h4 class="blue"><i><?php echo $this->employmentDetails['position_level']; ?></i></h4>
                        </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Pay Scale:</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <h4 class="blue"><i><?php echo $this->employmentDetails['minimum_pay_scale'].'-'.$employmentDetails['maximum_pay_scale']; ?></i></h4>
                        </div>
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Position Category:</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <h4 class="blue"><i><?php echo $this->employmentDetails['category']; ?></i></h4>
                        </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Major Occupational Group:</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <h4 class="blue"><i><?php echo $this->employmentDetails['major_occupational_group']; ?></i></h4>
                        </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Date of Last Promotion:</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <?php if(!empty($this->lastPromotionDate)){
                          foreach($this->lastPromotionDate as $details):
                            ?>
                          <h4 class="blue"><i><?php echo $details['promotion_order_date']; ?></i></h4>
                        <?php 
                      endforeach;
                            } else {?>
                                <h4 class="blue"><i><?php echo "Not yet applied for promotion before."; ?></i></h4>
                            <?php } ?>
                        </div>
                    </div>
                  </div>
                  <br />
                  <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-6 col-sm-2 col-xs-12">No. of continuous & active years of service completed from the date of initial appointment:</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <h4 class="blue"><i><?php echo $last['years_service_from_appointment']; ?></i></h4>
                        </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-6 col-sm-2 col-xs-12">No. of continuous & active years of service completed since the last promotion:</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <h4 class="blue"><i><?php echo $last['years_service_from_promotion']; ?></i></h4>
                        </div>
                    </div>
                  </div>
                  <br />
                  <!-- End of Leave Details Information-->
                  <div class="ln_solid"></div>
                  <br />
                  <div class="clearfix"></div>
                  <div class="row">
                    <div class="form-group">  
                       <div class="col-md-12 col-sm-12 col-xs-12">
                          <h2><i>Promotion Recommendation</i></h2>
                       </div>
                    </div>
                  </div>
                  <br />
                  <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Promotion Order No.<span class="required">*</span></label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <?php echo $this->formRow($form->get('promotion_order_no')); ?>
                        </div>
                       <label class="control-label col-md-2 col-sm-2 col-xs-12">Position Order Type.<span class="required">*</span></label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <?php echo $this->formRow($form->get('promotion_order_type')); ?>
                        </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-3 col-xs-12">Promotion Order Date</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <?php echo $this->formRow($form->get('promotion_order_date')); ?>
                        </div>
                       <label class="control-label col-md-2 col-sm-3 col-xs-12">Promotion Effective Date</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <?php echo $this->formRow($form->get('promotion_effective_date')); ?>
                        </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Occupational Group<span class="required">*</span></label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <?php echo $this->formRow($form->get('occupational_group')); ?>
                        </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Position Category<span class="required">*</span></label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <?php echo $this->formRow($form->get('recommended_position_category')); ?>
                        </div>
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Position Title<span class="required">*</span></label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <?php echo $this->formRow($form->get('recommended_position_title')); ?>
                        </div>                      
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group">  
                       <label class="control-label col-md-2 col-sm-3 col-xs-12">Position Level</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <?php echo $this->formRow($form->get('recommended_position_level')); ?>
                        </div>
                        <label class="control-label col-md-2 col-sm-3 col-xs-12">Pay Scale</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <?php echo $this->formRow($form->get('recommended_pay_scale')); ?>
                        </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group">  
                       <label class="control-label col-md-2 col-sm-3 col-xs-12"></label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          
                        </div>
                        <label class="control-label col-md-2 col-sm-3 col-xs-12">Teaching Allowance</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <?php echo $this->formRow($form->get('teaching_allowance')); ?>
                        </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Is the proposed promotion against the approved post?<span class="required">*</span></label>
                       <div class="col-md-8 col-sm-2 col-xs-12">
                          <?php echo $this->formRow($form->get('proposed_position_remarks')); ?>
                        </div>
                    </div>
                  </div> 
                  <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">State whether the candidate fully matches the job requirements of the post:<span class="required">*</span></label>
                       <div class="col-md-8 col-sm-2 col-xs-12">
                          <?php echo $this->formRow($form->get('job_requirements_remarks')); ?>
                        </div>
                    </div>
                  </div> 
                   <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Upload Promotion Order<span class="required">*</span></label>
                       <div class="col-md-8 col-sm-2 col-xs-12">
                          <?php echo $this->formRow($form->get('promotion_order_file')); ?>
                        </div>
                    </div>
                  </div>                     
          		  <div class="ln_solid"></div>
                      <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                          <?php  
                            echo $this->formHidden($form->get('csrf')); 
              							echo $this->formRow($form->get('submit'));
              							echo $this->form()->closeTag($form);
              						 ?>
                        </div>
                      </div>

       			 </div> <!-- End of x_content-->
        	  </div> <!-- End of x_panel-->
   			</div> 
        </div>
  	 </div>
   </div>
 </div>
 