<?php

 $title = 'Record Resigned Staff';
 $this->headTitle($title);

 $employeeDetails = array();
 foreach($this->employeeDetails as $details){
  $employeeDetails['name'] = $details['first_name'].' '.$details['middle_name'].' '.$details['last_name'];
   $employeeDetails['emp_id'] = $details['emp_id'];
    $employeeDetails['department_name'] = $details['department_name'];
     $employeeDetails['position_title'] = $details['position_title'];
 }
 
 $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));
    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}
 ?>

<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				             $resignation = $form->get('employeeresignation');
                    echo $this->form()->openTag($form);
					         $resignation->get('employee_details_id')->setValue($this->employee_details_id);
                   $resignation->get('resignation_type')->setValueOptions($this->resignationType);
                   $resignation->get('resignation_status')->setValue('Approved');
                    echo $this->formHidden($resignation->get('id')); 
        					echo $this->formHidden($resignation->get('employee_details_id'));
                  echo $this->formHidden($resignation->get('resignation_status'));
        				  ?>  

                  <?php 
                      if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                          echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                          echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                          $messages = $this->flashMessenger()->getMessages();
                          foreach($messages as $message) {
                              echo '<strong>Success!</strong>'. $message;
                          }
                          echo '</div>';
                      }

                      else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                          echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                          echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                          $messages = $this->flashMessenger()->getMessages();
                          foreach($messages as $message) {
                              echo '<strong>Failure!</strong>'. $message;
                          }
                          echo '</div>';
                      }
                      ?>

                      <h2 class="">Resigned Staff Details</h2>
                      <div class="row">
                        <div class="form-group">
                           <label class="control-label col-md-3 col-sm-3 col-xs-12">Staff Name:<span class="required">*</span></label>
                            <div class="col-md-2 col-sm-6 col-xs-12">
                          <input type="text" class="form-control" placeholder="<?php echo  $employeeDetails['name']; ?>" disabled="disabled">
                          </div>
                            <label class="control-label col-md-2 col-sm-3 col-xs-12">Staff ID:<span class="required">*</span></label>
                            <div class="col-md-2 col-sm-6 col-xs-12">
                              <input type="text" class="form-control" placeholder="<?php echo $employeeDetails['emp_id']; ?>" disabled="disabled">
                            </div>
                        </div>
                      </div>
                      <div class="row">
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Position Title:<span class="required">*</span></label>
                            <div class="col-md-2 col-sm-6 col-xs-12">
                              <input type="text" class="form-control" placeholder="<?php echo $employeeDetails['position_title']; ?>" disabled="disabled">
                            </div>
                            <label class="control-label col-md-2 col-sm-2 col-xs-12">Department:<span class="required">*</span></label>
                            <div class="col-md-2 col-sm-6 col-xs-12">
                              <input type="text" class="form-control" placeholder="<?php echo $employeeDetails['department_name']; ?>" disabled="disabled">
                            </div>
                        </div>
                      </div>

                      <h2 class="">Resignation Details</h2>
                      <div class="row">    
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Resignation Type:<span class="required">*</span></label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                              <?php  echo $this->formRow($resignation->get('resignation_type')); ?>
                            </div>
                        </div>
                      </div>
                      <div class="row">    
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Date of Application:<span class="required">*</span></label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                              <?php  echo $this->formRow($resignation->get('date_of_application')); ?>
                            </div>
                        </div>
                      </div>
                      <div class="row">    
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Reason:<span class="required">*</span></label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                              <?php  echo $this->formRow($resignation->get('reason_for_resignation')); ?>
                            </div>
                        </div>
                      </div> 
                  
                      <div class="row">
                          <div class="ln_solid"></div>
                          <div class="form-group">
                              <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                              <div class="col-md-6 col-sm-6 col-xs-12">
                						<?php
                						   echo $this->formHidden($form->get('csrf'));
                						   echo $this->formSubmit($resignation->get('submit')); 
                            ?>
                          	</div>
                          </div>
                     </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                </div>
              </div>
        	</div>
          </div>
        </div> 

            
         
              
       
                