<?php
 $title = 'Staff Attendance';
 $this->headTitle($title);
 
 $staffs = array();
 $i = 1;
 foreach($this->staffList as $detail){
	 $staffs[$detail['id']] = $detail['first_name'].' '.$detail['middle_name'].' '.$detail['last_name'];
 }
 if($this->staffAttendance != NULL){
	 $staffAttendance = array();
	 foreach($this->staffAttendance as $key=>$value){
		 foreach($value as $key1=>$value1){
			 $staffAttendance[$key][$key1] = $value1;
		 }
 	}
 }
 $absent_data = array();
 $absentee_data = array();
 if($attendanceRecordDate != NULL){
	 $index = 1;
	 foreach($this->attendanceRecordDate as $key=>$value){
		 foreach($value as $key1=>$value1){
			 if(array_key_exists('from_date', $absent_data)){
				 if(strtotime($absent_data['from_date']) > strtotime($value1)){
					  $absent_data['from_date'] = $value1;
				 }
			 } else {
				 $absent_data[$key1] = $value1;
			 }
			 if(array_key_exists('to_date', $absent_data)){
				 if(strtotime($absent_data['to_date']) < strtotime($value1)){
					  $absent_data['to_date'] = $value1;
				 }
			 } else {
				 $absent_data[$key1] = $value1;
			 }
		 }
	 }
	 $index = 1;
	 foreach($this->absentData as $key => $value){
		 foreach($value as $key1=>$value1){
			 $absentee_data[$key][$key1] = $value1;
		 }
	 }
 }
 
?>

 <div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
            
                <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                     <div class="clearfix"></div>
                    </div>
                    <br/>
                        <!-- Adding Attendance-->
                        <div class="col-md-12 col-xs-12">
                          <div class="x_panel">
                            <div class="x_title">
                              <h2><?php echo $this->escapeHtml("View Attendance by Unit/Section")?></h2>
                                <ul class="nav navbar-right panel_toolbox">
                                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                  </li>
                                </ul>
                             <div class="clearfix"></div>
                          
                            </div>
                               
                            <div class="x_content">
                            <h5><i>*(View "attendance" for a unit/section.)<br /></i></h5>
                              <br />
                               <?php
                                // Opening of the form tag
                                $form->prepare();
                                echo $this->form()->openTag($form);
								$form->get('unit_name')->setValueOptions($this->unitsList);
                              ?>
                            
                              <div class="row">
                                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Units/Section</label>
                                    <?php echo $this->formRow($form->get('unit_name')); ?>
                                  </div>
                                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>From Date - To Date</label>
                                    <?php echo $this->formRow($form->get('from_date')); ?>
                                  </div>
                             </div>
                             <div class="row">
                                <div class="ln_solid"></div>
                                <div class="form-group">
                                    <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                                      <?php
                                       echo $this->formHidden($form->get('csrf'));
                                       echo $this->formSubmit($form->get('submit')); 
                                       echo $this->form()->closeTag(); 
                                    ?>
                                </div>
                            </div>
                          </div>
                        </div>
                       </div>     
                              
                          
                        <div class="col-md-12 col-sm-12 col-xs-12">
                          <div class="x_panel">
                            <div class="x_title">
                              <h2><?php echo $this->escapeHtml("Staff Attendance Details"); ?></h2>
                              <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                </li>
                              </ul>
                              <div class="clearfix"></div>
                            </div>
            
                            <div class="x_content">
                              <div class="table-responsive">
                              <table id="datatable-buttons" class="table table-striped jambo_table table-bordered">
                                <thead>
                                  <tr class="headings">
                                    <th class="column-title" width="5%">Sl. No</th>
                                    <th class="column-title" width="15%">Staff Name</th>
                                    <th class="column-title" width="10%">From Date</th>
                                    <th class="column-title" width="10%">To Date</th>
                                    <th class="column-title" width="10%">Total No. Of Days</th>
                                    <th class="column-title no-link last" width="20%"><span class="nobr">Reason</span></th>
                                  </tr>
                                </thead>
                                <tbody>
                                  <?php $i=1; 
								  	foreach ($this->staffAttendance as $attendance) : 
								  ?>
                                  <tr class="even pointer">
                                    <td class=" "><?php echo $i++;?></td>
                                    <td class=" "><?php echo $this->escapeHtml($staffs[(int)$attendance['employee_details_id']]);?></td>
                                    <td class=" "><?php $from_date = strtotime($attendance['from_date']); echo $this->escapeHtml($attendance['from_date']);?></td>
                                    <td class=" "><?php $to_date = strtotime($attendance['to_date']); echo $this->escapeHtml($attendance['to_date']);?></td>
                                    <td class=" "><?php echo $this->escapeHtml(round(($to_date-$from_date)/(60*60*24)+1));?></td>
                                    <td class=" "><?php 
										if(array_key_exists('emp_leave_category_id', $attendance)){
											echo $this->escapeHtml($this->leaveCategory[$attendance['emp_leave_category_id']]);
										} else {
											echo $this->escapeHtml('Tour');
										}
										?></td>
                                  </tr>
                                  <?php 
								  	endforeach;
								  ?>
                                </tbody>
                              </table>
                            </div>
                            </div>
                            <div class="clearfix"></div>
                                    <!-- End of Attendance-->
                            </div>
                          </div>
                          
                        </div>
                        
                      </div>
                  </div>
                </div>
              
