<?php
 $title = 'Edit Professional Allowance';
 $this->headTitle($title);
?>
<div class="right_col" role="main">
      <div class="">
        <div class="col-md-12 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
              <h2><?php echo $this->escapeHtml($title); ?></h2>
             <div class="clearfix"></div>
            </div>
            <div class="x_content">
            <br />
            <div class="" role="tabpanel" data-example-id="togglable-tabs">
            <div id="myTabContent" class="tab-content">
              <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="profile-tab">
               <br/> 
               <p> 
                <div class="x_panel"> 
                <div class="x_content">
                <br />
                   
                <?php
                   // Opening of the form tag
					           $form->prepare();
                    echo $this->form()->openTag($form);
				            $university = $form->get('universityallowance');
          					$university->get('id')->setValue($this->allowanceDetails->getId());
                    //$university->get('position_level')->setValueOptions($this->positionLevel);
          					$university->get('position_level')->setValue($this->allowanceDetails->getPosition_Level());
          					$university->get('professional_allowance')->setValue($this->allowanceDetails->getProfessional_Allowance());
                    echo $this->formHidden($university->get('position_level'));  
                    $university->get('submit')->setValue('Update');
                    echo $this->formHidden($university->get('id'));   
                ?>
                  
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Position Level: <span class="required">*</span>
                    </label>
                    <div class="col-md-5 col-sm-5 col-xs-12">
                      <input type="text" value="<?php  echo $this->allowanceDetails->getPposition_Level(); ?>" class="form-control" readonly="readonly">
                    </div>
                </div>
                </div> 
                  
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm- col-xs-12">Professional Allowance: <span class="required">*</span>
                    </label>
                    <div class="col-md-5 col-sm-5 col-xs-12">
                      <?php  echo $this->formRow($university->get('professional_allowance')); ?>
                    </div>
                </div>
                </div> 
                       
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                        <?php 
						   echo $this->formHidden($form->get('csrf'));
						   echo $this->formSubmit($university->get('submit')); 
						?>
                        </div>
                    </div>
                </div>
                    
				<?php  echo $this->form()->closeTag(); ?>
                    
                </div>
                </div> 
                    
              
                <div class="x_panel">
                <div class="x_content">
                     <div class="table-responsive">
                      <table id="example-datatable" class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Position Level </th>
                            <th class="column-title">Professional Allowance</th>
                          </tr>
                        </thead>  
                        <tbody>
                      	<?php foreach ($this->university_allowance as $university): ?>
                          <tr>
                            <td><?php echo $this->escapeHtml($university->getPosition_Level());?></td>
                            <td><?php echo $this->escapeHtml($university->getProfessional_Allowance());?></td>
                          </tr>
                         <?php endforeach; ?>
						</tbody>
                      </table>
                     </div>
					</div>
				</div>
				</div>
                <!-- End of tabs-->        
                
   		 </div>
 		</div>
	</div>
</div>
</div>
            
