<?php
 $title = 'Job Vacancy Details';
 $this->headTitle($title);
 
 $hrmProposal = array();
 foreach($this->proposalDetail as $detail){
	 $hrmProposal = $detail;
 } 
 ?>
<div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                  </div>
                    
                  <div class="x_content">
                    <br/>
					<?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				    $vacancy = $form->get('vacancy');
                    echo $this->formHidden($vacancy->get('id')); 
					//$vacancy->get('five_year_plan')->setValue('12th Five Year Plan');
					$vacancy->get('position_title')->setValueOptions($this->positionTitle);
					$vacancy->get('position_title')->setValue($hrmProposal['position_title_id']);
					$vacancy->get('position_category')->setValueOptions($this->positionCategory);
					$vacancy->get('position_category')->setValue($hrmProposal['position_category_id']);
					$vacancy->get('position_level')->setValueOptions($this->positionLevel);
					$vacancy->get('position_level')->setValue($hrmProposal['position_level_id']);
					$vacancy->get('employee_type')->setValueOptions($this->empType);
					$vacancy->get('position_category')->setValueOptions($this->positionCategory);
					$vacancy->get('working_agency')->setValueOptions($this->workingAgency);
					$vacancy->get('working_agency')->setValue($hrmProposal['working_agency']);
					$vacancy->get('no_of_slots')->setValue($hrmProposal['required_no']);
					$vacancy->get('general_responsibilities')->setValue('Not Required to Enter. Will be retrieved from database');
					$vacancy->get('specific_responsibilities')->setValue('Please enter specific responsibilities');
					$vacancy->get('education_qualification_experience')->setValue('Not Required to Enter. Will be retrieved from database');
					$vacancy->get('knowledge_skills')->setValue('Not Required to Enter. Will be retrieved from database');
				  ?>  

           <?php if($this->message == NULL && $this->flashMessenger()->hasMessages()) {
              echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
              echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
              $messages = $this->flashMessenger()->getMessages();
              foreach($messages as $message) {
                echo '<strong>Success!</strong>'. $message;
              }
              echo '</div>';
                      } else if($this->message =='Failure' && $this->flashMessenger()->hasMessages()) {
                            echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                            echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                            $messages = $this->flashMessenger()->getMessages();
                            foreach($messages as $message) {
                                echo '<strong>Warning!</strong>'. $message;
                            }
                            echo '</div>';
                     }  ?>
                    <div class="row">
                        <div class="form-group">
                        	<label class="control-label col-md-2 col-sm-2 col-xs-12">Position Title  </label>
                            <div class="col-md-3 col-sm-3 col-xs-12">      
							<?php echo $this->formRow($vacancy->get('position_title')); ?>
                            </div>
                        	<label class="control-label col-md-2 col-sm-2 col-xs-12">Position Category  </label>
                            <div class="col-md-3 col-sm-3 col-xs-12">      
							<?php echo $this->formRow($vacancy->get('position_category')); ?>
                            </div>   
                         </div>
                     </div>
                     <div class="row">
                        <div class="form-group">
                           <label class="control-label col-md-2 col-sm-2 col-xs-12">Employee Type </label>
                           <div class="col-md-3 col-sm-3 col-xs-12">
                           <?php echo $this->formRow($vacancy->get('employee_type')); ?>
                           </div>
                         </div>
                    </div>
                    <div class="row">
                        <div class="form-group">
                        	<label class="control-label col-md-2 col-sm-2 col-xs-12">Position Level </label>
                            <div class="col-md-3 col-sm-3 col-xs-12">  
                            <?php echo $this->formRow($vacancy->get('position_level')); ?>
                       		</div>
                        	<label class="control-label col-md-2 col-sm-2 col-xs-12">Number of Slot  </label>
                            <div class="col-md-3 col-sm-3 col-xs-12">
                             <?php echo $this->formRow($vacancy->get('no_of_slots')); ?>
                    		</div>
                    	</div>
                    </div>
                    <div class="row">
                       <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Working Agency  </label>
                        <div class="col-md-8 col-sm-8 col-xs-12">
                        <?php echo $this->formRow($vacancy->get('working_agency')); ?>
                    	</div>
                      </div>
                    </div>
                    <div class="row">
                       <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Requirements : General Responsibility </label>
                        <div class="col-md-8 col-sm-8 col-xs-12">
                        <i><?php echo $this->formRow($vacancy->get('general_responsibilities')); ?></i>
                    	</div>
                      </div>
                    </div>
                    <div class="row">
                       <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Specific Roles and Responsibility:</label>
                        <div class="col-md-8 col-sm-8 col-xs-12">
                        <?php echo $this->formRow($vacancy->get('specific_responsibilities')); ?>
                    	</div>
                      </div>
                    </div>
                    <div class="row">
                       <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Education,Qualification & Experience</label>
                        <div class="col-md-8 col-sm-8 col-xs-12">
                        <i><?php echo $this->formRow($vacancy->get('education_qualification_experience')); ?></i>
                    	</div>
                      </div>
                    </div>
                    <div class="row">
                       <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Knowledge,Skills & Ability</label>
                        <div class="col-md-8 col-sm-8 col-xs-12">
                        <i><?php echo $this->formRow($vacancy->get('knowledge_skills')); ?></i>
                    	</div>
                      </div>
                    </div>
                    <div class="row">
                       <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Date of Advertisement</label>
                        <div class="col-md-3 col-sm-3 col-xs-12">  
                        <?php echo $this->formRow($vacancy->get('date_of_advertisement')); ?>
                    	</div>
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Last Date of Submission</label>
                        <div class="col-md-3 col-sm-3 col-xs-12">  
                        <?php echo $this->formRow($vacancy->get('last_date_submission')); ?>
                    	</div>
                      </div>
                    </div>
                    <div class="row">
                    <div class="ln_solid"></div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
						<?php
						   echo $this->formHidden($form->get('csrf'));
						   echo $this->formSubmit($vacancy->get('submit'));
						   echo $this->form()->closeTag();
                    	?>
                    	</div>
                     </div>
                   </div> 
					   
                       
                    
                  </div>
              </div>
          </div>
       </div> 
     </div>
  