<?php
 $title = 'Edit Sub Menu';
 $this->headTitle($title);
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <h5><i>Note: You can edit this particular sub menu if you have made any mistake.</i></h5>
                  <br />
                  <?php if($this->message == NULL && $this->flashMessenger()->hasMessages()){?>
                <div class="alert alert-success alert-dismissible fade in" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                    <strong>Success!</strong> <?=$this->flashMessenger()->setAutoEscape(false)->render(); ?>
                </div>
                <?php } else if($this->message =='Failure' && $this->flashMessenger()->hasMessages()) {?>
                <div class="alert alert-danger alert-dismissible fade in" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                    <strong>Failure!</strong> <?=$this->flashMessenger()->setAutoEscape(false)->render(); ?>
                </div>
                <?php } ?>
                <div class="x_content">
                  <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    $form->get('id')->setValue($this->editSubMenu->getId());
                    $form->get('user_menu_level')->setValue($this->editSubMenu->getUser_Menu_Level());
                    $form->get('user_menu_id')->setValue($this->editSubMenu->getParent_Menu());
                    $form->get('menu_name')->setValue($this->editSubMenu->getMenu_Name());
                    $form->get('menu_description')->setValue($this->editSubMenu->getMenu_Description());
                    $form->get('menu_weight')->setValue($this->editSubMenu->getMenu_Weight());
                    $form->get('submit')->setValue('Update Menu');
                    echo $this->formHidden($form->get('id'));
                    ?>  
                <div class="row">  
                   <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Menu Level<span class="required">*</span></label>
                    <div class="col-md-5 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($form->get('user_menu_level')); ?>
                    </div>
                  </div>  
                   <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Module Name<span class="required">*</span></label>
                    <div class="col-md-5 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($form->get('user_menu_id')); ?>
                    </div>
                  </div>
                   <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Sub-Module/ Sub-Menu<span class="required">*</span></label>
                    <div class="col-md-5 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($form->get('menu_name')); ?>
                    </div>
                   </div>
                   <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Menu Weight<span class="required">*</span></label>
                    <div class="col-md-5 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($form->get('menu_weight')); ?>
                    </div>
                  </div>
                   <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Sub-Module Description<span class="required">*</span></label>
                    <div class="col-md-5 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($form->get('menu_description')); ?>
                    </div>
                  </div>
                </div> 
                  
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-5 col-sm-6 col-xs-12">
            <?php
               echo $this->formHidden($form->get('csrf'));
               echo $this->formSubmit($form->get('submit')); 
                        ?>
                      </div>
                    </div>
               </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                </div>
              </div>
        
        <!-- Start of table listing budget ledgers -->
        <div class="x_panel">
          <div class="x_title">
                  <h2><?php echo $this->escapeHtml('List of added sub-menu'); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <h5><i>Note: If you have made any mistake then please click on edit button to edit it.</i></h5>
                  <br />
                <div class="x_content">
                     <div class="table-responsive">
                      <table id="datatable-buttons" class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Sl. No</th>
                            <th class="column-title">Sub Module Name</th>
                            <th class="column-title">Sub Module Description</th>
                            <th class="column-title">Parent Module Name</th>
                            <th class="column-title">Menu Level</th>
                            <th class="column-title">Menu Weight</th>
                           </tr>
                        </thead>
                        <tbody>
                         <?php $i = 1; foreach ($this->menus as $detail) : ?>
                          <tr class="even pointer">
                            <td class=" " width="8%"><?php echo $i++;?></td>
                            <td class=" "><?php echo $this->escapeHtml($detail['menu_name']);?></td>
                             <td class=" "><?php echo $this->escapeHtml($detail['menu_description']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($detail['parent_menu']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($detail['user_menu_level']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($detail['menu_weight']);?></td>
                          </tr>
                          <?php endforeach; ?>
                      </tbody>  
                        <tbody>
                      
                      </tbody>
                      </table>
                     </div>
                  </div>
               </div>
             </div>    
          </div>
        </div> 
     </div>
    </div>

