<?php
 $title = 'Adhoc Issue Goods to Staff';
 $this->headTitle($title);
?>

 <div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
            
                <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                     <div class="clearfix"></div>
                    </div>
                    <br/>
                        <!-- Adding Achievements-->
                        <div class="col-md-12 col-xs-12">
                          <div class="x_panel">
                            <div class="x_title">
                              <h2><?php echo $this->escapeHtml("Search for Staff")?></h2>
                                <ul class="nav navbar-right panel_toolbox">
                                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                  </li>
                            
                                </ul>
                             <div class="clearfix"></div>
                          
                            </div>
                               
                            <div class="x_content">
                            <h5><i>*(In order to add Adhoc Issue for a staff, first search for the Staff and then select the Staff from the table below to issue goods to staff. Input as many fields as possible to narrow the search.)<br />
                                            **Also note, search by name is done by "First Name" only and department can be of first letter</i></h5>
                                      <br />
                               <?php
                                // Opening of the form tag
                                $form->prepare();
                                echo $this->form()->openTag($form);
                              ?>
                            
                              <div class="row">
                                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Staff Name</label>
                                    <?php echo $this->formRow($form->get('employee_name')); ?>
                                  </div>
                                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Staff ID</label>
                                    <?php echo $this->formRow($form->get('emp_id')); ?>
                                  </div>
                                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Department</label>
                                    <?php echo $this->formRow($form->get('department')); ?>
                                  </div>
                               </div>
                             
                             <div class="row">
                                <div class="ln_solid"></div>
                                <div class="form-group">
                                    <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                                      <?php
                                       echo $this->formHidden($form->get('csrf'));
                                       echo $this->formSubmit($form->get('submit')); 
                                       echo $this->form()->closeTag(); 
                                    ?>
                                </div>
                            </div>
                              
                          </div>
                        </div>
                       </div>     
                              
                          
                        <div class="col-md-12 col-sm-12 col-xs-12">
                          <div class="x_panel">
                            <div class="x_title">
                              <h2><?php echo $this->escapeHtml("List of Staff(s)"); ?></h2>
                              <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                </li>
                              </ul>
                              <div class="clearfix"></div>
                            </div>
            
                            <div class="x_content">
                              <table id="datatable" class="table table-striped responsive-utilities jambo_table bulk_action table-bordered">
                                <thead>
                                    <th class="column-title">Sl No </th>
                                    <th class="column-title">Staff Name </th>
                                    <th class="column-title">Department</th>
                                    <th class="column-title">DOB </th>
                                    <th class="column-title">CID </th>
                                    <th class="column-title no-link last"><span class="nobr">Action</span></th>
                                </thead>
            
                                <tbody>
                                <?php $i=1; ?>
                                  <?php foreach ($this->staffList as $staff) : ?>
                                  <tr class="even pointer">
                                    <td class=" "><?php echo $i; ?></td>
                                    <td class=" "><?php echo $this->escapeHtml($staff['first_name']) . ' ' .
                                                             $this->escapeHtml($staff['middle_name']) . ' ' .
                                                             $this->escapeHtml($staff['last_name']) . ' ('.
                                                             $this->escapeHtml($staff['emp_id']). ')';?></td>
                                    <td class=" "><?php echo $this->escapeHtml($staff['department_name']);?></td>
                                    <td class=" "><?php echo $this->escapeHtml($staff['date_of_birth']); ?></td>
                                    <td class=" "><?php echo $this->escapeHtml($staff['cid']);?></td></td>
                                    <td class=" last"> <a href="<?php echo $this->url('add-adhoc-goods-issue', array('id' => $staff['id']));?>" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> Issue Goods </a></td>
                                  </tr>
                                  <?php $i++; ?>
                                  <?php endforeach; ?>
                                </tbody>
                              </table>
                            </div>
                          </div>
                        </div>
                        </div>
                      </div>
                  </div>
                </div>
              
