<?php
 // module/Inventory/view/goods-transaction/goods-transaction/edit-item-quantity-type.phtml:

 $title = 'Edit Item Quantity Type';
 $this->headTitle($title);

 $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));
    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}
?>

<div class="right_col" role="main">
    <div class="">             
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                <h2><?php echo $this->escapeHtml($title); ?></h2>
                <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                </ul>
                <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    $itemquantity = $form->get('itemquantitytype');
                    echo $this->form()->openTag($form);
                    $itemquantity->get('id')->setValue($this->itemQtyDetails->getId());
                    $itemquantity->get('item_quantity_type')->setValue($this->itemQtyDetails->getItem_Quantity_Type());
                    $itemquantity->get('remarks')->setValue($this->itemQtyDetails->getRemarks());
                    $itemquantity->get('organisation_id')->setValue($this->itemQtyDetails->getOrganisation_Id());
                    echo $this->formHidden($itemquantity->get('organisation_id'));
                    $itemquantity->get('submit')->setValue('Update Item Quantity Type');
                    echo $this->formHidden($itemquantity->get('id'));
                 ?>               
                
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="item_quantity_type">Item Quantity Type</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                            <?php  echo $this->formRow($itemquantity->get('item_quantity_type')); ?>
                    </div>
                </div>
                
                <div class="form-group">           
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="remarks">Remarks</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                            <?php  echo $this->formRow($itemquantity->get('remarks')); ?>
                    </div>
                </div>
                
                <div class="form-group">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                       <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <?php  
                            echo $this->formHidden($form->get('csrf'));
                            echo $this->formSubmit($itemquantity->get('submit'));
                          ?>
                        </div>
                    </div>
                </div> 

                <?php 
                //closing the form tag  
                 echo $this->form()->closeTag();
                 ?>
                </div>
              </div>
            
            <?php
// module/Inventory/view/goods-transaction/goods-transaction/view-item-quantity-type.phtml:

 $title = 'Item Quantity Type';
 $this->headTitle($title);
?>     
            <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>

                <div class="x_content">
                    <div class="table-responsive">
                        <table class="table table-striped responsive-utilities jambo_table bulk_action table-bordered">
                            <thead>
                                <tr class="headings">
                                    <th class="column-title">Sl. No</th>
                                    <th class="column-title">Item Quantity Type </th>
                                    <th class="column-title">Remarks </th>
                                </tr>
                            </thead>

                            <tbody>
                            <?php $i=1; ?>
                            <?php foreach ($this->itemQuantity as $itemQty) : ?>
                                <tr class="even pointer">
                                    <td class=" "><?php echo $i; ?></td>
                                    <td class=" "><?php echo $this->escapeHtml($itemQty->getItem_Quantity_Type()); ?></td>
                                    <td class=" "><?php echo $this->escapeHtml($itemQty->getRemarks()); ?></td>
                                </tr>
                            <?php $i++; ?>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>