
<?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Goods Lists';
 $this->headTitle($title);

  $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    //IDEA-CBC
    //Original
    //$iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('aes-256-cbc'));

    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));

    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}
?>     
<div class="right_col" role="main">
    <div class="">              
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                  <h5><i>Following are the lists of item issued</i></h5>
                </div>

                <!-- Start of Tab-->
                    <div class="" role="tabpanel" data-example-id="togglable-tabs">
                      <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                        <li role="presentation" class="active"><a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">Fixed Assets</a>
                        </li>
                        <li role="presentation" class=""><a href="#tab_content2" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false">Consumable Assets</a>
                        </li>
                      </ul>
                      <div id="myTabContent" class="tab-content">
                        <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab">
                                <br/>
                                <!-- Adding Item Category-->
                                <div class="col-md-12 col-xs-12">
                                  <div class="x_panel">
                                    <div class="x_title">
                                      <h2><?php echo $this->escapeHtml("Fixed Assets Lists")?></h2>
                                        <ul class="nav navbar-right panel_toolbox">
                                          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                          </li>
                                    
                                        </ul>
                                     <div class="clearfix"></div>
                                    <h5><i>Following are the lists of fixed item and if you want to surrender, please click on surrender button.</i></h5>
                                    </div>

                                    <?php 
                                      if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                                          echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                                          echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                          $messages = $this->flashMessenger()->getMessages();
                                          foreach($messages as $message) {
                                              echo '<strong>Success!</strong>'. $message;
                                          }
                                          echo '</div>';
                                      }

                                      else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                                          echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                                          echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                          $messages = $this->flashMessenger()->getMessages();
                                          foreach($messages as $message) {
                                              echo '<strong>Failure!</strong>'. $message;
                                          }
                                          echo '</div>';
                                      }

                                  ?> 
                                  
                                      <div class="x_content">
                                            <div class="table-responsive">
                                                <table id="datatable" class="table table-striped responsive-utilities jambo_table bulk_action table-bordered">
                                                    <thead>
                                                        <tr class="headings">
                                                            <th class="column-title">Sl. No</th>
                                                            <th class="column-title">Item Category</th>
                                                            <th class="column-title">Sub Category </th>
                                                             <th class="column-title">Item Name </th>
                                                             <th class="column-title">Item Code </th>
                                                             <th class="column-title">Quantity Type </th>
                                                              <th class="column-title">Quantity </th>
                                                               <th class="column-title">Issue Date </th>
                                                            <th class="column-title">Action</th>
                                                        </tr>
                                                    </thead>

                                                    <tbody>
                                                    <?php $i=1; ?>
                                                    <?php foreach ($this->fixedAssetGoodsList as $fixedList) : ?>
                                                        <tr class="even pointer">
                                                            <td class=" "><?php echo $i; ?></td>
                                                            <td class=" "><?php echo $this->escapeHtml($fixedList->getCategory_Type()); ?></td>
                                                            <td class=" "><?php echo $this->escapeHtml($fixedList->getSub_Category_Type()); ?></td>
                                                            <td class=" "><?php echo $this->escapeHtml($fixedList->getItem_Name()); ?></td>
                                                            <td class=" "><?php echo $this->escapeHtml($fixedList->getGoods_Code()); ?></td>
                                                            <td class=" "><?php echo $this->escapeHtml($fixedList->getItem_Quantity_Type()); ?></td>
                                                            <td class=" "><?php echo $this->escapeHtml($fixedList->getEmp_Quantity()); ?></td>
							    <td class=" "><?php echo $this->escapeHtml($fixedList->getDate_Of_Issue()); ?></td>
								
							    <td class=" ">

							   <?php  if ($goodSurrenderedStatus[$fixedList->getId()] == "Pending") 
							   		echo $goodSurrenderedStatus[$fixedList->getId()];  
							       else { ?> 

								       <a href="<?php echo $this->url('apply-goods-surrender', array('id' => my_encrypt($fixedList->getId(), $key))); ?>" class="btn btn-primary btn-xs"><i class="fa fa-send"></i> Surrender </a>                                                   <?php } ?>
                                                            </td>
                                                        </tr>
                                                    <?php $i++; ?>
                                                    <?php endforeach; ?>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div role="tabpanel" class="tab-pane fade" id="tab_content2"  aria-labelledby="profile-tab">
                                    <br/>   
                                          
                                      
                                    <div class="col-md-12 col-sm-12 col-xs-12">
                                      <div class="x_panel">
                                        <div class="x_title">
                                          <h2><?php echo $this->escapeHtml("Consumable Asset Lists"); ?></h2>
                                          <ul class="nav navbar-right panel_toolbox">
                                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                            </li>
                                          </ul>
                                          <div class="clearfix"></div>
                                          <h5><i>Following are the lists of consumable item and just click on Consumed button after you consumed all.</i></h5>
                                        </div>
                                            <div class="x_content">
                                                <table id="datatable-buttons" class="table table-striped responsive-utilities jambo_table bulk_action table-bordered" cellspacing="0" width="100%">
                                                    <thead>
                                                        <tr class="headings">
                                                            <th class="column-title">Sl. No</th>
                                                            <th class="column-title">Item Category</th>
                                                            <th class="column-title">Sub Category </th>
                                                             <th class="column-title">Item Name </th>
                                                             <th class="column-title">Quantity Type </th>
                                                              <th class="column-title">Quantity </th>
                                                               <th class="column-title">Issue Date </th>
                                                            <th class="column-title">Action</th>
                                                        </tr>
                                                    </thead>

                                                    <tbody>
                                                    <?php $i=1; ?>
                                                    <?php foreach ($this->consumableGoodsList as $consumableList) : ?>
                                                        <tr class="even pointer">
                                                            <td class=" "><?php echo $i; ?></td>
                                                            <td class=" "><?php echo $this->escapeHtml($consumableList->getCategory_Type()); ?></td>
                                                            <td class=" "><?php echo $this->escapeHtml($consumableList->getSub_Category_Type()); ?></td>
                                                            <td class=" "><?php echo $this->escapeHtml($consumableList->getItem_Name()); ?></td>
                                                            <td class=" "><?php echo $this->escapeHtml($consumableList->getItem_Quantity_Type()); ?></td>
                                                            <td class=" "><?php echo $this->escapeHtml($consumableList->getEmp_Quantity()); ?></td>
                                                            <td class=" "><?php echo $this->escapeHtml($consumableList->getDate_Of_Issue()); ?></td>
                                                            <th class=" "><a href="<?php echo $this->url('consumeemmpconsumablegoods', array('id' => my_encrypt($consumableList->getId(), $key))); ?>" class="btn btn-primary btn-xs"><i class="fa fa-send"></i> Consumed </a>
                                                            </th>
                                                        </tr>
                                                    <?php $i++; ?>
                                                    <?php endforeach; ?>
                                                    </tbody>
                                                </table>
                                        </div>
                                       
                                      </div>
                                    </div>
                                </div>
                            </div>
                    </div>

            </div>
        </div>
    </div>
</div>
