<?php
 // module/GoodsTransaction/view/goods-transaction/goods-transaction/add-goods-recieved-purchased.phtml:

 $title = 'Staff Goods Lists';
 $this->headTitle($title);
?>

<div class="right_col" role="main">
    <div class=" ">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
        <div class="x_title">
        <h2><?php echo $this->escapeHtml($title); ?></h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
        </ul>

        <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    $staff = $form->get('empissuegoods');
                    echo $this->form()->openTag($form);

                    $staff->get('id')->setValue($this->staffDetails->getId());
                    $staff->get('first_name')->setValue($this->staffDetails->getFirst_Name());
                    $staff->get('middle_name')->setValue($this->staffDetails->getMiddle_Name());
                    $staff->get('last_name')->setValue($this->staffDetails->getLast_Name());
                    $staff->get('emp_id')->setValue($this->staffDetails->getEmp_Id());
                    $staff->get('department_name')->setValue($this->staffDetails->getDepartment_Name());
                     $staff->get('unit_name')->setValue($this->staffDetails->getUnit_Name());


                    echo $this->formHidden($staff->get('id'));
                 ?> 
               
                <h4><i>Staff Details</i></h4>
                <div class="form-group">           
                    <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first_name">First Name</label>
                    <div class="col-md-3 col-sm-3 col-xs-12">
                            <?php  echo $this->formRow($staff->get('first_name')); ?>
                    </div>
                    <label class="control-label col-md-2 col-sm-2 col-xs-12" for="middle_name">Middle Name</label>
                    <div class="col-md-3 col-sm-3 col-xs-12">
                            <?php  echo $this->formRow($staff->get('middle_name')); ?>
                    </div>
                </div>              
                
                <div class="form-group">           
                    <label class="control-label col-md-2 col-sm-2 col-xs-12" for="last_name">Last Name</label>
                    <div class="col-md-3 col-sm-3 col-xs-12">
                            <?php  echo $this->formRow($staff->get('last_name')); ?>
                    </div>
                    <label class="control-label col-md-2 col-sm-2 col-xs-12" for="emp_id">Staff ID</label>
                    <div class="col-md-3 col-sm-3 col-xs-12">
                            <?php  echo $this->formRow($staff->get('emp_id')); ?>
                    </div>
                </div>
                                <div class="form-group">           
                    <label class="control-label col-md-2 col-sm-2 col-xs-12" for="department_name">Department</label>
                    <div class="col-md-3 col-sm-3 col-xs-12">
                            <?php  echo $this->formRow($staff->get('department_name')); ?>
                    </div>
                    <label class="control-label col-md-2 col-sm-2 col-xs-12" for="unit_name">Unit</label>
                    <div class="col-md-3 col-sm-3 col-xs-12">
                            <?php  echo $this->formRow($staff->get('unit_name')); ?>
                    </div>
                </div>
                <br>   

                <?php 
                //closing the form tag  
                echo $this->form()->closeTag();
                 ?>             
        </div> <!-- End of x-content -->
 

            <!-- Start of table listing item to issue -->
                <div class="x_panel">
                  <div class="x_title">
                    <h2><?php echo $this->escapeHtml('Lists of Item Issued'); ?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <h5><i>*The following are the list of the item issued to particular staff mentioned above.</i></h5>
                  <br />
                  <div class="x_content">
                     <div class="table-responsive">
                      <table class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">     
                            <th class="column-title">Sl.No. </th>
			    <th class="column-title">Item Name</th>
			    <th class="column-title">Item Code</th>
			    <th class="column-title">Goods Received Date (store)</th>
			    <th class="column-title">Actual Costs</th>
			    <th class="column-title">Scrap Value</th>
			    <th class="column-title">Depreciation %</th>
			    <th class="column-title">Depreciation value till Date</th>
                            <th class="column-title">Item Quantity</th>
                            <th class="column-title">Issued Date</th>
                          </tr>
                        </thead>
                        <tbody>
                        <?php $i=1; ?>
                        <?php foreach ($this->goodsListDetails as $goodsList) : ?>
                            <tr>
                                  <td class=" "><?php echo $i;   echo 'ID:'.$goodsList['item_name_id']; ?></td>
                                  <td class=" "><?php echo $this->escapeHtml($goodsList['item_name']);?></td>
				  <td class=" "><?php echo $this->escapeHtml($goodsList['goods_code']);?></td>
				  <td class=" "><?php echo $checkDepreciation[$goodsList['id']][$goodsList['item_name_id']]?></td>
				  <td class=" "><?php echo $checkDepreciation['amount'][$goodsList['item_name_id']]?></td>
				  <td class=" "><?php echo $checkDepreciation['scrap'] [$goodsList['item_name_id']]?></td>
				  <td class=" "><?php echo $checkDepreciation['depercent'][$goodsList['item_name_id']].'%'; ?> </td>
				  <td class=" "><?php echo $checkDepreciation[$goodsList['item_name_id']][$goodsList['id']]?></td>
				  <td class=" "><?php echo $this->escapeHtml($goodsList['emp_quantity']);?></td>
                                  <td class=" "><?php echo $this->escapeHtml($goodsList['date_of_issue']);?></td>  
                                   
                            </tr>
                            <?php $i++; ?>
                         <?php endforeach; ?>
                   
                        </tbody>
                      </table>
                     </div>
                 </div>                 
             </div>
        </div> 
    </div>
</div>
</div>

