<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
<div class="menu_section">
<br><br><br>
<ul class="nav side-menu">
	<li><a><i class="fa fa-home"></i>Home<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a href="<?php echo $this->url('index') ?>">Dashboard</a></li>
		</ul>
	</li>
	<li><a><i class="fa fa-user"></i>Counseling Service<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a href="<?php echo $this->url('counselingappointment') ?>">Seek Appointment</a></li>
			<li><a href="<?php echo $this->url('recommendcounseling') ?>">Recommend for Counseling</a></li>
			<li><a href="<?php echo $this->url('viewappointments') ?>">View Appointment</a></li>
			<li><a href="<?php echo $this->url('appointmentlists') ?>">Grant Appointment</a></li>
			<li><a href="<?php echo $this->url('recommendcounselinglist') ?>">View Counseling Recommended</a></li>
			<li><a href="<?php echo $this->url('recommendedcounselinglist') ?>">Recommended Counseling List</a></li>
			<li><a href="<?php echo $this->url('counselingrecord') ?>">Record Counseling Detail</a></li>
			<li><a href="<?php echo $this->url('listcounselingrecord') ?>">View Records</a></li>
		</ul>
	</li>
</ul>
</div>
</div>
