<?php
 $title = 'List of All Programmes';
 $this->headTitle($title);

  $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    //IDEA-CBC
    //Original
    //$iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('aes-256-cbc'));

    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));

    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}
?>
<div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title)?></h2>
                   <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                    </ul> 
                 <div class="clearfix"></div>
                </div>
                <?php if($this->message == NULL && $this->flashMessenger()->hasMessages()) {
					echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
					echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
					$messages = $this->flashMessenger()->getMessages();
					foreach($messages as $message) {
						echo '<strong>Success!</strong>'. $message;
					}
					echo '</div>';
				} else if($this->message =='Failure' && $this->flashMessenger()->hasMessages()) {
					echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
					echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
					$messages = $this->flashMessenger()->getMessages();
					foreach($messages as $message) {
						echo '<strong>Warning!</strong>'. $message;
					}
					echo '</div>';
			 } ?>
                <div class="x_content">
                  <div class="table-responsive">
                  <table id="datatable-buttons" class="table table-striped jambo_table table-bordered" width="100%">
                    <thead>
                      <tr class="headings">
                        <th class="column-title" width="5%">Sl. No</th>
                        <th class="column-title">Programme Name</th>
                        <th class="column-title">Programme Leader</th>
                        <th class="column-title">Approval Date</th>
                        <th class="column-title">APMR Date</th>
                        <th class="column-title">CCR Date</th>
                        <th class="column-title no-link last"><span class="nobr">Action</span> </th>
                      </tr>
                    </thead>
                    <tbody>
                        <?php $i=1; foreach ($this->programmes as $programme) : ?>
                      <tr class="even pointer">
                        <td class=" "><?php echo $i++;?></td>
                        <td class=" "><?php echo $this->escapeHtml($programme['programme_name']);?></td>
                        <td class=" "><?php echo $this->escapeHtml($programme['first_name'].' '.$programme['middle_name'].' '.$programme['last_name']);?></td>
                        <td class=" "><?php echo $this->escapeHtml($programme['programme_approval_date']);?></td>
                        <td class=" "><?php echo $this->escapeHtml($programme['programme_apmr_date']);?></td>
                        <td class=" "><?php echo $this->escapeHtml($programme['programme_ccr_date']);?></td>
                        <td><a href="<?php echo $this->url('viewprogrammehistory', array('id' => my_encrypt($programme['id'], $key)));?>" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i>View</a>
                            <a href="<?php echo $this->url('updateprogramme', array('id' => my_encrypt($programme['id'], $key)));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Update</a></td>
                      </tr>
                      <?php endforeach; ?>
                    </tbody>
                  </table>
                </div>
                </div>
                
                </div>
              </div>
             </div>
           </div>
          </div>
        </div> 
     </div>
     
     