<?php
 $title = 'Update Programme (College DAA)';
 $this->headTitle($title);
?>
<div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title)?></h2>
                   <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                    </ul> 
                 <div class="clearfix"></div>
              
                </div>
             
                 
                  <div class="x_content">
                <form> <br/>
                 <div class="row">
                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Programme Name</label>
                      <select class="form-control">
                        <option></option>  
                      </select>
                  </div>
                     <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Programme Leader</label>
                     <input type="text" placeholder="" class="form-control" >
                  </div>
                     <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Programme Approval Date</label>
                      <select class="form-control">
                        <option>Auto Captured</option>  
                      </select>
                  </div>
                     <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Programme APMR Date</label>
                      <select class="form-control">
                        <option>Auto captured and editable</option>  
                      </select>
                  </div>
                     <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Programme Complete Cycle Review Date</label>
                      <select class="form-control">
                        <option>Auto captured and editable</option>  
                      </select>
                  </div>
                     
                     <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Upload Review DPD</label>
                    <input type="file" placeholder="" class="form-control" >
                  </div> 
                    
                     </div><br/>
                      <div class="row">
                        <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                             <button class="btn btn-success">Add</button>
                   
                 </div>
                </div>
               </div>
                      </form><br/>
             <div class="x_content">

            <div class="table-responsive">
                  <table class="table   table-striped responsive-utilities jambo_table bulk_action table-bordered" width="100%">
                    <thead>
                      <tr class="headings">
                        </th>
                         <th class="column-title">Sl.No </th>
                        <th class="column-title">Programme Name</th>
                        <th class="column-title">Programme leader</th>
                        <th class="column-title">Programme Approved Date</th>
                        <th class="column-title">Programme Complete Cycle Review Date</th>
                           <th class="column-title">upload Review DPD</th>
                            
                        <th class="bulk-actions" colspan="7">
                          <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                        </th>
                      </tr>
                    </thead>

                    <tbody>
                      <tr class="even pointer">
                       <td class=" ">1</td>
                       <td class=" "></td>
                       <td class=" "></td>
                       <td class=" "></td>
                       <td class=" "></td>
                       <td class=" "></td>
                      </tr>
                      
                    </tbody>
                  </table>
                </div>
                 
                </div>
              </div>
            </div>
                      
                  
          </div>
        </div>
                  </div>
          
 
                
                 