<?php
 $title = 'Student Assessment Marks';
 $this->headTitle($title);
 
 $assessment_components = array();
 $student_id = array();
 $student_names = array();
 $assessment_weightage = array();
 foreach($this->studentAssessmentList as $key=>$value):
   foreach($value as $key2 => $value2):
     foreach($value2 as $key3 => $value3):
       foreach($value3 as $key4 => $value4):
	   		$assessment_components[$key4][$key][$value4['marks']]= $value4['id'];
			$assessment_weightage[$key]['weightage'] = $key2;
			$assessment_weightage[$key]['assessment_marks'] = $key3;
	   endforeach;
      endforeach;
   endforeach;
 endforeach;
 
 
 foreach($this->studentNameList as $key=>$value){
	 $student_names[$key] = $value;
 }
 
 $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    //IDEA-CBC
    //Original
    //$iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('aes-256-cbc'));

    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));

    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}
?>

 <div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
            
                <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                     <div class="clearfix"></div>
                    </div>
                    <br/>
                        <?php if($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                          echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                          echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                          $messages = $this->flashMessenger()->getMessages();
                          foreach($messages as $message) {
                            echo '<strong>Success!</strong>'. $message;
                          }
                          echo '</div>';
						  } else if($this->message =='Failure' && $this->flashMessenger()->hasMessages()) {
								echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
								echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
								$messages = $this->flashMessenger()->getMessages();
								foreach($messages as $message) {
									echo '<strong>Warning!</strong>'. $message;
								}
								echo '</div>';
						 } ?>
                        <!-- Adding Achievements-->
                        <div class="col-md-12 col-xs-12">
                          <div class="x_panel">
                            <div class="x_title">
                              <h2><?php echo $this->escapeHtml("Search for Students by Module")?></h2>
                                <ul class="nav navbar-right panel_toolbox">
                                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                  </li>
                            
                                </ul>
                             <div class="clearfix"></div>
                          
                            </div>
                               
                            <div class="x_content">
                            <h5><i>*(In order to add the students' mark, search by Module Name. Please note that the search is only done
                            		 by Module Name. However, both Module Name and Assessment Type has to be selected inorder to enter the marks)</i></h5>
                              <br />
                               <?php
                                // Opening of the form tag
                                $form->prepare();
                                echo $this->form()->openTag($form);
								$form->get('assessment_type')->setValue(1);
                                $form->get('section')->setValueOptions($this->sectionList);
                              ?>
                            
                              <div class="row">
                                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Module</label>
                                    <?php echo $this->formRow($form->get('assessment_component_id')); ?>
                                  </div>
                                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Section</label>
                                    <?php echo $this->formRow($form->get('section')); ?>
                                  </div>
                              </div>
                             <div class="row">
                                <div class="ln_solid"></div>
                                <div class="form-group">
                                    <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                                      <?php
                                       echo $this->formHidden($form->get('assessment_type'));
									   echo $this->formHidden($form->get('csrf'));
                                       echo $this->formSubmit($form->get('submit')); 
                                       echo $this->form()->closeTag(); 
                                    ?>
                                </div>
                            </div>
                              
                          </div>
                        </div>
                       </div>     
                              
                        <div id="print-content">  
                        <div class="col-md-12 col-sm-12 col-xs-12">
                          <div class="x_panel">
                            <div class="x_title">
                              <h2><?php echo $this->escapeHtml("List of Student(s)"); ?></h2>
                              <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                </li>
                              </ul>
                              <div class="clearfix"></div>
                            </div>
                            <div class="x_content">
                            <h5>
                            <b><i class="blue">MO: Marks Obtained&nbsp;&nbsp;&nbsp;&nbsp;M: Marks after conversion&nbsp;&nbsp;&nbsp
                            W: Weightage</i>&nbsp;&nbsp;
                            &nbsp;&nbsp;<i class="blue">FM: Total of Assessment </i>
                            </b></h5>
                              <table class="table   table-striped responsive-utilities jambo_table bulk_action table-bordered" border="1" width="100%">
                                <thead>
                                <tr>
                                    <td class="column-title" style="width:5%" rowspan="2">Sl No </td>
                                    <td class="column-title" style="width:15%" rowspan="2">Student Name </td>
                                    <td class="column-title" style="width:8%" rowspan="2">SID</td>
                                    <?php foreach($this->studentAssessmentList as $key => $value): ?>
									<td style="width: 3%" class="column-title" colspan="2"><?php echo $key; ?></td>
									<?php endforeach; ?>
                                </tr>
                                <tr>
									<?php foreach($this->studentAssessmentList as $key => $value): ?>
										<?php foreach($value as $key2 => $value2): ?>
											<?php foreach($value2 as $key3 => $value3): ?>
                                            	<td class="column-title" style="width:8%"><?php echo "MO [W=".$key2." / FM=".$key3."]"; ?></td>
                                                <td class="column-title" style="width:8%"><?php echo "M"; ?></td>
                                            <?php endforeach; ?>
                                        <?php endforeach; ?>
                                    <?php endforeach; ?>
                                </tr>
                                </thead>
                                <tbody>
                                  <?php $i = 1; foreach($assessment_components as $key=>$value):?>
                                    <tr class="even pointer">
                                       <td class=" "><?php echo $i++; ?></td>
                                       <td class=" "><?php echo $student_names[$key];  ?></td>
                                       <td class=" "><?php echo $key;  ?></td>
                                  		<?php foreach($value as $key2 => $value2): ?>
                                        	<?php foreach($value2 as $key3 => $value3): ?> 
                                            <td class=" "><?php echo $key3; ?> <a href="<?php echo $this->url('editstudentassessmentmark', array('id' => $value3));?>"><i class="fa fa-pencil pull-right"></i></a></td>
                                            <td class=" "><?php echo number_format((float)(($key3)*$assessment_weightage[$key2]['weightage']/$assessment_weightage[$key2]['assessment_marks']),2,'.','');; ?></td>
                                                      
                                  			<?php endforeach; ?>
                                        <?php endforeach; ?>
                                    </tr>
									<?php endforeach; ?>
                                </tbody>
                              </table>
                            </div>
                          </div>
                        </div>
                        <input type="button" class="btn btn-primary" onclick="printDiv('print-content')" value="Print this Page"/>
                  <!-- End of display-->
            </div>
                        <div class="clearfix"></div>
                           		<!-- End of Achievements-->
                        </div>
                      </div>
                  </div>
                </div>
              
