<?php
 // module/research-publication/view/research-publication/research-publication/announce-seminar.phtml:
 $title = 'Edit Research Seminar / Meets Announcement (DRER / DRIL)';
 $this->headTitle($title);

 $announcement_details = array();
 foreach($this->seminarAnnouncementDetails as $details){
     $announcement_details = $details;
 }

 $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));
    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    $research = $form->get('seminarannouncement');
                    echo $this->form()->openTag($form);
                    $research->get('id')->setValue($this->id);
                    $research->get('seminar_title')->setValue($announcement_details['seminar_title']);
                    $research->get('seminar_location')->setValue($announcement_details['seminar_location']);
                    $research->get('seminar_country')->setValue($announcement_details['seminar_country']);
                    $research->get('funding_agency')->setValue($announcement_details['funding_agency']);
                    $research->get('remarks')->setValue($announcement_details['remarks']);
                    $research->get('organisation_id')->setValue($announcement_details['organisation_id']);
                    $research->get('announced_by')->setValue($announcement_details['announced_by']);
                    $research->get('seminar_country')->setValueOptions($this->countryList);
                    $research->get('funding_agency')->setValueOptions($this->fundingTypes);
                    $research->get('organisation_id')->setValue($this->organisation_id);
                    $research->get('announced_by')->setValue($this->employee_details_id);
                    $seminar_start_date = explode("-",$announcement_details['seminar_start_date']);
                    $seminar_end_date = explode("-", $announcement_details['seminar_end_date']);
                    $research->get('seminar_start_date')->setValue($seminar_start_date[01].'/'.$seminar_start_date[02].'/'.$seminar_start_date[00]);
                    $research->get('seminar_end_date')->setValue($seminar_end_date[01].'/'.$seminar_end_date[02].'/'.$seminar_end_date[00]);
                    $research->get('submit')->setValue('Update');
                    echo $this->formHidden($research->get('organisation_id')); 
                    echo $this->formHidden($research->get('announced_by')); 
                    echo $this->formHidden($research->get('id')); 
                    ?>  

                <?php 
                    if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                        echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                        echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                        $messages = $this->flashMessenger()->getMessages();
                        foreach($messages as $message) {
                            echo '<strong>Success!</strong>'. $message;
                        }
                        echo '</div>';
                    }

                    else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                        echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                        echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                        $messages = $this->flashMessenger()->getMessages();
                        foreach($messages as $message) {
                            echo '<strong>Failure!</strong>'. $message;
                        }
                        echo '</div>';
                    }

                ?> 

                <div class="row">    
                  <div class="form-group">
                    <label class="control-label col-md-2 col-sm-2 col-xs-12">Seminar Title<span>*</span>:</label>
                    <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($research->get('seminar_title')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                  <label class="control-label col-md-2 col-sm-2 col-xs-12"> Seminar Location<span>*</span>: </label>
                    <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($research->get('seminar_location')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-2 col-sm-2 col-xs-12">Seminar Country<span>*</span>: </label>
                    <div class="col-md-6 col-sm-12 col-xs-12">
                      <?php  echo $this->formRow($research->get('seminar_country')); ?>
                    </div>
                  </div>

                  <div class="form-group">
                    <label class="control-label col-md-2 col-sm-2 col-xs-12">Seminar Start Date<span>*</span>: </label>
                    <div class="col-md-2 col-sm-12 col-xs-12">
                      <?php  echo $this->formRow($research->get('seminar_start_date')); ?>
                    </div>
                    <label class="control-label col-md-2 col-sm-2 col-xs-12">Seminar End Date<span>*</span>: </label>
                    <div class="col-md-2 col-sm-12 col-xs-12">
                      <?php  echo $this->formRow($research->get('seminar_end_date')); ?>
                    </div>
                  </div>

                  <div class="form-group">
                    <label class="control-label col-md-2 col-sm-2 col-xs-12">Funding Source<span>*</span>:</label>
                    <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($research->get('funding_agency')); ?>
                    </div>
                  </div>

                  <div class="form-group">
                    <label class="control-label col-md-2 col-sm-2 col-xs-12">Remarks:</label>
                    <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($research->get('remarks')); ?>
                    </div>
                  </div>
                </div> 
                  
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                        <?php                       
                          echo $this->formHidden($form->get('csrf'));
                          echo $this->formSubmit($research->get('submit')); 
                        ?>
                    	</div>
                    </div>
                    </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                </div>
              </div>

              <div class="x_panel">
                <div class="x_content">
                     <div class="table-responsive">
                      <table id="datatable" class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Sl. No</th>
                            <th class="column-title">Seminar Title</th>
                            <th class="column-title">Seminar Location</th>
                            <th class="column-title">Seminar Country</th>
                            <th class="column-title">Start Date</th>
                            <th class="column-title">End Date</th>
                            <th class="column-title">Funding Agency</th>      
                             </tr>
                        </thead>  
                        <tbody>
                         <?php $i = 1; foreach ($this->seminarAnnouncementList as $list) : ?>
                          <tr class="even pointer">
                            <td class=" "><?php echo $i++;?></td>
                            <td class=" "><?php echo $this->escapeHtml($list['seminar_title']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($list['seminar_location']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($list['country']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($list['seminar_start_date']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($list['seminar_end_date']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($list['funding_type']);?></td>
                          </tr>
                          <?php endforeach; ?>
                      </tbody>
                      </table>
                     </div>
                  </div>
               </div>
             </div>
        </div>
    
