<?php
 $title = 'Request For Publication Proposal (DRIL / OVC)';
 $this->headTitle($title);

 $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));
    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				            $research = $form->get('researchannouncement');
                    echo $this->form()->openTag($form);
					         $research->get('research_publication_type')->setValueOptions($this->publicationList);
                   $research->get('organisation_id')->setValue($this->organisation_id);
                   echo $this->formHidden($research->get('organisation_id')); 
                    echo $this->formHidden($research->get('id')); 
				  ?>  
                <?php 
                    if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                        echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                        echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                        $messages = $this->flashMessenger()->getMessages();
                        foreach($messages as $message) {
                            echo '<strong>Success!</strong>'. $message;
                        }
                        echo '</div>';
                    }

                    else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                        echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                        echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                        $messages = $this->flashMessenger()->getMessages();
                        foreach($messages as $message) {
                            echo '<strong>Failure!</strong>'. $message;
                        }
                        echo '</div>';
                    }

                ?> 
                <div class="row">    
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Publication Type/Name</label>
                    <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($research->get('research_publication_type')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Start Submission Date </label>
                    <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($research->get('start_date')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">End Submission Date </label>
                    <div class="col-md-3 col-sm-12 col-xs-12">
                      <?php  echo $this->formRow($research->get('end_date')); ?>
                    </div>
                  </div>
                </div> 
                  
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
						            <?php
                           
          						   echo $this->formHidden($form->get('csrf'));
          						   echo $this->formSubmit($research->get('submit')); 
                        ?>
                    	</div>
                    </div>
               </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                </div>
              </div>

              <div class="x_panel">
                <div class="x_content">
                     <div class="table-responsive">
                      <table class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Sl. No</th>
                            <th class="column-title">Publication Name</th>
                            <th class="column-title">Publication Type</th>
                            <th class="column-title">From Date</th>
                            <th class="column-title">To Date</th>
                            <th class="column-title">Remarks</th>
                            <th class="column-title">Action</th>
                            
                             </tr>
                        </thead>  
                        <tbody>
                      <tr>
                         <?php $i = 1; foreach ($this->publicationAnnouncement as $announcement) : ?>
                          <tr class="even pointer">
                            <td class=" "><?php echo $i++;?></td>
                            <td class=" "><?php echo $announcement['publication_name']; ?></td>
                            <td class=" "><?php echo $announcement['publication_type']; ?></td>
                            <td class=" "><?php echo $announcement['start_date']; ?></td>
                            <td class=" "><?php echo $announcement['end_date']; ?></td>
                            <td class=" "><?php echo $announcement['remarks']; ?></td>
                            <td class=" last"><a href="<?php echo $this->url('editrequestpublication', array('id' => my_encrypt($announcement['id'], $key)));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a></td>
                          </tr>
                          <?php endforeach; ?>
                      </tr>
                      </tbody>
                      </table>
                     </div>
                  </div>
               </div>

        </div>
    
          </div>
        </div> 
     </div>