<?php
 $title = 'Research Publication Application Status';
 $this->headTitle($title);

 $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));
    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}

?>
	<div class="right_col" role="main">
          <div class="">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                      <div class="x_title">
                        <h2><?php echo $this->escapeHtml($title); ?></h2>
                        <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"></a>
                      </li>
                      </ul>
                      <div class="clearfix"></div>
                      </div>
                      <?php 
                    if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                        echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                        echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                        $messages = $this->flashMessenger()->getMessages();
                        foreach($messages as $message) {
                            echo '<strong>Success!</strong>'. $message;
                        }
                        echo '</div>';
                    }

                    else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                        echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                        echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                        $messages = $this->flashMessenger()->getMessages();
                        foreach($messages as $message) {
                            echo '<strong>Failure!</strong>'. $message;
                        }
                        echo '</div>';
                    }

                ?>
                      <div class="table-responsive">
                      <table id="datatable-fixed-header" class="table table-striped jambo_table table-bordered">
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Publication Title </th>
                            <th class="column-title">Publication Type </th>
                            <th class="column-title">Submission Date </th>
                            <th class="column-title">Status</th>
                            <th class="column-title">Action</th>
                            
                             </tr>
                        </thead>  
                        <tbody>
                         <?php foreach ($this->researchPublication as $publication) : ?>
                          <tr class="even pointer">
                            <td class=" "><?php echo $this->escapeHtml($publication['publication_name']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($publication['publication_type']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($publication['submission_date']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($publication['publication_status']);?></td>
                            <td class=" last">
                              <?php if(($publication['publication_status'] == 'Accept Subject to identified limited revisions') OR ($publication['publication_status'] == 'Resubmit following substantial revision')) {?>
                              <a href="<?php echo $this->url('editpublication', array('id' => my_encrypt($publication['id'], $key))); ?>" class="btn btn-info btn-xs"><i class="fa fa-eye"></i> Edit</a>
                            <?php }?>
                              <?php if($publication['publication_file'] != NULL){?>
                            	<a href="<?php echo $this->url('downloadpublication', array('id' => my_encrypt($publication['id'], $key)));	?>" class="btn btn-primary btn-xs"><i class="fa fa-download"></i> Download</a>
                            <?php }else{?>
                              <p><i>File Not Uploaded!</i></p>
                            <?php } ?>
                            </td>
                          </tr>
                          <?php endforeach; ?>
                      </tbody>
                      </table>
                     </div>
               </div>
             </div>
          </div>
        </div>
              