<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
<div class="menu_section">
<br><br><br>
<ul class="nav side-menu">
	<li><a><i class="fa fa-home"></i>Home<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a href="<?php echo $this->url('index') ?>">Dashboard</a></li>
		</ul>
	</li>
	<li><a><i class="fa fa-users"></i>Human Resource<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>HR Planning<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>HRD Planning<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('hrdproposal') ?>">HRD Proposal</a></li>
						<li><a href="<?php echo $this->url('hrdapprovedlist') ?>">HRD Plan Approved List</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>HRM Planning<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('hrmproposal') ?>">Work Force Proposal</a></li>
						<li><a href="<?php echo $this->url('hrmapprovedlist') ?>">Work Force Approved List</a></li>
					</ul>
					</li>
			</ul>
			</li>
			<li><a><i class=""></i>Recruitment<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>Announce Vacancy<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('announceplannedlist') ?>">Planned</a></li>
						<li><a href="<?php echo $this->url('announceadhocvacancy') ?>">Adhoc</a></li>
						<li><a href="<?php echo $this->url('viewannouncedvacancy') ?>">Edit/View Announced Vacancy</a></li>
					</ul>
					</li>
					<li><a href="<?php echo $this->url('addnewemployee') ?>">Add New Staff</a></li>
					<li><a href="<?php echo $this->url('employeeonprobation') ?>">Regularize Staff</a></li>
					<li><a href="<?php echo $this->url('newemployeelist') ?>">Generate Staff ID</a></li>
					<li><a href="<?php echo $this->url('listvacancy') ?>">List Job Vacancies</a></li>
					<li><a href="<?php echo $this->url('jobapplicantstatus') ?>">Job Applicant Status & Recruitment</a></li>
					<li><a href="<?php echo $this->url('appliedjobapplicationstatus') ?>">Individual Job Applicant Status</a></li>
					<li><a href="<?php echo $this->url('viewappliedapplicantmarks') ?>">View Applicant Marks</a></li>
					<li><a href="<?php echo $this->url('jobregistrantdetails') ?>">View/Edit Job Registrant Details</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>HR Administration<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>Leave<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('leavestatus') ?>">Apply Leave</a></li>
						<li><a href="<?php echo $this->url('empleaveapproval') ?>">Leave Approval</a></li>
						<li><a href="<?php echo $this->url('staffleavestatus') ?>">My Leave Status</a></li>
						<li><a href="<?php echo $this->url('empleavedetaillist') ?>">Staff Leave Balance</a></li>
						<li><a href="<?php echo $this->url('applyonbehalfleave') ?>">Apply Leave On Behalf</a></li>
						<li><a href="<?php echo $this->url('empapprovedleavelist') ?>">Cancel Approved Leave</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Attendance<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('empattendance') ?>">Enter Attendance</a></li>
						<li><a href="<?php echo $this->url('viewempattendance') ?>">Staff Attendance</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Leave Encashment<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('empleaveencashmentapplication') ?>">Leave Encashment</a></li>
						<li><a href="<?php echo $this->url('empleaveencashmentlist') ?>">Leave Encashment List</a></li>
						<li><a href="<?php echo $this->url('empleaveencashmentorder') ?>">Leave Encashment Order</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Staff Task<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('employeetaskcategory') ?>">Add Task/Project</a></li>
						<li><a href="<?php echo $this->url('addempemployeetaskrecord') ?>">Add Self Activities</a></li>
						<li><a href="<?php echo $this->url('employeetaskrecord') ?>">Add Other Staff Activities</a></li>
						<li><a href="<?php echo $this->url('viewemployeetaskrecord') ?>">View Staff Task/Activities</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Department Filing<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('departmentfilingtype') ?>">Add Filing Category</a></li>
						<li><a href="<?php echo $this->url('uploaddepartmentdocuments') ?>">Upload Documents</a></li>
						<li><a href="<?php echo $this->url('viewfilingdocument') ?>">View Documents</a></li>
					</ul>
					</li>
					<li><a href="<?php echo $this->url('empassignofficiatingsupervisor') ?>">Assign Officiating Supervisor</a></li>
					<li><a href="<?php echo $this->url('employeepaydetails') ?>">Staff Pay Details</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>HR Development<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>Long Term Trainings<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('longtermplannedlist') ?>">Planned</a></li>
						<li><a href="<?php echo $this->url('longtermadhoc') ?>">Adhoc</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Short Term Trainings<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('shorttermplannedlist') ?>">Planned</a></li>
						<li><a href="<?php echo $this->url('shorttermadhoc') ?>">Adhoc</a></li>
					</ul>
					</li>
					<li><a href="<?php echo $this->url('nominatestaff') ?>">Nominate Staff for Trainings</a></li>
					<li><a href="<?php echo $this->url('applytrainings') ?>">Apply Trainings & Workshops</a></li>
					<li><a href="<?php echo $this->url('viewtrainingapplications') ?>">View Trainings & Workshop Applications</a></li>
					<li><a href="<?php echo $this->url('updatestudystatus') ?>">Update Training Status</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Staff Lifecycle<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>Transfer<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('applytransferform') ?>">Apply Transfer</a></li>
						<li><a href="<?php echo $this->url('transferfromapproval') ?>">From Org/College Approval</a></li>
						<li><a href="<?php echo $this->url('transfertoapproval') ?>">To Org/College Approval</a></li>
						<li><a href="<?php echo $this->url('transferapplicationstatus') ?>">Transfer Applicantion Status</a></li>
						<li><a href="<?php echo $this->url('stafftransferstatus') ?>">My Transfer Status</a></li>
						<li><a href="<?php echo $this->url('approvedtransfers') ?>">Approved Transfers</a></li>
						<li><a href="<?php echo $this->url('transferstaff') ?>">Transfer Staff</a></li>
						<li><a href="<?php echo $this->url('empdepartmentsearch') ?>">Transfer Department</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Promotion<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('empapplypromotion') ?>">Apply Promotion</a></li>
						<li><a href="<?php echo $this->url('empmeritoriouspromotion') ?>">Meritorious Promotion</a></li>
						<li><a href="<?php echo $this->url('promotionapplicantstatus') ?>">Update Promoted Applicants</a></li>
						<li><a href="<?php echo $this->url('staffpromotionstatus') ?>">My Promotion Status</a></li>
						<li><a href="<?php echo $this->url('emppromotionsearch') ?>">Promotion Via Open Competition</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Separation<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('empresignation') ?>">Apply Resignation</a></li>
						<li><a href="<?php echo $this->url('resignationapprovallist') ?>">Resignation Approval</a></li>
						<li><a href="<?php echo $this->url('resignationrecord') ?>">Dues Record</a></li>
						<li><a href="<?php echo $this->url('staffresignationstatus') ?>">My Resignation Status</a></li>
						<li><a href="<?php echo $this->url('recordresignedemployee') ?>">Add Compulsory Separation</a></li>
						<li><a href="<?php echo $this->url('separationrecord') ?>">Issue Relieving Order</a></li>
						<li><a href="<?php echo $this->url('separationrecordlist') ?>">Separation Record List</a></li>
					</ul>
					</li>
			</ul>
			</li>
			<li><a><i class=""></i>PMS<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>Appraisals<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('administrativeappraisal') ?>">Administrative Appraisal</a></li>
						<li><a href="<?php echo $this->url('academicappraisal') ?>">Academic Appraisal</a></li>
						<li><a href="<?php echo $this->url('appraisalapprovallist') ?>">Appraisal Approval Lists</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Review<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('empperformanceassessment') ?>">Staff Performance Assessment</a></li>
						<li><a href="<?php echo $this->url('feedbacks') ?>">Feedbacks</a></li>
						<li><a href="<?php echo $this->url('performancereviewlist') ?>">Performance Review Lists</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Completed Assessment<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('empviewassessment') ?>">Staff View Performance Assessment</a></li>
					</ul>
					</li>
					<li><a href="<?php echo $this->url('addpmsdates') ?>">Activate PMS Dates</a></li>
					<li><a href="<?php echo $this->url('listnominations') ?>">Nominations</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Staff Tour<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('emptravelauthorization') ?>">Travel Authorization</a></li>
					<li><a href="<?php echo $this->url('onbehalfemptravelauthorization') ?>">On behalf Travel Authorization </a></li>
					<li><a href="<?php echo $this->url('emptravellist') ?>">Travel Approval</a></li>
					<li><a href="<?php echo $this->url('emptravelorder') ?>">Travel Order</a></li>
					<li><a href="<?php echo $this->url('stafftourstatus') ?>">Travel Status</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Organisation Settings<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('hrothersetting') ?>">HR Other Setting</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Staff Management<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('addemployee') ?>">Add Missing Staff</a></li>
					<li><a href="<?php echo $this->url('employeelist') ?>">Staff List</a></li>
					<li><a href="<?php echo $this->url('empprofilepicture') ?>">Staff Profile Picture</a></li>
					<li><a href="<?php echo $this->url('updateempinitialdetails') ?>">Update Staff Details</a></li>
					<li><a href="<?php echo $this->url('emprelationdetail') ?>">Staff Relation Details</a></li>
					<li><a href="<?php echo $this->url('empworkexperience') ?>">Staff Work Experience</a></li>
					<li><a href="<?php echo $this->url('empeducation') ?>">Staff Education</a></li>
					<li><a href="<?php echo $this->url('emptrainingdetail') ?>">Staff Trainings</a></li>
					<li><a href="<?php echo $this->url('emppublication') ?>">Staff Publications</a></li>
					<li><a href="<?php echo $this->url('empresponsibility') ?>">Staff Responsibilities</a></li>
					<li><a href="<?php echo $this->url('empcontribution') ?>">Staff Contributions</a></li>
					<li><a href="<?php echo $this->url('empaward') ?>">Staff Awards</a></li>
					<li><a href="<?php echo $this->url('empcommunityservice') ?>">Staff Community Service</a></li>
					<li><a href="<?php echo $this->url('editstaffdepartment') ?>">Change Department</a></li>
					<li><a href="<?php echo $this->url('editstaffpositiontitlelevel') ?>">Edit Current Position</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>HR Reports<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('hrplanningreports') ?>">Staff Planning Reports</a></li>
					<li><a href="<?php echo $this->url('hrrecruitmentreports') ?>">HR Recruitment Report</a></li>
					<li><a href="<?php echo $this->url('hradministrationreports') ?>">HR Administration Report</a></li>
					<li><a href="<?php echo $this->url('hrdevelopmentreports') ?>">HR Development Report</a></li>
					<li><a href="<?php echo $this->url('hrlifecyclereports') ?>">HR Lifecycle Report</a></li>
			</ul>
			</li>
		</ul>
	</li>
	<li><a><i class="fa fa-calendar"></i>Planning<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>Create APA<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>APA Activities<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('activities') ?>">Executive Activities</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Success Indicator<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('successindicator') ?>">Executive Indicator</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Mid Term Review<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('midtermreview') ?>">Executive Mid Term Review</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>APA Evaluation<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('evaluateapa') ?>">Executive APA Evaluation</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Success Indicator Trend<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('addsuccessindicatortrend') ?>">Executive Indicator Trend</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Success Indicator Definition<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('addsuccessindicatordefinition') ?>">Executive Indicator Definition</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Success Indicator Requirements<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('addsuccessindicatorrequirements') ?>">Executive Indicator Requirement</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Key Aspiration (2A)<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('addexecutivekeyaspiration') ?>">Executive Key Aspiration</a></li>
					</ul>
					</li>
			</ul>
			</li>
			<li><a><i class=""></i>RUB Vision and Mission<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('viewfiveyearplan') ?>">View Vision and Mission</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Planning Reports<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('planningreports') ?>">Current FYP APA</a></li>
			</ul>
			</li>
		</ul>
	</li>
	<li><a><i class="fa fa-database"></i>Property and Inventory<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>Goods Requisition<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('apply-goods-requisition') ?>">Apply Requisition</a></li>
					<li><a href="<?php echo $this->url('requisition-approval-list') ?>">Requisition Approval</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Goods Transaction<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('emp-goods-list') ?>">My Goods List</a></li>
			</ul>
			</li>
		</ul>
	</li>
	<li><a><i class="fa fa-user"></i>Counseling Service<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a href="<?php echo $this->url('counselingappointment') ?>">Seek Appointment</a></li>
			<li><a href="<?php echo $this->url('recommendcounseling') ?>">Recommend for Counseling</a></li>
			<li><a href="<?php echo $this->url('listcounselingrecord') ?>">View Records</a></li>
		</ul>
	</li>
	<li><a><i class="fa fa-user"></i>Job Portal<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a href="<?php echo $this->url('addapplicantmarks') ?>">Add Marks Detail</a></li>
			<li><a href="<?php echo $this->url('listvacancy') ?>">Apply For Vacancy</a></li>
		</ul>
	</li>
	<li><a><i class="fa fa-users"></i>Alumni<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a href="<?php echo $this->url('alumninewregistration') ?>">Register Previous Alumni</a></li>
			<li><a href="<?php echo $this->url('alumnimemberlist') ?>">Alumni Member List</a></li>
			<li><a href="<?php echo $this->url('addalumnicontributiondetail') ?>">Add Alumni Contribution</a></li>
			<li><a href="<?php echo $this->url('createalumnievent') ?>">Create Alumni Event</a></li>
			<li><a href="<?php echo $this->url('createalumniresource') ?>">Create Alumni Resources</a></li>
			<li><a href="<?php echo $this->url('createalumnienquiry') ?>">Alumni Enquiry</a></li>
			<li><a href="<?php echo $this->url('viewalumnienquirylist') ?>">View Alumni Enquiry List</a></li>
			<li><a href="<?php echo $this->url('createalumnifaqs') ?>">Add Alumni FAQs</a></li>
			<li><a href="<?php echo $this->url('viewalumnifaqslist') ?>">View Alumni FAQs List</a></li>
			<li><a href="<?php echo $this->url('addalumnisubscriptiondetail') ?>">Add Alumni Subscription</a></li>
			<li><a href="<?php echo $this->url('addalumnisubscription') ?>">Add Alumni Subscription Details</a></li>
			<li><a href="<?php echo $this->url('alumnisubscriptionlist') ?>">Alumni Subscription List</a></li>
			<li><a href="<?php echo $this->url('viewalumniresourcelist') ?>">View Alumni Resource List</a></li>
			<li><a href="<?php echo $this->url('alumnisubscriberlist') ?>">Alumni Subscriber List</a></li>
		</ul>
	</li>
</ul>
</div>
</div>
