<?php
 $title = 'Feedback Questions for Different Nominees';
 $this->headTitle($title);
?>

 <div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
            
                <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                     <div class="clearfix"></div>
                    </div>
                    <br/>
                     <br/>
                	<!-- Start of Tab-->
                    <div class="" role="tabpanel" data-example-id="togglable-tabs">
                      <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                        <li role="presentation" class="active"><a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">Peer Feedback Questions</a>
                        </li>
                        <li role="presentation" class=""><a href="#tab_content2" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false">Subordinate Feedback Questions</a>
                        </li>
                        <li role="presentation" class=""><a href="#tab_content3" role="tab" id="profile-tab2" data-toggle="tab" aria-expanded="false">Beneficiary Feedback Questions</a>
                        </li>
                        <li role="presentation" class=""><a href="#tab_content4" role="tab" id="profile-tab3" data-toggle="tab" aria-expanded="false">Student Feedback Questions</a>
                        </li>
                      </ul>
                      <div id="myTabContent" class="tab-content">
                        <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab">
                            <br/>
                                <!-- Adding Feedback Questions-->
                                <div class="col-md-12 col-xs-12">
                                  <div class="x_panel">
                                    <div class="x_title">
                                      <h2><?php echo $this->escapeHtml("Add Peer Feedback Question")?></h2>
                                        <ul class="nav navbar-right panel_toolbox">
                                          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                          </li>
                                    
                                        </ul>
                                     <div class="clearfix"></div>
                                  
                                    </div>
                                       
                                    <div class="x_content">
                                      <br />
                                       <?php
                                        // Opening of the form tag
										$peerForm->setAttribute('action', $this->url('addpeerquestions', array('action' => 'addPeerQuestions')));
										$peerForm->prepare();
										echo $this->form()->openTag($peerForm);
										$peer = $peerForm->get('feedbackquestions');
										echo $this->formHidden($peer->get('id'));
                                      ?>
                                    
                                      <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12">New Peer Feedback Question<span class="required">*</span></label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                          <?php  echo $this->formRow($peer->get('questions')); ?>
                                        </div>
                                      </div>
                                     
                                     <div class="row">
                                        <div class="ln_solid"></div>
                                        <div class="form-group">
                                            <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                                              <?php
                                               echo $this->formHidden($peerForm->get('csrf'));
                                               echo $this->formSubmit($peer->get('submit')); 
                                               echo $this->form()->closeTag(); 
                                            ?>
                                        </div>
                                    </div>
                                      
                                  </div>
                                </div>
                               </div>     
                                      
                                  
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                  <div class="x_panel">
                                    <div class="x_title">
                                      <h2><?php echo $this->escapeHtml("Peer Feedback Questions"); ?></h2>
                                      <ul class="nav navbar-right panel_toolbox">
                                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                        </li>
                                      </ul>
                                      <div class="clearfix"></div>
                                    </div>
                    
                                    <div class="x_content">
                                      <table class="table   table-striped responsive-utilities jambo_table bulk_action table-bordered">
                                        <thead>
                                          <tr class="headings">
                                            </th>
                                             <th class="column-title">Sl.No.</th>
                                             <th class="column-title">Feedback Question</th>
                                             <th class="column-title">Action</th>
                                          </tr>
                                        </thead>
                    
                                        <tbody>
                                          <?php
                                          $i=1;  foreach($this->peerQuestions as $pQ): ?>
                                          <tr class="even pointer">
                                            <td class=" "><?php echo $i++;?></td>
                                            <td class=" "><?php echo $pQ['questions'];?></td>
                                            <td class=" "><a href="<?php echo $this->url('editpeerquestions', array('id' => $pQ['id']));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a></td>
                                          </tr>
                                          <?php endforeach; ?>
                                        </tbody>
                                      </table>
                                    </div>
                                  </div>
                                </div>
                            
                           		<!-- End of Feedback Questions-->
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="tab_content2" aria-labelledby="profile-tab">
                                <br/>
                                <!-- Adding Feedback Questions-->
                                <div class="col-md-12 col-xs-12">
                                  <div class="x_panel">
                                    <div class="x_title">
                                      <h2><?php echo $this->escapeHtml("Add Subordinate Feedback Question")?></h2>
                                        <ul class="nav navbar-right panel_toolbox">
                                          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                          </li>
                                    
                                        </ul>
                                     <div class="clearfix"></div>
                                  
                                    </div>
                                       
                                    <div class="x_content">
                                      <br />
                                       <?php
                                        // Opening of the form tag
										$subordinateForm->setAttribute('action', $this->url('addsubordinatequestions', array('action' => 'addSubordinateQuestions')));
										$subordinateForm->prepare();
										echo $this->form()->openTag($subordinateForm);
										$subordinate = $subordinateForm->get('feedbackquestions');
										echo $this->formHidden($subordinate->get('id'));
                                      ?>
                                    
                                      <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12">New Subordinate Feedback Question<span class="required">*</span></label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                          <?php  echo $this->formRow($subordinate->get('questions')); ?>
                                        </div>
                                      </div>
                                     
                                     <div class="row">
                                        <div class="ln_solid"></div>
                                        <div class="form-group">
                                            <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                                              <?php
                                               echo $this->formHidden($subordinateForm->get('csrf'));
                                               echo $this->formSubmit($subordinate->get('submit')); 
                                               echo $this->form()->closeTag(); 
                                            ?>
                                        </div>
                                    </div>
                                      
                                  </div>
                                </div>
                               </div>     
                                      
                                  
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                  <div class="x_panel">
                                    <div class="x_title">
                                      <h2><?php echo $this->escapeHtml("Subordinate Feedback Questions"); ?></h2>
                                      <ul class="nav navbar-right panel_toolbox">
                                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                        </li>
                                      </ul>
                                      <div class="clearfix"></div>
                                    </div>
                    
                                    <div class="x_content">
                                      <table class="table   table-striped responsive-utilities jambo_table bulk_action table-bordered">
                                        <thead>
                                          <tr class="headings">
                                            </th>
                                             <th class="column-title">Sl.No.</th>
                                             <th class="column-title">Feedback Question</th>
                                             <th class="column-title">Action</th>
                                          </tr>
                                        </thead>
                    
                                        <tbody>
                                          <?php
                                          $i=1;  foreach($this->subordinateQuestions as $sub): ?>
                                          <tr class="even pointer">
                                            <td class=" "><?php echo $i++;?></td>
                                            <td class=" "><?php echo $sub['questions'];?></td>
                                            <td class=" "><a href="<?php echo $this->url('editsubordinatequestions', array('id' => $sub['id']));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a></td>
                                          </tr>
                                          <?php endforeach; ?>
                                        </tbody>
                                      </table>
                                    </div>
                                  </div>
                                </div>
                            
                            	<!-- End of Feedback Questions-->
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="tab_content3" aria-labelledby="profile-tab">
                            <br/>
                            <!-- Adding Feedback Questions-->
                            <div class="col-md-12 col-xs-12">
                                  <div class="x_panel">
                                    <div class="x_title">
                                      <h2><?php echo $this->escapeHtml("Add Beneficiary Feedback Question")?></h2>
                                        <ul class="nav navbar-right panel_toolbox">
                                          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                          </li>
                                    
                                        </ul>
                                     <div class="clearfix"></div>
                                  
                                    </div>
                                       
                                    <div class="x_content">
                                      <br />
                                       <?php
                                        // Opening of the form tag
										$beneficiaryForm->setAttribute('action', $this->url('addbeneficiaryquestions', array('action' => 'addBeneficiaryQuestions')));
										$beneficiaryForm->prepare();
										echo $this->form()->openTag($beneficiaryForm);
										$beneficiary = $beneficiaryForm->get('feedbackquestions');
										echo $this->formHidden($beneficiary->get('id'));
                                      ?>
                                    
                                      <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12">New Beneficiary Feedback Question<span class="required">*</span></label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                          <?php  echo $this->formRow($beneficiary->get('questions')); ?>
                                        </div>
                                      </div>
                                     
                                     <div class="row">
                                        <div class="ln_solid"></div>
                                        <div class="form-group">
                                            <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                                              <?php
                                               echo $this->formHidden($beneficiaryForm->get('csrf'));
                                               echo $this->formSubmit($beneficiary->get('submit')); 
                                               echo $this->form()->closeTag(); 
                                            ?>
                                        </div>
                                    </div>
                                      
                                  </div>
                                </div>
                               </div>     
                                      
                                  
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                  <div class="x_panel">
                                    <div class="x_title">
                                      <h2><?php echo $this->escapeHtml("Beneficiary Feedback Questions"); ?></h2>
                                      <ul class="nav navbar-right panel_toolbox">
                                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                        </li>
                                      </ul>
                                      <div class="clearfix"></div>
                                    </div>
                    
                                    <div class="x_content">
                                      <table class="table   table-striped responsive-utilities jambo_table bulk_action table-bordered">
                                        <thead>
                                          <tr class="headings">
                                            </th>
                                             <th class="column-title">Sl.No.</th>
                                             <th class="column-title">Feedback Question</th>
                                             <th class="column-title">Action</th>
                                          </tr>
                                        </thead>
                    
                                        <tbody>
                                          <?php
                                          $i=1;  foreach($this->beneficiaryQuestions as $ben): ?>
                                          <tr class="even pointer">
                                            <td class=" "><?php echo $i++;?></td>
                                            <td class=" "><?php echo $ben['questions'];?></td>
                                            <td class=" "><a href="<?php echo $this->url('editbeneficiaryquestions', array('id' => $ben['id']));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a></td>
                                          </tr>
                                          <?php endforeach; ?>
                                        </tbody>
                                      </table>
                                    </div>
                                  </div>
                                </div>
                            
                            <!-- End of Feedback Questions-->
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="tab_content4" aria-labelledby="profile-tab">
                            <br/>
                            <!-- Adding Feedback Questions-->
                            <div class="col-md-12 col-xs-12">
                                  <div class="x_panel">
                                    <div class="x_title">
                                      <h2><?php echo $this->escapeHtml("Student Feedback Question")?></h2>
                                        <ul class="nav navbar-right panel_toolbox">
                                          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                          </li>
                                    
                                        </ul>
                                     <div class="clearfix"></div>
                                  
                                    </div>
                                       
                                    <div class="x_content">
                                      <br />
                                       <?php
                                        // Opening of the form tag
										$studentForm->setAttribute('action', $this->url('addstudentquestions', array('action' => 'addStudentQuestions')));
										$studentForm->prepare();
										echo $this->form()->openTag($studentForm);
										$student = $studentForm->get('feedbackquestions');
										echo $this->formHidden($student->get('id'));
                                      ?>
                                    
                                      <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12">New Student Feedback Question:<span class="required">*</span></label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                          <?php  echo $this->formRow($student->get('questions')); ?>
                                        </div>
                                      </div>
                                     
                                     <div class="row">
                                        <div class="ln_solid"></div>
                                        <div class="form-group">
                                        	<label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                                              <?php
                                               echo $this->formHidden($studentForm->get('csrf'));
                                               echo $this->formSubmit($student->get('submit')); 
                                               echo $this->form()->closeTag(); 
                                            ?>
                                        </div>
                                    </div>
                                      
                                  </div>
                                </div>
                               </div>     
                                      
                                  
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                  <div class="x_panel">
                                    <div class="x_title">
                                      <h2><?php echo $this->escapeHtml("Student Feedback Questions"); ?></h2>
                                      <ul class="nav navbar-right panel_toolbox">
                                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                        </li>
                                      </ul>
                                      <div class="clearfix"></div>
                                    </div>
                    
                                    <div class="x_content">
                                      <table class="table   table-striped responsive-utilities jambo_table bulk_action table-bordered">
                                        <thead>
                                          <tr class="headings">
                                            </th>
                                             <th class="column-title">Sl.No.</th>
                                             <th class="column-title">Feedback Question</th>
                                             <th class="column-title">Action</th>
                                          </tr>
                                        </thead>
                    
                                        <tbody>
                                          <?php
                                          $i=1;  foreach($this->studentQuestions as $stdQ): ?>
                                          <tr class="even pointer">
                                            <td class=" "><?php echo $i++;?></td>
                                            <td class=" "><?php echo $stdQ['questions'];?></td>
                                            <td class=" "><a href="<?php echo $this->url('editstudentquestions', array('id' => $stdQ['id']));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a></td>
                                          </tr>
                                          <?php endforeach; ?>
                                        </tbody>
                                      </table>
                                    </div>
                                  </div>
                                </div>
                            
                            <!-- End of Feedback Questions-->
                        </div>
                        
                      </div>
                    </div>
                    <!-- End of Tabs-->
                     
                     
                  </div>
                </div>
              </div>
     </div>
