<html lang="en">
<head>

<!-- Le styles -->
<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->appendStylesheet($this->basePath('login/bower_components/bootstrap/dist/css/bootstrap.min.css'))
        ->appendStylesheet($this->basePath('login/bower_components/font-awesome/css/font-awesome.min.css'))
        ->appendStylesheet($this->basePath('login/bower_components/Ionicons/css/ionicons.min.css'))
        ->appendStylesheet($this->basePath('dist/css/AdminLTE.min.css'))
        ->appendStylesheet($this->basePath('login/plugins/iCheck/square/blue.css')) 


?>

</head>                    
    
<body>
  <div class="container body">
    <div class="main_container">
      <!-- top navigation -->
      <?php // echo $this->partial('layout/top_navigation'); ?>
      <!-- /top navigation -->
      <!-- page content -->
    <?php echo $this->content; ?>
      <!-- /page content -->
    </div>
  </div>

  <div align="center" class="footer">
    <div class="footer-inner">
      <div class="footer-content">
        <span class="bigger-120">
          <span class="blue bolder">Copyright</span>
           &copy; 2017-<?php echo date('Y'); ?>
          <span class="blue bolder"> Royal University of Bhutan. All Rights Reserved.</span> 
        </span>
        &nbsp; &nbsp;
      </div>
    </div>
  </div>

<!-- Scripts -->
<?php echo $this->headScript()
    ->appendFile($this->basePath('js/jquery/dist/jquery.min.js'))
    ->appendFile($this->basePath('js/bootstrap/dist/js/bootstrap.min.js'))
    ->appendFile($this->basePath('js/fastclick/lib/fastclick.js'))
    ->appendFile($this->basePath('js/nprogress/nprogress.js'))
    ->appendFile($this->basePath('js/bootstrap-progressbar/bootstrap-progressbar.min.js'))
    ->appendFile($this->basePath('js/iCheck/icheck.min.js'))
    ->appendFile($this->basePath('js/moment/min/moment.min.js'))
    ->appendFile($this->basePath('js/bootstrap-daterangepicker/daterangepicker.js'))
    ->appendFile($this->basePath('js/build/js/custom.min.js'))
    ->appendFile($this->basePath('js/user/layout.js'))
    ->appendFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
    ->appendFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
; 

echo $this->inlineScript()->prependFile($this->basePath('js/jQuery-Smart-Wizard/js/jquery.smartWizard.js'));

?>

<!--<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' // optional
    });
  });
</script> -->

<!-- Flot -->
    <script type="text/javascript">
      $(document).ready(function() {
        var data1 = [
          [gd(2012, 1, 1), 17],
          [gd(2012, 1, 2), 74],
          [gd(2012, 1, 3), 6],
          [gd(2012, 1, 4), 39],
          [gd(2012, 1, 5), 20],
          [gd(2012, 1, 6), 85],
          [gd(2012, 1, 7), 7]
        ];

        var data2 = [
          [gd(2012, 1, 1), 82],
          [gd(2012, 1, 2), 23],
          [gd(2012, 1, 3), 66],
          [gd(2012, 1, 4), 9],
          [gd(2012, 1, 5), 119],
          [gd(2012, 1, 6), 6],
          [gd(2012, 1, 7), 9]
        ];
        $("#canvas_dahs").length && $.plot($("#canvas_dahs"), [
          data1, data2
        ], {
          series: {
            lines: {
              show: false,
              fill: true
            },
            splines: {
              show: true,
              tension: 0.4,
              lineWidth: 1,
              fill: 0.4
            },
            points: {
              radius: 0,
              show: true
            },
            shadowSize: 2
          },
          grid: {
            verticalLines: true,
            hoverable: true,
            clickable: true,
            tickColor: "#d5d5d5",
            borderWidth: 1,
            color: '#fff'
          },
          colors: ["rgba(38, 185, 154, 0.38)", "rgba(3, 88, 106, 0.38)"],
          xaxis: {
            tickColor: "rgba(51, 51, 51, 0.06)",
            mode: "time",
            tickSize: [1, "day"],
            //tickLength: 10,
            axisLabel: "Date",
            axisLabelUseCanvas: true,
            axisLabelFontSizePixels: 12,
            axisLabelFontFamily: 'Verdana, Arial',
            axisLabelPadding: 10
          },
          yaxis: {
            ticks: 8,
            tickColor: "rgba(51, 51, 51, 0.06)",
          },
          tooltip: false
        });

        function gd(year, month, day) {
          return new Date(year, month - 1, day).getTime();
        }
      });
    </script>
    <!-- /Flot -->

    <!-- JQVMap -->
    <script type="text/javascript">
      $(document).ready(function(){
        $('#world-map-gdp').vectorMap({
            map: 'world_en',
            backgroundColor: null,
            color: '#ffffff',
            hoverOpacity: 0.7,
            selectedColor: '#666666',
            enableZoom: true,
            showTooltip: true,
            values: sample_data,
            scaleColors: ['#E6F2F0', '#149B7E'],
            normalizeFunction: 'polynomial'
        });
      });
    </script>
    <!-- /JQVMap -->

    <!-- Skycons -->
    <script type="text/javascript">
      $(document).ready(function() {
        var icons = new Skycons({
            "color": "#73879C"
          }),
          list = [
            "clear-day", "clear-night", "partly-cloudy-day",
            "partly-cloudy-night", "cloudy", "rain", "sleet", "snow", "wind",
            "fog"
          ],
          i;

        for (i = list.length; i--;)
          icons.set(list[i], list[i]);

        icons.play();
      });
    </script>
    <!-- /Skycons -->

    <!-- Doughnut Chart -->
    <script type="text/javascript">
      $(document).ready(function(){
        var options = {
          legend: false,
          responsive: false
        };

        new Chart(document.getElementById("canvas1"), {
          type: 'doughnut',
          tooltipFillColor: "rgba(51, 51, 51, 0.55)",
          data: {
            labels: [
              "Symbian",
              "Blackberry",
              "Other",
              "Android",
              "IOS"
            ],
            datasets: [{
              data: [15, 20, 30, 10, 30],
              backgroundColor: [
                "#BDC3C7",
                "#9B59B6",
                "#E74C3C",
                "#26B99A",
                "#3498DB"
              ],
              hoverBackgroundColor: [
                "#CFD4D8",
                "#B370CF",
                "#E95E4F",
                "#36CAAB",
                "#49A9EA"
              ]
            }]
          },
          options: options
        });
      });
    </script>
    <!-- /Doughnut Chart -->
    
    <!-- gauge.js -->
    <script type="text/javascript">
      var opts = {
          lines: 12,
          angle: 0,
          lineWidth: 0.4,
          pointer: {
              length: 0.75,
              strokeWidth: 0.042,
              color: '#1D212A'
          },
          limitMax: 'false',
          colorStart: '#1ABC9C',
          colorStop: '#1ABC9C',
          strokeColor: '#F0F3F3',
          generateGradient: true
      };
      var target = document.getElementById('foo'),
          gauge = new Gauge(target).setOptions(opts);

      gauge.maxValue = 6000;
      gauge.animationSpeed = 32;
      gauge.set(3200);
      gauge.setTextField(document.getElementById("gauge-text"));
    </script>
    <!-- /gauge.js -->
    
  </body>
</html>
