<?php
 // module/EmployeeDetail/view/employee-detail/employee-detail/emppersonaldetail.phtml:

 $title = 'Add Guest House Room';
 $this->headTitle($title);
 ?>
<div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                  </div>
                    
                  <div class="x_content">
                    <br/>
                   
                        
                        
                        <?php
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        
                        echo $this->formHidden($form->get('id'));
                        ?>
                        <div class="row">
                            
                          <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Place/College<span class="required">*</span>
                        </label>
                              <div class="col-md-4 col-sm-4 col-xs-12">
                        <?php
                        echo $this->formRow($form->get('college_name'));
                        ?>
                          </div>
                              <label class="control-label col-md-2 col-sm-2 col-xs-12">Guest House<span class="required">*</span>
                        </label>
                              <div class="col-md-4 col-sm-4 col-xs-12">
                        <?php
                        echo $this->formRow($form->get('guest_house_name'));
                        ?>
                          </div>
                        </div>  
                        </div>  
                    
                     <div class="row">
                            
                          <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Floor Name<span class="required">*</span>
                        </label>
                              <div class="col-md-4 col-sm-4 col-xs-12">
                        <?php
                        echo $this->formRow($form->get('guest_house_floor_no'));
                        ?>
                          </div>
                              <label class="control-label col-md-2 col-sm-2 col-xs-12">Room No<span class="required">*</span>
                        </label>
                              <div class="col-md-4 col-sm-4 col-xs-12">
                        <?php
                        echo $this->formRow($form->get('guest_house_room_no'));
                        ?>
                          </div>
                        </div>  
                        </div>  
                    
                    <div class="row">
                            
                          <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Room Type<span class="required">*</span>
                        </label>
                              <div class="col-md-4 col-sm-4 col-xs-12">
                        <?php
                        echo $this->formRow($form->get('guest_house_room_type'));
                        ?>
                          </div>
                              <label class="control-label col-md-2 col-sm-2 col-xs-12">Amount<span class="required">*</span>
                        </label>
                              <div class="col-md-4 col-sm-4 col-xs-12">
                        <?php
                        echo $this->formRow($form->get('guest_house_room_charge'));
                        ?>
                          </div>
                        </div>  
                        </div> <br/> 
                     
                    <div class="ln_solid"></div>
                      <div class="form-group">
                        <div class="col-md-2 col-sm-2 col-xs-12">
                          <button type="submit" class="btn btn-primary"><i class="fa fa-plus">Add</i></button>
                          
                        </div>
                      </div>
                    
                       
                    
                  
                        <div class="table-responsive">
                      <table class="table table-striped jambo_table bulk_action"> 
                         <div class="form-group">      
                      </div> 
                        <thead>
                          <tr class="headings">
                           <!--<th>
                              <input type="checkbox" id="check-all" class="flat">
                            </th>-->
                              
                            <th class="column-title">Room No </th>
                            <th class="column-title">Room Type </th>
                            <th class="column-title">Room Amount </th>
                            
                            <th class="column-title no-link last"><span class="nobr">Action</span>
                            </th>
                            <th class="bulk-actions" colspan="7">
                              <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                            </th>
                          </tr>
                        </thead>
                        
                        <tbody>
                     
                         
                         
                        </tbody>
                          </table>
                      
                       <div class="ln_solid"></div>     
                    <?php
                        echo $this->formSubmit($form->get('submit')); 
                        echo $this->formSubmit($form->get('reset')); 
                      ?>
                   
                    </div>
                    
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                    </div>
                
          </div></div></div></div>
            
         
              
       
                