<?php
 $title = 'Personal Details';
 $this->headTitle($title);
?>

<?php 
if(!empty($alumni_id)){
  $alumniDetails = array();
  foreach ($this->details as $det): {
	$alumniDetails['first_name'] = $det['first_name'];
	$alumniDetails['middle_name'] = $det['middle_name'];
	$alumniDetails['last_name'] = $det['last_name'];
	$alumniDetails['student_id'] = $det['student_id'];
	$alumniDetails['programme_name'] = $det['programme_name'];
	$alumniDetails['cid'] = $det['cid'];
	$alumniDetails['current_job_title'] = $det['current_job_title'];
	$alumniDetails['current_job_organisation'] = $det['current_job_organisation'];
	//$img_location = $det['profile_picture'];
  }
?>
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>User Profile</h3>
      </div>
    </div>        
          <div class="clearfix"></div>

          <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                   <h2><?php echo $this->escapeHtml($title); ?></h2>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">

                  <div class="col-md-3 col-sm-3 col-xs-12 profile_left">

                    <div class="profile_img">

                      <!-- end of image cropping -->
                      <div id="crop-avatar">
                        <!-- Current avatar -->
                        <?php if(!empty($img_location)){ ?>
                        <img class="img-responsive avatar-view" src="<?php echo '../../'.$img_location; ?>" alt="Avatar" title="Change the avatar">
                        <?php } else {?>
                        <img class="img-responsive avatar-view" src="../img/logo.png" alt="Avatar" title="Change the avatar">
                        <?php } ?>
                
                        <!-- Cropping modal -->
                        <div class="modal fade" id="avatar-modal" aria-hidden="true" aria-labelledby="avatar-modal-label" role="dialog" tabindex="-1">
                          <div class="modal-dialog modal-lg">
                            <div class="modal-content">
                              <form class="avatar-form" action="crop.php" enctype="multipart/form-data" method="post">
                                <div class="modal-header">
                                  <button class="close" data-dismiss="modal" type="button">&times;</button>
                                  <h4 class="modal-title" id="avatar-modal-label">Change Avatar</h4>
                                </div>
                                <div class="modal-body">
                                  <div class="avatar-body">

                                    <!-- Upload image and data -->
                                    <div class="avatar-upload">
                                      <input class="avatar-src" name="avatar_src" type="hidden">
                                      <input class="avatar-data" name="avatar_data" type="hidden">
                                      <label for="avatarInput">Local upload</label>
                                      <input class="avatar-input" id="avatarInput" name="avatar_file" type="file">
                                    </div>

                                    <!-- Crop and preview -->
                                    <div class="row">
                                      <div class="col-md-9">
                                        <div class="avatar-wrapper"></div>
                                      </div>
                                      <div class="col-md-3">
                                        <div class="avatar-preview preview-lg"></div>
                                        <div class="avatar-preview preview-md"></div>
                                        <div class="avatar-preview preview-sm"></div>
                                      </div>
                                    </div>

                                    <div class="row avatar-btns">
                                      <div class="col-md-9">
                                        <div class="btn-group">
                                          <button class="btn btn-primary" data-method="rotate" data-option="-90" type="button" title="Rotate -90 degrees">Rotate Left</button>
                                          <button class="btn btn-primary" data-method="rotate" data-option="-15" type="button">-15deg</button>
                                          <button class="btn btn-primary" data-method="rotate" data-option="-30" type="button">-30deg</button>
                                          <button class="btn btn-primary" data-method="rotate" data-option="-45" type="button">-45deg</button>
                                        </div>
                                        <div class="btn-group">
                                          <button class="btn btn-primary" data-method="rotate" data-option="90" type="button" title="Rotate 90 degrees">Rotate Right</button>
                                          <button class="btn btn-primary" data-method="rotate" data-option="15" type="button">15deg</button>
                                          <button class="btn btn-primary" data-method="rotate" data-option="30" type="button">30deg</button>
                                          <button class="btn btn-primary" data-method="rotate" data-option="45" type="button">45deg</button>
                                        </div>
                                      </div>
                                      <div class="col-md-3">
                                        <button class="btn btn-primary btn-block avatar-save" type="submit">Done</button>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                                <!-- <div class="modal-footer">
                                                  <button class="btn btn-default" data-dismiss="modal" type="button">Close</button>
                                                </div> -->
                              </form>
                            </div>
                          </div>
                        </div>
                        <!-- /.modal -->

                        <!-- Loading state -->
                        <div class="loading" aria-label="Loading" role="img" tabindex="-1"></div>
                      </div>
                      <!-- end of image cropping -->

                    </div>

                      <h4><?php echo $alumniDetails['first_name'].' ';
                                echo $alumniDetails['middle_name'].' ';
                                echo $alumniDetails['last_name'];?></h4>

                      <ul class="list-unstyled user_data">
                      <li><i class="">Job Title: </i> 
					  <?php
						if(!empty($alumniDetails['current_job_title'])){
							echo $alumniDetails['current_job_title']; 
						} else {
							echo "NA";
						}
					  
					  ?>
					  </li>
                      <li><i class="">Organisation: </i> 
					  <?php 
					  if(!empty($alumniDetails['current_job_organisation'])){
						  echo $alumniDetails['current_job_organisation']; 
					  } else {
						  echo "NA";
					  }
					  
					  ?>
					  </li>
                      <!--<li><i class="">Semester: </i> <?php echo $alumniDetails['semester'].' Semester'; ?> </li>
                      <li><i class="">Year: </i> <?php echo $alumniDetails['programme_year_id'].' Year'; ?> </li>
                      <li><i class="">Organisation: </i> <?php echo $alumniDetails['organisation_name']; ?> </li>
                      <li><i class="">Academic Year: </i> <?php echo $alumniDetails['academic_year']; ?> </li> -->
                    </ul>

                    <?php endforeach; ?>
                     </div>
              <!-- Start for Staff to view student profile-->
                  <div class="col-md-9 col-sm-9 col-xs-12">

                    <div class="" role="tabpanel" data-example-id="togglable-tabs">
                    <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                      <li role="presentation" class="active"><a href="#tab_content1" id="profile-tab" role="tab" data-toggle="tab" aria-expanded="true"><i class="fa fa-signal"></i> Personal Details</a>
                      </li>
                       <li role="presentation" class=""><a href="#tab_content2" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false"><i class="fa fa-slideshare"></i> Current Details </a>
                      </li>
                    </ul>
                    <div id="myTabContent" class="tab-content">
                      <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="profile-tab">
                       <br/>  
                      <div class="x_panel">
                        <div class="x_content">                        
                   <!-- start accordion -->
                    <div class="accordion" id="accordion1" role="tablist" aria-multiselectable="true">
                      <div class="panel">
                        <a class="panel-heading" role="tab" id="headingOne1" data-toggle="collapse" data-parent="#accordion1" href="#collapseOne1" aria-expanded="true" aria-controls="collapseOne1">
                          <h4 class="blue panel-title"><i class="fa fa-ellipsis-v"></i> Personal Data</h4>
                        </a>
                        <div id="collapseOne1" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne1">
                          <div class="panel-body">
                            <div class="row">
                              <div class="form-group">
                                <table style="width: 100%">
                                  <?php
                                $personalDetail = array();
                                foreach ($this->alumniPersonalDetails as $pdetails): {
                                   $personalDetail['date_of_birth'] = $pdetails['date_of_birth'];
                                   $personalDetail['gender'] = $pdetails['gender'];
                                   $personalDetail['cid'] = $pdetails['cid'];
                                 } 
                                ?>
                                  <tr>
                                    <th>Date of Birth:</th>
                                    <td><?php echo $personalDetail['date_of_birth']; ?></td>
                                    <th>Gender:</th>
                                    <td><?php echo $personalDetail['gender']; ?></td>
                                  </tr>
                                  <tr>
                                    <th>CID:</th>
                                    <td><?php echo $personalDetail['cid']; ?></td>
                                  </tr>
                                  <?php endforeach; ?>
                                 </table>    
                               </div>                                                         
                            </div> <!-- end of row-->
                          </div>
                        </div>
                      </div>
                      <!-- Second -->
                      <div class="panel">
                        <a class="panel-heading collapsed" role="tab" id="headingTwo1" data-toggle="collapse" data-parent="#accordion1" href="#collapseTwo1" aria-expanded="false" aria-controls="collapseTwo1">
                          <h4 class="blue panel-title"><i class="fa fa-ellipsis-v"></i> Permanent Address</h4>
                        </a>
                        <div id="collapseTwo1" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo1">
                          <div class="panel-body">
                            <div class="row">
                                <div class="form-group">
                                    <table style="width: 100%">
                                      <?php
									  if(!empty($this->alumniPermanentAddress)){
                                      $alumniPermanentAdd = array();
                                      foreach ($this->alumniPermanentAddress as $address): 
                                        $alumniPermanentAdd = $address;                                       
                                      ?>
                                      <tr>
                                        <th>Village:</th>
                                        <td><?php echo $alumniPermanentAdd['village_name']; ?></td>
                                        <th>Gewog:</th>
                                        <td><?php echo $alumniPermanentAdd['gewog_name']; ?></td>
                                      </tr>
                                      <tr>
                                        <th>Dzongkhag:</th>
                                        <td><?php echo $alumniPermanentAdd['dzongkhag_name']; ?></td>
                                      </tr>
                                    <?php endforeach; 
									  } else {
									?>
									  <tr>
                                        <th>Village:</th>
                                        <td><?php echo "NA"; ?></td>
                                        <th>Gewog:</th>
                                        <td><?php echo "NA"; ?></td>
                                      </tr>
                                      <tr>
                                        <th>Country:</th>
                                        <td><?php echo "NA"; ?></td>
                                      </tr>
                                    <?php } ?>
                                    </table>
                                </div>
                            </div> <!-- end of row-->
                          </div>
                        </div>

                      </div>

                      <!-- Third panel-->
                      <div class="panel">
                        <a class="panel-heading collapsed" role="tab" id="headingThree1" data-toggle="collapse" data-parent="#accordion1" href="#collapseThree1" aria-expanded="false" aria-controls="collapseThree1">
                          <h4 class="blue panel-title"><i class="fa fa-ellipsis-v"></i> Contact Details</h4>
                        </a>
                        <div id="collapseThree1" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree1">
                          <div class="panel-body">
                            <div class="row">
                                <div class="form-group">
                                    <table style="width: 100%">
                                      <?php 
                                      $alumniContact = array();
                                      foreach ($this->alumniContactDetails as $contactDetails): {
                                        $alumniContact = $contactDetails;
                                      }
                                      ?>
                                      <tr>
                                        <th>Email:</th>
                                        <td><?php echo $alumniContact['email_address']; ?></td>
                                      </tr>
                                      <tr>
                                        <th>Contact No:</th>
                                        <td><?php echo $alumniContact['contact_no']; ?></td>
                                      </tr>
                                    <?php endforeach; ?>
                                    </table>
                                </div>
                            </div> <!-- end of row-->
                            <!-- end work experience -->
                          </div>
                        </div>
                      </div><!--End of third panel-->          
                    </div>
                    <!-- end of accordion -->
                </div>
              </div> 
            </div>
                        
                  
                  <div role="tabpanel" class="tab-pane fade" id="tab_content2" aria-labelledby="profile-tab">
                       <br/> 
                       <div class="x_panel"> 
             <div class="x_title">                  
                            <div class="clearfix"></div>
                                
                                <!-- start accordion -->
                    <div class="accordion" id="accordion2" role="tablist" aria-multiselectable="true">
                      <div class="panel">
                        <a class="panel-heading" role="tab" id="headingOne2" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne2" aria-expanded="true" aria-controls="collapseOne2">
                          <h4 class="blue panel-title"><i class="fa fa-ellipsis-v"></i> Current Employment Details</h4>
                        </a>
                        <div id="collapseOne2" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne2">
                          <div class="panel-body">
                              <div class="row">
                                <div class="form-group">
                                    <table style="width: 100%">
                                      <?php
									  if(!empty($this->alumniEmploymentDetails)){
                                      $employmentDetails = array();
                                      foreach ($this->alumniEmploymentDetails as $details): {
                                        $employmentDetails = $details;
                                      }
                                      ?>
                                      <tr>
                                        <th>Job Title:</th>
                                        <td><?php echo $employmentDetails['current_job_title']; ?></td>
										<th>Qualification:</th>
                                        <td><?php echo $employmentDetails['study_level']; ?></td>
                                      </tr>
                                      <tr>
                                        <th>Organisation:</th>
                                        <td><?php echo $employmentDetails['current_job_organisation']; ?></td>
                                      </tr>
									  <tr>
                                        <th>Address:</th>
                                        <td><?php echo $employmentDetails['present_address']; ?></td>
                                      </tr>
                                    <?php endforeach; 
									  } else {
									?>
									<tr>
                                        <th>Job Title:</th>
                                        <td><?php echo "NA"; ?></td>
										<th>Qualification:</th>
                                        <td><?php echo "NA"; ?></td>
                                      </tr>
                                      <tr>
                                        <th>Organisation:</th>
                                        <td><?php echo "NA"; ?></td>
                                      </tr>
									  <tr>
                                        <th>Address:</th>
                                        <td><?php echo "NA"; ?></td>
                                      </tr>
									  <?php } ?>
                                    </table>
                                </div>
                            </div> <!-- end of row-->                                
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>  
                </div>                           
                    </div> 
                   </div>
                 </div>
               </div>
             <!-- End of Staff View -->
           </div>
         </div>
       </div>
     </div>
   </div>
 </div>
<?php } else if(!empty($id)){
   $alumniDetails = array();
  foreach ($this->details as $det): {
	$alumniDetails['first_name'] = $det['first_name'];
	$alumniDetails['middle_name'] = $det['middle_name'];
	$alumniDetails['last_name'] = $det['last_name'];
	$alumniDetails['student_id'] = $det['student_id'];
	$alumniDetails['programme_name'] = $det['programme_name'];
	$alumniDetails['cid'] = $det['cid'];
	$alumniDetails['current_job_title'] = $det['current_job_title'];
	$alumniDetails['current_job_organisation'] = $det['current_job_organisation'];
	//$img_location = $det['profile_picture'];
  }
?>

      <div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>User Profile</h3>
      </div>
    </div>        
          <div class="clearfix"></div>

          <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                   <h2><?php echo $this->escapeHtml($title); ?></h2>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">

                  <div class="col-md-3 col-sm-3 col-xs-12 profile_left">

                    <div class="profile_img">

                      <!-- end of image cropping -->
                      <div id="crop-avatar">
                        <!-- Current avatar -->
                        <?php if(!empty($img_location)){ ?>
                        <img class="img-responsive avatar-view" src="<?php echo '../../'.$img_location; ?>" alt="Avatar" title="Change the avatar">
                        <?php } else {?>
                        <img class="img-responsive avatar-view" src="../img/logo.png" alt="Avatar" title="Change the avatar">
                        <?php } ?>
                
                        <!-- Cropping modal -->
                        <div class="modal fade" id="avatar-modal" aria-hidden="true" aria-labelledby="avatar-modal-label" role="dialog" tabindex="-1">
                          <div class="modal-dialog modal-lg">
                            <div class="modal-content">
                              <form class="avatar-form" action="crop.php" enctype="multipart/form-data" method="post">
                                <div class="modal-header">
                                  <button class="close" data-dismiss="modal" type="button">&times;</button>
                                  <h4 class="modal-title" id="avatar-modal-label">Change Avatar</h4>
                                </div>
                                <div class="modal-body">
                                  <div class="avatar-body">

                                    <!-- Upload image and data -->
                                    <div class="avatar-upload">
                                      <input class="avatar-src" name="avatar_src" type="hidden">
                                      <input class="avatar-data" name="avatar_data" type="hidden">
                                      <label for="avatarInput">Local upload</label>
                                      <input class="avatar-input" id="avatarInput" name="avatar_file" type="file">
                                    </div>

                                    <!-- Crop and preview -->
                                    <div class="row">
                                      <div class="col-md-9">
                                        <div class="avatar-wrapper"></div>
                                      </div>
                                      <div class="col-md-3">
                                        <div class="avatar-preview preview-lg"></div>
                                        <div class="avatar-preview preview-md"></div>
                                        <div class="avatar-preview preview-sm"></div>
                                      </div>
                                    </div>

                                    <div class="row avatar-btns">
                                      <div class="col-md-9">
                                        <div class="btn-group">
                                          <button class="btn btn-primary" data-method="rotate" data-option="-90" type="button" title="Rotate -90 degrees">Rotate Left</button>
                                          <button class="btn btn-primary" data-method="rotate" data-option="-15" type="button">-15deg</button>
                                          <button class="btn btn-primary" data-method="rotate" data-option="-30" type="button">-30deg</button>
                                          <button class="btn btn-primary" data-method="rotate" data-option="-45" type="button">-45deg</button>
                                        </div>
                                        <div class="btn-group">
                                          <button class="btn btn-primary" data-method="rotate" data-option="90" type="button" title="Rotate 90 degrees">Rotate Right</button>
                                          <button class="btn btn-primary" data-method="rotate" data-option="15" type="button">15deg</button>
                                          <button class="btn btn-primary" data-method="rotate" data-option="30" type="button">30deg</button>
                                          <button class="btn btn-primary" data-method="rotate" data-option="45" type="button">45deg</button>
                                        </div>
                                      </div>
                                      <div class="col-md-3">
                                        <button class="btn btn-primary btn-block avatar-save" type="submit">Done</button>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                                <!-- <div class="modal-footer">
                                                  <button class="btn btn-default" data-dismiss="modal" type="button">Close</button>
                                                </div> -->
                              </form>
                            </div>
                          </div>
                        </div>
                        <!-- /.modal -->

                        <!-- Loading state -->
                        <div class="loading" aria-label="Loading" role="img" tabindex="-1"></div>
                      </div>
                      <!-- end of image cropping -->

                    </div>

                      <h4><?php echo $alumniDetails['first_name'].' ';
                                echo $alumniDetails['middle_name'].' ';
                                echo $alumniDetails['last_name'];?></h4>

                      <ul class="list-unstyled user_data">
                      <li><i class="">Job Title: </i> 
					  <?php 
					  if(!empty($alumniDetails['current_job_title'])){
						  echo $alumniDetails['current_job_title'] ;
					  } else {
						  echo "NA";
					  }
					  
					  ?>
					  </li>
                      <li><i class="">Organisation: </i> 
					  <?php 
					  if(!empty($alumniDetails['current_job_organisation'])){
						  echo $alumniDetails['current_job_organisation']; 
					  } else {
						  echo "NA";
					  }
					  
					  ?> 
					  </li>
                      <!--<li><i class="">Semester: </i> <?php echo $alumniDetails['semester'].' Semester'; ?> </li>
                      <li><i class="">Year: </i> <?php echo $alumniDetails['programme_year_id'].' Year'; ?> </li>
                      <li><i class="">Organisation: </i> <?php echo $alumniDetails['organisation_name']; ?> </li>
                      <li><i class="">Academic Year: </i> <?php echo $alumniDetails['academic_year']; ?> </li> -->
                    </ul>

                    <?php endforeach; ?>
                     </div>
              <!-- Start for Staff to view student profile-->
                  <div class="col-md-9 col-sm-9 col-xs-12">

                    <div class="" role="tabpanel" data-example-id="togglable-tabs">
                    <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                      <li role="presentation" class="active"><a href="#tab_content1" id="profile-tab" role="tab" data-toggle="tab" aria-expanded="true"><i class="fa fa-signal"></i> Personal Details</a>
                      </li>
                       <li role="presentation" class=""><a href="#tab_content2" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false"><i class="fa fa-slideshare"></i> Current Details </a>
                      </li>
                    </ul>
                    <div id="myTabContent" class="tab-content">
                      <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="profile-tab">
                       <br/>  
                      <div class="x_panel">
                        <div class="x_content">                        
                   <!-- start accordion -->
                    <div class="accordion" id="accordion1" role="tablist" aria-multiselectable="true">
                      <div class="panel">
                        <a class="panel-heading" role="tab" id="headingOne1" data-toggle="collapse" data-parent="#accordion1" href="#collapseOne1" aria-expanded="true" aria-controls="collapseOne1">
                          <h4 class="blue panel-title"><i class="fa fa-ellipsis-v"></i> Personal Data</h4>
                        </a>
                        <div id="collapseOne1" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne1">
                          <div class="panel-body">
                            <div class="row">
                              <div class="form-group">
                                <table style="width: 100%">
                                  <?php
                                $personalDetail = array();
                                foreach ($this->alumniPersonalDetails as $pdetails): {
                                   $personalDetail['date_of_birth'] = $pdetails['date_of_birth'];
                                   $personalDetail['gender'] = $pdetails['gender'];
                                   $personalDetail['cid'] = $pdetails['cid'];
                                 } 
                                ?>
                                  <tr>
                                    <th>Date of Birth:</th>
                                    <td><?php echo $personalDetail['date_of_birth']; ?></td>
                                    <th>Gender:</th>
                                    <td><?php echo $personalDetail['gender']; ?></td>
                                  </tr>
                                  <tr>
                                    <th>CID:</th>
                                    <td><?php echo $personalDetail['cid']; ?></td>
                                  </tr>
                                  <?php endforeach; ?>
                                 </table>    
                               </div>                                                         
                            </div> <!-- end of row-->
                          </div>
                        </div>
                      </div>
                      <!-- Second -->
                      <div class="panel">
                        <a class="panel-heading collapsed" role="tab" id="headingTwo1" data-toggle="collapse" data-parent="#accordion1" href="#collapseTwo1" aria-expanded="false" aria-controls="collapseTwo1">
                          <h4 class="blue panel-title"><i class="fa fa-ellipsis-v"></i> Permanent Address</h4>
                        </a>
                        <div id="collapseTwo1" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo1">
                          <div class="panel-body">
                            <div class="row">
                                <div class="form-group">
                                    <table style="width: 100%">
                                      <?php
									  if(!empty($this->alumniPermanentAddress)){
                                      $alumniPermanentAdd = array();
                                      foreach ($this->alumniPermanentAddress as $address): 
                                        $alumniPermanentAdd = $address;                                       
                                      ?>
                                      <tr>
                                        <th>Village:</th>
                                        <td><?php echo $alumniPermanentAdd['village_name']; ?></td>
                                        <th>Gewog:</th>
                                        <td><?php echo $alumniPermanentAdd['gewog_name']; ?></td>
                                      </tr>
                                      <tr>
                                        <th>Dzongkhag:</th>
                                        <td><?php echo $alumniPermanentAdd['dzongkhag_name']; ?></td>
                                      </tr>
                                    <?php endforeach; 
									  } else {
									?>
									  <tr>
                                        <th>Village:</th>
                                        <td><?php echo "NA"; ?></td>
                                        <th>Gewog:</th>
                                        <td><?php echo "NA"; ?></td>
                                      </tr>
                                      <tr>
                                        <th>Country:</th>
                                        <td><?php echo "NA"; ?></td>
                                      </tr>
                                    <?php } ?>
                                    </table>
                                </div>
                            </div> <!-- end of row-->
                          </div>
                        </div>

                      </div>

                      <!-- Third panel-->
                      <div class="panel">
                        <a class="panel-heading collapsed" role="tab" id="headingThree1" data-toggle="collapse" data-parent="#accordion1" href="#collapseThree1" aria-expanded="false" aria-controls="collapseThree1">
                          <h4 class="blue panel-title"><i class="fa fa-ellipsis-v"></i> Contact Details</h4>
                        </a>
                        <div id="collapseThree1" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree1">
                          <div class="panel-body">
                            <div class="row">
                                <div class="form-group">
                                    <table style="width: 100%">
                                      <?php 
                                      $alumniContact = array();
                                      foreach ($this->alumniContactDetails as $contactDetails): {
                                        $alumniContact = $contactDetails;
                                      }
                                      ?>
                                      <tr>
                                        <th>Email:</th>
                                        <td><?php echo $alumniContact['email_address']; ?></td>
                                      </tr>
                                      <tr>
                                        <th>Contact No:</th>
                                        <td><?php echo $alumniContact['contact_no']; ?></td>
                                      </tr>
                                    <?php endforeach; ?>
                                    </table>
                                </div>
                            </div> <!-- end of row-->
                            <!-- end work experience -->
                          </div>
                        </div>
                      </div><!--End of third panel-->          
                    </div>
                    <!-- end of accordion -->
                </div>
              </div> 
            </div>
                        
                  
                  <div role="tabpanel" class="tab-pane fade" id="tab_content2" aria-labelledby="profile-tab">
                       <br/> 
                       <div class="x_panel"> 
             <div class="x_title">                  
                            <div class="clearfix"></div>
                                
                                <!-- start accordion -->
                    <div class="accordion" id="accordion2" role="tablist" aria-multiselectable="true">
                      <div class="panel">
                        <a class="panel-heading" role="tab" id="headingOne2" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne2" aria-expanded="true" aria-controls="collapseOne2">
                          <h4 class="blue panel-title"><i class="fa fa-ellipsis-v"></i> Current Employment Details</h4>
                        </a>
                        <div id="collapseOne2" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne2">
                          <div class="panel-body">
                              <div class="row">
                                <div class="form-group">
                                    <table style="width: 100%">
                                      <?php
									  if(!empty($this->alumniEmploymentDetails)){
                                      $employmentDetails = array();
                                      foreach ($this->alumniEmploymentDetails as $details): {
                                        $employmentDetails = $details;
                                      }
                                      ?>
                                      <tr>
                                        <th>Job Title:</th>
                                        <td><?php echo $employmentDetails['current_job_title']; ?></td>
										<th>Qualification:</th>
                                        <td><?php echo $employmentDetails['study_level']; ?></td>
                                      </tr>
                                      <tr>
                                        <th>Organisation:</th>
                                        <td><?php echo $employmentDetails['current_job_organisation']; ?></td>
                                      </tr>
									  <tr>
                                        <th>Address:</th>
                                        <td><?php echo $employmentDetails['present_address']; ?></td>
                                      </tr>
                                    <?php endforeach; 
									  } else {
									?>
									<tr>
                                        <th>Job Title:</th>
                                        <td><?php echo "NA"; ?></td>
										<th>Qualification:</th>
                                        <td><?php echo "NA"; ?></td>
                                      </tr>
                                      <tr>
                                        <th>Organisation:</th>
                                        <td><?php echo "NA"; ?></td>
                                      </tr>
									  <tr>
                                        <th>Address:</th>
                                        <td><?php echo "NA"; ?></td>
                                      </tr>
									  <?php } ?>
                                    </table>
                                </div>
                            </div> <!-- end of row-->                                
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>  
                </div>                           
                    </div> 
                   </div>
                 </div>
               </div>
             <!-- End of Staff View -->
           </div>
         </div>
       </div>
     </div>
   </div>
 </div>

    <?php } ?>