<?php

 $title = 'Search Hostel';
 $this->headTitle($title);

  $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    //IDEA-CBC
    //Original
    //$iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('aes-256-cbc'));

    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));

    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}
 ?>

<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <?php 
                            if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                                echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                $messages = $this->flashMessenger()->getMessages();
                                foreach($messages as $message) {
                                    echo '<strong>Failure!</strong>'. $message;
                                }
                                echo '</div>';
                            }

                            else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                                echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                $messages = $this->flashMessenger()->getMessages();
                                foreach($messages as $message) {
                                    echo '<strong>Failure!</strong>'. $message;
                                }
                                echo '</div>';
                            }
                        ?>
              </div>
              <div class="ln_solid"></div>
                      <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                          <a href="<?php echo $this->url('viewhostelroom');?>"><span class="btn btn-primary"><i class="fa fa-angle-double-left"></i> Back</span></a>
                        </div>
                      </div>

        </div>
          </div>
        </div>   
      </div>
                