<?php

 $title = 'Room Inventory';
 $this->headTitle($title);
 
 $inventory = array();
 foreach($hostelInventoryDetails as $details){
	 $inventory = $details;
 }

 ?>

<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                   <?php
                    // Opening of the form tag
                    $form->prepare();
					echo $this->form()->openTag($form);
				    $hostel = $form->get('hostel');
					$hostel->get('id')->setValue($inventory['id']);
				    $hostel->get('organisation_id')->setValue($this->organisation_id);
					$hostel->get('hostel_room_no')->setValue($inventory['hostel_room_no']);
					$hostel->get('no_chairs')->setValue($inventory['no_chairs']);
					$hostel->get('no_tables')->setValue($inventory['no_tables']);
					$hostel->get('no_beds')->setValue($inventory['no_beds']);
					$hostel->get('sockets')->setValue($inventory['sockets']);
					$hostel->get('lights')->setValue($inventory['lights']);
					$hostel->get('remarks')->setValue($inventory['remarks']);
					$hostel->get('hostels_list_id')->setValue($inventory['hostels_list_id']);
				    $hostel->get('hostels_list_id')->setValueOptions($this->hostelList);
                    echo $this->formHidden($hostel->get('id')); 
					echo $this->formHidden($hostel->get('organisation_id'));
				    ?> 
					<?php 
					  if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
						  echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
						  echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
						  $messages = $this->flashMessenger()->getMessages();
						  foreach($messages as $message) {
							  echo '<strong>Success!</strong>'. $message;
						  }
						  echo '</div>';
					  }

					  else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
						  echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
						  echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
						  $messages = $this->flashMessenger()->getMessages();
						  foreach($messages as $message) {
							  echo '<strong>Failure!</strong>'. $message;
						  }
						  echo '</div>';
					  }

					?> 
							
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Present Hostel Name: <span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php echo $this->formRow($hostel->get('hostels_list_id')); ?>
                    </div>
                </div>
                </div>
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12"> Room No:<br />
                    		<small>(Only if different from default)</small></label>
                    <div class="col-md-2 col-sm-6 col-xs-12">
                      <?php echo $this->formRow($hostel->get('hostel_room_no')); ?>
                    </div>
                </div>
                </div>
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12"> No. of Chairs: <span class="required">*</span></label>
                    <div class="col-md-2 col-sm-6 col-xs-12">
                      <?php echo $this->formRow($hostel->get('no_chairs')); ?>
                    </div>
                    <label class="control-label col-md-2 col-sm-3 col-xs-12"> No. of Tables: <span class="required">*</span></label>
                    <div class="col-md-2 col-sm-6 col-xs-12">
                      <?php echo $this->formRow($hostel->get('no_tables')); ?>
                    </div>
                </div>
                </div>
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12"> No. of Beds: <span class="required">*</span></label>
                    <div class="col-md-2 col-sm-6 col-xs-12">
                      <?php echo $this->formRow($hostel->get('no_beds')); ?>
                    </div>
                    <label class="control-label col-md-2 col-sm-3 col-xs-12"> No. of Sockets: <span class="required">*</span></label>
                    <div class="col-md-2 col-sm-6 col-xs-12">
                      <?php echo $this->formRow($hostel->get('sockets')); ?>
                    </div>
                </div>
                </div>
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Lights/Bulbs etc: <span class="required">*</span></label>
                    <div class="col-md-2 col-sm-6 col-xs-12">
                      <?php echo $this->formRow($hostel->get('lights')); ?>
                    </div>
                </div>
                </div>
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12"> Remarks:<br />
                    		<small>(if any)</small></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php echo $this->formRow($hostel->get('remarks')); ?>
                    </div>
                </div>
                </div>
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
						<?php
						   echo $this->formHidden($form->get('csrf'));
						   echo $this->formRow($hostel->get('submit'));
                        ?>
                    	</div>
                    </div>
               </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                </div>
              </div>
        </div>


              <?php
				 $title = 'Hostel Inventory List';
				 $this->headTitle($title);
			  ?>
              <div class="col-md-12 col-xs-12">
                  
                  <div class="x_panel">
                      <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                  </div>
                
                    <div class="x_content">
                        <div class="table-responsive">
                      <table id="datatable-buttons" class="table table-striped jambo_table bulk_action"> 
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Sl. No</th>
                            <th class="column-title">Hostel Name</th>
                            <th class="column-title">Room No</th>
                            <th class="column-title">Beds</th>
                            <th class="column-title">Chairs</th>
                            <th class="column-title">Tables</th>
                            <th class="column-title">Sockets</th>
                            <th class="column-title">Lights/Bulbs</th>
                          </tr>
                        </thead>
                        <tbody>
                            <?php $i=1; foreach ($this->hostelInventory as $hostel) : ?>
                          <tr class="even pointer">
                            <td class=" "><?php echo $i++;?></td>
                            <td class=" "><?php echo $this->escapeHtml($hostel['hostel_name']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($hostel['hostel_room_no']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($hostel['no_beds']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($hostel['no_chairs']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($hostel['no_tables']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($hostel['sockets']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($hostel['lights']);?></td>
                          </tr>
                          <?php endforeach; ?>
                        </tbody>
                      </table>
                    </div>
                    </div>
                
                </div>
             </div>
          </div>
        </div>
                