<?php
 $title = 'Add Individual Student Participation';
 $this->headTitle($title);
 ?>
<div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                  </div>
                    
                  <div class="x_content">
                    <br/>
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				            $participation = $form->get('participation');
                    $participation->get('participation_type')->setValueOptions($this->participation_category);
                    echo $this->form()->openTag($form);
                    echo $this->formHidden($participation->get('id'));
					
					//getting the student details
					$studentName;
					$studentId; //this is the student id
					$stdId; //this is the auto generated id
					$studentDetail = $this->studentDetail;
					foreach($studentDetail as $student){
						$studentName = $student['first_name'];
						$studentName .= ' ';
						$studentName .= $student['middle_name'];
						$studentName .= ' ';
						$studentName .= $student['last_name'];
						$studentId = $student['student_id'];
						$stdId = $student['id'];
					}
					
					//setting the value of the std id
					$participation->get('student_id')->setValue($stdId);
				  ?>  
                    <div class="row">
                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Student Name <span class="required">*</span></label>
                        <div class="col-md-3 col-sm-3 col-xs-12">
                       		<input type="text" placeholder="<?php echo $studentName; ?>" class="form-control col-md-7 col-xs-12" disabled="disabled">
                        </div>
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Student ID <span class="required">*</span></label>
                        <div class="col-md-3 col-sm-3 col-xs-12">
                        	<input type="text" placeholder="<?php echo $studentId; ?>" class="form-control col-md-7 col-xs-12" disabled="disabled">
                        </div>
                      </div>
                    </div>
                    <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Participation Date <span class="required">*</span></label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php
                        echo $this->formRow($participation->get('participation_date'));
                        ?>
                        </div>
                    </div>
                    </div>
                     <div class="row">
                    <div class="form-group"> 
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Participation Type<span class="required">*</span>
                        </label>
                        <div class="col-md-8 col-sm-8 col-xs-12">
                          <?php
                        echo $this->formRow($participation->get('participation_type'));
                        ?>
                        
                      </div>
                  </div>
                    </div>
                    <div class="row">
                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Brief Description
                        </label>
                        <div class="col-md-8 col-sm-8 col-xs-12">
                          <?php
                         echo $this->formRow($participation->get('remarks'));
                        ?>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Evidence File
                        </label>
                        <div class="col-md-8 col-sm-8 col-xs-12">
                          <?php
                         echo $this->formRow($participation->get('evidence_file'));
                        ?>
                        </div>
                      </div>
                    </div>
                   
                    <div class="ln_solid"></div>
                    <div class="row">
                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <?php
                         echo $this->formHidden($participation->get('student_id')->setValue($stdId));
						 echo $this->formHidden($form->get('csrf'));
						 echo $this->formSubmit($participation->get('submit')); 
                        ?>
                        </div>
                    </div>
                    </div>
                   <?php
                    echo $this->form()->closeTag();
                    ?>
                       
                    
                  </div>
                </div>
              </div>
           </div>
         </div>
