<?php
 // module/EmployeeDetail/view/employee-detail/employee-detail/emppersonaldetail.phtml:

 $title = 'Add Individual Student Achievements';
 $this->headTitle($title);
 ?>
<div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                  </div>
                    
                  <div class="x_content">
                    <br/>
                   
                        
                        
                        <?php
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        
                        echo $this->formHidden($form->get('id'));
                        ?>
                    <div class="row">
                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Year<span class="required">*</span>
                        </label>
                        <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php
                        echo $this->formRow($form->get('student_course'));
                        ?>
                        </div>
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Programme<span class="required">*</span>
                        </label>
                        <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php
                        echo $this->formRow($form->get('student_course'));
                        ?>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                    <div class="form-group">
                        
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Semester <span class="required">*</span>
                        </label>
                        <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php
                        echo $this->formRow($form->get('student_semester'));
                        ?>
                        </div>
                         <label class="control-label col-md-2 col-sm-2 col-xs-12">Name <span class="required">*</span>
                        </label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php
                        echo $this->formRow($form->get('student_name'));
                        ?>
                        </div>
                      </div>
                    </div>
                     <div class="row">
                    <div class="form-group"> 
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Achievement Category <span class="required">*</span>
                        </label>
                        <div class="col-md-8 col-sm-8 col-xs-12">
                          <?php
                        echo $this->formRow($form->get('student_achievement_cat'));
                        ?>
                        
                      </div>
                  </div>
                    </div>
                    <div class="row">
                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Remarks <span class="required">*</span>
                        </label>
                        <div class="col-md-8 col-sm-8 col-xs-12">
                          <?php
                         echo $this->formRow($form->get('student_achievement_remark'));
                        ?>
                        </div>
                      </div>
                    </div><div class="row">
                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Upload Evidence<span class="required">*</span>
                        </label>
                        <div class="col-md-3 col-sm-3 col-xs-12">
                         <input type="file">
                        </div></div></div>
                   
                    <div class="row">
                        <div class="form-group">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12"><span class="required"></span></label>
                            <div class="col-md-8 col-sm-8 col-xs-12">
                                <button type="button" class="btn btn-primary">Add More</button>
                            </div>
                        </div>
                    </div>
                    
                    
                    <div class="ln_solid"></div>
                    <div class="row">
                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <?php
                         echo $this->formSubmit($form->get('submit')); 
                        ?>
                        </div>
                    </div>
                    </div>
                   <?php
                    echo $this->form()->closeTag();
                    ?>
                       
                    
                  </div></div></div></div></div>
                        
                   
                    
                 
                 
            
         
              
       
                