<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
<div class="menu_section">
<br><br><br>
<ul class="nav side-menu">
	<li><a><i class="fa fa-graduation-cap"></i>Academic<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>Academic Assessment<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('academicassessment') ?>">Continuous Assessment</a></li>
					<li><a href="<?php echo $this->url('viewassessmentmarks') ?>">View Continuous Assessment</a></li>
					<li><a href="<?php echo $this->url('editassessmentmarks') ?>">Edit Continuous Assessment</a></li>
					<li><a href="<?php echo $this->url('viewsemestermarks') ?>">View Semester Marks</a></li>
					<li><a href="<?php echo $this->url('editsemestermarks') ?>">Edit Semester Marks</a></li>
					<li><a href="<?php echo $this->url('viewconsolidatedmarks') ?>">View Consolidated Marks</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Timetable<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('viewtimetable') ?>">View Student Timetable</a></li>
					<li><a href="<?php echo $this->url('viewtutortimetable') ?>">View Tutor Timetable</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Student Attendance<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('studentattendance') ?>">Attendance Entry</a></li>
					<li><a href="<?php echo $this->url('extraclassattendance') ?>">Extra Class Attendance</a></li>
			</ul>
			</li>
		</ul>
	</li>
	<li><a><i class="fa fa-graduation-cap"></i>Research Management<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>Research Grants<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('researchannouncementforgrant') ?>">Research Grant Announcement</a></li>
					<li><a href="<?php echo $this->url('applyuniversitygrant') ?>">Apply for University Grants</a></li>
					<li><a href="<?php echo $this->url('applycollegegrant') ?>">Apply for College Grants</a></li>
					<li><a href="<?php echo $this->url('listcarggrants') ?>">List of College Grants</a></li>
					<li><a href="<?php echo $this->url('updatecollegegrant') ?>">Update Approved CARG</a></li>
			</ul>
			</li>
			<li><a href="<?php echo $this->url('addpublicationtype') ?>">Publication Type</a></li>
			<li><a><i class=""></i>Research Publication<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('requestpublication') ?>">Request for Publication</a></li>
					<li><a href="<?php echo $this->url('applypublication') ?>">Apply for Research Publication</a></li>
					<li><a href="<?php echo $this->url('researchpublicationstatus') ?>">Research Publication Status</a></li>
					<li><a href="<?php echo $this->url('viewcollegepublication') ?>">View College Research Publication</a></li>
			</ul>
			</li>
			<li><a href="<?php echo $this->url('researchtype') ?>">Research Type</a></li>
		</ul>
	</li>
</ul>
</div>
</div>
