<?php
 // module/Inventory/view/goods-transaction/goods-transaction/add-item-quantity-type.phtml:

 $title = 'Add Item Quantity Type';
 $this->headTitle($title);
?>

<div class="right_col" role="main">
    <div class=" ">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
			  <div class="x_title">
				<h2><?php echo $this->escapeHtml($title); ?></h2>
				<ul class="nav navbar-right panel_toolbox">
				  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
				  </li>
				 </ul>
			  <div class="clearfix"></div>
			  </div>
		  
			  <div class="x_content">
				  <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				    $itemquantity = $form->get('itemquantitytype');
                    echo $this->form()->openTag($form);
                    echo $this->formHidden($itemquantity->get('id'));
                 ?>               
                
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="item_quantity_type">Item Quantity Type</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                            <?php  echo $this->formRow($itemquantity->get('item_quantity_type')); ?>
                    </div>
                </div>
                
                <div class="form-group">           
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="remarks">Remarks</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                            <?php  echo $this->formRow($itemquantity->get('remarks')); ?>
                    </div>
                </div>
                
                <div class="form-group">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                       <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
						   <?php  
                            echo $this->formHidden($form->get('csrf'));
                            echo $this->formSubmit($itemquantity->get('submit')); ?>
                        </div>
                    </div>
                </div> 

                    <?php 
                //closing the form tag  
                 echo $this->form()->closeTag();
                 ?>

			  </div> <!-- End of x-content -->
            </div>

            
<?php
// module/Inventory/view/goods-transaction/goods-transaction/view-item-quantity-type.phtml:

 $title = 'Item Quantity Type';
 $this->headTitle($title);
?>     
            <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>

                <div class="x_content">
                    <div class="table-responsive">
                        <table class="table table-striped responsive-utilities jambo_table bulk_action table-bordered">
                            <thead>
                                <tr class="headings">
                                    <th class="column-title">Sl. No</th>
                                    <th class="column-title">Item Quantity Type </th>
                                    <th class="column-title">Remarks </th>
                                    <th class="column-title">Action</th>
                                </tr>
                            </thead>

                            <tbody>
                            <?php $i=1; ?>
                            <?php foreach ($this->itemQuantity as $itemQty) : ?>
                                <tr class="even pointer">
                                    <td class=" "><?php echo $i; ?></td>
                                    <td class=" "><?php echo $this->escapeHtml($itemQty->getItem_Quantity_Type()); ?></td>
                                    <td class=" "><?php echo $this->escapeHtml($itemQty->getRemarks()); ?></td>
                                    <th class=" "><a href="<?php echo $this->url('edit-item-quantity-type', array('id' => $itemQty->getId())); ?>"><span class="fa fa-pencil"></span></a>&nbsp;&nbsp;&nbsp;

                                           <a href="<?php echo $this->url('delete-item-quantity-type', array('id' => $itemQty->getId())); ?>"><span class="fa fa-trash"></span></a>
                                    </th>
                                </tr>
                            <?php $i++; ?>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!--
 <script>
     function add_category() {
         var currentCount = $('form > fieldset > fieldset').length;
         var template = $('form > fieldset > span').data('template');
         template = template.replace(/__index__/g, currentCount);

         $('form > fieldset').append(template);

         return false;
     }
 </script>-->
