<?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Add Goods Received Donation';
 $this->headTitle($title);
?>

<div class="right_col" role="main">
    <div class=" ">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                <h2><?php echo $this->escapeHtml($title); ?></h2>
                <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                </ul>
              <div class="clearfix"></div>
              </div>
          
              <div class="x_content">
                  <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    $goodsdonationentry = $form->get('goodsreceiveddonation');
                    echo $this->form()->openTag($form);
                    echo $this->formHidden($goodsdonationentry->get('id'));

                    $goodsdonationentry->get('item_received_by')->setValue($this->username);
                    //$goodsdonationentry->get('item_category_id')->setValueOptions($this->itemCategory);
                    //$goodsdonationentry->get('item_sub_category_id')->setValueOptions($this->itemSubCategory);
                    //$goodsdonationentry->get('item_name_id')->setValueOptions($this->itemName);
                    //$goodsdonationentry->get('donation_id')->setValueOptions($this->itemDonar);

                    
                    $received_type = 'Donation';
                    $goodsdonationentry->get('item_received_type')->setValue($received_type);

                    $goods_entry_date = date('Y-m-d');
                    $goodsdonationentry->get('item_entry_date')->setValue($goods_entry_date);
                 ?> 

                 <div class="form-group">           
                    <label class="control-label col-md-2 col-sm-2 col-xs-12" for="item_received_type">Item Received Type</label>
                    <div class="col-md-8 col-sm-8 col-xs-12">
                            <?php  echo $this->formRow($goodsdonationentry->get('item_received_type')); ?>
                    </div>
                </div>

                <div class="form-group">           
                    <label class="control-label col-md-2 col-sm-2 col-xs-12" for="item_donor_details_id">Item Donar</label>
                    <div class="col-md-8 col-sm-8 col-xs-12">
                            <?php  echo $this->formRow($goodsdonationentry->get('item_donor_details_id')); ?>
                    </div>
                </div>

                <div class="form-group">           
                    <label class="control-label col-md-2 col-sm-2 col-xs-12" for="item_entry_date">Item Entry Date</label>
                    <div class="col-md-3 col-sm-3 col-xs-12">
                            <?php  echo $this->formRow($goodsdonationentry->get('item_entry_date')); ?>
                    </div>
                </div>

                <div class="form-group">           
                    <label class="control-label col-md-2 col-sm-2 col-xs-12" for="item_received_by">Item Received By</label>
                    <div class="col-md-3 col-sm-3 col-xs-12">
                            <?php  echo $this->formRow($goodsdonationentry->get('item_received_by')); ?>
                    </div>
                    <label class="control-label col-md-2 col-sm-2 col-xs-12" for="item_updated_by">Item Verified By</label>
                    <div class="col-md-3 col-sm-3 col-xs-12">
                            <?php  echo $this->formRow($goodsdonationentry->get('item_verified_by')); ?>
                    </div>
                </div><br/><br/>

                <div class="clear"></div>
                    <h2><?php echo $this->escapeHtml("Item Donation Details"); ?></h2>
                    <div class="clear"></div>
                    <div class="ln_solid"></div>

                <div class="form-group">
                    <div class="col-md-4 col-sm-12 col-xs-12">
                    <label>Item Category</label>
                        <?php echo $this->formRow($form->get('item_category_id')); ?>
                    </div>
                    <div class="col-md-4 col-sm-12 col-xs-12">
                    <label>Item Sub Category</label>
                        <?php echo $this->formRow($form->get('item_sub_category_id')); ?>
                    </div>
                    <div class="col-md-4 col-sm-12 col-xs-12">
                    <label>Item Name</label>
                        <?php echo $this->formRow($form->get('item_name_id')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                    <label>Quantity</label>
                        <?php echo $this->formRow($goodsdonationentry->get('item_quantity')); ?>
                    </div>
                    <div class="col-md-6 col-sm-12 col-xs-12">
                        <label>Item Cost</label>
                        <?php echo $this->formRow($goodsdonationentry->get('item_purchasing_rate')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4 col-sm-12 col-xs-12">
                    <label>Item Specification</label>
                        <?php echo $this->formRow($goodsdonationentry->get('item_specification')); ?>
                    </div>
                    <div class="col-md-4 col-sm-12 col-xs-12">
                    <label>Remarks</label>
                        <?php echo $this->formRow($goodsdonationentry->get('remarks')); ?>
                    </div>
                </div>
                
                <div class="form-group">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                       <label class="control-label col-md-12 col-sm-12 col-xs-12"></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                           <?php  
                            echo $this->formHidden($form->get('csrf'));
                            echo $this->formRow($goodsdonationentry->get('submit')); ?>
                        </div>
                    </div>
                </div> 

                    <?php 
                //closing the form tag  
                 echo $this->form()->closeTag();
                 ?>

              </div> <!-- End of x-content -->
            </div> 
        </div> 
    </div>
</div>


 <script>
     function add_goodsreceiveddonation() {
         var currentCount = $('form > fieldset > fieldset').length;
         var template = $('form > fieldset > span').data('template');
         template = template.replace(/__index__/g, currentCount);

         $('form > fieldset').append(template);

         return false;
     }

     function remove_addsreceiveddonation(){

        $('form > fieldset > fieldset').last().remove();
        
        return true;
     }
 </script>
