<?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Edit Supplied Item';
 $this->headTitle($title);

?>

<div class="right_col" role="main">
    <div class="">              
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                <h2><?php echo $this->escapeHtml($title); ?></h2>
                <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                </ul>
                <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    $editgoodssupplied = $form->get('goodsreceivedpurchased');
                    echo $this->form()->openTag($form);
                    $editgoodssupplied->get('id')->setValue($this->addGoodsSuppliedDetails->getId());
                   // $editgoodssupplied->get('organisation_id')->setValue($this->donorDetails->getOrganisation_Id());
                    echo $this->formHidden($editgoodssupplied->get('organisation_id'));
                    $editgoodssupplied->get('item_entry_date')->setValue($this->addGoodsSuppliedDetails->getItem_Entry_Date());
                    echo $this->formHidden($editgoodssupplied->get('item_entry_date'));

                   // $editgoodssupplied->get('item_category_id')->setValue($this->addGoodsSuppliedDetails->getItem_Category_Id());
                    $editgoodssupplied->get('item_quantity')->setValue($this->addGoodsSuppliedDetails->getItem_Quantity());
                    $editgoodssupplied->get('item_purchasing_rate')->setValue($this->addGoodsSuppliedDetails->getItem_Purchasing_Rate());
                    $editgoodssupplied->get('item_amount')->setValue($this->addGoodsSuppliedDetails->getItem_Amount());
                    $editgoodssupplied->get('item_received_type')->setValue($this->addGoodsSuppliedDetails->getItem_Received_Type());
                    echo $this->formHidden($editgoodssupplied->get('item_received_type'));
                    $editgoodssupplied->get('item_stock_status')->setValue($this->addGoodsSuppliedDetails->getItem_Stock_Status());
                    echo $this->formHidden($editgoodssupplied->get('item_stock_status'));
                    $editgoodssupplied->get('item_received_by')->setValue($this->addGoodsSuppliedDetails->getItem_Received_By());
                    echo $this->formHidden($editgoodssupplied->get('item_received_by'));
                    $editgoodssupplied->get('item_received_date')->setValue($this->addGoodsSuppliedDetails->getItem_Received_Date());
                    echo $this->formHidden($editgoodssupplied->get('item_received_date'));
                    $editgoodssupplied->get('item_verified_by')->setValue($this->addGoodsSuppliedDetails->getItem_Verified_By());
                    echo $this->formHidden($editgoodssupplied->get('item_verified_by'));
                    $editgoodssupplied->get('item_in_stock')->setValue($this->addGoodsSuppliedDetails->getItem_In_Stock());
                    echo $this->formHidden($editgoodssupplied->get('item_in_stock'));
                    $editgoodssupplied->get('item_received_purchased_id')->setValue($this->addGoodsSuppliedDetails->getItem_Received_Purchased_Id());
                    echo $this->formHidden($editgoodssupplied->get('item_received_purchased_id'));
                    $editgoodssupplied->get('item_status')->setValue($this->addGoodsSuppliedDetails->getItem_Status());
                    echo $this->formHidden($editgoodssupplied->get('item_status'));
                    $form->get('item_name_id')->setValue($this->addGoodsSuppliedDetails->getItem_Name_Id());
                    $editgoodssupplied->get('item_specification')->setValue($this->addGoodsSuppliedDetails->getItem_Specification());
                    $editgoodssupplied->get('remarks')->setValue($this->addGoodsSuppliedDetails->getRemarks());
                    $editgoodssupplied->get('submit')->setValue('Update');
                    echo $this->formHidden($editgoodssupplied->get('id'));
                 ?>               
                

                                    <div class="form-group">
                                       <div class="col-md-4 col-sm-12 col-xs-12">
                                        <label>Item Category</label>
                                            <?php echo $this->formRow($form->get('item_category_id')); ?>
                                        </div>
                                        <div class="col-md-4 col-sm-12 col-xs-12">
                                        <label>Item Sub Category</label>
                                            <?php echo $this->formRow($form->get('item_sub_category_id')); ?>
                                        </div>
                                        <div class="col-md-4 col-sm-12 col-xs-12">
                                        <label>Item Name</label>
                                            <?php echo $this->formRow($form->get('item_name_id')); ?>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="col-md-4 col-sm-12 col-xs-12" id="item_quantity">
                                            <label>Quantity</label>
                                            <?php echo $this->formRow($editgoodssupplied->get('item_quantity')); ?>
                                        </div>
                                    <div class="col-md-4 col-sm-12 col-xs-12" id="item_purchasing_rate">
                                        <label>Purchasing Rate</label>
                                        <?php echo $this->formRow($editgoodssupplied->get('item_purchasing_rate')); ?>
                                    </div>
                                    <div class="col-md-4 col-sm-12 col-xs-12" id="item_amount">
                                        <label>Amount</label>
                                        <?php echo $this->formRow($editgoodssupplied->get('item_amount')); ?>
                                    </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="col-md-6 col-sm-12 col-xs-12">
                                            <label>Item Specification</label>
                                            <?php echo $this->formRow($editgoodssupplied->get('item_specification')); ?>
                                        </div>
                    
                                        <div class="col-md-6 col-sm-12 col-xs-12">
                                        <label>Remarks</label>
                                        <?php echo $this->formRow($editgoodssupplied->get('remarks')); ?>
                                        </div>
                                    </div>

                <div class="form-group">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                       <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <?php  
                            echo $this->formHidden($form->get('csrf'));
                            echo $this->formSubmit($editgoodssupplied->get('submit'));
                          ?>
                        </div>
                    </div>
                </div> 

                <?php 
                //closing the form tag  
                 echo $this->form()->closeTag();
                 ?>
                </div>
            </div>
        </div>
    </div>
</div>