<?php
 $title = 'Edit Invigilator Assignment for Examination Duty';
 $this->headTitle($title);
 $invigilation_duties = array();
 foreach($this->inviglationDetails as $detail){
	 $invigilation_duties = $detail;
 }
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    $invigilator = $form->get('examinvigilator');
                    $invigilator->get('id')->setValue($invigilation_duties['id']);
                    $invigilator->get('examination_timetable_id')->setValueOptions($this->examinationList);
                    $invigilator->get('employee_details_id')->setValueOptions($this->employeeList);
                    $invigilator->get('exam_reliever_id')->setValueOptions($this->employeeList);
                    $invigilator->get('organisation_id')->setValue($this->organisation_id);
                    $invigilator->get('examination_timetable_id')->setValue($invigilation_duties['examination_timetable_id']);
                    $invigilator->get('employee_details_id')->setValue($invigilation_duties['employee_details_id']);  
                    $invigilator->get('exam_reliever_id')->setValue($invigilation_duties['exam_reliever_id']);
                    echo $this->formHidden($invigilator->get('id')); 
					          echo $this->formHidden($invigilator->get('organisation_id')); 
				            ?>  
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12"> Examination Module: <span class="required">*</span>
                    </label>
                    <div class="col-md-4 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($invigilator->get('examination_timetable_id')); ?>
                    </div>
                </div>
                </div>                 
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12"> Invigilator: <span class="required">*</span>
                    </label>
                    <div class="col-md-4 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($invigilator->get('employee_details_id')); ?>
                    </div>
                </div>
                </div> 
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12"> Exam Reliever: <span class="required">*</span>
                    </label>
                    <div class="col-md-4 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($invigilator->get('exam_reliever_id')); ?>
                    </div>
                </div>
                </div>
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
						<?php
						   echo $this->formHidden($form->get('csrf'));
						   echo $this->formSubmit($invigilator->get('submit')); 
                        ?>
                    	</div>
                    </div>
               </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                </div>
              </div>
            </div>
          </div>
     </div>
              
   
            
    