<?php
 $title = 'Edit Examination Timetable';
 $this->headTitle($title);
 $timetable_details = array();
 foreach($this->timetableDetails as $detail){
	 $timetable_details = $detail;
 } 
 
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    $form->get('id')->setValue($timetable_details['id']);
                    $form->get('examination_hall_id')->setValueOptions($this->examinationHalls);
                    $form->get('exam_type_id')->setValueOptions($this->examType);
                    $form->get('programmes_id')->setValue($timetable_details['programmes_id']); 
                    $form->get('academic_modules_allocation_id')->setValue($timetable_details['academic_modules_allocation_id']);
                    $form->get('examination_hall_id')->setValue($timetable_details['examination_hall_id']);
                    $form->get('start_time')->setValue(date('H:i', strtotime($timetable_details['start_time'])));
                    $form->get('end_time')->setValue(date('H:i', strtotime($timetable_details['end_time'])));
                    $exam_date = explode("-", $timetable_details['exam_date']);
                    $form->get('exam_date')->setValue($exam_date[01].'/'.$exam_date[02].'/'.$exam_date[00]);
                    $form->get('exam_type_id')->setValue($timetable_details['exam_type_id']);
                    $form->get('organisation_id')->setValue($timetable_details['organisation_id']);
                    $form->get('submit')->setValue('Update');
                    echo $this->formHidden($form->get('id')); 
                    echo $this->formHidden($form->get('programmes_id')); 
                    echo $this->formHidden($form->get('academic_modules_allocation_id'));
                    echo $this->formHidden($form->get('organisation_id'));
                    ?>  
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12"> Programme Name: <span class="required">*</span></label>
                    <div class="col-md-5 col-sm-6 col-xs-12">
                       <input type="text" class="form-control" value="<?php echo $this->programmeList[$timetable_details['programmes_id']]; ?>" disabled>
                    </div>
                </div>
                </div>
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12"> Module Name: <span class="required">*</span></label>
                    <div class="col-md-5 col-sm-6 col-xs-12">
                    <input type="text" class="form-control" value="<?php echo $this->allocatedModuleList[$timetable_details['academic_modules_allocation_id']]; ?>" disabled>
                    </div>
                </div>
                </div>
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12"> Exam Type: <span class="required">*</span></label>
                    <div class="col-md-5 col-sm-6 col-xs-12">
                    <?php  echo $this->formRow($form->get('exam_type_id')); ?>
                    </div>
                </div>
                </div>
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12"> Hall No: <span class="required">*</span></label>
                    <div class="col-md-5 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($form->get('examination_hall_id')); ?>
                    </div>
                </div>
                </div>
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12"> Start Time: <span class="required">*</span></label>
                    <div class="col-md-2 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($form->get('start_time')); ?>
                    </div>
                    <label class="control-label col-md-1 col-sm-3 col-xs-12"> End Time: <span class="required">*</span></label>
                    <div class="col-md-2 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($form->get('end_time')); ?>
                    </div>
                </div>
                </div> 
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12"> Exam Date: <span class="required">*</span></label>
                    <div class="col-md-5 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($form->get('exam_date')); ?>
                    </div>
                </div>
                </div> 
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
						<?php
						   echo $this->formHidden($form->get('csrf'));
						   echo $this->formSubmit($form->get('submit')); 
                        ?>
                    	</div>
                    </div>
               </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                </div>
              </div>
        
         <!-- Start of table listing -->
     </div>
     </div>
     </div>
     </div>
              
   
            
    