<?php
 $title = 'Student Examination Timetable';
 $this->headTitle($title);

 //calculate the no of days between the two selected dates
 if(!empty($this->examinationDates)){
  $start = strtotime($this->examinationDates['start_date']);
  $end = strtotime($this->examinationDates['end_date']);
  $date_diff = $end-$start; 
  $no_days = floor($date_diff/(60*60*24)) + 1; 
  $day = (int) substr($this->examinationDates['start_date'],8,2);
  $exam_dates = array();
  $exam_timetable = array();
  $exam_dates[1]['date'] = $this->examinationDates['start_date'];
  $exam_dates[1]['day'] = date('l', strtotime($exam_dates[1]['date']));
  if($no_days > 1){
    for($i=2; $i<= $no_days; $i++) {
      $exam_dates[$i]['date'] = date('Y-m-d', strtotime("+1 day", strtotime($exam_dates[$i-1]['date'])));
      $exam_dates[$i]['day'] = date('l', strtotime($exam_dates[$i]['date']));
    }
  }
  /*$index = 1;
  if($this->examinationTimetable != NULL){
    foreach($this->examinationTimetable as $timetable){
      $exam_timetable[$index++] = $timetable;
    }
  } 
 /* if($this->examinationTimetable != NULL){
    foreach($this->examinationTimetable as $key => $timetable){
      $exam_timetable[$timetable['exam_date']][$timetable['start_time'].'-'.$timetable['end_time']][] = $timetable['module_title'].'<br>('.$timetable['module_code'].')<br>('.$timetable['start_time'].'-'.$timetable['end_time'].')<br>('.$timetable['hall_name'].':HALL-'.$timetable['hall_no'].')<br><br>';
      //$exam_timetable[$timetable['exam_date']][$timetable['st'<br>('.$timetable['module_code'].')<br>('.$timetable['start_time'].'-'.$timetable['end_time'].')<br>('.$timetable['hall_name'].':HALL-'.$timetable['hall_no'].')<br><br>'art_time'].'-'.$timetable['end_time']][] = $timetable['module_title'].'<br>('.$timetable['module_code'].')<br>('.$timetable['start_time'].'-'.$timetable['end_time'].')<br>('.$timetable['hall_name'].':HALL-'.$timetable['hall_no'].')<br><br>'; 
    }
  }*/
 }
//var_dump($exam_timetable); die();
?>

 <div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
            
                <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                     <div class="clearfix"></div>
                    </div>
                    <br/>
                        <!-- Adding Achievements-->
                        <div class="col-md-12 col-xs-12">
                          <div class="x_panel">
                            <div class="x_title">
                              <h2><?php echo $this->escapeHtml("Timetable")?></h2>
                                <ul class="nav navbar-right panel_toolbox">
                                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                  </li>
                                </ul>
                             <div class="clearfix"></div>
                          
                            </div>
                               
                            <div class="x_content">
                            <h5><i>*(Please enter the programme and year to view the timetable)</i></h5>
                              <br />
                               <?php
                                // Opening of the form tag
                                $form->prepare();
                                echo $this->form()->openTag($form);
                                $form->get('programme')->setValueOptions($this->programmeList);
                                $form->get('exam_type')->setValueOptions($this->examType);
                                $form->get('year')->setValueOptions($this->selectYear);
                              ?>
                            
                              <div class="row">
                                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Programme Name</label>
                                    <?php echo $this->formRow($form->get('programme')); ?>
                                  </div>
                                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Year</label>
                                    <?php echo $this->formRow($form->get('year')); ?>
                                  </div>
                                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Exam Type</label>
                                    <?php echo $this->formRow($form->get('exam_type')); ?>
                                  </div>
                               </div>
                             
                             <div class="row">
                                <div class="ln_solid"></div>
                                <div class="form-group">
                                    <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                                      <?php
                                       echo $this->formHidden($form->get('csrf'));
                                       echo $this->formSubmit($form->get('submit')); 
                                       echo $this->form()->closeTag(); 
                                    ?>
                                </div>
                            </div>
                              
                          </div>
                        </div>
                       </div>     
                        <div class="col-md-12 col-sm-12 col-xs-12">
                          <div class="x_panel">
                            <div class="x_title">
                              <h2><?php echo $this->escapeHtml("Examination Timetable"); ?></h2>
                              <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                </li>
                              </ul>
                              <div class="clearfix"></div>
                            </div>
                            <?php if(!empty($this->examinationDates)){?>
                            <div class="x_content">
                              <div class="table-responsive">
                                <table id="datatable-buttons" class="table table-striped jambo_table bulk_action table-bordered">
                                  <thead>
                                    <tr class="headings">
                                      <th style="width: 10%" class="column-title">Day/Date </th>
                                      <?php foreach($this->examinationTiming as $key=>$value): ?>
                                        <th style="width: 15%" class="column-title"><?php echo $value; ?></th>
									                    <?php endforeach; ?>
                                    </tr>
                                  </thead>
                                  <tbody>
                                    <?php foreach($exam_dates as $date): 
                                     // $i = 1; foreach($this->examinationTimetable as $key=>$exam):
                                      ?> 
                                      <tr class="even pointer">
                                        <td><?php echo date('d-m-Y', strtotime($date['date'])).' <br> ('.$date['day'].')'; ?></td>
                                        <?php  
                                           foreach($this->examinationTiming as $index => $examTiming):
                                            ?>
                                              <td align="center">
                                              <?php foreach($this->examinationDetails as $key => $value): ?>
                                              <?php if($key == $date['date']){ ?>
                                              <?php if(array_key_exists($examTiming, $this->examinationTimetable[$date['date']])){  ?>
                                                <?php echo ($this->examinationTimetable[$date['date']][$examTiming]); ?>
                                                <?php } else { ?>
                                                <?php echo "OFF"; ?>
                                                <?php } ?>
                                        <?php	} else {?>
                                          
                                        <?php } ?>
                                        <?php endforeach; ?>
                                        
                                        </td>
                                        <?php endforeach; ?>
                                          
                                      </tr>
                                      
                                    <?php endforeach; ?>
                                  </tbody>
                                </table>
                                </div>
                            </div>
                            <?php } ?>
                          </div>
                        </div>
                            
                           		<!-- End of Achievements-->
                        </div>
                      </div>
                  </div>
                </div>
              
