<?php
 $level = 'Edit Employee Permanent Address';
 $this->headTitle($level);
 ?>
<div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2><?php echo $this->escapeHtml($level); ?></h2>
                    <div class="clearfix"></div>
                  </div>
                    
                  <div class="x_content">
                  <h5><i>*Uploading Profile Picture will replace the previous profile picture uploaded</i></h5>
                    <br/>
					<?php
					// Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				    $staff = $form->get('employeeaddress');
                    $staff->get('employee_details_id')->setValue($this->id);
                    $staff->get('emp_house_no')->setValue($this->employees->getEmp_House_No());
                    $staff->get('emp_thram_no')->setValue($this->employees->getEmp_Thram_No());
                    $staff->get('emp_dzongkhag')->setValue($this->employees->getEmp_Dzongkhag());
                    $staff->get('emp_gewog')->setValue($this->employees->getEmp_Gewog());
                    $staff->get('emp_village')->setValue($this->employees->getEmp_Village());
                    echo $this->formHidden($staff->get('id')); 
					echo $this->formHidden($staff->get('employee_details_id'));
                    ?>
                    <?php if($this->message == NULL && $this->flashMessenger()->hasMessages()) {
							echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
							echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
							$messages = $this->flashMessenger()->getMessages();
							foreach($messages as $message) {
								echo '<strong>Success!</strong>'. $message;
							}
							echo '</div>';
                    	} else if($this->message =='Failure' && $this->flashMessenger()->hasMessages()) {
                            echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                            echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                            $messages = $this->flashMessenger()->getMessages();
                            foreach($messages as $message) {
                                echo '<strong>Warning!</strong>'. $message;
                            }
                            echo '</div>';
                     }  ?>
                    <br />
                    <div class="row">
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-2 col-xs-12">Staff Name <span class="required">*</span></label>
                        <div class="col-md-3 col-sm-3 col-xs-12">
                       		<input type="text" placeholder="<?php echo $this->employees->getFirst_Name(). ' '.$this->employees->getMiddle_Name(). ' '.$this->employees->getLast_Name(); ?>" class="form-control col-md-7 col-xs-12" disabled="disabled">
                        </div>
                      </div>
                    </div>
                    <div class="row">
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-2 col-xs-12">Staff ID <span class="required">*</span></label>
                        <div class="col-md-3 col-sm-3 col-xs-12">
                        	<input type="text" placeholder="<?php echo $this->employees->getEmp_Id(); ?>" class="form-control col-md-7 col-xs-12" disabled="disabled">
                        </div>
                      </div>
                    </div>
                    <br />
                    <h2 class="StepTitle">Address Details:</h2>
                     <div class="row">
                      <div class="form-group">  
                          <label class="control-label col-md-2 col-sm-2 col-xs-12">House No:<span class="required">*</span></label>
                         <div class="col-md-2 col-sm-2 col-xs-12">
                            <?php echo $this->formRow($staff->get('emp_house_no')); ?>
                          </div>
                         <label class="control-label col-md-1 col-sm-3 col-xs-12">Thram No:</label>
                         <div class="col-md-2 col-sm-2 col-xs-12">
                            <?php echo $this->formRow($staff->get('emp_thram_no')); ?>
                          </div>
                      </div>
                    </div>
                    <br />
                    <div class="row">
                      <div class="form-group">  
                          <label class="control-label col-md-2 col-sm-2 col-xs-12">Dzongkhag<span class="required">*</span></label>
                         <div class="col-md-2 col-sm-2 col-xs-12">
                            <?php echo $this->formRow($staff->get('emp_dzongkhag')); ?>
                          </div>
                         <label class="control-label col-md-1 col-sm-3 col-xs-12">Gewog</label>
                         <div class="col-md-2 col-sm-2 col-xs-12">
                            <?php echo $this->formRow($staff->get('emp_gewog')); ?>
                          </div>
                          <label class="control-label col-md-1 col-sm-2 col-xs-12">Village</label>
                         <div class="col-md-2 col-sm-2 col-xs-12">
                            <?php echo $this->formRow($staff->get('emp_village')); ?>
                          </div>
                      </div>
                    </div>
                    <div class="row">
                       <div class="ln_solid"></div>
                    	  <div class="form-group">
                           <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                            <div class="col-md-3 col-sm-3 col-xs-12">
                            <?php
                               echo $this->formHidden($form->get('csrf')); 
							   echo $this->formSubmit($staff->get('submit'));
                               echo $this->form()->closeTag();
                            ?>
                            </div>
                    	  </div>
                     </div>
                 
                 </div>
              </div>
           </div>
        </div>
     </div>
