<?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Add Item Sub Category';
 $this->headTitle($title);
?>

<div class="right_col" role="main">
    <div class=" ">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
			  <div class="x_title">
				<h2><?php echo $this->escapeHtml($title); ?></h2>
				<ul class="nav navbar-right panel_toolbox">
				  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
				  </li>
				 </ul>
			  <div class="clearfix"></div>
			  </div>
		  
			  <div class="x_content">
				  <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				    $itemsubcategory = $form->get('itemsubcategory');
                    echo $this->form()->openTag($form);
                    echo $this->formHidden($itemsubcategory->get('id'));
                   // $itemsubcategory->get('item_category_id')->setValueOptions($itemCategory);
                 ?> 

                 <div class="form-group">           
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="item_category_id">Select Item Category Type</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                            <?php  echo $this->formRow($itemsubcategory->get('item_category_id')); ?>
                    </div>
                </div>              
                
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="sub_category_type">Sub Category Type</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                            <?php  echo $this->formRow($itemsubcategory->get('sub_category_type')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="sub_category_code">Sub Category Code</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                            <?php  echo $this->formRow($itemsubcategory->get('sub_category_code')); ?>
                    </div>
                </div>
                
                <div class="form-group">           
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="category_type">Description</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                            <?php  echo $this->formRow($itemsubcategory->get('description')); ?>
                    </div>
                </div>
                
                <div class="form-group">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                       <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
						   <?php  
                            echo $this->formHidden($form->get('csrf'));
                            echo $this->formSubmit($itemsubcategory->get('submit')); ?>
                        </div>
                    </div>
                </div> 

                    <?php 
                //closing the form tag  
                 echo $this->form()->closeTag();
                 ?>

			  </div> <!-- End of x-content -->
            </div> 
        </div> 
    </div>
</div>

<!--
 <script>
     function add_category() {
         var currentCount = $('form > fieldset > fieldset').length;
         var template = $('form > fieldset > span').data('template');
         template = template.replace(/__index__/g, currentCount);

         $('form > fieldset').append(template);

         return false;
     }
 </script>-->
