<?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Transfer Goods';
 $this->headTitle($title);
?>

<div class="right_col" role="main">
    <div class="">              
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                <h2><?php echo $this->escapeHtml($title); ?></h2>
                <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                </ul>
                <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    $applyTransferGoods = $form->get('transfergoods');
                    echo $this->form()->openTag($form);
                    // echo $this->formHidden($goodsTransferDetails->get('id'));
                  // $applyTransferGoods->get('id')->setValue($this->goodsTransferDetails->getId());

                    $applyTransferGoods->get('employee_details_id')->setValue($this->goodsTransferDetails->getEmployee_Details_Id());

                    $applyTransferGoods->get('goods_received_id')->setValue($this->goodsTransferDetails->getGoods_Received_Id());

                    $applyTransferGoods->get('date_of_issue')->setValue($this->goodsTransferDetails->getDate_Of_Issue());

                    $applyTransferGoods->get('quantity')->setValue($this->goodsTransferDetails->getQuantity());

                    $applyTransferGoods->get('submit')->setValue('Update');
                    echo $this->formRow($applyTransferGoods->get('id'));
                 ?>               
                
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="employee_details_id">Employee Id</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                            <?php  echo $this->formRow($applyTransferGoods->get('employee_details_id')); ?>
                    </div>
                </div>
                
                <div class="form-group">           
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="goods_received_id">Goods Received Id</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                            <?php  echo $this->formRow($applyTransferGoods->get('goods_received_id')); ?>
                    </div>
                </div>

                <div class="form-group">           
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="date_of_issue">Issue Date</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                            <?php  echo $this->formRow($applyTransferGoods->get('date_of_issue')); ?>
                    </div>
                </div>

                <div class="form-group">           
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="quantity">Quantity</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                            <?php  echo $this->formRow($applyTransferGoods->get('quantity')); ?>
                    </div>
                </div>
                
                <div class="form-group">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                       <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <?php  
                            //echo $this->formRow($form->get('reset'));
                            echo $this->formRow($applyTransferGoods->get('submit'));
                          ?>
                        </div>
                    </div>
                </div> 

                <?php 
                //closing the form tag  
                 echo $this->form()->closeTag();
                 ?>
                </div>
              </div>
            </div>
        </div>
    </div>

   