<?php
 $title = 'Edit Examination Hall';
 $this->headTitle($title);
 $hall_details = array();
 foreach($this->hallDetails as $detail){
	 $hall_details = $detail;
 }
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				            $examhall = $form->get('examhall');
                    $examhall->get('id')->setValue($hall_details['id']);
                    $examhall->get('hall_no')->setValue($hall_details['hall_no']);
                    $examhall->get('hall_name')->setValue($hall_details['hall_name']);
                    $examhall->get('no_seats')->setValue($hall_details['no_seats']);
                    $examhall->get('organisation_id')->setValue($hall_details['organisation_id']);
                    echo $this->formHidden($examhall->get('id'));
                    echo $this->formHidden($examhall->get('organisation_id')); 
                    ?>  
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12"> Hall No: <span class="required">*</span>
                    </label>
                    <div class="col-md-4 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($examhall->get('hall_no')); ?>
                    </div>
                </div>
                </div>
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12"> Hall/Building Name: <span class="required">*</span>
                    </label>
                    <div class="col-md-4 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($examhall->get('hall_name')); ?>
                    </div>
                </div>
                </div>                   
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12"> Total No. of Seats: <span class="required">*</span>
                    </label>
                    <div class="col-md-4 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($examhall->get('no_seats')); ?>
                    </div>
                </div>
                </div> 
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
						<?php
						   echo $this->formHidden($form->get('csrf'));
						   echo $this->formSubmit($examhall->get('submit')); 
                        ?>
                    	</div>
                    </div>
               </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                </div>
              </div>
        
         <!-- Start of table listing mission and vision -->
        <div class="x_panel">
        	<div class="x_title">
                  <h2><?php echo $this->escapeHtml('List of Examination Halls'); ?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                  </ul>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                     <div class="table-responsive">
                      <table class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                            <th class="column-title" width="5%">Sl No.</th>
                            <th class="column-title">Hall No.</th>
                            <th class="column-title">Hall/Building Name</th>
                            <th class="column-title">No. of Seats</th>
                          </tr>
                        </thead>  
                        <tbody>
                      <tr>
                         <?php $i = 1; foreach ($this->examinationHalls as $hall) : ?>
                          <tr class="even pointer">
                            <td class=" "><?php echo $this->escapeHtml($i++);?></td>
                            <td class=" "><?php echo $this->escapeHtml($hall['hall_no']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($hall['hall_name']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($hall['no_seats']);?></td>
                          </tr>
                          <?php endforeach; ?>
                      </tr>
                      </tbody>
                      </table>
                     </div>
                   </div>
                </div>
    
          </div>
        </div> 
     </div>
              
   
            
    