<?php
 $title = 'Academic Planning and Resources Committee Meeting Information';
 $this->headTitle($title);

?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <table id="datatable" class="table table-striped jambo_table table-bordered">
                    <thead>
                      <tr class="headings">
                        <th class="column-title">Academic Planning and Resources Committee Meeting Minutes</th>
                        <th class="column-title">Action</th>
                      </tr>
                    </thead>  
                    <tbody>
                      <tr class="even pointer">
                        <td class=" ">46th APRC minutes</td>
                        <td class=" last" width="10%"><a href="../data/meeting_minutes/aprc/46th_APRC_minutes.pdf" target="_blank" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Download</a></td>
                      </tr>
                      <tr class="even pointer">
                        <td class=" ">45th APRC minutes</td>
                        <td class=" last" width="10%"><a href="../data/meeting_minutes/aprc/45th_APRC_minutes.pdf" target="_blank" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Download</a></td>
                      </tr>
                      <tr class="even pointer">
                        <td class=" ">44th APRC minutes</td>
                        <td class=" last" width="10%"><a href="../data/meeting_minutes/aprc/44th_APRC_minutes.pdf" target="_blank" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Download</a></td>
                      </tr>
                      <tr class="even pointer">
                        <td class=" ">43rd APRC minutes</td>
                        <td class=" last" width="10%"><a href="../data/meeting_minutes/aprc/43rd_APRC_minutes.pdf" target="_blank" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Download</a></td>
                      </tr>
                      <tr class="even pointer">
                        <td class=" ">42nd APRC minutes</td>
                        <td class=" last" width="10%"><a href="../data/meeting_minutes/aprc/42nd_APRC_minutes.pdf" target="_blank" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Download</a></td>
                      </tr>
                      <tr class="even pointer">
                        <td class=" ">41st APRC minutes</td>
                        <td class=" last" width="10%"><a href="../data/meeting_minutes/aprc/41st_APRC_minutes.pdf" target="_blank" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Download</a></td>
                      </tr>
                      <tr class="even pointer">
                        <td class=" ">40th APRC minutes</td>
                        <td class=" last" width="10%"><a href="../data/meeting_minutes/aprc/40th_APRC_minutes.pdf" target="_blank" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Download</a></td>
                      </tr>
                      <tr class="even pointer">
                        <td class=" ">39th APRC minutes</td>
                        <td class=" last" width="10%"><a href="../data/meeting_minutes/aprc/39th_APRC_minutes.pdf" target="_blank" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Download</a></td>
                      </tr>
                    </tbody>
                  </table>
                  <a href="<?php echo $this->url('index') ?>"><button type="button" class="btn btn-primary">Home</button></a>
             </div>
          </div>
        </div> 
     </div>
   </div>
 </div>
</div>
