<?php
 $title = 'Programmes and Quality Committee Meeting Information';
 $this->headTitle($title);

?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <table id="datatable" class="table table-striped jambo_table table-bordered">
                    <thead>
                      <tr class="headings">
                        <th class="column-title">Programmes and Quality Committee Meeting Minutes</th>
                        <th class="column-title">Action</th>
                      </tr>
                    </thead>  
                    <tbody>
			<tr class="even pointer">
                        <td class=" ">56th PQC Minutes</td>
                        <td class=" last" width="10%"><a href="../data/meeting_minutes/pqc/56th_PQC_minutes.pdf" target="_blank" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Download</a></td>
                      </tr>

                      <tr class="even pointer">
                        <td class=" ">55th PQC Minutes</td>
                        <td class=" last" width="10%"><a href="../data/meeting_minutes/pqc/55th_PQC_minutes.pdf" target="_blank" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Download</a></td>
                      </tr>
                      <tr class="even pointer">
                        <td class=" ">54th PQC Minutes</td>
                        <td class=" last" width="10%"><a href="../data/meeting_minutes/pqc/54th_PQC_minutes.pdf" target="_blank" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Download</a></td>
                      </tr>
                      <tr class="even pointer">
                        <td class=" ">53rd PQC Minutes</td>
                        <td class=" last" width="10%"><a href="../data/meeting_minutes/pqc/53rd_PQC_minutes.pdf" target="_blank" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Download</a></td>
                      </tr>
                      <tr class="even pointer">
                        <td class=" ">52nd PQC Minutes</td>
                        <td class=" last" width="10%"><a href="../data/meeting_minutes/pqc/52nd_PQC_minutes.pdf" target="_blank" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Download</a></td>
                      </tr>
                      <tr class="even pointer">
                        <td class=" ">51st PQC Minutes</td>
                        <td class=" last" width="10%"><a href="../data/meeting_minutes/pqc/51st_PQC_minutes.pdf" target="_blank" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Download</a></td>
                      </tr>
                      <tr class="even pointer">
                        <td class=" ">50th PQC Minutes</td>
                        <td class=" last" width="10%"><a href="../data/meeting_minutes/pqc/50th_PQC_minutes.pdf" target="_blank" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Download</a></td>
                      </tr>
                      <tr class="even pointer">
                        <td class=" ">49th PQC Minutes</td>
                        <td class=" last" width="10%"><a href="../data/meeting_minutes/pqc/49th_PQC_minutes.pdf" target="_blank" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Download</a></td>
                      </tr>
                      <tr class="even pointer">
                        <td class=" ">48th PQC Minutes</td>
                        <td class=" last" width="10%"><a href="../data/meeting_minutes/pqc/48th_PQC_minutes.pdf" target="_blank" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Download</a></td>
                      </tr>
                      <tr class="even pointer">
                        <td class=" ">46 & 47th PQC Minutes</td>
                        <td class=" last" width="10%"><a href="../data/meeting_minutes/pqc/46-47-PQC-Minutes.pdf" target="_blank" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Download</a></td>
                      </tr>
                      <tr class="even pointer">
                        <td class=" ">46th PQC Minutes</td>
                        <td class=" last" width="10%"><a href="../data/meeting_minutes/pqc/46th_PQC_minutes.pdf" target="_blank" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Download</a></td>
                      </tr>
                      <tr class="even pointer">
                        <td class=" ">45th PQC Minutes</td>
                        <td class=" last" width="10%"><a href="../data/meeting_minutes/pqc/45th_PQC_minutes.pdf" target="_blank" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Download</a></td>
                      </tr>

                      <tr class="even pointer">
                        <td class=" ">44th PQC Minutes</td>
                        <td class=" last" width="10%"><a href="../data/meeting_minutes/pqc/44th_PQC_minutes.pdf" target="_blank" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Download</a></td>
                      </tr>

                    </tbody>
                  </table>
                  <a href="<?php echo $this->url('index') ?>"><button type="button" class="btn btn-primary">Home</button></a>
             </div>
          </div>
        </div> 
     </div>
   </div>
 </div>
</div>
