<?php
 $title = 'RUB-IMS Job Portal Information/Help';
 $this->headTitle($title);
?>
<div class="right_col" role="main">
  <div class="">
    <div class="col-md-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2><?php echo $this->escapeHtml($title); ?></h2>
          <div class="clearfix"></div>
        </div>
        <h2><a id="Top"></a></h2>
        <div class="x_content">
          <nav class="navbar navbar-default">
            <div class="container-fluid">
              <ul class="nav navbar-nav">
                <li class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#">Job Portal
                  <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="#JobPortalDashboard">Dashboard</a></li>
                    <li><a href="#JobPortalPersonalDetail">Presonal Detail</a></li>
                    <li><a href="#JobPortalEducationDetail">Education Detail</a></li>
                    <li><a href="#JobPortalMarkDetail">Marks Detail</a></li>
                    <li><a href="#JobPortalTrainingDetail">Training Detail</a></li>
                    <li><a href="#JobPortalEmploymentDetail">Employment Detail</a></li>
                    <li><a href="#JobPortalCommitteeDetail">Committee Services Detail</a></li>
                    <li><a href="#JobPortalLanguageDetail">Language Detail</a></li>
                    <li><a href="#JobPortalPublicationDetail">Publication Detail</a></li>
                    <li><a href="#JobPortalReferenceDetail">Reference Detail</a></li>
                  </ul>
                </li>
                <li class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#">Recruitment
                  <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="#RecruitmentListVacancy">List Vacancy</a></li>
                    <li><a href="#RecruitmentApplicationStatus">Application Status</a></li>
                  </ul>
                </li>
              </ul>
            </div>
          </nav>
        </div>
      </div> 
    </div>
<!-- Introduction  -->
    <div class="col-md-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <?php
           $title = 'Royal University of Bhutan - Information Management System - Job Portal';
           $this->headTitle($title);
          ?>
          <h1><?php echo $this->escapeHtml($title); ?></h1>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <h3>Background</h3>
          <p>The Royal University of Bhutan is founded on a distributed model with its constituent Colleges scattered across the country. The University has been granted autonomy for the management of human and financial resources. In order to function seamlessly, the University is required to embark on technology breaking the geographical barrier. Integrated software that is fully automated and web-based has become crucial for the University to support its administration and management across the colleges.</p>
          <p>The RUB Information Management System (RUB IMS) Job Portal is a solution for providing Job Applicant with highly effective tools to help them support in maintaining the profile and degital application to apply to RUB vacancy.</p>
          <p>RUB-IMS Job Protal is primarily an initiative to replace the University’s Recruitment Systems, which are operated manually, with a new integrated digital system. </p>
          Following are the list of the constituent Colleges
          <ul>
          <li>College of Natural Resources, Lobese, Punakha</li>
          <li>College of Science and Technology, Rinchending, Chukha</li>
          <li>Gedu College of Business Studies, Gedu, Chukha</li>
          <li>Gyelpozhing College of Information Technology</li>
          <li>Colege of Language and Culture Studies, Taktse, Trongsa</li>
          <li>Jigme Namgyel Engineering College, Dewathang, Samdrup Jongkhar</li>
          <li>Paro College of Education, Paro</li>
          <li>Samtse College of Education, Samtse</li>
          <li>Sherubtse College, Kanglung, Trashigang</li>
          </ul>

          <h3>Objectives</h3>
          <p>The general objectives of the job portal system are to ensure effective and efficient service delivery and to enhance governance by way of ensuring transparency, accountability and informed decision-making processes through reliable and timely provision of information.</p>
          More specifically the RUB-IMS Job Portal is expected:
          <ul>
          <li>To encourage and maintain efficient and reliable job applicant portal.</li>
          <li>To faster processing of application and job application submission degitally.</li>
          <li>To process and provide reliable and timely data to the Human Resources Devision/Section for effective operation and service delivery. </li>
          <li>To maintain up-to-date and systemic records regarding the job applicant and vacancy list.</li>
          <li>Improve the usage of Information Communication Technology systems in recruitment and administrative processes.</li>
          <li>Web based System managed centrally to avoid duplication of efforts and to ensure efficiency.</li>
          <li>To ensure availability of Real-time and reliable Information at all levels. </li>
          <li>Consistent & highly Secured System.</li>
          <li>Ensures Better Coordination and Workflow Between Job Applicant and Recruitment Agency</li>
          <li>Faster and Automatic Report Generation. </li>
          <li>Helps in Reducing Paperwork, Manual Filing and Record Keeping.</li>
          </ul>
          <div class="col-md-12 bg-light text-right">
            <a href="#Top"><button type="button" class="btn btn-primary">Top</button></a>
          </div>
          <h3>Important steps to follow for Recruitment Feature</h3>
          <ol>
            <li>Register as the Job Applicant in RUB-IMS.</li>
            <li>Login to the RUB-IMS using the username and password provided by the system.</li>
            <li>Fill up all the following details correctly before applying for job vacancy.
                <ul>
                  <li>Personal Details</li>
                  <li>Education Detail</li>
                  <li>Marks Detail</li>
                  <li>Training Detail</li>
                  <li>Employment Detail</li>
                  <li>Committee Services Detail</li>
                  <li>Language Detail</li>
                  <li>Publication Detail</li>
                  <li>Reference Detail</li>
                </ul>
            </li>
            <li>Crosscheck all the details once again.</li>
            <li>Now go to Human Resources -> Recruitment -> List Job Vacancy.</li>
            <li>Review the list job Vcancy announced.</li>
            <li>Click on the Apply button on the relevant vacancy.</li>
            <li>Once again crosscheck detail information displayed and make changes if required.</li>
            <li>Upload the required and relevant document such as Security Clearance, NOC, ect.</li>
            <li>After crosschecking all the detail please click on the apply button.</li>
            <li>After applying you can time and again check the status of the job application status by clicking on the 
              <br>Human Resources -> Recruitment -> Individual Job Applicant Status.</li>

          </ol>
          <div class="col-md-12 bg-light text-right">
            <a href="#Top"><button type="button" class="btn btn-primary">Top</button></a>
          </div>
        </div>
      </div> 
    </div>
<!-- Job Portal  -->
    <div class="col-md-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <?php
           $title = 'Job Portal';
           $this->headTitle($title);
          ?>
          <h1><?php echo $this->escapeHtml($title); ?></h1>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <div class="container">
            <h3><a id="JobPortal">Job Portal</a></h3>
            <h3><a id="JobPortalDashboard">Dashboard</a></h3>
            <p>The upper part of the dashboard shows brief informtion on your personal information.</p>
            <p>The lower part of the dashboard are list of the information that need to be enterd before applying for job vacancy.</p>
            <h3><a id="JobPortalPersonalDetail">Presonal Detail</a></h3>
            <p>Please crosscheck the information displayed and click on the edit button to edit and add information.</p>
            <p>After filling up and uploading the cid and the profile picture, please click on the Update button to update the information.(Note: Profile picture should be in jpeg,jpg,png format.)</p>
            <h3><a id="JobPortalEducationDetail">Education Detail</a></h3>
            <p>Please fill up the education detail and click on the submit button. You can view and edit the education detail from the list.</p>
            <h3><a id="JobPortalMarkDetail">Marks Detail</a></h3>
            <h3><a id="JobPortalTrainingDetail">Training Detail</a></h3>
            <h3><a id="JobPortalEmploymentDetail">Employment Detail</a></h3>
            <h3><a id="JobPortalCommitteeDetail">Committee Services Detail</a></h3>
            <h3><a id="JobPortalLanguageDetail">Language Detail</a></h3>
            <h3><a id="JobPortalPublicationDetail">Publication Detail</a></h3>
            <h3><a id="JobPortalReferenceDetail">Reference Detail</a></h3>
            <div class="col-md-12 bg-light text-right">
              <a href="#Top"><button type="button" class="btn btn-primary">Top</button></a>
            </div>
          </div>
        </div> 
      </div>
    </div>
    <!-- Recrutment -->
    <div class="col-md-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <?php
           $title = 'Recruitment';
           $this->headTitle($title);
          ?>
          <h1><?php echo $this->escapeHtml($title); ?></h1>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <div class="container">
            <h3><a id="JobPortal">Recruitment</a></h3>
            <h3><a id="RecruitmentListVacancy">List Vacancy</a></h3>
            <h3><a id="RecruitmentApplicationStatus">Application Status</a></h3>
            <div class="col-md-12 bg-light text-right">
              <a href="#Top"><button type="button" class="btn btn-primary">Top</button></a>
            </div>
          </div>
        </div> 
      </div>
    </div>
  </div>
</div>