<h3><a id="HRMPresentIssues">Present System & Issues</a></h3>
<h4>Present System</h4>
<ul>
	<li>RUB at present does not have a system to store and manage the information of the employees. </li>
	<li>The details are managed by the respective organization and whenever the Office of the Vice Chancellor requires the information the Human Resource Section compiles manually. </li>
	<li>The Present system used are very basic excel sheets and the decision for appraisal of assigning next task are not properly projected.</li>
</ul>
<h4>Issues</h4>
<ul>
	<li>The University cannot get information on staff or overall statistics in stipulated period.</li>
	<li>It takes lot of time and energy in gathering staff information from the colleges.</li>
	<li>The staff information also keeps changing due to lack of proper record keeping system in the University.</li>
	<li>Updating of staff information is resource and time intensive, as colleges need to be bothered quite often to provide information and making them work time and again to validate the information.</li>
	<li>The weak record keeping system does not allow the University to make informed decisions as the University is not able to generate statistics and records timely to support in the decision making processes. </li>
	<li>There is danger of losing and mixing files in some cases when record is maintained manually.</li>
	<li>Overall HR administration is difficult when information of staff is not maintained systematically. Thus, there has been lack of information on many employees.</li>
</ul>
<h3><a id="HRPlanning">HR Planning</a></h3>
<p>
HR Planning module includes    <strong>HRD Planning &amp; HRM Planning</strong>. In this module the
    HRO/ADM should insert and update the particular sub module information into
    the system after review all the HRD plan.
</p>
<p>
    <strong>HRD Planning</strong>
</p>
<p>
    <strong>HRD Proposal</strong>
</p>
<p>
    <em>OVC, HRD will set the date for HR development proposal. </em>
    <img
        width="100%"
        src="../data/user_manual/HR-Planning/clip_image001.png"
        
    />
</p>
<p align="center">
    <em>(Fig. HRD &amp; HRM proposal date activation)</em>
</p>
<p>
    Once the date is activated individual college HRD can access this menu and
    HRD can put up the proposal using this form and submit it.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image003.png"
        alt="hrd proposal.PNG"
    />
</p>
<p align="center">
    <em>(Fig. HRD proposal form)</em>
</p>
<p>
    <strong>HRD Plan Approved List</strong>
</p>
<p>
    Individual college HRD can view the entire approved list once the HRD, OVC
    approved the proposal.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image005.png"
        alt="hrd approved.PNG"
    />
</p>
<p align="center">
    <em>(Fig. HRD Approved List)</em>
</p>
<p>
    <strong>HRM Planning</strong>
</p>
<p>
    <strong>Work Force Proposal</strong>
</p>
<p>
    OVC, HRD will set the date for HR work force proposal and individual
    college HRD can access this menu. Once the date is activated college HRD
    can put up the proposal using this form based on the requirement of the
    college, save and submit it.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image007.png"
        alt="hrm proposal form.PNG"
    />
</p>
<p align="center">
    <em>(Fig. HRM proposal form)</em>
</p>
<p>
    <strong></strong>
</p>
<p>
    <strong></strong>
</p>
<p>
    <strong></strong>
</p>
<p>
    <strong></strong>
</p>
<p>
    <strong></strong>
</p>
<p>
    <strong>Work Force Approved List</strong>
</p>
<p>
    Individual college HRD can view the entire approved list after the review
    by HRD, OVC and approved the proposal.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image009.png"
        alt="hrmapproved.PNG"
    />
</p>
<p align="center">
    <em>(Fig. HRM work force approved list)</em>
</p>
<p>
    <strong>Staff Life Cycle</strong>
</p>
<p>
Staff Lifecycle module includes    <strong>Transfer, Promotion and Separation</strong> from service. In this
    module the HRO/ADM should insert and update the particular sub module
    information into the system when a decision is taken on a particular
    employee.
</p>
<p>
    <strong>Transfer</strong>
</p>
<p>
    <strong>Apply Transfer</strong>
</p>
<p>
    If a staff wants to apply for a transfer, the user has to apply by clicking
    on the Apply Transfer to fill up forms and submit.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image011.png"
        alt="transfer.PNG"
    />
</p>
<p>
    <em>(Fig. Apply transfer form) </em>
</p>
<p>
    <strong>From and To OVC/College Approval</strong>
</p>
<p>
    The OVC-HRO/College-HRO will see a list of transfer proposal by clicking on
    the <strong>From Org/College Approval </strong>menu. The
    OVC-HRO/College-HRO can take action by approving or rejecting upon approval
    from the management by clicking on the view button.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image013.png"
    />
</p>
<p align="center">
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image015.png"
        alt="transfer_request_to.PNG"
    />
    (Fig. Transfer request from organization)
</p>
<p align="center">
    <em>(Fig. List of Transfer request to organization)</em>
</p>
<p>
    <strong>Transfer Application Status</strong>
</p>
<p>
    The OVC-HRO/College-HRO can see the transfer proposal status by clicking on
    the Transfer Application Status
</p>
<p>
    <img
       width="100%"
        src="../data/user_manual/hr-planning/clip_image017.png"
    />
</p>
<p align="center">
    <em>(Fig. Transfer Application Status)</em>
</p>
<p>
    <strong>Approved Transfers</strong>
</p>
<p>
    Once the transfer proposal is approved by both the outgoing and coming
    organization the OVC-HRO can view by clicking on the Approved Transfer menu
    and update accordingly.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image019.png"
        alt="tansfer list by both org.png"
    />
</p>
<p align="center">
    <em>(Fig. List of Approved transfer proposal</em>
    
    <em>)</em>
</p>

    <em></em>
</p>
<p>
    <em>
        Now the OVC-HRO can click on the Update button to transfer the staff to
        the approved location after the approval from the management.
    </em>
</p>
<p>
    <em>
        <img
            width="100%"
            src="../data/user_manual/hr-planning/clip_image023.png"
            alt="update detail.png"
        />
    </em>
    <em></em>
</p>
<p align="center">
    <em>(Fig. Update detail of transferred application)</em>
</p>
<p>
    <strong>My Transfer Status</strong>
</p>
<p>
    The transfer applicant can view their status of transfer application.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image025.png"
        alt="mytransferstatus.PNG"
    />
</p>
<p align="center">
    (Fig. Transfer status)
</p>
<p>
    <strong>Transfer Staff</strong>
</p>
<p>
    This menu is for organization (OVC-HRO/ADM) to transfer the staffs to other
    department or agency.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image027.png"
        alt="transferstaff.png"
    />
</p>
<p align="center">
    <em>(Fig. Staff transfers detail)</em>
</p>
<p>
    HRO/ADM can click to update staffs new organization details and submit it.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image029.png"
        alt="stafftransferupdate.png"
    />
</p>
<p align="center">
    <em>(Fig. Update details of transfer staff)</em>
</p>
<p>
    <strong>Transfer Department</strong>
</p>
<p>
    This menu is for transferring staffs from one department to other, click
    search button (1) and type staff ID or name (2), then click to update to
    insert the new department details and submit it.
</p>
<p>
    <img
       width="100%"
        src="../data/user_manual/hr-planning/clip_image031.png"
        alt="departmenttransfer.png"
    />
</p>
<p align="center">
    (Fig. Staff update department)
</p>
<p align="center">
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image033.png"
        alt="updatenewdepartment.png"
    />
</p>
<p align="center">
    <em>(Fig. New department of staff form)</em>
</p>
<p>
    <strong></strong>
</p>
<p>
    <strong></strong>
</p>
<p>
    <strong></strong>
</p>
<p>
    <strong></strong>
</p>
<p>
    <strong></strong>
</p>
<p>
    <strong></strong>
</p>
<p>
    <strong></strong>
</p>
<p>
    <strong></strong>
</p>
<p>
    <strong></strong>
</p>
<p>
    <strong></strong>
</p>
<p>
    <strong>Promotion.</strong>
</p>
<p>
    Under the promotion category the employee will fill in the promotion form
    and apply for promotion. Now based on HRC the particular HRO of the
    colleges/OVC should update the system as per the HRC. The HRO/ADM of
    colleges/OVC will have the only right to update the prompted information of
    the employee into the system and uploading of order in the system.
</p>
<p>
    <strong>Apply Promotion </strong>
</p>
<p>
    To apply the promotion, individual employee will have to click on the Apply
    Promotion menu and fill up the required form and click on submit button.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image035.png"
        alt="applypormotion.png"
    />
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image037.png"
        alt="meritiouspromotion.PNG"
    />
</p>
<p align="center">
    <em>(Fig. Apply for promotion form)</em>
</p>
<p>
    <strong>Meritorious Promotion</strong>
    <em></em>
</p>
<p>
    If the employee is eligible and wish to apply for meritorious promotion
    then employee shall apply for meritorious promotion using this form.
</p>
<p>
    <img
		width="100%"
        src="../data/user_manual/hr-planning/clip_image039.png"
        alt="applym.PNG"
    />
</p>
<p align="center">
    <em>(Fig. Meritorious promotion Form)</em>
</p>
<p>
    <strong>Update Promoted Applications</strong>
</p>
<p>
    The OVC-HRO/College-HRO will have to click on the update promoted
    application to update the promoted detail.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image041.png"
        alt="promotionstatus.png"
    />
    
</p>
<p align="center">
    <em>(Fig. Promotion application update)</em>
</p>
<p>
    <strong>My Promotion Status</strong>
</p>
<p>
    The individual can view or track the application status using this menu.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image045.png"
        alt="mypromotion.PNG"
    />
</p>
<p align="center">
    <em>(Fig. Promotion status)</em>
</p>
<p>
    <strong>Promotion via open competition</strong>
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image047.png"
        alt="opencompetition.PNG"
    />
    This menu is for college or OVC HRO to update the candidate details for
    open competition, click search button (1) and type staff ID or name (2),
    then click to update detail to insert the candidate details and submit it.
</p>
<p align="center">
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image049.png"
        alt="opencomupdate.PNG"
    />
    <em>(Fig. Search staff to update promotion details)</em>
</p>
<p align="center">
    <em>(Fig. Update promotion details of staff for open competition form)</em>
</p>
<p>
    <strong></strong>
</p>
<p>
    <strong>Separation</strong>
</p>
<p>
    <strong>Apply Resignation</strong>
</p>
<p>
    If the employee wants to resign then employee shall apply for separation by
    clicking on the separation menu.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image051.jpg"
    />
</p>
<p align="center">
    <em>(Fig. Apply Resignation form)</em>
</p>
<p>
    <strong>Resignation Approval</strong>
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image053.png"
    />
    The OVC /College-HRO should click on the Resignation approval menu to
    approve or reject the resignation application.
</p>
<p>
    <em>(Fig. Resignation Approval List)</em>
</p>
<p>
    <strong>Dues Records</strong>
</p>
<p>
    Once the resignation approval is reviewed then OVC/College-HRO can check
    the status of the no due clearance of the approved staff.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image055.png"
    />
</p>
<p align="center">
    <em>(Fig. Resignation Approval List)</em>
</p>
<p>
    <strong></strong>
</p>
<p>
    <strong>My Resignation Status</strong>
</p>
<p>
    The user can view the resignation application status by using this menu.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image057.png"
        alt="mysperation status.PNG"
    />
</p>
<p align="center">
    <em>(Fig. Resignation Status)</em>
</p>
<p>
    <strong>Add Compulsory Separation</strong>
</p>
<p>
    This menu is for college or OVC HRO to update the staff details for
    compulsory separation, click search button (1) and type staff ID or name
    (2) and then click to record to insert the staff details and submit it.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image059.png"
        alt="compulsorysep.PNG"
    />
</p>
<p align="center">
    (Fig. Staff list)
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image061.png"
        alt="compulsoryrec.PNG"
    />
</p>
<p align="center">
    <em>(Fig. Record Resigned Staff Form)</em>
</p>
<p>
    <strong>Issue Relieving Order</strong>
</p>
<p>
    Once all relevant departments issued the clearance, the college or OVC HRO
    can issue a relieving order.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image063.png"
        alt="issuerecord.PNG"
    />
</p>
<p align="center">
    <em>(Fig. Resignation record issuance)</em>
</p>
<p>
    <strong>Separation Record List</strong>
</p>
<p>
    This menu is to view all the list of separation record for college or OVC
    HRO.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image065.png"
        alt="separationlist.PNG"
    />
</p>
<p align="center">
    <em>(Fig. Resignation approval list) </em>
</p>

<h3><a id="HRMRecruitment">Recruitment</a></h3>
<h4>Important steps to follow for Recruitment Feature</h4>
<ol>
	<li>Resepective OVC/College add new staff into the RUB-IMS</li>
	<li>OVC HR Divison generate Staff ID</li>
	<li>Resepective OVC/College Reguralize Staff after provision period</li>
	<li>Resepective OVC/College add new staff from Add Missing staff if the staff is not eligible for RUB Staff ID.</li>
</ol>
<p>
    <strong>1. </strong>
    <strong>HR Recruitment</strong>
</p>
<p>
    <strong>a. </strong>
    <strong>Vacancy Announcement</strong>
</p>
<p>
    Based on the workforce approved list the individual OVC-HRO and College-HRO
    can announce the vacancy by clicking on the planned and Ad-hoc menu.
</p>
<p>
    i. <strong>Planned</strong>
</p>
<p>
    As per the planned HRM, the vacancies can be announced.
</p>
<p>
    <strong> ii. </strong>
    <strong>Ad-hoc</strong>
</p>
<p>
    If the vacancies are not listed in HR plan and needs to add based on
    Ad-hoc.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/recruitment/clip_image001.png"
    />
</p>
<p align="center">
    <em>Figure 2.1: Job Vacancy Details</em>
</p>
<strong>
    <br clear="all"/>
</strong>
<p>
    <strong></strong>
</p>
<p>
    <strong>Add New Staff</strong>
</p>
<p>
    Add new staff without having to go through the vacancy announcement process
    or if staff doesn’t have Staff ID.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/recruitment/clip_image003.png"
    />
</p>
<p align="center">
    <em>Figure 2.2: Add New Staff</em>
</p>
<p>
    <strong>b. </strong>
    <strong>Regularize Staff</strong>
</p>
<p>
    If staff completes probation period and need to regularize. Search the
    staff and update.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/recruitment/clip_image005.png"
    />
</p>
<p align="center">
    <em>Figure 2.3: Regularize Staff</em>
</p>
<p>
    <strong>c. </strong>
    <strong>List Job Vacancies </strong>
</p>
<p>
    RUB staff and job seeker can have access to the vacancy announcement list
    by clicking on the List Job Vacancies. The applicant need to get registered
    as Job Applicant, update the required information and apply for vacancy
    announced.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/recruitment/clip_image007.png"
    />
</p>
<p align="center">
    <em>
        Figure 2.4: Vacancy Announcement Detail Click on the Apply to apply of
        the vacancy announced.
    </em>
</p>
<h4>
    d. Job Applicant Status &amp; Recruitment
</h4>
<p>
    Individual OVC-HRO and College-HRO will have access to the list of
    applicant details and take action by clicking on the
    View/Shortlist/Select/Reject button.
</p>
<p align="right">
    <img
        width="100%"
        src="../data/user_manual/recruitment/clip_image009.png"
    />
</p>
<p align="center">
    <em>Figure 2.5: Job Applicant Status Update</em>
</p>
<h4>
    d. Generate Staff ID
</h4>
<p>
    When applicant is selected, HR can generate staff ID.
</p>
<p>
    <strong>e. </strong>
    <strong>View Applicant Marks </strong>
</p>
<p>
    HR can view applicant’s marks and shortlist.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/recruitment/clip_image011.png"
    />
</p>
<p>
    <em>Figure 2.5a: Applicant’s Marks</em>
    <strong></strong>
</p>
<p>
    <strong></strong>
</p>
<strong>
    <br clear="all"/>
</strong>
<p>
    <strong></strong>
</p>
<p>
    <strong>2. </strong>
    <strong>Job Registration (Applicant Side)</strong>
</p>
<p>
    <strong>a. </strong>
    <strong>Register Job Applicant</strong>
</p>
<p>
    In order apply for the jobs at RUB, the applicants has to register first as
    shown, click <strong>Register Job Applicant</strong>.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/recruitment/clip_image013.png"
    />
</p>
<p>
    <em>Figure 2.6: Job Applicant Register Login</em>
</p>
<p>
    The applicants have to fill up the basic detials shown in the Figure 2.7.
    The password will be send to the email entered.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/recruitment/clip_image015.png"
    />
</p>
<p>
    <em>Figure 2.7: Job Applicant Registration</em>
</p>
<p>
    After the registration, the applicant will logout automatically. The
    applicant has to login again and has to change the password.
</p>
<p>
    After successful login, the applicant should submit all the details
    (personal details, education details, etc.) under the Job Portal as shown
    in the figure 2.8
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/recruitment/clip_image017.png"
    />
</p>
<p align="center">
    <em>Figure 2.8: Job Applicant Details</em>
</p>
<p>
    <strong>b. </strong>
    <strong>Job Application</strong>
</p>
<p>
    In order to apply for the job vacancies, the applicant has to click on the
    List Job Vacancies and apply for respective vacancies.
</p>
<p>
    <img
       width="100%"
        src="../data/user_manual/recruitment/clip_image019.png"
    />
</p>
<p align="center">
    <em>Figure 2.9: Apply Job Vacancies</em>
</p>
<br clear="all"/>
<p>
    When applying for the post, the applicant has to further upload mandatory
    documents as specified in the figure 2.10 on top of the details provided.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/recruitment/clip_image021.png"
    />
</p>
<p align="center">
    <em>Figure 2.10: Application Documents</em>
</p>
<p>
    <strong></strong>
</p>
<p>
    <strong>c. </strong>
    <strong>Job Status </strong>
</p>
<p>
    The applicant can view the status of individual applicants as shown in
    figure 2.11.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/recruitment/clip_image023.png"
    />
</p>
<p align="center">
    <em>Figure 2.11: Applicant Status</em>
</p>
<br clear="all"/>
<h3><a id="HRMAdministration">HR Administration</a></h3>
<p>
    LEAVE
</p>
<p>
    An online leave application portal enables the applicant to apply online
    and also enable the approving authority to approve online, and the approval
    conveyed back to the applicant and HRO, simultaneously. This leave
    information (Casual Leave, Earned Leave, Medical Leave, Maternity/Paternity
    Leave, Bereavement leave, Study Leave, extraordinary leave etc.) should be
    updated and kept online by HRO for information of all. Ideally, the online
    application portal should automatically remind the applicants and HRO on
    the status of leave (leave availed and leave balance).
</p>
<h2>
    Steps to follow while applying leave
</h2>
<p>
    · All staff will have to click on the Apply Leave to avail leave. The staff
    will get a list of type of leave available for the staff and based on the
    leave that user wants to take, the staff should click on the apply button.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-administration/clip_image001.png"
    />
</p>
<p>
    Figure 1-Leave status
</p>
<p>
    · Apply leave accordingly
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-administration/clip_image003.png"
    />
</p>
<p>
    Figure 2 - Leave status apply
</p>
<p>
· Submit the form as per the requirement –<em>Note: Enter the number of actual leave days in </em>    <strong>Total No. of Days: * rather</strong> than the calendar days.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-administration/clip_image005.png"
    />
</p>
<p>
    Figure 3 – Employee Leave Application
</p>
<p>
    · Any staff can apply leave on behalf of others who are not computer
    literate. Enter the appropriate data in the form.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-administration/clip_image007.png"
    />
</p>
<p>
    Figure 4-Apply on behalf Leave
</p>
<h2>
    Steps to follow while approving leave
</h2>
<p>
    · Leave approval shall be notified to the concern official as per given in
    the leave status page
</p>
<p>
    · Supervisor shall approve leave from the dashboard or from the menu under
    HR-Administration
</p>
<p>
    · Staff can view the pending, approved or rejected leave forms
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-administration/clip_image009.png"
    />
</p>
<p>
    Figure 5 - Employee Leave Approval
</p>
<p>
    · Approve or Reject leave
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-administration/clip_image011.png"
    />
</p>
<p>
    Figure 6-Employee Leave Status -1
</p>
<h2>
    Cancel and Staff Leave Detail list
</h2>
<p>
    · HRO shall cancel the approved leave when the staff has not used the total
    number of applied leave days.
</p>
<p>
    · HRO shall maintain the correct Earned and Casual leave
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-administration/clip_image013.png"
    />
</p>
<p>
    Figure 7-Employee Leave Detail lists
</p>
<h1>
    LEAVE ENCASHMENT
</h1>
<p>
    Any staff who have earned leave balance of 30 can apply for the leave
    encashment once in a year.
</p>
<h2>
    Applying for Leave Encashment
</h2>
<p>
    · Staff need to submit the form to apply for leave encashment.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-administration/clip_image015.png"
    />
</p>
<p>
    Figure 8-Employee leave encashment application
</p>
<h2>
    Leave Encashment Approval
</h2>
<p>
    · HRO/ADM assistant shall approve or reject the leave encashment form
    submitted by the staff.
</p>
<p>
    · HRO/ADM assistant can also view the past approved or rejected forms in
    the same page.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-administration/clip_image017.png"
    />
</p>
<p>
    Figure 9-Leave Encashment Lists
</p>
<h1>
    STAFF TASK
</h1>
<p>
    Human Resource Management Staff Task is an organizational function that
    deals with issues such as keeping record of the individual staff activities
    based on the APA/Task/Project category set on daily, weekly and timely
    manner. The record once mentioned in IMS can be retrieved or reviewed
    whenever required. It can be used during the Work from Home, Work from
    Office and Work during Travel. This can also be used by staff who feels
    that their activities need to be recorded for future reference.
</p>
<h2>
    Add/Edit Task/Project Category
</h2>
<p>
    Any staff can add the Task/Project category. By adding the Task/Project
    category the system will keep records of the all the individual staff
    activities grouped into defined the Task/Project category. The form
    includes the 3 field that need to be added.
</p>
<p>
    · Staff need to enter the proper details in the form and the current status
    of the work.
</p>
<p>
    · After adding the categories, staff can also edit to make any changes.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-administration/clip_image019.png"
    />
</p>
<p>
    Figure 10 - Task/Project Categories
</p>
<h2>
    Add/Edit Self Activities
</h2>
<p>
    Staff can add the self-activities based on the Task/Project category. The
    staff can add the activities on daily or in interval bases. By adding the
    activities, the system will keep records of the all the individual staff
    activities and can be reviewed whenever required. The form includes the 9
    field but all not compulsory.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-administration/clip_image021.png"
    />
</p>
<p>
    Figure 11-Self Activities
</p>
<h2>
    Add/Edit Other Staff Activities
</h2>
<p>
    If the staff feels that other staff have helped them then they can also add
    the activities for the other staff under the same Task/Project Categories.
</p>
<p>
    For this staff will have to search the other staff either by first name or
    by staff id or just click on the search button to get whole staff list.
    Then the list of staff will be displayed in the table below and then click
    on the Add record button to add the activities.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-administration/clip_image023.png"
    />
</p>
<p>
    Figure 12-Add other staff Activities
</p>
<p>
    Once after clicking on the Add Record, similar form to add self-activities
    will be displayed. Staff then needs to add details of the other staff.
</p>
<h2>
    View Staff Task Record
</h2>
<p>
    Supervisor/head of the organization can view the detail activities of the
    staff. The supervisor will have to click on the View button to view the
    details of the staff activity.
    <img
        width="100%"
        src="../data/user_manual/hr-administration/clip_image025.png"
    />
</p>
<p>
    Figure 13-View employee task Record
</p>

<h3><a id="HRMDevelopment">HR Development</a></h3>
<h4>Important steps to follow for HR Development Feature</h4>
<ol>
	<li>HR Division/Section add Longterm/Shortterm Training Detail</li>
	<li>HR Division/Section Nominate the staff for the particular training</li>
	<li>Nominated staff apply for the particular training by uploading the required documents</li>
	<li>HR Divison/Section Issue releving order for the training</li>
	<li>Individual staff report to HR with report.</li>
</ol>
<p>
    HR Development
</p>
<p>
    HR Development Human Resource Development is the frameworks for helping
    employees develop their personal and organizational skills, knowledge and
    abilities, career development which contributes to the organizational
    performance. The database should have the details of all trainings availed
    by an employee during his/her tenure. It has feature to continuously update
    the status of the long-term study beginning from enrollment till the
    successful completion and generation of HRD report (individual and
    organizational).
</p>
<p>
    <strong>Add long term training details</strong>
</p>
<p>
    The OVC-HRO/College-HRO will have to add the training detail
</p>
<p>
    1. Go to HR Development menu
</p>
<p>
    2. Click Adhoc and fill up the details
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hrd/clip_image001.png"
    />
</p>
<p>
    3. After filling up the details click submit button
</p>
<p>
    <strong>Add short term training details</strong>
</p>
<p>
    The OVC-HRO/College-HRO will have to add the training detail.
</p>
<p>
    1. Go to HR Development menu
</p>
<p>
    2. Click Adhoc and fill up the details
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hrd/clip_image003.png"
    />
</p>
<p>
    <strong>Nominate staff for trainings</strong>
</p>
<p>
    Based on the approval from the management the OVC-HRO/College-HRO will
    nominate the staff for the training by searching the staff and clicking the
    particular staff and submit for nomination.
</p>
<p>
    1. Go to HR Development menu
</p>
<p>
    2. Click nominate staff for trainings
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hrd/clip_image005.png"
    />
</p>
<p>
    3. To search employee search by name or staff id and click nominate button.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hrd/clip_image007.png"
    />
</p>
<p>
    4. Then select the training and nomination evidence file approved by
    management and click submit button.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hrd/clip_image009.png"
    />
</p>
<p>
    <strong>Apply Trainings and Workshop</strong>
</p>
<p>
    Every Individual who has been nominated should apply for training by
    clicking on the Apply Training &amp; Workshop by submitting the documents.
    Once individual is nominated for training/workshop mail notification will
    be sent to individual university email.
</p>
<p>
    1. Under HR Development menu click apply trainings and workshop and click
    apply
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hrd/clip_image011.png"
    />
</p>
<p>
    2. Upload required training documents
</p>
<p>
    After clicking apply individual staff will be redirected to submit the
    required documents. Upload required documents and click submit
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hrd/clip_image013.png"
    />
</p>
<p>
    <strong>View Trainings &amp; Workshops Applications </strong>
</p>
<p>
    OVC-HRO/College-HRO can view the training nomination details with documents
    submitted or not
</p>
<p>
    1. Clik view training and workshop application and approve the final
    applicant by clicking on the check box. For instance if Tshering is
    selected click on check box and submit required documents and submit.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hrd/clip_image015.png"
    />
</p>
<p>
    <strong>Update Training Report</strong>
</p>
<p>
    OVC-HRO/College-HRO will update training report submitted by individual
    staffs.
</p>
<p>
    1. Click update training status and click training report
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hrd/clip_image017.png"
    />
</p>
<p>
    2. Update required form and documents submitted by individual staffs.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hrd/clip_image017.png"
    />
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hrd/clip_image019.png"
    />
</p>


<h3><a id="HRMLifecycle">HR Lifecycle</a></h3>
<h3>Important steps to follow for Separation Feature</h3>
<ol>
	<li>Individual Staff apply for resignation or HR add details of staff resigning</li>
	<li>HR Divison/Section Approve the resignation </li>
	<li>Relivant division/section issue no due clearance (Administrative division/section, Estate Section, Store Unit, Finance Section, Library Unit)</li>
	<li>HR Divison/Section Finally issue Releaving Order</li>
</ol>
<p>
    <strong>Staff Life Cycle</strong>
</p>
<p>
Staff Lifecycle module includes    <strong>Transfer, Promotion and Separation</strong> from service. In this
    module the HRO/ADM should insert and update the particular sub module
    information into the system when a decision is taken on a particular
    employee.
</p>
<p>
    <strong>Transfer</strong>
</p>
<p>
    <strong>Apply Transfer</strong>
</p>
<p>
    If a staff wants to apply for a transfer, the user has to apply by clicking
    on the Apply Transfer to fill up forms and submit.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image011.png"
        alt="transfer.PNG"
    />
</p>
<p>
    <em>(Fig. Apply transfer form) </em>
</p>
<p>
    <strong>From and To OVC/College Approval</strong>
</p>
<p>
    The OVC-HRO/College-HRO will see a list of transfer proposal by clicking on
    the <strong>From Org/College Approval </strong>menu. The
    OVC-HRO/College-HRO can take action by approving or rejecting upon approval
    from the management by clicking on the view button.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image013.png"
    />
</p>
<p align="center">
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image015.png"
        alt="transfer_request_to.PNG"
    />
    (Fig. Transfer request from organization)
</p>
<p align="center">
    <em>(Fig. List of Transfer request to organization)</em>
</p>
<p>
    <strong>Transfer Application Status</strong>
</p>
<p>
    The OVC-HRO/College-HRO can see the transfer proposal status by clicking on
    the Transfer Application Status
</p>
<p>
    <img
       width="100%"
        src="../data/user_manual/hr-planning/clip_image017.png"
    />
</p>
<p align="center">
    <em>(Fig. Transfer Application Status)</em>
</p>
<p>
    <strong>Approved Transfers</strong>
</p>
<p>
    Once the transfer proposal is approved by both the outgoing and coming
    organization the OVC-HRO can view by clicking on the Approved Transfer menu
    and update accordingly.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image019.png"
        alt="tansfer list by both org.png"
    />
</p>
<p align="center">
    <em>(Fig. List of Approved transfer proposal</em>
    
    <em>)</em>
</p>

    <em></em>
</p>
<p>
    <em>
        Now the OVC-HRO can click on the Update button to transfer the staff to
        the approved location after the approval from the management.
    </em>
</p>
<p>
    <em>
        <img
            width="100%"
            src="../data/user_manual/hr-planning/clip_image023.png"
            alt="update detail.png"
        />
    </em>
    <em></em>
</p>
<p align="center">
    <em>(Fig. Update detail of transferred application)</em>
</p>
<p>
    <strong>My Transfer Status</strong>
</p>
<p>
    The transfer applicant can view their status of transfer application.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image025.png"
        alt="mytransferstatus.PNG"
    />
</p>
<p align="center">
    (Fig. Transfer status)
</p>
<p>
    <strong>Transfer Staff</strong>
</p>
<p>
    This menu is for organization (OVC-HRO) to transfer the staffs to other
    department or agency.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image027.png"
        alt="transferstaff.png"
    />
</p>
<p align="center">
    <em>(Fig. Staff transfers detail)</em>
</p>
<p>
    HRO/ADM can click to update staffs’ new organization details and submit it.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image029.png"
        alt="stafftransferupdate.png"
    />
</p>
<p align="center">
    <em>(Fig. Update details of transfer staff)</em>
</p>
<p>
    <strong>Transfer Department</strong>
</p>
<p>
    This menu is for transferring staffs from one department to other, click
    search button (1) and type staff ID or name (2), then click to update to
    insert the new department details and submit it.
</p>
<p>
    <img
       width="100%"
        src="../data/user_manual/hr-planning/clip_image031.png"
        alt="departmenttransfer.png"
    />
</p>
<p align="center">
    (Fig. Staff update department)
</p>
<p align="center">
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image033.png"
        alt="updatenewdepartment.png"
    />
</p>
<p align="center">
    <em>(Fig. New department of staff form)</em>
</p>
<p>
    <strong></strong>
</p>
<p>
    <strong></strong>
</p>
<p>
    <strong></strong>
</p>
<p>
    <strong></strong>
</p>
<p>
    <strong></strong>
</p>
<p>
    <strong></strong>
</p>
<p>
    <strong></strong>
</p>
<p>
    <strong></strong>
</p>
<p>
    <strong></strong>
</p>
<p>
    <strong></strong>
</p>
<p>
    <strong>Promotion.</strong>
</p>
<p>
    Under the promotion category the employee will fill in the promotion form
    and apply for promotion. Now based on HRC the particular HRO of the
    colleges/OVC should update the system as per the HRC. The HRO/ADM of
    colleges/OVC will have the only right to update the prompted information of
    the employee into the system and uploading of order in the system.
</p>
<p>
    <strong>Apply Promotion </strong>
</p>
<p>
    To apply the promotion, individual employee will have to click on the Apply
    Promotion menu and fill up the required form and click on submit button.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image035.png"
        alt="applypormotion.png"
    />
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image037.png"
        alt="meritiouspromotion.PNG"
    />
</p>
<p align="center">
    <em>(Fig. Apply for promotion form)</em>
</p>
<p>
    <strong>Meritorious Promotion</strong>
    <em></em>
</p>
<p>
    If the employee is eligible and wish to apply for meritorious promotion
    then employee shall apply for meritorious promotion using this form.
</p>
<p>
    <img
		width="100%"
        src="../data/user_manual/hr-planning/clip_image039.png"
        alt="applym.PNG"
    />
</p>
<p align="center">
    <em>(Fig. Meritorious promotion Form)</em>
</p>
<p>
    <strong>Update Promoted Applications</strong>
</p>
<p>
    The OVC-HRO/College-HRO will have to click on the update promoted
    application to update the promoted detail.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image041.png"
        alt="promotionstatus.png"
    />
    
</p>
<p align="center">
    <em>(Fig. Promotion application update)</em>
</p>
<p>
    <strong>My Promotion Status</strong>
</p>
<p>
    The individual can view or track the application status using this menu.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image045.png"
        alt="mypromotion.PNG"
    />
</p>
<p align="center">
    <em>(Fig. Promotion status)</em>
</p>
<p>
    <strong>Promotion via open competition</strong>
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image047.png"
        alt="opencompetition.PNG"
    />
    This menu is for college or OVC HRO to update the candidate details for
    open competition, click search button (1) and type staff ID or name (2),
    then click to update detail to insert the candidate details and submit it.
</p>
<p align="center">
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image049.png"
        alt="opencomupdate.PNG"
    />
    <em>(Fig. Search staff to update promotion details)</em>
</p>
<p align="center">
    <em>(Fig. Update promotion details of staff for open competition form)</em>
</p>
<p>
    <strong></strong>
</p>
<p>
    <strong>Separation</strong>
</p>
<p>
    <strong>Apply Resignation</strong>
</p>
<p>
    If the employee wants to resign then employee shall apply for separation by
    clicking on the separation menu.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image051.jpg"
    />
</p>
<p align="center">
    <em>(Fig. Apply Resignation form)</em>
</p>
<p>
    <strong>Resignation Approval</strong>
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image053.png"
    />
    The OVC /College-HRO should click on the Resignation approval menu to
    approve or reject the resignation application.
</p>
<p>
    <em>(Fig. Resignation Approval List)</em>
</p>
<p>
    <strong>Dues Records</strong>
</p>
<p>
    Once the resignation approval is reviewed then OVC/College-HRO can check
    the status of the no due clearance of the approved staff.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image055.png"
    />
</p>
<p align="center">
    <em>(Fig. Resignation Approval List)</em>
</p>
<p>
    <strong></strong>
</p>
<p>
    <strong>My Resignation Status</strong>
</p>
<p>
    The user can view the resignation application status by using this menu.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image057.png"
        alt="mysperation status.PNG"
    />
</p>
<p align="center">
    <em>(Fig. Resignation Status)</em>
</p>
<p>
    <strong>Add Compulsory Separation</strong>
</p>
<p>
    This menu is for college or OVC HRO to update the staff details for
    compulsory separation, click search button (1) and type staff ID or name
    (2) and then click to record to insert the staff details and submit it.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image059.png"
        alt="compulsorysep.PNG"
    />
</p>
<p align="center">
    (Fig. Staff list)
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image061.png"
        alt="compulsoryrec.PNG"
    />
</p>
<p align="center">
    <em>(Fig. Record Resigned Staff Form)</em>
</p>
<p>
    <strong>Issue Relieving Order</strong>
</p>
<p>
    Once all relevant departments issued the clearance, the college or OVC HRO
    can issue a relieving order.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image063.png"
        alt="issuerecord.PNG"
    />
</p>
<p align="center">
    <em>(Fig. Resignation record issuance)</em>
</p>
<p>
    <strong>Separation Record List</strong>
</p>
<p>
    This menu is to view all the list of separation record for college or OVC
    HRO.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/hr-planning/clip_image065.png"
        alt="separationlist.PNG"
    />
</p>
<p align="center">
    <em>(Fig. Resignation approval list) </em>
</p>

<h3><a id="HRMPMS">PMS</a></h3>
<h3><a id="HRMStaffTour">Staff Tour</a></h3>
<p>
    Staff Tour
</p>
<p>
    Please add the Travel Authorization details prior to filling the Travel
    Details.
</p>
<p>
    1. Go to staff tour menu and click travel authorization. Fill up the
    details, click add &amp; next and add travel details
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/tour/clip_image001.png"
    />
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/tour/clip_image003.png"
    />
</p>
<p>
    <strong>Travel status</strong>
</p>
<p>
    Check the travel status for approval from the management
</p>
<p>
    1. Click Travel status
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/tour/clip_image005.png"
    />
</p>
<p>
    <strong>Travel Approval</strong>
</p>
<p>
    After individual staff apply for travel authorization concern authorized
    person has to check the travel details and approve/reject
</p>
<p>
    1. Click travel approval. Click view details and check the travel details
    and approve/reject
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/tour/clip_image007.png"
    />
</p>
<p>
    Travel order
</p>
<p>
    Check the travel order and view office order and other information.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/tour/clip_image009.png"
    />
    <br/>
    <br/>
</p>
<h3><a id="HRMOrganisationSetting">Organisation Setting</a></h3>
<h3><a id="HRMStaffManagement">Staff Management</a></h3>
<h1>
    Human Resources Management Staff Management Module
</h1>
<p>
    Human Resource Management Staff Management is a feature that deals with
    issues such as keeping record of the individual staff details. The record
    once mentioned in IMS can be a personal file in digital form and will be
    updated automatically after every activity.
</p>
<h2>
    <a name="_Toc51321940"></a>
    <a name="_Toc522440269">Add Missing Staff</a>
</h2>
<p>
    HR Division and Administrative Section will have the right to add the staff
    into the IMS. It is used if any staff is not listed in the IMS system. It
    can also be used for adding new staff such as contract, adjunct and GSS
    staff. As soon as the staff is added a user account will be created and
    staff can start using IMS.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/staff-management/clip_image001.png"
    />
</p>
<p>
    Figure 1-Add missing staff
</p>
<h2>
    <a name="_Toc51321941">Staff List</a>
</h2>
<p>
    This menu is used for searching staff and viewing staff profile. Staff have
    to click on the search button without filling up any fields to list all
    staff or filter search using first name or staff ID
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/staff-management/clip_image003.png"
    />
</p>
<p>
    Figure 2-Staff List
</p>
<p>
    Staff can view the staff profile by clicking on the View details on the
    list.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/staff-management/clip_image005.jpg"
    />
</p>
<p>
    Figure 3-Staff Profile
</p>
<p>
    <em></em>
</p>
<h2>
    <a name="_Toc51321943">Staff Profile Picture</a>
</h2>
<p>
    This form is used for adding profile picture of the staff. The HR Division
    and Administrative Section have the only right to add the profile picture.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/staff-management/clip_image007.jpg"
    />
</p>
<p>
    Figure 4-Add Staff Profile picture
</p>
<p>
    Once after searching the staff click on the upload profile picture, select
    the photo and click on the Add Profile Picture.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/staff-management/clip_image009.jpg"
    />
</p>
<p>
    Figure 5-Staff Profile Picture
</p>
<h2>
    <a name="_Toc51321944">Update Staff Details</a>
</h2>
<p>
    In case if there are any details which is not captured in the staff profile
    can be added form this form. Only HR Division and Administrative Section
    can update the staff details. Click on the Update Details of the particular
    staff that is required for updates.
</p>
<p>
    <em>
        <img
            width="100%"
            src="../data/user_manual/staff-management/clip_image010.jpg"
        />
    </em>
</p>
<p>
    Figure 6-Update Staff Detail list
</p>
<p>
    HR Division and Administrative Section need to enter the correct data into
    the fields to update the staff details. Select Update personal details or
    update permanent address to make changes
    <img
        width="100%"
        src="../data/user_manual/staff-management/clip_image012.jpg"
    />
</p>
<p>
    <em>Figure 1.9: Update Staff Details</em>
</p>
<h2>
    <a name="_Toc51321945">Staff Relation Details</a>
</h2>
<p>
    This form is for adding the family details of the particular staff. Enter
    the details and click add relation detail to update.
</p>
<p>
    <em>
        <img
            width="100%"
            src="../data/user_manual/staff-management/clip_image014.jpg"
        />
    </em>
</p>
<p>
    Figure 7-Staff Relation details
</p>
<h2>
    <a name="_Toc51321946">Staff Work Experience</a>
</h2>
<p>
    This form is to for adding staff past work experience. Add both RUB past
    work experience or NON RUB work experience if any. If the staff have worked
    in RUB but is not recorded into IMS can fill up the following form under
    ADD RUB Work Experience and upload the evidence file (office order) for
    future reference.
</p>
<p>
    <em>
        <img
            width="100%"
            src="../data/user_manual/staff-management/clip_image016.jpg"
        />
    </em>
</p>
<p>
    Figure 8-Staff Work Experience
</p>
<h2>
    <a name="_Toc51321947">Staff Education</a>
</h2>
<p>
    This form is used for adding the education details of the staff. Add
    education details and click on the Add Education button to update.
</p>
<p>
    <em>
        <img
            width="100%"
            src="../data/user_manual/staff-management/clip_image018.jpg"
        />
    </em>
</p>
<p>
    Figure 9-Staff Education
</p>
<h2>
    <a name="_Toc51321948">Staff Training</a>
</h2>
<p>
    This form is used for adding the training details of the staff. Add
    training details and click on the Add Training button to update.
</p>
<p>
    <em>
        <img
            width="100%"
            src="../data/user_manual/staff-management/clip_image020.jpg"
        />
    </em>
</p>
<p>
    Figure 10-Staff Training
</p>
<h2>
    <a name="_Toc51321949">Staff Publication</a>
</h2>
<p>
    This form is used for adding the publication details of the staff. Add the
    publication details and click on the Add Publication button to update.
</p>
<p>
    <em>
        <img
            width="100%"
            src="../data/user_manual/staff-management/clip_image022.jpg"
        />
    </em>
</p>
<p>
    Figure 11-Staff Publication
</p>
<h2>
    <a name="_Toc51321950">Staff Responsibilities</a>
</h2>
<p>
    This form is used for adding the responsibilities of the staff. Add the
    responsibilities and click on the Add Responsibilities button to update.
</p>
<p>
    <em>
        <img
            width="100%"
            src="../data/user_manual/staff-management/clip_image024.jpg"
        />
    </em>
</p>
<p>
    Figure 12-Staff Responsibilities
</p>
<h2>
    <a name="_Toc51321951">Staff Contributions</a>
</h2>
<p>
    This form is used for adding the contribution details of the staff. Add the
    contribution details and click on the Add Contribution button to update.
</p>
<p>
    <em>
        <img
            width="100%"
            src="../data/user_manual/staff-management/clip_image026.jpg"
        />
    </em>
</p>
<p>
    Figure 13-Staff Contributions
</p>
<h2>
    <a name="_Toc51321952">Staff Awards</a>
</h2>
<p>
    This form is used for adding the award details of the staff. Add the award
    details and click on the Add Award button to update.
</p>
<p>
    <em>
        <img
            width="100%"
            src="../data/user_manual/staff-management/clip_image028.jpg"
        />
    </em>
</p>
<p>
    Figure 14-Staff Awards
</p>
<h2>
    <a name="_Toc51321953">Staff Community Service</a>
</h2>
<p>
    This form is used for adding the community service of the staff. Add any
    Community service of the staff and click on the Add Community Service
    button to update.
</p>
<p>
    <em>
        <img
            width="100%"
            src="../data/user_manual/staff-management/clip_image030.jpg"
        />
    </em>
</p>
<p>
    Figure 15-Staff Community Service
</p>
<h2>
    <a name="_Toc51321954">Change Department</a>
</h2>
<p>
    If the is any mistake in staff department or the division of the staff, we
    can use this form to updated it.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/staff-management/clip_image032.jpg"
    />
</p>
<p>
    Figure 16-Change Department
</p>
<h2>
    <a name="_Toc51321955">Edit Current</a>
    Position
</h2>
<p>
    If the is any mistake in the position title or the position level of the
    staff, we can use this form to updated it.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/staff-management/clip_image034.jpg"
    />
</p>
<p>
    Figure 17-Edit Current Position
</p>
<br clear="all"/>

<h3><a id="HRMHRReports">HR Reports</a></h3>
<p>
    <strong>1. </strong>
    <strong>HR Reports </strong>
</p>
<p>
    The HR reports can be generated based on Staff Planning, HR Recruitment, HR
    Administration, HR Development and HR Lifecycle.
</p>
<p>
    <strong></strong>
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/recruitment/clip_image025.png"
    />
    <strong></strong>
</p>
<p>
    <strong></strong>
</p>
<p>
    <strong>a. </strong>
    <strong>Staff Planning Reports</strong>
</p>
<p>
    Reports based on human resource development and human resource management
    planning can be viewed by selecting select report type, agency and five
    year plan.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/recruitment/clip_image027.png"
    />
</p>
<p align="center">
    <em>Figure 3.1: Report of HRM and HRD</em>
</p>
<p>
    The HRD and HRM reports can be further categorized based on List/Details or
    summary/consolidated.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/recruitment/clip_image029.png"
    />
</p>
<p>
    <em>Figure 3.2: report details</em>
</p>
<p>
    b. HR Recruitment Report
</p>
<p>
    Report based on recruitment by position level within the same agency, five
    year plan and further categorized list or consolidated shown in figure 3.2.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/recruitment/clip_image031.png"
    />
</p>
<p>
    <em>Figure 3.2: Recruitment Reports </em>
</p>
<p>
    <em></em>
</p>
<p>
    <em></em>
</p>
<p>
    <em></em>
</p>
<p>
    <em></em>
</p>
<p>
    <em></em>
</p>
<p>
    <strong>c. </strong>
    <strong>HR Administration Report </strong>
</p>
<p>
    The administrative report can be generated based on Staff on Leave, Staff
    Pending Leave, Staff on Tour, Staff on Trainings/Studies and Staff Taken
    Leave Encashment.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/recruitment/clip_image033.png"
    />
</p>
<p>
    <em>Figure 3.3: Administration Reports </em>
</p>
<p>
    <em></em>
</p>
<p>
    <strong>d. </strong>
    <strong>HR Development Report</strong>
</p>
<p>
    The HR development report is based on progress of FYP implementation,
    Training implementation by Category, Training Implementation by Country and
    by Source of Funding.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/recruitment/clip_image035.png"
    />
</p>
<p>
    <em>Figure 3.4: HR Development Report</em>
</p>
<p>
    <strong>e. </strong>
    <strong>HR Life Cycle Report </strong>
</p>
<p>
    The HR Life Cycle report categorized by separation by agencies and position
    level, recruitment and separation record, staff performance appraisal
    details, staff by Dzongkhag, Nationality, Religion, Gender, Organization,
    department, employee type, division/section, marital status, position
    title, level and blood group.
</p>
<p>
    <img
        width="100%"
        src="../data/user_manual/recruitment/clip_image037.png"
    />
</p>
<p>
    <em>Figure 3.4: HR Life Cycle Report</em>
</p>