<?php
 $title = 'Transfer List Awaiting Approval From OVC';
 $this->headTitle($title);
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                    <table class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                             <th class="column-title">Sl.No. </th>
                             <th class="column-title">Current Working Agency </th>
                             <th class="column-title">Request Working Agency </th>
                             <th class="column-title">Staff Name </th>
                             <th class="column-title">Staff ID </th>
                             <th class="column-title">Status (From Agency)</th>
                             <th class="column-title">Status (To Agency) </th>
                             <th class="column-title">Application Date </th>
                             <th class="column-title">Action</th>
                          </tr>
                        </thead>
                        <tbody>
                           <?php $i=1; foreach ($this->approvedTransferList as $transfer) : ?>
                              <tr class="even pointer">
                                <td class=" "><?php echo $i++;?></td>
                                <td class=" "><?php echo $this->escapeHtml($this->organisationList[$transfer['organisation_id']]);?></td>
                                <td class=" "><?php echo $this->escapeHtml($this->organisationList[$transfer['transfer_request_to']]);?></td>
                                <td class=" "><?php echo $this->escapeHtml($transfer['first_name'].' '.$transfer['middle_name'].' '.$transfer['last_name']);?></td>
                                <td class=" "><?php echo $this->escapeHtml($transfer['emp_id']);?></td>
                                <td class=" "><?php echo $this->escapeHtml($transfer['to_org_transfer_status']);?></td>
                                <td class=" "><?php echo $this->escapeHtml($transfer['from_org_transfer_status']);?></td>
                                <td class=" "><?php echo $this->escapeHtml($transfer['date_of_request']);?></td>
                                <td><a href="<?php echo $this->url('ovctransferapproval', array('id' => $transfer['id']));?>" class="btn btn-success btn-xs"><i class="fa fa-pencil"></i>View Transfer</a>
                                </td>
                              </tr>
                           <?php endforeach; ?>
                        </tbody>
                      </table>

                        
             </div>
          </div>
        </div>
       </div>
   </div>
 </div>
            

