<?php

$title = 'Edit Student Fee Category';
$this->headTitle($title);
$key = $this->keyphrase;
function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    //IDEA-CBC
    //Original
    //$iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('aes-256-cbc'));

    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));

    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}

?>
<div class="right_col" role="main">
    <div class="">
        <div class="col-md-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                </div>
                <h5><i>Note: You can add menu that display at level, two, three, etc. Menu weight means at what position
                        the menus have to display (Example:- If you enter menu weight '1' then it will display at top).
                        If you select select level one than module name/ menu level zero will display in module name, if
                        you select level two then module/ menu added at level one will display at module name and
                        etc...</i></h5>
                <br/>

                <?php $flashMessenger = $this->flashMessenger(); ?>

                <?php if ( $this->message_status == 'Success' && $flashMessenger->hasMessages() ): ?>
                    <div class="alert alert-success alert-dismissible fade in" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                    aria-hidden="true">×</span></button>
                        <?php foreach ( $flashMessenger->getMessages() as $msg ): ?>
                            <strong>Success!</strong> <?php echo $msg ?>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>

                <?php if ( $this->message_status == 'Failure' && $flashMessenger->hasMessages() ): ?>
                    <div class="alert alert-danger alert-dismissible fade in" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                    aria-hidden="true">×</span></button>
                        <?php foreach ( $flashMessenger->getMessages() as $msg ): ?>
                            <strong>Failure!</strong> <?php echo $msg ?>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>

                <div class="x_content">
                    <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    $StudentFeeCategory = $form->get('StudentFeeCategory');
                    echo $this->form()->openTag($form);

                    $StudentFeeCategory->get('id')->setValue($this->fee_category_details['id'])->setAttribute('readonly', 'readonly');
                    $StudentFeeCategory->get('fee_category')->setValue($this->fee_category_details['fee_category']);
                    $StudentFeeCategory->get('remarks')->setValue($this->fee_category_details['remarks']);
                    $StudentFeeCategory->get('organisation_id')->setValue($this->fee_category_details['organisation_id']);
                    $StudentFeeCategory->get('submit')->setValue('Update Student Fee Category');
                    echo $this->formHidden($StudentFeeCategory->get('id'));
                    ?>
                    <div class="row">
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Organisation<span
                                        class="required">*</span></label>
                            <div class="col-md-5 col-sm-12 col-xs-12 form-group">
                                <?php echo $this->formRow(
                                    $StudentFeeCategory->get('organisation_id')->setAttribute('options', $this->organisation_lists)->setAttribute('data-readonly', 'true')
                                ); ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Fee Category Name<span
                                        class="required">*</span></label>
                            <div class="col-md-5 col-sm-12 col-xs-12 form-group">
                                <?php echo $this->formRow($StudentFeeCategory->get('fee_category')); ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Remarks<span
                                        class="required">*</span></label>
                            <div class="col-md-5 col-sm-12 col-xs-12 form-group">
                                <?php echo $this->formRow($StudentFeeCategory->get('remarks')); ?>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                            <div class="col-md-5 col-sm-6 col-xs-12">
                                <?php

                                echo $this->formHidden($StudentFeeCategory->get('csrf'));
                                echo $this->formSubmit($StudentFeeCategory->get('submit'));
                                ?>
                            </div>
                        </div>
                    </div>
                    <?php

                    echo $this->form()->closeTag();
                    ?>
                </div>
            </div>

            <!-- Start of table listing student fee category -->
            <?php $this->key = $key; ?>
            <div id="feeSrtucureTable" class="x_panel">
                <?php echo $this->render('accounts/student-fee-category/common-table.phtml') ?>
            </div>

        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $("select[data-readonly='true']").attr('readonly', 'readonly').attr("style", "pointer-events: none;").prop("disabled", false);
    });
    $(window).load(function () {
        $("select[data-readonly='true']").prop("disabled", false);
    });
</script>
