<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  // 'EmployeeDetail\Module'                        => __DIR__ . '/Module.php',
   //'EmployeeDetail\Controller\EmployeeDetailController' => __DIR__ . '/src/EmployeeDetail/Controller/EmployeeDetailController.php',
    
);
