<?php
 $title = 'Student Feedback Reports';
 $this->headTitle($title);
?>
<div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title)?></h2>
                   <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                    </ul> 
                 <div class="clearfix"></div>
                </div>
                  <div class="x_content">
                	<br/>
                 	<?php
                            // Opening of the form tag
                            $form->prepare();
                            echo $this->form()->openTag($form);
                          ?>
                        
                          <div class="row">
                              <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                <label>Report Type</label>
                                <?php echo $this->formRow($form->get('report_type')); ?>
                              </div>
                           </div>
                         <div class="row">
                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                                  <?php
                                   echo $this->formHidden($form->get('csrf'));
                                   echo $this->formSubmit($form->get('submit')); 
                                   echo $this->form()->closeTag(); 
                                ?>
                                </div>
                            </div>
                       </div>
                     </div>
                   </div>
                </div>
               <?php
                    $title = 'Student Feedback Related Report';
                    $this->headTitle($title);
               ?>
              <div class="col-md-12 col-xs-12">
                  <div class="x_panel">
                      <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                  </div>
                
                    <div class="x_content">
                     <?php if($this->report_type == 'overall_feedback_ratings'){
                            echo $this->partial('overall_student_feedbacks.phtml', 
                                            array( 
                                                    'student_report' => $this->student_report)); 
                            } else if($this->report_type == 'individual_feedback_ratings'){
                                    echo $this->partial('individual_feedback_ratings.phtml', 
                                            array( 
                                                    'student_report' => $this->student_report));
                            } 
                      ?>
                    </div>
                
                </div>
              </div>
             </div>
           </div>
          </div>
        </div> 
     </div>
     
     