<?php
 $title = 'Add Social Event';
 $this->headTitle($title);

 $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    //IDEA-CBC
    //Original
    //$iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('aes-256-cbc'));

    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));

    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}


?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2>Add Social Event</h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
          				    $event = $form->get('socialevent');
          					$event->get('organisation_id')->setValue($this->organisation_id);
                    $event->get('academic_year')->setValue($this->academic_year);
                    echo $this->formHidden($event->get('id')); 
                    echo $this->formHidden($event->get('academic_year'));
          					echo $this->formHidden($event->get('organisation_id')); 
          				  ?>
                <?php 
                  if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                      echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                      echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                      $messages = $this->flashMessenger()->getMessages();
                      foreach($messages as $message) {
                          echo '<strong>Success!</strong>'. $message;
                      }
                      echo '</div>';
                  }

                  else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                      echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                      echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                      $messages = $this->flashMessenger()->getMessages();
                      foreach($messages as $message) {
                          echo '<strong>Failure!</strong>'. $message;
                      }
                      echo '</div>';
                  }
                ?>
                <h4><i>Add Social event which is planned as well as adhoc social event in order to enter the extra curricular attendance.</i></h4><br>
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-2 col-sm-2 col-xs-12">Event Name: <span class="required">*</span></label>
                    <div class="col-md-8 col-sm-8 col-xs-12">
                      <?php  echo $this->formRow($event->get('event')); ?>
                    </div>
                </div>
                </div>
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-2 col-sm-2 col-xs-12">Event Date: <span class="required">*</span></label>
                    <div class="col-md-3 col-sm-3 col-xs-12">
                      <?php  echo $this->formRow($event->get('date')); ?>
                    </div>
                    <label class="control-label col-md-2 col-sm-2 col-xs-12">Academic Year: <span class="required">*</span></label>
                    <div class="col-md-3 col-sm-3 col-xs-12">
                      <input type="text" value="<?php echo $this->academic_year; ?>" class="form-control" readonly="readonly">
                    </div>
                </div>
                </div>
                <div class="row" >
                <div class="form-group">
                    <label class="control-label col-md-2 col-sm-2 col-xs-12">Event Description:</label>
                    <div class="col-md-8 col-sm-8 col-xs-12">
                      <?php  echo $this->formRow($event->get('event_description')); ?>
                    </div>
                </div> 
                </div>
               
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12"></label>
                              <div class="col-md-3 col-sm-3 col-xs-12">
                    <?php
                        echo $this->formHidden($form->get('csrf'));
            						echo $this->formSubmit($event->get('submit')); 
            						echo $this->form()->closeTag();
                      ?>
                    </div>
                   </div>
                </div>
                       
                </div>
              </div>
            </div>
              
              
               <?php
               $title = 'Social Events of '.date('Y');
               $this->headTitle($title);
              ?>
               <div class="col-md-12 col-xs-12">
                  
                  <div class="x_panel">
                      <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                  </div>
                
                    <div class="x_content">
                     <div class="table-responsive">
                      <table id="datatable" class="table table-striped jambo_table table-bordered">
                        <thead>
                          <tr class="headings">
                            <th width="7%" class="column-title">Sl. No</th>
                            <th class="column-title">Event Name </th>
                            <th class="column-title">Date </th>
                            <th class="column-title">Academic Year </th>
                            <th class="column-title">Description</th>
                            <th width="10%" class="column-title">Action</span></th>
                          </tr>
                        </thead>
                        <tbody>
                            <?php $i=1; foreach ($this->events as $event) : ?>
                            <?php                             
                            if($event['academic_year'] == $this->academic_year){
                            ?>
                          <tr class="even pointer">
                            <td class=" "><?php echo $i++;?></td>
                            <td class=" "><?php echo $this->escapeHtml($event['event']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($event['date']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($event['academic_year']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($event['event_description']);?></td>
                            <td><a href="<?php echo $this->url('editsocialevent', array('id' => my_encrypt($event['id'], $key)));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a></td>
                          </tr>
                        <?php } ?>
                          <?php endforeach; ?>
                        </tbody>
                      </table>
                    </div>
                   </div>
                
                </div></div></div></div>
             
          </div>
        </div> 
     </div>