<?php

$title = 'Edit Student Stipend';

$this->headTitle($title);

$key = $this->keyphrase;

function my_encrypt($data, $key) {
    $encryption_key = base64_decode($key);

    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));

    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);

    return bin2hex(base64_encode($encrypted . '::' . $iv));
}

?>

<div class="right_col" role="main">
    <div>
        <div class="col-md-12 col-sm-12 col-xs-12">

            <div class="x_panel">
                <div class="x_title">
                    <h2>Student Details</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                    </ul>

                    <div class="clearfix"></div>

                </div><!--end of x-title-->

                <div class="x_content">
                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Organisation ID:</label>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                            <?php echo $this->escapeHtml($this->studentDetails['organisation_name']); ?>
                        </div>
                    </div>

                    <br/><br/>

                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Student ID:</label>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                            <?php echo $this->escapeHtml($this->studentDetails['student_id']); ?>
                        </div>
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Student Name:</label>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                            <?php echo $this->escapeHtml($this->studentDetails['first_name'] . ' ' . $this->studentDetails['middle_name'] . ' ' . $this->studentDetails['last_name']); ?>
                        </div>
                    </div>

                    <br/><br/>

                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Student Email:</label>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                            <?php echo $this->escapeHtml($this->studentDetails['email']); ?>
                        </div>
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Student Contact No:</label>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                            <?php echo $this->escapeHtml($this->studentDetails['contact_no']); ?>
                        </div>
                    </div>

                    <br/><br/>

                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Programme:</label>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                            <?php echo $this->escapeHtml($this->studentDetails['programme_name']); ?>
                        </div>
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Student Type:</label>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                            <?php echo $this->escapeHtml($this->studentDetails['student_type']); ?>
                        </div>
                    </div>

                    <br/><br/>

                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Organisation Name:</label>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                            <?php echo $this->escapeHtml($this->studentDetails['organisation_name']); ?>
                        </div>
                    </div>

                    <br/><br/>

                    <div class="clearfix"></div>

                </div><!--end of x-content-->

                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                    </ul>

                    <div class="clearfix"></div>
                </div>

                <?php $flashMessenger = $this->flashMessenger(); ?>

                <?php if ( $this->message_status == 'Success' && $flashMessenger->hasMessages() ): ?>
                    <div class="alert alert-success alert-dismissible fade in" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                    aria-hidden="true">×</span></button>
                        <?php foreach ( $flashMessenger->getMessages() as $msg ): ?>
                            <strong>Success!</strong> <?php echo $msg ?>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>

                <?php if ( $this->message_status == 'Failure' && $flashMessenger->hasMessages() ): ?>
                    <div class="alert alert-danger alert-dismissible fade in" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                    aria-hidden="true">×</span></button>
                        <?php foreach ( $flashMessenger->getMessages() as $msg ): ?>
                            <strong>Failure!</strong> <?php echo $msg ?>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>

                <div class="x_content">
                    <?php

                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    $register = $form->get('AddStudentStipend');

                    $register->get('id')->setValue($this->id);
                    echo $this->formHidden($register->get('id'));

                    $register->get('student_id')->setValue($this->student_id);
                    echo $this->formHidden($register->get('student_id'));

                    $register->get('year')->setValue($this->studentStipendDetail['year']);
                    $register->get('month')->setValue($this->studentStipendDetail['month']);
                    $register->get('stipend')->setValue($this->studentStipendDetail['stipend']);
                    $register->get('h_r')->setValue($this->studentStipendDetail['h_r']);
                    $register->get('ebill')->setValue($this->studentStipendDetail['ebill']);
                    $register->get('net_amount')->setValue($this->studentStipendDetail['net_amount']);
                    $register->get('submit')->setValue('Update Student Stipend');
                    ?>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="year">Year<span
                                    class="required">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <?php echo $this->formRow($register->get('year')->setAttribute('options', $this->year)); ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="month">Month<span
                                    class="required">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <?php echo $this->formRow($register->get('month')->setAttribute('options', $this->month)); ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="stipend">Stipend<span
                                    class="required">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <?php echo $this->formRow($register->get('stipend')); ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="h_r">H/R</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <?php echo $this->formRow($register->get('h_r')); ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="ebill">EBill</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <?php echo $this->formRow($register->get('ebill')); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="net_amount">Net Amount<span
                                    class="required">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <?php echo $this->formRow($register->get('net_amount')); ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="ln_solid"></div>
                        <div class="form-group text-center">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <?php

                                echo $this->formHidden($register->get('csrf'));
                                echo $this->formSubmit($register->get('submit'));
                                ?>

                                <a href="/public/student-stipend/add/<?php echo my_encrypt($this->student_id, $key); ?>"
                                   class="control-label btn btn-danger">
                                    Cancel
                                </a>
                            </div>
                        </div>
                    </div>
                    <?php

                    //closing the form tag
                    echo $this->form()->closeTag();
                    ?>
                </div> <!-- End of x-content -->
            </div>

        </div>
    </div>
</div>
<script type="text/javascript">
    function validationMessage(type) {
        var message = "";

        switch (type) {
            case 'digits':
                message = "The input must contain only numbers and two decimal digits";
                break;
            case 'required':
                message = "This input field should not be left blank";
                break;
            default:
        }

        if (message.length > 0) {
            return "<ul class='not-valid'><li>" + message + "</li></ul>";
        }

        return true;
    }

    function isNumber(evt, element) {
        var regex = /^[0-9]*(?:\.\d{1,2})?$/;

        return regex.test($(element).val());
    }

    function getNetAmount() {
        var sAmount = $("#StudentStipendAmount").val();

        var hr = $("#StudentStipendHR").val() || 0;

        var ebill = $("#StudentStipendEBill").val() || 0;

        var netAmount = parseFloat(sAmount) - parseFloat(hr) - parseFloat(ebill);

        $("#StudentStipendNetAmount").val(netAmount.toFixed(2));
    }

    $(document).ready(function () {

        $("#StudentStipendAmount, #StudentStipendHR, #StudentStipendEBill, #StudentStipendNetAmount").change(function (e) {
            var isValid = isNumber(e, this);

            if (isValid === false) {
                $(this).parent().find('.not-valid').remove();
                $(this).after(validationMessage('digits'));

                $('#submitbutton').prop('disabled', true);
            } else {
                $(this).parent().find('.not-valid').remove();

                if ($(".not-valid").length === 0) {
                    $('#submitbutton').prop('disabled', false);
                }

                getNetAmount();
            }
        });


        $(".deleteStudentStipend").on('click', function () {
            if (confirm('Are you sure you want to delete this record?')) {
                window.location = "/public/student-stipend/delete/" + $(this).data('id');
            }
        });
    });

</script>
