<?php

$title = 'Government Scholarship Student List';

$this->headTitle($title);

$key = $this->keyphrase;

function my_encrypt($data, $key) {
    $encryption_key = base64_decode($key);

    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));

    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);

    return bin2hex(base64_encode($encrypted . '::' . $iv));
}

?>

<div class="right_col" role="main">
    <div class="">
        <div class="col-md-12 col-sm-12 col-xs-12">

            <div class="x_panel">

                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="">
                        <a class="btn btn-success" style="float: right;" href="/public/student-stipend/pdf">
                            Generate PDF
                        </a>

                        <a class="btn btn-success" style="float: right;" href="/public/student-stipend/bulk">
                            Generate Bulk Stipend
                        </a>
                    </div>
                    <div class="clearfix"></div>
                </div>

                <br/>

                <!-- Student List-->
                <div class="col-md-12 col-xs-12">
                    <div class="x_panel">

                        <div class="x_title">
                            <h2><?php echo $this->escapeHtml("Search for Student") ?></h2>
                            <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                </li>

                            </ul>
                            <div class="clearfix"></div>
                        </div>

                        <div class="x_content">
                            <?php

                            // Opening of the form tag
                            $form->prepare();
                            echo $this->form()->openTag($form);
                            ?>

                            <div class="row">
                                <div class="col-md-4 col-sm-12 col-xs-12 form-group">
                                    <label>Organisation</label>
                                    <?php echo $this->formRow(
                                        $form->get('organisation_id')
                                            ->setAttribute('options', $this->organisation_lists)
                                    ); ?>
                                </div>

                                <div class="col-md-4 col-sm-12 col-xs-12 form-group">
                                    <label>Student Name</label>
                                    <?php echo $this->formRow($form->get('student_name')); ?>
                                </div>

                                <div class="col-md-4 col-sm-12 col-xs-12 form-group">
                                    <label>Student ID</label>
                                    <?php echo $this->formRow($form->get('student_id')); ?>
                                </div>
                            </div>

                            <div class="row">
                                <div class="ln_solid"></div>

                                <div class="form-group">
                                    <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                                    <?php

                                    echo $this->formHidden($form->get('csrf'));
                                    echo $this->formSubmit($form->get('submit'));
                                    echo $this->form()->closeTag();
                                    ?>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>


                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2><?php echo $this->escapeHtml("List of Government Scholarship Student(s)"); ?></h2>
                            <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                </li>
                            </ul>
                            <div class="clearfix"></div>
                        </div>

                        <div class="x_content">
                            <div class="table-responsive">
                                <table id="datatable-buttons"
                                       class="table table-striped responsive-utilities jambo_table bulk_action table-bordered">
                                    <thead>
                                    <tr>
                                        <th class="column-title">Sl No</th>
                                        <th class="column-title">Name</th>
                                        <th class="column-title">Student ID</th>
                                        <th class="column-title">Gender</th>
                                        <th class="column-title">CID</th>
                                        <th class="column-title">Course Name</th>
                                        <th class="column-title">Admission Year</th>
                                        <th class="column-title">Student Type</th>
                                        <!--<th class="column-title mobile">Residency Type :-</th>-->
                                        <th class="column-title no-link last"><span class="nobr">Actions</span></th>
                                    </tr>
                                    </thead>

                                    <tbody>
                                    <?php $i = 1; ?>
                                    <?php foreach ( $this->studentList as $student ) : ?>
                                        <tr class="even pointer">
                                            <td class=" "><?php echo $i; ?></td>
                                            <td class=" "><?php echo $this->escapeHtml($student['first_name']) . ' ' .
                                                    $this->escapeHtml($student['middle_name']) . ' ' .
                                                    $this->escapeHtml($student['last_name']); ?></td>
                                            <td class=" "><?php echo $this->escapeHtml($student['student_id']); ?></td>
                                            <td class=" "><?php echo $this->escapeHtml($student['stdGender']); ?></td>
                                            <td class=" "><?php echo $this->escapeHtml($student['cid']); ?></td>
                                            <td class=" "><?php echo $this->escapeHtml($student['programme_name']); ?></td>
                                            <td class=" "><?php echo $this->escapeHtml($student['enrollment_year']); ?></td>
                                            <td class=" "><?php echo $this->escapeHtml($student['student_type']); ?></td>
                                            <!-- <td class=" "><?php /*echo $this->escapeHtml($student['dzongkhag_name']) . ' ' .
                                                    $this->escapeHtml($student['gewog_name']) . ' ' .
                                                    $this->escapeHtml($student['village_name']) . ' ' .
                                                    $this->escapeHtml($student['house_no']) . ' ' .
                                                    $this->escapeHtml($student['thram_no']); */ ?></td>-->
                                            <td class=" last">
                                                <a href="<?php echo $this->url('student-stipend', array('controller' => 'StudentStipend', 'action' => 'add', 'id' => my_encrypt($student['id'], $key))); ?>"
                                                   class="btn btn-success btn-xs">
                                                    <i class="fa fa-plus"></i> Add Stipend
                                                </a>
                                            </td>
                                        </tr>
                                        <?php $i++; ?>
                                    <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

