<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
<div class="menu_section">
<br><br><br>
<ul class="nav side-menu">
	<li><a><i class="fa fa-home"></i>Home<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a href="<?php echo $this->url('index') ?>">Dashboard</a></li>
		</ul>
	</li>
	<li><a><i class="fa fa-users"></i>Human Resource<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>HR Administration<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>Leave<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('leavestatus') ?>">Apply Leave</a></li>
						<li><a href="<?php echo $this->url('empleaveapproval') ?>">Leave Approval</a></li>
						<li><a href="<?php echo $this->url('staffleavestatus') ?>">My Leave Status</a></li>
					</ul>
					</li>
					<li><a href="<?php echo $this->url('empassignofficiatingsupervisor') ?>">Assign Officiating Supervisor</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Staff Tour<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('emptravelauthorization') ?>">Travel Authorization</a></li>
					<li><a href="<?php echo $this->url('stafftourstatus') ?>">Travel Status</a></li>
			</ul>
			</li>
		</ul>
	</li>
	<li><a><i class="fa fa-graduation-cap"></i>Academic<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>Timetable<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('addtimetable') ?>">Add Timetable</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Student Attendance<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('studentattendance') ?>">Attendance Entry</a></li>
			</ul>
			</li>
		</ul>
	</li>
	<li><a><i class="fa fa-graduation-cap"></i>Research Management<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>Research Grants<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('researchannouncementforgrant') ?>">Research Grant Announcement</a></li>
					<li><a href="<?php echo $this->url('applyuniversitygrant') ?>">Apply for University Grants</a></li>
					<li><a href="<?php echo $this->url('grantapplicationstatus') ?>">Grant Application Status</a></li>
					<li><a href="<?php echo $this->url('applycollegegrant') ?>">Apply for College Grants</a></li>
					<li><a href="<?php echo $this->url('listcarggrants') ?>">List of College Grants</a></li>
					<li><a href="<?php echo $this->url('updatecollegegrant') ?>">Update Approved CARG</a></li>
			</ul>
			</li>
			<li><a href="<?php echo $this->url('addpublicationtype') ?>">Publication Type</a></li>
			<li><a><i class=""></i>Research Publication<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('requestpublication') ?>">Request for Publication</a></li>
					<li><a href="<?php echo $this->url('applypublication') ?>">Apply for Research Publication</a></li>
					<li><a href="<?php echo $this->url('researchpublicationstatus') ?>">Research Publication Status</a></li>
					<li><a href="<?php echo $this->url('viewuniversitypublication') ?>">View University Research Publication</a></li>
					<li><a href="<?php echo $this->url('viewcollegepublication') ?>">View College Research Publication</a></li>
					<li><a href="<?php echo $this->url('announceseminar') ?>">Announce Research Seminar/Meets</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Research Reports<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('researchreports') ?>">Research Related Reports</a></li>
			</ul>
			</li>
			<li><a href="<?php echo $this->url('researchtype') ?>">Research Type</a></li>
		</ul>
	</li>
	<li><a><i class="fa fa-users"></i>Alumni<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a href="<?php echo $this->url('alumninewregistration') ?>">Register Previous Alumni</a></li>
			<li><a href="<?php echo $this->url('alumnimemberlist') ?>">Alumni Member List</a></li>
			<li><a href="<?php echo $this->url('addalumnicontributiondetail') ?>">Add Alumni Contribution</a></li>
			<li><a href="<?php echo $this->url('createalumnievent') ?>">Create Alumni Event</a></li>
			<li><a href="<?php echo $this->url('createalumniresource') ?>">Create Alumni Resources</a></li>
			<li><a href="<?php echo $this->url('createalumnienquiry') ?>">Alumni Enquiry</a></li>
			<li><a href="<?php echo $this->url('viewalumnienquirylist') ?>">View Alumni Enquiry List</a></li>
			<li><a href="<?php echo $this->url('createalumnifaqs') ?>">Add Alumni FAQs</a></li>
			<li><a href="<?php echo $this->url('viewalumnifaqslist') ?>">View Alumni FAQs List</a></li>
			<li><a href="<?php echo $this->url('addalumnisubscriptiondetail') ?>">Add Alumni Subscription</a></li>
			<li><a href="<?php echo $this->url('addalumnisubscription') ?>">Add Alumni Subscription Details</a></li>
			<li><a href="<?php echo $this->url('alumnisubscriptionlist') ?>">Alumni Subscription List</a></li>
			<li><a href="<?php echo $this->url('viewalumniresourcelist') ?>">View Alumni Resource List</a></li>
			<li><a href="<?php echo $this->url('alumnisubscriberlist') ?>">Alumni Subscriber List</a></li>
		</ul>
	</li>
</ul>
</div>
</div>
