<?php
 $title = 'Edit Awards Received';
 $this->headTitle($title);

$award_details = array();
foreach($this->awardDetails as $details){
  $award_details = $details;
} 
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    $registrant = $form->get('awards');
                    $registrant->get('id')->setValue($this->id);
                    $registrant->get('job_applicant_id')->setValue($award_details['job_applicant_id']);
                    $registrant->get('award_name')->setValue($award_details['award_name']);
                    $registrant->get('award_given_by')->setValue($award_details['award_given_by']);
                    $registrant->get('award_reasons')->setValue($award_details['award_reasons']);
                    $award_date = explode("-", $award_details['award_date']);
                    $registrant->get('award_date')->setValue($award_date[01].'/'.$award_date[02].'/'.$award_date[00]);
                    date_default_timezone_set("Asia/Thimphu");
                    $registrant->get('last_updated')->setValue(date("Y-m-d h:i:s"));
                    $registrant->get('submit')->setValue('Update');
                    echo $this->formHidden($registrant->get('id'));
                    echo $this->formHidden($registrant->get('last_updated'));
                  echo $this->formHidden($registrant->get('job_applicant_id'));
                  ?>  
                <div class="row">    
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Award Name:<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($registrant->get('award_name')); ?>
                    </div>
                   </div>
                   <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Award Date:<span class="required">*</span></label>
                    <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($registrant->get('award_date')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Award Presented By:<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($registrant->get('award_given_by')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Reasons for Receiving Award:<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($registrant->get('award_reasons')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Supporting File (Optional):</label>
                    <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                    <?php  
                    if($award_details['supporting_file']){?>
                      <a href="<?php echo $this->url('downloadapplicantawardfile', array('filename'=> 'supporting_file'.$award_details['id'])); ?>" class="btn btn-primary btn-xs"><i class="fa fa-download"></i> Download and View</a>
                    <?php } else{
                      echo $this->formRow($registrant->get('supporting_file')); 
                    }
                    ?>
                    </div>
                  </div>
                </div> 
                  
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php
               echo $this->formHidden($form->get('csrf'));
               echo $this->formSubmit($registrant->get('submit')); 
                        ?>
                      </div>
                    </div>
               </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                </div>
              </div>
        
        <!-- Start of table listing budget ledgers -->
             </div>
        
        
    
          </div>
        </div> 
     </div>
