<?php
 $title = 'Edit Reference Details';
 $this->headTitle($title);

 $reference_details = array();
 foreach($this->referenceDetails as $details){
  $reference_details = $details;
 }

?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    $registrant = $form->get('references');
                     $registrant->get('id')->setValue($this->id);
                    $registrant->get('job_applicant_id')->setValue($reference_details['job_applicant_id']);
                    $registrant->get('name')->setValue($reference_details['name']);
                    $registrant->get('title')->setValue($reference_details['title']);
                    $registrant->get('position')->setValue($reference_details['position']);
                    $registrant->get('organisation')->setValue($reference_details['organisation']);
                    $registrant->get('relation_applicant')->setValue($reference_details['relation_applicant']);
                    $registrant->get('telephone')->setValue($reference_details['telephone']);
                    $registrant->get('mobile')->setValue($reference_details['mobile']);
                    $registrant->get('email')->setValue($reference_details['email']);
                    date_default_timezone_set("Asia/Thimphu");
                    $registrant->get('last_updated')->setValue(date("Y-m-d h:i:s"));
                    $registrant->get('submit')->setValue('Update');
                    echo $this->formHidden($registrant->get('id'));
                    echo $this->formHidden($registrant->get('last_updated'));
                    echo $this->formHidden($registrant->get('job_applicant_id'));
                    ?>  
                <div class="row">    
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Reference Name<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($registrant->get('name')); ?>
                    </div>
                   </div>
                    <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Title:<span class="required">*</span></label>
                    <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($registrant->get('title')); ?>
                    </div>
                    <label class="control-label col-md-2 col-sm-3 col-xs-12">Position:<span class="required">*</span></label>
                    <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($registrant->get('position')); ?>
                    </div>
                   </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Organisation:<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($registrant->get('organisation')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Relationship to Applicant:<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($registrant->get('relation_applicant')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Telephone:</label>
                    <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($registrant->get('telephone')); ?>
                    </div>
                    <label class="control-label col-md-2 col-sm-3 col-xs-12">Mobile:<span class="required">*</span></label>
                    <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($registrant->get('mobile')); ?>
                    </div>
                   </div>
                   <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Email:</label>
                    <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($registrant->get('email')); ?>
                    </div>
                   </div>
                </div> 
                  
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php
               echo $this->formHidden($form->get('csrf'));
               echo $this->formSubmit($registrant->get('submit')); 
                        ?>
                      </div>
                    </div>
               </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                </div>
              </div>
        
        <!-- Start of table listing budget ledgers -->
             </div>
        
        
    
          </div>
        </div> 
     </div>
