<?php

 $title = 'Assign Module Tutor';
 $this->headTitle($title);
  $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    //IDEA-CBC
    //Original
    //$iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('aes-256-cbc'));

    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));

    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}
?>
<div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title)?></h2>
                   <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                    </ul> 
                 <div class="clearfix"></div>
                </div>
                  <div class="x_content">
                      <div class="col-md-12 col-sm-12 col-xs-12" align="right">
                        <div class="row">
                            <a href="<?php echo $this->url('uploadmoduletutors'); ?>"> <button type="submit" class="btn btn-success"><i class="fa fa-upload"></i> Import Module Tutors List </button></a>
                        </div>
                    </div> 
                    <br /><br />
                	<br/>
                 	<?php
                            // Opening of the form tag
                            $form->prepare();
                            echo $this->form()->openTag($form);
                            $form->get('programmes_id')->setValueOptions($this->programmeList);
                            $form->get('academic_modules_allocation_id')->setValueOptions($this->moduleList);
                            $form->get('module_coordinator')->setValueOptions($this->tutorList);
                            //$form->get('section')->setValueOptions($this->sectionList);
                            $form->get('module_tutor')->setValueOptions($this->tutorList);
                            $form->get('module_tutor_2')->setValueOptions($this->tutorList);
                            $form->get('module_tutor_3')->setValueOptions($this->tutorList);
                            $form->get('module_coordinator')->setValue('0');
                            $form->get('module_tutor')->setValue('0');
                            $form->get('module_tutor_2')->setValue('0');
                            $form->get('module_tutor_3')->setValue('0');
                            $form->get('year')->setValue(date('Y'));
                            echo $this->formHidden($form->get('id'));
                    ?>
                    <?php if($this->message == NULL && $this->flashMessenger()->hasMessages()) {
							echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
							echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
							$messages = $this->flashMessenger()->getMessages();
							foreach($messages as $message) {
								echo '<strong>Success!</strong>'. $message;
							}
							echo '</div>';
                    	} else if($this->message =='Failure' && $this->flashMessenger()->hasMessages()) {
                            echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                            echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                            $messages = $this->flashMessenger()->getMessages();
                            foreach($messages as $message) {
                                echo '<strong>Warning!</strong>'. $message;
                            }
                            echo '</div>';
                     } ?>
                    <div class="row">
                        <div class="form-group">  
                           <label class="control-label col-md-2 col-sm-2 col-xs-12">Programme Name <span class="required">*</span></label>
                           <div class="col-md-3 col-sm-3 col-xs-12">
                              <?php echo $this->formRow($form->get('programmes_id')); ?>
                           </div>
                           <label class="control-label col-md-2 col-sm-2 col-xs-12">Module Name <span class="required">*</span></label>
                           <div class="col-md-3 col-sm-3 col-xs-12">
                              <?php echo $this->formRow($form->get('academic_modules_allocation_id')); ?>
                           </div>
                        </div>
                     </div>
                     <div class="panel-body">
                          <b>Please Select a Section <small><i>(If no sections, please select 'A')</i></small></b><br /><br />
                          <div class="row fontawesome-icon-list">
                             <?php foreach($this->sectionList as $key => $value): ?>
                                <div class="col-md-3 col-sm-4 col-xs-12"><?php  echo $this->formRow($form->get('section_'.$key), 'append'); ?></div>
                            <?php endforeach; ?>
                          </div>
                        </div>
                    <br />
                     <div class="row">
                        <div class="form-group">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12">Module Co-Ordinator/Tutor<span class="required">*</span><br /></label>
                            <div class="col-md-3 col-sm-1 col-xs-12">
                              <?php echo $this->formRow($form->get('module_coordinator')); ?>
                            </div>
                            <label class="control-label col-md-2 col-sm-1 col-xs-12">Module Tutor (2)<span class="required">*</span><br />
                                <small><i>(If more than one module tutor for a subject)</i></small></label>
                            <div class="col-md-3 col-sm-1 col-xs-12">
                              <?php echo $this->formRow($form->get('module_tutor')); ?>
                            </div>
                        </div>
                     </div>
                     <br />
                     <div class="row">
                        <div class="form-group">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12">Module Tutor (3)<span class="required">*</span><br />
                            	<small><i>(If more than one module tutor for a subject)</i></small></label>
                            <div class="col-md-3 col-sm-1 col-xs-12">
                              <?php echo $this->formRow($form->get('module_tutor_2')); ?>
                            </div>
                            <label class="control-label col-md-2 col-sm-1 col-xs-12">Module Tutor (4)<span class="required">*</span><br />
                            	<small><i>(If more than one module tutor for a subject)</i></small></label>
                            <div class="col-md-3 col-sm-1 col-xs-12">
                              <?php echo $this->formRow($form->get('module_tutor_3')); ?>
                            </div>
                        </div>
                     </div>
                     <div class="row">
                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                <?php
                                   echo $this->formHidden($form->get('csrf'));
                                   echo $this->formSubmit($form->get('submit')); 
                                ?>
                                </div>
                            </div>
                       </div>
                            <?php
                            echo $this->form()->closeTag();
                            ?>
                        </div>
                      </div>
                </div>
               <?php
				 $title = 'Academic Modules Tutors for Academic Year';
				 $this->headTitle($title);
			  ?>
              <div class="col-md-12 col-xs-12">
                  
                  <div class="x_panel">
                      <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                  </div>
                
                    <div class="x_content">
                        <div class="table-responsive">
                      <table id="datatable-buttons" class="table table-striped jambo_table table-bordered">
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Sl. No</th>
                            <th class="column-title">Programme Name</th>
                            <th class="column-title">Module Title</th>
                            <th class="column-title">Module Code</th>
                            <th class="column-title">Credits</th>
                            <th class="column-title">Module Co-Ordinator</th>
                            <th class="column-title">Module Tutor</th>
                            <th class="column-title">Year</th>
                            <th class="column-title">Semester</th>
                            <th class="column-title">Academic Year</th>
                            <th class="column-title no-link last"><span class="nobr">Action</span>
                            </th>
                            <th class="bulk-actions" colspan="7">
                              <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                            </th>
                          </tr>
                        </thead>
                        <tbody>
                            <?php $i=1; foreach ($this->moduleAllocated as $module) : ?>
                          <tr class="even pointer">
                            <td class=" "><?php echo $i++;?></td>
                            <td class=" "><?php echo $this->escapeHtml($module['programme_name']); ?></td>
                            <td class=" "><?php echo $this->escapeHtml($module['module_title']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($module['module_code']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($module['module_credit']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($module['first_name'].' '.$module['middle_name'].' '.$module['last_name']);?></td>
                            <td class=" "><?php 
                                                //preg_match_all('!\d+!', $module['module_tutor'], $tutor_ids);
												$tutor_ids = explode("/", $module['module_tutor']);
                                                foreach($tutor_ids as $key=>$value){
                                                       echo $this->escapeHtml($this->tutorDetail[$value]).', ';
                                                }
										?></td>
                            <td class=" "><?php echo $this->escapeHtml($module['year']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($module['semester']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($module['academic_year']);?></td>
                            <td class="fa fa-pencil"></td>
                          </tr>
                          <?php endforeach; ?>
                        </tbody>
                      </table>
                    </div>
                    </div>
                
                </div>
              </div>
            </div>
           </div>  
          </div>
        </div> 
     </div>