<?php

 $title = 'Edit Module Allocation to An Academic Year';
 $this->headTitle($title);
 $module_detail = array();
 foreach($this->moduleDetails as $detail){
	 $module_detail = $detail;
 }
?>
<div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title)?></h2>
                   <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                    </ul> 
                 <div class="clearfix"></div>
                </div>
                  <div class="x_content">
                	<br/>
                 	<?php
						// Opening of the form tag
						$form->prepare();
						echo $this->form()->openTag($form);
						$form->get('id')->setValue($module_detail['id']);
						$form->get('programmes_id')->setValue($module_detail['programmes_id']);
						$form->get('academic_modules_id')->setValue($module_detail['academic_modules_id']);
						$form->get('academic_year')->setValue($module_detail['academic_year']);
						$form->get('semester')->setValue($module_detail['semester']);
            $form->get('year')->setValue($module_detail['year']);
            $form->get('module_type')->setValue($module_detail['module_type']);
            $form->get('module_credit')->setValue($module_detail['module_credit']);
						$form->get('academic_session')->setValue($module_detail['academic_session']);
						//$form->get('programmes_id')->setValueOptions($this->programmeList);
						//$form->get('academic_modules_id')->setValueOptions($this->moduleList);
						//$form->get('academic_year')->setValue(date('Y'));
						echo $this->formHidden($form->get('id'));
						echo $this->formHidden($form->get('programmes_id'));
						echo $this->formHidden($form->get('academic_modules_id'));
					?>
                    <div class="row">
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-2 col-xs-12">Academic Year<span class="required">*</span></label>
                            <div class="col-md-2 col-sm-1 col-xs-12">
                              <?php echo $this->formRow($form->get('academic_year')); ?>
                            </div>
                            <label class="control-label col-md-2 col-sm-2 col-xs-12">Academic Session<span class="required">*</span></label>
                            <div class="col-md-2 col-sm-1 col-xs-12">
                              <?php echo $this->formRow($form->get('academic_session')); ?>
                            </div>
                        </div>
                     </div>
                     <div class="row">
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-2 col-xs-12">Year<span class="required">*</span></label>
                            <div class="col-md-2 col-sm-1 col-xs-12">
                              <?php echo $this->formRow($form->get('year')); ?>
                            </div>
                            <label class="control-label col-md-2 col-sm-2 col-xs-12">Semester<span class="required">*</span></label>
                            <div class="col-md-2 col-sm-1 col-xs-12">
                              <?php echo $this->formRow($form->get('semester')); ?>
                            </div>
                        </div>
                     </div>
                     <div class="row">
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-2 col-xs-12">Module Type<span class="required">*</span></label>
                            <div class="col-md-2 col-sm-1 col-xs-12">
                              <?php echo $this->formRow($form->get('module_type')); ?>
                            </div>
                            <label class="control-label col-md-2 col-sm-1 col-xs-12">Module Credit<span class="required">*</span></label>
                            <div class="col-md-3 col-sm-1 col-xs-12">
                              <?php echo $this->formRow($form->get('module_credit')); ?>
                            </div>
                        </div>
                     </div>
                     <br />
                     <!--
                     <div class="row">
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-2 col-xs-12">Programme<span class="required">*</span></label>
                            <div class="col-md-3 col-sm-3 col-xs-12">
                              <?php //echo $this->formRow($form->get('programmes_id')); ?>
                            </div>
                        </div>
                     </div>
                     <br />
                    <div class="row">
                           <label class="control-label col-md-3 col-sm-2 col-xs-12">Module Name <span class="required">*</span><br />
                            	<small>(Please ensure that you only select one)</small></label>
                           <div class="col-md-6 col-sm-6 col-xs-12">
                              <?php //echo $this->formRow($form->get('academic_modules_id')); ?>
                           </div>
                     </div>
                    -->
                     <div class="row">
                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                <?php
                                   
                                   echo $this->formHidden($form->get('csrf'));
                                   echo $this->formSubmit($form->get('submit')); 
                                ?>
                                </div>
                            </div>
                       </div>
                            <?php
                            echo $this->form()->closeTag();
                            ?>
                        </div>
                      </div>
                </div>
               <?php
				 $title = 'Academic Modules for Academic Year';
				 $this->headTitle($title);
			  ?>
              <div class="col-md-12 col-xs-12">
                  
                  <div class="x_panel">
                    <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                  </div>
                
                    <div class="x_content">
                        <div class="table-responsive">
                      <table id="datatable-buttons" class="table table-striped jambo_table table-bordered">
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Sl. No</th>
                            <th class="column-title">Programme Name</th>
                            <th class="column-title">Module Title</th>
                            <th class="column-title">Module Code</th>
                            <th class="column-title">Credits</th>
                            <th class="column-title">Module Type</th>
                            <th class="column-title">Year</th>
                            <th class="column-title">Semester</th>
                            <th class="column-title">Academic Year</th>
                          </tr>
                        </thead>
                        <tbody>
                            <?php $i=1; foreach ($this->moduleAllocated as $module) : ?>
                          <tr class="even pointer">
                            <td class=" "><?php echo $i++;?></td>
                            <td class=" "><?php echo $this->escapeHtml($module['programme_name']); ?></td>
                            <td class=" "><?php echo $this->escapeHtml($module['module_title']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($module['module_code']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($module['module_credit']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($module['module_type']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($module['year']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($module['semester']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($module['academic_year']);?></td>
                          </tr>
                          <?php endforeach; ?>
                        </tbody>
                      </table>
                    </div>
                    </div>
                
                </div>
              </div>
            </div>
           </div>  
          </div>
        </div> 
     </div>