<div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>
              <ul class="nav navbar-nav navbar-right">
                <?php $userRole=$this->layout()->userRole; ?>
                  <?php $userType=$this->layout()->userType; ?>
                <li class="">
                  <?php $userImage=$this->layout()->userImage; ?>
                  <?php if(!empty($userImage)) {?>
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <img src="<?php echo '../../'.$userImage; ?>" alt=""><?php echo $this->layout()->userDetails; ?>
                    <span class=" fa fa-angle-down"></span>
                  </a>
                <?php } else{?>
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <img src="<?php echo $this->url('index'); ?>/img/logo.png" alt=""><?php echo $this->layout()->userDetails; ?>
                    <span class=" fa fa-angle-down"></span>
                  </a>
                <?php } ?>
  
                  <ul class="dropdown-menu dropdown-usermenu pull-right">
                    <?php if($userType == "1") {?>
                      <li><a href="<?php echo $this->url('staffprofile', array('action' => 'staffProfile')); ?>"> Profile</a></li>
                      <?php } else if($userType == "2"){?>
                        <li><a href="<?php echo $this->url('studentprofile', array('action' => 'studentProfile')); ?>"> Profile</a></li>
                      <?php } else if($userType == "5"){?>
                        <li><a href="<?php echo $this->url('alumniprofile', array('action' => 'alumniProfile')); ?>"> Profile</a></li>
                      <?php } ?>                      
		    <li><a href="<?php echo $this->url('changepassword', array('action' => 'changePassword')); ?>"><i class="fa fa-refresh pull-right"></i> Change Password</a></li>
		    <li><a href="<?php echo $this->url('rubimsinformation', array('action' => 'rubimsInformation')); ?>"><i class="fa fa-refresh pull-right"></i> Help</a></li>
                    <li><a href="<?php echo $this->url('auth', array('action' => 'logout')); ?>"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                  </ul>
                </li>
              </ul>
            </nav>
          </div>
        </div>
