<?php
 $title = 'Staff Details';
 $this->headTitle($title);

  $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));
    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}


?>

 <div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
            
                <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                     <div class="clearfix"></div>
                    </div>
                	
                        <!-- Search Employees-->
                        <div class="col-md-12 col-xs-12">
                          <div class="x_panel">
                            <div class="x_title">
                              <h2><?php echo $this->escapeHtml("Search for Staff")?></h2>
                                <ul class="nav navbar-right panel_toolbox">
                                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                  </li>
                            
                                </ul>
                             <div class="clearfix"></div>
                          
                            </div>
                             <?php if($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                            echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                            echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                            $messages = $this->flashMessenger()->getMessages();
                            foreach($messages as $message) {
                              echo '<strong>Success!</strong>'. $message;
                            }
                            echo '</div>';
                             } else if($this->message =='Failure' && $this->flashMessenger()->hasMessages()) {
                            echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                            echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                            $messages = $this->flashMessenger()->getMessages();
                            foreach($messages as $message) {
                                echo '<strong>Warning!</strong>'. $message;
                            }
                            echo '</div>';
                     }  ?>
                               
                            <div class="x_content">
                               <?php
                                // Opening of the form tag
                                //$form->setAttribute('action', $this->url('addpeerquestions', array('action' => 'addPeerQuestions')));
                                $form->prepare();
                                echo $this->form()->openTag($form);
                              ?>
                            
                              <div class="row">
                                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Staff First Name</label>
                                    <?php echo $this->formRow($form->get('employee_name')); ?>
                                  </div>
                                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Staff ID</label>
                                    <?php echo $this->formRow($form->get('emp_id')); ?>
                                  </div>
                                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Department</label>
                                    <?php echo $this->formRow($form->get('department')); ?>
                                  </div>
                               </div>
                             
                             <div class="row">
                                <div class="ln_solid"></div>
                                <div class="form-group">
                                    <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                                      <?php
                                       echo $this->formHidden($form->get('csrf'));
                                       echo $this->formSubmit($form->get('submit')); 
                                       echo $this->form()->closeTag(); 
                                    ?>
                                </div>
                            </div>
                              
                          </div>
                        </div>
                       </div>     
                              
                          
                        <div class="col-md-12 col-sm-12 col-xs-12">
                          <div class="x_panel">
                            <div class="x_title">
                              <h2><?php echo $this->escapeHtml("List of Employee(s)"); ?></h2>
                              <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                </li>
                              </ul>
                              <div class="clearfix"></div>
                            </div>
            
                            <div class="x_content">
                            <h5><i>*(For performance issues, the list have been limited to 50. Use search bar above table to filter and search. If employee is not found,
                            		use the "Search" functionality above)</i></h5>
                              <br />
                              <table id="datatable-buttons" class="table table-striped jambo_table table-bordered" width="100%">
                                <thead>                        
                                    <th class="column-title">Sl. No. </th>
                                    <th class="column-title">Staff ID</th>
                                    <th class="column-title">Name</th>
                                    <th class="column-title">Position Title </th>
                                    <th class="column-title">Department</th>
                                    <th class="column-title no-link last"><span class="nobr">Action</span></th>
                                </thead>
            
                                <tbody>
                                  <?php $i =1; foreach ($this->employeeList as $employee) : ?>
                                  <tr class="even pointer">
                                    <td class=" "><?php echo $i++;?></td>
                                    <td class=" "><?php echo $this->escapeHtml($employee['emp_id']);?></td>
                                    <td class=" "><?php echo $this->escapeHtml($employee['first_name']) . ' ';
                                                        echo $this->escapeHtml($employee['middle_name']) . ' ';
                                                        echo $this->escapeHtml($employee['last_name']);
                                                  ?></td>
                                    <td class=" "><?php echo $this->escapeHtml($employee['position_title']);?></td></td>
                                    <td class=" "><?php echo $this->escapeHtml($employee['department_name']);?></td>
                                    <td class=" last"><a href="<?php echo $this->url('editemployeepaydetails', array('id' => my_encrypt($employee['id'], $key)));?>" class="btn btn-primary btn-xs"><i class="fa fa-eye"></i> Edit Pay Details</a>
                                    </td>
                                  </tr>
                                  <?php endforeach; ?>
                                </tbody>
                              </table>
                            </div>
                          </div>
                        </div>
                    
                        <!-- End of Search-->
                  
                     
                  </div>
                </div>
              </div>
     </div>
   </div>
 </div>
