<?php

 $title = 'All Goods Requisition Lists (Store / Procurement)';
 $this->headTitle($title);

  $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    //IDEA-CBC
    //Original
    //$iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('aes-256-cbc'));

    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));

    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}
?>
 <div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
            
                <div class="x_panel">
                <div class="x_title">
		    <h2><?php echo $this->escapeHtml($title); ?></h2>
                     <div class="clearfix"></div>
                    </div>
                    
                    <!-- Start of Tab-->
                    <div class="" role="tabpanel" data-example-id="togglable-tabs">
                      <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                        <li role="presentation" class="active"><a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">Pending Requisition</a>
                        </li>
                        <li role="presentation" class=""><a href="#tab_content2" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false">Approved Requisition</a>
                        </li>
                        <li role="presentation" class=""><a href="#tab_content3" role="tab" id="profile-tab2" data-toggle="tab" aria-expanded="false">Rejected Requisition</a>
                        </li>
		      </ul>
		      <div id="myTabContent"   class="tab-content">
                        <div role="tabpanel" class="tab-pane fade active in" id="tab_content1"  aria-labelledby="home-tab">
                                <div class="table-responsive">
                                  <table id="datatable" class="table table-striped jambo_table bulk_action">
                                    <thead>
                                      <tr class="headings">
                                         <th class="column-title">Sl.No </th>
                                         <th class="column-title">Staff</th>
                                         <th class="column-title">Department</th>
                                         <th class="column-title">Unit</th>
                                         <th class="column-title">Item</th>
                                         <th class="column-title">Requisition Quantity</th>
					 <th class="column-title">Applied Date</th>
                                         <th class="column-title">Action </th>
                                      </tr>
				</thead>

                                <tbody>
                                   <?php $i=1; foreach ($this->pendingRequisitionList as $pendinglist) : ?>
                                  <tr class="even pointer">
                                    <td class=" "><?php echo $i++;?></td>
                                        <td class=" "><?php echo $this->escapeHtml($pendinglist->getFirst_Name()).'';
                                                            echo $this->escapeHtml($pendinglist->getMiddle_Name()).'';
                                                            echo $this->escapeHtml($pendinglist->getLast_Name()). ' (';
                                                            echo $this->escapeHtml($pendinglist->getEmp_Id()).')'; ?></td>
                                        <td class=" "><?php echo $this->escapeHtml($pendinglist->getDepartment_Name());?></td>
                                        <td class=" "><?php echo $this->escapeHtml($pendinglist->getUnit_Name());?></td>
                                        <td class=" "><?php echo $this->escapeHtml($pendinglist->getItem_Name());?></td>
                                        <td class=" "><?php echo $this->escapeHtml($pendinglist->getRequisition_Item_Quantity());?></td>
					<td class=" "><?php echo $this->escapeHtml($pendinglist->getRequisition_Date());?></td>
                                    <td><a href="<?php echo $this->url('requisition-pending-details', array('id' => my_encrypt($pendinglist->getId(), $key)));?>" class="btn btn-primary btn-xs"><i class="fa fa-eye"></i> View Details</a></td>
                                  </tr>
                                      <?php endforeach; ?>
                                    </tbody>
                                  </table>
                                </div>
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="tab_content2" aria-labelledby="profile-tab">
                                <div class="table-responsive">
                                  <table class="table table-striped jambo_table bulk_action">
                                    <thead>
                                      <tr class="headings">
                                         <th class="column-title">Sl.No </th>
                                         <th class="column-title">Staff</th>
                                         <th class="column-title">Department</th>
                                         <th class="column-title">Unit</th>
                                         <th class="column-title">Item</th>
                                         <th class="column-title">Requisition Quantity</th>
                                         <th class="column-title">Approved Quantity</th>
                                         <th class="column-title">Approved Balance Quantity</th>
                                         <th class="column-title">Applied Date</th>
					 <th class="column-title">Approved Date</th>
					 <th class="column-title">Goods received by Store Date</th>
					 <th class="column-title">Depreciated Value </th>
					 <th class="column-title">Item Cost </th>
                                         <th class="column-title">Action </th>
                                      </tr>
                                    </thead>
                                    <tbody>
                                       <?php $i=1; foreach ($this->approvedRequisitionList as $approvedList) : ?>
                                      <tr class="even pointer">
                                        <td class=" "><?php echo $i++;?></td>
                                        <td class=" "><?php echo $this->escapeHtml($approvedList->getFirst_Name()).'';
                                                            echo $this->escapeHtml($approvedList->getMiddle_Name()).'';
                                                            echo $this->escapeHtml($approvedList->getLast_Name()). ' (';
                                                            echo $this->escapeHtml($approvedList->getEmp_Id()).')'; ?></td>
                                        <td class=" "><?php echo $this->escapeHtml($approvedList->getDepartment_Name());?></td>
                                        <td class=" "><?php echo $this->escapeHtml($approvedList->getUnit_Name());?></td>
                                        <td class=" "><?php echo $this->escapeHtml($approvedList->getItem_Name());?></td>
                                        <td class=" "><?php echo $this->escapeHtml($approvedList->getRequisition_Item_Quantity());?></td>
                                        <td class=" "><?php echo $this->escapeHtml($approvedList->getApproved_Item_Quantity());?></td>
                                        <td class=" "><?php echo $this->escapeHtml($approvedList->getApproved_Balance_Quantity());?></td>
                                        <td class=" "><?php echo $this->escapeHtml($approvedList->getRequisition_Date());?></td>
					<td class=" "><?php echo $this->escapeHtml($approvedList->getApproval_Date());?></td>
					<td class=" "><?php   if (isset($depreciationval[$approvedList->getEmployee_Details_Id()][$approvedList->getItem_Name_Id()]))
                                                                           echo $depreciationval[$approvedList->getEmployee_Details_Id()][$approvedList->getItem_Name_Id()]; ?> </td>
					<td class=" "> <?php //var_dump($depreciationval); 
							   // echo $approvedList->getItem_Name_Id();
							    //echo $approvedList->getEmp_Id();
							    //echo  'ID---:'.$approvedList->getEmployee_Details_Id();
							              if (isset($depreciationval[$approvedList->getItem_Name_Id()][$approvedList->getEmployee_Details_Id()]))
											echo $depreciationval[$approvedList->getItem_Name_Id()][$approvedList->getEmployee_Details_Id()];
?></td> 
					<td class=" "> <?php echo $depreciationval['amount'][$approvedList->getItem_Name_Id()]; ?>
                                        <td><a href="<?php echo $this->url('requisition-approved-details', array('id' => my_encrypt($approvedList->getId(), $key)));?>" class="btn btn-primary btn-xs"><i class="fa fa-eye"></i> View Details</a></td>
                                        
                                      </tr>
                                      <?php endforeach; ?>
                                    </tbody>
                                  </table>
                                </div>
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="tab_content3" aria-labelledby="profile-tab">
                            <div class="table-responsive">
                              <table class="table table-striped jambo_table bulk_action">
                                <thead>
                                  <tr class="headings">
                                     <th class="column-title">Sl.No </th>
                                         <th class="column-title">Staff</th>
                                         <th class="column-title">Department</th>
                                         <th class="column-title">Unit</th>
                                         <th class="column-title">Item</th>
                                         <th class="column-title">Requisition Quantity</th>
                                         <th class="column-title">Applied Date</th>
                                         <th class="column-title">Rejected Date</th>
                                         <th class="column-title">Action </th>
                                      </tr>
                                    </thead>
                                    <tbody>
                                       <?php $i=1; foreach ($this->rejectedRequisitionList as $rejectlist) : ?>
                                      <tr class="even pointer">
                                        <td class=" "><?php echo $i++;?></td>
                                        <td class=" "><?php echo $this->escapeHtml($rejectlist->getFirst_Name()).'';
                                                            echo $this->escapeHtml($rejectlist->getMiddle_Name()).'';
                                                            echo $this->escapeHtml($rejectlist->getLast_Name()). ' ('; 
                                                            echo $this->escapeHtml($rejectlist->getEmp_Id()).')';?></td>
                                        <td class=" "><?php echo $this->escapeHtml($rejectlist->getDepartment_Name());?></td>
                                        <td class=" "><?php echo $this->escapeHtml($rejectlist->getUnit_Name());?></td>
                                        <td class=" "><?php echo $this->escapeHtml($rejectlist->getItem_Name());?></td>
                                        <td class=" "><?php echo $this->escapeHtml($rejectlist->getRequisition_Item_Quantity());?></td>
                                        <td class=" "><?php echo $this->escapeHtml($rejectlist->getRequisition_Date());?></td>
                                        <td class=" "><?php echo $this->escapeHtml($rejectlist->getApproval_Date());?></td>
                                        <td><a href="<?php echo $this->url('requisition-rejected-details', array('id' => my_encrypt($rejectlist->getId(), $key)));?>" class="btn btn-primary btn-xs"><i class="fa fa-eye"></i> View Details</a></td>
                                      </tr>                                    
                                  
                                  <?php endforeach; ?>
                                </tbody>
                              </table>
			    </div>
			
                        </div>                        
                      </div>
                    </div>
                    <!-- End of Tabs-->
                     
                     
                  </div>
                </div>
              </div>
     </div>
          
                     
