<?php
 $title = 'Hostel Allocation for Students';
 $this->headTitle($title);

  $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    //IDEA-CBC
    //Original
    //$iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('aes-256-cbc'));

    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));

    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}
 ?>
<div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                  </div>
                    
                  <div class="x_content">
                    <br/>  
                      <div class="table-responsive">
                      <table id="datatable-buttons" class="table table-striped jambo_table bulk_action"> 
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Sl. No</th>
                            <th class="column-title">Hostel Name </th>
                            <th class="column-title">Hostel Type </th>
                            <th class="column-title">Hostel Category </th>
                            <th class="column-title">Total No. of Rooms</th>
                            <th class="column-title">Room Capacity</th>
                            <th class="column-title">Provost</th>
                            <th class="column-title no-link last"><span class="nobr">Action</span></th>
                            <th class="bulk-actions" colspan="7">
                              <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                            </th>
                          </tr>
                        </thead>
                        <tbody>
                            <?php $i=1; foreach ($this->hostels as $hostel) : ?>
                          <tr class="even pointer">
                            <td class=" "><?php echo $i++;?></td>
                            <td class=" "><?php echo $this->escapeHtml($hostel['hostel_name']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($hostel['hostel_type']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($hostel['hostel_category']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($hostel['hostel_room_no']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($hostel['room_capacity']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($hostel['first_name'].' '.$hostel['middle_name'].' '.$hostel['last_name'].' ('.$hostel['emp_id'].')');?></td>
                            <td class=" "><a href="<?php echo $this->url('allocatedhosteldetails', array('id' => my_encrypt($hostel['id'], $key)));?>" class="btn btn-primary btn-xs"><i class="fa fa-eye"></i> View Details</a></td>
                          </tr>
                          <?php endforeach; ?>
                        </tbody>
                      </table>
                                        
                    </div>
                 </div>
              </div>
            </div>
         </div>
      </div>
            
   