<?php
 $title = 'Allocate Hostel Room';
 $this->headTitle($title);

 ?>
 <div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                  </div>
                  <?php 
                            if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                                echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                $messages = $this->flashMessenger()->getMessages();
                                foreach($messages as $message) {
                                    echo '<strong>Success!</strong>'. $message;
                                }
                                echo '</div>';
                            }

                            else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                                echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                $messages = $this->flashMessenger()->getMessages();
                                foreach($messages as $message) {
                                    echo '<strong>Failure!</strong>'. $message;
                                }
                                echo '</div>';
                            }
                        ?>
                  <div class="x_content"><br/>
				  <?php
                    $form->prepare();
					echo $this->form()->openTag($form);
                    $hostel = $form->get('hostelallocation');
					$hostel->get('hostel_name')->setValueOptions($this->hostelList);
					$hostel->get('yearwise')->setValueOptions($this->programmeYear);
                    echo $this->formHidden($hostel->get('id'));
                  ?>
                      
                    
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-2 col-xs-12">Hostel Name<span class="required">*</span><br />
                    			<small><i>(Press "shift" key to select multiple hostels)</i></small></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                    <?php echo $this->formRow($hostel->get('hostel_name')); ?>
                    </div>
                 </div>
                 <div class="form-group">
                    <label class="control-label col-md-3 col-sm-2 col-xs-12">Allocate Room By Year:<span class="required">*</span><br />
                    			<small><i>(Hostel Allocation will be done by mixing various programmes by year)</i></small></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                    <?php echo $this->formRow($hostel->get('yearwise')); ?>
                    </div>
                 </div>
              	 <br />
                 <p><i>**Important: When selecting multiple hostels, please ensure that you do not select a mixutre of hostels allocated for both boys and girls. 
                 		For e.g. If allocation is for boys, then select only hostels allocated to boys<br />
                       ***Important: If the no. of students exceeds the total no. of rooms available, then priority will be given to "scholarship" students. Self 
                       Financed students will then have to be allocated manually.</i> </p>
                 <br />
                <div class="ln_solid"></div>
                <div class="form-group">
                	<label class="control-label col-md-4 col-sm-2 col-xs-12"></label>
                   <div class="col-md-3 col-sm-12 col-xs-12">
                   <?php 
				   	echo $this->formHidden($form->get('csrf'));
					echo $this->formSubmit($hostel->get('submit')); 
				   ?>
                   </div>
                </div>
                 <?php echo $this->form()->closeTag();?>
                </div>
                  
			</div>
         </div>
       </div>
     </div>
   </div>
 </div>
            
         
              
       
                