<?php
 $title = 'Budget Proposal (Individual College Finance)';
 $this->headTitle($title);
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                   <?php
                   $form->prepare();
                   echo $this->form()->openTag($form);

                   echo $this->formHidden($form->get('id'));   
                ?>
                  
                <div class="row">    
                   <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Five Year Plan
                    </label>
                <?php  echo $this->formRow($form->get('training_type')); ?>
                    </div>
                   <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Financial Year
                    </label>
                <?php  echo $this->formRow($form->get('training_type')); ?>
                    </div>
                      <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Plan Type
                    </label>
                <?php  echo $this->formRow($form->get('training_type')); ?>
                    </div>
                     
                    <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Working Agency
                    </label>
                <?php  echo $this->formRow($form->get('autoretrieve')); ?>
                    </div> 
                </div>  
                  
                  <div class="row">    
                 <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Office / Department / Section
                    </label>
                <?php  echo $this->formRow($form->get('funding_source')); ?>
                </div>
            
                 <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Centre / Department / Section
                    </label>
                <?php  echo $this->formRow($form->get('funding_source')); ?>
                </div>
                   <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Action Plan
                    </label>
                <?php  echo $this->formRow($form->get('funding_source')); ?>
                </div>
                      <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Sub Activities Name
                    </label>
                <?php  echo $this->formRow($form->get('emp_requirement_no')); ?>
                    </div> 
               
                     <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Sub Activities Code
                    </label>
                <?php  echo $this->formRow($form->get('emp_requirement_no')); ?>
                    </div> 
                      <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Budget Type
                    </label>
                <select class="form-control"><option>--select--</option><option>Capital Budget</option><option>Current Budget</option></select>
                    </div> 
                 <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Allocated Budget
                    </label>
                <?php  echo $this->formRow($form->get('autoretrieve')); ?>
                </div>
            
                 <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Proposed Budget 
                    </label>
                <?php  echo $this->formRow($form->get('emp_requirement_no')); ?>
                    </div>
                   <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Write up
                    </label>
                <?php  echo $this->formRow($form->get('emp_requirement_no')); ?>
                    </div>   
                    
                </div> 
                  <h6>If Budget type Capital is selected,then Allocated Budget data will be auto-retrieved ,if not allocated budget will be zero by default</h6>
               
                <div class="row">
                        <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                              <div class="col-md-6 col-sm-6 col-xs-12">
                    <button class="btn btn-success">Add</button>
                    </div>
                    </div>
                    </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                </div>
              </div>
        </div>
              
     <?php

 $title = '';
 $this->headTitle($title);
?>     
              
        <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>

                <div class="x_content">

            <div class="table-responsive">
                  <table class="table   table-striped responsive-utilities jambo_table bulk_action table-bordered">
                    <thead>
                      <tr class="headings">
                        </th>
                         <th class="column-title">Sl.No </th>
                        <th class="column-title">Five Year Plan</th>
                        <th class="column-title">Financial Year</th>
                        <th class="column-title">Plan Type</th>
                        <th class="column-title">Working Agency</th>
                        <th class="column-title">Office/Department/Section</th>
                        <th class="column-title">Centre/Department/Section</th>
                         <th class="column-title">Action Plan</th>
                          <th class="column-title">Sub Activities Name</th>
                           <th class="column-title">Sub Activities Code</th>
                           <th class="column-title"> Budget Type</th>
                            <th class="column-title">Allocated Budget</th>
                            <th class="column-title">Proposed Budget</th>
                             <th class="column-title">Write up</th>
                        <th class="bulk-actions" colspan="7">
                          <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                        </th>
                      </tr>
                    </thead>

                    <tbody>
                      <tr class="even pointer">
                       <td class=" "></td>
                       <td class=" "></td>
                       <td class=" "></td>
                       <td class=" "></td>
                       <td class=" "></td>
                       <td class=" "></td>
                       <td class=" "></td>
                       <td class=" "></td>
                       <td class=" "></td>
                       <td class=" "></td>
                       <td class=" "></td>
                       <td class=" "></td>
                       <td class=" "></td>
                       <td class=" "></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
                 <div class="row">
                        <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                    <button class="btn btn-success">Submit</button>
                 </div>
                </div>
               </div>
                </div>
              </div>
            </div>
         
          </div>
        </div> 

              
              
   
            
    