<?php
 $title = 'Employee Trainings ';
 $this->headTitle($title);
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title)?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                
                    </ul>
                 <div class="clearfix"></div>
              
                </div>
                   
                <div class="x_content">
                  <br />
                   <?php
                   $form->prepare();
                   echo $this->form()->openTag($form);

                   echo $this->formHidden($form->get('id'));   
                ?>
                <div class="row">  
                    <label class="control-label col-md-1 col-sm-1 col-xs-12"></label>
                 <div class="col-md-4 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Employee ID <span class="required">*</span>
                    </label>
                <?php  echo $this->formRow($form->get('emp_id')); ?>
                </div>
                </div>
                  
                <div class="row">
                        <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12"></label>
                              <div class="col-md-3 col-sm-3 col-xs-12">
                      <a href="trainingapprovalform" class="btn btn-success">Submit</a>                     
                              </div>
                    </div>
                </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                  
          </div>
        </div>
                  </div></div></div>
                
                 