<?php
 $title = 'Counseling Application';
 $this->headTitle($title);
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title)?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                   <?php
                   $form->prepare();
                   echo $this->form()->openTag($form);

                   echo $this->formHidden($form->get('id'));   
                ?>
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">To: <span class="required">*</span>
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($form->get('to_whom')); ?>
                    </div>
                </div>
                </div> 
                  
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Subject: <span class="required">*</span>
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($form->get('time')); ?>
                    </div>
                    </div>
                    </div>
                <div class="row" >
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Reasons:<span class="required">*</span>
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($form->get('reasons')); ?>
                    </div>
                </div> 
                </div>
           
                <div class="row">
                        <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12"></label>
                              <div class="col-md-3 col-sm-3 col-xs-12">
                    <?php
                        echo $this->formSubmit($form->get('submit')); 
                      ?>
                    </div>
                    </div>
                    </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                       
                </div>
              </div>
                </div>
              
              
             <?php
 $title = 'Counseling Details';
 $this->headTitle($title);
 ?>
              <div class="col-md-12 col-xs-12">
                  
                  <div class="x_panel">
                      <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                  </div>
                
                    <div class="x_content">
                        <div class="table-responsive">
                      <table class="table table-striped jambo_table bulk_action"> 
                         <div class="form-group">      
                      </div> 
                        <thead>
                          <tr class="headings">
                           <!--<th>
                              <input type="checkbox" id="check-all" class="flat">
                            </th>-->
                              <th class="column-title">Sl. No</th>
                            <th class="column-title">To Whom</th>
                            <th class="column-title">Subject</th>
                            <th class="column-title">Reasons</th>
                            <th class="column-title">Status</th>
                            <th class="column-title no-link last"><span class="nobr">Action</span>
                            </th>
                            <th class="bulk-actions" colspan="7">
                              <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                            </th>
                          </tr>
                        </thead>
                        
                        <tbody>
                     
                          <tr>
                           
                            <td>1</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td class="fa fa-pencil"></td><td class="fa fa-close"></td>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                    </div>
                
                </div></div></div></div>   
              
              
              
              
              
              
              
              
              
              
              
    