<!-- start project list -->
<?php 
    $total_responses = 0;
    $ratings_description = array(
                '1' => 'Very Poor',
                '2' => 'Poor',
                '3' => 'Good',
                '4' => 'Very Good', 
                '5' => 'Excellent',
            );
   
   foreach($this->student_report as $key=>$value){
        foreach($value as $key2=>$value2){
            $total_responses += count($this->student_report[$key][$key2]);
        }
   }

?>
<table class="table table-striped projects" width="100%">
      <thead>
        <tr>
          <th style="width: 1%">#</th>
          <th style="width: 20%">Rating</th>
          <th>Response</th>
          <th style="width: 1%"></th>
          <th style="width: 20%">Total</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach($this->student_report as $key => $report):?>
          <tr>
          <td>#</td>
          <td>
            <a><?php echo $ratings_description[$key]; echo ' ('.$key.')'; ?></a>
          </td>
          <td class="project_progress">
            <div class="progress progress_sm">
              <div class="progress-bar bg-green" role="progressbar" data-transitiongoal="<?php echo (int)(count($this->student_report[$key])/$total_responses*100); ?>"></div>
            </div>
            <small><?php echo count($this->student_report[$key]); ?> Responses</small>
          </td>
          <td>
              
          </td>
          <td>
            <?php echo count($this->student_report[$key]); ?>
          </td>
        </tr>
        <?php endforeach; ?>
      </tbody>
    </table>
    <!-- end project list -->