<?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Black List Item Supplier';
 $this->headTitle($title);
?>

<div class="right_col" role="main">
    <div class="">              
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                <h2><?php echo $this->escapeHtml($title); ?></h2>
                <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                </ul>
                <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    $editsupplier = $form->get('itemsupplier');
                    echo $this->form()->openTag($form);
                    $editsupplier->get('id')->setValue($this->supplierDetails->getId());
                    $editsupplier->get('supplier_details_id')->setValue($this->supplierDetails->getId());
                    echo $this->formHidden($editsupplier->get('supplier_details_id'));
                    $editsupplier->get('organisation_id')->setValue($this->supplierDetails->getOrganisation_Id());
                     echo $this->formHidden($editsupplier->get('organisation_id'));
                    $editsupplier->get('supplier_name')->setValue($this->supplierDetails->getSupplier_Name());
                    $editsupplier->get('supplier_tpn_no')->setValue($this->supplierDetails->getSupplier_Tpn_No());
                    $editsupplier->get('supplier_bank_acc_no')->setValue($this->supplierDetails->getSupplier_Bank_Acc_No());
                    $editsupplier->get('supplier_contact_no')->setValue($this->supplierDetails->getSupplier_Contact_No());
                    $editsupplier->get('supplier_address')->setValue($this->supplierDetails->getSupplier_Address());
                    $editsupplier->get('supplier_status')->setValue($this->supplierDetails->getSupplier_Status());
                    $editsupplier->get('submit')->setValue('Update');
                    echo $this->formHidden($editsupplier->get('id'));
                 ?>               
                
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="supplier_name">Supplier Name</label>
                    <div class="col-md-7 col-sm-7 col-xs-12">
                            <?php  echo $this->formRow($editsupplier->get('supplier_name')); ?>
                    </div>
                </div>
                
                <div class="form-group">           
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="supplier_tpn_no">Supplier TPN No</label>
                    <div class="col-md-7 col-sm-7 col-xs-12">
                            <?php  echo $this->formRow($editsupplier->get('supplier_tpn_no')); ?>
                    </div>
                </div>

                <div class="form-group">           
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="supplier_bank_acc_no">Supplier Bank Account No</label>
                    <div class="col-md-7 col-sm-7 col-xs-12">
                            <?php  echo $this->formRow($editsupplier->get('supplier_bank_acc_no')); ?>
                    </div>
                </div>

                <div class="form-group">           
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="supplier_contact_no">Supplier Contact No</label>
                    <div class="col-md-7 col-sm-7 col-xs-12">
                            <?php  echo $this->formRow($editsupplier->get('supplier_contact_no')); ?>
                    </div>
                </div>

                <div class="form-group">           
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="supplier_address">Supplier Address</label>
                    <div class="col-md-7 col-sm-7 col-xs-12">
                            <?php  echo $this->formRow($editsupplier->get('supplier_address')); ?>
                    </div>
                </div>

                <div class="form-group">           
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="supplier_address">Change Supplier Status</label>
                    <div class="col-md-7 col-sm-7 col-xs-12">
                            <?php  echo $this->formRow($editsupplier->get('supplier_status')); ?>
                    </div>
                </div>
                <div class="form-group">           
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="from_date">From Date</label>
                    <div class="col-md-2 col-sm-2 col-xs-12">
                            <?php  echo $this->formRow($editsupplier->get('from_date')); ?>
                    </div>
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="to_date">To Date</label>
                    <div class="col-md-2 col-sm-2 col-xs-12">
                            <?php  echo $this->formRow($editsupplier->get('to_date')); ?>
                    </div>
                </div>

                <div class="form-group">           
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="supplier_address">Upload Supporting Document</label>
                    <div class="col-md-7 col-sm-7 col-xs-12">
                            <?php  echo $this->formRow($editsupplier->get('supporting_documents')); ?>
                    </div>
                </div>
                
                <div class="form-group">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                       <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-7 col-sm-7 col-xs-12">
                          <?php  
                            echo $this->formHidden($form->get('csrf'));
                            echo $this->formSubmit($editsupplier->get('submit'));
                          ?>
                        </div>
                    </div>
                </div> 

                <?php 
                //closing the form tag  
                 echo $this->form()->closeTag();
                 ?>
                </div>
              </div>
           
            </div>
        </div>
    </div>