<?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Edit Donor Details';
 $this->headTitle($title);
?>

<div class="right_col" role="main">
    <div class="">              
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                <h2><?php echo $this->escapeHtml($title); ?></h2>
                <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                </ul>
                <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    $editdonor = $form->get('additemdonor');
                    echo $this->form()->openTag($form);
                    $editdonor->get('id')->setValue($this->donorDetails->getId());
                    $editdonor->get('organisation_id')->setValue($this->donorDetails->getOrganisation_Id());
                    echo $this->formHidden($editdonor->get('organisation_id'));
                    $editdonor->get('donor_name')->setValue($this->donorDetails->getDonor_Name());
                    $editdonor->get('remarks')->setValue($this->donorDetails->getRemarks());
                    $editdonor->get('submit')->setValue('Update Donor Details');
                    echo $this->formHidden($editdonor->get('id'));
                 ?>               
                
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="donor_name">Donor Name</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                            <?php  echo $this->formRow($editdonor->get('donor_name')); ?>
                    </div>
                </div>
                
                <div class="form-group">           
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="remarks">Remarks</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                            <?php  echo $this->formRow($editdonor->get('remarks')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                       <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <?php  
                            echo $this->formHidden($form->get('csrf'));
                            echo $this->formSubmit($editdonor->get('submit'));
                          ?>
                        </div>
                    </div>
                </div> 

                <?php 
                //closing the form tag  
                 echo $this->form()->closeTag();
                 ?>
                </div>
            </div>

            <?php
 // Inventory/Inventory/view/goods-transaction/goods-transaction/view-item-donar.phtml:

 $title = 'Donor Lists';
 $this->headTitle($title);
?>     
            <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>

                <div class="x_content">
                    <div class="table-responsive">
                        <table class="table table-striped responsive-utilities jambo_table bulk_action table-bordered">
                            <thead>
                                <tr class="headings">
                                    <th class="column-title">Sl. No</th>
                                    <th class="column-title">Donor Name </th>
                                    <th class="column-title">Remarks </th>
                                </tr>
                            </thead>

                            <tbody>
                            <?php $i=1; ?>
                            <?php foreach ($this->itemDonorList as $donorList) : ?>
                                <tr class="even pointer">
                                    <td class=" "><?php echo $i; ?></td>
                                    <td class=" "><?php echo $this->escapeHtml($donorList->getDonor_Name()); ?></td>
                                    <td class=" "><?php echo $this->escapeHtml($donorList->getRemarks()); ?></td>
                                </tr>
                            <?php $i++; ?>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>