
<?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Approval List for Goods Transfered';
 $this->headTitle($title);
?>     
<div class="top_nav">
    <div class="nav_menu">              
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>

                <div class="x_content">
                    <div class="table-responsive">
                        <table id="datatable-buttons" class="table table-striped responsive-utilities jambo_table bulk_action table-bordered">
                            <thead>
                                <tr class="headings">
                                    <th class="column-title">Sl. No</th>
                                    <th class="column-title">Department  From </th> 
                                    <th class="column-title">Department  To </th>
                                    <th class="column-title">Transfer Date</th>
                                    <th class="column-title">Item Name</th>
                                    <th class="column-title">Item Quantity</th>
                                    <th class="column-title">Remarks</th>
                                    <th class="column-title">Status</th>
                                    <th class="column-title">Action</th>
                                </tr>
                            </thead>

                            <tbody>
                            <?php $i=1; ?>
                            <?php foreach ($this->approvallist as $goodstransfer) : ?>
                                <tr class="even pointer">
                                    <td class=" "><?php echo $i; ?></td>
                                    <td class=" "><?php echo $this->escapeHtml($goodstransfer->getDepartment_Id()); ?>
                                    <td class=" "><?php echo $this->escapeHtml($goodstransfer->getDepartment_To_Id()); ?></td>
                                    <td class=" "><?php echo $this->escapeHtml($goodstransfer->getGoods_Transfer_Date()); ?></td>
                                    <td class=" "><?php echo $this->escapeHtml($goodstransfer->getItem_Name_Id()); ?></td>
                                    <td class=" "><?php echo $this->escapeHtml($goodstransfer->getQuantity()); ?></td>
                                    <td class=" "><?php echo $this->escapeHtml($goodstransfer->getApplied_Remarks()); ?></td>
                                    <td class=" "><?php echo $this->escapeHtml($goodstransfer->getApproval_Status()); ?></td>

                                    <td class=""><a href="<?php echo $this->url('update-goods-transfer-status', array('id' => $goodstransfer->getId())); ?>" class="btn btn-success btn-xs"><i class="fa fa-pencil-square-o"></i> Update</a>
                                    </td>
                                    
                                </tr>
                            <?php $i++; ?>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>