<?php
// module/Inventory/view/goods-transaction/goods-transaction/view-item-details.phtml:
 $title = 'Item Details - College Level';
 $this->headTitle($title);
?>

<div class="right_col" role="main">
    <div class="">
        <div class="col-md-12 col-sm-12 col-xs-12">
            
            <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                     <div class="clearfix"></div>
                </div>
                	<!-- Start of Tab-->
                    <div class="" role="tabpanel" data-example-id="togglable-tabs">
                      <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                        <li role="presentation" class=""><a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">Item Category</a>
                        </li>
                        <li role="presentation" class="active"><a href="#tab_content2" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false">Item Sub Category</a>
                        </li>
                        <li role="presentation" class=""><a href="#tab_content3" role="tab" id="profile-tab2" data-toggle="tab" aria-expanded="false">Item Quantity Type</a>
                        </li>
                        <li role="presentation" class=""><a href="#tab_content4" role="tab" id="profile-tab2" data-toggle="tab" aria-expanded="false">Item Name</a>
                        </li>
                      </ul>
                      <div id="myTabContent" class="tab-content">
                        <div role="tabpanel" class="tab-pane fade" id="tab_content1" aria-labelledby="home-tab">
                                <br/>    
                                      
                                  
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                  <div class="x_panel">
                                    <div class="x_title">
                                      <h2><?php echo $this->escapeHtml("Item Category"); ?></h2>
                                      <ul class="nav navbar-right panel_toolbox">
                                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                        </li>
                                      </ul>
                                      <div class="clearfix"></div>
                                    </div>
                    
                                    <div class="x_content">
                                        <table id="datatable" class="table table-striped responsive-utilities jambo_table bulk_action table-bordered" cellspacing="0" width="100%">
                                            <thead>
                                                <tr class="headings">
                                                    <th class="column-title">Sl. No</th>
                                                    <th class="column-title">Item Category </th>
                                                    <th class="column-title">Item Description </th>
                                                </tr>
                                            </thead>
                    
                                            <tbody>
                                            <?php 
                                            $i=1;
                                            foreach ($this->listItemCategory as $itemCat) : ?>
                                            <tr class="even pointer">
                                              <td class=" "><?php echo $i++;?></td>
                                              <td class=" "><?php echo $itemCat->getCategory_Type();?></td>
                                              <td class=" "><?php echo $itemCat->getDescription();?></td>
                                              </td>
                                            </tr>
                                            <?php endforeach; ?>
                                        </tbody>
                                      </table>
                                    </div>
                                  </div>
                                </div>
                            
                              <!-- End of Item Category-->
                        </div>

                        <div role="tabpanel" class="tab-pane fade active in" id="tab_content2" aria-labelledby="profile-tab">
                                <br/>
                                <!-- Adding Item Sub Category-->
                                <div class="col-md-12 col-xs-12">
                                  <div class="x_panel">
                                    <div class="x_title">
                                      <h2><?php echo $this->escapeHtml("Add Item Sub Category")?></h2>
                                        <ul class="nav navbar-right panel_toolbox">
                                          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                          </li>
                                    
                                        </ul>
                                     <div class="clearfix"></div>
                                  
                                    </div>
                                       
                                    <div class="x_content">
                                      <br />
                                      <?php
                                        // Opening of the form tag
										                  $itemsubcategoryForm->setAttribute('action', $this->url('add-college-item-sub-category', array('action' => 'addCollegeItemSubCategory')));
										                  $itemsubcategoryForm->prepare();
										                  echo $this->form()->openTag($itemsubcategoryForm);
										                  $itemSubCategory = $itemsubcategoryForm->get('itemsubcategory');
                                      $itemSubCategory->get('organisation_id')->setValue($this->organisation_id);
										                  echo $this->formHidden($itemSubCategory->get('id'));
                                      echo $this->formHidden($itemSubCategory->get('organisation_id'));

                                      $itemSubCategory->get('item_category_id')->setValueOptions($this->itemCategory);
                                      ?>
                                    
                                      <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="item_category_id">Select Item Category<span class="required">*</span></label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                          <?php  echo $this->formRow($itemSubCategory->get('item_category_id')); ?>
                                        </div>
                                      </div>
									  
									                    <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Item Sub Category<span class="required">*</span></label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                          <?php  echo $this->formRow($itemSubCategory->get('sub_category_type')); ?>
                                        </div>
                                      </div>
									  
									                    <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Description</label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                          <?php  echo $this->formRow($itemSubCategory->get('description')); ?>
                                        </div>
                                      </div>
                                     
                                 
                                      <div class="ln_solid"></div>
                                      <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
									                      <div class="col-md-6 col-sm-6 col-xs-12">
                                          <?php
                                           echo $this->formHidden($itemsubcategoryForm->get('csrf'));
                                           echo $this->formSubmit($itemSubCategory->get('submit')); 
                                           echo $this->form()->closeTag(); 
                                          ?>
											                  </div>
                                      </div>                                     
                                  </div>
                                </div>
                               </div>     
                                      
                                  
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                  <div class="x_panel">
                                    <div class="x_title">
                                      <h2><?php echo $this->escapeHtml("Item Sub Category"); ?></h2>
                                      <ul class="nav navbar-right panel_toolbox">
                                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                        </li>
                                      </ul>
                                      <div class="clearfix"></div>
                                    </div>
                    
                                    <div class="x_content">
                                        <table id="datatable1" class="table table-striped responsive-utilities jambo_table bulk_action table-bordered" cellspacing="0" width="100%">
                                            <thead>
                                                <tr class="headings">
                                                    <th class="column-title">Sl. No</th>
                                                    <th class="column-title">Item Sub Category </th>
                                                    <th class="column-title">Item Category </th>
                                                    <th class="column-title">Item Sub Description </th>
                                                    <th class="column-title">Action</th>
                                                </tr>
                                            </thead>
                    
                                            <tbody>
                                            <?php 
											                      $i=1;
											                      foreach ($this->listItemSubCategory as $itemsubcat) : ?>
                                            <tr class="even pointer">
                                              <td class=" "><?php echo $i++;?></td>
                                              <td class=" "><?php echo $itemsubcat->getSub_Category_Type();?></td>
											                        <td class=" "><?php echo $itemsubcat->getCategory_Type();?></td>
											                        <td class=" "><?php echo $itemsubcat->getDescription();?></td>
                                              <td class=" "><a href="<?php echo $this->url('edit-item-sub-category', array('id' => $itemsubcat->getId())); ?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit </a>
                                              </td>
                                            </tr>
                                            <?php endforeach; ?>
                                        </tbody>
                                      </table>
                                    </div>
                                  </div>
                                </div>
                            
                            	<!-- End of Item Sub Category-->
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="tab_content3" aria-labelledby="profile-tab">
                            <br/>  
                                      
                                  
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                  <div class="x_panel">
                                    <div class="x_title">
                                      <h2><?php echo $this->escapeHtml("Item Quantity Type"); ?></h2>
                                      <ul class="nav navbar-right panel_toolbox">
                                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                        </li>
                                      </ul>
                                      <div class="clearfix"></div>
                                    </div>

                                    <div class="x_content">
                                      <br />
                                       <?php
                                        // Opening of the form tag
                                      $itemquantitytypeForm->setAttribute('action', $this->url('add-college-item-quantity-type', array('action' => 'addCollegeItemQuantityType')));
                                      $itemquantitytypeForm->prepare();
                                      echo $this->form()->openTag($itemquantitytypeForm);
                                      $itemQuantityType = $itemquantitytypeForm->get('itemquantitytype');
                                      $itemQuantityType->get('organisation_id')->setValue($this->organisation_id);
                                      echo $this->formHidden($itemQuantityType->get('id'));
                                      echo $this->formHidden($itemQuantityType->get('organisation_id'));
                                      
                                      ?>
                                    
                                      <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Item Quantity Type<span class="required">*</span></label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                          <?php  echo $this->formRow($itemQuantityType->get('item_quantity_type')); ?>
                                        </div>
                                      </div>
                  
                                     <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Remarks</label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                          <?php  echo $this->formRow($itemQuantityType->get('remarks')); ?>
                                        </div>
                                    </div>
                                     
                                    <div class="ln_solid"></div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                          <?php
                                          echo $this->formHidden($itemquantitytypeForm->get('csrf'));
                                          echo $this->formSubmit($itemQuantityType->get('submit')); 
                                          echo $this->form()->closeTag(); 
                                          ?>
                                        </div>
                                    </div>                                      
                                    </div>
                                  </div>
                                </div>

                                <div class="col-md-12 col-sm-12 col-xs-12">
                                  <div class="x_panel">
                                    <div class="x_title">
                                      <h2><?php echo $this->escapeHtml("Item Quantity Type"); ?></h2>
                                      <ul class="nav navbar-right panel_toolbox">
                                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                        </li>
                                      </ul>
                                      <div class="clearfix"></div>
                                    </div>
                    
                                    <div class="x_content">
                                      <table id="datatable2" class="table   table-striped responsive-utilities jambo_table bulk_action table-bordered" cellspacing="0" width="100%">
                                        <thead>
                                            <tr class="headings">
                                                <th class="column-title">Sl. No</th>
                                                <th class="column-title">Item Quantity Type </th>
                                                <th class="column-title">Remarks </th>
                                            </tr>
                                        </thead>
                    
                                        <tbody>
                                          <?php
                                          $i=1;  foreach($this->listItemQuantityType as $itemquantity): ?>
                                          <tr class="even pointer">
                                            <td class=" "><?php echo $i++;?></td>
                                            <td class=" "><?php echo $itemquantity->getItem_Quantity_Type();?></td>
										                        <td class=" "><?php echo $itemquantity->getRemarks();?></td>
                                            </td>
                                          </tr>
                                          <?php endforeach; ?>
                                        </tbody>
                                      </table>
                                    </div>
                                  </div>
                                </div>
                            
                            <!-- End of Item Quantity Type-->
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="tab_content4" aria-labelledby="profile-tab">
                            <br/>
                            <!-- Adding Item Name-->
                            <div class="col-md-12 col-xs-12">
                                  <div class="x_panel">
                                    <div class="x_title">
                                      <h2><?php echo $this->escapeHtml("Add Item Name")?></h2>
                                        <ul class="nav navbar-right panel_toolbox">
                                          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                          </li>
                                    
                                        </ul>
                                     <div class="clearfix"></div>
                                  
                                    </div>
                                       
                                    <div class="x_content">
                                      <br />
                                      <?php
                                        // Opening of the form tag
                  										$itemnameForm->setAttribute('action', $this->url('add-college-item-name', array('action' => 'addCollegeItemName')));
                  										$itemnameForm->prepare();
                  										echo $this->form()->openTag($itemnameForm);
                  										$itemName = $itemnameForm->get('itemname');
                                      $itemName->get('organisation_id')->setValue($this->organisation_id);
                                      echo $this->formHidden($itemName->get('organisation_id'));
                  										echo $this->formHidden($itemName->get('id'));
                  										
                  										//$itemName->get('item_category_id')->setValueOptions($this->itemCategory);
                                     // $itemName->get('item_sub_category_id')->setValueOptions($this->itemSubCategory);
                                     // $itemName->get('item_sub_category_id')->setValueOptions($this->itemSubCategory);

                                      $itemName->get('item_quantity_type_id')->setValueOptions($this->itemQuantityType);										
                                      ?>

                                      <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Select Category<span class="required">*</span></label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                          <?php  echo $this->formRow($itemnameForm->get('item_category_id')); ?>
                                        </div>
                                      </div>
                                    									  
									                    <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Select Sub Category<span class="required">*</span></label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                          <?php  echo $this->formRow($itemnameForm->get('item_sub_category_id')); ?>
                                        </div>
                                      </div>
									  
									                    <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Select Item Quantity Type<span class="required">*</span></label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                          <?php  echo $this->formRow($itemName->get('item_quantity_type_id')); ?>
                                        </div>
                                      </div>
									  
									                    <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Item Name<span class="required">*</span></label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                          <?php  echo $this->formRow($itemName->get('item_name')); ?>
                                        </div>
                                      </div>
									  
									                    <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Description</label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                          <?php  echo $this->formRow($itemName->get('description')); ?>
                                        </div>
                                      </div>
                               
                                    <div class="ln_solid"></div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
										                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <?php
                                        echo $this->formHidden($itemnameForm->get('csrf'));
                                        echo $this->formSubmit($itemName->get('submit')); 
                                        echo $this->form()->closeTag(); 
                                        ?>
										                    </div>
                                    </div>
                                    </div>
                                      
                                  </div>
                                </div>                                      
                                  
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                  <div class="x_panel">
                                    <div class="x_title">
                                      <h2><?php echo $this->escapeHtml("Item Name List"); ?></h2>
                                      <ul class="nav navbar-right panel_toolbox">
                                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                        </li>
                                      </ul>
                                      <div class="clearfix"></div>
                                    </div>
                    
                                    <div class="x_content">
                                      <table id="datatable-buttons" class="table   table-striped responsive-utilities jambo_table bulk_action table-bordered" cellspacing="0" width="100%">
                                        <thead>
                                            <tr class="headings">
                                                <th class="column-title">Sl. No</th>
                                                <th class="column-title">Item Name </th>
                                                <th class="column-title">Sub Category </th>   
                                                <th class="column-title">Category </th>
                                                <th class="column-title">Quantity Type</th>
                                                <th class="column-title">Action</th>
                                            </tr>
                                        </thead>
                    
                                        <tbody>
                                          <?php
                                          $i=1;  foreach($this->listItemName as $item): ?>
                                          <tr class="even pointer">
                                            <td class=" "><?php echo $i++;?></td>
                                            <td class=" "><?php echo $item->getItem_Name();?></td>
                      											<td class=" "><?php echo $item->getSub_Category_Type();?></td>
                      											<td class=" "><?php echo $item->getCategory_Type();?></td>
                      											<td class=" "><?php echo $item->getItem_Quantity_Type();?></td>
                                            <td class=" "><a href="<?php echo $this->url('edit-item-name', array('id' => $item->getId())); ?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit </a>
                                            </td>
                                          </tr>
                                          <?php endforeach; ?>
                                        </tbody>
                                      </table>
                                    </div>
                                  </div>
                                </div>
                                <!-- End of Item Name-->
						              </div>
                        </div>     
                    </div>
            </div>
                    <!-- End of Tabs-->                                        
        </div>
    </div>
</div>
    
