<?php
 $title = 'Edit Position Title';
 $this->headTitle($title);
?>
<div class="right_col" role="main">
      <div class="">
        <div class="col-md-12 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
              <h2><?php echo $this->escapeHtml($title); ?></h2>
             <div class="clearfix"></div>
            </div>
            <div class="x_content">
            <br />
            <div class="" role="tabpanel" data-example-id="togglable-tabs">
            <div id="myTabContent" class="tab-content">
              <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="profile-tab">
               <br/> 
               <p> 
                <div class="x_panel"> 
                <div class="x_content">
                <br />
                   
                <?php
                   // Opening of the form tag
					$form->prepare();
                    echo $this->form()->openTag($form);
				    $title = $form->get('positiontitle');
					$title->get('id')->setValue($this->positionDetails->getId());
					$title->get('position_category_id')->setValue($this->positionDetails->getPosition_Category_Id());
					$title->get('position_title')->setValue($this->positionDetails->getPosition_Title());
					$title->get('description')->setValue($this->positionDetails->getDescription());
					$title->get('notes')->setValue($this->positionDetails->getNotes());
					$title->get('position_category_id')->setValueOptions($this->positionCategory);
                    echo $this->formHidden($title->get('id'));
                ?>
                  
                <div class="row">    
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Postion Category: <span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($title->get('position_category_id')); ?>
                    </div>
                  </div>
                </div>
                <div class="row">    
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Position Title: <span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($title->get('position_title')); ?>
                    </div>
                  </div>
                </div>
                <div class="row">    
                 <div class="form-group">
                    <label class="control-label col-md-3 col-sm- col-xs-12">Position Title Description: <span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($title->get('description')); ?>
                    </div>
                 </div>
                </div>                 
                <div class="row">    
                 <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Notes: <span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($title->get('notes')); ?>
                    </div>
                  </div>
                </div>  
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                        <?php 
						   echo $this->formHidden($form->get('csrf'));
						   echo $this->formSubmit($title->get('submit')); 
						?>
                        </div>
                    </div>
                </div>
                    
				<?php echo $this->form()->closeTag(); ?>
                    
                </div>
                </div> 
                
				<div class="x_panel">
                <div class="x_content">
                     <div class="table-responsive">
                      <table id="example-datatable" class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Position Titles </th>
                            <th class="column-title">Position Category</th>
                            <th class="column-title">Position Descriptions </th>
                            <th class="column-title">Action</th>
                          </tr>
                        </thead>  
                        <tbody>
                        <?php foreach ($this->position_title as $positions): ?>
						  <tr>
							<td><?php echo $this->escapeHtml($positions->getPosition_Title());?></td>
							<td><?php echo $this->escapeHtml($positionCategory[$positions->getPosition_Category_Id()]);?></td>
							<td><?php echo $this->escapeHtml($positions->getDescription());?></td>
                            <td><a href="<?php echo $this->url('editpositiontitle', array('id' => $positions->getId()));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a></td>
						  </tr>
                        <?php endforeach; ?>
                        </tbody>
                      </table>
                     </div>
					</div>
				</div>
				</div>
                <!-- End of tabs-->        
                
   		 </div>
 		</div>
	</div>
</div>
</div>
            
