<?php

 $title = 'Documents Submitted for Long Term Training';
 $this->headTitle($title);
 
 $training_detail = array();
 $nomination_list = array();
 foreach($this->appliedTrainingDetails as $details){
  $training_detail = $details;
 } 
 
 /*foreach($this->trainingNominations as $key=>$value){
	$nomination_list[$value['employee_details_id']] = $value['first_name'].' '.$value['middle_name'].' '.$value['last_name'];
 }*/

  $secretKey = $this->keyphrase;
 function my_encrypt($data, $secretKey) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($secretKey);
    // Generate an initialization vector
    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));
    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}
 
?>

 <div class="right_col" role="main">
          <div class="">
              <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                  </div>

                  <div class="x_content">

                    <?php 
                      if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                          echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                          echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                          $messages = $this->flashMessenger()->getMessages();
                          foreach($messages as $message) {
                              echo '<strong>Success!</strong>'. $message;
                          }
                          echo '</div>';
                      }

                      else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                          echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                          echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                          $messages = $this->flashMessenger()->getMessages();
                          foreach($messages as $message) {
                              echo '<strong>Failure!</strong>'. $message;
                          }
                          echo '</div>';
                      }
                      ?>
                      
                      <div class="table-responsive">
                          <table class="table   table-striped responsive-utilities jambo_table bulk_action table-bordered">
                            <thead>
                              <tr class="headings">     
                                <th style="width:10%" class="column-title">Course Title </th>
                                <th style="width:9%" class="column-title">Audit Clearance Form</th>
                                <th style="width:9%" class="column-title">Security Clearance Form </th>
                                <th style="width:9%" class="column-title">Medical Clearance Certificate</th>
                                <th style="width:9%" class="column-title">Acceptance Letter from Institute</th>
                                <th style="width:9%" class="column-title">Course Content and Schedule </th>
                                <th style="width:9%" class="column-title">Professional Development Report </th
                              </tr>
                            </thead>
                            <tbody>
                              <tr>
                                <td class=" "><?php echo $training_detail['course_title']; ?></td>
                                <td class=" ">
                                  <?php
                                    if(!empty($training_detail['audit_clearance'])) 
                                    {?>
                                      <a href="<?php echo $this->url('downloadlongtermapplication', array('filename' => 'audit_clearance_'.$training_detail['id']));?>" class="btn btn-primary btn-xs"><i class="fa fa-download"></i>Download</a>
                                    <?php }else
                                    echo "Documents Not Submitted";
                                    ?>
                                </td>
                                <td class=" ">
                                  <?php
                                    if(!empty($training_detail['security_clearance'])) 
                                    {?>
                                      <a href="<?php echo $this->url('downloadlongtermapplication', array('filename' => 'security_clearance_'.$training_detail['id']));?>" class="btn btn-primary btn-xs"><i class="fa fa-download"></i>Download</a>
                                    <?php }else
                                    echo "Documents Not Submitted";
                                    ?>
                                </td>
                                <td class=" ">
                                  <?php
                                    if(!empty($training_detail['medical_certificate'])) 
                                    {?>
                                      <a href="<?php echo $this->url('downloadlongtermapplication', array('filename' => 'medical_certificate_'.$training_detail['id']));?>" class="btn btn-primary btn-xs"><i class="fa fa-download"></i>Download</a>
                                    <?php }else
                                    echo "Documents Not Submitted";
                                    ?>
                                </td>
                                <td class=" ">
                                  <?php
                                    if(!empty($training_detail['acceptance_letter'])) 
                                    {?>
                                      <a href="<?php echo $this->url('downloadlongtermapplication', array('filename' => 'acceptance_letter_'.$training_detail['id']));?>" class="btn btn-primary btn-xs"><i class="fa fa-download"></i>Download</a>
                                    <?php }else
                                    echo "Documents Not Submitted";
                                    ?>
                                </td>
                                <td class=" ">
                                  <?php
                                    if(!empty($training_detail['course_content_schedule'])) 
                                    {?>
                                      <a href="<?php echo $this->url('downloadlongtermapplication', array('filename' => 'course_content_schedule_'.$training_detail['id']));?>" class="btn btn-primary btn-xs"><i class="fa fa-download"></i>Download</a>
                                    <?php }else
                                    echo "Documents Not Submitted";
                                    ?>
                                </td>
                                <td class=" ">
                                  <?php
                                    if(!empty($training_detail['professional_development_report'])) 
                                    {?>
                                      <a href="<?php echo $this->url('downloadlongtermapplication', array('filename' => 'professional_development_report_'.$training_detail['id']));?>" class="btn btn-primary btn-xs"><i class="fa fa-download"></i>Download</a>
                                    <?php }else
                                    echo "Documents Not Submitted";
                                    ?>
                                </td>
                              </tr>
                            </tbody>
                        </table>
                   </div>
                   <div class="ln_solid"></div>
                  <div class="clearfix"></div>
                  <br />
                  <?php if(empty($training_detail['award_letter'])){?>
                    <p><i><b><font color="red">***You are allowed to use below upload form to upload the missing required document(s) or if you have mistakenly uploaded the document. If you have previously uploaded the correct document(s) before and by chance if you happen to upload the different document(s) then the previously uploaded document(s) will get replaced by the current uploading document(s). </font></b></i></p>
                  <?php 
                  $form->prepare();
                    echo $this->form()->openTag($form);
                    $training = $form->get('longtermtraining');
                     $training->get('id')->setValue($training_detail['id']);
                    $training->get('employee_details_id')->setValue($this->employee_details_id);
                    $training->get('training_details_id')->setValue($training_detail['training_details_id']);
                    echo $this->formHidden($training->get('id'));
                    echo $this->formHidden($training->get('training_details_id'));
                    echo $this->formHidden($training->get('employee_details_id'));
                    $training->get('submit')->setValue('Update');
                    ?>

                    <div class="row">
                    <div class="form-group">  
                       <label class="control-label col-md-3 col-sm-3 col-xs-12">Audit Clearance</label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php echo $this->formRow($training->get('audit_clearance')); ?>
                        </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group">  
                       <label class="control-label col-md-3 col-sm-3 col-xs-12">Security Clearance</label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php echo $this->formRow($training->get('security_clearance')); ?>
                        </div>
                    </div>
                  </div> 
                  <div class="row">
                    <div class="form-group">  
                       <label class="control-label col-md-3 col-sm-3 col-xs-12">Medical Clearance Certificate</label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php echo $this->formRow($training->get('medical_certificate')); ?>
                        </div>
                    </div>
                  </div> 
                  <div class="row">
                    <div class="form-group">  
                       <label class="control-label col-md-3 col-sm-3 col-xs-12">Course Content and Schedule</label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php echo $this->formRow($training->get('course_content_schedule')); ?>
                        </div>
                    </div>
                  </div> 
                  <div class="row">
                    <div class="form-group">  
                       <label class="control-label col-md-3 col-sm-3 col-xs-12">Acceptance Letter from Institute</label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php echo $this->formRow($training->get('acceptance_letter')); ?>
                        </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group">  
                       <label class="control-label col-md-3 col-sm-3 col-xs-12">Professional Development Report Form</label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php echo $this->formRow($training->get('professional_development_report')); ?>
                        </div>
                    </div>
                  </div> 
                <div class="ln_solid"></div>
                      <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                          <?php  
                            echo $this->formHidden($form->get('csrf')); 
                            echo $this->formRow($training->get('submit'));
                            echo $this->form()->closeTag($form);
                           ?>
                        </div>
                      </div>
                    <?php } else{?>
                      <div class="x_content">
                      <?php 
                            
                     echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert"></button>';
                      echo '<strong>Alert! Your training application has been already approved and attached award letter. You are not allow to edit your application</strong>';
                      echo '</div>';
            ?>
          </div>
          <?php } ?>
       			 </div> <!-- End of x_content-->
        	  </div> <!-- End of x_panel-->
   			</div> 
        </div>
  	 </div>
   </div>
 </div>
 