<?php
 $title = 'Planned Training Details';
 $this->headTitle($title);
 ?>
<div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                  </div>
                    
                  <div class="x_content">
                    <br/>
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				    $training = $form->get('employeetraining');
                    echo $this->form()->openTag($form);
                    echo $this->formHidden($training->get('id'));
					$training->get('hrd_type')->setValue('adhoc training');
					echo $this->formHidden($training->get('hrd_type'));
				  ?>  
                    <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Training/Long Term Study Order No.<span class="required">*</span></label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php  echo $this->formRow($training->get('order_no')); ?>
                        </div>
                       <label class="control-label col-md-2 col-sm-2 col-xs-12">Training/Long Term Study Order Date<span class="required">*</span></label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php  echo $this->formRow($training->get('order_date')); ?>
                        </div>
                    </div>
                    </div>
                    <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Training Category<span class="required">*</span></label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php  echo $this->formRow($training->get('training_category')); ?>
                        </div>
                       <label class="control-label col-md-2 col-sm-2 col-xs-12">Training Type<span class="required">*</span></label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php  echo $this->formRow($training->get('training_type')); ?>
                        </div>
                    </div>
                    </div>
                    <div class="row"> 
                    <br />
                	<h4><i>Training/Course Details:</i></h4>
                    <br />
                    <div class="row">
                    <div class="form-group">  
                       <label class="control-label col-md-2 col-sm-2 col-xs-12">Course Title<span class="required">*</span></label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php  echo $this->formRow($training->get('course_title')); ?>
                        </div>
                    </div>
                    </div>
                    <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Study/Course Level<span class="required">*</span></label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php  echo $this->formRow($training->get('course_level')); ?>
                        </div>
                       <label class="control-label col-md-2 col-sm-2 col-xs-12">Field Of Study<span class="required">*</span></label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php  echo $this->formRow($training->get('field_study')); ?>
                        </div>
                    </div>
                    </div>
                    <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Training Start Date<span class="required">*</span></label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php  echo $this->formRow($training->get('training_start_date')); ?>
                        </div>
                       <label class="control-label col-md-2 col-sm-2 col-xs-12">Training End Date<span class="required">*</span></label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php  echo $this->formRow($training->get('training_end_date')); ?>
                        </div>
                    </div>
                    </div>
                    <div class="row"> 
                    <br />
                	<h4><i>Institute Details:</i></h4>
                    <br />
                    <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Institute/University Name<span class="required">*</span></label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php  echo $this->formRow($training->get('institute_name')); ?>
                        </div>
                       <label class="control-label col-md-2 col-sm-2 col-xs-12">Training/Study Location<span class="required">*</span></label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php  echo $this->formRow($training->get('institute_country')); ?>
                        </div>
                    </div>
                    </div>
                    <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Training/Study Address<span class="required">*</span></label>
                       <div class="col-md-8 col-sm-8 col-xs-12">
                          <?php  echo $this->formRow($training->get('institute_location')); ?>
                        </div>
                    </div>
                    </div>
                    <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Source of Funding<span class="required">*</span></label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php  echo $this->formRow($training->get('source_of_funding')); ?>
                        </div>
                       <label class="control-label col-md-2 col-sm-2 col-xs-12">Professional Development No.<span class="required">*</span></label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php  echo $this->formRow($training->get('professional_development_no'));?>
                        </div>
                    </div>
                    </div>
                   
                    <div class="ln_solid"></div>
                    <div class="row">
                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <?php
						 echo $this->formHidden($form->get('csrf'));
						 echo $this->formSubmit($training->get('submit')); 
                        ?>
                        </div>
                    </div>
                    </div>
                   <?php
                    echo $this->form()->closeTag();
                    ?>
                       
                    
                   </div>
                </div>
              </div>
           </div>
         </div>
	  </div>
    </div>
  