<?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Add New House';
 $this->headTitle($title);

  $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    //IDEA-CBC
    //Original
    //$iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('aes-256-cbc'));

    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));

    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}
?>

<div class="right_col" role="main">
    <div class=" ">
        <div class="col-md-12 col-xs-12">
            <div class="x_panel">
			  <div class="x_title">
				<h2><?php echo $this->escapeHtml($title); ?></h2>
			  <div class="clearfix"></div>
			  <h5><i>To add new house form. Please take care when you add new house. There should not have any duplicate house entered.</i></h5>
			  </div>
			  <div class="x_content">
				  <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				    $studenthouse = $form->get('studenthouse');
					$studenthouse->get('organisation_id')->setValue($this->organisation_id);
					echo $this->formHidden($studenthouse->get('organisation_id')); 
                    echo $this->form()->openTag($form);
                 ?>

                 <?php 
                    if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                        echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                        echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                        $messages = $this->flashMessenger()->getMessages();
                        foreach($messages as $message) {
                            echo '<strong>Success!</strong>'. $message;
                        }
                        echo '</div>';
                    }

                    else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                        echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                        echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                        $messages = $this->flashMessenger()->getMessages();
                        foreach($messages as $message) {
                            echo '<strong>Failure!</strong>'. $message;
                        }
                        echo '</div>';
                    }

                ?>             
                
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="student_type">House Name<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                            <?php  echo $this->formRow($studenthouse->get('house_name')); ?>
                    </div>
                </div>
                
                <div class="form-group">           
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="description">Description  </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                            <?php  echo $this->formRow($studenthouse->get('description')); ?>
                    </div>
                </div>
                
                <div class="form-group">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                       <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
						   <?php  
                            echo $this->formHidden($form->get('csrf'));
                            echo $this->formSubmit($studenthouse->get('submit')); 
                            ?>
                        </div>
                    </div>
                </div> 

                    <?php 
                //closing the form tag  
                 echo $this->form()->closeTag();
                 ?>

			  </div> <!-- End of x-content -->
            </div>

            <?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'House List';
 $this->headTitle($title);
?>     
            <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
				  <h5><i>Lists of House</i></h5>
                </div>
                </br>
                <div class="x_content">
                    <div class="table-responsive">
                        <table id="datatable" class="table table-striped responsive-utilities jambo_table bulk_action table-bordered">
                            <thead>
                                <tr class="headings">
                                    <th class="column-title">Sl. No</th>
                                    <th class="column-title">House Name </th>
                                    <th class="column-title">Description </th>
                                    <th class="column-title">Action</th>
                                </tr>
                            </thead>

                            <tbody>
                            <?php $i=1; ?>
                            <?php foreach ($this->house as $house) : ?>
                                <tr class="even pointer">
                                    <td class=" " width="8%"><?php echo $i; ?></td>
                                    <td class=" "><?php echo $this->escapeHtml($house->getHouse_Name()); ?></td>
                                    <td class=" "><?php echo $this->escapeHtml($house->getDescription()); ?></td>
                                    <th class=" " width="10%"><a href="<?php echo $this->url('edit-house', array('id' => my_encrypt($house->getId(), $key))); ?>" class="btn btn-info btn-xs"><span class="fa fa-pencil"></i> Edit </span></a>
                                    </th>
                                </tr>
                            <?php $i++; ?>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div> 
        </div> 
    </div>
</div>
</div>
</div>

