<?php
 // module/EmployeeDetail/view/employee-detail/employee-detail/emppersonaldetail.phtml:

    $title = 'Student List';
    $this->headTitle($title);

     //get student list in an array
 $studentName = array();
 $semesterName = array();
 //$studentSection = array();
 //$criteriaName = array();
 $i=1;
 $j=1;
 foreach($this->semesterStudentList as $student){
    $studentName[$i] = $student['first_name']. ' ' .$student['middle_name'].' '.$student['last_name'].' ('.$student['student_id'].')';
    $semesterName[$i] = $student['semester'];
    $studentId[$i] = $student['id'];
    $i++;
 }
 
?>
<div class="right_col" role="main">
    <div class="">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </ul>
                    <div class="clearfix"></div>
                </div> 

                <div class="col-md-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2><?php echo $this->escapeHtml("Search for List of Student for semester registration")?></h2>
                            <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                            </ul>
                            <div class="clearfix"></div>
                  
                        </div>
                       
                        <div class="x_content">
                            <h5><i>*(In order to search the list of student  and to register semester to them, you have to select programme and semester from drop down list and click on search button to display the list of students with respect to the programme you select.)<br />
                                        **When list display, select section from drop down list and at once you can submit their registered semester** </i></h5>
                                  <br />
                            <?php
                            // Opening of the form tag
                            $form->prepare();
                            echo $this->form()->openTag($form);
                            $form->get('semester_id')->setValueOptions($this->studentSemester);
                            ?>
                        
                            <div class="row">
                                <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Programme</label>
                                    <?php echo $this->formRow($form->get('programmes_id')); ?>
                                </div>
                                <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Semester</label>
                                    <?php echo $this->formRow($form->get('semester_id')); ?>
                                </div>
                            </div>                         
                            <div class="row">
                                <div class="ln_solid"></div>
                                <div class="form-group">
                                    <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                                      <?php
                                       echo $this->formHidden($form->get('csrf'));
                                       echo $this->formSubmit($form->get('submit')); 
                                       echo $this->form()->closeTag(); 
                                    ?>
                                </div>
                            </div>                          
                        </div>
                    </div>
                </div>
                

                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2><?php echo $this->escapeHtml("List of student to semester registration"); ?></h2>
                            <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                            </ul>
                            <div class="clearfix"></div>
                        </div>
                        <?php
                       
                                // Opening of the form tag
                               $studentSemesterForm->setAttribute('action', $this->url('updatestudentsemester', array('action' => 'updateStudentSemester')));
                                $form->prepare();
                                echo $this->form()->openTag($studentSemesterForm);
                                $studentSemesterForm->get('studentCount')->setValue($this->studentCount);
                                $studentSemesterForm->get('programmes_id')->setValue($this->programmesId);
                                $studentSemesterForm->get('semester_id')->setValue($this->semesterId);
                               // $studentSemesterForm->get('student_section_id')->setValue($student->getStudent_Section_Id());
                                echo $this->formHidden($studentSemesterForm->get('programmes_id'));
                                $studentSemesterForm->get('academic_year')->setValue(date('Y'));
                                echo $this->formHidden($studentSemesterForm->get('id'));  
                                echo $this->formHidden($studentSemesterForm->get('studentCount'));
                                echo $this->formHidden($studentSemesterForm->get('academic_year'));
                                echo $this->formHidden($studentSemesterForm->get('student_section_id'));                            
                        ?>      
                        <div class="x_content">
                            <div  class="table-responsive">
                                <table class="table table-striped responsive-utilities jambo_table bulk_action table-bordered">  
                                    <thead>
                                        <tr class="headings">
                                                                      
                                            <th class="column-title" width="10%">Sl.No. </th>
                                            <th class="column-title" width="10%">ID. </th>
                                            <th class="column-title">Name & Student Id</th>
                                            <th class="column-title">Previous Semester</th>
                                            <th class="column-title">Action</th>
        
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php for($i = 1; $i<=$this->studentCount; $i++) {?>
                                        <tr class="even pointer">
                                            <td class=" "><?php echo $i; ?></td>
                                            <td class=" "><?php echo $studentId[$i]; ?></td>
                                            <td class=" "><?php echo $studentName[$i]; ?></td>
                                            <td class=" "><?php echo $semesterName[$i]; ?></td>
                                            <td class=" "><?php echo $this->formRow($studentSemesterForm->get('semester_id'.$i)); ?></td>
                                            <td class=" "><?php echo $this->formRow($studentSemesterForm->get('student_semester_registration_type')); ?></td>
                                            
                                        </tr>
                                        <?php  }?>
                                    </tbody>
                                </table>
                            </div>
                        </div>

                        <?php
                            echo $this->formHidden($studentSemesterForm->get('csrf'));
                            echo $this->formSubmit($studentSemesterForm->get('submit'));
                            echo $this->form()->closeTag();
                        
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>      
</div>           
       
                