<?php
 // module/EmployeeDetail/view/employee-detail/employee-detail/emppersonaldetail.phtml:

    $title = 'Registered Student List';
    $this->headTitle($title);

     $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    //IDEA-CBC
    //Original
    //$iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('aes-256-cbc'));

    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));

    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}
 
?>
<div class="right_col" role="main">
    <div class="">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                    </ul>
                    <div class="clearfix"></div>
                </div> 

                <div class="col-md-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2><?php echo $this->escapeHtml("Search of Registered Student List")?></h2>
                            <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                            </ul>
                            <div class="clearfix"></div>
                  
                        </div>
                       <?php 
                            if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                                echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                $messages = $this->flashMessenger()->getMessages();
                                foreach($messages as $message) {
                                    echo '<strong>Success!</strong>'. $message;
                                }
                                echo '</div>';
                            }

                            else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                                echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                $messages = $this->flashMessenger()->getMessages();
                                foreach($messages as $message) {
                                    echo '<strong>Failure!</strong>'. $message;
                                }
                                echo '</div>';
                            }
                        ?>
                        <div class="x_content">
                            <h5><i>*(In order to search the list of student  and to register semester to them, you have to compulsory select programme and year from drop down list (whereas name and student id is optionally) and click on search button to display the list of students with respect to the programme and year you select.)<br />
                                        *** For student name you can search with first name and for student id you have to type correct ID. When list display, select section from drop down list and at once you can submit their registered semester** </i></h5>
                                  <br />
                            <?php
                            // Opening of the form tag
                            $form->prepare();
                            echo $this->form()->openTag($form);
                            $form->get('year')->setValueOptions($this->studentYear);
                            $form->get('academic_year')->setValueOptions($this->stdAcademicYear);
                            ?>
                        
                            <div class="row">
                                <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Programme</label>
                                    <?php echo $this->formRow($form->get('programmes_id')); ?>
                                </div>
                                <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Year</label>
                                    <?php echo $this->formRow($form->get('year')); ?>
                                </div>
                                <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Academic Year</label>
                                    <?php echo $this->formRow($form->get('academic_year')); ?>
                                </div>
                                <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Student Name</label>
                                    <?php echo $this->formRow($form->get('student_name')); ?>
                                </div>
                                <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Student ID</label>
                                    <?php echo $this->formRow($form->get('student_id')); ?>
                                </div>
                            </div>                         
                            <div class="row">
                                <div class="ln_solid"></div>
                                <div class="form-group">
                                    <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                                      <?php
                                       echo $this->formHidden($form->get('csrf'));
                                       echo $this->formSubmit($form->get('submit')); 
                                       echo $this->form()->closeTag(); 
                                    ?>
                                </div>
                            </div>                          
                        </div>
                    </div>
                </div>
                

                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2><?php echo $this->escapeHtml("List of student registered for semester"); ?></h2>
                            <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                            </ul>
                            <div class="clearfix"></div>
                        </div>     
                        <div class="x_content">
                            <div  class="table-responsive">
                                <table id="datatable-buttons" class="table table-striped jambo_table bulk_action">  
                                    <thead>
                                        <tr class="headings">
                                                                      
                                            <th class="column-title">Sl.No. </th>
                                            <th class="column-title">Student Id & Name</th>
                                            <th class="column-title">Gender</th>
                                            <th class="column-title">Programme</th>
                                            <th class="column-title">Year</th>
                                            <th class="column-title">Semester</th>
                                            <th class="column-title">Section</th>
                                            <th class="column-title">Academic Year</th>
                                            <th class="column-title">Status</th>
                                            <th class="column-title">Action</th>
        
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php $i=1; ?>
                                    <?php foreach ($this->semesterStudentList as $studentList) : ?>
                                        <tr class="even pointer">
                                            <td class=" " width="8%"><?php echo $i; ?></td>
                                            <td class=" "><?php echo $this->escapeHtml($studentList['student_id']) . ' - ' .
                                                                     $this->escapeHtml($studentList['first_name']) . ' ' .
                                                                     $this->escapeHtml($studentList['middle_name']).' '.
                                                                     $this->escapeHtml($studentList['last_name']).'';?></td>
                                            <td class=" "><?php echo $this->escapeHtml($studentList['stdgender']); ?></td>
                                            <td class=" "><?php echo $this->escapeHtml($studentList['programme_name']); ?></td>
                                            <td class=" "><?php echo $this->escapeHtml($studentList['year']); ?></td>
                                            <td class=" "><?php echo $this->escapeHtml($studentList['semester']); ?></td>
                                            <td class=" "><?php echo $this->escapeHtml($studentList['section']); ?></td>
                                            <td class=" "><?php echo $this->escapeHtml($studentList['academic_year']); ?></td>
                                            <td class=" "><?php echo $this->escapeHtml($studentList['reason']); ?></td>
                                            <td class=" last" width="10%"> <a href="<?php echo $this->url('updatenotreportedstudent', array('id' => my_encrypt($studentList['id'], $key)));?>" class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i> Update </a></td>
                                            
                                        </tr>
                                        <?php $i++; ?>
                                    <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>      
</div> 
</div>
</div>          
       
                