<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
<div class="menu_section">
<br><br><br>
<ul class="nav side-menu">
	<li><a><i class="fa fa-user"></i>Student Service<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>Responsibility<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('responsibilitycategory') ?>">Add New Category</a></li>
					<li><a href="<?php echo $this->url('studentresponsibility') ?>">Assign Student Responsibility</a></li>
					<li><a href="<?php echo $this->url('viewstdresponsibility') ?>">View Responsibility</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Student Disciplinary<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('disciplinarycategory') ?>">Offence Category</a></li>
					<li><a href="<?php echo $this->url('disciplinaryrecord') ?>">Record Disciplinary Problem</a></li>
					<li><a href="<?php echo $this->url('viewdisciplinaryrecord') ?>">View Disciplinary Record</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Character Certificate<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('studentccevaluation') ?>">Character Certificate Evaluation</a></li>
					<li><a href="<?php echo $this->url('viewcharactercert') ?>">View Character Certificate</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Achievement<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('stdcontributioncategory') ?>">Add Category</a></li>
					<li><a href="<?php echo $this->url('studentachievement') ?>">Add Achievement</a></li>
					<li><a href="<?php echo $this->url('viewachievement') ?>">View Achievement</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Student Participation<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('stdparticipation') ?>">Add Participation Record</a></li>
					<li><a href="<?php echo $this->url('viewstdparticipation') ?>">View Participation Record</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Contribution<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('stdcontribution') ?>">Add Contribution</a></li>
					<li><a href="<?php echo $this->url('viewstdcontribution') ?>">View Contribition</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Medical Record<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('stdmedicalrecord') ?>">Add Medical Record</a></li>
					<li><a href="<?php echo $this->url('viewstdmedicalrecord') ?>">View Medical Record</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Leave Management<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('stdleavecategory') ?>">Leave Category</a></li>
					<li><a href="<?php echo $this->url('approvestdleave') ?>">Leave Approval</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Student Suggestion<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('suggestioncommittee') ?>">Suggestion Committee</a></li>
					<li><a href="<?php echo $this->url('stdsuggestioncategory') ?>">Suggestion Category</a></li>
					<li><a href="<?php echo $this->url('viewstdsuggestions') ?>">View Suggestion</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Clubs and Units<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('addclub') ?>">Add Club</a></li>
					<li><a href="<?php echo $this->url('applymembership') ?>">Apply Club Membership</a></li>
					<li><a href="<?php echo $this->url('clubmembershipstatus') ?>">Club Membership Status</a></li>
					<li><a href="<?php echo $this->url('clubmembers') ?>">Club Members</a></li>
			</ul>
			</li>
			<li><a href="<?php echo $this->url('studentlists') ?>">Student Lists</a></li>
		</ul>
	</li>
</ul>
</div>
</div>
