 <?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Short Term Trainings ';
 $this->headTitle($title);
?>
<div class="right_col" role="main">
          <div class="">
          
              <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title)?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                    </ul>
                 <div class="clearfix"></div>
              
                </div>
                   
                <div class="x_content">
                  <br />
                   <?php
                   $form->prepare();
                   echo $this->form()->openTag($form);

                   echo $this->formHidden($form->get('id'));   
                ?>
                <div class="row">  
                    <label class="control-label col-md-1 col-sm-1 col-xs-12"></label>
                 <div class="col-md-4 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Employee ID <span class="required">*</span>
                    </label>
                <?php  echo $this->formRow($form->get('emp_id')); ?>
                </div>
                </div>
                  
                <div class="row">
                        <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12"></label>
                              <div class="col-md-3 col-sm-3 col-xs-12">
                            <button class="btn btn-success" type="submit">Submit</button>                              
                              </div>
                    </div>
                </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                  
          </div>
        </div>
                  </div>
            
              <?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Employee Details ';
 $this->headTitle($title);
?>
              
             <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title)?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                    </ul>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                <form>   
                 <div class="row">
                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Employee Name</label>
                    <input type="text" placeholder="Dorjee  Wangmo Wangda" class="form-control" readonly>
                  </div>

                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Employee ID</label>
                    <input type="text" placeholder="RUB2345" class="form-control" readonly>
                  </div>

                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Position Title</label>
                    <input type="text" placeholder="Finance Officer" class="form-control" readonly>
                  </div>

                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Citizenship  Identity  Card</label>
                    <input type="text" placeholder="10504050409" class="form-control" readonly>
                  </div>
                </div>
                    <div class="row">
                      <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Date of Birth</label>
                    <input type="text" placeholder="03-04-1979" class="form-control" readonly>
                  </div>
                        <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Agency Location</label>
                    <input type="text" placeholder="Thimphu" class="form-control" readonly>
                  </div>
                 <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Contact No.</label>
                    <input type="text" placeholder="18734532" class="form-control" readonly>
                  </div>
                        <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <label>Permanent Address</label>
                    <input type="text" placeholder="Nobgang,Samar,Haa" class="form-control" readonly>
                  </div>
                      </div>
                     
                      </form>
                  
          </div>
        </div>
                  </div> 
              
          <?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Training Approval Form ';
 $this->headTitle($title);
?>    
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title)?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                
                    </ul>
                 <div class="clearfix"></div>
              
                </div>
                   
                <div class="x_content">
                  <br />
                   <?php
                   $form->prepare();
                   echo $this->form()->openTag($form);

                   echo $this->formHidden($form->get('id'));   
                ?>
                <div class="row">    
                 <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Training Order No. 
                    </label>
                <?php  echo $this->formRow($form->get('training_order_no')); ?>
                </div>
            
                 <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Training Order Date  
                    </label>
                <?php  echo $this->formRow($form->get('training_order_date')); ?>
                    </div>
                   <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Training Category
                    </label>
                <?php  echo $this->formRow($form->get('training_category')); ?>
                    </div>   
                  
                 <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Training Type 
                    </label>
                <?php  echo $this->formRow($form->get('training_type')); ?>
                    </div>
                     </div>
                    
                     <div class="row">    
                 <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Course Title 
                    </label>
                <?php  echo $this->formRow($form->get('course_title')); ?>
                    </div>
                   
                 <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Institute / University
                    </label>
                <?php  echo $this->formRow($form->get('institute_university')); ?>
                    </div>
                     
                 <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Training Country 
                    </label>
                <?php  echo $this->formRow($form->get('training_country')); ?>
                    </div>
                      
                 <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Training City 
                    </label>
                <?php  echo $this->formRow($form->get('training_city')); ?>
                    </div>
                     </div>
                    
                     <div class="row">    
                 <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Training Start Date 
                    </label>
                <?php  echo $this->formRow($form->get('training_start_date')); ?>
                    </div>
                    
                 <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Training End  Date 
                    </label>
                <?php  echo $this->formRow($form->get('training_end_date')); ?>
                    </div>
                   
                 <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Source of Funding 
                    </label>
                <?php  echo $this->formRow($form->get('source_of_funding')); ?>
                    </div>
                 
                    <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Security Clearance Certificate No. 
                    </label>
                <?php  echo $this->formRow($form->get('security_clearance_certificate_no')); ?>
                    </div>
                     </div>
                   
                   <div class="row">  
                 <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Audit Clearance Certificate No.
                    </label>
                <?php  echo $this->formRow($form->get('audit_clearance_certificate_no')); ?>
                    </div>
                   
                       <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Medical Fitness Certificate No. 
                    </label>
                <?php  echo $this->formRow($form->get('medical_fitness_certificate_no')); ?>
                    </div>
                     </div>
                  
                <div class="row">
                        <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                              <div class="col-md-6 col-sm-6 col-xs-12">
                    <?php
                        echo $this->formSubmit($form->get('submit')); 
                        echo $this->formSubmit($form->get('reset'));
                      ?>
                    </div>
                    </div>
                    </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                  
          </div>
        </div>
                  </div>
  
          </div></div>
                
                 