<?php
 $title = 'Student Extra-Curricular Attendance';
 $this->headTitle($title);

     //get student list in an array
 $studentName = array();
 $programmeName = array();
 $year = array();
 $studentId = array();
 //$criteriaName = array();
 $i=1;
 $j=1;
 foreach($this->studentList as $student){
    $studentName[$i] = $student['first_name']. ' ' .$student['middle_name'].' '.$student['last_name'];
    $studentId[$i] = $student['studentId'];
    $programmeName[$i] = $student['programme_name'];
    $attendance[$i] = $student['attendance'];
    $year[$i] = $student['enrollment_year'];
    $i++;
 }
?>

 <div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
            
                <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                     <div class="clearfix"></div>
                    </div>
                    <br/>
                        <!-- Adding Extra Curricular Attendance-->
                        <div class="col-md-12 col-xs-12">
                          <div class="x_panel">
                            <div class="x_title">
                              <h2><?php echo $this->escapeHtml("Search for Student to Edit Attendance")?></h2>
                                <ul class="nav navbar-right panel_toolbox">
                                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                  </li>
                            
                                </ul>
                             <div class="clearfix"></div>
                          
                            </div>
                            <?php 
                              if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                                  echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                                  echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                  $messages = $this->flashMessenger()->getMessages();
                                  foreach($messages as $message) {
                                      echo '<strong>Success!</strong>'. $message;
                                  }
                                  echo '</div>';
                              }

                              else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                                  echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                                  echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                  $messages = $this->flashMessenger()->getMessages();
                                  foreach($messages as $message) {
                                      echo '<strong>Failure!</strong>'. $message;
                                  }
                                  echo '</div>';
                              }

                          ?>    
                            <div class="x_content">
                            <h5><i>*(In order to add "attendance" for a student, first search for the student and then select the student from the table below to edit the extra curricular attendance. Input as many fields as possible to narrow the search.)<br/><br/>
                                    *** List of student will display if and only if you have added extra curricular attendance of particular programme for particular events</i>
                                  </h5>
                              <br />
                               <?php
                                // Opening of the form tag
                                $form->prepare();
                                echo $this->form()->openTag($form);
                								//following arguments are set as clubs_id is require
                								$form->get('clubs')->setValue(1);
                								$form->get('date')->setValue(date('Y-m-d'));
                								$form->get('programme')->setValueOptions($this->programmeList);
                								$form->get('social_events_id')->setValueOptions($this->eventList);
                                $form->get('year')->setValueOptions($this->studentYear);
                								echo $this->formHidden($form->get('clubs'));
                								echo $this->formHidden($form->get('date'));
                              ?>
                            
                              <div class="row">
                                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Programme</label>
                                    <?php echo $this->formRow($form->get('programme')); ?>
                                  </div>
                                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Year</label>
                                    <?php echo $this->formRow($form->get('year')); ?>
                                  </div>
                                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Student Name</label>
                                    <?php echo $this->formRow($form->get('student_name')); ?>
                                  </div>
                                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Student Id</label>
                                    <?php echo $this->formRow($form->get('student_id')); ?>
                                  </div>
                                </div>
                              <div class="row">
                                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Event Name</label>
                                    <?php echo $this->formRow($form->get('social_events_id')); ?>
                                  </div>
                               </div>
                             
                             <div class="row">
                                <div class="ln_solid"></div>
                                <div class="form-group">
                                    <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                                      <?php
                                       echo $this->formHidden($form->get('csrf'));
                                       echo $this->formSubmit($form->get('submit')); 
                                       echo $this->form()->closeTag(); 
                                    ?>
                                </div>
                            </div>
                              
                          </div>
                        </div>
                       </div>     
                              
                          
                        <div class="col-md-12 col-sm-12 col-xs-12">
                          <div class="x_panel">
                            <div class="x_title">
                              <h2><?php echo $this->escapeHtml("Attendance for Students"); ?></h2>
                              <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                </li>
                              </ul>
                              <div class="clearfix"></div>
                            </div>
            
                            <div class="x_content">
                              <table class="table   table-striped responsive-utilities jambo_table bulk_action table-bordered">
                                <thead>
                                    <th class="column-title">Sl No </th>
                                    <th class="column-title">Student ID </th>
                                    <th class="column-title">Name </th>
                                    <th class="column-title">Programme </th>
                                    <th class="column-title">Year </th>
                                    <th class="column-title no-link last"><span class="nobr">Attendance</span></th>
                                </thead>
            
                                <tbody>
                                  <?php                      
                									 $i = 1;
                									 // Opening of the form tag
                									 $attendanceForm->setAttribute('action', $this->url('editextracurricularattendance', array('action' => 'updateExtraCurricularAttendance')));
                									 $form->prepare();
                									 echo $this->form()->openTag($attendanceForm);
                									 $attendanceForm->get('date')->setValue($this->date_event);
                									 $attendanceForm->get('social_events_id')->setValue($this->event_name);
                									 $attendanceForm->get('student_count')->setValue($this->studentCount);
                									 $attendanceForm->get('programme')->setValue($this->programme);
                									 $attendanceForm->get('year')->setValue($this->year);
                									 $attendanceForm->get('student_name')->setValue($this->studentName);
                									 $attendanceForm->get('student_id')->setValue($this->studentId);
                									 echo $this->formHidden($attendanceForm->get('id'));
                									 echo $this->formHidden($attendanceForm->get('date'));
                									 echo $this->formHidden($attendanceForm->get('social_events_id'));
                									 echo $this->formHidden($attendanceForm->get('student_count'));
                									 echo $this->formHidden($attendanceForm->get('programme'));
                									 echo $this->formHidden($attendanceForm->get('year'));
                									 echo $this->formHidden($attendanceForm->get('student_name'));
                									 echo $this->formHidden($attendanceForm->get('student_id'));

                                   for($i = 1; $i<=$this->studentCount; $i++) { ?>
                									  <tr class="even pointer">
                										<td class=" "><?php echo $i;?></td>
                                    <td class=" "><?php echo $studentId[$i];?></td>
                										<td class=" "><?php echo $studentName[$i];?></td>
                										<td class=" "><?php echo $programmeName[$i];?></td>
                                    <td class=" "><?php echo $year[$i];?></td>
                                    <td class=" ">
                                      <?php 
                                      
                                      $attendanceForm->get('attendance_'.$i)->setValue($attendance[$i]);
                                      
                                      echo $this->formRow($attendanceForm->get('attendance_'.$i)); 

                                    ?>
                                       
                                    </td>
                									  </tr>
                                  <?php }  
								                  ?>
                               </tbody>
                              </table>
                            </div>
                            <div class="clearfix"></div>
                            <div class="row">
                                    <div class="ln_solid"></div>
                                    <div class="form-group">
                                    <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                                      <?php
                                       echo $this->formHidden($attendanceForm->get('csrf'));
                                       echo $this->formSubmit($attendanceForm->get('submit')); 
                                       echo $this->form()->closeTag(); 
                                    ?>
                                    </div>
                                </div>
                                
                                    <!-- End of Attendance-->
                            </div>
                          </div>
                          
                        </div>
                        
                      </div>
                  </div>
                </div>
              
