<?php
 $title = 'Edit Social Event';
 $this->headTitle($title);
 $event_description = array();
 foreach($this->eventDetail as $detail){
	 $event_description = $detail;
 }
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $title; ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				            $events = $form->get('socialevent');
          					$events->get('id')->setValue($event_description['id']);
          					$events->get('event')->setValue($event_description['event']);
                    $date = explode("-", $event_description['date']);
          					$events->get('date')->setValue($date[01].'/'.$date[02].'/'.$date[00]);
                    $events->get('academic_year')->setValue($event_description['academic_year']);
          					$events->get('event_description')->setValue($event_description['event_description']);
          					$events->get('organisation_id')->setValue($event_description['organisation_id']);
                    echo $this->formHidden($events->get('id')); 
                    echo $this->formHidden($events->get('academic_year'));
          					echo $this->formHidden($events->get('organisation_id')); 
          				  ?>
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-2 col-sm-2 col-xs-12">Event Name: <span class="required">*</span></label>
                    <div class="col-md-8 col-sm-8 col-xs-12">
                      <?php  echo $this->formRow($events->get('event')); ?>
                    </div>
                </div>
                </div>
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-2 col-sm-2 col-xs-12">Event Date: <span class="required">*</span></label>
                    <div class="col-md-3 col-sm-3 col-xs-12">
                      <?php  echo $this->formRow($events->get('date')); ?>
                    </div>
                    <label class="control-label col-md-2 col-sm-2 col-xs-12">Academic Year: <span class="required">*</span></label>
                    <div class="col-md-3 col-sm-3 col-xs-12">
                      <input type="text" value="<?php echo $event_description['academic_year']; ?>" class="form-control" readonly="readonly">
                    </div>
                </div>
                </div>
                <div class="row" >
                <div class="form-group">
                    <label class="control-label col-md-2 col-sm-2 col-xs-12">Event Description:<span class="required">*</span></label>
                    <div class="col-md-8 col-sm-8 col-xs-12">
                      <?php  echo $this->formRow($events->get('event_description')); ?>
                    </div>
                </div> 
                </div>
               
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12"></label>
                              <div class="col-md-3 col-sm-3 col-xs-12">
                    <?php
                        echo $this->formHidden($form->get('csrf'));
            						echo $this->formSubmit($events->get('submit')); 
            						echo $this->form()->closeTag();
                      ?>
                    </div>
                   </div>
                </div>
                       
                </div>
              </div>
            </div>
              
              
               <?php
               $title = 'Social Events';
               $this->headTitle($title);
              ?>
               <div class="col-md-12 col-xs-12">
                  
                  <div class="x_panel">
                      <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                  </div>
                
                    <div class="x_content">
                     <div class="table-responsive">
                      <table id="datatable" class="table table-striped jambo_table table-bordered">
                        <thead>
                          <tr class="headings">
                            <th width="7%" class="column-title">Sl. No</th>
                            <th class="column-title">Event Name </th>
                            <th class="column-title">Date </th>
                            <th class="column-title">Description</th>
                          </tr>
                        </thead>
                        <tbody>
                            <?php $i=1; foreach ($this->events as $event) : ?>
                            <?php                             
                            if($event['academic_year'] == $this->academic_year){
                            ?>
                          <tr class="even pointer">
                            <td class=" "><?php echo $i++;?></td>
                            <td class=" "><?php echo $this->escapeHtml($event['event']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($event['date']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($event['event_description']);?></td>
                          </tr>
                          <?php } ?>
                          <?php endforeach; ?>
                        </tbody>
                      </table>
                    </div>
                    </div>
                
                </div></div></div></div>
             
          </div>
        </div> 
     </div>