<?php

 $title = 'Apply Resignation';
 $this->headTitle($title);
 
 $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));
    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}
 ?>

<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				             $resignation = $form->get('employeeresignation');
                    echo $this->form()->openTag($form);
					         $resignation->get('employee_details_id')->setValue($this->employee_details_id);
                   $resignation->get('resignation_type')->setValueOptions($this->resignationType);
                    echo $this->formHidden($resignation->get('id')); 
        					echo $this->formHidden($resignation->get('employee_details_id'));
        				  ?>  

                  <?php 
                      if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                          echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                          echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                          $messages = $this->flashMessenger()->getMessages();
                          foreach($messages as $message) {
                              echo '<strong>Success!</strong>'. $message;
                          }
                          echo '</div>';
                      }

                      else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                          echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                          echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                          $messages = $this->flashMessenger()->getMessages();
                          foreach($messages as $message) {
                              echo '<strong>Failure!</strong>'. $message;
                          }
                          echo '</div>';
                      }
                      ?>
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Resignation Type:<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($resignation->get('resignation_type')); ?>
                    </div>
                </div>
                </div>
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Date of Application:<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($resignation->get('date_of_application')); ?>
                    </div>
                </div>
                </div>
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Reason:<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($resignation->get('reason_for_resignation')); ?>
                    </div>
                </div>
                </div> 
                  
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
          						<?php
          						   echo $this->formHidden($form->get('csrf'));
          						   echo $this->formSubmit($resignation->get('submit')); 
                      ?>
                    	</div>
                    </div>
               </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                </div>
              </div>
               <div class="x_panel">
                  <div class="x_title">
                    <h2><?php echo $this->escapeHtml("Edit Resignation Details"); ?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                    </ul>
                  <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <div class="table-responsive">
                      <table class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Sl No</th>
                            <th class="column-title">Resignation Type</th>
                            <th class="column-title"><span class="nobr">Application Receive Date</span></th>
                            <th class="column-title"><span class="nobr">Status</span></th>
                            <th class="column-title no-link last"><span class="nobr">Action</span></th>
                          </tr>
                        </thead>
                        <tbody>
						              <?php $i=1; foreach ($this->resignation_details as $resignation) : ?>
                          <tr class="even pointer">
                            <td class=" "><?php echo $i++;?></td>
                            <td class=" "><?php echo $this->escapeHtml($resignation['resignation_type']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($resignation['date_of_application']);?></td>
                            <td class=" ">
                              <?php if($resignation['resignation_status'] == NULL){
                                 echo "Still Pending";
                                 }else{
                                ?>
                              <?php echo $this->escapeHtml($resignation['resignation_status']);?></td>
                          <?php }?>
                            <td>
                              <?php if(($resignation['resignation_status'] == 'Approved')||($resignation['resignation_status'] == 'Rejected')){?><a href="<?php echo $this->url('viewresignationdetails', array('id' => my_encrypt($resignation['id'], $key)));?>" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> View</a>
                            <?php }else if($resignation['resignation_status'] == NULL){?>
                            	<a href="<?php echo $this->url('editresignationdetails', array('id' => my_encrypt($resignation['id'], $key)));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit</a>
                                <a href="<?php echo $this->url('deleteresignationdetails', array('id' => my_encrypt($resignation['id'], $key)));?>" class="btn btn-danger btn-xs"><i class="fa fa-trash"></i> Delete</a>
                              <?php } ?>
                              </td>
                          </tr>
                          <?php endforeach; ?>
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
        	</div>
          </div>
        </div> 
     </div>
    </div>
            
         
              
       
                