<?php

 $title = 'Issue No Dues Certificate (Library)';
 $this->headTitle($title);
 ?>

<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				            $resignation = $form->get('dues');
                    $resignation->get('issuing_authority')->setValue($this->library_clearance_authority);
                    $resignation->get('emp_resignation_id')->setValue($this->emp_resignation_id);
                    echo $this->formHidden($resignation->get('id')); 
          					echo $this->formHidden($resignation->get('issuing_authority'));
          					echo $this->formHidden($resignation->get('emp_resignation_id'));
          				  ?>  
                
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Remarks:<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($resignation->get('remarks')); ?>
                    </div>
                </div>
                </div>
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Date of Issue:<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($resignation->get('date_of_issue')); ?>
                    </div>
                </div>
                </div>
                  
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
						<?php
						   echo $this->formHidden($form->get('csrf'));
						   echo $this->formSubmit($resignation->get('submit')); 
                        ?>
                    	</div>
                    </div>
               </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                </div>
              </div>
        </div>

             
          </div>
        </div> 
     </div>
            
         
              
       
                