<?php
 $title = 'Resignation Approval List';
 $this->headTitle($title);
 
 
 $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));
    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}

?>

 <div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                    </ul>
                  <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <?php 
                      if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                          echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                          echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                          $messages = $this->flashMessenger()->getMessages();
                          foreach($messages as $message) {
                              echo '<strong>Success!</strong>'. $message;
                          }
                          echo '</div>';
                      }

                      else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                          echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                          echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                          $messages = $this->flashMessenger()->getMessages();
                          foreach($messages as $message) {
                              echo '<strong>Failure!</strong>'. $message;
                          }
                          echo '</div>';
                      }
                      ?>
                    <div class="table-responsive">
                      <table id="datatable" class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Sl No </th>
                            <th class="column-title">Staff Name </th>
                            <th class="column-title">Staff ID </th>
                            <th class="column-title">Resignation Type</th>
                            <th class="column-title"><span class="nobr">Application Date</span></th>
                             <th class="column-title"><span class="nobr">Order Date</span></th>
                            <th class="column-title"><span class="nobr">Status</span></th>
                            <th class="column-title no-link last"><span class="nobr">Action</span></th>
                          </tr>
                        </thead>
                        <tbody>
						  <?php $i=1; foreach ($this->separationRecordList as $list) : ?>
                          <tr class="even pointer">
                            <td class=" "><?php echo $i++; ?></td>
                            <td class=" "><?php echo $this->escapeHtml($list['first_name'].' '.$list['middle_name'].' '.$list['last_name']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($list['emp_id']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($list['resignation_type']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($list['date_of_application']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($list['separation_order_date']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($list['resignation_status']);?></td>
                            <td class=" last"> <a href="<?php echo $this->url('empseparationrecorddetails', array('id' => my_encrypt($list['id'], $key)));?>" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> View Record</a>

                            <?php if(!empty($list['relieving_order_file'])){?>
                              <a href="<?php echo $this->url('downloadseparationrecordfile', array('id' => my_encrypt($list['id'], $key))); ?>" class="btn btn-primary btn-xs"><i class="fa fa-download"></i> Download</a>
                            <?php }else {?>
                              <?php echo "No File Uploaded"; ?>
                            <?php }?>
                          </td>
                          </tr>
                          <?php endforeach; ?>
                        </tbody> 
                      </table>
                    </div>
                  </div>
                </div>
              </div>
     </div>     
 </div>
                         
                     