<?php
 $title = 'Add Employee Responsibility';
 $this->headTitle($title);

 $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    //IDEA-CBC
    //Original
    //$iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('aes-256-cbc'));

    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));

    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}
 ?>
<div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <div class="clearfix"></div>
                  </div>
                    
                  <div class="x_content">
                    <br/>
					<?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				    $responsibility = $form->get('employeeresponsibility');
					$responsibility->get('id')->setValue($this->employeeResponsibilityDetail->getId());
          $responsibility->get('employee_details_id')->setValue($this->employeeResponsibilityDetail->getEmployee_Details_Id());
          $responsibility->get('responsibility_category_id')->setValue($this->employeeResponsibilityDetail->getResponsibility_Category_Id());
          $responsibility->get('responsibility_name')->setValue($this->employeeResponsibilityDetail->getResponsibility_Name());
           $responsibility->get('remarks')->setValue($this->employeeResponsibilityDetail->getRemarks());
            $responsibility->get('start_date')->setValue(date("m/d/y", strtotime($this->employeeResponsibilityDetail->getStart_Date())));
             $responsibility->get('end_date')->setValue(date("m/d/y", strtotime($this->employeeResponsibilityDetail->getEnd_Date())));
              $responsibility->get('evidence_file')->setValue($this->employeeResponsibilityDetail->getEvidence_File());
          $responsibility->get('responsibility_category_id')->setValueOptions($this->responsibility_category);
                    echo $this->formHidden($responsibility->get('id'));
					echo $this->formHidden($responsibility->get('employee_details_id'));
                    ?>
                    <?php if($this->message == NULL && $this->flashMessenger()->hasMessages()) {
							echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
							echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
							$messages = $this->flashMessenger()->getMessages();
							foreach($messages as $message) {
								echo '<strong>Success!</strong>'. $message;
							}
							echo '</div>';
                    	} else if($this->message =='Failure' && $this->flashMessenger()->hasMessages()) {
                            echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                            echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                            $messages = $this->flashMessenger()->getMessages();
                            foreach($messages as $message) {
                                echo '<strong>Warning!</strong>'. $message;
                            }
                            echo '</div>';
                     }  ?>
                    <div class="row">
                    <div class="form-group">
                        <label class="control-label col-md-1 col-sm-2 col-xs-12">Staff Name <span class="required">*</span></label>
                        <div class="col-md-3 col-sm-3 col-xs-12">
                       		<input type="text" placeholder="<?php echo $this->employeeResponsibilityDetail->getFirst_Name(). ' '.$this->employeeResponsibilityDetail->getMiddle_Name(). ' '.$this->employeeResponsibilityDetail->getLast_Name(); ?>" class="form-control col-md-7 col-xs-12" disabled="disabled">
                        </div>
                      <label class="control-label col-md-3 col-sm-2 col-xs-12">Staff ID <span class="required">*</span></label>
                        <div class="col-md-3 col-sm-3 col-xs-12">
                        	<input type="text" placeholder="<?php echo $this->employeeResponsibilityDetail->getEmp_Id(); ?>" class="form-control col-md-7 col-xs-12" disabled="disabled">
                        </div>
                      </div>
                    </div>
                    
                    <div class="ln_solid"></div>
                    <br />
                    <div class="x_title">
                        <h2><?php echo $this->escapeHtml($title); ?></h2>
                        <div class="clearfix"></div>
                    </div>
                    <br />
                    <div class="row">
                     <div class="col-md-12 center-margin">
                      <div class="form-group col-md-3 col-sm-3 col-xs-12">
                          <label>Responsibility Category</label>
              <?php echo $this->formRow($responsibility->get('responsibility_category_id')); ?>
                        </div>
                        <div class="form-group col-md-3 col-sm-3 col-xs-12">
                          <label>Responsibility Name</label>
						  <?php echo $this->formRow($responsibility->get('responsibility_name')); ?>
                        </div>
                        <div class="form-group col-md-3 col-sm-3 col-xs-12">
                          <label>Start Date</label>
						  <?php echo $this->formRow($responsibility->get('start_date')); ?>
                        </div>
                        <div class="form-group col-md-3 col-sm-3 col-xs-12">
                          <label>End Date</label>
						  <?php echo $this->formRow($responsibility->get('end_date')); ?>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                     <div class="col-md-12 center-margin">
                        <div class="form-group col-md-3 col-sm-3 col-xs-12">
                          <label>Remarks</label>
						  <?php echo $this->formRow($responsibility->get('remarks')); ?>
                        </div>
                        <div class="form-group col-md-3 col-sm-3 col-xs-12">
                          <label>Evidence File:</label>
              <?php echo $this->formRow($responsibility->get('evidence_file')); ?>
                        </div>
                     </div>
                    </div>
                    <div class="row">
                       <div class="ln_solid"></div>
                    	  <div class="form-group">
                           <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                            <div class="col-md-3 col-sm-3 col-xs-12">
                            <?php
                               echo $this->formHidden($form->get('csrf')); 
							   echo $this->formSubmit($responsibility->get('submit'));
                               echo $this->form()->closeTag();
                            ?>
                            </div>
                    	  </div>
                     </div>
                 </div>
              </div>
           </div>
        </div>
     </div>
            