<?php
 $title = 'Staff Details';
 $this->headTitle($title);

  $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));
    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}
 ?>
  <div class="right_col" role="main">
          <div class="">
              <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <?php if($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                    echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                    echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                      $messages = $this->flashMessenger()->getMessages();
                      foreach($messages as $message) {
                        echo '<strong>Success!</strong>'. $message;
                      }
                      echo '</div>';
                      } else if($this->message =='Failure' && $this->flashMessenger()->hasMessages()) {
                            echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                            echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                            $messages = $this->flashMessenger()->getMessages();
                            foreach($messages as $message) {
                                echo '<strong>Warning!</strong>'. $message;
                            }
                            echo '</div>';
                     } ?>

                     <div class="row">
                    <div class="form-group">
                        <label class="control-label col-md-1 col-sm-2 col-xs-12">Staff Name <span class="required">*</span></label>
                        <div class="col-md-3 col-sm-3 col-xs-12">
                          <input type="text" placeholder="<?php echo $this->employeeDetails->getFirst_Name(). ' '.$this->employeeDetails->getMiddle_Name(). ' '.$this->employeeDetails->getLast_Name(); ?>" class="form-control col-md-7 col-xs-12" disabled="disabled">
                        </div>
                      <label class="control-label col-md-3 col-sm-2 col-xs-12">Staff ID <span class="required">*</span></label>
                        <div class="col-md-3 col-sm-3 col-xs-12">
                          <input type="text" placeholder="<?php echo $this->employeeDetails->getEmp_Id(); ?>" class="form-control col-md-7 col-xs-12" disabled="disabled">
                        </div>
                      </div>
                    </div>
                    <br />
                    <div class="ln_solid"></div>
                    <br />
                  </div>

                  <!-- Staff Permanent Address--> 
                  <div class="x_panel">
                    <div class="x_title">
                      <h2><?php echo $this->escapeHtml("Edit Staff Address Details"); ?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                    </div>

                    <div class="x_content">
                      <?php 
                      $detailForm->setAttribute('action', $this->url('editemppersonaldetails', array('action' => 'editEmployeePersonalDetails', 'id' => my_encrypt($this->id, $key))));
                      $detailForm->prepare(); 
                      echo $this->form()->openTag($detailForm);
                      $details = $detailForm->get('employeedetails');
                      $details->get('id')->setValue($this->employeeDetails->getId());
                      $details->get('emp_id')->setValue($this->employeeDetails->getEmp_Id());
                      $details->get('first_name')->setValue($this->employeeDetails->getFirst_Name());
                      $details->get('middle_name')->setValue($this->employeeDetails->getMiddle_Name());
                       $details->get('last_name')->setValue($this->employeeDetails->getLast_Name());
						            $date_of_birth = explode("-", $this->employeeDetails->getDate_Of_Birth());
                       $details->get('date_of_birth')->setValue($date_of_birth[01].'/'.$date_of_birth[02].'/'.$date_of_birth[00]);
                        $details->get('gender')->setValue($this->employeeDetails->getGender());
                         $details->get('marital_status')->setValue($this->employeeDetails->getMarital_Status());
                          $details->get('previous_emp_id')->setValue($this->employeeDetails->getEmp_Id());
                          $details->get('cid')->setValue($this->employeeDetails->getCid());
                           $details->get('country')->setValue($this->employeeDetails->getCountry());
                            $details->get('nationality')->setValue($this->employeeDetails->getNationality());
                             $details->get('phone_no')->setValue($this->employeeDetails->getPhone_No());
                              $details->get('email')->setValue($this->employeeDetails->getEmail());
                               $details->get('blood_group')->setValue($this->employeeDetails->getBlood_Group());
                                $details->get('religion')->setValue($this->employeeDetails->getReligion());

                                $details->get('emp_house_no')->setValue($this->employeeDetails->getEmp_House_No());
                                $details->get('emp_thram_no')->setValue($this->employeeDetails->getEmp_Thram_No());
                                $details->get('organisation_id')->setValue($this->employeeDetails->getOrganisation_Id());
                                $details->get('departments_id')->setValue($this->employeeDetails->getDepartments_Id());
                                $details->get('departments_units_id')->setValue($this->employeeDetails->getDepartments_Units_Id());
                                $recruitment_date = explode("-", $this->employeeDetails->getRecruitment_Date());
                                $details->get('recruitment_date')->setValue($recruitment_date[01].'/'.$recruitment_date[02].'/'.$recruitment_date[00]);
                                 $details->get('emp_resignation_id')->setValue($this->employeeDetails->getEmp_Resignation_Id());
                                 $details->get('emp_dzongkhag')->setValue($this->employeeDetails->getEmp_Dzongkhag());
                                 $details->get('emp_gewog')->setValue($this->employeeDetails->getEmp_Gewog());
                                 $details->get('emp_village')->setValue($this->employeeDetails->getEmp_Village());

                                 $details->get('profile_picture')->setValue($this->employeeDetails->getProfile_Picture());
                                $details->get('emp_type')->setValue($this->employeeDetails->getEmp_Type());


                                 $details->get('gender')->setValueOptions($this->gender);
                                 $details->get('marital_status')->setValueOptions($this->maritialStatus);
                                 $details->get('country')->setValueOptions($this->country);
                                 $details->get('nationality')->setValueOptions($this->nationality);
                                 $details->get('blood_group')->setValueOptions($this->bloodGroup);
                                 $details->get('religion')->setValueOptions($this->religion);

                                 echo $this->formHidden($details->get('emp_id'));
                                 echo $this->formHidden($details->get('emp_house_no'));
                                 echo $this->formHidden($details->get('emp_thram_no'));
                                 echo $this->formHidden($details->get('organisation_id'));
                                 echo $this->formHidden($details->get('departments_id'));
                                 echo $this->formHidden($details->get('departments_units_id'));
                                 //echo $this->formHidden($details->get('recruitment_date'));
                                 echo $this->formHidden($details->get('emp_resignation_id'));
                                 echo $this->formHidden($details->get('emp_dzongkhag'));
                                 echo $this->formHidden($details->get('emp_gewog'));
                                 echo $this->formHidden($details->get('emp_village'));
                                 echo $this->formHidden($details->get('profile_picture'));
                                 echo $this->formHidden($details->get('emp_type'));
                                  echo $this->formHidden($details->get('previous_emp_id'));

                                 $details->get('submit')->setValue('Update Personal Details');
                                  echo $this->formHidden($details->get('id'));
                      ?>

                      <div class="row">
                        <div class="form-group">  
                            <label class="control-label col-md-2 col-sm-2 col-xs-12">First Name:</label>
                           <div class="col-md-2 col-sm-2 col-xs-12">
                              <?php echo $this->formRow($details->get('first_name')); ?>
                            </div>
                           <label class="control-label col-md-1 col-sm-3 col-xs-12">Middle Name:</label>
                           <div class="col-md-2 col-sm-2 col-xs-12">
                              <?php echo $this->formRow($details->get('middle_name')); ?>
                            </div>
                            <label class="control-label col-md-1 col-sm-2 col-xs-12">Last Name:</label>
                           <div class="col-md-2 col-sm-2 col-xs-12">
                              <?php echo $this->formRow($details->get('last_name')); ?>
                            </div>
                        </div>
                      </div>
                      <div class="row">
                        <div class="form-group">  
                            <label class="control-label col-md-2 col-sm-2 col-xs-12">Date of Birth:(mm/dd/yyyy)</label>
                           <div class="col-md-2 col-sm-2 col-xs-12">
                              <?php echo $this->formRow($details->get('date_of_birth')); ?>
                            </div>
                            <label class="control-label col-md-1 col-sm-3 col-xs-12">Maritial Status:</label>
                               <div class="col-md-2 col-sm-2 col-xs-12">
                                  <?php echo $this->formRow($details->get('marital_status')); ?>
                                </div>
                                <label class="control-label col-md-1 col-sm-2 col-xs-12">Gender:</label>
                               <div class="col-md-2 col-sm-2 col-xs-12">
                                  <?php echo $this->formRow($details->get('gender')); ?>
                                </div>
                        </div>
                      </div>

                      <div class="row">
                        <div class="form-group">  
                            <label class="control-label col-md-2 col-sm-2 col-xs-12">CID:<br><small>(In case of non-national, plese enter work permit no.)</small></label>
                           <div class="col-md-2 col-sm-2 col-xs-12">
                              <?php echo $this->formRow($details->get('cid')); ?>
                            </div>
                            <label class="control-label col-md-1 col-sm-3 col-xs-12">Country:</label>
                               <div class="col-md-2 col-sm-2 col-xs-12">
                                  <?php echo $this->formRow($details->get('country')); ?>
                                </div>
                                <label class="control-label col-md-1 col-sm-2 col-xs-12">Nationality:</label>
                               <div class="col-md-2 col-sm-2 col-xs-12">
                                  <?php echo $this->formRow($details->get('nationality')); ?>
                                </div>
                        </div>
                      </div>

                      <div class="row">
                            <div class="form-group">  
                                <label class="control-label col-md-2 col-sm-2 col-xs-12">Phone No:</label>
                               <div class="col-md-2 col-sm-2 col-xs-12">
                                  <?php echo $this->formRow($details->get('phone_no')); ?>
                                </div>
                                <label class="control-label col-md-1 col-sm-2 col-xs-12">E-mail:</label>
                               <div class="col-md-2 col-sm-2 col-xs-12">
                                  <?php echo $this->formRow($details->get('email')); ?>
                                </div>
                                <label class="control-label col-md-1 col-sm-2 col-xs-12">Recruitment Date:(mm/dd/yyyy)</label>
                               <div class="col-md-2 col-sm-2 col-xs-12">
                                  <?php echo $this->formRow($details->get('recruitment_date')); ?>
                                </div>
                            </div>
                          </div>
                          <br />
                          <div class="row">
                            <div class="form-group">  
                                <label class="control-label col-md-2 col-sm-2 col-xs-12">Blood Group:</label>
                               <div class="col-md-2 col-sm-2 col-xs-12">
                                  <?php echo $this->formRow($details->get('blood_group')); ?>
                                </div>
                                <label class="control-label col-md-1 col-sm-2 col-xs-12">Religion:</label>
                               <div class="col-md-2 col-sm-2 col-xs-12">
                                  <?php echo $this->formRow($details->get('religion')); ?>
                                </div>
                                <label class="control-label col-md-1 col-sm-2 col-xs-12">Staff ID:</label>
                               <div class="col-md-2 col-sm-2 col-xs-12">
                                  <input type="text" class="form-control" placeholder="<?php echo $this->employeeDetails->getEmp_Id(); ?>" disabled="disabled">
                                </div>
                            </div>
                          </div>                     

                       <div class="ln_solid"></div>
                          <div class="row">
                            <div class="form-group">
                              <div class="col-md-12 col-sm-12 col-xs-12 col-md-offset-0">
                                <?php  
                                echo $this->formHidden($detailForm->get('csrf'));
                                echo $this->formSubmit($details->get('submit')); 
                                echo $this->form()->closeTag();
                                ?>
                                <a href="<?php echo $this->url('updateempinitialdetails');?>"><span class="btn btn-primary"><i class="fa fa-angle-double-left"></i> Back</span></a>
                                <a href="<?php echo $this->url('addempeducation', array('id' => my_encrypt($this->id, $key)));?>"><span class="btn btn-info">Next <i class="fa fa-angle-double-right"></i></span></a>
                              </div>
                            </div>
                          </div>
                    </div>
                  </div>

                  <!--Staff Personal Details -->
                  <div class="x_panel">
                    <div class="x_title">
                      <h2><?php echo $this->escapeHtml("Edit Personal Details"); ?></h2>
                      <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                    </ul>
                    <div class="clearfix"></div>
                    </div>

                    <div class="x_content">
                      <?php
                      // Opening of the form tag
                      $form->prepare();
                      echo $this->form()->openTag($form);
                      $employee = $form->get('employeedetails');
                       $employee->get('id')->setValue($this->permanentAddress->getId());
                       $employee->get('emp_id')->setValue($this->permanentAddress->getEmp_Id());
                       $employee->get('first_name')->setValue($this->permanentAddress->getFirst_Name());
                       $employee->get('middle_name')->setValue($this->permanentAddress->getMiddle_Name());
                       $employee->get('last_name')->setValue($this->permanentAddress->getLast_Name());
                       $employee->get('cid')->setValue($this->permanentAddress->getCid());
                       $employee->get('nationality')->setValue($this->permanentAddress->getNationality());
                       $employee->get('country')->setValue($this->permanentAddress->getCountry());
                      $employee->get('date_of_birth')->setValue($this->permanentAddress->getDate_Of_Birth());
                      $employee->get('emp_house_no')->setValue($this->permanentAddress->getEmp_House_No());
                      $employee->get('emp_thram_no')->setValue($this->permanentAddress->getEmp_Thram_No());
                      $employee->get('organisation_id')->setValue($this->permanentAddress->getOrganisation_Id());
                      $employee->get('departments_id')->setValue($this->permanentAddress->getDepartments_Id());
                      $employee->get('departments_units_id')->setValue($this->permanentAddress->getDepartments_Units_Id());
                      $employee->get('recruitment_date')->setValue($this->permanentAddress->getRecruitment_Date());
                       $employee->get('emp_resignation_id')->setValue($this->permanentAddress->getEmp_Resignation_Id());

                        $employee->get('gender')->setValue($this->permanentAddress->getGender());
                         $employee->get('marital_status')->setValue($this->permanentAddress->getMarital_Status());
                          $employee->get('phone_no')->setValue($this->permanentAddress->getPhone_No());
                              $employee->get('email')->setValue($this->permanentAddress->getEmail());
                               $employee->get('blood_group')->setValue($this->permanentAddress->getBlood_Group());
                                $employee->get('religion')->setValue($this->permanentAddress->getReligion());
                                $employee->get('profile_picture')->setValue($this->permanentAddress->getProfile_Picture());
                                $employee->get('emp_type')->setValue($this->permanentAddress->getEmp_Type());

                      echo $this->formHidden($employee->get('emp_id'));
                      echo $this->formHidden($employee->get('first_name'));
                      echo $this->formHidden($employee->get('middle_name'));
                      echo $this->formHidden($employee->get('last_name'));
                      echo $this->formHidden($employee->get('cid'));
                      echo $this->formHidden($employee->get('nationality'));
                      echo $this->formHidden($employee->get('country'));
                      echo $this->formHidden($employee->get('date_of_birth'));
                      echo $this->formHidden($employee->get('organisation_id'));
                      echo $this->formHidden($employee->get('departments_id'));
                      echo $this->formHidden($employee->get('departments_units_id'));
                       echo $this->formHidden($employee->get('recruitment_date'));
                        echo $this->formHidden($employee->get('emp_resignation_id'));
                        echo $this->formHidden($employee->get('gender'));
                        echo $this->formHidden($employee->get('marital_status'));
                        echo $this->formHidden($employee->get('phone_no'));
                        echo $this->formHidden($employee->get('email'));
                        echo $this->formHidden($employee->get('blood_group'));
                        echo $this->formHidden($employee->get('religion'));
                        echo $this->formHidden($employee->get('profile_picture'));
                        echo $this->formHidden($employee->get('emp_type'));
                      $employee->get('submit')->setValue('Update Permanent Address');
                      echo $this->formHidden($employee->get('id'));
                       
                     ?> 
			
			<div class="table-responsive">
                       <table class="table table-striped responsive-utilities jambo_table bulk_action table-bordered">
                         <thead>
                                <tr class="headings">
                                    <th class="column-title">Dzongkhag </th>
                                    <th class="column-title">Gewog </th>
                                    <th class="column-title">Village</th>
                                </tr>
                            </thead>
                            <tbody>
                            <?php if(!empty($this->empPermanentAddr)) {?>
                            <?php foreach ($this->empPermanentAddr as $address) : ?>
                                <tr class="even pointer">
                                    <td class=" "><?php echo $this->escapeHtml($address['dzongkhag_name']); ?></td>
                                    <td class=" "><?php echo $this->escapeHtml($address['gewog_name']); ?></td>
                                    <td class=" "><?php echo $this->escapeHtml($address['village_name']); ?></td>
                                </tr>
                            <?php endforeach; ?>
                            <?php } else{?>
                              <p>No data, please update it.</p>
                            <?php } ?>
                            </tbody>
                       </table>
                     </div>
                     <br><br>
                     
                     <div class="row">
                            <div class="form-group">  
                                <label class="control-label col-md-2 col-sm-2 col-xs-12">House No:</label>
                               <div class="col-md-2 col-sm-2 col-xs-12">
                                  <?php echo $this->formRow($employee->get('emp_house_no')); ?>
                                </div>
                               <label class="control-label col-md-1 col-sm-3 col-xs-12">Thram No:</label>
                               <div class="col-md-2 col-sm-2 col-xs-12">
                                  <?php echo $this->formRow($employee->get('emp_thram_no')); ?>
                                </div>
                            </div>
                          </div>

                          <div class="row">
                            <div class="form-group">  
                                <label class="control-label col-md-2 col-sm-2 col-xs-12">Dzongkhag:</label>
                               <div class="col-md-2 col-sm-2 col-xs-12">
                                  <?php echo $this->formRow($form->get('emp_dzongkhag')); ?>
                                </div>
                               <label class="control-label col-md-1 col-sm-3 col-xs-12">Gewog:</label>
                               <div class="col-md-2 col-sm-2 col-xs-12">
                                  <?php echo $this->formRow($form->get('emp_gewog')); ?>
                                </div>
                                <label class="control-label col-md-1 col-sm-3 col-xs-12">Village:</label>
                               <div class="col-md-2 col-sm-2 col-xs-12">
                                  <?php echo $this->formRow($form->get('emp_village')); ?>
                                </div>
                            </div>
                          </div>   

                          <div class="ln_solid"></div>
                          <div class="row">
                            <div class="form-group">
                              <div class="col-md-12 col-sm-12 col-xs-12 col-md-offset-0">
                                <?php  
                                echo $this->formHidden($form->get('csrf'));
                                echo $this->formSubmit($employee->get('submit')); 
                                echo $this->form()->closeTag();
                                ?>
                                <a href="<?php echo $this->url('updateempinitialdetails');?>"><span class="btn btn-primary"><i class="fa fa-angle-double-left"></i> Back</span></a>
                                <a href="<?php echo $this->url('addempeducation', array('id' => my_encrypt($this->id, $key)));?>"><span class="btn btn-info">Next <i class="fa fa-angle-double-right"></i></span></a>
                              </div>
                            </div>
                          </div>
                    </div>
                  </div>       
             </div> <!-- End of x_content-->
            </div> <!-- End of x_panel-->
        </div> 
        </div>
     </div>
   </div>
 </div>
