<?php
 $title = 'Staff Details';
 $this->headTitle($title);
 
 $staffDetail = array();
 foreach($this->staffRequisitionForward as $requisitionForwarded)
 {
     $staffDetail['name'] = $requisitionForwarded['first_name'] . ' '. $requisitionForwarded['middle_name'] . ' ' .$requisitionForwarded['last_name'];
     $staffDetail['emp_id'] = $requisitionForwarded['emp_id'];
     $staffDetail['department_name'] = $requisitionForwarded['department_name'];
     $staffDetail['unit_name'] = $requisitionForwarded['unit_name'];
 }
 ?>
<div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                  </div>
                    
                  <div class="x_content">
                    <br/>
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
                            $staffDetails = $form->get('goodsrequisitionapproval');
                    echo $this->form()->openTag($form);
                    $staffDetails->get('emp_id')->setValue($this->id);
                            echo $this->formHidden($staffDetails->get('id'));
                            echo $this->formHidden($staffDetails->get('emp_id'));
                    
                  ?>  
                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Staff Name</label>
                        <div class="col-md-3 col-sm-3 col-xs-12">
                            <input type="text" placeholder="<?php echo $staffDetail['name']; ?>" class="form-control col-md-7 col-xs-12" disabled="disabled">
                        </div>
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Staff ID</label>
                        <div class="col-md-3 col-sm-3 col-xs-12">
                            <input type="text" placeholder="<?php echo $staffDetail['emp_id']; ?>" class="form-control col-md-7 col-xs-12" disabled="disabled">
                        </div>
                      </div>
                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Depatment</label>
                        <div class="col-md-3 col-sm-3 col-xs-12">
                            <input type="text" placeholder="<?php echo $staffDetail['department_name']; ?>" class="form-control col-md-7 col-xs-12" disabled="disabled">
                        </div>
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Department Unit</label>
                        <div class="col-md-3 col-sm-3 col-xs-12">
                            <input type="text" placeholder="<?php echo $staffDetail['unit_name']; ?>" class="form-control col-md-7 col-xs-12" disabled="disabled">
                        </div>
                      </div>              
                   
                    <div class="ln_solid"></div>
                   <?php
                    echo $this->form()->closeTag();
                    ?>
                       
                    
                  </div>
                </div>

                <!-- Start of table listing item to issue -->
                <div class="x_panel">
                  <div class="x_title">
                    <h2><?php echo $this->escapeHtml('Goods Requisition Forwarded List Details'); ?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <h5><i>*The following are the list of the item applied for requisition by above particualr selected staff and Forwarded</i></h5>
                  <br />
                  <div class="x_content">
                     <div class="table-responsive">
                      <table id="datatable" class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">     
                            <th class="column-title">Sl.No. </th>
                            <th class="column-title">Item Category </th>
                            <th class="column-title">Sub Category Type </th>
                            <th class="column-title">Item Name</th>
                            <th class="column-title">Quantity Type</th>
                            <th class="column-title">Quantity</th>
                            <th class="column-title">Applied Date</th>
                            <th class="column-title">Remarks</th>
                            <th class="column-title">Action</th>
                          </tr>
                        </thead>
                        <tbody>
                        <?php $i=1; ?>
                        <?php foreach ($this->staffRequisitionForwardList as $equisitionForwardList) : ?>
                            <tr>
                                 <td class=" "><?php echo $i; ?></td>
                                  <td class=" "><?php echo $this->escapeHtml($equisitionForwardList['category_type']);?></td>
                                   <td class=" "><?php echo $this->escapeHtml($equisitionForwardList['sub_category_type']);?></td>
                                   <td class=" "><?php echo $this->escapeHtml($equisitionForwardList['item_name']);?></td>
                                   <td class=" "><?php echo $this->escapeHtml($equisitionForwardList['item_quantity_type']);?></td>
                                   <td class=" "><?php echo $this->escapeHtml($equisitionForwardList['requisition_item_quantity']);?></td>
                                   <td class=" "><?php echo $this->escapeHtml($equisitionForwardList['requisition_date']);?></td>
                                    <td class=" "><?php echo $this->escapeHtml($equisitionForwardList['requisition_remarks']);?></td>
                                    <td class="last"> <a href="<?php echo $this->url('requisition-approval', array('id' => $equisitionForwardList['id']));?>" class="btn btn-primary btn-xs"><i class="fa fa-eye"></i> View Details </button></a></td>
                                                                       
                            </tr>
                            <?php $i++; ?>
                         <?php endforeach; ?>
                        </tbody>
                      </table>
                     </div>
                 </div>
             </div>
              </div>
           </div>
         </div>
