<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
<div class="menu_section">
<br><br><br>
<ul class="nav side-menu">
	<li><a><i class="fa fa-graduation-cap"></i>Academic<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>Academic Assessment<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>Continuous Assessment<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('academicassessment') ?>">Add CA Marks</a></li>
						<li><a href="<?php echo $this->url('viewassessmentmarks') ?>">View CA Marks</a></li>
						<li><a href="<?php echo $this->url('editassessmentmarks') ?>">Edit/Moderate CA Marks</a></li>
						<li><a href="<?php echo $this->url('compileassessmentmarks') ?>">Compile CA Marks</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Semester End<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('semesterassessment') ?>">Add SE Marks</a></li>
						<li><a href="<?php echo $this->url('viewsemestermarks') ?>">View SE Marks</a></li>
						<li><a href="<?php echo $this->url('editsemestermarks') ?>">Edit/Moderate SE Marks</a></li>
						<li><a href="<?php echo $this->url('compilesemestermarks') ?>">Compile SE Marks</a></li>
					</ul>
					</li>
			</ul>
			</li>
			<li><a><i class=""></i>Assessment Mark Allocation<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('addallocationmark') ?>">Allocate Assessment Marks</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Timetable<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('addtimetable') ?>">Add Timetable</a></li>
					<li><a href="<?php echo $this->url('viewtutortimetable') ?>">View Tutor Timetable</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Student Attendance<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('extraclassattendance') ?>">Extra Class Attendance</a></li>
					<li><a href="<?php echo $this->url('cancelledlectures') ?>">Cancelled/Called Off Lectures</a></li>
					<li><a href="<?php echo $this->url('editstudentattendance') ?>">Edit Attendance</a></li>
					<li><a href="<?php echo $this->url('viewstudentattendance') ?>">View Attendance</a></li>
			</ul>
			</li>
		</ul>
	</li>
</ul>
</div>
</div>
