<?php
 $title = 'Selected Candidates by Colleges/Agencies';
 $this->headTitle($title);
 
 $key = $this->keyphrase;
 function my_encrypt($data, $key) {
		// Remove the base64 encoding from our key
		$encryption_key = base64_decode($key);
		// Generate an initialization vector
		$iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));
		// Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
		$encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
		// The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
		return bin2hex(base64_encode($encrypted . '::' . $iv));
	}

?>
	<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-sm-12 col-xs-12">
     		 <div class="x_panel">
              <div class="x_title">
                        <h2><?php echo $this->escapeHtml($title); ?></h2>
                        <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                  </li>
                  <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"></a>
                  </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">
                     <div class="table-responsive">
                      <table id="datatable-fixed-header" class="table table-striped jambo_table table-bordered">
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Agency </th>
                            <th class="column-title">Position Category</th>
                            <th class="column-title">Position Title</th>
                            <th class="column-title">Position Level </th>
                            <th class="column-title">Department </th>
                            <th class="column-title">Date</th>
                            <th class="column-title no-link last"><span class="nobr">Action</span></th>
                          </tr>
                        </thead>  
                        <tbody>
                         <?php foreach ($this->jobApplicants as $applicant) : ?>
                          <tr class="even pointer">
                            <td class=" "><?php echo $this->escapeHtml($applicant['working_agency']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($applicant['position_category']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($applicant['position_title']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($applicant['position_level']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($applicant['departments_id']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($applicant['appointment_date']);?></td>
                            <td class="last"><a href="<?php echo $this->url('updateselectedcandidate', array('id' => my_encrypt($applicant['id'], $key)));?>" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i>View</a>
                            	</td>
                          </tr>
                          <?php endforeach; ?>
                      </tbody>
                      </table>
                     </div>
                   </div>
                 </div>
               </div>
             </div>
           </div>
              