<?php
 $title = 'Upload Academic Timetable';
 $this->headTitle($title);
?>

<div class="right_col" role="main">
  <div class=" ">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2><?php echo $this->escapeHtml($title); ?></h2>
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
          </ul>
          <div class="clearfix"></div>
        </div>
                 
      
            <div class="x_content">
              <?php
              // Opening of the form tag
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        $timetable = $form->get('uploadtimetable');
                        echo $this->form()->openTag($form);
                        echo $this->formHidden($timetable->get('id'));
                        $timetable->get('organisation_id')->setValue($this->organisation_id);
                        echo $this->formHidden($timetable->get('organisation_id'));
              ?>
              <?php if($this->message == NULL && $this->flashMessenger()->hasMessages()){?>
              <div class="alert alert-success alert-dismissible fade in" role="alert">
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                  <strong>Success!</strong> <?=$this->flashMessenger()->setAutoEscape(false)->render(); ?>
              </div>
              <?php } else if($this->message =='Failure' && $this->flashMessenger()->hasMessages()) {?>
              <div class="alert alert-danger alert-dismissible fade in" role="alert">
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                  <strong>Failure!</strong> <?=$this->flashMessenger()->setAutoEscape(false)->render(); ?>
              </div>
              <?php } ?> 

              <div class="col-md-12 col-sm-12 col-xs-12" style="border: 2px solid #a1a1a1;margin-top: 15px;padding: 10px;">
                <div class="form-group">           
                  <div class="col-md-6 col-sm-6 col-xs-12">
                          <?php  echo $this->formRow($timetable->get('file_name')); ?>
                  </div>
                </div>

                <div class="form-group">
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <?php  
                        echo $this->formRow($form->get('csrf'));
                        echo $this->formRow($timetable->get('submit')); 
                    ?> 
                  </div>
                </div> 
                <?php 
                  //closing the form tag  
                   echo $this->form()->closeTag();
               ?>

              </div></div> <!-- End of x-content -->
          </div>
        </div>
      </div>
    </div>
  </div>

 