<?php

 $title = 'Hostel Change Application Status';
 $this->headTitle($title);
?>

 <div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
            
                <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                     <div class="clearfix"></div>
                    </div>

                        <div class="table-responsive">
                          <table class="table table-striped jambo_table bulk_action">
                            <thead>
                              <tr class="headings">
                                 <th class="column-title">Sl.No </th>
                                 <th class="column-title">From Hostel</th>
                                 <th class="column-title">To Hostel</th>
                                 <th class="column-title">Hostel Type</th>
                                 <th class="column-title">Hostel Category</th>
                                 <th class="column-title">Room No</th>
                                 <th class="column-title">Status</th>
                              </tr>
                        </thead>
                        <tbody>
                           <?php $i=1; foreach ($this->hostelChangeApplication as $application) : ?>
                          <tr class="even pointer">
                            <td class=" "><?php echo $i++;?></td>
                                <td class=" "><?php echo $this->escapeHtml($application['fhostel_name']);?></td>
                                <td class=" "><?php echo $this->escapeHtml($application['thostel_name']);?></td>
                                <td class=" "><?php echo $this->escapeHtml($application['hostel_type']);?></td>
                                <td class=" "><?php echo $this->escapeHtml($application['hostel_category']);?></td>
                                <td class=" "><?php echo $this->escapeHtml($application['hostel_room_no']);?></td>
                                <td class=" "><?php echo $this->escapeHtml($application['status']);?></td>
                              </tr>
                              <?php endforeach; ?>
                            </tbody>
                          </table>
                        </div>
                        </div>                        
                      </div>
                    </div>
                    <!-- End of Tabs-->
                     
                     
                  </div>
                </div>
              </div>
     </div>
          
                     