<?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'My Appraisal Form (Academic)';
 $this->headTitle($title);
?>
<div class="right_col" role="main">
          <div class="">
        <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                  <div class="x_content">
                  <br />
                   <div class="" role="tabpanel" data-example-id="togglable-tabs">
                    <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                      <li role="presentation" class=""><a href="#tab_content2" role="home-tab" id="tab" data-toggle="tab" aria-expanded="true">Peer</a>
                      </li>
                      <li role="presentation" class=""><a href="#tab_content3" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false">Subordinate</a>
                      </li>
                      <li role="presentation" class=""><a href="#tab_content4" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false">Beneficiary</a>
                      </li>
                    </ul>
                    <div id="myTabContent" class="tab-content">
                      <div role="tabpanel" class="tab-pane fade active in" id="tab_content2" aria-labelledby="home-tab">
                        <p>
                         
                        <div class="x_panel"> 
            <div class="x_content">
                      <table class="table table-striped jambo_table bulk_action"> 
                        <thead>
                          <tr class="headings">
                           <th>
                              <input type="checkbox" id="check-all" class="flat">
                            </th>
                             <th class="column-title">Sl.No. </th>
                            <th class="column-title">Employee Name</th>
                            <th class="column-title">EID </th>
                            <th class="column-title">Designation</th>
                            <th class="column-title">Feedback Form</th>
                            <th class="column-title">Status</th>
                            <th class="bulk-actions" colspan="7">
                              <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                            </th>
                          </tr>
                        </thead>
                        
                        <tbody>
                          <tr>
                           <td><input type="checkbox" id="check-all" class="flat"></td>
                            <td>1</td>
                            <td>Dorji</td>
                            <td>R11</td>
                            <td>ICT</td>
                             <td><a href="peerfeedbackform"><u> Click here</u></td>
                             <td>Completed</td>
                          </tr>
                        </tbody>
                          </table>    
            </div></div>
                </div>
                        <div role="tabpanel" class="tab-pane fade" id="tab_content3" aria-labelledby="profile-tab">
                        <p>
                         
                        <div class="x_panel"> 
            <div class="x_content">
                      <table class="table table-striped jambo_table bulk_action"> 
                        <thead>
                          <tr class="headings">
                           <th>
                              <input type="checkbox" id="check-all" class="flat">
                            </th>
                             <th class="column-title">Sl.No. </th>
                            <th class="column-title">Employee Name</th>
                            <th class="column-title">EID </th>
                            <th class="column-title">Designation</th>
                            <th class="column-title">Feedback Form</th>
                            <th class="column-title">Status</th>
                            <th class="bulk-actions" colspan="7">
                              <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                            </th>
                          </tr>
                        </thead>
                        
                        <tbody>
                          <tr>
                           <td><input type="checkbox" id="check-all" class="flat"></td>
                            <td>1</td>
                            <td>Dorji</td>
                            <td>R11</td>
                            <td>ICT</td>
                             <td><a href="subordinatefeedbackform"><u> Click here</u></td>
                             <td>Completed</td>
                          </tr>
                        </tbody>
                          </table>    
            </div></div>
                </div>
                        
                        <div role="tabpanel" class="tab-pane fade" id="tab_content4" aria-labelledby="profile-tab">
                        <p>
                          <div class="x_panel">  
                        <div class="x_content">
                      <table class="table table-striped jambo_table bulk_action"> 
                        <thead>
                          <tr class="headings">
                           <th>
                              <input type="checkbox" id="check-all" class="flat">
                            </th>
                             <th class="column-title">Sl.No. </th>
                            <th class="column-title">Employee Name</th>
                            <th class="column-title">EID </th>
                            <th class="column-title">Designation</th>
                            <th class="column-title">Feedback Form</th>
                            <th class="column-title">Status</th>
                            <th class="bulk-actions" colspan="7">
                              <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                            </th>
                          </tr>
                        </thead>
                        
                        <tbody>
                          <tr>
                           <td><input type="checkbox" id="check-all" class="flat"></td>
                            <td>1</td>
                            <td>Dorji</td>
                            <td>R11</td>
                            <td>ICT</td>
                             <td><a href="peerfeedbackform"><u> Click here</u></td>
                             <td>Completed</td>
                          </tr>
                        </tbody>
                          </table>    
            </div></div>
                </div>
                </div>
              </p>
              
             </div>
          </div>
                  <div class="x_content">
                 <div class="row">
                        <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                    <button class="btn btn-default">Save & Close</button>
                    <button class="btn btn-success">Submit</button>
                 </div>
                </div>
               </div>
                </div>
              </div>
            </div>
         
          </div>
        </div> 

              
              
   
            
    