<!-- page content -->
<div class="col-md-12 col-sm-12 col-xs-12">   
<div class="x_panel">
<div class="x_title">
    <h2><?php echo $this->escapeHtml('Student Intake By Year'); ?></h2>
     <div class="clearfix"></div>
    </div>
    <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab">
        <br/>
           <div class="table-responsive">
                <?php if($this->student_report != NULL) {?>
                    <table id="datatable-buttons" class="table table-striped jambo_table table-bordered"width="100%">
                    <thead>
                      <tr class="headings">
                         <th class="column-title">Sl.No </th>
                         <th class="column-title">Organisation</th>
                         <th class="column-title">Male</th>
                         <th class="column-title">Female</th>
                         <th class="column-title">Total</th>
                      </tr>
                    </thead>
                    <tbody>
					  <?php $i=1;
                        foreach ($this->student_report as $key => $value) : ?>
                      <?php  
                            $male_ac = 0;
                            $female_ac = 0;
                      ?>
                      <tr class="even pointer">
                        <td class=" "><?php echo $i++;?></td>
                        <td class=" "><?php echo $this->escapeHtml($key);?></td>
                        <td class=" "><?php 
                                            if(array_key_exists('Male', $this->student_report[$key])){
                                                    $male_ac = $this->student_report[$key]['Male'];
                                                    echo $this->escapeHtml($male_ac);
                                                }
                                                else 
                                                    echo $this->escapeHtml("0");?></td>
                        <td class=" "><?php 
                                                if(array_key_exists('Female', $this->student_report[$key])){
                                                    $female_ac = $this->student_report[$key]['Female'];
                                                    echo $this->escapeHtml($female_ac);
                                                }
                                                else 
                                                    echo $this->escapeHtml("0");?></td>
                        <td class=" "><?php 
                                            echo $this->escapeHtml($male_ac + $female_ac );?></td>
                      </tr>
                      <?php endforeach; ?>
                    </tbody>
                  </table>
               <?php } ?>
            </div>
    </div>
  </div>
</div>          
<!-- /page content -->
                  