<?php

 $title = 'Add Dates to Academic Calendar';
 $this->headTitle($title);

  $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector

    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));

    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}
$academic_session1 = "$academic_session Semester Duration";
$academic_session2 = "$academic_session Academic Session Duration";
 ?>

<div class="right_col" role="main">
  <div class="">
    <div class="col-md-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2><?php echo $this->escapeHtml($title); ?></h2>
          <div class="clearfix"></div>
        </div>
        <div class="x_content"><br />
        <?php
        // Opening of the form tag
        $form->prepare();
        echo $this->form()->openTag($form);
        $calendar = $form->get('academiccalendar');
				$calendar->get('academic_event')->setValueOptions($this->event_list);
				$calendar->get('academic_year')->setValueOptions($this->academic_year_list);
				$calendar->get('employee_details_id')->setValue(-1);
        echo $this->formHidden($calendar->get('id')); 
				echo $this->formHidden($calendar->get('employee_details_id')); 
			  ?>
        <div class="x_content">
          <div class="row">    
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12"> Name of Event: <span class="required">*</span></label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <?php  echo $this->formRow($calendar->get('academic_event')); ?>
              </div>
            </div>
          </div>
          <div class="row">    
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12"> Academic Year: <span class="required">*</span></label>
              <div class="col-md-2 col-sm-3 col-xs-12">
                <?php  echo $this->formRow($calendar->get('academic_year')); ?>
              </div>
              <label class="control-label col-md-2 col-sm-3 col-xs-12"> Event For: <span class="required">*</span></label>
              <div class="col-md-2 col-sm-3 col-xs-12">
                <?php  echo $this->formRow($calendar->get('event_for')); ?>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12"> From-To Date: <span class="required">*</span></label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <?php  echo $this->formRow($calendar->get('date_range')); ?>
              </div>
            </div>
          </div>
          <div class="row">    
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12"> Remarks: <span class="required">*</span></label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <?php  echo $this->formRow($calendar->get('remarks')); ?>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="ln_solid"></div>
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <?php
                echo $this->formHidden($form->get('csrf'));
                echo $this->formSubmit($calendar->get('submit')); 
                ?>
              </div>
            </div>
          </div>
          <?php
          echo $this->form()->closeTag();
          ?>
        </div>
      </div>
    </div>
    <?php
    $title = 'Academic Calendar Dates';
    $this->headTitle($title);
    ?>
    <div class="col-md-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2><?php echo $this->escapeHtml($title); ?></h2>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <div class="table-responsive">
            <table class="table table-striped jambo_table bulk_action"> 
              <div class="form-group">      
              </div> 
              <thead>
                <tr class="headings">
                  <th class="column-title">Sl. No</th>
                  <th class="column-title">Academic Event</th>
                  <th class="column-title">Academic Year</th>
                  <th class="column-title">Event For</th>
                  <th class="column-title">Start Date </th>
                  <th class="column-title">End Date </th>
                  <th class="column-title">Remarks </th>                            
                  <th class="column-title no-link last"><span class="nobr">Action</span></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <?php $i=1; foreach ($this->calendarDates as $date) : ?>
                  <tr class="even pointer">
                    <td class=" "><?php echo $i++;?></td>
                    <td class=" "><?php echo $this->escapeHtml($date['academic_event']);?></td>
                    <td class=" "><?php echo $this->escapeHtml($date['academic_year']);?></td>
                    <td class=" "><?php echo $this->escapeHtml($date['event_for']);?></td>
                    <td class=" "><?php echo $this->escapeHtml($date['from_date']);?></td>
                    <td class=" "><?php echo $this->escapeHtml($date['to_date']);?></td>
                    <td class=" "><?php echo $this->escapeHtml($date['remarks']);?></td>
                    <td>
                      <?php
                      if($this->escapeHtml($date['academic_year']) >= $academic_year)
                      { 
                        if($academic_session1 == $this->escapeHtml($date['academic_event'])) { ?>
                          <a href="<?php echo $this->url('editcalendar', array('id' => my_encrypt($date['id'], $key)));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a>
                          <?php } 
                          else if($academic_session1 == $this->escapeHtml($date['academic_event'])) { ?>
                          <a href="<?php echo $this->url('editcalendar', array('id' => my_encrypt($date['id'], $key)));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a>
                          <?php } 
                          else if($academic_session2 == $this->escapeHtml($date['academic_event'])) { ?>
                          <a href="<?php echo $this->url('editcalendar', array('id' => my_encrypt($date['id'], $key)));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a>
                          <?php } 
                          else if('National Holiday' == $this->escapeHtml($date['academic_event'])) { ?>
                          <a href="<?php echo $this->url('editcalendar', array('id' => my_encrypt($date['id'], $key)));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a>
                          <?php } 
                          else if('Local Holiday' == $this->escapeHtml($date['academic_event'])) { ?>
                          <a href="<?php echo $this->url('editcalendar', array('id' => my_encrypt($date['id'], $key)));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a>
                          <?php } 
                          else if('CA Marks Compile Duration' == $this->escapeHtml($date['academic_event'])) { ?>
                          <a href="<?php echo $this->url('editcalendar', array('id' => my_encrypt($date['id'], $key)));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a>
                          <?php }
                          else if('SE Marks Compile Duration' == $this->escapeHtml($date['academic_event'])) { ?>
                          <a href="<?php echo $this->url('editcalendar', array('id' => my_encrypt($date['id'], $key)));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a>
                          <?php }
			  else {
                          echo("Cannot Edit");
                          }
                        } else {
                          echo("Cannot Edit");
                        } 
                      ?>
                    </td>
                  </tr>
                <?php endforeach; ?>
              </tr>
            </tbody>
          </table>
        </div>
      </div> 
    </div>
  </div>

  <div class="col-md-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2><?php echo 'National and Local Holidays' ?></h2>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <div class="table-responsive">
            <table class="table table-striped jambo_table bulk_action"> 
              <div class="form-group">      
              </div> 
              <thead>
                <tr class="headings">
                  <th class="column-title">Sl. No</th>
                  <th class="column-title">Academic Event</th>
                  <th class="column-title">Academic Year</th>
                  <th class="column-title">Event For</th>
                  <th class="column-title">Start Date </th>
                  <th class="column-title">End Date </th>
                  <th class="column-title">Remarks </th>                            
                  <th class="column-title no-link last"><span class="nobr">Action</span></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <?php $i=1; foreach ($this->holidayCalendarDates as $date) : ?>
                  <tr class="even pointer">
                    <td class=" "><?php echo $i++;?></td>
                    <td class=" "><?php echo $this->escapeHtml($date['academic_event']);?></td>
                    <td class=" "><?php echo $this->escapeHtml($date['academic_year']);?></td>
                    <td class=" "><?php echo $this->escapeHtml($date['event_for']);?></td>
                    <td class=" "><?php echo $this->escapeHtml($date['from_date']);?></td>
                    <td class=" "><?php echo $this->escapeHtml($date['to_date']);?></td>
                    <td class=" "><?php echo $this->escapeHtml($date['remarks']);?></td>
                    <td>
                      <?php
                      if($this->escapeHtml($date['academic_year']) >= $academic_year)
                      { 
                        if($academic_session1 == $this->escapeHtml($date['academic_event'])) { ?>
                          <a href="<?php echo $this->url('editcalendar', array('id' => my_encrypt($date['id'], $key)));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a>
                          <?php } 
                          else if($academic_session1 == $this->escapeHtml($date['academic_event'])) { ?>
                          <a href="<?php echo $this->url('editcalendar', array('id' => my_encrypt($date['id'], $key)));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a>
                          <?php } 
                          else if($academic_session2 == $this->escapeHtml($date['academic_event'])) { ?>
                          <a href="<?php echo $this->url('editcalendar', array('id' => my_encrypt($date['id'], $key)));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a>
                          <?php } 
                          else if('National Holiday' == $this->escapeHtml($date['academic_event'])) { ?>
                          <a href="<?php echo $this->url('editcalendar', array('id' => my_encrypt($date['id'], $key)));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a>
                          <?php } 
                          else if('Local Holiday' == $this->escapeHtml($date['academic_event'])) { ?>
                          <a href="<?php echo $this->url('editcalendar', array('id' => my_encrypt($date['id'], $key)));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a>
                          <?php } 
                          else if('CA Marks Compile Duration' == $this->escapeHtml($date['academic_event'])) { ?>
                          <a href="<?php echo $this->url('editcalendar', array('id' => my_encrypt($date['id'], $key)));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a>
                          <?php }
                          else if('SE Marks Compile Duration' == $this->escapeHtml($date['academic_event'])) { ?>
                          <a href="<?php echo $this->url('editcalendar', array('id' => my_encrypt($date['id'], $key)));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a>
                          <?php }
        else {
                          echo("Cannot Edit");
                          }
                        } else {
                          echo("Cannot Edit");
                        } 
                      ?>
                    </td>
                  </tr>
                <?php endforeach; ?>
              </tr>
            </tbody>
          </table>
        </div>
      </div> 
    </div>
  </div>
</div>
</div>
</div>

            
