<?php

 $title = 'Edit Dates/Events to My Calendar';
 $this->headTitle($title);
 
 $calendar_detail = array();
 foreach($this->calendarDetail as $detail){
	 $calendar_detail = $detail;
 }
 ?>

<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				    $calendar = $form->get('staffcalendar');
                    echo $this->form()->openTag($form);
					$calendar->get('id')->setValue($calendar_detail['id']);
					$calendar->get('event_name')->setValue($calendar_detail['event_name']);
					$calendar->get('from_date')->setValue($calendar_detail['from_date']);
					$calendar->get('to_date')->setValue($calendar_detail['to_date']);
					$calendar->get('remarks')->setValue($calendar_detail['remarks']);
                    echo $this->formHidden($calendar->get('id')); 
				  ?>  
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12"> Name of Event: <span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($calendar->get('event_name')); ?>
                    </div>
                </div>
                </div>
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12"> From Date: <span class="required">*</span></label>
                    <div class="col-md-2 col-sm-3 col-xs-12">
                      <?php  echo $this->formRow($calendar->get('from_date')); ?>
                    </div>
                    <label class="control-label col-md-2 col-sm-3 col-xs-12"> To Date: <span class="required">*</span></label>
                    <div class="col-md-2 col-sm-3 col-xs-12">
                      <?php  echo $this->formRow($calendar->get('to_date')); ?>
                    </div>
                </div>
                </div>
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12"> Remarks: <span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($calendar->get('remarks')); ?>
                    </div>
                </div>
                </div>
                  
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
						<?php
						   echo $this->formHidden($form->get('csrf'));
						   echo $this->formSubmit($calendar->get('submit')); 
                        ?>
                    	</div>
                    </div>
               </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                </div>
              </div>
        </div>


              <?php
				 $title = 'Calendar Dates/Events';
				 $this->headTitle($title);
			  ?>
              <div class="col-md-12 col-xs-12">
                  
                  <div class="x_panel">
                      <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                  </div>
                
                    <div class="x_content">
                        <div class="table-responsive">
                      <table class="table table-striped jambo_table bulk_action"> 
                         <div class="form-group">      
                      </div> 
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Sl. No</th>
                            <th class="column-title">Event Name </th>
                            <th class="column-title">Start Date </th>
                            <th class="column-title">End Date </th>
                            <th class="column-title no-link last"><span class="nobr">Action</span></th>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                          <?php $i=1; foreach ($this->calendarDates as $date) : ?>
                          <tr class="even pointer">
                            <td class=" "><?php echo $i++;?></td>
                            <td class=" "><?php echo $this->escapeHtml($date['event_name']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($date['from_date']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($date['to_date']);?></td>
                            <td><a href="<?php echo $this->url('editcalendar', array('id' => $date['id']));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a>
                          </tr>
                          <?php endforeach; ?>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                    </div>
                
                </div></div></div></div>
             
          </div>
        </div> 
     </div>
            