<?php
 $title = 'Assessment Component Type for College';
 $this->headTitle($title);
?>

 <div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
            
                <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                     <div class="clearfix"></div>
                    </div>
                        <!-- Adding Assessment-->
                        <?php if($this->message == NULL && $this->flashMessenger()->hasMessages()) {
							echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
							echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
							$messages = $this->flashMessenger()->getMessages();
							foreach($messages as $message) {
								echo '<strong>Success!</strong>'. $message;
							}
							echo '</div>';
                    	} else if($this->message =='Failure' && $this->flashMessenger()->hasMessages()) {
                            echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                            echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                            $messages = $this->flashMessenger()->getMessages();
                            foreach($messages as $message) {
                                echo '<strong>Warning!</strong>'. $message;
                            }
                            echo '</div>';
                     } ?>
                        <br/>
                        <!-- Adding Assessment Component Type-->
                        <div class="col-md-12 col-xs-12">
                          <div class="x_panel">
                            <div class="x_title">
                              <h2><?php echo $this->escapeHtml("Assessment Component Type")?></h2>
                                <ul class="nav navbar-right panel_toolbox">
                                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                  </li>

                                </ul>
                             <div class="clearfix"></div>

                            </div>

                            <div class="x_content">
                              <br />
                               <?php
                                // Opening of the form tag
                                $typeForm->setAttribute('action', $this->url('addassessmentcomponenttypes', array('action' => 'addAssessmentComponentType')));
                                $typeForm->prepare();
                                echo $this->form()->openTag($typeForm);
                                $assessmentType = $typeForm->get('assessmentcomponent');
                                $assessmentType->get('organisation_id')->setValue($this->organisation_id);
                                echo $this->formHidden($assessmentType->get('id'));
                                echo $this->formHidden($assessmentType->get('organisation_id'));
                              ?>
                              <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Assessment Component Type<span class="required">*</span></label>
                                <div class="col-md-5 col-sm-6 col-xs-12">
                                  <?php  echo $this->formRow($assessmentType->get('assessment_component_type')); ?>
                                </div>
                              </div>                                     
                             <div class="row">
                                <div class="ln_solid"></div>
                                <div class="form-group">
                                    <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                                      <?php
                                       echo $this->formHidden($typeForm->get('csrf'));
                                       echo $this->formSubmit($assessmentType->get('submit')); 
                                       echo $this->form()->closeTag(); 
                                    ?>
                                </div>
                            </div>

                          </div>
                        </div>
                       </div>     


                        <div class="col-md-12 col-sm-12 col-xs-12">
                          <div class="x_panel">
                            <div class="x_title">
                              <h2><?php echo $this->escapeHtml("Assessment Component Type"); ?></h2>
                              <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                </li>
                              </ul>
                              <div class="clearfix"></div>
                            </div>

                            <div class="x_content">
                              <table class="table   table-striped responsive-utilities jambo_table bulk_action table-bordered">
                                <thead>
                                  <tr class="headings">
                                    </th>
                                     <th class="column-title">Sl.No.</th>
                                     <th class="column-title">Assessment Component Type</th>
                                     <th class="column-title">Action</th>
                                  </tr>
                                </thead>

                                <tbody>
                                  <?php
                                  $i=1;  foreach($this->componentTypeList as $sub): ?>
                                  <tr class="even pointer">
                                    <td class=" "><?php echo $i++;?></td>
                                    <td class=" "><?php echo $sub['assessment_component_type']; ?></td>
                                    <td class=" "><?php  ?></td>
                                  </tr>
                                  <?php endforeach; ?>
                                </tbody>
                              </table>
                            </div>
                          </div>
                        </div>

                        <!-- End of Assessment Component Type-->
                     
                     
                  </div>
                </div>
              </div>
     </div>
