<?php
 $title = 'Organisation Configuration & Settings';
 $this->headTitle($title);
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
               <div class="" role="tabpanel" data-example-id="togglable-tabs">
                <div id="myTabContent" class="tab-content">
                  <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="profile-tab">
                   <br/> 
                   <p> 
                   <div class="x_panel"> 
                     <h2>Organisation/Colleges</h2>   
                    <div class="x_content">
                  <br />
                   
                <?php
                   // Opening of the form tag
					$form->prepare();
                    echo $this->form()->openTag($form);
				    $organisation = $form->get('organisation');
                    echo $this->formHidden($organisation->get('id'));   
                ?>
                <div class="row">    
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Organisation/College Name: <span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <input type="text" placeholder="Dorjee" class="form-control" readonly="readonly"/>
                    </div>
                  </div>
                </div>
                <div class="row">    
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Organisation Address: <span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <input type="text" placeholder="Dorjee" class="form-control" readonly="readonly"/>
                    </div>
                  </div>
                </div>
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                        <?php 
						   echo $this->formHidden($form->get('csrf'));
						   echo $this->formSubmit($organisation->get('submit')); 
						?>
                        </div>
                    </div>
                </div>
                    
				<?php echo $this->form()->closeTag(); ?>
                    
                </div>
                </div> 
                
				<div class="x_panel">
                <div class="x_content">
                     <div class="table-responsive">
                      <table id="example-datatable" class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Organisation/College Name</th>
                            <th class="column-title">Address</th>
                            <th class="column-title">Action</th>
                          </tr>
                        </thead>  
                        <tbody>
                        <?php foreach ($this->organisations as $org): ?>
						  <tr>
							<td><?php echo $this->escapeHtml($org->getOrganisation_Name());?></td>
							<td><?php echo $this->escapeHtml($org->getAddress());?></td>
                            <td><a href="<?php echo $this->url('vieworganisation', array('id' => $org->getId()));?>" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i>View</a>
                            	<a href="<?php echo $this->url('editorganisation', array('id' => $org->getId()));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a>
						  </tr>
                        <?php endforeach; ?>
                        </tbody>
                      </table>
                     </div>
					</div>
				</div>
			</div> 
                
   		 </div>
 		</div>
	</div>
  </div>
</div>
            
