<?php
 $title = 'Add Club Advisor & Coordinator';
 $this->headTitle($title);

  $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    //IDEA-CBC
    //Original
    //$iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('aes-256-cbc'));

    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));

    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2>Add Club, Advisor & Coordinator</h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				            $clubs = $form->get('clubs');
          					$data = $this->selectData;
          					$clubs->get('organisation_id')->setValue($this->organisation_id);
                    echo $this->formHidden($clubs->get('id')); 
          					echo $this->formHidden($clubs->get('organisation_id')); 
          				  ?>
                    <?php 
                  if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                      echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                      echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                      $messages = $this->flashMessenger()->getMessages();
                      foreach($messages as $message) {
                          echo '<strong>Success!</strong>'. $message;
                      }
                      echo '</div>';
                  }

                  else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                      echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                      echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                      $messages = $this->flashMessenger()->getMessages();
                      foreach($messages as $message) {
                          echo '<strong>Failure!</strong>'. $message;
                      }
                      echo '</div>';
                  }
                ?>
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Club: <span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($clubs->get('club_name')); ?>
                    </div>
                </div>
                </div> 
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Maximum Members: <span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($clubs->get('maximum_members')); ?>
                    </div>
                </div>
                </div> 
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Advisor Name: <span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($clubs->get('advisor_name')); ?>
                    </div>
                </div>
                </div> 
                  
                   <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Coordinator Name: <span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($clubs->get('coordinator_name')); ?>
                    </div>
                </div>
                </div>
                
                <div class="row" >
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Description:<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($clubs->get('description')); ?>
                    </div>
                </div> 
                </div>
               
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12"></label>
                              <div class="col-md-3 col-sm-3 col-xs-12">
                    <?php
                        echo $this->formHidden($form->get('csrf'));
            						echo $this->formSubmit($clubs->get('submit')); 
            						echo $this->form()->closeTag();
                      ?>
                    </div>
                   </div>
                </div>
                       
                </div>
              </div>
            </div>
              
              
               <?php
               $title = 'Club, Advisor & Coordinator';
               $this->headTitle($title);
              ?>
               <div class="col-md-12 col-xs-12">
                  
                  <div class="x_panel">
                      <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                  </div>
                
                    <div class="x_content">
                        <div class="table-responsive">
                      <table class="table table-striped jambo_table bulk_action"> 
                         <div class="form-group">      
                      </div> 
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Sl. No</th>
                            <th class="column-title">Club Name </th>
                            <th class="column-title">Advisor Name</th>
                            <th class="column-title">Co-Ordinator Name</th>
                            <th class="column-title">Description</th>
                            <th class="column-title no-link last"><span class="nobr">Action</span></th>
                            <th class="bulk-actions" colspan="7">
                              <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                            </th>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <?php $i=1; foreach ($this->clubs as $club) : ?>
                          <tr class="even pointer">
                            <td class=" "><?php echo $i++;?></td>
                            <td class=" "><?php echo $this->escapeHtml($club['club_name']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($club['advisor_name']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($club['coordinator_name']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($club['description']);?></td>
                            <td><a href="<?php echo $this->url('viewclub', array('id' => my_encrypt($club['id'], $key)));?>" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> View</a>
                            	<a href="<?php echo $this->url('editclub', array('id' => my_encrypt($club['id'], $key)));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit</a></td>
                          </tr>
                          <?php endforeach; ?>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                    </div>
                
                </div>
              </div>
            </div>
          </div>
             