<?php
 // module/EmployeeDetail/view/employee-detail/employee-detail/emppersonaldetail.phtml:

 $title = 'Add Employee Work Experience';
 $this->headTitle($title);
 ?>
<div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                  </div>
                    
                  <div class="x_content">
                    <br/>
                   
                        
                        
                        <?php
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        
                        echo $this->formHidden($form->get('id'));
                        ?>
                        <div class="row">
                          <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Company<span class="required">*</span>
                        </label>
                              <div class="col-md-3 col-sm-3 col-xs-12">
                        <?php
                        echo $this->formRow($form->get('emp_id'));
                        ?>
                          </div>
                        </div>
                        </div>
                    
                   
                    <div class="row"> 
                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Position Title<span class="required">*</span>
                        </label>
                              <div class="col-md-3 col-sm-3 col-xs-12">
                    <?php
                        echo $this->formRow($form->get('emp_job_title'));
                        ?>
                    </div>
                    </div>
                    </div>
                    
                    <div class="row"> 
                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">From<span class="required">*</span>
                        </label>
                              <div class="col-md-3 col-sm-3 col-xs-12">
                            <?php
                        echo $this->formRow($form->get('emp_experience_yr'));
                    ?>
                  </div>
                    </div>
                    </div>
                    <div class="row"> 
                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">To<span class="required">*</span>
                        </label>
                              <div class="col-md-3 col-sm-3 col-xs-12">
                            <?php
                        echo $this->formRow($form->get('emp_experience_yr'));
                    ?>
                  </div>
                    </div>
                    </div>
                    <div class="row"> 
                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Comments<span class="required">*</span>
                        </label>
                              <div class="col-md-3 col-sm-3 col-xs-12">
                    <?php
                    
                        echo $this->formRow($form->get('emp_work_experience'));
                        ?>
                    </div>
                    </div>
                    </div>
                   
                    <div class="row">
                        <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12"></label>
                              <div class="col-md-3 col-sm-3 col-xs-12">
                    <?php
                        echo $this->formSubmit($form->get('submit'));                  
                        echo $this->formSubmit($form->get('reset')); 
                      ?>
                    </div>
                    
                    </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                       
                    
                   </div></div></div></div></div></div>
            
         
              
       
                