<?php
 $title = 'Academic Review for Staff';
 $this->headTitle($title);
 $staff = array();
 $api_output = array();
 $academic_activities = array();
 $api = array();
  $remarks_data = array();
  foreach($this->employee_details as $emp){
	 $staff = $emp;
 }
 $ratings_array =array('1' =>'Needs Improvement','2'=>'Good','3'=>'Very Good','4'=>'Excellent');
 $index=1;
 foreach($this->academicAppraisal as $kpi){
	 $academic_activities[$kpi['category']][$kpi['activity_name']][]= $kpi;
	 $api_output[$kpi['category']][] = $kpi['activity_name'];
	 $api[$kpi['pms_nature_activity_id']] = $kpi['nature_of_activity'];
	 $remarks_data[$index++] = $kpi['id'];
 }
?>

 <div class="right_col" role="main">
  <div class="">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
            <h2><?php echo $this->escapeHtml($title); ?></h2>
             <div class="clearfix"></div>
            </div>
            <br/>
             <div class="row">
                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                  <label>Appraisal Period</label>
                  <input type="text" placeholder="2017-2018" class="form-control" readonly>
                  </div>
                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                  <label>Employee Name</label>
                  <input type="text" placeholder="<?php echo $staff['first_name'].' '.$staff['middle_name'].' '.$staff['last_name']; ?>" class="form-control" readonly>
                  </div>
                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                  <label>Employee ID No.</label>
                  <input type="text" placeholder="<?php echo $staff['emp_id']; ?>" class="form-control" readonly>
                  </div>
                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                  <label>Position Title</label>
                  <input type="text" placeholder="Finance Officer" class="form-control" readonly>
                  </div>
             </div>
             <div class="row">
                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                  <label>Position Level</label>
                  <input type="text" placeholder="Grade 8" class="form-control" readonly>
                  </div>
                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                  <label>OVC / College</label>
                  <input type="text" placeholder="OVC" class="form-control" readonly>
                  </div>
                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                  <label>Department/Division</label>
                  <input type="text" placeholder="IT Division" class="form-control" readonly>
                  </div>
             </div>
            <br />
            <?php
				// Opening of the form tag
				$form->prepare();
				echo $this->form()->openTag($form);
			?> 
            <div class="ln_solid"></div>
            <br />
            <div class="table-responsive">
              <table class="table   table-striped responsive-utilities jambo_table bulk_action table-bordered">
                <thead>
                  <tr class="headings">
                     <th style="width:14%" class="column-title">College/Department Output</th>
                     <th style="width:18%" class="column-title">Activities</th>
                     <th style="width:14%" class="column-title">Maximum API </th>
                     <th style="width:14%" class="column-title">Minimum API</th>
                     <th style="width:10%" class="column-title">Self Rating</th>
                     <th style="width:10%" class="column-title">Comments</th>
                     <th style="width:12%" class="column-title">Supervisor Rating</th>
                  </tr>
                </thead>
                <tbody>
                  <?php 
                    $i=1;
                    $activity=NULL;
                    foreach($academic_activities as $key=>$value){
                  ?>
                  <tr class="even pointer">
                    <td class=" "><?php  $j=1;?></td>
                    <td class="blue"><i><b><?php echo $key; ?></b></i></td>
                    <td class=" "></td>
                    <td class=" "></td>
                    <td class=" "></td>
                    <td class=" "></td>
                    <td class=" "></td>
                  </tr>
                  <?php 
                    foreach($value as $key1=>$value1){
                        foreach($value1 as $key2=>$value2){
                  ?>
                  <tr>
                    <td class=" "><?php echo $key1; ?></td>
                    <td class=" "><?php echo $api[$value2['pms_nature_activity_id']];?></td>
                    <td class=" "><?php echo $value2['maximum_api'];?></td>
                    <td class=" "><?php echo $value2['minimum_api'];?></td>
                    <td class=" "><?php echo $value2['self_rating'];?></td>
                    <td class=" "><?php echo $value2['evaluation_remarks'];?></td>
                    <td class=" "><?php echo $this->formRow($form->get('rating'.$remarks_data[$i++])); ?></td>
                  </tr>
                  <?php  } } } ?>
                </tbody>
              </table>
           </div>
           <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
						<?php
						   echo $this->formHidden($form->get('csrf'));
						   echo $this->formSubmit($form->get('submit')); 
						   echo $this->form()->closeTag();
                        ?>
                    	</div>
                    </div>
           </div>
        </div>
      </div>
    </div>
  </div>
 </div>
