<?php
 // module/Album/view/album/album/edit.phtml:

 $title = ' Performance Assessment (Executive/Administrative & Technical Employee)';
 $this->headTitle($title);
?>

 <div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
            
                <div class="x_panel">
                     <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                    </ul> 
                     <div class="clearfix"></div>
                    </div>
                    <br/>
                    <table class="table   table-striped responsive-utilities jambo_table bulk_action table-bordered">
                    <thead>
                      <tr class="headings">
                        </th>
                         <th class="column-title">Sl.No </th>
                        <th class="column-title">Activities </th>
                        <th class="column-title">Outstanding </th>
                        <th class="column-title">Very Good </th>
                         <th class="column-title">Good </th>
                        <th class="column-title">Needs Improvement</th>
                        <th class="column-title">Self Rating</th>
                        
                        <th class="bulk-actions" colspan="7">
                          <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                        </th>
                      </tr>
                    </thead>

                    <tbody>
                      <tr class="even pointer">
                       <td class=" ">1</td>
                       <td class=" ">Network</td>
                       <td><textarea class="form-control">12months network up</textarea></td>
                       <td><textarea class="form-control">1month network disruption</textarea></td>
                       <td><textarea class="form-control">3months network disruptions</textarea></td>
                       <td><textarea class="form-control">more than six months network disruptions</textarea></td>
                       <td><input type="text" class="form-control"></td>
                      </tr>
                      <tr class="even pointer">
                       <td class=" ">2</td>
                       <td class=" ">Project</td>
                       <td><textarea class="form-control">12months network up</textarea></td>
                       <td><textarea class="form-control">1month network disruption</textarea></td>
                       <td><textarea class="form-control">3months network disruptions</textarea></td>
                       <td><textarea class="form-control">more than six months network disruptions</textarea></td>
                       <td><input type="text" class="form-control"></td>
                      </tr>
                      <tr class="even pointer">
                       <td class=" ">3</td>
                       <td class=" ">Database</td>
                       <td><textarea class="form-control">12months network up</textarea></td>
                       <td><textarea class="form-control">1month network disruption</textarea></td>
                       <td><textarea class="form-control">3months network disruptions</textarea></td>
                       <td><textarea class="form-control">more than six months network disruptions</textarea></td>
                       <td><input type="text" class="form-control"></td>
                      </tr>
                    </tbody>
                  </table>
                         <div class="row">
                        <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-6 col-sm-6 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                    <button class="btn btn-default">Save & Close</button>
                    <button class="btn btn-success">Submit</button>
                 </div>
                </div>
               </div>
                  </div>
                </div>
           
              
         <?php
 // module/Album/view/album/album/edit.phtml:

 $title = ' Performance Assessment (Academic Employee)';
 $this->headTitle($title);
?>     
              
              
              <div class="col-md-12 col-sm-12 col-xs-12">
            
                <div class="x_panel">
                     <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                    </ul> 
                     <div class="clearfix"></div>
                    </div>
                    <br/>
                    <table class="table   table-striped responsive-utilities jambo_table bulk_action table-bordered">
                    <thead>
                      <tr class="headings">
                        </th>
                         <th class="column-title">Sl.No </th>
                          <th class="column-title">Category </th>
                        <th class="column-title">Activities </th>
                        <th class="column-title">Maximum API</th>
                        <th class="column-title">Weightage</th>
                        <th class="column-title">Self Rating</th>
                        
                        <th class="bulk-actions" colspan="7">
                          <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                        </th>
                      </tr>
                    </thead>

                    <tbody>
                      <tr class="even pointer">
                       <td class=" ">1</td>
                       <td class=" ">Teaching & Learning(60%)</td>
                       <td class=" ">Digital Electronics</td>
                       <td>60%</td>
                       <td>20%</td>
                       <td><input type="text" class="form-control"></td>
                      </tr><tr class="even pointer">
                       <td class=" ">2</td>
                       <td class=" ">Research and Innovation(30%)</td>
                       <td class=" ">Digital Electronics</td>
                       <td>30%</td>
                       <td>10%</td>
                       <td><input type="text" class="form-control"></td>
                      </tr>
                      <tr class="even pointer">
                       <td class=" ">3</td>
                       <td class=" ">Professional Services(10)</td>
                       <td class=" ">Digital Electronics</td>
                       <td>10%</td>
                       <td>8%</td>
                       <td><input type="text" class="form-control"></td>
                      </tr>
                    </tbody>
                  </table>
                    <h6>**notes:student feedback rated marks will come under Teaching & Learning</h6>
                         <div class="row">
                        <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-6 col-sm-6 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                    <button class="btn btn-default">Save & Close</button>
                    <button class="btn btn-success">Submit</button>
                 </div>
                </div>
               </div>
                  </div>
                </div>
              </div>
     </div>
          
                     