<?php
 $title = 'Staff Details';
 $this->headTitle($title);

  $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));
    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}


?>

 <div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
            
                <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                  </li>
                            
                                </ul>
                     <div class="clearfix"></div>
                    </div>
            
                            <div class="x_content">
                            <h5><i>Following are the list of new staffs recruited in the year (<?php echo date('Y'); ?>) or before</i></h5>

                                 <?php if($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                            echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                            echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                            $messages = $this->flashMessenger()->getMessages();
                            foreach($messages as $message) {
                              echo '<strong>Success!</strong>'. $message;
                            }
                            echo '</div>';
                             } else if($this->message =='Failure' && $this->flashMessenger()->hasMessages()) {
                            echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                            echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                            $messages = $this->flashMessenger()->getMessages();
                            foreach($messages as $message) {
                                echo '<strong>Warning!</strong>'. $message;
                            }
                            echo '</div>';
                     }  ?>

                              <br />
                              <table id="datatable-buttons" class="table table-striped jambo_table table-bordered">
                                <thead>                        
                                    <th class="column-title">Sl. No. </th>
                                    <th class="column-title">Name</th>
                                    <th class="column-title">Position Title </th>
                                    <th class="column-title">Position Level </th>
                                    <th class="column-title">Department</th>
                                    <th class="column-title">Recruitment Date</th>
                                    <th class="column-title">Status</th>
                                    <th class="column-title no-link last"><span class="nobr">Action</span></th>
                                </thead>
            
                                <tbody>
                                  <?php $i =1; foreach ($this->employeeList as $employee) : ?>
                                  <tr class="even pointer">
                                    <?php 
                                    $year = explode('-', $employee['recruitment_date']); 
                                    $recruitment_year = $year[0];
                                    ?>
                                    <?php if($recruitment_year <= date('Y')){ ?>
                                    <td class=" "><?php echo $i++;?></td>
                                    <td class=" "><?php echo $this->escapeHtml($employee['first_name']) . ' ';
                                                        echo $this->escapeHtml($employee['middle_name']) . ' ';
                                                        echo $this->escapeHtml($employee['last_name']);
                                                  ?></td>
                                    <td class=" "><?php echo $this->escapeHtml($employee['position_title']);?></td></td>
                                    <td class=" "><?php echo $this->escapeHtml($employee['position_level']);?></td></td>
                                    <td class=" "><?php echo $this->escapeHtml($employee['department_name']);?></td>
                                     <td class=" "><?php echo $this->escapeHtml($employee['recruitment_date']);?></td>
                                    <td class=" "><?php echo $this->escapeHtml($employee['status']);?></td>
                                    <td class=" ">
                                      <a href="<?php echo $this->url('viewnewaddedemployeedetails', array('id' => my_encrypt($employee['id'], $key)));?>" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> View Details</a>
        <?php 
        if($this->organisation_id ==1){ 
          if($employee['status'] == 'Pending') {
            if($employee['submission_status'] == 'Submitted to OVC'){ ?>
              <a href="<?php echo $this->url('generatenewemployeeid', array('id' => my_encrypt($employee['id'], $key))); ?>" class="btn btn-success btn-xs"><i class="fa fa-refresh"></i> Generate ID</a>
            <?php }
          }
          else if($employee['status'] == 'Generated') {
            if(!empty($employee['evidence_file'])){ ?>
              <p>ID Generated & Order uploaded</p><?php 
            } else { ?>
              <a href="<?php echo $this->url('uploadnewemployeeorder', array('id' => my_encrypt($employee['id'], $key))); ?>" class="btn btn-success btn-xs"><i class="fa fa-refresh"></i> Upload Order</a>
            <?php } 
          } 
        } else { 
          if($employee['status'] == 'Pending') {
            if($employee['submission_status'] == 'Do Not Submit to OVC'){ ?>
              <a href="<?php echo $this->url('generatenewemployeeid', array('id' => my_encrypt($employee['id'], $key))); ?>" class="btn btn-success btn-xs"><i class="fa fa-refresh"></i> Generate ID</a>
            <?php }
          }
          else if($employee['status'] == 'Generated') {
            if(!empty($employee['evidence_file'])){ ?>
              <p>ID Generated & Order uploaded</p><?php 
            } else { ?>
              <a href="<?php echo $this->url('uploadnewemployeeorder', array('id' => my_encrypt($employee['id'], $key))); ?>" class="btn btn-success btn-xs"><i class="fa fa-refresh"></i> Upload Order</a>
            <?php } 
          }?>

                                      <?php } ?>
                                    </td>
                                  <?php } ?>
                                  </tr>
                                  <?php endforeach; ?>
                                </tbody>
                              </table>
                            </div>
                          </div>
                        </div>
                    
                        <!-- End of Search--> 
                  </div>
                </div>
              </div>
     </div>
   </div>
 </div>
