<?php
		
	// Add a JavaScript file
	$this->headScript()->appendFile('js/rub-ajax/ajax.js', 'text/javascript');
        
 $title = 'Human Resource Report';
 $this->headTitle($title);
 $organisation_list = array();
 foreach($this->organisationList as $key=>$organisation){
	$organisation_list[$key] = $organisation;
 }

?>

 <div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
            
                <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                     <div class="clearfix"></div>
                    </div>
                	
                        <!-- Search Employees-->
                        <div class="col-md-12 col-xs-12">
                          <div class="x_panel">
                            <div class="x_title">
                              <h2><?php echo $this->escapeHtml("Report")?></h2>
                                <ul class="nav navbar-right panel_toolbox">
                                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                                </ul>
                             <div class="clearfix"></div>
                            </div>
                            <div class="x_content">
                               <?php
                                // Opening of the form tag
                                $form->prepare();
                                echo $this->form()->openTag($form);
                              ?>
                            
                              <div class="row">
                                  <div class="col-md-5 col-sm-12 col-xs-12 form-group">
                                    <label>Report Type</label>
                                    <?php echo $this->formRow($form->get('report_type')); ?>
                                  </div>
                               </div>
                             
                             <div class="row">
                                <div class="ln_solid"></div>
                                <div class="form-group">
                                    <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                                      <?php
                                       echo $this->formHidden($form->get('csrf'));
                                       echo $this->formSubmit($form->get('submit')); 
                                       echo $this->form()->closeTag(); 
                                    ?>
                                </div>
                            </div>
                          </div>
                        </div>
                       </div>     
                          
                        <!-- page content -->
                                  <div class="col-md-12 col-sm-12 col-xs-12">
                                    <div class="x_panel">
                                      <div class="x_content">
                                        <div class="col-md-9 col-sm-9 col-xs-12">
                                          <div class="profile_title">
                                            <div class="col-md-6">
                                              <h2>HR Report</h2>
                                            </div>
                                            <div class="col-md-6">
                                            </div>
                                          </div>
                                          <!-- start of report-graph -->
                                          <div class="x_content">
                                            <canvas id="bar-chart-grouped" style="width:100%; height:280px;"></canvas>
                                          </div>
                                          <!-- end of report-graph -->
                                          
                                          <div class="" role="tabpanel" data-example-id="togglable-tabs">
                                                <!-- start reports -->
                                                <br /><br />
                                                <h2><?php echo "Table";?></h2>
												<?php if($this->hr_report != NULL) {?>
                                                <table class="table table-striped jambo_table table-bordered">
                                                	  <thead>
                                                         <td rowspan="3" style="width:15%">Agency</td>
														 <?php foreach($this->five_year_plan as $year): ?>
                                                         <td colspan="3"><?php echo $year; ?></td>
                                                         <?php endforeach; ?>
                                                      </thead>
                                                      <tr>
                                                        <td rowspan="3"></td>
                                                        <td rowspan="2"><b>Plan-<br />ned</b></td>
                                                        <td colspan="2"><b>Implemented</b></td>
                                                        <td rowspan="2"><b>Plan-<br />ned</b></td>
                                                        <td colspan="2"><b>Implemented</b></td>
                                                        <td rowspan="2"><b>Plan-<br />ned</b></td>
                                                        <td colspan="2"><b>Implemented</b></td>
                                                        <td rowspan="2"><b>Plan-<br />ned</b></td>
                                                        <td colspan="2"><b>Implemented</b></td>
                                                        <td rowspan="2"><b>Plan-<br />ned</b></td>
                                                        <td colspan="2"><b>Implemented</b></td>
                                                      </tr>
                                                      <tr>
                                                        <td><b>P</b></td>
                                                        <td><b>A</b></td>
                                                        <td><b>P</b></td>
                                                        <td><b>A</b></td>
                                                        <td><b>P</b></td>
                                                        <td><b>A</b></td>
                                                        <td><b>P</b></td>
                                                        <td><b>A</b></td>
                                                        <td><b>P</b></td>
                                                        <td><b>A</b></td>
                                                      </tr>
                                                    <tbody>
                                                      
													  <?php foreach($organisation_list as $key => $value) : ?>
                                                      <tr>
                                                      	<td><?php echo $value; ?></td>
                                                        <?php foreach($this->five_year_plan as $year): ?>
                                                        <td><b><?php 
															if(array_key_exists($key, $this->hr_report))	
																echo ($this->hr_report[$key]['Planned']['longterm'][$year] + $this->hr_report[$key]['Planned']['shortterm'][$year]);
															else 
																echo "NA"; ?></b></td>
                                                        <td><?php 
															if(array_key_exists($key, $this->hr_report))
																echo ($this->hr_report[$key]['Planned_implemented']['longterm'][$year] + $this->hr_report[$key]['Planned_implemented']['shortterm'][$year]); 
															else
																echo "NA"; ?></td>
                                                        <td><?php 
															if(array_key_exists($key, $this->hr_report))
																echo ($this->hr_report[$key]['Adhoc']['longterm'][$year] + $this->hr_report[$key]['Adhoc']['shortterm'][$year]); 
															else
																echo "NA"; ?></td>
                                                        <?php endforeach; ?>
                                                      <tr>
													  <?php endforeach; ?>
                                                    </tbody>
                                                  </table>
                                                 <?php } ?>
                                                <!-- end of reports -->
                                          </div>
                                        </div>
                                        <div class="col-md-3 col-sm-3 col-xs-12 profile_left">
                                          <div class="profile_title">
                                            <div class="col-md-6">
                                              <h2>Report</h2>
                                            </div>
                                          </div>
                                          <br />
                    
                                          <!-- report generation -->
                                          <h5><i>*Generate Report. Please note that the graphs will be not be displayed in the generated pdf report. To use the graphs, 
                                                save the graphs from the webpage and paste it to relevant document</i></h5><br />
                                         <a href="<?php echo $this->url('generatehrreports', array('reporttype' => $this->report_type));?>" class="btn btn-success">Generate Report</a>
                                         
                                          <!-- end of report generation -->
                    
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                            <!-- /page content -->
                  </div>
                </div>
              </div>
            </div>
           </div>
     </div>

<script type="text/javascript">

<?php
foreach($organisation_list as $key => $value){
	$phd[$key]= count($this->hr_report[$key]['Contract'][11]) + count($this->hr_report[$key]['Regular'][11]);
	$masters[$key] = count($this->hr_report[$key]['Contract'][10]) + count($this->hr_report[$key]['Regular'][10]);
	$bachelor[$key] = count($this->hr_report[$key]['Contract'][7]) + count($this->hr_report[$key]['Regular'][7]);
	$others[$key] = 0;
}

$this->inlineScript()->captureStart();
echo <<<JS2
new Chart(document.getElementById("bar-chart-grouped"), {
    type: 'bar',
    data: {
      labels: ["CLCS", "CNR", "CST", "GCBS", "GCIT", "JNEC", "PCE", "SCE", "Sherubtse", "YC", "OVC" ],
      datasets: [
        {
          label: "PhD",
          backgroundColor: "#e74c3c",
          data: [$phd[5], $phd[2], $phd[3], $phd[4], 0, $phd[6], $phd[7], $phd[8], $phd[9], 0, $phd[1]]
        }, {
          label: "Masters",
          backgroundColor: "#26b99a",
          data: [$masters[5], $masters[2], $masters[3], $masters[4], 0, $masters[6], $masters[7], $masters[8], $masters[9], 0, $masters[1]]
        }, {
          label: "Bachelor",
          backgroundColor: "#9b59b6",
          data: [$bachelor[5], $bachelor[2], $bachelor[3], $bachelor[4], 0, $bachelor[6], $bachelor[7], $bachelor[8], $bachelor[9], 0, $bachelor[1]]
        }, {
          label: "Diploma/Certificate",
          backgroundColor: "#3498db",
          data: [$others[5], $others[2], $others[3], $others[4], 0, $others[6], $others[7], $others[8], $others[9], 0, $others[1]]
        }
      ]
    },
    options: {
      title: {
        display: true,
        text: 'Total Number (Regular + Contract)'
      }
    }
});
JS2;
$this->inlineScript()->captureEnd();
