<?php
 $title = 'Edit Class 10 and 12 Marks';
 $this->headTitle($title);
 $marks_details = array();
 foreach($this->markDetails as $detail){
	 $marks_details = $detail;
 }

 $applicant_details = array();
 foreach($this->applicantDetails as $applicant){
     $applicant_details = $applicant;
 }

?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    $registrant = $form->get('jobapplicantmarks');
                    $registrant->get('id')->setValue($marks_details['id']);
                    $registrant->get('job_applicant_id')->setValue($marks_details['job_applicant_id']);
                    $registrant->get('x_english')->setValue($marks_details['x_english']);
                    $registrant->get('x_sub1_mark')->setValue($marks_details['x_sub1_mark']);
                    $registrant->get('x_sub2_mark')->setValue($marks_details['x_sub2_mark']);
                    $registrant->get('x_sub3_mark')->setValue($marks_details['x_sub3_mark']);
                    $registrant->get('x_sub4_mark')->setValue($marks_details['x_sub4_mark']);
                    $registrant->get('xll_english')->setValue($marks_details['xll_english']);
                    $registrant->get('xll_sub1_mark')->setValue($marks_details['xll_sub1_mark']);
                    $registrant->get('xll_sub2_mark')->setValue($marks_details['xll_sub2_mark']);
                    $registrant->get('xll_sub3_mark')->setValue($marks_details['xll_sub3_mark']);
                    date_default_timezone_set("Asia/Thimphu");
                    $registrant->get('last_updated')->setValue(date("Y-m-d h:i:s"));
                    echo $this->formHidden($registrant->get('id'));
                    echo $this->formHidden($registrant->get('job_applicant_id'));
                    echo $this->formHidden($registrant->get('last_updated'));
                    $registrant->get('submit')->setValue('Update Marks');
                    ?> 
                    <?php 
                    if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                        echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                        echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                        $messages = $this->flashMessenger()->getMessages();
                        foreach($messages as $message) {
                            echo '<strong>Success!</strong>'. $message;
                        }
                        echo '</div>';
                    }

                    else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                        echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                        echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                        $messages = $this->flashMessenger()->getMessages();
                        foreach($messages as $message) {
                            echo '<strong>Failure!</strong>'. $message;
                        }
                        echo '</div>';
                    }

                ?>
                <h2 class="StepTitle">Job Applicant Details</h2>
                <div class="row">
                    <div class="form-group">
                    <label class="control-label col-md-2 col-sm-2 col-xs-12">Applicant Name:</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                           <h4><i><?php echo $applicant_details['first_name'].' '.$applicant_details['middle_name'].' '.$applicant_details['last_name']; ?></i></h4>
                       </div>
                       <label class="control-label col-md-2 col-sm-2 col-xs-12">Staff ID:</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                           <h4><i><?php echo "NA";                           
                           ?></i></h4>
                       </div>
                    </div>   
                    </div>

                    <div class="row">
                    <div class="form-group">
                    <label class="control-label col-md-2 col-sm-2 col-xs-12">Email ID:</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                           <h4><i><?php echo $applicant_details['email']; ?></i></h4>
                       </div>
                    </div>   
                    <label class="control-label col-md-2 col-sm-2 col-xs-12">Contact No#:</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                           <h4><i><?php echo $applicant_details['contact_no']; ?></i></h4>
                       </div>
                    </div>  
                    
                    <br/><br/>

                <h2 class="StepTitle">1. Class 10 Marks, <small><i>Please enter class 10 English Marks with best four subjects marks. Don't repeat particular subject's mark more than one</i></small></h2><br/> 
                <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">English Mark:<span class="required">*</span></label>
                       <div class="col-md-2 col-sm-2 col-xs-12">
                        <?php echo $this->formRow($registrant->get('x_english')); ?>
                        </div>
                       <label class="control-label col-md-1 col-sm-3 col-xs-12">Best Subject 1 Mark:<span class="required">*</span></label>
                       <div class="col-md-2 col-sm-2 col-xs-12">
                        <?php echo $this->formRow($registrant->get('x_sub1_mark')); ?>
                        </div>
                        <label class="control-label col-md-1 col-sm-2 col-xs-12">Best Subject 2 Mark:<span class="required">*</span></label>
                       <div class="col-md-2 col-sm-2 col-xs-12">
                        <?php echo $this->formRow($registrant->get('x_sub2_mark')); ?>
                        </div>
                      </div>
                  </div>
                  <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Best Subject 3 Mark:<span class="required">*</span></label>
                       <div class="col-md-2 col-sm-2 col-xs-12">
                        <?php echo $this->formRow($registrant->get('x_sub3_mark')); ?>
                        </div>
                       <label class="control-label col-md-1 col-sm-3 col-xs-12">Best Subject 4 Mark:<span class="required">*</span></label>
                       <div class="col-md-2 col-sm-2 col-xs-12">
                        <?php echo $this->formRow($registrant->get('x_sub4_mark')); ?>
                        </div>
                  </div>
                  <br />
                  <h2 class="StepTitle">2. Class 12 Marks, <small><i>Please enter class 12 English Marks with best three subjects marks. Don't repeat particular subject's mark more than one</i></small></h2><br/> 

                  <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">English Mark:<span class="required">*</span></label>
                       <div class="col-md-2 col-sm-2 col-xs-12">
                        <?php echo $this->formRow($registrant->get('xll_english')); ?>
                        </div>
                       <label class="control-label col-md-1 col-sm-3 col-xs-12">Best Subject 1 Mark:<span class="required">*</span></label>
                       <div class="col-md-2 col-sm-2 col-xs-12">
                        <?php echo $this->formRow($registrant->get('xll_sub1_mark')); ?>
                        </div>
                        <label class="control-label col-md-1 col-sm-2 col-xs-12">Best Subject 2 Mark:<span class="required">*</span></label>
                       <div class="col-md-2 col-sm-2 col-xs-12">
                        <?php echo $this->formRow($registrant->get('xll_sub2_mark')); ?>
                        </div>
                      </div>
                  </div>
                  <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Best Subject 3 Mark:<span class="required">*</span></label>
                       <div class="col-md-2 col-sm-2 col-xs-12">
                        <?php echo $this->formRow($registrant->get('xll_sub3_mark')); ?>
                        </div>
                  </div>
                  
                  
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
          						<?php
          						   echo $this->formHidden($form->get('csrf'));
          						   echo $this->formSubmit($registrant->get('submit')); 
                        ?>
                    	</div>
                    </div>
               </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                </div>
              </div>
             </div>
          </div>
        </div> 
     </div>
   </div>
