<?php
/**
 * 
 * Index -- of Closing Balance
 * 
 */
	$this->headTitle($this->title);
?>
<div class="row">
	<div class="space-12"></div>
	<div class="col-xs-12">
		<div class="widget-box transparent">
			<div class="widget-header widget-header-large">
				<h3 class="widget-title grey lighter">
					<i class="ace-icon fa fa-file-text-o green"></i>
					Closing Balance of Year <?php echo $this->selected_year;?>
				</h3>
				<div class="widget-toolbar hidden-xs">
				    <a class="red pull-right DTTT_button btn btn-white btn-info btn-bold" data-tooltip="tooltip" data-placement="top" title="" href="<?php echo $this->url('closing', array('action'=>'addclosing'));?>">
						<span class="red"><i class="fa fa-plus"></i> <span class="hidden-sm hidden-xs">&nbsp;Add Closing </span></span>
					</a>
				</div>
			</div>
			<div class="widget-body">
				<div class="widget-main padding-24">
					<div class="row">
						<div class="col-lg-12">
							<form method="post" class="form-horizontal" action="<?php echo $this->url('closing');?>">
								<label for="module" class="control-label col-lg-1">Year</label>
								<div class="col-lg-2">
									<select id="year" name="year" class="form-control" data-placeholder="Select" onchange="this.form.submit()">
										<?php 
										for($year = date('Y'); $year >= $this->min_year; $year--):
										?>
											<?php $selected = ($year == $this->selected_year)?"selected":"";?>
											<option value="<?php echo $year;?>" <?php echo $selected;?>>
												<?php echo $year;?> 
											</option>
										<?php endfor; ?>
									</select>
								</div>
							</form>
						</div>
					</div>
					<div class="space-12"></div>
					<div class="row">
						<div class="col-lg-12">
							<table class="table table-striped table-bordered table-hover" id="dataTables">
								<thead>
									<tr>
										<th>#</th>
										<th>Subhead</th>
										<th>Closing_dr</th>
										<th>Closing_cr</th>
									</tr>
								</thead>
								<tbody>
									<?php
									$i = 1;
									if($this->closingbalanceObj->isPresent(array('year' => $this->selected_year))):
										foreach($this->closingbalanceObj->get(array('year'=>$this->selected_year)) as $row):?>
											<tr>
												<td><?php echo $i++; ?> </td>
												<td><?php echo $row['sub_head'];?></td>
												<td><?php echo $row['closing_dr'];?></td>
												<td><?php echo $row['closing_cr'];?></td>
											</tr>
										<?php endforeach;	
									else:
										$filter = array(
												'start_date' => date('Y-m-d',strtotime('10-01-'.$this->selected_year)),
												'end_date' => date('Y-m-t',strtotime('01-12-'.$this->selected_year)),
												'organisation' => -1,
										);
										foreach($this->subheadObj->getAll() as $rows):
																			
											$closing_balance = $this->transactiondetailObj->getClosingBalance($filter, $rows['id'], 1);
												
											$closing_cr = ($closing_balance < 0)? -$closing_balance:'0';
											$closing_dr = ($closing_balance > 0)? $closing_balance:'0';
									?>
											<tr>
												<td><?php echo $i++; ?> </td>
												<td><?php echo $rows['name'];?></td>
												<td><?php echo $this->currency($closing_dr);?></td>
												<td><?php echo $this->currency($closing_cr);?></td>
											</tr>
										<?php endforeach;
									endif; ?>				
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
	$('#dataTables').genpdftable({
		src:"<?php echo $this->url('pdfxls', array('action' => 'pdf'));?>",
		orentation:"P",//L =landscape, P = potrait
		caller:'#print-cltable',
	});
</script>
