<?php
  $title = 'Travel Authorization Payment';
  $this->headTitle($title);
  $key = $this->keyphrase;

function my_encrypt($data, $key) {
  // Remove the base64 encoding from our key
  $encryption_key = base64_decode($key);
  // Generate an initialization vector
  $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));
  // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
  $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
  // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
  return bin2hex(base64_encode($encrypted . '::' . $iv));
}
?>

<div class="right_col" role="main">
    <div class="">
        <div class="col-md-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <?php
                    if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                      echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                      echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                      $messages = $this->flashMessenger()->getMessages();
                      foreach ($messages as $message) {
                        echo '<strong>Success!</strong>' . $message;
                      }
                      echo '</div>';
                    } else if ($this->message == 'Failure' && $this->flashMessenger()->hasMessages()) {
                      echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                      echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                      $messages = $this->flashMessenger()->getMessages();
                      foreach ($messages as $message) {
                        echo '<strong>Failure!</strong>' . $message;
                      }
                      echo '</div>';
                    }
                    ?>
                    <?php
                        if ($this->travelDetails['pending_amount'] > 0):
                    ?>
                    <h5><i>*Please add the Travel Authorization Payment Details.</i></h5>
                    <br />
                    <?php
                        // Opening of the form tag
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        $register = $form->get('emptravelPayment');
                        
                        // Set form fields value
                        $register->get('payment_type')->setValueOptions($this->paymentTypes);
                    ?>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Estimated Expenses</label>
                        <div class="col-md-6 col-sm-6 col-xs-12" style="margin-top: 8px;">
                            <?php echo $this->travelDetails['estimated_expenses']; ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Advance Required</label>
                        <div class="col-md-6 col-sm-6 col-xs-12" style="margin-top: 8px;">
                            <?php echo $this->travelDetails['advance_required']; ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Pending Amount</label>
                        <div class="col-md-6 col-sm-6 col-xs-12" style="margin-top: 8px;">
                            <?php echo $this->travelDetails['pending_amount']; ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="amount">Amount<span class="required">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <?php echo $this->formRow($register->get('amount')); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="payment_type">Payment Type<span class="required">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <?php echo $this->formRow($register->get('payment_type')); ?>
                        </div>
                    </div>
                    <div class="form-group" style="display: none;">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="cheque_no">Cheque No<span class="required">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <?php echo $this->formRow($register->get('cheque_no')); ?>
                        </div>
                    </div>
                    <div class="form-group" style="display: none;">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="dd_no">Demand Draft No<span class="required">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <?php echo $this->formRow($register->get('dd_no')); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="status">Status<span class="required">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <?php echo $this->formRow($register->get('status')); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="ln_solid"></div>
                        <div class="form-group text-center">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                              <?php
                              echo $this->formHidden($register->get('csrf'));
                              echo $this->formSubmit($register->get('submit'));
                              ?>
                            </div>
                        </div>
                    </div> 
                    <?php
                        //closing the form tag  
                        echo $this->form()->closeTag();
                        else:
                    ?>
                    <div class="text-center">
                        <h2 class="bg-green">Payment already done</h2>
                    </div>
                    <?php
                        endif
                    ?>
                    <br>
                    <div class="" role="tabpanel" data-example-id="togglable-tabs">
                        <br/>
                        <div class="table-responsive">
                            <table id="datatable-buttons" class="table table-striped jambo_table bulk_action">
                                <thead>
                                    <tr class="headings">
                                        <th class="column-title">Sl.No.</th>
                                        <th class="column-title">Tour Purpose </th>
                                        <th class="column-title">No of Days </th>
                                        <th class="column-title">Estimated Expenses </th>
                                        <th class="column-title">Advance Allowance </th>
                                        <th class="column-title">Amount Paid </th>
                                        <th class="column-title">Status </th>
                                        <th class="column-title">Action </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php 
                                      $i = 1;
                                      foreach ($this->travelPaymentList as $travelPayment):
                                    ?>
                                      <tr class="even pointer">
                                          <td class=" "><?php echo $i++; ?></td>
                                          <td class=" "><?php echo $this->escapeHtml($travelPayment['purpose_of_tour']); ?></td>
                                          <td class=" "><?php echo $this->escapeHtml($travelPayment['no_of_days']); ?></td>
                                          <td class=" "><?php echo $this->escapeHtml($travelPayment['estimated_expenses']); ?></td>
                                          <td class=" "><?php echo $this->escapeHtml($travelPayment['advance_required']); ?></td>
                                          <td class=" "><?php echo $this->escapeHtml($travelPayment['amount']); ?></td>
                                          <td class=" "><?php echo $this->escapeHtml($travelPayment['status']); ?></td>
                                          <td class=" last">
                                              <a href="/public/emptravel/editpayment/<?php echo my_encrypt($travelPayment['id'], $key); ?>" class="btn btn-info btn-xs">
                                                  <i class="fa fa-edit"></i> Edit
                                              </a>
                                              <button data-id="<?php echo my_encrypt($travelPayment['id'], $key); ?>" class="btn btn-danger btn-xs deleteFeePayment">
                                                  <i class="fa fa-trash"></i> Delete
                                              </button>
                                          </td>
                                      </tr>
                                    <?php 
                                      endforeach; 
                                    ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div> 
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
  
  $(document).ready(function () {
      $('#amount').attr('max', '<?php echo $this->travelDetails['pending_amount']; ?>');
      $('#PaymentTypes').on('change', function () {
          var type = $(this).val();
          $('#cheque_no, #dd_no').removeAttr('required').parents('.form-group').css('display', 'none');
          if (type === '2') {
            $('#cheque_no').attr('required', 'required').parents('.form-group').css('display', 'block');
          } else if (type === '3') {
            $('#dd_no').attr('required', 'required').parents('.form-group').css('display', 'block');
          }
      });
      $(document).on('click', ".deleteFeePayment", function () {
        if (confirm('Are you sure you want to delete this record?')) {
          window.location = "/public/emptravel/deletepayment/"+$(this).data('id');
        }
      });
  });
  
</script>
