<?php
  $type = $this->subheadObj->getColumn(array('head'=>$this->head),'type');
  if($type == 1)// Asset
  { 
    $asset_dtls = $this->assetObj->get(array('organisation_id'=>$userorg));
	foreach($asset_dtls as $row);
    $subHeadDtls = $this->subheadObj->get(array('head'=>$this->head,'type'=>$type), $order='name');
  }
  elseif($type == 2)//Bank
  {
	$bankacc_dtls = $this->bankaccountObj->get(array('organisation_id'=>$userorg));
	foreach($bankacc_dtls as $row);
    $bankaccount_id = $row['id'];
    $subHeadDtls = $this->subheadObj->get(array('head'=>$this->head,'ref_id'=>$bankaccount_id,'type'=>$type), $order='name');
  }
  elseif($type == 3)//Cash
  {
	$cashacc_dtls = $this->cashaccountObj->get(array('organisation_id'=>$userorg));
	foreach($cashacc_dtls as $row);
    $cashaccount_id = $row['id'];
    $subHeadDtls = $this->subheadObj->get(array('head'=>$this->head,'ref_id'=>$cashaccount_id,'type'=>$type), $order='name'); 
  }
  elseif($type == 4)//College Stds
  {
    $std_dtls = $this->stdObj->get(array('s.organisation_id'=>$userorg));
	foreach($std_dtls as $row);
    $std_id = $row['id'];
    $subHeadDtls = $this->subheadObj->get(array('head'=>$this->head,'ref_id'=>$std_id,'type'=>$type), $order='name'); 
  }
  elseif($type == 5)//RUB Employee
  {
	$empl_dtls = $this->emplObj->get(array('e.organisation_id'=>$userorg));
	foreach($empl_dtls as $row):
    $empl_id = $row['id'];
    $subHeadDtls = $this->subheadObj->get(array('head'=>$this->head,'type'=>$type), $order='name'); 
    endforeach;	
  }
  elseif($type == 6)//Party
  {
	$pty_dtls = $this->ptObj->get(array('p.organisation_id'=>$userorg));
	foreach($pty_dtls as $row);
    $pty_id = $row['id'];
    $subHeadDtls = $this->subheadObj->get(array('head'=>$this->head,'ref_id'=>$pty_id,'type'=>$type), $order='name');   
  }
  elseif($type == 7)//Budget
  {
	$b_dtls = $this->budgetObj->get(array('b.organisation_id'=>$userorg));
	foreach($b_dtls as $row);
    $b_id = $row['id'];
    $subHeadDtls = $this->subheadObj->get(array('head'=>$this->head,'ref_id'=>$b_id,'type'=>$type), $order='name');    
  }
  elseif($type == 8)//Pay Heads
  {
	$payh_dtls = $this->payhObj->getAll();
	foreach($payh_dtls as $row):
    $payh_id = $row['id'];
    $subHeadDtls = $this->subheadObj->get(array('head'=>$this->head,'type'=>$type), $order='name'); 
    endforeach;	
  }
  else// others = 9
  {
	$subHeadDtls = $this->subheadObj->get(array('head'=>$this->head), $order='name');    
  }
  if(sizeof($subHeadDtls) > 0){	
	     ?>		  
			<div class="col-lg-12">
			<h3>Closing Balance of <?php echo $year; echo " [ ",$this->headObj->getColumn($this->head, 'name'); ?>] </h3>
				<table class="table" id="trdetails_table" style="border-top:2px solid #ddd;">
					<thead>
						<tr>
							<th>#</th>							
							<th>Organisation</th>
							<th>Sub Ledger/SubHead</th>
							<th>Closing Debit</th>
							<th>Closing Credit</th>
						</tr>
					</thead>
					<tbody>
					<?php 
					$i=1;
					 foreach($subHeadDtls as $row):
					    $result = $this->closingbalanceObj->get(array('year'=>$this->year, 'sub_head'=>$row['id']));					  
						if(sizeof($result) > 0):
							foreach( $result as $dtl);						
							$closing_credit = $dtl['closing_cr'];
							$closing_debit = $dtl['closing_dr'] ;
							$id = $dtl['id'];
						else:
						    $closing_credit = "0.00";
							$closing_debit = "0.00";
							$id = 0;
						endif;						
					   ?>
					    <tr> 
							<td><?php echo $i++; ?> </td>
							<td><strong><?php echo $this->orgObj->getColumn($userorg,'organisation_name'); ?> </strong>
							<td><strong><?php echo $row['name']; ?> </strong>
							<input type ="hidden" name="head[]" value="<?php echo $this->headObj->getColumn($this->head, 'id'); ?>">
							<input type ="hidden" name="organisation[]" value="<?php echo $this->orgObj->getColumn($userorg,'id');?>">
							<input type="hidden" name="sub_head[]" value="<?php echo $row['id']; ?>">
							<input type="hidden" value="<?php echo $id; ?>" name="closing_id[]"> </td>
							<td><div class="form-group"> <input type="text" name="closing_dr[]" id="debit" class="form-control" value="<?php echo $closing_debit; ?>" required></div></td>
							<td><div class="form-group"> <input type="text" name="closing_cr[]" id="credit" class="form-control" value="<?php echo $closing_credit; ?>" required></div></td>
						</tr>
					   <?php
 					 endforeach;
					?>
					</tbody>
				</table>
			</div>
<?php			
  }
?>
