<?php 
$title = 'Bank Account';
$this->headTitle($title);
?>
<div class="right_col" role="main">
	<div class=" ">
		<div class="col-md-12 col-xs-12">
			<div class="x_panel">
				<div class="x_title">
					<h2><?php echo $this->escapeHtml($title);?></h2>
					<ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </ul>
					<div class="clearfix"></div>
				</div>
				<div class="pull-right tableTools-container"></div>			
				<a class="pull-right btn btn-primary" href="<?php echo $this->url('asset', array('action'=>'addbankaccount'));?>">
				<span class="white"><i class="fa fa-plus"></i> <span class="hidden-sm hidden-xs">&nbsp;Add Bank Account </span></span>
				</a>
				<div class="pull-right"></div>			
				<?php echo $this->partial('accounts/asset/partial.phtml', array('active' => 'bankaccount')); ?>
				<div class="x_content">
					<div class="table-responsive">
						<table id="datatable" class="table table-striped jambo_table bulk_action">
							<thead>
								<tr class="headings">
									<th>SL. No. </th>
									<th>Account</th>
									<th>Branch</th>
									<th>Organisation</th>
									<th class="">Action</th>
								</tr>
							</thead>
							<tbody>
								<?php
									$i = 1; 
									foreach ($this->rowset as $rows):
								?>
									<tr>
										<td><?php echo $i; ?> </td>
										<td><b><?php echo $rows['bank_account']; ?></b></td>
										<td><?php echo $rows['branch']; ?></td>
										<td><?php echo $rows['organisation']; ?></td>
										<td><div class="btn-group">
										<a class="btn btn-xs btn-info " href="<?php echo $this->url('asset', array('action'=>'editbankaccount', 'id'=>$rows['id']));?>" >
											<span class="white"><i class="fa fa-pencil bigger-120"> Edit</i> <span class="hidden-lg hidden-xs"></span></span>
										</a>
									</div></td>	
									</tr>
								<?php 
								$i++;
								endforeach;  
								?>
							</tbody>
						</table>
		            </div>
		        </div>
		    </div>
		</div>
	</div>
</div>