<?php
 $title = 'Types of Research Publication';
 $this->headTitle($title);
 //$publication_detail = array();
 foreach($this->publicationDetails as $detail){
	 $publication_detail = $detail;
 }
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
        				    $publication = $form->get('publicationtype');
        					$publication->get('organisation_id')->setValue($this->organisation_id);
        					$publication->get('publication_type')->setValue($this->publication_type);
        					$publication->get('id')->setValue($publication_detail['id']);
        					$publication->get('publication_name')->setValue($publication_detail['publication_name']);
        					$publication->get('remarks')->setValue($publication_detail['remarks']);
                            echo $this->formHidden($publication->get('id')); 
        					echo $this->formHidden($publication->get('organisation_id'));
        				  ?>  
                <div class="row">    
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Publication Name<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($publication->get('publication_name')); ?>
                    </div>
                   </div>
                   <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Publication Type<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($publication->get('publication_type')); ?>
                    </div>
                   </div>
                   <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Remarks<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($publication->get('remarks')); ?>
                    </div>
                  </div>
                </div> 
                  
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
						<?php
						   echo $this->formHidden($form->get('csrf'));
						   echo $this->formSubmit($publication->get('submit')); 
                        ?>
                    	</div>
                    </div>
               </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                </div>
              </div>
        
        <!-- Start of table listing publication type -->
        <div class="x_panel">
                <div class="x_content">
                     <div class="table-responsive">
                      <table class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Sl. No</th>
                            <th class="column-title">Publication Name</th>
                            <th class="column-title">Publication Type</th>
                            <th class="column-title">Remarks</th>
                            
                             </tr>
                        </thead>  
                        <tbody>
                      <tr>
                         <?php $i = 1; foreach ($this->publicationList as $list) : ?>
                          <tr class="even pointer">
                            <td class=" "><?php echo $i++;?></td>
                            <td class=" "><?php echo $this->escapeHtml($list['publication_name']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($list['publication_type']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($list['remarks']);?></td>
                          </tr>
                          <?php endforeach; ?>
                      </tr>
                      </tbody>
                      </table>
                     </div>
                  </div>
               </div>
             </div>
        
        
    
          </div>
        </div> 
     </div>
