<?php
 $title = 'COLLEGE ANNUAL RESEARCH GRANT APPLICATION FORM';
 $this->headTitle($title);
 ?>
 <div class="right_col" role="main">
          <div class="">
              <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">

                    <!-- Smart Wizard -->
                    <p>Please fill in the forms which are necessary</p>
                    <div id="wizard" class="form_wizard wizard_horizontal">
                      <ul class="wizard_steps">
                          <li>
                          <a href="#step-1">
                            <span class="step_no">1</span>
                            <span class="step_descr">
                                              Step 1<br />
                                              <small>GRANT</small>
                                          </span>
                          </a>
                        </li>
                        <li>
                          <a href="#step-2">
                            <span class="step_no">2</span>
                            <span class="step_descr">
                                              Step 2<br />
                                              <small>PRINCIPAL  <br/>RESEARCHER</small>
                                          </span>
                          </a>
                        </li>
                        <li>
                          <a href="#step-3">
                            <span class="step_no">3</span>
                            <span class="step_descr">
                                              Step 3<br />
                                              <small>CO-RESEARCHER/S</small>
                                          </span>
                          </a>
                        </li>
                        <li>
                          <a href="#step-4">
                            <span class="step_no">4</span>
                            <span class="step_descr">
                                              Step 4<br />
                                              <small>RESEARCH</small>
                                          </span>
                          </a>
                        </li>
                        <li>
                          <a href="#step-5">
                            <span class="step_no">5</span>
                            <span class="step_descr">
                                              Step 5<br />
                                              <small>RESEARCH/PROJECT <br/>SUMMARY</small>
                                          </span>
                          </a>
                        </li>
                        <li>
                          <a href="#step-6">
                            <span class="step_no">6</span>
                            <span class="step_descr">
                                              Step 6<br />
                                              <small>ACTION <br/>PLAN</small>
                                          </span>
                          </a>
                        </li>
                        <li>
                          <a href="#step-7">
                            <span class="step_no">7</span>
                            <span class="step_descr">
                                              Step 7<br />
                                              <small>BUDGET</small> 
                                          </span>
                          </a>
                        </li>
                        <li>
                          <a href="#step-8">
                            <span class="step_no">8</span>
                            <span class="step_descr">
                                              Step 8<br />
                                              <small>Documents</small> 
                                          </span>
                          </a>
                        </li>
                        
                      </ul>
                        <div id="step-1">
                            <h2 class="StepTitle">Step 1: GRANT</h2>
                          <form class="form-horizontal form-label-left input_mask"><br/>
                        <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Grant applied for</label>
                        <div class="col-md-5 col-sm-5 col-xs-12">
                          <select class="form-control">
                                <option>--Select Grant Type--</option>
                                <option>Beginner Faculty Researcher </option>
                                <option>Early Career Researcher </option>
                                <option>Mid-Career Researcher </option>
                                 <option>Advanced Career Researcher </option>
                           </select>
                            
                        </div>
                        </div>
                          </form>
                        </div>
                    
                      <div id="step-2">
                      <h2 class="StepTitle">Step 2:PRINCIPAL RESEARCHER</h2>
                          <form class="form-horizontal form-label-left input_mask"><br/>

                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Name</label>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                          <input type="text" class="form-control" placeholder="Name">
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Qualification</label>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                          <input type="text" class="form-control" placeholder="Qualification">
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Position level</label>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                          <input type="text" class="form-control" placeholder="Lecturer">
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Appointment Year</label>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                          <input type="text" class="form-control" placeholder="Enter year appointed to the current level">
                        </div>
                      </div>         
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">E-mail</label>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                          <input type="text" class="form-control" placeholder="Enter your email">
                        </div>
                      </div>         
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Contact No.</label>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                          <input type="text" class="form-control" placeholder="Enter your phone">
                        </div>
                      </div>         
                </form>
                 <h2 class="Title">CARG Category:(Please tick)</h2>     
                 <form class="form-horizontal form-label-left input_mask"><br/>
                    <div class="form-group">
                        <div class="col-md-2 col-sm-3 col-xs-12 control-label">
                        </div>

                        <div class="col-md-9 col-sm-9 col-xs-12">
                         
                          
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" class="flat">Category1;
                                </label>
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" class="flat">Category2
                                </label>
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" class="flat">Category3
                                </label>
                            </div>
                          </div>
                      </div>
                    </form>     
                </div>
                   <div id="step-3">
                        <h2 class="StepTitle">Step 3: CO-RESEARCHER</h2>
                                      <form class="form-horizontal form-label-left input_mask"><br/>

                                          
                                          <div class="x_panel">
                               
                <div class="x_content">
                    <!--<div>
                        <a href="applytransfer"> <button type="submit" class="btn btn-primary">Apply for Transfer of Goods</button></a>
                          <div class="ln_solid"></div>
                        </div> !-->
                     <div class="table-responsive">
                                         
                      <table class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                            
                            <th class="column-title">Full Name </th>
                            <th class="column-title">Faculty/Student </th>
                            <th class="column-title">Qualification </th>
                            <th class="column-title">Position level </th>
                            <th class="column-title">Appointment Year </th>
                            <th class="column-title">Email </th>
                            <th class="column-title">Contact No </th>
                             <th class="column-title">CARG Category </th>
                             <th class="column-title">Action</th>
                            <th class="bulk-actions" colspan="7">
                              <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                            </th>
                             </tr>
                        </thead>  
                        <tbody>
                      <tr class="even pointer">
                          
                          <td><input type="text"></td>
                        <td><select class="form-control">
                                <option>Select</option>
                                <option>Faculty</option>
                                <option>Student</option>
                                
                            </select></td>
                        <td><input type="text"></td>
                        <td><select class="form-control">
                                <option>Select</option>
                                <option>P1</option>
                                <option>P2</option>
                                
                            </select></td>
                        <td><select class="form-control">
                                <option>Select</option>
                                <option>2013</option>
                                <option>2014</option>
                                <option>2015</option>
                                
                            </select></td>
                        
                            <td><input type="email"></td>
                            <td><input type="text"></td>
                            <td><select class="form-control">
                                <option>Select</option>
                                <option>Cat1</option>
                                <option>Cat2</option>
                                <option>Cat3</option>
                                
                            </select></td>
                        
                        <td><button class="btn btn-primary fa fa-plus">Add More</button></td>
                        
                        
                      </tr>
                      
                      </tbody>
                                            
                      </table>
                     </div></div></div>
                      
                          
                    </form>
                  
                    </div>
                                                
                      <div id="step-4">
                          <h2 class="StepTitle">Step 4: Research/Project Title</h2>
                          <form class="form-horizontal form-label-left input_mask"><br/>

                      <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Research Title</label>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                          <input type="text" class="form-control" placeholder="Enter project/research title">
                        </div>
                      </div>
                      
                      <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Total Amount Requested</label>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                          <input type="text" class="form-control" placeholder="Enter total amount requested">
                        </div>
                      </div>         
                    </form>
                      </div>

                      <div id="step-5">
                      <h2 class="StepTitle">Step 5: Research/Project Summary</h2>
                          <form class="form-horizontal form-label-left input_mask"><br/>
                              
                      <div class="form-group">
                          <h6><b>Note</b> :( Write a Plain English summary in no more than 150 words focusing on the overall goals and significance of the research/project )</h6>
                          <label class="control-label col-md-3 col-sm-3 col-xs-12">Research/Project Summary</label>
                  <div class="col-md-9 col-sm-9 col-xs-12">
                    <textarea class="resizable_textarea form-control" style="width: 90%; overflow: hidden; word-wrap: break-word; resize: horizontal; height: 87px;">
                    </textarea>
                  </div>
                      </div> <br>
                              <div class="table-responsive">
                         <table class="table table-striped jambo_table">
                         <thead>
                             <tr>
                                 <th>Previously Received Grants</th>
                                 <th>Yes / No</th>
                                 <th>Year</th>
                                 <th>Amount</th>
                                 <th>Year</th>
                                 <th>Amount</th>
                             </tr>
                         </thead>
                         <tbody>
                             
                             <tr>
                                 <td><label>Has the Principal Researcher previously received Annual Research University Grant(AURG)in past two years:</label></td>
                                 <td><select class="form-control">
                                <option>Select</option>
                                <option>Yes</option>
                                <option>No</option>
                                                               
                            </select></td>
                                 <td><select class="form-control">
                                <option>Select</option>
                                <option>2014</option>
                                <option>2015</option>
                                <option>2016</option>
                                
                            </select></td>
                            <td><input type="number" class="form-control"></td>
                                 <td><select class="form-control">
                                <option>Select</option>
                                <option>2014</option>
                                <option>2015</option>
                                <option>2016</option>
                                
                            </select></td>
                            <td><input type="number" class="form-control"></td>
                             </tr>
                             <tr>
                                 <td><label>Has the Principal Researcher previously received Annual Research College Grantin past two years::</label></td>
                                 <td><select class="form-control">
                                <option>Select</option>
                                <option>Yes</option>
                                <option>No</option>
                                                               
                            </select></td>
                                 <td><select class="form-control">
                                <option>Select</option>
                                <option>2014</option>
                                <option>2015</option>
                                <option>2016</option>
                                
                            </select></td>
                            <td><input type="number" class="form-control"></td>
                                 <td><select class="form-control">
                                <option>Select</option>
                                <option>2014</option>
                                <option>2015</option>
                                <option>2016</option>
                                
                            </select></td>
                            <td><input type="number" class="form-control"></td>
                             </tr>
                         
                         </tbody>
                         
                         </table>
                     </div> 
                      
                    </form>
                      </div>
                        
                        <div id="step-6">
                            <h2 class="StepTitle">Step 6: Action Plan</h2>
                            <h4 class="StepTitle">(Detail plan of action to implement this research/project)</h4>
                          <form class="form-horizontal form-label-left input_mask"><br/>
                           
                              
                              <div class="x_panel">
                               
                <div class="x_content">
                    <!--<div>
                        <a href="applytransfer"> <button type="submit" class="btn btn-primary">Apply for Transfer of Goods</button></a>
                          <div class="ln_solid"></div>
                        </div> !-->
                     <div class="table-responsive">
                                         
                      <table class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                            
                            <th class="column-title">Activity </th>
                            <th class="column-title">Time Frame </th>
                            <th class="column-title">Remarks </th>
                            <th class="column-title">Action</th>
                            <th class="bulk-actions" colspan="7">
                              <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                            </th>
                             </tr>
                        </thead>  
                        <tbody>
                      <tr class="even pointer">
                          
                          <td><input type="text"></td>
                        <td><input type="text"></td>
                        <td><input type="text"></td>
                                               
                        <td><button class="btn btn-primary fa fa-plus">Add More</button></td>
                        
                        
                      </tr>
                      
                      </tbody>
                                            
                      </table>
                     </div></div></div>
                       
 </form>
            </div>
                        
            <div id="step-7">
          <h2 class="StepTitle">Step 7: Budget</h2> 
<h4 class="StepTitle">(Provide detailed breakdown of budget requested in item 4 above)</h4>
                                   <form class="form-horizontal form-label-left input_mask"><br/>
                           
                                       
                                       <div class="x_panel">
                               
                <div class="x_content">
                    <!--<div>
                        <a href="applytransfer"> <button type="submit" class="btn btn-primary">Apply for Transfer of Goods</button></a>
                          <div class="ln_solid"></div>
                        </div> !-->
                     <div class="table-responsive">
                                         
                      <table class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                            
                            <th class="column-title">Purpose </th>
                            <th class="column-title">Amount </th>
                            <th class="column-title">Remarks </th>
                            <th class="column-title">Action</th>
                            <th class="bulk-actions" colspan="7">
                              <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                            </th>
                             </tr>
                        </thead>  
                        <tbody>
                      <tr class="even pointer">
                          
                          <td><input type="textarea"></td>
                          <td><input type="number"></td>
                        <td><input type="textarea"></td>
                                               
                        <td><button class="btn btn-primary fa fa-plus">Add More</button></td>
                        
                        
                      </tr>
                      
                      </tbody>
                                            
                      </table>
                     </div></div></div>
                                       <br>
                        <div class="form-group">     
                         <label class="control-label col-md-2 col-sm-2 col-xs-12">College Ethics Committee Approval Number </label>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                          <input type="number" class="form-control" >
                        </div>
                        </div>
                                       
                        <div class="form-group">     
                         <label class="control-label col-md-2 col-sm-2 col-xs-12">Total Amount Granted by CRC </label>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                          <input type="number" class="form-control" >
                        </div>
                        </div>
                                       
              </form>
          </div>
                        <div id="step-8">
                            <h2 class="StepTitle">Step 8: UPLOAD DOCUMENTS (scanned copy)</h2><br/>
                          <form class="form-horizontal form-label-left input_mask">
                              
                      <div class="form-group">
                            <label class="control-label col-md-4 col-sm-4 col-xs-12">Certification duly signed by all Researchers</label>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                            <input type="file" class="form-control" placeholder="">
                        </div>
                      </div>
                       <div class="form-group">
                         <label class="control-label col-md-4 col-sm-4 col-xs-12">Certification duly signed by all CRC Members</label>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                          <input type="file" class="form-control" placeholder="">
                        </div>
                        </div>
                              <div class="form-group">
                         <label class="control-label col-md-4 col-sm-4 col-xs-12">Research Proposal Document</label>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                          <input type="file" class="form-control" placeholder="">
                        </div>
                        </div>
                              
                           
                                                  
                           <div class="clearfix"></div>
                            <div class="ln_solid"></div>
                          
                      <h2 class="StepTitle">DECLARATION: Please Check to Confirm</h2>
                        <div class="form-group">
                        <div class="col-md-1 col-sm-1 col-xs-12">
                            <input type="checkbox" class="flat"></div>
                            <div class="col-md-11 col-sm-11 col-xs-12"><p> 
                            I certify that the research/project can be accommodated within the general
                            understanding of the College in relation to workloads,leave availability, and overall research facilities.</p>
                           </div>
                        </div>        
                            
                    </form>
                      </div>
      </div>
       </div>
        </div>
   </div>
    </div>
   </div></div>
         
     
        
        <?php     
$this->inlineScript()->captureStart();
echo <<<JS
      $(document).ready(function() {
        $('#wizard').smartWizard();

        $('.buttonNext').addClass('btn btn-success');
        $('.buttonPrevious').addClass('btn btn-primary');
        $('.buttonFinish').addClass('btn btn-default');
      });
JS;
$this->inlineScript()->captureEnd(); 

