<?php
// Add a JavaScript file
echo $this->headScript()->appendFile($this->basePath('bower_components/jquery-ui/jquery-ui.min.js'));

$title = 'Leave Application Form';
$this->headTitle($title);
?>
<div class="right_col" role="main">
    <div class="">
        <div class="col-md-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title) ?></h2>
                    <div class="clearfix"></div>
                </div>
                <?php if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
          echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
          echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
          $messages = $this->flashMessenger()->getMessages();
          foreach ($messages as $message) {
            echo '<strong>Success!</strong>' . $message;
          }
          echo '</div>';
        } else if ($this->message == 'Failure' && $this->flashMessenger()->hasMessages()) {
          echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
          echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
          $messages = $this->flashMessenger()->getMessages();
          foreach ($messages as $message) {
            echo '<strong>Warning!</strong>' . $message;
          }
          echo '</div>';
        } ?>
                <div class="x_content">
                    <br />
                    <?php
          // Opening of the form tag
          $form->prepare();
          echo $this->form()->openTag($form);
          $leave = $form->get('employeeleave');
          echo $this->form()->openTag($form);
          echo $this->formHidden($leave->get('id'));
          $leave->get('emp_leave_category_id')->setValue($this->emp_leave_category_id);
          $leave->get('employee_details_id')->setValue($this->employee_details_id);
          $leave->get('applied_by_id')->setValue($this->employee_details_id);
          $leave->get('leave_status')->setValue('Pending');
          $leave->get('substitution')->setValueOptions($this->employeeList);
          echo $this->formHidden($leave->get('emp_leave_category_id'));
          echo $this->formHidden($leave->get('employee_details_id'));
          echo $this->formHidden($leave->get('applied_by_id'));
          echo $this->formHidden($leave->get('leave_status'));
          ?>

                    <div class="row">
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-12 col-xs-12">Assign Substitution: <span
                                    class="required">*</span></label>
                            <div class="col-md-6 col-sm-12 col-xs-12">
                                <?php echo $this->formRow($leave->get('substitution')); ?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group">
                            <label class="control-label col-md-7 col-sm-12 col-xs-12">Note: While applying for Casual,
                                Annual & Earned Leave, please exclude the weekend and local holiday.</Lable>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-12 col-xs-12">Total No. of Days: <span
                                    class="required">*</span></label>
                            <div class="col-md-6 col-sm-12 col-xs-12">
                                <?php echo $this->formRow($leave->get('days_of_leave')); ?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-12 col-xs-12">From Date:(mm/dd/yyyy) <span
                                    class="required">*</span></label>
                            <div class="col-md-2 col-sm-12 col-xs-12">
                                <?php echo $this->formRow($leave->get('from_date')); ?>
                            </div>
                            <label class="control-label col-md-2 col-sm-12 col-xs-12">To Date:(mm/dd/yyyy) <span
                                    class="required">*</span></label>
                            <div class="col-md-2 col-sm-12 col-xs-12">
                                <?php echo $this->formRow($leave->get('to_date')); ?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-12 col-xs-12">Reasons:<span
                                    class="required">*</span></label>
                            <div class="col-md-6 col-sm-12 col-xs-12">
                                <?php echo $this->formRow($leave->get('reason')); ?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-12 col-xs-12">Attach Documents(if any) </label>
                            <div class="col-md-6 col-sm-12 col-xs-12">
                                <?php echo $this->formRow($leave->get('evidence_file')); ?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12"></label>
                            <div class="col-md-3 col-sm-3 col-xs-12">
                                <?php
                echo $this->formRow($form->get('csrf'));
                echo $this->formSubmit($leave->get('submit'));
                ?>
                                <script type="text/javascript"
                                    src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
                                <script type="text/javascript">
                                $(window).on('beforeunload', function() {
                                    $("input[type=submit], input[type=button]").prop("disabled", "disabled");
                                });
                                </script>
                            </div>
                        </div>
                    </div>
                    <?php
          echo $this->form()->closeTag();
          ?>

                </div>
            </div>
        </div>

    </div>
</div>


<script type="text/javascript">
<?php
  $this->inlineScript()->captureStart();
  echo <<<JS
var dateToday = new Date();
var dates = $("#single_cal3, #single_cal4").datepicker({
    defaultDate: "+1w",
    changeMonth: true,
    numberOfMonths: 2,
    minDate: dateToday,
    onSelect: function(selectedDate) {
        var option = this.id == "single_cal3" ? "minDate" : "maxDate",
            instance = $(this).data("datepicker"),
            date = $.datepicker.parseDate(instance.settings.dateFormat || $.datepicker._defaults.dateFormat, selectedDate, instance.settings);
        dates.not(this).datepicker("option", option, date);
    }
});
JS;
  $this->inlineScript()->captureEnd();