<?php

 $title = 'Resignation Details';
 $this->headTitle($title);
 
 $resignationApplication = array();
 
 foreach($this->resignationDetails as $detail){
	 $resignationApplication = $detail;
 }
 ?>

<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				    $resignation = $form->get('employeeresignation');
				  ?>  
                <h2 class="">Staff Details</h2>
                <div class="row">
                <div class="form-group">
                 	 <label class="control-label col-md-3 col-sm-3 col-xs-12">Staff Name:<span class="required">*</span></label>
                    <div class="col-md-2 col-sm-6 col-xs-12">
                 	<input type="text" class="form-control" placeholder="<?php echo $resignationApplication['first_name'].' ' .$resignationApplication['middle_name'].' '.
								$resignationApplication['last_name']; ?>" disabled="disabled">
                 	</div>
                    <label class="control-label col-md-2 col-sm-3 col-xs-12">Staff ID:<span class="required">*</span></label>
                    <div class="col-md-2 col-sm-6 col-xs-12">
                      <input type="text" class="form-control" placeholder="<?php echo $resignationApplication['emp_id']; ?>" disabled="disabled">
                    </div>
                </div>
                </div>
                <div class="row">
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Date of Birth:<span class="required">*</span></label>
                    <div class="col-md-2 col-sm-6 col-xs-12">
                      <input type="text" class="form-control" placeholder="<?php echo $resignationApplication['date_of_birth']; ?>" disabled="disabled">
                    </div>
                </div>
                </div>
                <br /><br />
                <h2 class="">Resignation Application Details</h2>
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Resignation Type:<span class="required">*</span></label>
                    <div class="col-md-2 col-sm-6 col-xs-12">
                      <input type="text" class="form-control" placeholder="<?php echo $resignationApplication['resignationType']; ?>" disabled="disabled">
                    </div>
                    <label class="control-label col-md-2 col-sm-3 col-xs-12">Date of Application:<span class="required">*</span></label>
                    <div class="col-md-2 col-sm-6 col-xs-12">
                      <input type="text" class="form-control" placeholder="<?php echo $resignationApplication['date_of_application']; ?>" disabled="disabled">
                    </div>
                </div>
                </div>
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Reason:<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <textarea class="form-control" rows="3" disabled="disabled" placeholder='<?php echo $resignationApplication['reason_for_resignation']; ?>'></textarea>
                    </div>
                </div>
                </div> 
                  
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                    	</div>
                    </div>
               </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                </div>
              </div>
        </div>

             
          </div>
        </div> 
     </div>
            
         
              
       
                