<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
<div class="menu_section">
<br><br><br>
<ul class="nav side-menu">
	<li><a><i class="fa fa-home"></i>Home<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a href="<?php echo $this->url('index') ?>">Dashboard</a></li>
		</ul>
	</li>
	<li><a><i class="fa fa-users"></i>Human Resource<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>HR Administration<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>Leave<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('leavestatus') ?>">Apply Leave</a></li>
						<li><a href="<?php echo $this->url('empleaveapproval') ?>">Leave Approval</a></li>
						<li><a href="<?php echo $this->url('staffleavestatus') ?>">My Leave Status</a></li>
						<li><a href="<?php echo $this->url('applyonbehalfleave') ?>">Apply Leave On Behalf</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Leave Encashment<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('empleaveencashmentapplication') ?>">Leave Encashment</a></li>
					</ul>
					</li>
					<li><a href="<?php echo $this->url('empassignofficiatingsupervisor') ?>">Assign Officiating Supervisor</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Staff Lifecycle<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>Transfer<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('applytransferform') ?>">Apply Transfer</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Promotion<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('empapplypromotion') ?>">Apply Promotion</a></li>
						<li><a href="<?php echo $this->url('empmeritoriouspromotion') ?>">Meritorious Promotion</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Separation<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('empresignation') ?>">Apply Resignation</a></li>
					</ul>
					</li>
			</ul>
			</li>
			<li><a><i class=""></i>HR Development<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('applytrainings') ?>">Apply Trainings & Workshops</a></li>
			</ul>
			</li>
		</ul>
	</li>
	<li><a><i class="fa fa-graduation-cap"></i>Academic<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>Programme<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('addnewprogramme') ?>">New Programme</a></li>
					<li><a href="<?php echo $this->url('listprogrammes') ?>">Update Programme</a></li>
					<li><a href="<?php echo $this->url('programmeshistory') ?>">Programme Record</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Modules<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('addnewmodule') ?>">Add Modules</a></li>
					<li><a href="<?php echo $this->url('moduleassessmentcomponent') ?>">Module Assessment Component</a></li>
					<li><a href="<?php echo $this->url('addassessmentcomponenttypes') ?>">Assessment Component Types</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Module Allocation<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('assignmodulecoordinator') ?>">Assign Module Coordinator</a></li>
					<li><a href="<?php echo $this->url('assignmoduletotutors') ?>">Assign Module Tutor</a></li>
					<li><a href="<?php echo $this->url('allocatemoduleacademicyear') ?>">Assign Modules for Academic Year</a></li>
					<li><a href="<?php echo $this->url('assignmodule') ?>">Assign Module Tutor for Academic Year</a></li>
					<li><a href="<?php echo $this->url('viewacademicyeartutor') ?>">View Module Tutor for Academic Year</a></li>
					<li><a href="<?php echo $this->url('viewacademicyearmodule') ?>">View Module Allocation by Academic Year</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Academic Assessment<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('academicassessment') ?>">Continuous Assessment</a></li>
					<li><a href="<?php echo $this->url('viewassessmentmarks') ?>">View Continuous Assessment</a></li>
					<li><a href="<?php echo $this->url('editassessmentmarks') ?>">Edit Continuous Assessment</a></li>
					<li><a href="<?php echo $this->url('semesterassessment') ?>">Semester Marks</a></li>
					<li><a href="<?php echo $this->url('viewsemestermarks') ?>">View Semester Marks</a></li>
					<li><a href="<?php echo $this->url('editsemestermarks') ?>">Edit Semester Marks</a></li>
					<li><a href="<?php echo $this->url('viewconsolidatedmarks') ?>">View Consolidated Marks</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Timetable<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('addtimetable') ?>">Add Timetable</a></li>
					<li><a href="<?php echo $this->url('viewtimetable') ?>">View Student Timetable</a></li>
					<li><a href="<?php echo $this->url('viewtutortimetable') ?>">View Tutor Timetable</a></li>
					<li><a href="<?php echo $this->url('addtimetabletimings') ?>">Academic Timing</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Student Attendance<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('studentattendance') ?>">Attendance Entry</a></li>
					<li><a href="<?php echo $this->url('extraclassattendance') ?>">Extra Class Attendance</a></li>
					<li><a href="<?php echo $this->url('cancelledlectures') ?>">Cancelled/Called Off Lectures</a></li>
					<li><a href="<?php echo $this->url('editstudentattendance') ?>">Edit Attendance</a></li>
					<li><a href="<?php echo $this->url('viewstudentattendance') ?>">View Attendance</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Recheck of Marks<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('listrecheckapplicants') ?>">Recheck List</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Reassessment of Modules<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('applyreassessment') ?>">Apply for Reassessment</a></li>
					<li><a href="<?php echo $this->url('listreassessmentapplicants') ?>">Reassessment List</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Repeat Modules<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('applyrepeatmodule') ?>">Apply for Backlog Module</a></li>
					<li><a href="<?php echo $this->url('listrepeatmoduleapplicants') ?>">Repeat Module List</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Consolidated Marks<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('viewconsolidatedmarks') ?>">Consolidated Marks (Module)</a></li>
					<li><a href="<?php echo $this->url('viewprogrammeconsolidatedmarks') ?>">Consolidated Marks (Programme)</a></li>
					<li><a href="<?php echo $this->url('liststudentconsolidatedmarks') ?>">Consolidated Marks (Student)</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Academic Calendar<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('addcalendar') ?>">Add Academic Calendar</a></li>
					<li><a href="<?php echo $this->url('addacademicevent') ?>">Add Academic Event</a></li>
					<li><a href="<?php echo $this->url('addstaffcalendarevent') ?>">Add Calendar Event (Staff)</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Academic Reports<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('academicreports') ?>">Academic Related Reports</a></li>
			</ul>
			</li>
		</ul>
	</li>
	<li><a><i class="fa fa-calendar"></i>Planning<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>Create APA<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>APA Evaluation<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('evaluateapa') ?>">Executive APA Evaluation</a></li>
					</ul>
					</li>
					<li><a href="<?php echo $this->url('apaselfevaluated') ?>">Self Evaluated APA</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>RUB Vision and Mission<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('viewfiveyearplan') ?>">View Vision and Mission</a></li>
			</ul>
			</li>
			<li><a href="<?php echo $this->url('apadates') ?>">Activate APA </a></li>
		</ul>
	</li>
	<li><a><i class="fa fa-database"></i>Property and Inventory<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>Goods Requisition<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('apply-goods-requisition') ?>">Apply Requisition</a></li>
					<li><a href="<?php echo $this->url('view-requisition') ?>">Requisition List</a></li>
			</ul>
			</li>
		</ul>
	</li>
</ul>
</div>
</div>
