<?php
 $title = 'Budget Proposal';
 $this->headTitle($title);

    $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    //IDEA-CBC
    //Original
    //$iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('aes-256-cbc'));

    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));

    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                  </ul>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				            $proposal = $form->get('budgetproposal');
                    echo $this->form()->openTag($form);
                    echo $this->formHidden($proposal->get('id')); 
          					$proposal->get('five_year_plan')->setValue($this->five_year_plan);
                    $proposal->get('financial_year')->setValue($this->financial_year);
          					$proposal->get('departments_id')->setValueOptions($this->departments);
          					$proposal->get('organisation_id')->setValue($this->organisation_id);
          					$proposal->get('budget_proposal_status')->setValue('Not Submitted');
          					$proposal->get('budget_ledger_head_id')->setValueOptions($this->ledgerHeads);
          					//$form->get('accounts_group_head_id')->setValueOptions($this->accountGroupHeads);
          					//$form->get('chart_of_accounts_id')->setValueOptions($this->chartAccounts);
                    echo $this->formHidden($proposal->get('five_year_plan'));
                    echo $this->formHidden($proposal->get('financial_year'));
          				  ?> 
                    <?php 
                    if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                        echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                        echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                        $messages = $this->flashMessenger()->getMessages();
                        foreach($messages as $message) {
                            echo '<strong>Success!</strong>'. $message;
                        }
                        echo '</div>';
                    }

                    else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                        echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                        echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                        $messages = $this->flashMessenger()->getMessages();
                        foreach($messages as $message) {
                            echo '<strong>Failure!</strong>'. $message;
                        }
                        echo '</div>';
                    }

                ?>  
                <div class="row">    
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Five Year Plan</label>
                    <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <input type="text" class="form-control" placeholder="<?php  echo $this->five_year_plan; ?>" readonly>
                    </div>
                    <label class="control-label col-md-2 col-sm-3 col-xs-12">Financial Year</label>
                    <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <input type="text" class="form-control" placeholder="<?php  echo $this->financial_year; ?>" readonly>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Organisation</label>
                    <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <input type="text" class="form-control" placeholder="<?php echo $this->organisation_list[$this->organisation_id]; ?>" readonly>
                    </div>
                    <label class="control-label col-md-2 col-sm-3 col-xs-12">Office/Department</label>
                    <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($proposal->get('departments_id')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Programme (Ledger Name)<span class="required">*</span></label>
                    <div class="col-md-7 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($proposal->get('budget_ledger_head_id')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Activity / Accounts Group Head<span class="required">*</span></label>
                    <div class="col-md-7 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($form->get('accounts_group_head_id')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Chart of Accounts<span class="required">*</span></label>
                    <div class="col-md-7 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($form->get('chart_of_accounts_id')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Budget Type<span class="required">*</span></label>
                    <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($proposal->get('budget_type')); ?>
                    </div>
                    <label class="control-label col-md-2 col-sm-3 col-xs-12">Proposed Budget (Amount)<span class="required">*</span></label>
                    <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($proposal->get('proposed_budget_amount')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Write Up<span class="required">*</span></label>
                    <div class="col-md-7 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($proposal->get('write_up')); ?>
                    </div>
                  </div>
                </div> 
                  
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
						<?php
              echo $this->formHidden($proposal->get('budget_proposal_status'));
						   echo $this->formHidden($proposal->get('organisation_id'));
						   echo $this->formHidden($form->get('csrf'));
						   echo $this->formSubmit($proposal->get('submit')); 
                        ?>
                    	</div>
                    </div>
               </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                </div>
              </div>
        <!-- Start of table listing budget ledgers -->
        <div class="x_panel">
            <div class="x_title">
                  <h2><?php echo $this->escapeHtml('Budget Proposal List'); ?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                  </ul>
                 <div class="clearfix"></div>
                </div>
                <h5><i>*The following are the list of the proposals to be submitted by the Department. You can view/edit/delete the proposal before submitting
                  			to the HRO of the College/Organisation. Once submitted, then you will not be able to edit the proposal</i></h5>
                  <br />
                <div class="x_content">
                     <div class="table-responsive">
                      <table class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Sl. No. </th>
                            <th class="column-title">Programme</th>
                            <th class="column-title">Activity</th>
                            <th class="column-title">Chart of Accounts</th>
                            <th class="column-title">Description</th>
                            <th class="column-title">Proposed Amount</th>
                            <th class="column-title">Actions</th>
                          </tr>
                        </thead>  
                        <tbody>
                      <tr>
                         <?php $i =1; foreach ($this->budgetProposals as $proposal) : ?>
                          <tr class="even pointer">
                            <td class=" "><?php echo $i++; ?></td>
                            <td class=" "><?php echo $this->escapeHtml($proposal['ledger_head']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($proposal['group_head']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($proposal['head_of_accounts']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($proposal['write_up']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($proposal['proposed_budget_amount']);?></td>
                            <td class=" "><a href="<?php echo $this->url('viewbudgetproposal', array('id' => my_encrypt($proposal['id'], $key))); ?>" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i>View</a>
                            			  <a href="<?php echo $this->url('editbudgetproposal', array('id' => my_encrypt($proposal['id'], $key), 'role_type' => my_encrypt('INDIVIDUAL', $key))); ?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a>
                                          <a href="<?php echo $this->url('deletecurrentbudgetproposal', array('id' => my_encrypt($proposal['id'], $key))); ?>" class="btn btn-danger btn-xs"><i class="fa fa-thrash-o"></i>Delete</a>
                                    </td>
                          </tr>
                          <?php endforeach; ?>
                      </tr>
                      </tbody>
                      </table>
                     </div>
                 </div>
                 <?php
					// Opening of the form tag
					$submitForm->setAttribute('action', $this->url('updatebudgetproposal', array('action' => 'updateBudgetProposal', 'id' => '1')));
                    $submitForm->prepare();
                    echo $this->form()->openTag($submitForm);
					echo $this->formHidden($submitForm->get('csrf'));
					echo $this->formSubmit($submitForm->get('submit'));
				  ?>
              </div>
              	
    
          </div>
        </div> 
     </div>
   </div>
 </div>
