<?php
 // module/EmployeeDetail/view/employee-detail/employee-detail/emppersonaldetail.phtml:

    $title = 'Reported Student List';
    $this->headTitle($title);

     //get student list in an array
 $studentName = array();
 //$studentId = array();
 //$criteriaName = array();
 $i=1;
 $j=1;
 foreach($this->studentList as $student){
    $studentName[$i] = $student['first_name']. ' ' .$student['middle_name'].' '.$student['last_name'].' ('.$student['studentId'].')';
    $semesterName[$i] = $student['semester'];
    $i++;
 }
 
?>
<div class="right_col" role="main">
    <div class="">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </ul>
                    <div class="clearfix"></div>
                </div> 

                <div class="col-md-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2><?php echo $this->escapeHtml("Search for List of new Student list to add section")?></h2>
                            <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                            </ul>
                            <div class="clearfix"></div>
                  
                        </div>
                       
                        <div class="x_content">
                            <h5><i>*(In order to search the list of new student reported and to add section to them, you have to select programme from drop down list and click on search button to display the list of new students with respect to the programme you select. It will display only the list where you haven't added section of current new batch.)<br />
                                        **When list display, select section from drop down list and at once you can submit their section** </i></h5>
                                  <br />
                            <?php
                            // Opening of the form tag
                            $form->prepare();
                            echo $this->form()->openTag($form);
                            ?>
                        
                            <div class="row">
                                <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Programme</label>
                                    <?php echo $this->formRow($form->get('programmes_id')); ?>
                                </div>
                            </div>                         
                            <div class="row">
                                <div class="ln_solid"></div>
                                <div class="form-group">
                                    <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                                      <?php
                                       echo $this->formHidden($form->get('csrf'));
                                       echo $this->formSubmit($form->get('submit')); 
                                       echo $this->form()->closeTag(); 
                                    ?>
                                </div>
                            </div>                          
                        </div>
                    </div>
                </div>
                

                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2><?php echo $this->escapeHtml("List of student to add section"); ?></h2>
                            <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                            </ul>
                            <div class="clearfix"></div>
                        </div>
                        <?php
                       
                                // Opening of the form tag
                               $studentSectionForm->setAttribute('action', $this->url('updatenewstudentsection', array('action' => 'updateNewStudentSection')));
                                $form->prepare();
                                echo $this->form()->openTag($studentSectionForm);
                                $studentSectionForm->get('studentCount')->setValue($this->studentCount);
                                $studentSectionForm->get('programmes_id')->setValue($this->programmesId);
                                echo $this->formHidden($studentSectionForm->get('programmes_id'));
                                echo $this->formHidden($studentSectionForm->get('id'));  
                                echo $this->formHidden($studentSectionForm->get('studentCount'));                            
                        ?>      
                        <div class="x_content">
                            <div  class="table-responsive">
                                <table class="table table-striped responsive-utilities jambo_table bulk_action table-bordered">  
                                    <thead>
                                        <tr class="headings">
                                                                      
                                            <th class="column-title" width="10%">Sl.No. </th>
                                            <th class="column-title">Name & Student Id</th>
                                            <th class="column-title">Semester</th>
                                            <th class="column-title">Section</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php for($i = 1; $i<=$this->studentCount; $i++) {?>
                                        <tr class="even pointer">
                                            <td class=" "><?php echo $i; ?></td>
                                            <td class=" "><?php echo $studentName[$i]; ?></td>
                                            <td class=" "><?php echo $semesterName[$i]; ?></td>
                                            <td class=" "><?php echo $this->formRow($studentSectionForm->get('student_section_id'.$i)); ?></td>
                                            
                                        </tr>
                                        <?php  }?>
                                    </tbody>
                                </table>
                            </div>
                        </div>

                        <?php
                            echo $this->formHidden($studentSectionForm->get('csrf'));
                            echo $this->formSubmit($studentSectionForm->get('submit'));
                            echo $this->form()->closeTag();
                        
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>      
</div>           
       
                