<?php

 $title = 'Student Relation Details';
 $this->headTitle($title);
?>

<div class="right_col" role="main">
    <div class=" ">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                </div><!--end of x-title-->
                 <div class="x_content">
                    <?php
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        $parents = $form->get('studentrelationdetails');
                        echo $this->form()->openTag($form);
                        $parents->get('id')->setValue($this->stdRelationDetails->getId());
                        $parents->get('parent_nationality')->setValueOptions($this->nationality);
                        $parents->get('parent_dzongkhag')->setValueOptions($this->dzongkhag);
                        $parents->get('relation_type')->setValueOptions($this->relationType);
                        $parents->get('relation_type')->setValue($this->stdRelationDetails->getRelation_Type());
                        $parents->get('parent_name')->setValue($this->stdRelationDetails->getParent_Name());
                        $parents->get('parent_cid')->setValue($this->stdRelationDetails->getParent_Cid());
                        $parents->get('parent_nationality')->setValue($this->stdRelationDetails->getParent_Nationality());
                        $parents->get('parent_dzongkhag')->setValue($this->stdRelationDetails->getParent_Dzongkhag());
                        $parents->get('parent_occupation')->setValue($this->stdRelationDetails->getParent_Occupation());
                        $parents->get('parent_contact_no')->setValue($this->stdRelationDetails->getParent_Contact_No());
                        $parents->get('parent_address')->setValue($this->stdRelationDetails->getParent_Address());
                        $parents->get('student_id')->setValue($this->stdRelationDetails->getStudent_Id());
                        echo $this->formHidden($parents->get('id'));
                        echo $this->formHidden($parents->get('student_id'));
                        $parents->get('submit')->setValue('Update Relation Details');
                        echo $this->formHidden($parents->get('id')); 

                     ?>
                     <h2>Personal Details</h2> 
                     <hr> 
                 <?php 
                    $personalDetails = array();
                    foreach ($this->stdDetails as $details): {
                        $personalDetails['name'] = $details['first_name'].' '.$details['middle_name'].' '.$details['last_name'];
                        $personalDetails['student_id'] = $details['student_id'];
                        $personalDetails['stdgender'] = $details['stdgender'];
                        $personalDetails['programme_name'] = $details['programme_name'];
                        $personalDetails['student_type'] = $details['student_type'];
                        $personalDetails['enrollment_year'] = $details['enrollment_year'];
                    }

                 ?> 
                    <div class="form-group"> 
                        <label class="control-label col-md-2 col-sm-2 col-xs-12"><b>Name:</b></label>
                            <div class="col-md-4 col-sm-4 col-xs-12">
                                <input type="text" placeholder="<?php echo $personalDetails['name']; ?>" class="form-control" disabled="disabled">
                            </div>
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Student ID:</label>
                            <div class="col-md-4 col-sm-4 col-xs-12">
                                <input type="text" placeholder="<?php echo $personalDetails['student_id']; ?>" class="form-control" disabled="disabled">
                            </div>
                    </div>
                    <div class="form-group"> 
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Gender:</label>
                            <div class="col-md-4 col-sm-4 col-xs-12">
                                <input type="text" placeholder="<?php echo $personalDetails['stdgender']; ?>" class="form-control" disabled="disabled">
                            </div>
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Student Type:</label>
                            <div class="col-md-4 col-sm-4 col-xs-12">
                                <input type="text" placeholder="<?php echo $personalDetails['student_type']; ?>" class="form-control" disabled="disabled">
                            </div>
                    </div>
                    <div class="form-group"> 
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Programme:</label>
                            <div class="col-md-4 col-sm-4 col-xs-12">
                                <input type="text" placeholder="<?php echo $personalDetails['programme_name']; ?>" class="form-control" disabled="disabled">
                            </div>
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Enrollment Year:</label>
                            <div class="col-md-4 col-sm-4 col-xs-12">
                                <input type="text" placeholder="<?php echo $personalDetails['enrollment_year']; ?>" class="form-control" disabled="disabled">
                            </div>
                    </div><br/>
                <?php endforeach; ?>
                 <div class="ln_solid"></div>

                    <h2>Update Student Relation Details</h2>
                    <hr>

                    <div class="row">
                        <div class="col-md-12 center-margin">
                            <div class="form-group col-md-3 col-sm-3 col-xs-12">
                              <label>Relation Type</label>
                              <?php echo $this->formRow($parents->get('relation_type')); ?>
                            </div>
                            <div class="form-group col-md-3 col-sm-3 col-xs-12">
                              <label>Name</label>
                              <?php echo $this->formRow($parents->get('parent_name')); ?>
                            </div>
                            <div class="form-group col-md-3 col-sm-3 col-xs-12">
                              <label>CID No#</label>
                              <?php echo $this->formRow($parents->get('parent_cid')); ?>
                            </div>
                            <div class="form-group col-md-3 col-sm-3 col-xs-12">
                              <label>Nationality</label>
                              <?php echo $this->formRow($parents->get('parent_nationality')); ?>
                            </div>
                        </div>
                    </div> 
                    <div class="row">
                        <div class="col-md-12 center-margin">
                            <div class="form-group col-md-3 col-sm-3 col-xs-12">
                              <label>Dzongkhag</label>
                              <?php echo $this->formRow($parents->get('parent_dzongkhag')); ?>
                            </div>
                            <div class="form-group col-md-3 col-sm-3 col-xs-12">
                              <label>Occupation</label>
                              <?php echo $this->formRow($parents->get('parent_occupation')); ?>
                            </div>
                            <div class="form-group col-md-3 col-sm-3 col-xs-12">
                              <label>Contact No#</label>
                              <?php echo $this->formRow($parents->get('parent_contact_no')); ?>
                            </div>
                            <div class="form-group col-md-3 col-sm-3 col-xs-12">
                              <label>Present Address</label>
                              <?php echo $this->formRow($parents->get('parent_address')); ?>
                            </div>
                         </div>
                    </div>  
                    <div class="form-group">
                    <div class="ln_solid"></div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <?php  
                                    echo $this->formHidden($form->get('csrf')); 
                                    echo $this->formSubmit($parents->get('submit')); 
                                    echo $this->form()->closeTag();
                                    ?>
                                </div>
                        </div>
                    </div>
                    </div>
            </div><!--end of x-content-->
        </div><!--end of x-Panel-->
    </div><!--end of col-md-12 col-xs-12-- >
</div><!--end of ""-->
</div>


 