<?php
 // Inventory/Inventory/view/goods-transaction/goods-transaction/add-item-donar.phtml:

 $title = 'Upload Selected Student Lists';
 $this->headTitle($title);
?>

<div class="right_col" role="main">
  <div class=" ">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2><?php echo $this->escapeHtml($title); ?></h2>
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="col-md-12 col-xs-12">
          <div class="x_panel">
              <div class="x_title">
                  <h2><?php echo $this->escapeHtml("Please select list of selected student list in excel (Format: 'xls')")?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                  </ul>
                  <div class="clearfix"></div>
        
              </div>    
      
              <div class="x_content">
                <?php
                // Opening of the form tag
                          $form->prepare();
                          echo $this->form()->openTag($form);
                          $studentList = $form->get('uploadstudentlists');
                          echo $this->form()->openTag($form);
                          echo $this->formHidden($studentList->get('id'));
                          $studentList->get('upload_date')->setValue(date('Y-m-d'));
                          echo $this->formHidden($studentList->get('upload_date'));
                          $studentList->get('organisation_id')->setValue($this->organisation_id);
                          echo $this->formHidden($studentList->get('organisation_id'));
                          $studentList->get('year')->setValue(date('Y'));
                          echo $this->formHidden($studentList->get('year'));
                ?>
                <?php 
                    if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                        echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                        echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                        $messages = $this->flashMessenger()->getMessages();
                        foreach($messages as $message) {
                            echo '<strong>Success!</strong>'. $message;
                        }
                        echo '</div>';
                    }

                    else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                        echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                        echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                        $messages = $this->flashMessenger()->getMessages();
                        foreach($messages as $message) {
                            echo '<strong>Failure!</strong>'. $message;
                        }
                        echo '</div>';
                    }
                ?>

                <div class="col-md-12 col-sm-12 col-xs-12" style="border: 2px solid #a1a1a1;margin-top: 15px;padding: 10px;">
                  <div class="form-group">           
                    <div class="col-md-6 col-sm-6 col-xs-12">
                            <?php  echo $this->formRow($studentList->get('file_name')); ?>
                    </div>
                  </div>

                  <div class="form-group">
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  
                          echo $this->formRow($form->get('csrf'));
                          echo $this->formRow($studentList->get('submit')); 
                      ?> 
                    </div>
                  </div> 
                  <?php 
                    //closing the form tag  
                     echo $this->form()->closeTag();
                 ?>

                </div> 
                <br>
                  In order to upload the student data, please download the excel format and upload the data.Thanks  <a href="../data/newstudent/student_registration_sample.xls"><button class="btn btn-primary"><i class="fa fa-download"></i> Download Sample Excel </button></a>          
              </div> <!-- End of x-content -->
          </div>
        </div>

        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
              <div class="x_title">
                  <h2><?php echo $this->escapeHtml("Student Data Import Logs"); ?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                  </ul>
                  <div class="clearfix"></div>
              </div>
                       
              <div class="x_content">
                  <div  class="table-responsive">
                      <table id="datatable" class="table table-striped jambo_table bulk_action">  
                          <thead>
                              <tr class="headings">
                                                            
                                  <th class="column-title">Sl.No. </th>
                                  <th class="column-title">Year </th>
                                  <th class="column-title"> Upload Date </th>
                                  <th class="column-title"> Action </th>
                              </tr>
                          </thead>

                          <tbody>
                            <?php $i=1; ?>
                            <?php foreach ($this->newStudentListFile as $studentFile) : ?>
                                <tr class="even pointer">
                                    <td class=" " width="10%"><?php echo $i++; ?></td>
                                    <td class=" " width=""><?php echo $this->escapeHtml($studentFile['year']); ?></td>
                                    <td class=" "><?php echo $this->escapeHtml($studentFile['upload_date']); ?></td>
                                    <td class=" " width="15%">
                                         <a href="<?php echo $this->url('downloadstudentexcellist', array('id' => $studentFile['id']));?>" class="btn btn-primary btn-xs"><i class="fa fa-download"></i> Download Excel File</a></td>
                                </tr>
                            <?php endforeach; ?>
                                            
                                        </tbody>
            
                      </table>
                  </div>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
 