<?php
if($suggestType == 1){
  $title = 'Edit recommend Staff for Counseling';
}

else if($suggestType == 2){
  $title = 'Edit Recommended Student for Counseling';
}
 
 $this->headTitle($title);
 ?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title)?></h2>
                 <div class="clearfix"></div>
                </div>
                
                    <div class="x_content">
                  <?php 
                            if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                                echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                $messages = $this->flashMessenger()->getMessages();
                                foreach($messages as $message) {
                                    echo '<strong>Success!</strong>'. $message;
                                }
                                echo '</div>';
                            }

                            else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                                echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                $messages = $this->flashMessenger()->getMessages();
                                foreach($messages as $message) {
                                    echo '<strong>Failure!</strong>'. $message;
                                }
                                echo '</div>';
                            }
                        ?>
                  <br />
                  <?php 
                  if($suggestType == 1)
                  {
                      $suggestedName;
                      $suggestedId; //this is the student id
                      //$staffId; //this is the auto generated id
                      $staffDetail = $this->suggestedDetails;
                      foreach($staffDetail as $details){
                        $suggestedName = $details['first_name'];
                        $suggestedName .= ' ';
                        $suggestedName .= $details['middle_name'];
                        $suggestedName .= ' ';
                        $suggestedName .= $details['last_name'];
                        $suggestedId = $details['emp_id'];
                        //$stdId = $staff['id'];
                      }
                   }
                   else if($suggestType == 2)
                   {
                      $suggestedName;
                      $suggestedId; //this is the student id
                      //$staffId; //this is the auto generated id
                      $staffDetail = $this->suggestedDetails;
                      foreach($staffDetail as $details){
                        $suggestedName = $details['first_name'];
                        $suggestedName .= ' ';
                        $suggestedName .= $details['middle_name'];
                        $suggestedName .= ' ';
                        $suggestedName .= $details['last_name'];
                        $suggestedId = $details['student_id'];
                        //$stdId = $staff['id'];
                      }
                   }
                  ?>
                  <?php
                  $form->prepare();
                  echo $this->form()->openTag($form);
                  $counsel = $form->get('suggestcounseling');
                  echo $this->form()->openTag($form);
                  $counsel->get('id')->setValue($this->recommendCounseling->getId());
                  $counsel->get('counselor_id')->setValueOptions($this->selectCounselor);
                  $counsel->get('counselor_id')->setValue($this->recommendCounseling->getCounselor_Id());
                  $counsel->get('subject')->setValue($this->recommendCounseling->getSubject());
                  $counsel->get('reason')->setValue($this->recommendCounseling->getReason());
                  $counsel->get('suggested_id')->setValue($this->recommendCounseling->getSuggested_Id());
                  $counsel->get('suggested_by')->setValue($this->recommendCounseling->getSuggested_By());
                  $counsel->get('suggested_date')->setValue($this->recommendCounseling->getSuggested_Date());
                  $counsel->get('suggested_status')->setValue($this->recommendCounseling->getSuggested_Status());
                  $counsel->get('suggested_type')->setValue($this->recommendCounseling->getSuggested_Type());
                  echo $this->formHidden($counsel->get('suggested_id'));  
                  echo $this->formHidden($counsel->get('suggested_by'));
                  echo $this->formHidden($counsel->get('suggested_date'));
                  echo $this->formHidden($counsel->get('suggested_status')); 
                  echo $this->formHidden($counsel->get('suggested_type'));   
                  $counsel->get('submit')->setValue('Edit Suggested');
                  echo $this->formHidden($counsel->get('id')); 
                ?>
                <div class="row">
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Recommended Name <span class="required">*</span></label>
                    <div class="col-md-2 col-sm-2 col-xs-12">
                        <input type="text" placeholder="<?php echo $suggestedName; ?>" class="form-control col-md-7 col-xs-12" disabled="disabled">
                    </div>
                    <label class="control-label col-md-2 col-sm-2 col-xs-12">Recommended ID <span class="required">*</span></label>
                    <div class="col-md-2 col-sm-2 col-xs-12">
                        <input type="text" placeholder="<?php echo $suggestedId; ?>" class="form-control col-md-7 col-xs-12" disabled="disabled">
                    </div>
                  </div>
                </div>
                <br>
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">To: <span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($counsel->get('counselor_id')); ?>
                    </div>
                </div>
                </div>
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Subject: <span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($counsel->get('subject')); ?>
                    </div>
                </div>
                </div>
                <div class="row" >
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Reasons:<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($counsel->get('reason')); ?>
                    </div>
                </div> 
                </div>           
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-2 col-xs-12"></label>
                        <div class="col-md-3 col-sm-3 col-xs-12">
                      <?php 
                      echo $this->formHidden($form->get('csrf'));
                      echo $this->formSubmit($counsel->get('submit')); 
                    ?>
                      </div>
                    </div>
                </div> 
                <?php echo $this->form()->closeTag(); ?>                      
                </div>
                
                
              </div>
            </div>
       </div>       
 	</div>
  </div>
 </div>   
              
              
              
              
              
              
              
              
              
              
              
    