<?php
 $title = 'Leave Details (Supervisor/HRO)';
 $this->headTitle($title);
 
 $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));
    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}

?>

 <div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
            
                <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                     <div class="clearfix"></div>
                    </div>
                    <br/>
                    <?php if($this->message == NULL && $this->flashMessenger()->hasMessages()) {
							echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
							echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
							$messages = $this->flashMessenger()->getMessages();
							foreach($messages as $message) {
								echo '<strong>Success!</strong>'. $message;
							}
							echo '</div>';
                    	} else if($this->message =='Failure' && $this->flashMessenger()->hasMessages()) {
                            echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                            echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                            $messages = $this->flashMessenger()->getMessages();
                            foreach($messages as $message) {
                                echo '<strong>Warning!</strong>'. $message;
                            }
                            echo '</div>';
                     }?>
                     <br/>
                	<!-- Start of Tab-->
                    <div class="" role="tabpanel" data-example-id="togglable-tabs">
                      <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                        <li role="presentation" class="active"><a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">Awaiting Leave</a>
                        </li>
                        <li role="presentation" class=""><a href="#tab_content2" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false">Approved Approval</a>
                        </li>
                        <li role="presentation" class=""><a href="#tab_content3" role="tab" id="profile-tab2" data-toggle="tab" aria-expanded="false">Not Approved Leave</a>
                        </li>
                      </ul>
                      <div id="myTabContent" class="tab-content">
                        <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab">
                          <div class="row">
                             </div>
                                <br/>
                                <div class="table-responsive">
                                  <table id="datatable-buttons" class="table table-striped jambo_table bulk_action">
                                    <thead>
                                      <tr class="headings">
                                        <th class="column-title">Staff Name </th>
                                        <th class="column-title">Staff ID </th>
                                        <th class="column-title">Type of Leave </th>
                                        <th class="column-title">Date From</th>
                                        <th class="column-title">Date To</th>
                                        <th class="column-title">Reasons</th>
                                        <th class="column-title">Applied On</th>
                                        <th class="column-title">Actions</th>
                                      </tr>
                                    </thead>
                                    <tbody>
                                      <?php if(!empty($this->pendingList)){?>
                                       <?php foreach ($this->pendingList as $approval) : ?>
                                        <tr>
                                           <td class=" "><?php echo $this->escapeHtml($approval['first_name'].' '.$approval['middle_name'].' '.$approval['last_name']);?></td>
                                           <td class=" "><?php echo $this->escapeHtml($approval['emp_id']);?></td>
                                           <td class=" "><?php echo $this->escapeHtml($this->leaveCategory[$approval['emp_leave_category_id']]);?></td>
                                           <td class=" "><?php echo $this->escapeHtml($approval['from_date']);?></td>
                                           <td class=" "><?php echo $this->escapeHtml($approval['to_date']);?></td>
                                           <td class=" "><?php echo $this->escapeHtml($approval['reason']);?></td>
                                           <td class=" "><?php echo $this->escapeHtml($approval['created_at']);?></td>
                                           <td><a href="<?php echo $this->url('empleavestatus', array('id' => my_encrypt($approval['id'], $key)));?>" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i>View</a></td>
                                        </tr>
                                     <?php endforeach; ?>
                                   <?php } ?>
                                    </tbody>
                                  </table>
                                </div>
                        </div>
                       <div role="tabpanel" class="tab-pane fade" id="tab_content2" aria-labelledby="profile-tab">
                        	<div class="row">
                            </div>
                            <br/>
                                <div class="table-responsive">
                                  <table id="datatable" class="table table-striped jambo_table bulk_action">
                                    <thead>
                                      <tr class="headings">
                                        <th class="column-title">Staff Name </th>
                                        <th class="column-title">Staff ID </th>
                                        <th class="column-title">Type of Leave </th>
                                        <th class="column-title">Date From</th>
                                        <th class="column-title">Date To</th>
                                        <th class="column-title">Reasons</th>
                                        <th class="column-title">Supervisor Remarks</th>
                                      </tr>
                                    </thead>
                                    <tbody>
                                       <?php if(!empty($this->approvedList)){?>
                                       <?php foreach ($this->approvedList as $approved) : ?>
                                        <tr>
                                           <td class=" "><?php echo $this->escapeHtml($approved['first_name'].' '.$approved['middle_name'].' '.$approved['last_name']);?></td>
                                           <td class=" "><?php echo $this->escapeHtml($approved['emp_id']);?></td>
                                           <td class=" "><?php echo $this->escapeHtml($this->leaveCategory[$approved['emp_leave_category_id']]);?></td>
                                           <td class=" "><?php echo $this->escapeHtml($approved['from_date']);?></td>
                                           <td class=" "><?php echo $this->escapeHtml($approved['to_date']);?></td>
                                           <td class=" "><?php echo $this->escapeHtml($approved['reason']);?></td>
                                           <td class=" "><?php echo $this->escapeHtml($approved['remarks']);?></td>
                                        </tr>
                                     <?php endforeach; ?>
                                   <?php } ?>
                                    </tbody>
                                  </table>
                                </div>
                        </div>
                        
                        <div role="tabpanel" class="tab-pane fade" id="tab_content3" aria-labelledby="profile-tab">
                          <div class="row">
                          </div>
                            <br/>
                            <div class="table-responsive">
                              <table id="datatable-keytable" class="table table-striped jambo_table bulk_action">
                                <thead>
                                  <tr class="headings">
                                    <th class="column-title">Staff Name </th>
                                    <th class="column-title">Staff ID </th>
                                    <th class="column-title">Type of Leave </th>
                                    <th class="column-title">Date From</th>
                                    <th class="column-title">Date To</th>
                                    <th class="column-title">Reasons</th>
                                    <th class="column-title">Supervisor Remarks</th>
                                  </tr>
                                </thead>
                                <tbody>
                                   <?php if(!empty($this->rejectList)){?>
                                   <?php foreach ($this->rejectList as $reject) : ?>
                                    <tr>
                                       <td class=" "><?php echo $this->escapeHtml($reject['first_name'].' '.$reject['middle_name'].' '.$reject['last_name']);?></td>
                                       <td class=" "><?php echo $this->escapeHtml($reject['emp_id']);?></td>
                                       <td class=" "><?php echo $this->escapeHtml($this->leaveCategory[$reject['emp_leave_category_id']]);?></td>
                                       <td class=" "><?php echo $this->escapeHtml($reject['from_date']);?></td>
                                       <td class=" "><?php echo $this->escapeHtml($reject['to_date']);?></td>
                                       <td class=" "><?php echo $this->escapeHtml($reject['reason']);?></td>
                                       <td class=" "><?php echo $this->escapeHtml($reject['remarks']);?></td>
                                    </tr>
                                 <?php endforeach; ?>
                               <?php } ?>
                                </tbody>
                              </table>
                            </div>
                        </div>
                        
                      </div>
                    </div>
                    <!-- End of Tabs-->
                     
                     
                  </div>
                </div>
              </div>
     </div>
          
                     