<?php
 $title = 'Leave Application';
 $this->headTitle($title);
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title)?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				    $leave = $form->get('employeeleave');
                    echo $this->form()->openTag($form);
                    echo $this->formHidden($leave->get('id'));
					$leave->get('emp_leave_category_id')->setValue($this->emp_leave_category_id);
					$leave->get('employee_details_id')->setValue($this->employee_details_id);
					$leave->get('leave_status')->setValue('Pending');
					echo $this->formHidden($leave->get('emp_leave_category_id'));
					echo $this->formHidden($leave->get('employee_details_id'));
					echo $this->formHidden($leave->get('leave_status'));
				  ?>
                <div class="row">    
                 <div class="form-group">
                    <label class="control-label col-md-3 col-sm-12 col-xs-12">Assign Substitution: <span class="required">*</span></label>
                    <div class="col-md-6 col-sm-12 col-xs-12">
                      <?php  echo $this->formRow($leave->get('substitution')); ?>
                    </div>
                  </div>
                 </div>
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-12 col-xs-12">Total No. of Days: <span class="required">*</span></label>
                    <div class="col-md-6 col-sm-12 col-xs-12">
                      <?php  echo $this->formRow($leave->get('days_of_leave')); ?>
                   </div>
                 </div>
                </div>
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-12 col-xs-12">From:(mm/dd/yyyy) <span class="required">*</span></label>
                    <div class="col-md-6 col-sm-12 col-xs-12">
                      <?php  echo $this->formRow($leave->get('from_date')); ?>
                   </div>
                 </div>
                </div>
                  
                <div class="row">    
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-12 col-xs-12">To:(mm/dd/yyyy) <span class="required">*</span></label>
                    <div class="col-md-6 col-sm-12 col-xs-12">
                      <?php  echo $this->formRow($leave->get('to_date')); ?>
                    </div>
                </div>
                </div>   
                
                <div class="row" >
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-12 col-xs-12">Reasons:<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-12 col-xs-12">
                      <?php  echo $this->formRow($leave->get('reason')); ?>
                    </div>
                </div> 
                </div>
                <div class="row" >    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-12 col-xs-12">Attach Documents(only for CL&EL) </label>
                  <div class="col-md-6 col-sm-12 col-xs-12">
                    <?php  echo $this->formRow($leave->get('evidence_file')); ?>
                  </div>
                </div> 
                </div> 
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12"></label>
                        <div class="col-md-3 col-sm-3 col-xs-12">
                    <?php
                        echo $this->formRow($form->get('csrf'));
						echo $this->formSubmit($leave->get('submit')); 
                      ?>
                        </div>
                    </div>
                    </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                       
                </div>
              </div>
            </div>
              
              
             <?php
 $title = 'Leave Details';
 $this->headTitle($title);
 ?>
              <div class="col-md-12 col-xs-12">
                  
                  <div class="x_panel">
                      <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                  </div>
                
                    <div class="x_content">
                        <div class="table-responsive">
                      <table class="table table-striped jambo_table bulk_action"> 
                         <div class="form-group">      
                      </div> 
                        <thead>
                          <tr class="headings">
                           <!--<th>
                              <input type="checkbox" id="check-all" class="flat">
                            </th>-->
                              <th class="column-title">Sl. No</th>
                              <th class="column-title">Substitution Name</th>
                            <th class="column-title">From Date</th>
                            <th class="column-title">To Date</th>
                             <th class="column-title">No.of Days</th>
                            <th class="column-title">Reasons</th>
                            <th class="column-title">Status</th>
                            <th class="bulk-actions" colspan="7">
                              <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                            </th>
                          </tr>
                        </thead>
                        
                        <tbody>
                     
                          <tr>
                            <!--<td>
                              <input type="checkbox" class="flat" name="table_records">
                            </td>-->
                            <td>1</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                    </div>
                
                </div></div></div></div>   
              
              
              
              
              
              
              
              
              
              
              
    