<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
<div class="menu_section">
<br><br><br>
<ul class="nav side-menu">
	<li><a><i class="fa fa-home"></i>Home<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a href="<?php echo $this->url('index') ?>">Dashboard</a></li>
		</ul>
	</li>
	<li><a><i class="fa fa-users"></i>Human Resource<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>HR Planning<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>HRD Planning<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('hrdapprovedlist') ?>">HRD Plan Approved List</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>HRM Planning<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('hrmapprovedlist') ?>">Work Force Approved List</a></li>
					</ul>
					</li>
			</ul>
			</li>
			<li><a><i class=""></i>HR Administration<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>Leave<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('leavestatus') ?>">Apply Leave</a></li>
						<li><a href="<?php echo $this->url('empleaveapproval') ?>">Leave Approval</a></li>
						<li><a href="<?php echo $this->url('staffleavestatus') ?>">My Leave Status</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Leave Encashment<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('empleaveencashmentapplication') ?>">Leave Encashment</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Staff Task<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('employeetaskcategory') ?>">Add Task/Project</a></li>
						<li><a href="<?php echo $this->url('addempemployeetaskrecord') ?>">Add Self Activities</a></li>
						<li><a href="<?php echo $this->url('employeetaskrecord') ?>">Add Other Staff Activities</a></li>
						<li><a href="<?php echo $this->url('viewemployeetaskrecord') ?>">View Staff Task/Activities</a></li>
					</ul>
					</li>
			</ul>
			</li>
			<li><a><i class=""></i>HR Development<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>Long Term Trainings<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('longtermplannedlist') ?>">Planned</a></li>
					</ul>
					</li>
					<li><a href="<?php echo $this->url('applytrainings') ?>">Apply Trainings & Workshops</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Staff Lifecycle<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>Transfer<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('applytransferform') ?>">Apply Transfer</a></li>
						<li><a href="<?php echo $this->url('stafftransferstatus') ?>">My Transfer Status</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Promotion<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('empapplypromotion') ?>">Apply Promotion</a></li>
						<li><a href="<?php echo $this->url('empmeritoriouspromotion') ?>">Meritorious Promotion</a></li>
						<li><a href="<?php echo $this->url('staffpromotionstatus') ?>">My Promotion Status</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Separation<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('empresignation') ?>">Apply Resignation</a></li>
						<li><a href="<?php echo $this->url('resignationrecord') ?>">Dues Record</a></li>
						<li><a href="<?php echo $this->url('staffresignationstatus') ?>">My Resignation Status</a></li>
					</ul>
					</li>
			</ul>
			</li>
			<li><a><i class=""></i>PMS<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>Appraisals<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('administrativeappraisal') ?>">Administrative Appraisal</a></li>
						<li><a href="<?php echo $this->url('academicappraisal') ?>">Academic Appraisal</a></li>
						<li><a href="<?php echo $this->url('appraisalapprovallist') ?>">Appraisal Approval Lists</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Review<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('feedbacks') ?>">Feedbacks</a></li>
					</ul>
					</li>
					<li><a href="<?php echo $this->url('listnominations') ?>">Nominations</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Recruitment<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('listvacancy') ?>">List Job Vacancies</a></li>
					<li><a href="<?php echo $this->url('appliedjobapplicationstatus') ?>">Individual Job Applicant Status</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Staff Tour<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('emptravelauthorization') ?>">Travel Authorization</a></li>
					<li><a href="<?php echo $this->url('stafftourstatus') ?>">Travel Status</a></li>
			</ul>
			</li>
		</ul>
	</li>
	<li><a><i class="fa fa-bank"></i>Admission<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>Student Details<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('studentlists') ?>">Student Lists</a></li>
					<li><a href="<?php echo $this->url('studentpersonaldetails') ?>">Student Personal Details</a></li>
					<li><a href="<?php echo $this->url('studentpermanentaddressdetails') ?>">Student Permanent Address</a></li>
					<li><a href="<?php echo $this->url('studentrelationdetails') ?>">Student Relation Details</a></li>
					<li><a href="<?php echo $this->url('studentpreviousschooldetails') ?>">Student Previous School Details</a></li>
					<li><a href="<?php echo $this->url('studentprofilepicture') ?>">Student Profile Picture</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Admission Report<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('overallstudentreports') ?>">Overall Report</a></li>
			</ul>
			</li>
		</ul>
	</li>
	<li><a><i class="fa fa-graduation-cap"></i>Academic<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>Academic Assessment<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>Continuous Assessment<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('academicassessment') ?>">Add CA Marks</a></li>
						<li><a href="<?php echo $this->url('viewassessmentmarks') ?>">View CA Marks</a></li>
						<li><a href="<?php echo $this->url('editassessmentmarks') ?>">Edit/Moderate CA Marks</a></li>
						<li><a href="<?php echo $this->url('compileassessmentmarks') ?>">Compile CA Marks</a></li>
						<li><a href="<?php echo $this->url('viewcompiledassessmentmarks') ?>">Edit/Moderate Compile CA Marks</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Semester End<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('semesterassessment') ?>">Add SE Marks</a></li>
						<li><a href="<?php echo $this->url('viewsemestermarks') ?>">View SE Marks</a></li>
						<li><a href="<?php echo $this->url('editsemestermarks') ?>">Edit/Moderate SE Marks</a></li>
						<li><a href="<?php echo $this->url('compilesemestermarks') ?>">Compile SE Marks</a></li>
						<li><a href="<?php echo $this->url('viewcompiledsemestermarks') ?>">Edit/Moderate Compile SE Marks</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Repeat Module<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('addreassessmentmarks') ?>">Add Re-assessment Marks</a></li>
						<li><a href="<?php echo $this->url('addrepeatconsolidatedmarks') ?>">Add Repeat Module Marks</a></li>
						<li><a href="<?php echo $this->url('editreconsolidatedmarks') ?>">Edit Repeat & Re-assessment Marks</a></li>
					</ul>
					</li>
					<li><a href="<?php echo $this->url('viewindividualconsolidatedmarks') ?>">View Consolidated Marks</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Modules<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('moduleassessmentcomponent') ?>">Module Assessment Component</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Module Allocation<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('assignmodulecoordinator') ?>">Assign Module Coordinator/Tutor</a></li>
					<li><a href="<?php echo $this->url('assignmoduletotutors') ?>">Assign Module Co-Tutor</a></li>
					<li><a href="<?php echo $this->url('assignmodule') ?>">Allocate Section to Module Tutor</a></li>
					<li><a href="<?php echo $this->url('viewacademicyeartutor') ?>">View Module Tutor for Academic Year</a></li>
					<li><a href="<?php echo $this->url('electivemoduleallocation') ?>">Assign Student for Elective Module</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Assessment Mark Allocation<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('addallocationmark') ?>">Allocate Assessment Marks</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Timetable<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('addtimetable') ?>">Add Timetable</a></li>
					<li><a href="<?php echo $this->url('viewtimetable') ?>">View Student Timetable</a></li>
					<li><a href="<?php echo $this->url('viewtutortimetable') ?>">View Tutor Timetable</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Student Attendance<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('studentattendance') ?>">Attendance Entry</a></li>
					<li><a href="<?php echo $this->url('extraclassattendance') ?>">Extra Class Attendance</a></li>
					<li><a href="<?php echo $this->url('cancelledlectures') ?>">Cancelled/Called Off Lectures</a></li>
					<li><a href="<?php echo $this->url('editstudentattendance') ?>">Edit Attendance</a></li>
					<li><a href="<?php echo $this->url('recordmissingstudentattendance') ?>">Add Missing Attendance</a></li>
					<li><a href="<?php echo $this->url('viewstudentattendance') ?>">View Attendance</a></li>
					<li><a href="<?php echo $this->url('tutordeletestudentattendance') ?>">Delete Attendance</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Consolidated Marks<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('viewconsolidatedmarks') ?>">Consolidated Marks (Module)</a></li>
					<li><a href="<?php echo $this->url('liststudentconsolidatedmarks') ?>">Consolidated Marks (Student)</a></li>
			</ul>
			</li>
		</ul>
	</li>
	<li><a><i class="fa fa-book"></i>Examination<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>Examinations<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('viewexamtimetable') ?>">View Examination Timetable</a></li>
			</ul>
			</li>
		</ul>
	</li>
	<li><a><i class="fa fa-user"></i>Student Services<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>Responsibility<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('responsibilitycategory') ?>">Add New Category</a></li>
					<li><a href="<?php echo $this->url('viewstdresponsibility') ?>">View Responsibility</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Student Disciplinary<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('disciplinarycategory') ?>">Offence Category</a></li>
					<li><a href="<?php echo $this->url('disciplinaryrecord') ?>">Record Disciplinary Problem</a></li>
					<li><a href="<?php echo $this->url('viewdisciplinaryrecord') ?>">View Disciplinary Record</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Character Certificate<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('viewcharactercert') ?>">View Character Certificate</a></li>
					<li><a href="<?php echo $this->url('ccgeneration') ?>">Generate Character Certificate</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Hostel Management<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('identifyroom') ?>">Hostel Inventory</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Extra Curricular Attendance<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('clubsattendance') ?>">Add Club & Unit Attendance</a></li>
					<li><a href="<?php echo $this->url('studentextracurricular') ?>">Add Other Curricular Attendance</a></li>
					<li><a href="<?php echo $this->url('editextracurricularattendance') ?>">Edit Extra Curricular Attendance</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Achievement<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('addachievementcategory') ?>">Add Category</a></li>
					<li><a href="<?php echo $this->url('studentachievement') ?>">Add Achievement</a></li>
					<li><a href="<?php echo $this->url('viewachievement') ?>">View Achievement</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Student Participation<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('stdparticipationcategory') ?>">Add Category</a></li>
					<li><a href="<?php echo $this->url('stdparticipation') ?>">Add Participation Record</a></li>
					<li><a href="<?php echo $this->url('viewstdparticipation') ?>">View Participation Record</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Contribution<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('stdcontributioncategory') ?>">Add Category</a></li>
					<li><a href="<?php echo $this->url('stdcontribution') ?>">Add Contribution</a></li>
					<li><a href="<?php echo $this->url('viewstdcontribution') ?>">View Contribition</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Medical Record<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('stdmedicalrecord') ?>">Add Medical Record</a></li>
					<li><a href="<?php echo $this->url('viewstdmedicalrecord') ?>">View Medical Record</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Leave Management<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('stdleavecategory') ?>">Leave Category</a></li>
					<li><a href="<?php echo $this->url('stdleaveapproval') ?>">Leave Approval</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Student Suggestion<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('suggestioncommittee') ?>">Suggestion Committee</a></li>
					<li><a href="<?php echo $this->url('stdsuggestioncategory') ?>">Suggestion Category</a></li>
					<li><a href="<?php echo $this->url('viewstdsuggestions') ?>">View Suggestion</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Clubs and Units<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('addclub') ?>">Add Club</a></li>
					<li><a href="<?php echo $this->url('clubmembershipstatus') ?>">Club Membership Status</a></li>
					<li><a href="<?php echo $this->url('clubmembers') ?>">Club Members</a></li>
					<li><a href="<?php echo $this->url('viewclubsattendance') ?>">View Clubs Attendance</a></li>
					<li><a href="<?php echo $this->url('editclubsattendance') ?>">Update Clubs Attendance</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Student Reports<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('studentreports') ?>">Other Related Reports</a></li>
					<li><a href="<?php echo $this->url('studentfeedbackreports') ?>">Feedbacks Report</a></li>
			</ul>
			</li>
			<li><a href="<?php echo $this->url('studentlists') ?>">Student Lists</a></li>
		</ul>
	</li>
	<li><a><i class="fa fa-database"></i>Property and Inventory<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>Goods Requisition<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('apply-goods-requisition') ?>">Apply Requisition</a></li>
					<li><a href="<?php echo $this->url('view-requisition') ?>">Requisition List</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Goods Transaction<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('emp-goods-list') ?>">My Goods List</a></li>
			</ul>
			</li>
		</ul>
	</li>
	<li><a><i class="fa fa-graduation-cap"></i>Research Management<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>Research Grants<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('applyuniversitygrant') ?>">Apply for University Grants</a></li>
					<li><a href="<?php echo $this->url('applycollegegrant') ?>">Apply for College Grants</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Research Publication<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('applypublication') ?>">Apply for Research Publication</a></li>
			</ul>
			</li>
		</ul>
	</li>
</ul>
</div>
</div>
