<?php
 $title = 'HR Other Configuration Settings';
 $this->headTitle($title);

   $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));
    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <?php if($this->message == NULL && $this->flashMessenger()->hasMessages()) {
							echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
							echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
							$messages = $this->flashMessenger()->getMessages();
							foreach($messages as $message) {
								echo '<strong>Success!</strong>'. $message;
							}
							echo '</div>';
                    	} else if($this->message =='Failure' && $this->flashMessenger()->hasMessages()) {
                            echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                            echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                            $messages = $this->flashMessenger()->getMessages();
                            foreach($messages as $message) {
                                echo '<strong>Warning!</strong>'. $message;
                            }
                            echo '</div>';
                     }  ?>
                <div class="x_content">
                  <br />
                   <div class="" role="tabpanel" data-example-id="togglable-tabs">
                    <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                      <li role="presentation" class="active"><a href="#tab_content1" id="profile-tab" role="tab" data-toggle="tab" aria-expanded="true">Award Category</a>
                      </li>
                      <li role="presentation" class=""><a href="#tab_content2" id="profile-tab" role="tab" data-toggle="tab" aria-expanded="false">Community Service Category</a>
                      </li>
                      <li role="presentation" class=""><a href="#tab_content3" id="profile-tab" role="tab" data-toggle="tab" aria-expanded="false">Contribution Category</a>
                      </li>
                      <li role="presentation" class=""><a href="#tab_content4" id="profile-tab" role="tab" data-toggle="tab" aria-expanded="false">Responsibility Category</a>
                      </li>
                    </ul>
                    <div id="myTabContent" class="tab-content">
                      <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="profile-tab">
                       <br/> 
                       <p> 
                       <div class="x_panel"> 
                         <h2>Award Category</h2>   
                        <div class="x_content">
                  <br />
                   
                <?php
                   // Opening of the form tag
                    $awardCategoryForm->setAttribute('action', $this->url('addempawardcategory', array('action' => 'addEmpAwardCategory')));
					          $awardCategoryForm->prepare();
                    echo $this->form()->openTag($awardCategoryForm);
				            $award = $awardCategoryForm->get('awardcategory');
                    $award->get('organisation_id')->setValue($this->organisation_id);
                    echo $this->formHidden($award->get('organisation_id'));
                    echo $this->formHidden($award->get('id'));   
                ?>
                <div class="row">    
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Award Category: <span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($award->get('award_category')); ?>
                    </div>
                  </div>
                </div>
                <div class="row">    
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Remarks: </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($award->get('remarks')); ?>
                    </div>
                  </div>
                </div>
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                        <?php 
						   echo $this->formHidden($awardCategoryForm->get('csrf'));
						   echo $this->formSubmit($award->get('submit')); 
						?>
                        </div>
                    </div>
                </div>
                    
				<?php echo $this->form()->closeTag(); ?>
                    
                </div>
                </div> 
                
				<div class="x_panel">
                <div class="x_content">
                     <div class="table-responsive">
                      <table id="example-datatable" class="table table-striped responsive-utilities jambo_table bulk_action table-bordered" cellspacing="0" width="100%">
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Sl No </th>
                            <th class="column-title">Award Category </th>
                            <th class="column-title">Action</th>
                          </tr>
                        </thead>  
                        <tbody>
                        <?php $i=1; foreach ($this->award_category as $category): ?>
						            <tr class="even pointer">
                          <td class=" "><?php echo $i++; ?></td>
            							<td class=" "><?php echo $this->escapeHtml($category['award_category']);?></td>
                          <td class=" "><a href="<?php echo $this->url('editempawardcategory', array('id' => my_encrypt($category['id'], $key)));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit</a></td>
						            </tr>
                        <?php endforeach; ?>
                        </tbody>
                      </table>
                     </div>
					</div>
				</div>
			</div> 
                    
            <div role="tabpane2" class="tab-pane fade " id="tab_content2" aria-labelledby="profile-tab">
               <br/> 
                <p>  
                <div class="x_panel"> 
                <h2>Community Service Category</h2>   
                <div class="x_content">
                <br />
                   
                <?php
                   // Opening of the form tag
                    $csCategoryForm->setAttribute('action', $this->url('communityservicecategory', array('action' => 'addEmpCommunityServiceCategory')));
					$csCategoryForm->prepare();
                    echo $this->form()->openTag($csCategoryForm);
				    $communityservice = $csCategoryForm->get('communityservicecategory');
            $communityservice->get('organisation_id')->setValue($this->organisation_id);
                    echo $this->formHidden($communityservice->get('organisation_id'));
                    echo $this->formHidden($communityservice->get('id'));   
                ?>
                  
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Community Service Category: <span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($communityservice->get('community_service_category')); ?>
                    </div>
                </div>
                </div> 
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Remarks: </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($communityservice->get('remarks')); ?>
                    </div>
                </div>
                </div>
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                        <?php 
						   echo $this->formHidden($csCategoryForm->get('csrf'));
						   echo $this->formSubmit($communityservice->get('submit')); 
						?>
                        </div>
                    </div>
                </div>
                    
				<?php  echo $this->form()->closeTag(); ?>
                    
                </div>
                </div> 
                    
              
                <div class="x_panel">
                <div class="x_content">
                     <div class="table-responsive">
                      <table id="datatable" class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Sl No </th>
                            <th class="column-title">Community Service Category </th>
                            <th class="column-title">Action</th>
                          </tr>
                        </thead>  
                        <tbody>
                          <?php $i=1; foreach ($this->cs_category as $category): ?>
                        <tr class="even pointer">
                          <td class=" "><?php echo $i++; ?></td>
                          <td class=" "><?php echo $this->escapeHtml($category['community_service_category']);?></td>
                          <td class=" "><a href="<?php echo $this->url('editcommunityservicecategory', array('id' => my_encrypt($category['id'], $key)));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit</a></td>
                        </tr>
                        <?php endforeach; ?>
                      	
						</tbody>
                      </table>
                     </div>
					</div>
				  </div>
				</div>
                
                <div role="tabpane3" class="tab-pane fade " id="tab_content3" aria-labelledby="profile-tab">
               <br/> 
                <p>  
                <div class="x_panel"> 
                <h2>Contribution Category</h2>   
                <div class="x_content">
                <br />
                   
                <?php
                   // Opening of the form tag
                    $contributionCategoryForm->setAttribute('action', $this->url('addempcontributioncategory', array('action' => 'addEmpContributionCategory')));
					$contributionCategoryForm->prepare();
                    echo $this->form()->openTag($contributionCategoryForm);
				    $contribution = $contributionCategoryForm->get('contributioncategory');
            $contribution->get('organisation_id')->setValue($this->organisation_id);
                    echo $this->formHidden($contribution->get('organisation_id'));
                    echo $this->formHidden($contribution->get('id'));   
                ?>
                  
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Contribution Category: <span class="required">*</span>
                    </label>
                    <div class="col-md-5 col-sm-5 col-xs-12">
                      <?php  echo $this->formRow($contribution->get('contribution_category')); ?>
                    </div>
                </div>
                </div> 
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Remarks:</label>
                    <div class="col-md-5 col-sm-5 col-xs-12">
                      <?php  echo $this->formRow($contribution->get('remarks')); ?>
                    </div>
                </div>
                </div>
                       
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                        <?php 
						   echo $this->formHidden($contributionCategoryForm->get('csrf'));
						   echo $this->formSubmit($contribution->get('submit')); 
						?>
                        </div>
                    </div>
                </div>
                    
				<?php  echo $this->form()->closeTag(); ?>
                    
                </div>
                </div> 
                <!-- End of tabs-->        
                <div class="x_panel">
                <div class="x_content">
                     <div class="table-responsive">
                      <table id="datatable" class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Sl No </th>
                            <th class="column-title">Contribution Category </th>
                            <th class="column-title">Action</th>
                          </tr>
                        </thead>  
                        <tbody>
                          <?php $i=1; foreach ($this->contribution_category as $category): ?>
                        <tr class="even pointer">
                          <td class=" "><?php echo $i++; ?></td>
                          <td class=" "><?php echo $this->escapeHtml($category['contribution_category']);?></td>
                          <td class=" "><a href="<?php echo $this->url('editempcontributioncategory', array('id' => my_encrypt($category['id'], $key)));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit</a></td>
                        </tr>
                        <?php endforeach; ?>
                      	
						</tbody>
                      </table>
                     </div>
					</div>
				  </div>
				</div>

         <div role="tabpane4" class="tab-pane fade " id="tab_content4" aria-labelledby="profile-tab">
               <br/> 
                <p>  
                <div class="x_panel"> 
                <h2>Responsibility Category</h2>   
                <div class="x_content">
                <br />
                   
                <?php
                   // Opening of the form tag
                    $responsibilityCategoryForm->setAttribute('action', $this->url('addempresponsibilitycategory', array('action' => 'addEmpResponsibilityCategory')));
          $responsibilityCategoryForm->prepare();
                    echo $this->form()->openTag($responsibilityCategoryForm);
            $responsibility = $responsibilityCategoryForm->get('responsibilitycategory');
            $responsibility->get('organisation_id')->setValue($this->organisation_id);
                    echo $this->formHidden($responsibility->get('organisation_id'));
                    echo $this->formHidden($responsibility->get('id'));   
                ?>
                  
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Responsibility Category: <span class="required">*</span>
                    </label>
                    <div class="col-md-5 col-sm-5 col-xs-12">
                      <?php  echo $this->formRow($responsibility->get('responsibility_category')); ?>
                    </div>
                </div>
                </div> 
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Remarks:</label>
                    <div class="col-md-5 col-sm-5 col-xs-12">
                      <?php  echo $this->formRow($responsibility->get('remarks')); ?>
                    </div>
                </div>
                </div>
                       
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                        <?php 
               echo $this->formHidden($responsibilityCategoryForm->get('csrf'));
               echo $this->formSubmit($responsibility->get('submit')); 
            ?>
                        </div>
                    </div>
                </div>
                    
        <?php  echo $this->form()->closeTag(); ?>
                    
                </div>
                </div> 
                <!-- End of tabs-->        
                <div class="x_panel">
                <div class="x_content">
                     <div class="table-responsive">
                      <table id="datatable" class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Sl No </th>
                            <th class="column-title">Responsibility Category </th>
                            <th class="column-title">Action</th>
                          </tr>
                        </thead>  
                        <tbody>
                          <?php $i=1; foreach ($this->responsibility_category as $category): ?>
                        <tr class="even pointer">
                          <td class=" "><?php echo $i++; ?></td>
                          <td class=" "><?php echo $this->escapeHtml($category['responsibility_category']);?></td>
                          <td class=" "><a href="<?php echo $this->url('editempresponsibilitycategory', array('id' => my_encrypt($category['id'], $key)));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit</a></td>
                        </tr>
                        <?php endforeach; ?>
                        
            </tbody>
                      </table>
                     </div>
          </div>
          </div>
        </div>

   		 </div>
 		</div>
	</div>
</div>
</div>
</div>
</div>
</div>
</div>
            
