<?php
 $title = 'COUNSELING APPOINTMENT';
 $this->headTitle($title);

 $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    //IDEA-CBC
    //Original
    //$iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('aes-256-cbc'));

    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));

    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title)?></h2>
                 <div class="clearfix"></div>
                </div>
                 <?php 
                            if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                                echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                $messages = $this->flashMessenger()->getMessages();
                                foreach($messages as $message) {
                                    echo '<strong>Success!</strong>'. $message;
                                }
                                echo '</div>';
                            }

                            else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                                echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                $messages = $this->flashMessenger()->getMessages();
                                foreach($messages as $message) {
                                    echo '<strong>Failure!</strong>'. $message;
                                }
                                echo '</div>';
                            }
                        ?>
                
                <div class="x_content">
                   <?php
                   $form->prepare();
                   echo $this->form()->openTag($form);
				           $counsel = $form->get('counselingappointment');
                   if($usertype == 1){
                    $counsel->get('applicant_id')->setValue($this->employee_details_id);
                   }
                   else if($usertype == 2){
                    $counsel->get('applicant_id')->setValue($this->student_id);
                   }
        				   
        				   $counsel->get('organisation_id')->setValue($this->organisation_id);
                   $counsel->get('applicant_type')->setValue($this->usertype);
                   $counsel->get('consent_detail')->setValue("
                   1. Will cooperate with the counsellor in being sincere and honest in sharing the problems and issues I am facing so that it helps the counsellor to think of appropriate therapeutic interventions;
                   2. Any information that I share with my counsellor shall be treated with respect and confidentiality;
                   3. Availing the services on my own free will considering or understanding the potential benefits of counselling;
                   4. Give permission to the counsellor to share my information to any relevant agencies/individuals in the event of a possible threat or serious harm to self or others;
                   5. I have the right to decline or terminate the service at any given point of time at my own free will that I deem most appropriate.");
                   $counsel->get('counselor_id')->setValueOptions($this->selectCounselor);
        				   $counsel->get('appointment_status')->setValue('Pending');
                   $counsel->get('applied_date')->setValue(date('Y-m-d'));
                   echo $this->formHidden($counsel->get('id'));
        				   echo $this->formHidden($counsel->get('applicant_id'));
                   echo $this->formHidden($counsel->get('applicant_type'));
                   echo $this->formHidden($counsel->get('consent_detail'));
        				   echo $this->formHidden($counsel->get('organisation_id'));
        				   echo $this->formHidden($counsel->get('appointment_status'));
                   echo $this->formHidden($counsel->get('applied_date'));
                ?>
                <h2 class="StepTitle">Consent for Seeking Counselling</h2>
                  With my decision to seek an appointment for counselling and seek help to discuss the issues I am currently facing, I declare and give my consent for the following:<br/><br/>
                  <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-1 col-sm-1 col-xs-12"></label>
                      <div class="col-md-11 col-sm-11 col-xs-12">
                          <?php echo '1. Will cooperate with the counsellor in being sincere and honest in sharing the problems and issues I am facing so that it helps the counsellor to think of appropriate therapeutic interventions; '; ?>
                        </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-1 col-sm-1 col-xs-12"></label>
                      <div class="col-md-11 col-sm-11 col-xs-12">
                          <?php echo '2. Any information that I share with my counsellor shall be treated with respect and confidentiality;'; ?>
                        </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-1 col-sm-1 col-xs-12"></label>
                      <div class="col-md-11 col-sm-11 col-xs-12">
                          <?php echo '3. Availing the services on my own free will considering or understanding the potential benefits of counselling; '; ?>
                        </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-1 col-sm-1 col-xs-12"></label>
                      <div class="col-md-11 col-sm-11 col-xs-12">
                          <?php echo '4. Give permission to the counsellor to share my information to any relevant agencies/individuals in the event of a possible threat or serious harm to self or others;'; ?>
                        </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-1 col-sm-1 col-xs-12"></label>
                      <div class="col-md-11 col-sm-11 col-xs-12">
                          <?php echo '5. I have the right to decline or terminate the service at any given point of time at my own free will that I deem most appropriate.'; ?>
                        </div>
                    </div>
                  </div>
		<div class="row">
                    <div class="form-group">  
			<label class="control-label col-md-6 col-sm-6 col-xs-12"><input type="checkbox" class="flat" required="required"> I hereby agree to the terms and conditions stated above:<span class="required">*</span></label>
			<div class="col-md-3 col-sm-2 col-xs-12">
                          
                        </div>
                        
                    </div>
                  </div>
                  <br/><br/>
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">To: <span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($counsel->get('counselor_id')); ?>
                    </div>
                </div>
                </div> 
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Subject: <span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($counsel->get('subject')); ?>
                    </div>
                </div>
                </div>
                <div class="row" >
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Reasons:<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($counsel->get('description')); ?>
                    </div>
                </div> 
                </div>
                <div class="row" >
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Appointment Time:<br /><small>(e.g. 04:30 PM)</small> <span class="required">*</span></label>
                    <div class="col-md-2 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($counsel->get('appointment_time')); ?>
                    </div>
                    <label class="control-label col-md-2 col-sm-3 col-xs-12">Appointment Date:<span class="required">*</span></label>
                    <div class="col-md-2 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($counsel->get('appointment_date')); ?>
                    </div>
                </div> 
                </div>
                <div class="row" >
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Other Preferable Time:<br /><i><small>(Please suggest other times that would 
                    		be preferable if the suggested appointment time and date are not available)</small></i></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($counsel->get('remarks')); ?>
                    </div>
                </div> 
                </div>
           
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-2 col-xs-12"></label>
                        <div class="col-md-3 col-sm-3 col-xs-12">
                   		<?php 
        						  echo $this->formHidden($form->get('csrf'));
        						  echo $this->formSubmit($counsel->get('submit')); 
                      echo $this->form()->closeTag();
        						?>
                    	</div>
                    </div>
                </div>
                       
                </div>
              </div>
              <?php 
               $title = 'Counseling Appointment Application List';
               $this->headTitle($title);
              ?>
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title)?></h2>
                 <div class="clearfix"></div>
                  <h5><i>***Following are the lists of counseling appointment application. You can edit before counselor approve it. Once counselor approve your counseling appointment then you can't edit it.</i></h5>
                </div>
                <div class="x_content">
                  <div class="table-responsive">
                      <table class="table table-striped jambo_table bulk_action"> 
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Sl. No</th>
                            <th class="column-title">Counselor</th>
                            <th class="column-title">Subject</th>
                            <th class="column-title">Description</th>
                            <th class="column-title">Applied Date</th>
                            <th class="column-title">Status</th>
                            <th class="column-title no-link last"><span class="nobr">Action</span></th>
                          </tr>
                        </thead>
                        <tbody>
                          <?php $i=1; foreach($this->indcounselingapplication as $list): ?>
                          <tr>
                            <td><?php echo $i++; ?></td>
                            <td><?php echo $list['first_name'].' '.$list['middle_name'].' '.$list['last_name']; ?></td>
                            <td><?php echo $list['subject']; ?></td>
                            <td><?php echo $list['description']; ?></td>
                            <td><?php echo $list['applied_date']; ?></td>
                            <td><?php echo $list['appointment_status']; ?></td>
                            <td><?php if($list['appointment_status'] == 'Pending'){?>
                               <a href="<?php echo $this->url('editcounselingappointment', array('id' => my_encrypt($list['id'], $key))); ?>" class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i> Edit </a>
                            <?php } else if($list['appointment_status'] == 'Granted'){?>
                               <a href="<?php echo $this->url('viewindcounselingappointment', array('id' => my_encrypt($list['id'], $key))); ?>" class="btn btn-primary btn-xs"><i class="fa fa-eye"></i> View </a>
                            <?php } ?>
                              </td>
                          </tr>
                          <?php endforeach; ?>
                        </tbody>
                      </table>
                    </div>
                </div>
              </div>

            </div>
       </div>       
 	</div> 
              
              
              
              
              
              
              
              
              
              
              
    