<?php
 $title = 'Edit Club Advisor & Coordinator';
 $this->headTitle($title);

  $clubdetails = array();
 foreach($this->clubDetails as $details){
  $clubdetails = $details;
 }
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2>Add Club, Advisor & Coordinator</h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				            $clubs = $form->get('clubs');
          					$data = $this->selectData;
          					$clubs->get('id')->setValue($clubdetails['id']);
          					$clubs->get('club_name')->setValue($clubdetails['club_name']);
          					$clubs->get('maximum_members')->setValue($clubdetails['maximum_members']);
          					$clubs->get('advisor_name')->setValue($clubdetails['advisor_name']);
          					$clubs->get('coordinator_name')->setValue($clubdetails['coordinator_name']);
          					$clubs->get('description')->setValue($clubdetails['description']);
          					$clubs->get('organisation_id')->setValue($clubdetails['organisation_id']);
                    echo $this->formHidden($clubs->get('id')); 
          					echo $this->formHidden($clubs->get('organisation_id')); 
          				  ?>
                <?php if($this->message == 'Success'){?>
                <div class="alert alert-success alert-dismissible fade in" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                    <strong>Success!</strong> Club was successfully edited.
                </div>
                <?php } else if($this->message !='Success' && $this->message != NULL) {?>
                <div class="alert alert-danger alert-dismissible fade in" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                    <strong>Failure!</strong> <?php echo $this->message; ?>
                </div>
                <?php } ?>
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Club: <span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($clubs->get('club_name')); ?>
                    </div>
                </div>
                </div> 
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Maximum Members: <span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($clubs->get('maximum_members')); ?>
                    </div>
                </div>
                </div> 
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Advisor Name: <span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($clubs->get('advisor_name')); ?>
                    </div>
                </div>
                </div> 
                  
                   <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Coordinator Name: <span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($clubs->get('coordinator_name')); ?>
                    </div>
                </div>
                </div>
                
                <div class="row" >
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Description:<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($clubs->get('description')); ?>
                    </div>
                </div> 
                </div>
               
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12"></label>
                              <div class="col-md-3 col-sm-3 col-xs-12">
                    <?php
                        echo $this->formHidden($form->get('csrf'));
						echo $this->formSubmit($clubs->get('submit')); 
						echo $this->form()->closeTag();
                      ?>
                    </div>
                   </div>
                </div>
                       
                </div>
              </div>
            </div>
              
              
               <?php
               $title = 'Club, Advisor & Coordinator';
               $this->headTitle($title);
              ?>
               <div class="col-md-12 col-xs-12">
                  
                  <div class="x_panel">
                      <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                  </div>
                
                    <div class="x_content">
                        <div class="table-responsive">
                      <table class="table table-striped jambo_table bulk_action"> 
                         <div class="form-group">      
                      </div> 
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Sl. No</th>
                            <th class="column-title">Club Name </th>
                            <th class="column-title">Advisor Name</th>
                            <th class="column-title">Co-Ordinator Name</th>
                            <th class="column-title">Description</th>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <?php $i=1; foreach ($this->clubs as $club) : ?>
                          <tr class="even pointer">
                            <td class=" "><?php echo $i++;?></td>
                            <td class=" "><?php echo $this->escapeHtml($club['club_name']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($club['advisor_name']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($club['coordinator_name']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($club['description']);?></td>
                          </tr>
                          <?php endforeach; ?>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                    </div>
                
                </div>
              </div>
            </div>
          </div>
             