

<?php
 // module/EmployeeDetail/view/employee-detail/employee-detail/emppersonaldetail.phtml:

 $title = 'Allocate Hostel Room';
 $this->headTitle($title);
 ?>
 <div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
                  <div class="" role="tabpanel" data-example-id="togglable-tabs">
                      <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                          <li role="presentation" class="active"><a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">Allocate Hostel Room</a>
                        </li>
                        <li role="presentation" class=""><a href="#tab_content2" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false">Allocated List</a>
                        </li>
                      </ul>
                      <div id="myTabContent" class="tab-content">
                  <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab"> 
                      <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    
                  <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    
                  <div class="clearfix"></div>
                  </div>
              
                  <div class="x_content"><br/>
                      
                      <?php
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        
                        echo $this->formHidden($form->get('id'));
                        ?>
                      
                    
                  <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Hostel Type<span class="required">*</span>
                        </label>
                              <div class="col-md-4 col-sm-4 col-xs-12">
                        <?php
                        echo $this->formRow($form->get('hostel_type'));
                        ?>
                          </div>
                      <label class="control-label col-md-2 col-sm-2 col-xs-12">Hostel Category<span class="required">*</span>
                        </label>
                              <div class="col-md-4 col-sm-4 col-xs-12">
                        <?php
                        echo $this->formRow($form->get('hostel_category'));
                        ?>
                          </div>
                        </div>  
                      
                      <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Hostel Name<span class="required">*</span>
                        </label>
                              <div class="col-md-4 col-sm-4 col-xs-12">
                        <?php
                        echo $this->formRow($form->get('hostel_name'));
                        ?>
                          </div>
                      <label class="control-label col-md-2 col-sm-2 col-xs-12">Room No<span class="required">*</span>
                        </label>
                              <div class="col-md-4 col-sm-4 col-xs-12">
                        <?php
                        echo $this->formRow($form->get('hostel_room_no'));
                        ?>
                          </div>
                        </div>  
                      
                      <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Course<span class="required">*</span>
                        </label>
                              <div class="col-md-4 col-sm-4 col-xs-12">
                        <?php
                        echo $this->formRow($form->get('std_course'));
                        ?>
                          </div>
                      <label class="control-label col-md-2 col-sm-2 col-xs-12">Semester<span class="required">*</span>
                        </label>
                              <div class="col-md-4 col-sm-4 col-xs-12">
                        <?php
                        echo $this->formRow($form->get('std_semester'));
                        ?>
                          </div>
                        </div>  
                      
                      <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Hostel Allocation Date<span class="required">*</span>
                        </label>
                              <div class="col-md-4 col-sm-4 col-xs-12">
                        <?php
                        echo $this->formRow($form->get('hostel_allocate_date'));
                        ?>
                          </div>
                        </div>  
                    
                      <div class="ln_solid"></div>
                      <div class="form-group">
                          <div class="col-md-12 col-sm-12 col-xs-12">
                            <?php 
                            echo $this->formSubmit($form->get('submit'));
                            ?>
                          
                        </div>
                      </div>
                      
                       <?php
                    echo $this->form()->closeTag();
                    ?>
                  </div>
                </div></div>
                  
</div>
                          <div role="tabpanel" class="tab-pane fade" id="tab_content2" aria-labelledby="profile-tab">
                              <?php 
                                                  include "allocatedhostel.phtml"
                              ?>
                          </div>
                  
                      </div></div></div></div></div>
            
         
              
       
                