<?php
 $title = 'Add Employee';
 $this->headTitle($title);
 ?>
  <div class="right_col" role="main">
          <div class="">
              <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                     <!-- Smart Wizard -->
                    <div id="wizard" class="form_wizard wizard_horizontal">
                      <ul class="wizard_steps">
                          <li>
                          <a class="done">
                            <span class="step_no">1</span>
                            <span class="step_descr">
                                      Step 1<br />
                                      <small>PERSONAL<br/>DETAILS</small>
                                  </span>
                          </a>
                        </li>
                        <li>
                          <a class="done">
                            <span class="step_no">2</span>
                            <span class="step_descr">
                                      Step 2<br />
                                      <small>RELATION<br/>DETAILS</small>
                                  </span>
                          </a>
                        </li>
                        <li>
                          <a class="done">
                            <span class="step_no">3</span>
                            <span class="step_descr">
                                      Step 3<br />
                                      <small>EDUCATION<br/>DETAILS</small>
                                  </span>
                          </a>
                        </li>
                        <li>
                          <a class="done">
                            <span class="step_no">4</span>
                            <span class="step_descr">
                                      Step 4<br />
                                      <small>TRAINING<br/>DETAILS</small>
                                  </span>
                          </a>
                        </li>
                        <li>
                          <a class="done">
                            <span class="step_no">5</span>
                            <span class="step_descr">
                                      Step 5<br />
                                      <small>WORK<br/>DETAILS</small>
                                  </span>
                          </a>
                        </li>
                        <li>
                          <a class="done">
                            <span class="step_no">6</span>
                            <span class="step_descr">
                                      Step 6<br />
                                      <small>RESEARCH<br/>DETAILS</small>
                                  </span>
                          </a>
                        </li>
                        <li>
                          <a class="done">
                            <span class="step_no">7</span>
                            <span class="step_descr">
                                      Step 7<br />
                                      <small>DOCUMENT</small> <br/>
                                      <small>UPLOAD</small>
                                  </span>
                          </a>
                        </li>
                      </ul>
                      <?php
						// Opening of the form tag
						$form->prepare();
						echo $this->form()->openTag($form);
						$employee = $form->get('employeedocuments');
						$employee->get('employee_details_id')->setValue($this->employee_details_id);
						echo $this->formHidden($employee->get('id'));
						echo $this->formHidden($employee->get('employee_details_id'));
					 ?> 
                    <br />
                  <div class="row">
                    <div class="form-group">  
                       <label class="control-label col-md-4 col-sm-3 col-xs-12">Passport Size Photo</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <?php echo $this->formRow($employee->get('passport_photo')); ?>
                        </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group">  
                       <label class="control-label col-md-4 col-sm-3 col-xs-12">Upload CID/Work Permit</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <?php echo $this->formRow($employee->get('identity_proof')); ?>
                        </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group">  
                       <label class="control-label col-md-4 col-sm-3 col-xs-12">Upload Security Clearance</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <?php echo $this->formRow($employee->get('security_clearance_file')); ?>
                        </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group">  
                       <label class="control-label col-md-4 col-sm-3 col-xs-12">Upload Aduit Clearance</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <?php echo $this->formRow($employee->get('medical_clearance_file')); ?>
                        </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group">  
                       <label class="control-label col-md-4 col-sm-3 col-xs-12">Upload Certificate</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <?php echo $this->formRow($employee->get('other_certificate_file')); ?>
                        </div>
                    </div>
                  </div>    
                    
                
          		<div class="ln_solid"></div>
                      <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                          <?php  
                            echo $this->formHidden($form->get('csrf'));
                            echo $this->formRow($employee->get('submit')); 
							echo $this->form()->closeTag($form);
						 ?>
                        </div>
                      </div>

       			</div> <!-- End of x_content-->
        	  </div> <!-- End of x_panel-->
   			</div> 
        </div>
      </div>
   </div>
 </div>
