<?php
 $title = 'Assessment of Various Modules';
 $this->headTitle($title);

  $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    //IDEA-CBC
    //Original
    //$iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('aes-256-cbc'));

    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));

    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}
?>

 <div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
            
                <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                     <div class="clearfix"></div>
                    </div>
                    <br/>
                     <br/>
                    <!-- Start of Tab-->
                    <div class="" role="tabpanel" data-example-id="togglable-tabs">
                      <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                        <li role="presentation" class="active"><a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">Assessment</a>
                        </li>
                        <li role="presentation" class=""><a href="#tab_content3" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false">Assessment Component Type</a>
                        </li>
                      </ul>
                      <div id="myTabContent" class="tab-content">
                        <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab">
                            <br/>
                                <!-- Adding Assessment-->
                                <?php if($this->message == NULL && $this->flashMessenger()->hasMessages()) {
										echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
										echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
										$messages = $this->flashMessenger()->getMessages();
										foreach($messages as $message) {
											echo '<strong>Success!</strong>'. $message;
										}
										echo '</div>';
									} else if($this->message =='Failure' && $this->flashMessenger()->hasMessages()) {
										echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
										echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
										$messages = $this->flashMessenger()->getMessages();
										foreach($messages as $message) {
											echo '<strong>Warning!</strong>'. $message;
										}
										echo '</div>';
								 } ?>
                                <div class="col-md-12 col-xs-12">
                                  <div class="x_panel">
                                    <div class="x_title">
                                      <h2><?php echo $this->escapeHtml("Add Assessment")?></h2>
                                        <ul class="nav navbar-right panel_toolbox">
                                          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                          </li>
                                    
                                        </ul>
                                     <div class="clearfix"></div>
                                  
                                    </div>
                                       
                                    <div class="x_content">
                                      <br />
                                       <?php
                                        // Opening of the form tag
											$componentForm->prepare();
											echo $this->form()->openTag($componentForm);
											$assessment = $componentForm->get('assessmentcomponent');
											$assessment->get('programmes_id')->setValueOptions($this->programmeList);
											$assessment->get('assessment')->setValueOptions($this->assessmentComponentTypeList);
											echo $this->formHidden($assessment->get('id'));
                                      ?>
                                      <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Programme Name:<span class="required">*</span></label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                          <?php  echo $this->formRow($assessment->get('programmes_id')); ?>
                                        </div>
                                      </div>
                                      <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Assessment Type:<span class="required">*</span></label>
                                        <div class="col-md-3 col-sm-6 col-xs-12">
                                          <?php  echo $this->formRow($assessment->get('assessment')); ?>
                                        </div>
                                        <label class="control-label col-md-2 col-sm-3 col-xs-12">Weightage:<span class="required">*</span></label>
                                        <div class="col-md-1 col-sm-6 col-xs-12">
                                          <?php  echo $this->formRow($assessment->get('weightage')); ?>
                                        </div>
                                      </div>
                                      <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Remarks<span class="required">*</span></label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                          <?php  echo $this->formRow($assessment->get('remarks')); ?>
                                        </div>
                                      </div>
                                     
                                     <div class="row">
                                        <div class="ln_solid"></div>
                                        <div class="form-group">
                                            <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                                              <?php
                                               echo $this->formHidden($componentForm->get('csrf'));
                                               echo $this->formSubmit($assessment->get('submit')); 
                                               echo $this->form()->closeTag(); 
                                            ?>
                                        </div>
                                    </div>
                                      
                                  </div>
                                </div>
                               </div>   
                                      
                                  
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                  <div class="x_panel">
                                    <div class="x_title">
                                      <h2><?php echo $this->escapeHtml("Assessment"); ?></h2>
                                      <ul class="nav navbar-right panel_toolbox">
                                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                        </li>
                                      </ul>
                                      <div class="clearfix"></div>
                                    </div>
                    
                                    <div class="x_content">
                                      <table id="datatable-buttons" class="table table-striped jambo_table table-bordered">
                                        <thead>
                                          <tr class="headings">
                                            </th>
                                             <th class="column-title">Sl.No.</th>
                                             <th class="column-title">Programme Name</th>
                                             <th class="column-title">Module Name</th>
                                             <th class="column-title">Module Code</th>
                                             <th class="column-title">Assessment Type</th>
                                             <th class="column-title">Weightage</th>
                                             <th class="column-title">Action</th>
                                          </tr>
                                        </thead>
                    
                                        <tbody>
                                          <?php
                                          $i=1;  foreach($this->componentList as $component): ?>
                                          <tr class="even pointer">
                                            <td class=" "><?php echo $i++;?></td>
                                            <td class=" "><?php echo $component['programme_name']; ?></td>
                                            <td class=" "><?php echo $component['module_title']; ?></td>
                                            <td class=" "><?php echo $component['module_code']; ?></td>
                                            <td class=" "><?php echo $component['assessment']; ?></td>
                                            <td class=" "><?php echo $component['weightage']; ?></td>
                                            <td><a href="<?php echo $this->url('editassessmentcomponent', array('id' => my_encrypt($component['id'], $key)));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a>
                                          </tr>
                                          <?php endforeach; ?>
                                        </tbody>
                                      </table>
                                    </div>
                                  </div>
                                </div>
                            
                           		<!-- End of Assessment-->
                        </div>
                        
                        <div role="tabpanel" class="tab-pane fade" id="tab_content3" aria-labelledby="profile-tab">
                                <br/>
                                <!-- Adding Assessment Component Type-->
                                <div class="col-md-12 col-xs-12">
                                  <div class="x_panel">
                                    <div class="x_title">
                                      <h2><?php echo $this->escapeHtml("Assessment Component Type")?></h2>
                                        <ul class="nav navbar-right panel_toolbox">
                                          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                          </li>
                                    
                                        </ul>
                                     <div class="clearfix"></div>
                                  
                                    </div>
                                       
                                    <div class="x_content">
                                      <br />
                                       <?php
                                        // Opening of the form tag
                    										$typeForm->setAttribute('action', $this->url('addassessmentcomponenttypes', array('action' => 'addAssessmentComponentType')));
                    										$typeForm->prepare();
                    										echo $this->form()->openTag($typeForm);
                    										$assessmentType = $typeForm->get('assessmentcomponent');
                    										$assessmentType->get('organisation_id')->setValue($this->organisation_id);
                    										echo $this->formHidden($assessmentType->get('id'));
                    										echo $this->formHidden($assessmentType->get('organisation_id'));
                                      ?>
                                      <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Assessment Component Type<span class="required">*</span></label>
                                        <div class="col-md-5 col-sm-6 col-xs-12">
                                          <?php  echo $this->formRow($assessmentType->get('assessment_component_type')); ?>
                                        </div>
                                      </div>                                     
                                     <div class="row">
                                        <div class="ln_solid"></div>
                                        <div class="form-group">
                                            <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                                              <?php
                                               echo $this->formHidden($typeForm->get('csrf'));
                                               echo $this->formSubmit($assessmentType->get('submit')); 
                                               echo $this->form()->closeTag(); 
                                            ?>
                                        </div>
                                    </div>
                                      
                                  </div>
                                </div>
                               </div>     
                                      
                                  
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                  <div class="x_panel">
                                    <div class="x_title">
                                      <h2><?php echo $this->escapeHtml("Assessment Component Type"); ?></h2>
                                      <ul class="nav navbar-right panel_toolbox">
                                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                        </li>
                                      </ul>
                                      <div class="clearfix"></div>
                                    </div>
                    
                                    <div class="x_content">
                                      <table class="table   table-striped responsive-utilities jambo_table bulk_action table-bordered">
                                        <thead>
                                          <tr class="headings">
                                            </th>
                                             <th class="column-title">Sl.No.</th>
                                             <th class="column-title">Assessment Component Type</th>
                                             <th class="column-title">Action</th>
                                          </tr>
                                        </thead>
                    
                                        <tbody>
                                          <?php
                                          $i=1;  foreach($this->componentTypeList as $sub): ?>
                                          <tr class="even pointer">
                                            <td class=" "><?php echo $i++;?></td>
                                            <td class=" "><?php echo $sub['assessment_component_type']; ?></td>
                                            <td class=" "><?php  ?></td>
                                          </tr>
                                          <?php endforeach; ?>
                                        </tbody>
                                      </table>
                                    </div>
                                  </div>
                                </div>
                            
                            	<!-- End of Assessment Component Type-->
                        </div>
                      </div>
                    </div>
                    <!-- End of Tabs-->
                     
                     
                  </div>
                </div>
              </div>
     </div>
