<?php
 $title = 'Compile Student Assessment Marks';
 $this->headTitle($title);
?>
<?php
  $compileDateDuration = array();
  foreach($this->compileDate as $detail){
     $compileDateDuration = $detail;
 }
 
 //set it to a default value
 if(empty($compileDateDuration))
    $compileDateDuration['to_date'] = '2000-01-01';
    $compileDateDuration['from_date'] = '2000-01-01';
?>

<div class="right_col" role="main">
  <div class="">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2><?php echo $this->escapeHtml($title); ?></h2>
          <div class="clearfix"></div>
        </div><br/>
        <?php 
        if($this->message == NULL && $this->flashMessenger()->hasMessages()) {
          echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
          echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
          $messages = $this->flashMessenger()->getMessages();
          foreach($messages as $message) {
            echo '<strong>Success!</strong>'. $message;
          }
          echo '</div>';
        } else if($this->message =='Failure' && $this->flashMessenger()->hasMessages()) {
          echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
          echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
          $messages = $this->flashMessenger()->getMessages();
          foreach($messages as $message) {
            echo '<strong>Warning!</strong>'. $message;
          }
          echo '</div>';
        } ?>
        <?php if(strtotime($compileDateDuration['from_date']) <= strtotime(date('Y-m-d')) && strtotime(date('Y-m-d')) <= strtotime($compileDateDuration['to_date'])) { ?>
        <!-- Adding Achievements-->
        <h5><i>*(In order to add the students' mark, search by Module Name. Please note that the search is only done by Module Name. However, both Module Name and Assessment Type has to be selected inorder to enter the marks)</i></h5>
        <br />
        <?php
        // Opening of the form tag
        $form->prepare();
        echo $this->form()->openTag($form);
        $form->get('assessment_type')->setValue(1);
        $form->get('section')->setValueOptions($this->sectionList);
        ?>
        <div class="row">
          <div class="col-md-3 col-sm-12 col-xs-12 form-group">
            <label>Module</label>
            <?php echo $this->formRow($form->get('assessment_component_id')); ?>
          </div>
          <div class="col-md-3 col-sm-12 col-xs-12 form-group">
            <label>Section</label>
            <?php echo $this->formRow($form->get('section')); ?>
          </div>
        </div>
        <div class="row">
          <div class="ln_solid"></div>
          <div class="form-group">
            <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
            <?php
            echo $this->formHidden($form->get('assessment_type'));
            echo $this->formHidden($form->get('csrf'));
            echo $this->formSubmit($form->get('compile')); 
            echo $this->form()->closeTag(); 
            ?>
          </div>
        </div>
        <?php } else { ?>
          <h2 class="StepTitle">Marks compiling date is not yet open. Examination and Student Record Service will notify the date for compiling the marks.</h2>
        <?php } ?>
      </div>
    </div>
  </div>
</div>
              
