<?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Add Alumni Contribution';
 $this->headTitle($title);
?>
<div class="right_col" role="main">
    <div class="">
        <div class="col-md-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                </div><!--end of x-title-->
                <div class="x_content">
                    <?php
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        $contribution = $form->get('alumnicontribution');
                        $contribution->get('organisation_id')->setValue($this->organisation_id);
                        echo $this->formHidden($contribution->get('id')); 
            						echo $this->formHidden($contribution->get('organisation_id'));
                     ?>

                     <?php 
                            if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                                echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                $messages = $this->flashMessenger()->getMessages();
                                foreach($messages as $message) {
                                    echo '<strong>Success!</strong>'. $message;
                                }
                                echo '</div>';
                            }

                            else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                                echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                $messages = $this->flashMessenger()->getMessages();
                                foreach($messages as $message) {
                                    echo '<strong>Failure!</strong>'. $message;
                                }
                                echo '</div>';
                            }
                        ?>
                        <h4><i>Please enter the contribution details with contributor (s) and contributed date.</i></h4><br/>
                            
                            <div class="form-group">
                                <label class="control-label col-md-2 col-sm-2 col-xs-12">Contribution Details:<span class="required">*</span></label>
                                    <div class="col-md-8 col-sm-8 col-xs-12">
                                        <?php  echo $this->formRow($contribution->get('contribution_details')); ?>
                                    </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-2 col-sm-2 col-xs-12"> Contributed By: <span class="required">*</span><br><small>(You can enter more than one contributor)</small></label>
                                        <div class="col-md-3 col-sm-3 col-xs-12">
                                            <?php  echo $this->formRow($contribution->get('contributed_by')); ?>
                                      </div>
                                <label class="control-label col-md-2 col-sm-2 col-xs-12"> Contributed Date:<span class="required">*</span></label>
                                        <div class="col-md-3 col-sm-3 col-xs-12">
                                            <?php  echo $this->formRow($contribution->get('contributed_date')); ?>
                                        </div>
                            </div>

                            <div class="form-group"> 
                                <label class="control-label col-md-2 col-sm-2 col-xs-12">Remarks:</label>
                                    <div class="col-md-8 col-sm-8 col-xs-12">
                                            <?php  echo $this->formRow($contribution->get('remarks')); ?>
                                    </div>
                            </div>
      
                            <div class="ln_solid"></div>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                        <?php 
                                                     echo $this->formHidden($form->get('csrf'));
                                                      echo $this->formSubmit($contribution->get('submit')); ?>
                                        </div>
                                </div>
                        </div>
                            <?php
                                echo $this->form()->closeTag();
                            ?>
                    </div><!--end of x-content-->
                </div><!--end of x-Panel-->
          </div><!--end of col-md-12 col-xs-12-- >
      </div><!--end of ""-->
	  

         
              <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel"> 
                  <div class="x_title">
                    <h2>Alumni Contribution Lists: <small>(Alumni Contribution lists for the year <b><?php echo date('Y'); ?></b>)</small></h2>
                  <div class="clearfix"></div>
                  </div>
            <div class="x_content">
                    <div class="table-responsive">
                      <table id="datatable-responsive" class="table table-striped responsive-utilities jambo_table bulk_action table-bordered"> 
                         <thead>
                          <tr class="headings">
                      <!--  <th>
                          <input type="checkbox" id="check-all" class="flat" disabled>
                        </th>-->                          
                          <th class="column-title">Sl.No. </th>
                          <th class="column-title">Contribution Details</th>
                          <th class="column-title">Contributed By</th>
                          <th class="column-title">Contributed On</th>
                         </tr>
                        </thead>
                           <?php $i=1; ?>
                         <?php foreach ($this->contributions as $contribution) : ?>
                          <tr class="even pointer">
                           <!--  <td class="a-center ">
                              <input type="checkbox" class="flat" name="table_records">
                            </td>-->
                             <td class=" "><?php echo $i; ?></td>
                              <td class=" "><?php echo $contribution['contribution_details'];?></td>
                              <td class=" "><?php echo $contribution['contributed_by'];?></td>
                              <td class=" "><?php echo $contribution['contributed_date'];?></td>
                          </tr>
                           <?php $i++; ?>
                          <?php endforeach; ?>
                          </table>
                    </div>
            </div>
		</div>
	</div>
  </div>
