<?php

 $title = 'Alumni Registration Form';
 $this->headTitle($title);
?>

<div class="right_col" role="main">
    <div class=" ">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                </div><!--end of x-title-->
                 <div class="x_content">   
                    <br/>
                    <?php
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        $register = $form->get('alumninewregistration');
                        $register->get('alumni_programmes_id')->setValueOptions($this->programmeName);
                        $register->get('qualification_level_id')->setValueOptions($this->qualificationLevel);
                        $register->get('gender')->setValueOptions($this->gender);
                        $register->get('enrollment_year')->setValueOptions($this->enrollmentYear);
                        $register->get('graduation_year')->setValueOptions($this->graduationYear);
                        echo $this->formHidden($register->get('id'));
                        $register->get('organisation_id')->setValue($this->organisation_id);
						echo $this->formHidden($register->get('organisation_id'));
                       // $register ->get('alumni_status')->setValue('Active');
                        //echo $this->formHidden($register->get('alumni_status'));	
						                          
                     ?>

                     <?php 
                            if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                                echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                $messages = $this->flashMessenger()->getMessages();
                                foreach($messages as $message) {
                                    echo '<strong>Success!</strong>'. $message;
                                }
                                echo '</div>';
                            }

                            else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                                echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                $messages = $this->flashMessenger()->getMessages();
                                foreach($messages as $message) {
                                    echo '<strong>Failure!</strong>'. $message;
                                }
                                echo '</div>';
                            }
                        ?>

                     <p><b><i>NOTE: Field (s) with * mark is mandatory to fill up:</i></b></p>
                            <div class="form-group">
                                <label class="control-label col-md-2 col-sm-2 col-xs-12">First Name:<span class="required">*</span></label>
                                    <div class="col-md-3 col-sm-3 col-xs-12">
                                        <?php  echo $this->formRow($register->get('first_name')); ?>
                                    </div>
                                <label class="control-label col-md-2 col-sm-2 col-xs-12">Middle Name:</label>
                                    <div class="col-md-3 col-sm-3 col-xs-12">
                                        <?php  echo $this->formRow($register->get('middle_name')); ?>
                                    </div>
                            </div>    
                            <div class="form-group">
                                <label class="control-label col-md-2 col-sm-2 col-xs-12">Last Name:</label>
                                    <div class="col-md-3 col-sm-3 col-xs-12">
                                        <?php  echo $this->formRow($register->get('last_name')); ?>
                                    </div>
                                 <label class="control-label col-md-2 col-sm-2 col-xs-12">CID No: <span class="required">*</span></label>
                                    <div class="col-md-3 col-sm-3 col-xs-12">
                                        <?php  echo $this->formRow($register->get('cid')); ?>
                                    </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-2 col-sm-2 col-xs-12">Date of Birth:<span class="required">*</span></label>
                                    <div class="col-md-3 col-sm-3 col-xs-12">
                                        <?php  echo $this->formRow($register->get('date_of_birth')); ?>
                                    </div>
                                    <label class="control-label col-md-2 col-sm-2 col-xs-12">Gender:<span class="required">*</span></label>
                                    <div class="col-md-3 col-sm-3 col-xs-12">
                                        <?php  echo $this->formRow($register->get('gender')); ?>
                                    </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-2 col-sm-2 col-xs-12">Student Id:</label>
                                    <div class="col-md-3 col-sm-3 col-xs-12">
                                            <?php  echo $this->formRow($register->get('student_id')); ?>
                                    </div>
                                <label class="control-label col-md-2 col-sm-2 col-xs-12">Programme:<span class="required">*</span></label>
                                    <div class="col-md-3 col-sm-3 col-xs-12">
                                        <?php  echo $this->formRow($register->get('alumni_programmes_id')); ?>
                                    </div>
                                    
                            </div>
                            <div class="form-group">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12">Enrollment Year:<span class="required">*</span></label>
                                    <div class="col-md-3 col-sm-3 col-xs-12">
                                            <?php  echo $this->formRow($register->get('enrollment_year')); ?>
                                    </div> 
                                <label class="control-label col-md-2 col-sm-2 col-xs-12">Graduation Year:<span class="required">*</span></label>
                                    <div class="col-md-3 col-sm-3 col-xs-12">
                                            <?php  echo $this->formRow($register->get('graduation_year')); ?>
                                    </div>
                            </div><br/>
                            <h4><i>Current Details</i></h4>
                            <div class="form-group">
                                <label class="control-label col-md-2 col-sm-2 col-xs-12">Current Organisation:</label>
                                    <div class="col-md-3 col-sm-3 col-xs-12">
                                           <?php  echo $this->formRow($register->get('current_job_organisation')); ?>
                                    </div>
                                    <label class="control-label col-md-2 col-sm-2 col-xs-12">Current Job Title:</label>
                                    <div class="col-md-3 col-sm-3 col-xs-12">
                                            <?php  echo $this->formRow($register->get('current_job_title')); ?>
                                    </div>
                            </div>
                            <div class="form-group">
                                 <label class="control-label col-md-2 col-sm-2 col-xs-12">Qualification Level:</label>
                                    <div class="col-md-3 col-sm-3 col-xs-12">
                                            <?php  echo $this->formRow($register->get('qualification_level_id')); ?>
                                    </div>
                                    <label class="control-label col-md-2 col-sm-2 col-xs-12">Qualification Field:</label>
                                    <div class="col-md-3 col-sm-3 col-xs-12">
                                            <?php  echo $this->formRow($register->get('qualification_field')); ?>
                                    </div>
                            </div>
                            <div class="form-group"> 
                                <label class="control-label col-md-2 col-sm-2 col-xs-12">Email Address:<span class="required">*</span></label>
                                    <div class="col-md-3 col-sm-3 col-xs-12">
                                            <?php  echo $this->formRow($register->get('email_address')); ?>
                                    </div>
                                <label class="control-label col-md-2 col-sm-2 col-xs-12">Contact No:<span class="required">*</span></label>
                                    <div class="col-md-3 col-sm-3 col-xs-12">
                                           <?php  echo $this->formRow($register->get('contact_no')); ?>
                                    </div>
                            </div>
                            <div class="form-group"> 
                                <label class="control-label col-md-2 col-sm-2 col-xs-12">Registration Date:<span class="required">*</span></label>
                                    <div class="col-md-3 col-sm-3 col-xs-12">
                                            <?php  echo $this->formRow($register->get('registration_date')); ?>
                                    </div>
                                <label class="control-label col-md-2 col-sm-2 col-xs-12">Present Address:<span class="required">*</span></label>
                                    <div class="col-md-3 col-sm-3 col-xs-12">
                                            <?php  echo $this->formRow($register->get('present_address')); ?>
                                    </div>                               
                            </div>
							
                            <div class="form-group">
                            <div class="ln_solid"></div>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <?php  echo $this->formRow($form->get('csrf')); ?>
                                            <?php  echo $this->formSubmit($register->get('submit')); ?>
                                        </div>
                                </div>
                            </div>
                            <?php
                                echo $this->form()->closeTag();
                            ?>
                            </div>
                        </div><!--end of x-content-->
                    </div><!--end of x-Panel-->
                </div><!--end of col-md-12 col-xs-12-- >
        </div><!--end of ""-->
</div><!--end of right_col-- >

 