<?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Compose Mail';
 $this->headTitle($title);

 $alumni_subscription = array();
 foreach($this->check_subscribtion as $subscription){
  $alumni_subscription[] = $subscription;
 }
 $StaringDate = $subscription['updated_date'];

 $newEndingDate = date("Y-m-d", strtotime(date("Y-m-d", strtotime($StaringDate)) . " + 365 day"));

?>
<div class="right_col" role="main">
    <div class="">
        <div class="col-md-12 col-xs-12">
            <div class="x_panel">
              <?php if($this->alumni_id){?>
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                </div><!--end of x-title-->
                <?php if(!empty($alumni_subscription)){?>
                  <?php if($subscription['subscription_type'] == "Yearly"){?> 
                    <?php if(date('Y-m-d') <= $newEndingDate){ ?>
                    <div class="x_content">
                    <br />
                    <?php
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        $enquiry = $form->get('alumnienquiry');
						            $enquiry->get('alumni_id')->setValue($this->alumni_id);					 
						            $enquiry->get('organisation_id')->setValue($this->organisation_id);
                        $enquiry ->get('enquiry_status')->setValue('Pending');
                        echo $this->formHidden($enquiry->get('organisation_id'));
                        echo $this->formHidden($enquiry->get('alumni_id'));
                        echo $this->formHidden($enquiry->get('enquiry_status'));
                        echo $this->formHidden($enquiry->get('id')); 
                     ?>

                     <?php 
                            if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                                echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                $messages = $this->flashMessenger()->getMessages();
                                foreach($messages as $message) {
                                    echo '<strong>Success!</strong>'. $message;
                                }
                                echo '</div>';
                            }

                            else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                                echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                $messages = $this->flashMessenger()->getMessages();
                                foreach($messages as $message) {
                                    echo '<strong>Failure!</strong>'. $message;
                                }
                                echo '</div>';
                            }
                        ?>
                            
                            <div class="form-group">
                                <label class="control-label col-md-2 col-sm-2 col-xs-12">Topic:</label>
                                    <div class="col-md-8 col-sm-8 col-xs-12">
                                        <?php  echo $this->formRow($enquiry->get('topic')); ?>
                                    </div>
                            </div>
                        <br/> 
						<div class="form-group"> 
                                <label class="control-label col-md-2 col-sm-2 col-xs-12">Enquiries:</label>
                                    <div class="col-md-8 col-sm-8 col-xs-12">
                                            <?php  echo $this->formRow($enquiry->get('email_contents')); ?>
                                    </div>
									
                            </div>
                        <br/>
                       
                            <div class="ln_solid"></div>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                        <?php 
                                                     echo $this->formHidden($form->get('csrf'));
                                                      echo $this->formSubmit($enquiry->get('submit')); 
                                                      echo $this->form()->closeTag();

                                                      ?>
                                        </div>
                                </div>
                        </div>
                            
                    </div><!--end of x-content-->

              <div class="x_panel"> 
                  <div class="x_title">
                    <h2>Equiry Lists: <small>(Alumni Enqu lists for the year)</small></h2>
                  <div class="clearfix"></div>
                  </div>
            <div class="x_content">
                    <div class="table-responsive">
                      <table id="datatable-responsive" class="table table-striped responsive-utilities jambo_table bulk_action table-bordered"> 
                         <thead>
                          <tr class="headings">
                      <!--  <th>
                          <input type="checkbox" id="check-all" class="flat" disabled>
                        </th>-->                          
                          <th class="column-title">Sl.No. </th>
                          <th class="column-title">Enquiry Topic</th>
                          <th class="column-title">Content</th>
                          <th class="column-title">Enquiry Status</th>
                          <th class="column-title">Date</th>
                          <th class="bulk-actions" colspan="7">
                              <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                            </th>
                         </tr>
                        </thead>
                        <?php $i=1; ?>
                         <?php foreach ($this->enquiry as $enquiry) : ?>
                          <tr class="even pointer">
                           <!--  <td class="a-center ">
                              <input type="checkbox" class="flat" name="table_records">
                            </td>-->
                             <td class=" "><?php echo $i; ?></td>
                                                  <td class=" "><?php echo $enquiry['topic'];?></td>
                                                  <td class=" "><?php echo $enquiry['email_contents'];?></td>
                                                  <td class=" "><?php echo $enquiry['enquiry_status'];?></td>
                                                  <td class=" "><?php echo $enquiry['created_date'];?></td>

                          </tr>
                           <?php $i++; ?>
                          <?php endforeach; ?>
                          </table>
                    </div>
            </div>
        </div>
      <?php } else{?>
         <div class="x_content">
          <?php 
                            
                     echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert"></button>';
                    echo '<strong>Alert! Your yearly subscription has been expired on '.$newEndingDate.'. Please contact your alumni manager to RENEW your subscription.</strong>';
                    echo '</div>';
            ?>
          </div>
      <?php } ?>
      <?php } else {?>
          <div class="x_content">
                    <br />
                    <?php
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        $enquiry = $form->get('alumnienquiry');
                        $enquiry->get('alumni_id')->setValue($this->alumni_id);          
                        $enquiry->get('organisation_id')->setValue($this->organisation_id);
                        $enquiry ->get('enquiry_status')->setValue('Pending');
                        echo $this->formHidden($enquiry->get('organisation_id'));
                        echo $this->formHidden($enquiry->get('alumni_id'));
                        echo $this->formHidden($enquiry->get('enquiry_status'));
                        echo $this->formHidden($enquiry->get('id')); 
                     ?>

                     <?php 
                            if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                                echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                $messages = $this->flashMessenger()->getMessages();
                                foreach($messages as $message) {
                                    echo '<strong>Success!</strong>'. $message;
                                }
                                echo '</div>';
                            }

                            else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                                echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                $messages = $this->flashMessenger()->getMessages();
                                foreach($messages as $message) {
                                    echo '<strong>Failure!</strong>'. $message;
                                }
                                echo '</div>';
                            }
                        ?>
                            
                            <div class="form-group">
                                <label class="control-label col-md-2 col-sm-2 col-xs-12">Topic:</label>
                                    <div class="col-md-8 col-sm-8 col-xs-12">
                                        <?php  echo $this->formRow($enquiry->get('topic')); ?>
                                    </div>
                            </div>
                        <br/> 
            <div class="form-group"> 
                                <label class="control-label col-md-2 col-sm-2 col-xs-12">Enquiries:</label>
                                    <div class="col-md-8 col-sm-8 col-xs-12">
                                            <?php  echo $this->formRow($enquiry->get('email_contents')); ?>
                                    </div>
                  
                            </div>
                        <br/>
                       
                            <div class="ln_solid"></div>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                        <?php 
                                                     echo $this->formHidden($form->get('csrf'));
                                                      echo $this->formSubmit($enquiry->get('submit')); 
                                                      echo $this->form()->closeTag();

                                                      ?>
                                        </div>
                                </div>
                        </div>
                            
                    </div><!--end of x-content-->

              <div class="x_panel"> 
                  <div class="x_title">
                    <h2>Equiry Lists: <small>(Alumni Enqu lists for the year)</small></h2>
                  <div class="clearfix"></div>
                  </div>
            <div class="x_content">
                    <div class="table-responsive">
                      <table id="datatable-responsive" class="table table-striped responsive-utilities jambo_table bulk_action table-bordered"> 
                         <thead>
                          <tr class="headings">
                      <!--  <th>
                          <input type="checkbox" id="check-all" class="flat" disabled>
                        </th>-->                          
                          <th class="column-title">Sl.No. </th>
                          <th class="column-title">Enquiry Topic</th>
                          <th class="column-title">Content</th>
                          <th class="column-title">Enquiry Status</th>
                          <th class="column-title">Date</th>
                          <th class="bulk-actions" colspan="7">
                              <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                            </th>
                         </tr>
                        </thead>
                        <?php $i=1; ?>
                         <?php foreach ($this->enquiry as $enquiry) : ?>
                          <tr class="even pointer">
                           <!--  <td class="a-center ">
                              <input type="checkbox" class="flat" name="table_records">
                            </td>-->
                             <td class=" "><?php echo $i; ?></td>
                                                  <td class=" "><?php echo $enquiry['topic'];?></td>
                                                  <td class=" "><?php echo $enquiry['email_contents'];?></td>
                                                  <td class=" "><?php echo $enquiry['enquiry_status'];?></td>
                                                  <td class=" "><?php echo $enquiry['created_date'];?></td>

                          </tr>
                           <?php $i++; ?>
                          <?php endforeach; ?>
                          </table>
                    </div>
            </div>
        </div>
      <?php }?>
      <?php } else{?>
        <div class="x_content">
          <?php 
                            
                     echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert"></button>';
                    echo '<strong>Alert! You are not registered for alumni subscription. If you need this service then please get register in alumni subscription</strong>';
                    echo '</div>';
            ?>
          </div>
      <?php } ?>
    </div>
  <?php } else{?>
    <div class="x_content">
      <?php 
                            
                     echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert"></button>';
                    echo '<strong>Alert! You are not eligible to post any enquiry.</strong>';
                    echo '</div>';
            ?>
    </div>
  <?php } ?>

 </div>
</div>
</div>

 

 