<?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Edit Alumni Subscription Details';
 $this->headTitle($title);

 $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    //IDEA-CBC
    //Original
    //$iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('aes-256-cbc'));

    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));

    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}
?>
<div class="right_col" role="main">
    <div class="">
        <div class="col-md-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                </div><!--end of x-title-->
                <div class="x_content">
                    <?php
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        $subscription = $form->get('alumnisubscriptiondetails');
                        $subscription->get('id')->setValue($this->subscriptionDetail->getId());
            						$subscription->get('organisation_id')->setValue($this->subscriptionDetail->getOrganisation_Id());
                        $subscription->get('subscription_details')->setValue($this->subscriptionDetail->getSubscription_Details());
                        $subscription->get('subscription_charge')->setValue($this->subscriptionDetail->getSubscription_Charge());
                        $subscription->get('remarks')->setValue($this->subscriptionDetail->getRemarks());
                        $subscription->get('submit')->setValue('Update');
                         echo $this->formHidden($subscription->get('id')); 
            						echo $this->formHidden($subscription->get('organisation_id'));
                     ?>

                     <?php 
                            if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                                echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                $messages = $this->flashMessenger()->getMessages();
                                foreach($messages as $message) {
                                    echo '<strong>Success!</strong>'. $message;
                                }
                                echo '</div>';
                            }

                            else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                                echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                $messages = $this->flashMessenger()->getMessages();
                                foreach($messages as $message) {
                                    echo '<strong>Failure!</strong>'. $message;
                                }
                                echo '</div>';
                            }
                        ?>
                        <h4><i>Please enter edit subscription details of your organisation</i></h4><br/>
                            
                            <div class="form-group">
                                <label class="control-label col-md-2 col-sm-2 col-xs-12">Subscription Details:<span class="required">*</span></label>
                                    <div class="col-md-8 col-sm-8 col-xs-12">
                                        <?php  echo $this->formRow($subscription->get('subscription_details')); ?>
                                    </div>
                            </div>    
                            <div class="form-group">
                                <label class="control-label col-md-2 col-sm-2 col-xs-12"> Subscription Charge:</label>
                                        <div class="col-md-3 col-sm-3 col-xs-12">
                                            <?php  echo $this->formRow($subscription->get('subscription_charge')); ?>
                                      </div>
                                <label class="control-label col-md-2 col-sm-2 col-xs-12"> Remarks:</label>
                                        <div class="col-md-3 col-sm-3 col-xs-12">
                                            <?php  echo $this->formRow($subscription->get('remarks')); ?>
                                        </div>
                            </div>
                            <div class="ln_solid"></div>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                        <?php 
                                                     echo $this->formHidden($form->get('csrf'));
                                                      echo $this->formSubmit($subscription->get('submit')); ?>
                                        </div>
                                </div>
                        </div>
                            <?php
                                echo $this->form()->closeTag();
                            ?>
                    </div><!--end of x-content-->
                </div>
</div>
</div>

