<?php
 $title = 'Update Selected Applicant Details';
 $this->headTitle($title);
 $personal = array();
 $vacancy_detail = array();
 $pay_scale = array();
 foreach($this->personalDetails as $detail){
	 $personal = $detail;
 }
 
 foreach($this->vacancyDetail as $detail){
	 $vacancy_detail = $detail;
 }
 
 foreach($this->payScale as $scale){
     $pay_scale[$scale['id']] = $scale['minimum_pay_scale'].'-'.$scale['maximum_pay_scale'];
 }

 ?>
  <div class="right_col" role="main">
          <div class="">
              <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
				  <?php
                    // Opening of the form tag
                   $form->prepare();
                   echo $this->form()->openTag($form);
                   // $application = $form->get('jobapplication');
                    $form->get('id')->setValue($this->id);
                    $form->get('religion')->setValueOptions($this->religion);
                    $form->get('blood_group')->setValueOptions($this->bloodGroup);
                    $form->get('emp_type')->setValueOptions($this->employeeType);
                    $form->get('emp_job_applications_id')->setValue($this->id);
                   // $form->get('emp_job_applications_id')->setValue($this->emp_job_applications_id);
                   /* if(array_key_exists('position_title', $vacancy_detail)){
                      $form->get('position_title')->setValue($vacancy_detail['position_title']);
                    }
                    if(array_key_exists('position_level', $vacancy_detail)){
                      $form->get('position_level')->setValue($vacancy_detail['position_level']);
                    }
                    if(array_key_exists('position_category', $vacancy_detail)){
                      $form->get('position_category')->setValue($vacancy_detail['position_category']);
                    }
                    $form->get('pay_scale')->setValue($pay_scale[$vacancy_detail['position_level']]);*/
                    $form->get('emp_resignation_id')->setValue('0');
                    $form->get('status')->setValue('Pending');
                    echo $this->formHidden($form->get('emp_resignation_id'));
                    echo $this->formHidden($form->get('id'));
                   // echo $this->formHidden($form->get('emp_job_applications_id'));
                   echo $this->formHidden($form->get('emp_job_applications_id'));
                    echo $this->formHidden($form->get('status'));
                    $form->get('submit')->setValue('Update');
                 ?> 
                  <!-- Personal Details Information-->
                  <h2 class="StepTitle">Personal Details</h2>
                  <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Name:</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <h4 class="blue"><i><?php echo $personal['first_name'].' '.$personal['middle_name'].' '.$personal['last_name']; ?></i></h4>
                        </div>
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Emp ID:</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <h4 class="blue"><i><?php if(array_key_exists('position_title', $vacancy_detail)){
                               echo $personal['emp_id']; 
                            } else{
                                 echo "No Emp ID";
                               }
												?></i></h4>
                        </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Date of Birth:</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <h4 class="blue"><i><?php echo $personal['date_of_birth']; ?></i></h4>
                        </div>
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Marital Status:</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <h4 class="blue"><i><?php echo $personal['maritial_status']; ?></i></h4>
                        </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">CID:</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <h4 class="blue"><i><?php echo $personal['cid']; ?></i></h4>
                        </div>
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Gender:</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <h4 class="blue"><i><?php echo $personal['gender']; ?></i></h4>
                        </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Contact No:</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <h4 class="blue"><i><?php echo $personal['contact_no']; ?></i></h4>
                        </div>
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Email:</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <h4 class="blue"><i><?php echo $personal['email']; ?></i></h4>
                        </div>
                    </div>
                  </div>
                  
                  <h2 class="StepTitle">Address Details</h2>
                  <div class="row">
                    <div class="form-group">  
                       <label class="control-label col-md-2 col-sm-2 col-xs-12">Address:</label>
                       <label class="control-label col-md-1 col-sm-2 col-xs-12">House No:</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <h4 class="blue"><i><?php echo $personal['house_no']; ?></i></h4>
                       </div>
                       <label class="control-label col-md-1 col-sm-2 col-xs-12">Thram No:</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <h4 class="blue"><i><?php echo $personal['thram_no']; ?></i></h4>
                       </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group">
                    <label class="control-label col-md-2 col-sm-2 col-xs-12"></label>
                    <label class="control-label col-md-1 col-sm-2 col-xs-12">Country:</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <h4 class="blue"><i><?php echo $personal['country']; ?></i></h4>
                        </div>
                        <label class="control-label col-md-1 col-sm-2 col-xs-12">Nationality:</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <h4 class="blue"><i><?php echo $personal['nationality']; ?></i></h4>
                        </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group">  
                       <label class="control-label col-md-2 col-sm-2 col-xs-12"></label>
                       <label class="control-label col-md-1 col-sm-2 col-xs-12">Village:</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <h4 class="blue"><i><?php echo $personal['village_name']; ?></i></h4>
                       </div>
                       <label class="control-label col-md-1 col-sm-2 col-xs-12">Gewog:</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <h4 class="blue"><i><?php echo $personal['gewog_name']; ?></i></h4>
                       </div>
                    </div>
                  </div><div class="row">
                    <div class="form-group">  
                       <label class="control-label col-md-2 col-sm-2 col-xs-12"></label>
                       <label class="control-label col-md-1 col-sm-2 col-xs-12">Dzongkhag:</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <h4 class="blue"><i><?php echo $personal['dzongkhag_name']; ?></i></h4>
                       </div>
                    </div>
                  </div>
                  <br />

                  <h2 class="StepTitle">Other Related Detail<i><font color="red">(Please fill up the form)</i></font></h2>
                  <br />
                  <div class="row">
                    <div class="form-group">  
                       <label class="control-label col-md-2 col-sm-2 col-xs-12">Religion:</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <?php echo $this->formRow($form->get('religion')); ?>
                       </div>
                       <label class="control-label col-md-2 col-sm-2 col-xs-12">Blood Group:</label>
                       <div class="col-md-3 col-sm-2 col-xs-12">
                          <?php echo $this->formRow($form->get('blood_group')); ?>
                       </div>
                    </div>
                  </div>
                  <h2 class="StepTitle">Employment Details:<i><font color="red">(Please fill up the form)</i></font></h2>
                  <br />
                  <div class="row">
                    <div class="form-group"> 
                      <label class="control-label col-md-2 col-sm-2 col-xs-12">Working Agency:<span class="required">*</span></label>
                        <div class="col-md-2 col-sm-2 col-xs-12">
                          <?php echo $this->formRow($form->get('organisation_id')); ?>
                        </div> 
                        <label class="control-label col-md-1 col-sm-3 col-xs-12">Department:</label>
                        <div class="col-md-2 col-sm-2 col-xs-12">
                          <?php echo $this->formRow($form->get('departments_id')); ?>
                        </div>
                        <label class="control-label col-md-1 col-sm-2 col-xs-12">Division/Section:</label>
                        <div class="col-md-2 col-sm-2 col-xs-12">
                          <?php echo $this->formRow($form->get('departments_units_id')); ?>
                        </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group"> 
                      <label class="control-label col-md-2 col-sm-2 col-xs-12">Occupational Group:<span class="required">*</span></label>
                        <div class="col-md-2 col-sm-2 col-xs-12">
                          <?php echo $this->formRow($form->get('occupational_group')); ?>
                        </div> 
                        <label class="control-label col-md-1 col-sm-3 col-xs-12">Category:</label>
                        <div class="col-md-2 col-sm-2 col-xs-12">
                          <?php echo $this->formRow($form->get('emp_category')); ?>
                        </div>
                        <label class="control-label col-md-1 col-sm-2 col-xs-12">Position Title:</label>
                        <div class="col-md-2 col-sm-2 col-xs-12">
                          <?php echo $this->formRow($form->get('position_title_id')); ?>
                        </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group"> 
                      <label class="control-label col-md-2 col-sm-2 col-xs-12">Position Level:<span class="required">*</span></label>
                        <div class="col-md-2 col-sm-2 col-xs-12">
                          <?php echo $this->formRow($form->get('position_level_id')); ?>
                        </div> 
                        <label class="control-label col-md-1 col-sm-3 col-xs-12">Staff Type:</label>
                        <div class="col-md-2 col-sm-2 col-xs-12">
                          <?php echo $this->formRow($form->get('emp_type')); ?>
                        </div>
                        <label class="control-label col-md-1 col-sm-2 col-xs-12">Recruitment Date:</label>
                        <div class="col-md-2 col-sm-2 col-xs-12">
                          <?php echo $this->formRow($form->get('recruitment_date')); ?>
                        </div>
                    </div>
                  </div>
  
                  <div class="ln_solid"></div>
                  <div class="clearfix"></div>
                  <br />
                  <div class="row">
                    <div class="form-group">  
                       <div class="col-md-12 col-sm-12 col-xs-12">
                          <h5><i>
                                ***If there is any file that need to upload based on the description below, please upload but it is not mandatory to upload it.
                          </i></h5>
                       </div>
                    </div>
                  </div>
                  <br />
                  <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Announcement Document: <small>(Optional)</small></label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php echo $this->formRow($form->get('announcement_doc')); ?>
                        </div>
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Shortlisted Document: <small>(Optional)</small></label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php echo $this->formRow($form->get('shortlist_doc')); ?>
                        </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Selection Document: <small>(Optional)</small></label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php echo $this->formRow($form->get('selection_doc')); ?>
                        </div>
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Minutes Document: <small>(Optional)</small></label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php echo $this->formRow($form->get('minutes_doc')); ?>
                        </div>
                    </div>
                  </div> 

                  <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Employment Application Form: <small>(Optional)</small></label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php echo $this->formRow($form->get('emp_application_form_doc')); ?>
                        </div>
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Copies of Academic Transcripts and Certificates: <small>(Optional)</small></label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php echo $this->formRow($form->get('emp_academic_transcript_doc')); ?>
                        </div>
                    </div>
                  </div> 

                  <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Copies of Relevant Training Caetificates: <small>(Optional)</small></label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php echo $this->formRow($form->get('emp_training_doc')); ?>
                        </div>
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Copies of the CID/Work Permit: <small>(Optional)</small></label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php echo $this->formRow($form->get('emp_cid_wp_doc')); ?>
                        </div>
                    </div>
                  </div> 

                  <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Copies of Security Clearance: <small>(Optional)</small></label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php echo $this->formRow($form->get('emp_security_cl_doc')); ?>
                        </div>
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Copies of Medical Fitness Certificate: <small>(Optional)</small></label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php echo $this->formRow($form->get('emp_medical_doc')); ?>
                        </div>
                    </div>
                  </div> 
 

                  <div class="row">
                    <div class="form-group">
                    <label class="control-label col-md-2 col-sm-2 col-xs-12">No objection Certificate: <small>(Optional)</small></label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php echo $this->formRow($form->get('emp_no_objec_doc')); ?>
                        </div>  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Appointment Order Document: <small>(Optional)</small></label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php echo $this->formRow($form->get('appointment_order_doc')); ?>
                        </div>
                    </div>
                  </div> 

                  <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Other Document: <small>(Optional)</small></label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php echo $this->formRow($form->get('others_doc')); ?>
                        </div>
                    </div>
                  </div>
                  <br/>
                  <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Submission Status: <small><font color="red">(Required)</font></small></label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php echo $this->formRow($form->get('submission_status')); ?>
                        </div>
                    </div>
                  </div>
          		  <div class="ln_solid"></div>
                      <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                          <?php  
                          echo $this->formHidden($form->get('csrf')); 
                          echo $this->formSubmit($form->get('submit'));
                          echo $this->form()->closeTag($form);
                        ?>
                        </div>
                      </div>

       			 </div> <!-- End of x_content-->
        	  </div> <!-- End of x_panel-->
   			</div> 
        </div>
  	 </div>
   </div>
 </div>
 