<?php
 $title = 'Search for User';
 $this->headTitle($title);

$key = $this->keyphrase;
function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    //IDEA-CBC
    //Original
    //$iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('aes-256-cbc'));

    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));

    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}

?>
<div class="right_col" role="main">
  <div class="">
    <div class="col-md-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2><?php echo $this->escapeHtml($title); ?></h2>
         <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <br />
           <?php
            // Opening of the form tag
            $form->prepare();
            echo $this->form()->openTag($form);
           ?>
        <div class="row">
          <div class="col-md-3 col-sm-12 col-xs-12 form-group">
            <label>Student/Staff</label>
            <?php echo $this->formRow($form->get('user_type')); ?>
          </div>
          <div class="col-md-3 col-sm-12 col-xs-12 form-group">
            <label>First Name</label>
            <?php echo $this->formRow($form->get('name')); ?>
          </div>
          <div class="col-md-3 col-sm-12 col-xs-12 form-group">
            <label>Student/Staff ID</label>
            <?php echo $this->formRow($form->get('user_id')); ?>
          </div>
       </div>
        <div class="row">
            <div class="ln_solid"></div>
            <div class="form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                <div class="col-md-5 col-sm-6 col-xs-12">
				<?php
                   echo $this->formHidden($form->get('csrf'));
                   echo $this->formSubmit($form->get('submit')); 
                ?>
            	</div>
            </div>
       </div>
            <?php
            echo $this->form()->closeTag();
            ?>
        </div>
      </div>

<!-- Start of table listing budget ledgers -->
<div class="x_panel">
  <div class="x_title">
            <h2><?php echo $this->escapeHtml("List of Users"); ?></h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <?php 
                    if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                        echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                        echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                        $messages = $this->flashMessenger()->getMessages();
                        foreach($messages as $message) {
                            echo '<strong>Success!</strong>'. $message;
                        }
                        echo '</div>';
                    }

                    else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                        echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                        echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                        $messages = $this->flashMessenger()->getMessages();
                        foreach($messages as $message) {
                            echo '<strong>Failure!</strong>'. $message;
                        }
                        echo '</div>';
                    }
                ?>
                
        <div class="x_content">
             
              <table id="datatable-buttons" class="table table-striped jambo_table table-bordered">
                <thead>
                  <tr class="headings">
                    <th class="column-title">Sl. No</th>
                    <th class="column-title">Name</th>
                    <th class="column-title">SID</th>
                    <th class="column-title">Last Logged In ("Y-m-d h:i:s")</th>
                    <th class="column-title">Action</th>
                    
                     </tr>
                </thead>  
                <tbody>
                 <?php $i = 1; foreach ($this->employeeList as $detail) : ?>
                  <tr class="even pointer">
                    <td class=" " width="8%"><?php echo $i++;?></td>
                    <td class=" "><?php echo $this->escapeHtml($detail['first_name'].' '.$detail['middle_name'].' '.$detail['last_name']);?></td>
                    <td class=" "><?php 
										if(array_key_exists('emp_id', $detail))
											echo $this->escapeHtml($detail['emp_id']);
										else 
											echo $this->escapeHtml($detail['student_id']);
									?></td>
		    <td><?php echo $this->escapeHtml($detail['last_login']); ?></td>
		    <td class=" last" width="10%"><a href="<?php echo $this->url('updateuserpassword', array('id' => my_encrypt($detail['id'], $key)));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Change Password </a></td>
                  </tr>
                  <?php $i++; ?>
                  <?php endforeach; ?>
              </tbody>
              </table>
             </div>
          </div>
       </div>
     </div>      
  </div>
</div> 
</div>
