<?php
 $title = 'Change Password';
 $this->headTitle($title);
 $user_detail = array();
 foreach($this->userDetail as $detail){
	 $user_detail = $detail;
 } //var_dump($user_detail); die();
?>
<div class="right_col" role="main">
  <div class="">
    <div class="col-md-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2><?php echo $this->escapeHtml($title); ?></h2>
         <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <br />
           <?php
            // Opening of the form tag
            $form->prepare();
            echo $this->form()->openTag($form);
            $user = $form->get('changeuserpassword');
			      $user->get('id')->setValue($this->id);
            $user->get('user_type_id')->setValue($this->userTypeId);
            echo $this->formHidden($user->get('user_type_id'));
            echo $this->formHidden($user->get('id'));
           ?>
           <?php 
              if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                  echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                  echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                  $messages = $this->flashMessenger()->getMessages();
                  foreach($messages as $message) {
                      echo '<strong>Success!</strong>'. $message;
                  }
                  echo '</div>';
              }

              else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                  echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                  echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                  $messages = $this->flashMessenger()->getMessages();
                  foreach($messages as $message) {
                      echo '<strong>Failure!</strong>'. $message;
                  }
                  echo '</div>';
              }
            ?> 
            <div id="step-1">
                <h2 class="StepTitle">Personal Details</h2>
                <br />
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Name: </label>
                    <div class="col-md-3 col-sm-3 col-xs-12">
                      <h4><i><?php echo $user_detail['first_name'].' '.$user_detail['middle_name'].' '.$user_detail['last_name']; ?></i></h4>
                    </div>
                   </div>
                   <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">SID:</label>
                    <div class="col-md-1 col-sm-3 col-xs-12">
                      <h4><i><?php 
					  			if(array_key_exists('emp_id', $user_detail))
									echo $user_detail['emp_id']; 
								else
									echo $user_detail['student_id']; 
							?></i></h4>
                    </div>
            </div>
            <br />
        <div class="row">   
           <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12">New Password<span class="required">*</span></label>
            <div class="col-md-5 col-sm-12 col-xs-12 form-group">
            <?php  echo $this->formRow($user->get('password')); ?>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12">Repeat New Password<span class="required">*</span></label>
            <div class="col-md-5 col-sm-12 col-xs-12 form-group">
            <?php  echo $this->formRow($user->get('repeat_password')); ?>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12">Ask for a password change at the next sign in? <small>(Optional)</small></label>
            <div class="col-md-5 col-sm-12 col-xs-12 form-group">
              <?php echo $this->formRow($user->get('sign_in')); ?>
            </div>
          </div>
        </div> 
          
        <div class="row">
            <div class="ln_solid"></div>
            <div class="form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                <div class="col-md-5 col-sm-6 col-xs-12">
				<?php
                   echo $this->formHidden($form->get('csrf'));
                   echo $this->formSubmit($user->get('submit')); 
?>
            	</div>
            </div>
       </div>
            <?php
            echo $this->form()->closeTag();
            ?>
        </div>
      </div>
     </div>      
  </div>
</div> 
</div>
