<?php
        
 $title = 'HR Administration Report';
 $this->headTitle($title);

?>

 <div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
            
                <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                     <div class="clearfix"></div>
                    </div>
                	
                        <!-- Search Employees-->
                        <div class="col-md-12 col-xs-12">
                          <div class="x_panel">
                            <div class="x_title">
                              <h2><?php echo $this->escapeHtml("Report")?></h2>
                                <ul class="nav navbar-right panel_toolbox">
                                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                                </ul>
                             <div class="clearfix"></div>
                            </div>
                            <div class="x_content">
                               <?php
                                // Opening of the form tag
                                $form->prepare();
                                echo $this->form()->openTag($form);
                                $form->get('report_name')->setValueOptions($this->report_list);
                              ?>
                            
                              <div class="row">
                                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Report Type</label>
                                    <?php echo $this->formRow($form->get('report_name')); ?>
                                  </div>
                                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>From-To Date:</label>
                                    <?php echo $this->formRow($form->get('date')); ?>
                                  </div>
                             </div>
                             <div class="row">
                                <div class="ln_solid"></div>
                                <div class="form-group">
                                    <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                                      <?php
                                       echo $this->formHidden($form->get('csrf'));
                                       echo $this->formSubmit($form->get('submit')); 
                                       echo $this->form()->closeTag(); 
                                    ?>
                                </div>
                            </div>
                          </div>
                        </div>
                       </div>     
                          
                        <?php 
                            if(!empty($this->report_details) && $this->report_details['report_name'] == 'staff_leave'){
                                    echo $this->partial('staff_on_leave.phtml', 
                                                            array( 
                                                                'hr_report' => $this->hr_report)); 
                            } else if(!empty($this->report_details) && $this->report_details['report_name'] == 'staff_pending_leave'){
                                    echo $this->partial('staff_pending_leave.phtml', 
                                                            array( 
                                                                'hr_report' => $this->hr_report)); 
                            }else if(!empty($this->report_details) && $this->report_details['report_name'] == 'staff_tour'){
                                    echo $this->partial('staff_on_tour.phtml', 
                                                            array( 
                                                                'hr_report' => $this->hr_report)); 
                            } else if(!empty($this->report_details) && $this->report_details['report_name'] == 'staff_training'){
                                    echo $this->partial('staff_on_training.phtml', 
                                                            array( 
                                                                'hr_report' => $this->hr_report));
                            } else if(!empty($this->report_details) && $this->report_details['report_name'] == 'staff_leave_encashment'){
                                    echo $this->partial('staff_leave_encashment.phtml', 
                                                            array( 
                                                                'hr_report' => $this->hr_report));
                            } else if(!empty($this->report_details) && $this->report_details['report_name'] == 'staff_overall'){
                                    echo $this->partial('overall_staff_administration.phtml', 
                                                            array( 
                                                                'hr_report' => $this->hr_report)); 
                            }

                    ?>
                  </div>
                </div>
              </div>
            </div>
           </div>
     </div>