           
    <!-- page content -->
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_content">
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      <div class="profile_title">
                        <div class="col-md-6">
                          <h2>HR Report</h2>
                        </div>
                        <div class="col-md-6">
                        </div>
                      </div>
                      <!-- start of report-graph -->
                      <div class="x_content">
                        <canvas id="bar-chart-grouped" style="width:100%; height:280px;"></canvas>
                      </div>
                      <!-- end of report-graph -->
                      
                      <div class="" role="tabpanel" data-example-id="togglable-tabs">
                            <!-- start reports -->
                            <br /><br />
                            <h2><?php echo "Table";?></h2>
                            <?php if($this->hr_report != NULL) {?>
                            <table class="table table-striped jambo_table table-bordered">
                                <thead>                        
                                     <th class="column-title" style="width:20%">Position Category & Position Level</th>
                                     <?php foreach($this->five_year_plan as $year): ?>
                                     <th class="column-title" style="width:15%"><?php echo $year; ?></th>
                                     <?php endforeach; ?>
                                </thead>
                                <tbody>
                                  <?php $i =1; $temp_category = NULL; foreach($this->hr_report as $k => $v) : ?>
                                  <?php foreach($v as $key => $value):?>
                                  <?php if($temp_category == NULL || $temp_category != $k){ ?>
                                  <tr>
                                    <td colspan="6" style="text-align:center"><b><i><?php echo $k; $temp_category = $k;?></i></b></td>
                                  </tr>
                                  <?php } ?>
                                  <tr class="even pointer">
                                    <td class=" "><?php echo $key;?></td>
                                    <?php foreach($this->five_year_plan as $year): ?>
                                    <td class=" "><?php 
                                        if(array_key_exists($k, $this->hr_report) && array_key_exists($key, $this->hr_report[$k]) && array_key_exists($year, $this->hr_report[$k][$key])){
                                            echo count($this->hr_report[$k][$key][$year]);
                                        }
                                         else
                                            echo $this->escapeHtml(0);										
                                        ?></td>
                                    <?php endforeach; $i++?>
                                  </tr>
                                  <?php endforeach; ?>
                                  <?php endforeach; ?>
                                </tbody>
                              </table>
                             <?php } ?>
                            <!-- end of reports -->
                      </div>
                    </div>
                    <div class="col-md-3 col-sm-3 col-xs-12 profile_left">
                      <div class="profile_title">
                        <div class="col-md-6">
                          <h2>Report</h2>
                        </div>
                      </div>
                      <br />

                      <!-- report generation -->
                      <h5><i>*Generate Report. Please note that the graphs will be not be displayed in the generated pdf report. To use the graphs, 
                            save the graphs from the webpage and paste it to relevant document</i></h5><br />
                     <a href="<?php echo $this->url('generatehrreports', array('reporttype' => $this->report_type));?>" class="btn btn-success">Generate Report</a>
                     
                      <!-- end of report generation -->

                    </div>
                  </div>
                </div>
              </div>
        <!-- /page content -->
                  