<?php
 $title = 'Research Publication Details';
 $this->headTitle($title);
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    $registrant = $form->get('publications');
                    echo $this->formHidden($registrant->get('id'));
				  ?>  
                <div class="row">    
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Publication Name<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($registrant->get('publication_name')); ?>
                    </div>
                   </div>
                   <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Publication Date<span class="required">*</span></label>
                    <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($registrant->get('publication_date')); ?>
                    </div>
                  </div>
                </div> 
                  
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
						<?php
						   echo $this->formHidden($form->get('csrf'));
						   echo $this->formSubmit($registrant->get('submit')); 
                        ?>
                    	</div>
                    </div>
               </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                </div>
              </div>
        
        <!-- Start of table listing budget ledgers -->
        <div class="x_panel">
                <div class="x_content">
                     <div class="table-responsive">
                      <table class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Sl. No</th>
                            <th class="column-title">Publication Name</th>
                            <th class="column-title">Publication Date</th>
                            <th class="column-title">Action</th>
                            
                             </tr>
                        </thead>  
                        <tbody>
                      <tr>
                         <?php $i = 1; foreach ($this->publicationDetails as $detail) : ?>
                          <tr class="even pointer">
                            <td class=" "><?php echo $i++;?></td>
                            <td class=" "><?php echo $this->escapeHtml($detail['broad_head_name']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($detail['broad_head_code']);?></td>
                            <td class=" last"><a href="<?php echo $this->url('editbroadheadname', array('id' => $detail['id']));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a></td>
                          </tr>
                          <?php endforeach; ?>
                      </tr>
                      </tbody>
                      </table>
                     </div>
                  </div>
               </div>
             </div>
        
        
    
          </div>
        </div> 
     </div>
