<?php
 $title = 'Mission & Vision';
 $this->headTitle($title);
 
 $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));
    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}

?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				            $fiveyearplan = $form->get('fiveyearplan');
                    echo $this->form()->openTag($form);
                    echo $this->formHidden($fiveyearplan->get('id')); 
				            ?>  
                <?php 
                            if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                                echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                $messages = $this->flashMessenger()->getMessages();
                                foreach($messages as $message) {
                                    echo '<strong>Success!</strong>'. $message;
                                }
                                echo '</div>';
                            }

                            else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                                echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                $messages = $this->flashMessenger()->getMessages();
                                foreach($messages as $message) {
                                    echo '<strong>Failure!</strong>'. $message;
                                }
                                echo '</div>';
                            }
                        ?>
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12"> Five Year Plan: <span class="required">*</span>
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($fiveyearplan->get('five_year_plan')); ?>
                    </div>
                </div>
                </div>
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12"> Date: <span class="required">*</span>
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($fiveyearplan->get('date_range')); ?>
                    </div>
                </div>
                </div>                   
                  
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
						<?php
						   echo $this->formHidden($form->get('csrf'));
						   echo $this->formSubmit($fiveyearplan->get('submit')); 
                        ?>
                    	</div>
                    </div>
               </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                </div>
              </div>
        
         <!-- Start of table listing mission and vision -->
        <div class="x_panel">
        	<div class="x_title">
                  <h2><?php echo $this->escapeHtml('RUB Five Year Plans'); ?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                  </ul>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                     <div class="table-responsive">
                      <table class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Five Year Plan</th>
                            <th class="column-title">From</th>
                            <th class="column-title">To</th>
                            <th class="column-title">Action</th>
                          </tr>
                        </thead>  
                        <tbody>
                      <tr>
                         <?php foreach ($this->FiveYearPlan as $fiveyearplan) : ?>
                          <tr class="even pointer">
                            <td class=" "><?php echo $this->escapeHtml($fiveyearplan['five_year_plan']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($fiveyearplan['from_date']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($fiveyearplan['to_date']);?></td>
                            <td class=" ">
                            	<a href="<?php echo $this->url('editfiveyearplan', array('id' => my_encrypt($fiveyearplan['id'], $key)));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a></td>
                          </tr>
                          <?php endforeach; ?>
                      </tr>
                      </tbody>
                      </table>
                     </div>
                   </div>
                </div>
    
          </div>
        </div> 
     </div>
              
   
            
    