<?php
 $title = 'Trend Values of Success Indicator';
 $this->headTitle($title);
 $five_year_plan = array();
 foreach($this->five_year as $set){
			$start_year = $set['from_date'];
			$end_year = $set['to_date'];
		}
for($i=0; $i<5; $i++){
	$five_year_plan[] = substr($start_year, 0, 4)+$i;
}

$trend_detail = array();
foreach($this->successTrendDetail as $detail){
    $trend_detail = $detail;
}

$key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));
    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}


?>
<div class="right_col" role="main">
          <div class=""> 
         <!-- Adding Activities-->
         <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title)?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                    </ul>
                 <div class="clearfix"></div>
              
                </div>
                   
                <div class="x_content">
                  <br />
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    $indicators = $form->get('successindicatortrend');
                    //get the objectives with their id
                    $data = $this->selectData;
                    echo $this->form()->openTag($form);
                    $indicators->get('id')->setValue($trend_detail['id']);
                    $indicators->get('awpa_activities_id')->setValue($trend_detail['awpa_activities_id']);
                    $indicators->get('year_one_projected')->setValue($trend_detail['year_one_projected']);
                    $indicators->get('year_two_projected')->setValue($trend_detail['year_two_projected']);
                    $indicators->get('year_three_projected')->setValue($trend_detail['year_three_projected']);
                    $indicators->get('year_four_projected')->setValue($trend_detail['year_four_projected']);
                    $indicators->get('year_five_projected')->setValue($trend_detail['year_five_projected']);
                    $indicators->get('awpa_activities_id')->setValueOptions($data);
                    $indicators->get('employee_details_id')->setValueOptions($this->supervisorRoles);
                    echo $this->formHidden($indicators->get('id')); 
                  ?>
                
                  <?php if($this->message == NULL && $this->flashMessenger()->hasMessages()) {
							echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
							echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
							$messages = $this->flashMessenger()->getMessages();
							foreach($messages as $message) {
								echo '<strong>Success!</strong>'. $message;
							}
							echo '</div>';
                    	} else if($this->message =='Failure' && $this->flashMessenger()->hasMessages()) {
                            echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                            echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                            $messages = $this->flashMessenger()->getMessages();
                            foreach($messages as $message) {
                                echo '<strong>Warning!</strong>'. $message;
                            }
                            echo '</div>';
                     }  ?>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Activity Trend For<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($indicators->get('employee_details_id')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" >Success Indicator<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($indicators->get('awpa_activities_id')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Actual Values <br /><i><small>(Year <?php echo $five_year_plan[0].'-'.$five_year_plan[1]; ?>)</small></i></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($indicators->get('year_one_projected')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Actual Values <br /><i><small>(Year <?php echo $five_year_plan[1].'-'.$five_year_plan[2]; ?>)</small></i></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($indicators->get('year_two_projected')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Actual Values <br /><i><small>(Year <?php echo $five_year_plan[2].'-'.$five_year_plan[3]; ?>)</small></i></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($indicators->get('year_three_projected')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Actual Values <br /><i><small>(Year <?php echo $five_year_plan[3].'-'.$five_year_plan[4]; ?>)</small></i></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($indicators->get('year_four_projected')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Actual Values <br /><i><small>(Year <?php echo $five_year_plan[4].'-'.($five_year_plan[4]+1); ?>)</small></i></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($indicators->get('year_five_projected')); ?>
                    </div>
                  </div>
                 <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                          <?php
                            echo $this->formHidden($form->get('csrf'));
                            echo $this->formSubmit($indicators->get('submit')); 
                            echo $this->form()->closeTag(); 
                        ?>
                    </div>
                </div>
              </div>
        </div> 
                  
          <!-- Start of table listing Activities -->
        <div class="x_panel">
        	<div class="x_title">
                  <h2><?php echo $this->escapeHtml('Table Displaying the '.$title); ?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                  </ul>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                     <div class="table-responsive">
                      <table id="datatable-fixed-header" class="table table-striped jambo_table table-bordered">
                        <thead>
                          <tr class="headings">
                            <th class="column-title" style="width:8%">Sl No</th>
                            <th class="column-title" style="width:32%">Success Indicator</th>
                            <th class="column-title" style="width:10%">Actual Values<br /><i><small>(Year <?php echo $five_year_plan[0].'-'.$five_year_plan[1]; ?>)</small></i></th>
                            <th class="column-title" style="width:10%">Actual Values<br /><i><small>(Year <?php echo $five_year_plan[1].'-'.$five_year_plan[2]; ?>)</small></i></th>
                            <th class="column-title" style="width:10%">Actual Values<br /><i><small>(Year <?php echo $five_year_plan[2].'-'.$five_year_plan[3]; ?>)</small></i></th>
                            <th class="column-title" style="width:10%">Actual Values<br /><i><small>(Year <?php echo $five_year_plan[3].'-'.$five_year_plan[4]; ?>)</small></i></th>
                            <th class="column-title" style="width:10%">Actual Values<br /><i><small>(Year <?php echo $five_year_plan[4].'-'.($five_year_plan[4]+1); ?>)</small></i></th>
                            <th class="column-title" style="width:10%">Actions</th>
                          </tr>
                        </thead>  
                        <tbody>
                      <tr>
                         <?php $i =1; foreach ($this->successIndicatorTrend as $trends) : ?>
                          <tr class="even pointer">
                            <td class=" "><?php echo $this->escapeHtml($i++);?></td>
                            <td class=" "><?php echo $this->escapeHtml($trends['activity_name']);?></td>
          <td class=" "><?php echo $this->escapeHtml($trends['year_one_projected']);?></td>
          <td class=" "><?php echo $this->escapeHtml($trends['year_two_projected']);?></td>
          <td class=" "><?php echo $this->escapeHtml($trends['year_three_projected']);?></td>
          <td class=" "><?php echo $this->escapeHtml($trends['year_four_projected']);?></td>
          <td class=" "><?php echo $this->escapeHtml($trends['year_five_projected']);?></td>
                            <td><a href="<?php echo $this->url('editsuccessindicatortrend', array('id' => my_encrypt($trends['id'], $key)));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a></td>
                          </tr>
                          <?php endforeach; ?>
                      </tr>
                      </tbody>
                      </table>
                     </div>
                   </div>
                </div>
          </div>
        </div>
     </div>
