<?php
 $title = 'Edit Key Aspiration';
 $this->headTitle($title);
 $temp_message = NULL;
 if($this->flashMessenger()->hasMessages()){
    
         $temp_message = $this->flashMessenger()->getMessages();
         $temp_message = $temp_message[0];
 }

 $key_aspiration = array();
 foreach($this->keyAspirationDetail as $detail){
     $key_aspiration = $detail;
 }
 
 $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));
    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}

?>
<div class="right_col" role="main">
      <div class="">
         <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title)?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                
                    </ul>
                 <div class="clearfix"></div>
              
                </div>
                <div class="x_content">
                  <br />
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    $aspiration = $form->get('keyaspiration');
                    $aspiration->get('id')->setValue($key_aspiration['id']);
                    $aspiration->get('employee_details_id')->setValue($key_aspiration['employee_details_id']);
                    $aspiration->get('unit')->setValue($key_aspiration['unit']);
                    $aspiration->get('key_performance_indicator')->setValue($key_aspiration['key_performance_indicator']);
                    $aspiration->get('outstanding')->setValue($key_aspiration['outstanding']);
                    $aspiration->get('very_good')->setValue($key_aspiration['very_good']);
                    $aspiration->get('good')->setValue($key_aspiration['good']);
                    $aspiration->get('need_improvement')->setValue($key_aspiration['need_improvement']);
                    $aspiration->get('financial_year')->setValue($key_aspiration['financial_year']);
                    $aspiration->get('activity_status')->setValue($key_aspiration['activity_status']);
                    //get the objectives with their id
                    echo $this->form()->openTag($form);
                    echo $this->formHidden($aspiration->get('id'));
                    echo $this->formHidden($aspiration->get('financial_year')); 
                    echo $this->formHidden($aspiration->get('activity_status'));
                    $aspiration->get('submit')->setValue('Update Key Aspiration');  
                    $aspiration->get('employee_details_id')->setValueOptions($this->supervisorRoles);
                  ?>
                    
                    <?php if($temp_message == 'Error' && $this->flashMessenger()->hasMessages()) {
							echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
							echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
							$messages = $this->flashMessenger()->getMessages();
							foreach($messages as $message) {
								echo '<strong>Success!</strong>'. 'The Total weightage exceeds 100! Please re-enter the values.';
							}
							echo '</div>';
						} else if($this->message == NULL && $this->flashMessenger()->hasMessages()) {
							echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
							echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
							$messages = $this->flashMessenger()->getMessages();
							foreach($messages as $message) {
								echo '<strong>Success!</strong>'. $message;
							}
							echo '</div>';
                    	} else if($this->message =='Failure' && $this->flashMessenger()->hasMessages()) {
                            echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                            echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                            $messages = $this->flashMessenger()->getMessages();
                            foreach($messages as $message) {
                                echo '<strong>Warning!</strong>'. $message;
                            }
                            echo '</div>';
                     }  ?>
                     
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">New Key Aspiration For<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($aspiration->get('employee_details_id')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">New Key Aspiration<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($aspiration->get('key_performance_indicator')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Measurement Unit</label>
                    <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($aspiration->get('unit')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12"> Target/Criteria Values</label>
                    <label class="control-label col-md-1 col-sm-3 col-xs-12">Outstanding:</label>
                    <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($aspiration->get('outstanding')); ?>
                    </div>
                    <label class="control-label col-md-1 col-sm-3 col-xs-12">Very Good:</label>
                    <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($aspiration->get('very_good')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12"> </label>
                    <label class="control-label col-md-1 col-sm-3 col-xs-12">Good:</label>
                    <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($aspiration->get('good')); ?>
                    </div>
                    <label class="control-label col-md-1 col-sm-3 col-xs-12">Need Improvement:</label>
                    <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($aspiration->get('need_improvement')); ?>
                    </div>
                  </div>
                 
                 <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                          <?php
						   //echo $this->formHidden($aspiration->get('remarks'));
						   //echo $this->formHidden($aspiration->get('financial_year'));
						   echo $this->formHidden($aspiration->get('activity_status'));
						   echo $this->formHidden($form->get('csrf'));
						   echo $this->formSubmit($aspiration->get('submit')); 
						   echo $this->form()->closeTag(); 
                        ?>
                    </div>
                </div>
                  
          </div>
        </div>
                  </div>     
                  
              
        <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml("Key Aspiration"); ?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>

                <div class="x_content">

                      <table id="datatable-buttons" class="table table-striped jambo_table bulk_action">

               
                    <thead>
                      <tr class="headings">
                        </th>
                         <th class="column-title">Sl.No.</th>
                         <th class="column-title">Key Aspiration</th>
                         <th class="column-title">Unit </th>
                         <th class="column-title">Outstanding</th>
                         <th class="column-title">Very Good</th>
                         <th class="column-title">Good</th>
                         <th class="column-title">Need Improvement</th>
                         <th class="column-title">Action</th>
                      </tr>
                    </thead>

                    <tbody>
                      <?php
					  $i=1;  foreach($this->key_aspiration as $aspiration): ?>
                      <tr class="even pointer">
                        <td class=" "><?php echo $i++;?></td>
                        <td class=" "><?php echo $aspiration['key_performance_indicator'];?></td>
                        <td class=" "><?php echo $aspiration['unit'];?></td>
                        <td class=" "><?php echo $aspiration['outstanding'];?></td>
                        <td class=" "><?php echo $aspiration['very_good'];?></td>
                        <td class=" "><?php echo $aspiration['good'];?></td>
                        <td class=" "><?php echo $aspiration['need_improvement'];?></td>
                        <td><a href="<?php echo $this->url('editkeyaspiration', array('id' => my_encrypt($aspiration['id'], $key)));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a></td>
                      </tr>
                      <?php endforeach; ?>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div> 
