<?php
 $title = 'Mission & Vision';
 $this->headTitle($title);
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				    $vision = $form->get('rubvisionmission');
                    echo $this->form()->openTag($form);
                    echo $this->formHidden($vision->get('id')); 
				  ?>  
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12"> Five Year Plan: <span class="required">*</span>
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($vision->get('five_year_plan')); ?>
                    </div>
                </div>
                </div>
                <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12"> Vision: <span class="required">*</span>
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($vision->get('vision')); ?>
                    </div>
                </div>
                </div> 
                   <div class="row">    
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12"> Mission: <span class="required">*</span>
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($vision->get('mission')); ?>
                    </div>
                </div>
                </div> 
                  
                  
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
						<?php
                           
						   echo $this->formHidden($form->get('csrf'));
						   echo $this->formSubmit($vision->get('submit')); 
                        ?>
                    	</div>
                    </div>
               </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                </div>
              </div>
        
         <!-- Start of table listing mission and vision -->
        <div class="x_panel">
        	<div class="x_title">
                  <h2><?php echo $this->escapeHtml('RUB Vision and Mission'); ?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                  </ul>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                     <div class="table-responsive">
                      <table class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Mission</th>
                            <th class="column-title">Action</th>
                          </tr>
                        </thead>  
                        <tbody>
                      <tr>
                         <?php foreach ($this->visionMission as $vision) : ?>
                          <tr class="even pointer">
                            <td class=" "><?php echo $this->escapeHtml($vision['mission']);?></td>
                            <td class=" ">
                            	<a href="<?php echo $this->url('editmissionvision', array('id' => $vision['id']));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a>
                                <a href="<?php echo $this->url('deletemissionvision', array('id' => $vision['id']));?>" class="btn btn-danger btn-xs"><i class="fa fa-thrash-o"></i>Delete</a></td>
                          </tr>
                          <?php endforeach; ?>
                      </tr>
                      </tbody>
                      </table>
                     </div>
                   </div>
                </div>
    
          </div>
        </div> 
     </div>
              
   
            
    