<?php
 $title = 'Edit Staff Personal Details';
 $this->headTitle($title);
?>

 <div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
            
                <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                     <div class="clearfix"></div>
                    </div>
                	
                        <!-- Search Employees-->
                        <div class="col-md-12 col-xs-12">
                          <div class="x_panel">
                            <div class="x_title">
                              <h2><?php echo $this->escapeHtml("Search for Employee")?></h2>
                                <ul class="nav navbar-right panel_toolbox">
                                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                  </li>
                            
                                </ul>
                             <div class="clearfix"></div>
                          
                            </div>
                               
                            <div class="x_content">
                            <h5><i>*(In order to edit "personal details" for an staff, first search for the staff and then select the staff from the table below to add
                                    his/her position level. Input as many fields as possible to narrow the search.)<br />
                                    **Also note, search by name is done by "First Name" only</i></h5>
                              <br />
                               <?php
                                // Opening of the form tag
                                $form->prepare();
                                echo $this->form()->openTag($form);
                              ?>
                            
                              <div class="row">
                                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Staff First Name</label>
                                    <?php echo $this->formRow($form->get('employee_name')); ?>
                                  </div>
                                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Staff ID</label>
                                    <?php echo $this->formRow($form->get('emp_id')); ?>
                                  </div>
                                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Position Title</label>
                                    <?php echo $this->formRow($form->get('department')); ?>
                                  </div>
                               </div>
                             
                             <div class="row">
                                <div class="ln_solid"></div>
                                <div class="form-group">
                                    <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                                      <?php
                                       echo $this->formHidden($form->get('csrf'));
                                       echo $this->formSubmit($form->get('submit')); 
                                       echo $this->form()->closeTag(); 
                                    ?>
                                </div>
                            </div>
                              
                          </div>
                        </div>
                       </div>     
                              
                          
                        <div class="col-md-12 col-sm-12 col-xs-12">
                          <div class="x_panel">
                            <div class="x_title">
                              <h2><?php echo $this->escapeHtml("List of Employee(s)"); ?></h2>
                              <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                </li>
                              </ul>
                              <div class="clearfix"></div>
                            </div>
            
                            <div class="x_content">
                              <table id="datatable-buttons" class="table table-striped jambo_table table-bordered">
                                <thead>                        
                                     <th class="column-title">Sl. No. </th>
                                        <th class="column-title">Staff ID</th>
                                        <th class="column-title">Name</th>
                                        <th class="column-title">Position Title </th>
                                        <th class="column-title">Department</th>
                                        <th class="column-title no-link last"><span class="nobr">Action</span>
                                        </th>
                                     </tr>
                                </thead>
            
                                <tbody>
                                  <?php $i =1; foreach ($this->employeeList as $employee) : ?>
                                  <tr class="even pointer">
                                    <td class=" "><?php echo $i++;?></td>
                                    <td class=" "><?php echo $this->escapeHtml($employee['emp_id']);?></td>
                                    <td class=" "><?php echo $this->escapeHtml($employee['first_name']) . ' ';
                                                        echo $this->escapeHtml($employee['middle_name']) . ' ';
                                                        echo $this->escapeHtml($employee['last_name']);
                                                  ?></td>
                                    <td class=" "><?php echo $this->escapeHtml($employee['position_title']);?></td></td>
                                    <td class=" "><?php echo $this->escapeHtml($employee['department_name']);?></td>
                                    <td class=" last"><a href="<?php echo $this->url('editemppersonaldetails', array('id' => $employee['id']));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit Personal Details</a> </td>
                                  </tr>
                                  <?php endforeach; ?>
                                </tbody>
                              </table>
                            </div>
                          </div>
                        </div>
                    
                        <!-- End of Search-->
                  
                     
                  </div>
                </div>
              </div>
     </div>
