<?php
$title = 'Allocated List';
$this->headTitle($title);
?>
                 
            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel"> 
                 <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    
                  <div class="clearfix"></div>
                  </div>
            <div class="x_content">
                              
                    <div class="table-responsive">
                      <table class="table table-striped jambo_table bulk_action"> 
                        <thead>
                          <tr class="headings">
                           
                            <th class="column-title">SL No </th>
                            <th class="column-title">Name </th>
                            <th class="column-title">Course </th>
                            <th class="column-title">Semester </th>
                            <th class="column-title">Hostel Name </th>
                            <th class="column-title">Room No </th>
                            <th class="column-title">Allocation Date </th>
                            <th class="column-title no-link last"><span class="nobr">Action</span>
                            </th>
                            <th class="bulk-actions" colspan="7">
                              <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                            </th>
                          </tr>
                        </thead>
                        
                        <tbody>
                     
                                                  
                        </tbody>
                          </table>
                      
                    </div>
            </div></div></div>                

                          
                  

                        
                      
                      
                  
                     
            
         
              
       
                