<?php
 $title = 'Add Timetable';
 $this->headTitle($title);
 $flash_message = NULL;
 $success = "Timetable has been successfully added";
 $failure = "Timetable for Day/Time has already been added";
 $messages = $this->flashMessenger()->getMessages();
 foreach($messages as $temp) {
	$flash_message = $temp;
 }

  $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    //IDEA-CBC
    //Original
    //$iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('aes-256-cbc'));

    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));

    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <?php if(!empty($this->check_allocated_tutor)) {?>
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                <?php if(strcasecmp($flash_message, $success) == 0) {
							echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
							echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
							echo '<strong>Success!</strong> '.$flash_message;
							echo '</div>';
					}
					if(strcmp($flash_message, $failure) == 0) {
                            echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                            echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                            echo '<strong>Failure!</strong> '.$flash_message;
							echo '</div>';
                     } ?>
                  <br />
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    echo $this->formHidden($form->get('id'));
					$form->get('from_time')->setValueOptions($this->fromTimingList);
					$form->get('to_time')->setValueOptions($this->toTimingList);
				//	$form->get('group')->setValueOptions($this->sectionList);
					$form->get('status')->setValue('Active');
					echo $this->formHidden($form->get('status'));
				  ?>  
                <div class="row">    
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Day<span class="required">*</span></label>
                    <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($form->get('day')); ?>
                    </div>
                    <label class="control-label col-md-2 col-sm-3 col-xs-12">Classroom/Hall<span class="required">*</span></label>
                    <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($form->get('classroom')); ?>
                    </div>
                  </div>
                </div>
                <div class="row">    
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">From (Time)<span class="required">*</span></label>
                    <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($form->get('from_time')); ?>
                    </div>
                    <label class="control-label col-md-2 col-sm-3 col-xs-12">To (Time)<span class="required">*</span><br /></label>
                    <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($form->get('to_time')); ?>
                    </div>
                  </div>
                </div> 
                 <div class="row">    
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Programme<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($form->get('programmes_id')); ?>
                    </div>
                   </div>
                   <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Module<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($form->get('academic_modules_allocation_id')); ?>
                    </div>
                  </div>
                </div>    
                <div class="row">    
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Section/Group<span class="required">*</span></label>
                    <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($form->get('group')); ?>
                    </div>
                   </div>
                </div>
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
						<?php
                           echo $this->formHidden($form->get('csrf'));
                           echo $this->formSubmit($form->get('submit')); 
                        ?>
                    	</div>
                    </div>
               </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                </div>
              </div>
        
        
        <!-- Start of table listing -->
        <div class="x_panel">
            <div class="x_title">
                    <h2><?php echo $this->escapeHtml('Timetable for Academic Year'); ?></h2>
                    <div class="clearfix"></div>
                  </div>
                  <br />
                  <!-- Start of Tab-->
                    <div class="" role="tabpanel" data-example-id="togglable-tabs">
                      <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                        <li role="presentation" class="active"><a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">Active Timetable</a>
                        </li>
                        <li role="presentation" class=""><a href="#tab_content2" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false">In Active Timetable</a>
                        </li>
                      </ul>
                      <div id="myTabContent" class="tab-content">
                        <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab">
                            <br/>
                                <div class="table-responsive">
                                  <table id="datatable-fixed-header" class="table table-striped jambo_table table-bordered">
                                    <thead>
                                      <tr class="headings">
                                        <th style="width: 5%" class="column-title">Sl. No</th>
                                        <th class="column-title">Day</th>
                                        <th class="column-title">From Time</th>
                                        <th class="column-title">To Time</th>
                                        <th class="column-title">Programme</th>
                                        <th class="column-title">Module Title</th>
                                        <th class="column-title">Module Code</th>
                                        <th class="column-title">Section/Group</th>
                                        <th class="column-title">Classroom</th>
                                        <th class="column-title">Action</th>
                                        
                                         </tr>
                                    </thead>  
                                    <tbody>
                                     <?php $i = 1; foreach ($this->timetable as $table) : ?>
                                      <tr class="even pointer">
                                        <td class=" "><?php echo $i++;?></td>
                                        <td class=" "><?php echo $this->escapeHtml($table['day']);?></td>
                                        <td class=" "><?php echo $this->escapeHtml($table['from_time']);?></td>
                                        <td class=" "><?php echo $this->escapeHtml($table['to_time']);?></td>
                                        <td class=" "><?php echo $this->escapeHtml($table['programme_code']);?></td>
                                        <td class=" "><?php echo $this->escapeHtml($table['module_title']);?></td>
                                        <td class=" "><?php echo $this->escapeHtml($table['module_code']);?></td>
                                        <td class=" "><?php echo $this->escapeHtml($table['section']);?></td>
                                        <td class=" "><?php echo $this->escapeHtml($table['classroom']);?></td>
                                        <td class=" last">
                                            <a href="<?php echo $this->url('edittimetable', array('id' => my_encrypt($table['id'], $key)));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a>
                                            <a href="<?php echo $this->url('deletetimetable', array('id' => my_encrypt($table['id'], $key)));?>" class="btn btn-danger btn-xs"><i class="fa fa-trash"></i>Delete</a>
                                        </td>
                                      </tr>
                                      <?php endforeach; ?>
                                  </tbody>
                                  </table>
                                 </div>
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="tab_content2" aria-labelledby="profile-tab">
                                <br/>
                                <div class="table-responsive">
                                      <table id="datatable" class="table table-striped jambo_table table-bordered">
                                        <thead>
                                          <tr class="headings">
                                            <th style="width: 5%" class="column-title">Sl. No</th>
                                            <th class="column-title">Day</th>
                                            <th class="column-title">From Time</th>
                                            <th class="column-title">To Time</th>
                                            <th class="column-title">Programme</th>
                                            <th class="column-title">Module Title</th>
                                            <th class="column-title">Module Code</th>
                                            <th class="column-title">Section/Group</th>
                                            <th class="column-title">Classroom</th>
                                            <th class="column-title">Action</th>
                                            
                                             </tr>
                                        </thead>  
                                        <tbody>
                                         <?php $i = 1; foreach ($this->inActiveTimetable as $table) : ?>
                                          <tr class="even pointer">
                                            <td class=" "><?php echo $i++;?></td>
                                            <td class=" "><?php echo $this->escapeHtml($table['day']);?></td>
                                            <td class=" "><?php echo $this->escapeHtml($table['from_time']);?></td>
                                            <td class=" "><?php echo $this->escapeHtml($table['to_time']);?></td>
                                            <td class=" "><?php echo $this->escapeHtml($table['programme_code']);?></td>
                                            <td class=" "><?php echo $this->escapeHtml($table['module_title']);?></td>
                                            <td class=" "><?php echo $this->escapeHtml($table['module_code']);?></td>
                                            <td class=" "><?php echo $this->escapeHtml($table['section']);?></td>
                                            <td class=" "><?php echo $this->escapeHtml($table['classroom']);?></td>
                                            <td class=" last">
                                                <a href="<?php echo $this->url('edittimetable', array('id' => my_encrypt($table['id'], $key)));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a>
                                                <a href="<?php echo $this->url('deletetimetable', array('id' => my_encrypt($table['id'], $key)));?>" class="btn btn-danger btn-xs"><i class="fa fa-trash"></i>Delete</a>
                                            </td>
                                          </tr>
                                          <?php endforeach; ?>
                                      </tbody>
                                      </table>
                                     </div>
                        </div>
                        
                      </div>
                    </div>
                    <!-- End of Tabs-->
               </div>
             </div>
        
        <?php } else{?>
          <div class="x_content">
          <?php 
                            
                     echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert"></button>';
                    echo '<strong>Alert! You are not allocated with the module or you are not a academic staff.</strong>';
                    echo '</div>';
            ?>
          </div>
        <?php } ?>
    
          </div>
        </div> 
     </div>
