<?php
 $title = 'Edit Timetable Timings';
 $this->headTitle($title);
 $timetable_timing = array();
 foreach($this->timingDetails as $detail){
	 $timetable_timing = $detail;
 }
 
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
					$timetable = $form->get('timetabletiming');
					$timetable->get('id')->setValue($timetable_timing['id']);
					$timetable->get('organisation_id')->setValue($this->organisation_id);
					//$timetable->get('from_time')->setValue($timetable_timing['from_time']);
					//$timetable->get('to_time')->setValue($timetable_timing['to_time']);
                    echo $this->formHidden($timetable->get('id'));
					echo $this->formHidden($timetable->get('organisation_id'));
				  ?>  
                <div class="row">    
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">From Time<span class="required">*</span><br /></label>
                    <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($timetable->get('from_time')); ?>
                    </div>
                  </div>
                </div> 
                <div class="row">    
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">To Time<span class="required">*</span></label>
                    <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($timetable->get('to_time')); ?>
                    </div>
                  </div>
                </div> 
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
						<?php
                            echo $this->formRow($form->get('csrf'));
							echo $this->formSubmit($timetable->get('submit'));
							echo $this->form()->closeTag();
                        ?>
                    	</div>
                    </div>
               </div>
             </div>
           </div>
        
        <!-- Start of table listing -->
        <div class="x_panel">
                <div class="x_content">
                     <div class="table-responsive">
                      <table class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                            <th style="width: 15%" class="column-title">Sl. No</th>
                            <th class="column-title">From Time</th>
                            <th class="column-title">To Time</th>
                            <th style="width: 25%" class="column-title">Action</th>
                            
                             </tr>
                        </thead>  
                        <tbody>
                      <tr>
                         <?php $i = 1; foreach ($this->timingsList as $table) : ?>
                          <tr class="even pointer">
                            <td class=" "><?php echo $i++;?></td>
                            <td class=" "><?php echo $this->escapeHtml($table['from_time']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($table['to_time']);?></td>
                            <td class=" last"><a href="<?php echo $this->url('edittimetabletimings', array('id' => $table['id']));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a></td>
                          </tr>
                          <?php endforeach; ?>
                      </tr>
                      </tbody>
                      </table>
                     </div>
                  </div>
               </div>
             </div>
        
        
    
          </div>
        </div> 
     </div>
