<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
<div class="menu_section">
<br><br><br>
<ul class="nav side-menu">
	<li><a><i class="fa fa-home"></i>Home<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a href="<?php echo $this->url('index') ?>">Dashboard</a></li>
		</ul>
	</li>
	<li><a><i class="fa fa-users"></i>Human Resource<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>HR Administration<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>Leave<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('leavestatus') ?>">Apply Leave</a></li>
						<li><a href="<?php echo $this->url('staffleavestatus') ?>">My Leave Status</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Leave Encashment<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('empleaveencashmentapplication') ?>">Leave Encashment</a></li>
					</ul>
					</li>
			</ul>
			</li>
			<li><a><i class=""></i>Staff Lifecycle<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>Transfer<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('applytransferform') ?>">Apply Transfer</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Promotion<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('empapplypromotion') ?>">Apply Promotion</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Separation<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('empresignation') ?>">Apply Resignation</a></li>
						<li><a href="<?php echo $this->url('staffresignationstatus') ?>">My Resignation Status</a></li>
					</ul>
					</li>
			</ul>
			</li>
			<li><a><i class=""></i>PMS<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>Review<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('feedbacks') ?>">Feedbacks</a></li>
					</ul>
					</li>
			</ul>
			</li>
			<li><a><i class=""></i>Recruitment<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('appliedjobapplicationstatus') ?>">Individual Job Applicant Status</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>HR Development<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('applytrainings') ?>">Apply Trainings & Workshops</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Staff Tour<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('emptravelauthorization') ?>">Travel Authorization</a></li>
					<li><a href="<?php echo $this->url('stafftourstatus') ?>">Travel Status</a></li>
			</ul>
			</li>
		</ul>
	</li>
	<li><a><i class="fa fa-bank"></i>Admission<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>Student Section<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('edit-student-section') ?>">Update Student Section</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Student House<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('add-new-house') ?>">Add New House</a></li>
					<li><a href="<?php echo $this->url('add-new-student-house') ?>">Add New Student House</a></li>
					<li><a href="<?php echo $this->url('edit-student-house') ?>">Edit Student House</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Student Details<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('studentlists') ?>">Student Lists</a></li>
					<li><a href="<?php echo $this->url('studentpersonaldetails') ?>">Student Personal Details</a></li>
					<li><a href="<?php echo $this->url('studentpermanentaddressdetails') ?>">Student Permanent Address</a></li>
					<li><a href="<?php echo $this->url('studentrelationdetails') ?>">Student Relation Details</a></li>
					<li><a href="<?php echo $this->url('studentpreviousschooldetails') ?>">Student Previous School Details</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Parent Portal Access<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('parentportalaccess') ?>">Assign Parent</a></li>
			</ul>
			</li>
			<li><a href="<?php echo $this->url('new-registered-student-list') ?>">Report New Student</a></li>
			<li><a href="<?php echo $this->url('new-reported-student-list') ?>">Generate Student ID</a></li>
			<li><a href="<?php echo $this->url('reported-student-list') ?>">Update Reported Student List</a></li>
			<li><a href="<?php echo $this->url('add-new-student') ?>">Add New Student (College)</a></li>
			<li><a href="<?php echo $this->url('register-student-semester') ?>">Student Semester Registration</a></li>
			<li><a href="<?php echo $this->url('semesterreportedstudentlist') ?>">Update Student Status</a></li>
			<li><a href="<?php echo $this->url('graduatedstudentlist') ?>">Graduate Student</a></li>
			<li><a href="<?php echo $this->url('programmechange') ?>">Student Change Programme</a></li>
		</ul>
	</li>
	<li><a><i class="fa fa-graduation-cap"></i>Academic<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>Academic Assessment<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>Continuous Assessment<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('compileassessmentmarks') ?>">Compile CA Marks</a></li>
						<li><a href="<?php echo $this->url('viewcompiledassessmentmarks') ?>">Edit/Moderate Compile CA Marks</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Semester End<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('viewsemestermarks') ?>">View SE Marks</a></li>
						<li><a href="<?php echo $this->url('viewcompiledsemestermarks') ?>">Edit/Moderate Compile SE Marks</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Repeat Module<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('addrepeatconsolidatedmarks') ?>">Add Repeat Module Marks</a></li>
					</ul>
					</li>
			</ul>
			</li>
			<li><a><i class=""></i>Module Allocation<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('assignmoduletotutors') ?>">Assign Module Tutor</a></li>
					<li><a href="<?php echo $this->url('viewacademicyeartutor') ?>">View Module Tutor for Academic Year</a></li>
					<li><a href="<?php echo $this->url('viewacademicyearmodule') ?>">View Module Allocation by Academic Year</a></li>
					<li><a href="<?php echo $this->url('allocatemissingmodules') ?>">Assign Missing Modules for Semester</a></li>
					<li><a href="<?php echo $this->url('allocatedmoduleassessmentcomponent') ?>">View/Edit Assigned Module Assessment Component</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Timetable<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('viewtimetable') ?>">View Student Timetable</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Student Attendance<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('editstudentattendance') ?>">Edit Attendance</a></li>
					<li><a href="<?php echo $this->url('viewconsolidatedattendancerecord') ?>">View All Consolidated Attendance</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Recheck of Marks<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('listrecheckapplicants') ?>">Update Recheck Payment</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Reassessment of Modules<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('listreassessmentapplicants') ?>">Reassessment List</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Repeat Modules<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('listrepeatmoduleapplicants') ?>">Repeat Module List</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Consolidated Marks<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('viewconsolidatedmarks') ?>">Consolidated Marks (Module)</a></li>
					<li><a href="<?php echo $this->url('viewprogrammeconsolidatedmarks') ?>">Consolidated Marks (Programme)</a></li>
					<li><a href="<?php echo $this->url('liststudentconsolidatedmarks') ?>">Consolidated Marks (Student)</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Academic Reports<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('academicresultsreports') ?>">Academic Marks Report</a></li>
			</ul>
			</li>
		</ul>
	</li>
	<li><a><i class="fa fa-book"></i>Examination<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>Examinations<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('addexamtimetable') ?>">Examination Timetable</a></li>
					<li><a href="<?php echo $this->url('viewexamtimetable') ?>">View Examination Timetable</a></li>
					<li><a href="<?php echo $this->url('assignexaminvigilator') ?>">Invigilation Duties</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Examination Codes<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('eligiblestudentlist') ?>">Eligible Student List</a></li>
					<li><a href="<?php echo $this->url('noneligiblestudentlist') ?>">Non Eligible Student List</a></li>
					<li><a href="<?php echo $this->url('generateexamcode') ?>">Generate Examination Code</a></li>
					<li><a href="<?php echo $this->url('viewexamcode') ?>">View Examination Code</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Repeat<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('backpapergeneration') ?>">Repeat Module List</a></li>
					<li><a href="<?php echo $this->url('studentbackpaper') ?>">Add Repeat Module</a></li>
					<li><a href="<?php echo $this->url('studentbackyear') ?>">Add Repeat Semester</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Results<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('declareresults') ?>">Declare Results</a></li>
			</ul>
			</li>
			<li><a href="<?php echo $this->url('addexamhall') ?>">Exam Halls</a></li>
			<li><a href="<?php echo $this->url('exammoderation') ?>">Exam Moderation</a></li>
		</ul>
	</li>
	<li><a><i class="fa fa-user"></i>Student Services<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>Student Reports<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('yearwisestudentreports') ?>">Year Wise Report</a></li>
					<li><a href="<?php echo $this->url('overallstudentreports') ?>">Overall Report</a></li>
					<li><a href="<?php echo $this->url('studentreports') ?>">Other Related Reports</a></li>
			</ul>
			</li>
			<li><a href="<?php echo $this->url('studentlists') ?>">Student Lists</a></li>
		</ul>
	</li>
	<li><a><i class="fa fa-graduation-cap"></i>Research Management<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>Research Grants<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('applyuniversitygrant') ?>">Apply for University Grants</a></li>
					<li><a href="<?php echo $this->url('grantapplicationstatus') ?>">Grant Application Status</a></li>
					<li><a href="<?php echo $this->url('applycollegegrant') ?>">Apply for College Grants</a></li>
			</ul>
			</li>
		</ul>
	</li>
</ul>
</div>
</div>
