<?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Activities';
 $this->headTitle($title);
?>
<div class="right_col" role="main">
          <div class="">
              
         <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title)?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                
                    </ul>
                 <div class="clearfix"></div>
              
                </div>
                   
                <div class="x_content">
                  <br />
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				    $awpa = $form->get('awpaobjectivesactivity');
					//get the objectives with their id
					$data = $this->selectData;
                    echo $this->form()->openTag($form);
                    echo $this->formHidden($awpa->get('id')); 
					$awpa->get('rub_objectives_id')->setValueOptions($data);
				  ?>
                
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" >Objectives <span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($awpa->get('rub_objectives_id')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">New Activity<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($awpa->get('activity_name')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">KPI<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($awpa->get('success_indicator_name')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Measurement Unit</label>
                    <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($awpa->get('unit')); ?>
                    </div>
                    <label class="control-label col-md-1 col-sm-3 col-xs-12">Baseline</label>
                    <div class="col-md-1 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($awpa->get('baseline')); ?>
                    </div>
                    <label class="control-label col-md-1 col-sm-3 col-xs-12">Target</label>
                    <div class="col-md-1 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($awpa->get('target')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Weight<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($awpa->get('weight')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12"> Target/Criteria Values</label>
                    <label class="control-label col-md-1 col-sm-3 col-xs-12">Excellent</label>
                    <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($awpa->get('excellent_rating')); ?>
                    </div>
                    <label class="control-label col-md-1 col-sm-3 col-xs-12">Very Good</label>
                    <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($awpa->get('very_good_rating')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12"> </label>
                    <label class="control-label col-md-1 col-sm-3 col-xs-12">Good</label>
                    <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($awpa->get('good_rating')); ?>
                    </div>
                    <label class="control-label col-md-1 col-sm-3 col-xs-12">Fair</label>
                    <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($awpa->get('fair_rating')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12"> </label>
                    <label class="control-label col-md-1 col-sm-3 col-xs-12">Poor</label>
                    <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($awpa->get('poor_rating')); ?>
                    </div>
                  </div>
                 
                 <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                          <?php
						   echo $this->formHidden($form->get('csrf'));
						   echo $this->formSubmit($awpa->get('submit')); 
						   echo $this->form()->closeTag(); 
                        ?>
                    </div>
                </div>
                  
          </div>
        </div>
                  </div>     
              
     <?php
 // module/Album/view/album/album/edit.phtml:

 $title = '';
 $this->headTitle($title);
?>     
              
        <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>

                <div class="x_content">


                  <table class="table   table-striped responsive-utilities jambo_table bulk_action table-bordered">
                    <thead>
                      <tr class="headings">
                        </th>
                         <th class="column-title">Sl.No.</th>
                         <th class="column-title">FYP</th>
                        <th class="column-title">Objectives </th>
                         <th class="column-title">Weightage</th>
                        <th class="column-title">KPI</th>
                         <th class="column-title">Financial Year</th>
                          <th class="column-title">Activities</th>
                      </tr>
                    </thead>

                    <tbody>
                      <tr class="even pointer">
                        <td class=" "></td>
                        <td class=" "></td>
                        <td class=" "></td>
                        <td class=" "></td>
                        <td class=" "></td>
                        <td class=" "></td>
                        <td class=" "></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
         
          </div>
        </div> 

              
              
   
            
    