<?php
 $title = 'Key Performance Indicator ( KPI)';
 $this->headTitle($title);
?>
<div class="right_col" role="main">
          <div class="">
              
         <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title)?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                
                    </ul>
                 <div class="clearfix"></div>
              
                </div>
                   
                <div class="x_content">
                  <br />
                   <?php
                   $form->prepare();
                   echo $this->form()->openTag($form);

                   echo $this->formHidden($form->get('id'));   
                   ?>
                
                <form id="demo-form2" data-parsley-validate class="form-horizontal form-label-left">
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Five Year Plan <span class="required">*</span> </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($form->get('five_year_plan')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" >Objectives <span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($form->get('financial_year')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">KPI<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($form->get('mission')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Measurement Unit</label>
                    <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($form->get('weight')); ?>
                    </div>
                    <label class="control-label col-md-1 col-sm-3 col-xs-12">Baseline</label>
                    <div class="col-md-1 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($form->get('weight')); ?>
                    </div>
                    <label class="control-label col-md-1 col-sm-3 col-xs-12">Target</label>
                    <div class="col-md-1 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($form->get('weight')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Description of KPI<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($form->get('mission')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Data Collection Method<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($form->get('mission')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Information Source<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($form->get('weight')); ?>
                    </div>
                  </div>
                </form>
                  
                 <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                              <button type="button" class="btn btn-success">Add</button>
                          </div>
                    </div>
                </div>
                    <?php echo $this->form()->closeTag(); ?>
                  
          </div>
        </div>
                  </div>     
              
     <?php
 $title = '';
 $this->headTitle($title);
?>     
              
        <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>

                <div class="x_content">


                  <table class="table   table-striped responsive-utilities jambo_table bulk_action table-bordered">
                    <thead>
                      <tr class="headings">
                        </th>
                         <th class="column-title">Sl.No.</th>
                         <th class="column-title">FYP</th>
                        <th class="column-title">Objectives </th>
                        <th class="column-title">KPI</th>
                        <th class="column-title">Descriptions</th>
                         <th class="column-title">Measurement Unit</th>
                          <th class="column-title">Baseline</th>
                        <th class="column-title">Target</th>
                         <th class="column-title">Information Source</th>
                      </tr>
                    </thead>

                    <tbody>
                      <tr class="even pointer">
                        <td class=" "></td>
                        <td class=" "></td>
                        <td class=" "></td>
                        <td class=" "></td>
                        <td class=" "></td>
                        <td class=" "></td>
                        <td class=" "></td>
                        <td class=" "></td>
                        <td class=" "></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
         
          </div>
        </div> 

              
              
   
            
    