<?php
 $title = 'Edit OVC Objectives & Weightage';
 $this->headTitle($title);
 
 $objectivesData = array();
 $i = 0;
 foreach($this->objectivesDetail as $detail){
	 $objectivesData['id'] = $detail['id'];
	 $objectivesData['rub_objectives_id'] = $detail['rub_objectives_id'];
	 $objectivesData['five_year_plan_id'] = $detail['five_year_plan_id'];
   $objectivesData['weightage'] = $detail['weightage'];
   $objectivesData['organisation_id'] = $detail['organisation_id'];
   $objectivesData['departments_id'] = $detail['departments_id'];
   $objectivesData['financial_year'] = $detail['financial_year'];
   $objectivesData['five_year_plan'] = $detail['five_year_plan'];
 } 
 
 $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));
    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}

?>
<div class="right_col" role="main">
         <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title)?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                
                    </ul>
                 <div class="clearfix"></div>
              
                </div>
                   
                <div class="x_content">
                  <br />
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				            $objectives = $form->get('ovcobjectiveweightage');
                    echo $this->form()->openTag($form);
          					//$objectives->get('rub_vision_mission_id')->setValue('1');
          					$objectives->get('id')->setValue($objectivesData['id']);
                    $objectives->get('rub_objectives_id')->setValueOptions($this->rub_objectives);
          					$objectives->get('rub_objectives_id')->setValue($objectivesData['rub_objectives_id']);
          					$objectives->get('five_year_plan_id')->setValue($objectivesData['five_year_plan']);
                    $objectives->get('weightage')->setValue($objectivesData['weightage']);
                    $objectives->get('organisation_id')->setValue($objectivesData['organisation_id']);
                    $objectives->get('departments_id')->setValueOptions($this->departments);
                    $objectives->get('departments_id')->setValue($objectivesData['departments_id']);
                    $objectives->get('financial_year')->setValue($objectivesData['financial_year']);
                    echo $this->formHidden($objectives->get('organisation_id'));
                    echo $this->formHidden($objectives->get('departments_id'));
                    echo $this->formHidden($objectives->get('financial_year'));
          					echo $this->formHidden($objectives->get('id')); 
          				  ?>   
                   <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"> Five Year Plan: <span class="required">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <?php  echo $this->formRow($objectives->get('five_year_plan_id')); ?>
                        </div>
                    </div>

                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Departments:<span class="required">*</span>
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($objectives->get('departments_id')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Objectives<span class="required">*</span>
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($objectives->get('rub_objectives_id')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Weightage</label>
                    <div class="col-md-2 col-sm-2 col-xs-12">
                          <?php  echo $this->formRow($objectives->get('weightage')); ?>
                    </div>
                  </div>
                
                  
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
						<?php
                           //need to set it as 'id' rather than Five Year Plan
						   $objectives->get('five_year_plan_id')->setValue($objectivesData['five_year_plan_id']);
						   echo $this->formHidden($objectives->get('five_year_plan_id'));
						   echo $this->formHidden($form->get('csrf'));
						   echo $this->formSubmit($objectives->get('submit')); 
						   echo $this->form()->closeTag(); 
                        ?>
                    </div>
                </div>
                    
                  
          <!-- Start of table listing mission and vision -->
        <div class="x_panel">
        	<div class="x_title">
                  <h2><?php echo $this->escapeHtml('RUB Vision and Mission'); ?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                  </ul>
                 <div class="clearfix"></div>
                </div>
               <div class="x_content">
                     <div class="table-responsive">
                      <table id="datatable-buttons" class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                            <th class=" ">Sl No</th>
                            <th class="column-title">Objectives</th>
                            <th class="column-title">Weightage</th>
                            <th class="column-title">Departments</th>
                            <th class="column-title">Action</th>
                            
                             </tr>
                        </thead>  
                        <tbody>
                         <?php $i =1; foreach ($this->objectives as $objectives) : ?>
                          <tr class="even pointer">
                            <td><?php echo $i++; ?></td>
                            <td class=" "><?php echo $this->escapeHtml($objectives['objectives']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($objectives['weightage']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($objectives['department_name']);?></td>
                            <td class=" "><a href="<?php echo $this->url('editovcobjectiveweightage', array('id' => my_encrypt($objectives['id'], $key)));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a></td>
                          </tr>
                          <?php endforeach; ?>
                      </tbody>
                      </table>
                     </div>
                   </div>
                </div>
    
          </div>
        </div> 
     </div>
   </div>
  </div>