<?php
 $title = 'Objectives & Actions';
 $this->headTitle($title);
 $five_year = array();
 $temp_message = NULL;
 foreach($this->five_year_plan as $key => $value){
	$five_year['id'] = $key; 
	$five_year['five_year_plan'] = $value; 
 } 
 if($this->flashMessenger()->hasMessages()){
    
         $temp_message = $this->flashMessenger()->getMessages();
         $temp_message = $temp_message[0];
 }
 
 $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));
    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}

?>
<div class="right_col" role="main">
         <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title)?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                    </ul>
                 <div class="clearfix"></div>
              
                </div>
                   
                <div class="x_content">
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				    $objectives = $form->get('rubobjectives');
                    $objectives->get('five_year_plan')->setValue($five_year['five_year_plan']);
                    echo $this->formHidden($objectives->get('id')); 
				  ?>

          <?php 
                            if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                                echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                $messages = $this->flashMessenger()->getMessages();
                                foreach($messages as $message) {
                                    echo '<strong>Success!</strong>'. $message;
                                }
                                echo '</div>';
                            }

                            else if ($this->message == 'Error' && $this->flashMessenger()->hasMessages()) {
                                echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                $messages = $this->flashMessenger()->getMessages();
                                foreach($messages as $message) {
                                    echo '<strong>Failure!</strong>'. $message;
                                }
                                echo '</div>';
                            }

                            else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                                echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                $messages = $this->flashMessenger()->getMessages();
                                foreach($messages as $message) {
                                    echo '<strong>Failure!</strong>'. $message;
                                }
                                echo '</div>';
                            }
                        ?>
                
                    <p><i>***This is initial adding of RUB Objectives. When you add objective please enter the objective's weightage that is relevant to colleges PRESIDENT since at one go, it add the weightage of objective relevant for colleges president based on financial years within the particular five year plan. It means all financial years objectives are added at one go.</i></p> 
                  <div class="row">    
                   <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"> Five Year Plan: <span class="required">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <?php  echo $this->formRow($objectives->get('five_year_plan')); ?>
                        </div>
                    </div>
                  </div>
                  <div class="row"> 
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Objectives<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($objectives->get('objectives')); ?>
                    </div>
                  </div>
                  </div>
                  <div class="row"> 
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Weightage</label>
                    <div class="col-md-2 col-sm-2 col-xs-12">
                          <?php  echo $this->formRow($objectives->get('weightage')); ?>
                    </div>
                    <label class="control-label col-md-1 col-sm-3 col-xs-12">Objectives for </label>
                    <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php  echo $this->formRow($objectives->get('remarks')); ?>
                    </div>
                  </div>
                  </div>
                  
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
						<?php
                           //need to set it as 'id' rather than Five Year Plan
						   $objectives->get('five_year_plan')->setValue($five_year['id']);
						   echo $this->formHidden($objectives->get('five_year_plan'));
						   echo $this->formHidden($form->get('csrf'));
						   echo $this->formSubmit($objectives->get('submit')); 
						   echo $this->form()->closeTag(); 
                        ?>
                    </div>
                </div>
                </div>
                </div>
                </div>
                    
                  
          <!-- Start of table listing mission and vision -->
        <div class="x_panel">
        	<div class="x_title">
                  <h2><?php echo $this->escapeHtml('RUB Objectives'); ?><small> (Weightages in lists are applicable for VC and College Presidents)</small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                  </ul>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                     <div class="table-responsive">
                      <table class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                            <th class=" ">Sl No</th>
                            <th class="column-title">Objectives</th>
                            <th class="column-title">Weightage</th>
                            <th class="column-title">College/OVC</th>
                            <th class="column-title">Action</th>
                            
                             </tr>
                        </thead>  
                        <tbody>
                      <tr>
                         <?php $i =1; foreach ($this->objectives as $objectives) : ?>
                          <tr class="even pointer">
                            <td><?php echo $i++; ?></td>
                            <td class=" "><?php echo $this->escapeHtml($objectives['objectives']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($objectives['weightage']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($objectives['remarks']);?></td>
                            <td class=" "><a href="<?php echo $this->url('editobjectives', array('id' => my_encrypt($objectives['id'], $key)));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a></td>
                          </tr>
                          <?php endforeach; ?>
                      </tr>
                      </tbody>
                      </table>
                     </div>
                   </div>
                </div>
    
          </div>
        </div> 
      </div>
    </div>