<?php
 $title = 'Edit Community Service Details';
 $this->headTitle($title);

 $community_service = array();
 foreach($this->serviceDetails as $details){
  $community_service = $details;
 }
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    $registrant = $form->get('communityservice');
                    $registrant->get('id')->setValue($this->id);
                    $registrant->get('job_applicant_id')->setValue($community_service['job_applicant_id']);
                    $registrant->get('service_name')->setValue($community_service['service_name']);
                    $registrant->get('remarks')->setValue($community_service['remarks']);
                    $service_date = explode("-", $community_service['service_date']);
                    $registrant->get('service_date')->setValue($service_date[01].'/'.$service_date[02].'/'.$service_date[00]);
                    date_default_timezone_set("Asia/Thimphu");
                    $registrant->get('last_updated')->setValue(date("Y-m-d h:i:s"));
                    $registrant->get('submit')->setValue('Update');
                    echo $this->formHidden($registrant->get('id'));
                     echo $this->formHidden($registrant->get('last_updated'));
                   echo $this->formHidden($registrant->get('job_applicant_id'));
                  ?>  
                <div class="row">    
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Community Service Name:<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($registrant->get('service_name')); ?>
                    </div>
                   </div>
                   <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Date:<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($registrant->get('service_date')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Remarks:</label>
                    <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($registrant->get('remarks')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Supporting File (Optional):</label>
                    <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                    <?php  
                    if($community_service['supporting_file']){?>
                      <a href="<?php echo $this->url('downloadapplicantcommunityfile', array('filename'=> 'supporting_file'.$community_service['id'])); ?>" class="btn btn-primary btn-xs"><i class="fa fa-download"></i> Download and View</a>
                    <?php } else{
                      echo $this->formRow($registrant->get('supporting_file')); 
                    }
                    ?>
                    </div>
                  </div>
                </div> 
                  
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                    <?php
                       echo $this->formHidden($form->get('csrf'));
                       echo $this->formSubmit($registrant->get('submit')); 
                        ?>
                      </div>
                    </div>
               </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                </div>
              </div>
        
        <!-- Start of table listing budget ledgers -->
             </div>
        
        
    
          </div>
        </div> 
     </div>
