<?php
 $title = 'New Registered Student List';
 $this->headTitle($title);

 //get student list in an array
 $studentName = array();
 $studentCid = array();
 $studentDOB = array();
 $studentGender = array();
 $studentNo = array();
 $programmeName = array();
 $admissionYear = array();
 $studentType = array();
 $studentId = array();

 $i=1;
 $j=1;
 foreach($this->newStudentList as $student){
    $studentIndexNo[$i] = $student['twelve_indexnumber'];
    $studentName[$i] = $student['first_name'].' '.$student['middle_name'].' '.$student['last_name'];
    $studentCid[$i] = $student['cid'];
    $studentDOB[$i] = $student['date_of_birth'];
    $studentGender[$i] = $student['gender'];
    $studentNo[$i] = $student['contact_no'];
    $programmeName[$i] = $student['programme_name'];
    $admissionYear[$i] = $student['admission_year'];
    $studentType[$i] = $student['student_type'];
    $studentId[$i] = $student['id'];
    $i++;
 }

  $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));

    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}

?>

 <div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
            
                <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                     <div class="clearfix"></div>
                    </div>
                    <br/>
                     
                    <?php 
                    if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                        echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                        echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                        $messages = $this->flashMessenger()->getMessages();
                        foreach($messages as $message) {
                            echo '<strong>Success!</strong>'. $message;
                        }
                        echo '</div>';
                    }

                    else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                        echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                        echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                        $messages = $this->flashMessenger()->getMessages();
                        foreach($messages as $message) {
                            echo '<strong>Failure!</strong>'. $message;
                        }
                        echo '</div>';
                    }
                ?>

                    <div class="col-md-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2><?php echo $this->escapeHtml("Search for List of new Student list to report")?></h2>
                            <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                            </ul>
                            <div class="clearfix"></div>
                  
                        </div>
                       
                        <div class="x_content">
                            <h5><i>*(In order to search the list of new student registered and to click report, you have to select programme from drop down list and click on search button to display the list of new registered students with respect to the programme you select. It will display only the list those who haven't reported to the college.)<br />
                                        **When list display, by default all student are checked which means all are reported. If there is student who didn't report then uncheck the checkbox and  click on submit button. It will change the status to Reported for those who you have checked** </i></h5>
                                  <br />
                            <?php
                            // Opening of the form tag
                            $form->prepare();
                            echo $this->form()->openTag($form);
                            ?>
                        
                            <div class="row">
                                <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Programme</label>
                                    <?php echo $this->formRow($form->get('programmes_id')); ?>
                                </div>
                            </div>                         
                            <div class="row">
                                <div class="ln_solid"></div>
                                <div class="form-group">
                                    <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                                      <?php
                                       echo $this->formHidden($form->get('csrf'));
                                       echo $this->formSubmit($form->get('submit')); 
                                       echo $this->form()->closeTag(); 
                                    ?>
                                </div>
                            </div>                          
                        </div>
                    </div>
                </div>   
                              
                          
                        <div class="col-md-12 col-sm-12 col-xs-12">
                          <div class="x_panel">
                            <div class="x_title">
                              <h2><?php echo $this->escapeHtml("List of New Registered Student(s)"); ?></h2>
                              <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                </li>
                              </ul>
                              <div class="clearfix"></div>
                              <h5><i>List of Students those who haven't reported yet. Once they report, their name list will be not found if you search also. It will list only the reporting status is <b>"Pending". Please uncheck for those who haven't report before you click on "Submit" Button</b> </i></h5>
                                  <br />
                            </div>
                            <?php
                               // if($changeProgrammeForm != NULL){
                       
                                // Opening of the form tag
                               $reportNewStudentForm->setAttribute('action', $this->url('reportnewstudent', array('action' => 'reportNewStudent')));
                                $form->prepare();
                                echo $this->form()->openTag($reportNewStudentForm);
                                $reportNewStudentForm->get('studentCount')->setValue($this->studentCount);
                                $reportNewStudentForm->get('organisation_id')->setValue($this->organisation_id);
                                $reportNewStudentForm->get('programmes_id')->setValue($this->stdProgramme);
                                echo $this->formHidden($reportNewStudentForm->get('organisation_id'));
                                echo $this->formHidden($reportNewStudentForm->get('programmes_id'));
                                echo $this->formHidden($reportNewStudentForm->get('id'));  
                                echo $this->formHidden($reportNewStudentForm->get('studentCount'));                            
                        ?>
                            <div class="x_content">
                              <div  class="table-responsive">
                                <table class="table table-striped responsive-utilities jambo_table bulk_action table-bordered">
                                  <thead>
                                    <tr class="headings">
                                      <th class="column-title" rowspan="2">Sl No </th>
                                      <th class="column-title" rowspan="2">Class 12 Index Number </th>
                                      <th class="column-title" rowspan="2">Student Name </th>
                                      <th class="column-title" rowspan="2">CID </th>
                                      <th class="column-title" rowspan="2">DOB </th>
                                      <th class="column-title" rowspan="2">Gender </th>
                                      <th class="column-title" rowspan="2">Phone No </th>
                                      <th class="column-title" rowspan="2">Programme </th>
                                      <th class="column-title" rowspan="2">Admission Year </th>
                                      <th class="column-title" rowspan="2">Scholarship Type </th>
                                      <th class="column-title" colspan="2" align="center">Action</th>
                                    </tr>
                                    <tr>
                                          <th>Report <small>(Check only the reported one)</small></th>
                                          <th>View</th>
                                        </tr>
                                  </thead>
              
                                  <tbody>
                                  <?php for($i = 1; $i<=$this->studentCount; $i++) {?>
                                    <tr class="even pointer">
                                      <td class=" "><?php echo $i; ?></td>
                                      <td class=" "><?php echo $studentIndexNo[$i]; ?></td>
                                      <td class=" "><?php echo $studentName[$i]; ?></td>
                                      <td class=" "><?php echo $studentCid[$i]; ?></td>
                                      <td class=" "><?php echo $studentDOB[$i]; ?></td>
                                      <td class=" "><?php echo $studentGender[$i]; ?></td>
                                      <td class=" "><?php echo $studentNo[$i]; ?></td>
                                      <td class=" "><?php echo $programmeName[$i]; ?></td>
                                      <td class=" "><?php echo $admissionYear[$i]; ?></td>
                                      <td class=" "><?php echo $studentType[$i]; ?></td>
                                      <td class=" "><?php echo $this->formRow($reportNewStudentForm->get('student_'.$i)); ?></td>
                                      <td class=" last"> <a href="<?php echo $this->url('new-registered-student-details', array('id' => my_encrypt($studentId[$i], $key)));?>" class="btn btn-primary btn-xs"><i class="fa fa-eye"></i> View </a>

                                      
                                    </tr>
                                     <?php  }?>
                                  </tbody>
                                </table>
                              </div>
                            </div>
                            <?php
                            echo $this->formHidden($reportNewStudentForm->get('csrf'));
                            echo $this->formSubmit($reportNewStudentForm->get('submit'));
                            echo $this->form()->closeTag();
                            ?>
                          </div>
                        </div>
                        </div>
                      </div>
                  </div>
                </div>
              
