<?php
 $title = 'Workshop, Seminar, Field Visit & Other Details';
 $this->headTitle($title);

   $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    //IDEA-CBC
    //Original
    //$iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('aes-256-cbc'));

    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));

    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}
 ?>
<div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                  </div>
                    
                  <div class="x_content">
                    <br/>
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    $training = $form->get('employeeworkshop');
                    $training->get('source_of_funding')->setValueOptions($this->funding_source);
					         $training->get('type')->setValueOptions($this->training_type);
                    $training->get('institute_country')->setValueOptions($this->institute_country);
                    echo $this->form()->openTag($form);
                    $training->get('hrd_type')->setValue('Adhoc Training');
                    echo $this->formHidden($training->get('id'));
          					$training->get('proposing_agency')->setValue($this->proposing_agency);
          					echo $this->formHidden($training->get('proposing_agency'));
                    echo $this->formHidden($training->get('hrd_type'));
				              ?>  

                      <?php 
                      if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                          echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                          echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                          $messages = $this->flashMessenger()->getMessages();
                          foreach($messages as $message) {
                              echo '<strong>Success!</strong>'. $message;
                          }
                          echo '</div>';
                      }

                      else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                          echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                          echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                          $messages = $this->flashMessenger()->getMessages();
                          foreach($messages as $message) {
                              echo '<strong>Failure!</strong>'. $message;
                          }
                          echo '</div>';
                      }
                      ?>
                      
                    <div class="row">
                    <div class="form-group">  
                       <label class="control-label col-md-2 col-sm-2 col-xs-12">Training Type<span class="required">*</span></label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php  echo $this->formRow($training->get('type')); ?>
                        </div>
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Source of Funding<span class="required">*</span></label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php  echo $this->formRow($training->get('source_of_funding')); ?>
                        </div>
                    </div>
                    </div>
                    <div class="row"> 
                    <br />
                	<h4><i>Workshop/Seminar Details Details:</i></h4>
                    <br />
                    <div class="row">
                    <div class="form-group">  
                       <label class="control-label col-md-2 col-sm-2 col-xs-12">Workshop/Seminar  Title<span class="required">*</span></label>
                       <div class="col-md-8 col-sm-8 col-xs-12">
                          <?php  echo $this->formRow($training->get('title')); ?>
                        </div>
                    </div>
                    </div>
                    <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Workshop/Seminar Start Date- End Date<span class="required">*</span></label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php  echo $this->formRow($training->get('workshop_start_date')); ?>
                        </div>
                    </div>
                    </div>
                    <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Remarks</label>
                       <div class="col-md-8 col-sm-8 col-xs-12">
                          <?php  echo $this->formRow($training->get('remarks')); ?>
                        </div>
                    </div>
                    </div>
                    <div class="row"> 
                    <br />
                	<h4><i>Institute Details:</i></h4>
                    <br />
                    <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Institute/University Name<span class="required">*</span></label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php  echo $this->formRow($training->get('institute_name')); ?>
                        </div>
                       <label class="control-label col-md-2 col-sm-2 col-xs-12">Training/Study Location<span class="required">*</span></label>
                       <div class="col-md-3 col-sm-3 col-xs-12">
                          <?php  echo $this->formRow($training->get('institute_country')); ?>
                        </div>
                    </div>
                    </div>
                    <div class="row">
                    <div class="form-group">  
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Training/Study Address<span class="required">*</span></label>
                       <div class="col-md-8 col-sm-8 col-xs-12">
                          <?php  echo $this->formRow($training->get('institute_location')); ?>
                        </div>
                    </div>
                    </div>
                   
                    <div class="ln_solid"></div>
                    <div class="row">
                    <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <?php
						 echo $this->formHidden($form->get('csrf'));
						 echo $this->formSubmit($training->get('submit')); 
                        ?>
                        </div>
                    </div>
                    </div>
                   <?php
                    echo $this->form()->closeTag();
                    ?>
                       
                    
                   </div>
                </div>
              </div>
           </div>

           <?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Short Term Adhoc Trainings';
 $this->headTitle($title);
?>     
            <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                  <h5><i> (Lists of Short Term Adhoc Trainings)</i></h5>
                </div>
                <div class="x_content">
                    <div class="table-responsive">
                        <table id="datatable-buttons" class="table table-striped responsive-utilities jambo_table bulk_action table-bordered">
                            <thead>
                                <tr class="headings">
                                    <th class="column-title">Sl. No</th>
                                    <th class="column-title">Field Study </th>
                                    <th class="column-title">Institute Name </th>
                                    <th class="column-title">Institute Location </th>
                                    <th class="column-title">Training From </th>
                                    <th class="column-title">Training To </th>
                                    <th class="column-title">Action</th>
                                </tr>
                            </thead>

                            <tbody>
                              <?php 
                              $i=1;
                              foreach($this->trainingList as $list):?>
                                <tr>
                                  <td class=" " width="8%"><?php echo $i; ?></td>
                                  <td class=" "><?php echo $list['title']; ?></td>
                                  <td class=" "><?php echo $list['institute_name']; ?></td>
                                  <td class=" "><?php echo $list['institute_location']; ?></td>
                                  <td class=" "><?php echo $list['workshop_start_date']; ?></td>
                                  <td class=" "><?php echo $list['workshop_end_date']; ?></td>
                                  <td class=" " width="10%">
                                    <a href="<?php echo $this->url('shorttermadhocdetails', array('id' => my_encrypt($list['id'], $key))); ?>" class="btn btn-info btn-xs"><span class="fa fa-eye"> View Details</span></a>
									<a href="<?php echo $this->url('editshorttermadhoctraining', array('id' => my_encrypt($list['id'], $key))); ?>" class="btn btn-primary btn-xs"><span class="fa fa-pencil"> Edit</span></a>
									<a href="<?php echo $this->url('deleteshorttermadhoctraining', array('id' => my_encrypt($list['id'], $key)));?>" class="btn btn-danger btn-xs"><span class="fa fa-trash"> Delete</span></a>
                                  </td>
                                </tr>
                                <?php 
                                $i++;
                              endforeach;
                                ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

         </div>
	  </div>
    </div>
  </div>
</div>
  