<?php

 $title = 'Add Student Category';
 $this->headTitle($title);

  $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    //IDEA-CBC
    //Original
    //$iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('aes-256-cbc'));

    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));

    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}
?>

<div class="right_col" role="main">
    <div class=" ">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                    </ul>
                    <div class="clearfix"></div>
                </div><!--end of x-title-->
                <h5><i>Below form is to add student category. Please take care while you are adding new student category. There should not have duplicate student category. Field with * are compulsory to fill.</i></h5>
                </br>
                <?php 
                    if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                        echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                        echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                        $messages = $this->flashMessenger()->getMessages();
                        foreach($messages as $message) {
                            echo '<strong>Success!</strong>'. $message;
                        }
                        echo '</div>';
                    }

                    else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                        echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                        echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                        $messages = $this->flashMessenger()->getMessages();
                        foreach($messages as $message) {
                            echo '<strong>Failure!</strong>'. $message;
                        }
                        echo '</div>';
                    }
                ?> 
                <div class="x_content">   
                    <?php
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        $category = $form->get('studentcategory');
                        echo $this->form()->openTag($form);
                     ?>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Student Category<span class="required">*</span></label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <?php  echo $this->formRow($category->get('student_category')); ?>
                                    </div>
                            </div>        
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Description</label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <?php  echo $this->formRow($category->get('description')); ?>
                                    </div>
                            </div>    
                            <div class="form-group">
                            <div class="ln_solid"></div>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <?php  echo $this->formHidden($form->get('csrf')); ?>
                                            <?php  echo $this->formSubmit($category->get('submit')); ?>
                                        </div>
                                </div>
                            </div>
                    <?php
                        echo $this->form()->closeTag();
                    ?>
                </div>
            </div>
<?php
 // module/EmployeeDetail/view/employee-detail/employee-detail/emppersonaldetail.phtml:

 $title = 'Student Category';
 $this->headTitle($title);
 
 ?>

            <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                        <div class="clearfix"></div>
                </div>
                <h5><i>Following are the list of student category added</i></h5>
                </br>
                    <div class="x_content">
                        <div class="table-responsive">
                            <table class="table table-striped jambo_table bulk_action">
                                <thead>
                                    <tr class="headings">
                                        <th class="column-title">Sl.No. </th>
                                        <th class="column-title"> Student Category </th>
                                        <th class="column-title">Description</th>
                                        <th class="column-title">Action</th>
                                    </tr>
                                </thead>
                                <?php $i=1; ?>
                                <?php foreach ($this->Categories as $cat) : ?>
                                    <tr class="even pointer">
                                        <td class=" "><?php echo $i; ?></td>
                                        <td class=" "><?php echo $this->escapeHtml($cat->getStudent_Category());?></td>
                                        <td class=" "><?php echo $this->escapeHtml($cat->getDescription());?></td>
                                        <td class=" "><a href="<?php echo $this->url('edit-student-category', array('id' => my_encrypt($cat->getId(), $key))); ?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit</a>
                                    </td>
                                    </tr>
                                <?php $i++; ?>
                                <?php endforeach; ?>
                            </table>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</div>