<?php
 $title = 'Activate HR Proposal';
 $this->headTitle($title);
 $date_range = date("m-d-Y", strtotime($this->dateDetails->getStart_Date())).' - '.date("m-d-Y",strtotime($this->dateDetails->getEnd_Date()));
 
 $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));
    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}

 
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				    $activation = $form->get('hractivation');
					$activation->get('id')->setValue($this->dateDetails->getId());
					$activation->get('hr_proposal_type')->setValue($this->dateDetails->getHr_Proposal_Type());
					$activation->get('five_year_plan')->setValue($this->dateDetails->getFive_Year_Plan());
					$activation->get('date_range')->setValue($date_range);
                    echo $this->formHidden($activation->get('id')); 
					echo $this->formHidden($activation->get('five_year_plan')); 
				  ?>  
                <div class="row">    
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">HR Proposal Type</label>
                    <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($activation->get('hr_proposal_type')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Start to End Date For Proposal Submission </label>
                    <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($activation->get('date_range')); ?>
                    </div>
                  </div>
                </div> 
                  
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
						<?php
                           
						   echo $this->formHidden($form->get('csrf'));
						   echo $this->formSubmit($activation->get('submit')); 
                        ?>
                    	</div>
                    </div>
               </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                </div>
              </div>
       <!-- Start of table listing activation dates -->
        <div class="x_panel">
                <div class="x_content">
                     <div class="table-responsive">
                      <table class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Sl. No</th>
                            <th class="column-title">HR Proposal Type</th>
                            <th class="column-title">Start Date</th>
                            <th class="column-title">End Date</th>
                            <th class="column-title">Action</th>
                            
                             </tr>
                        </thead>  
                        <tbody>
                      <tr>
                         <?php $i = 1; foreach($this->activationDates as $date) : ?>
                          <tr class="even pointer">
                            <td class=" "><?php echo $i++;?></td>
                            <td class=" "><?php echo $this->escapeHtml($date->getHr_Proposal_Type());?></td>
                            <td class=" "><?php echo $this->escapeHtml($date->getStart_Date());?></td>
                            <td class=" "><?php echo $this->escapeHtml($date->getEnd_Date());?></td>
                            <td class=" last"><a href="<?php echo $this->url('editactivationdate', array('id' => my_encrypt($date->getId(), $key)));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a></td>
                          </tr>
                          <?php endforeach; ?>
                      </tr>
                      </tbody>
                      </table>
                     </div>
                  </div>
               </div>
             </div>    
          </div>
        </div> 
     </div>
