<?php

 $title = 'HRD Plan Approval Lists (RUB / OVC HRO)';
 $this->headTitle($title);
 
 $key = $this->keyphrase;
 function my_encrypt($data, $key) {
    // Remove the base64 encoding from our key
    $encryption_key = base64_decode($key);
    // Generate an initialization vector
    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('BF-CFB'));
    // Encrypt the data using AES 256 encryption in CBC mode using our encryption key and initialization vector.
    $encrypted = openssl_encrypt($data, 'BF-CFB', $encryption_key, 0, $iv);
    // The $iv is just as important as the key for decrypting, so save it with our encrypted data using a unique separator (::)
    return bin2hex(base64_encode($encrypted . '::' . $iv));
}

?>

 <div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                     <div class="clearfix"></div>
                    </div>
                    <br/>
                        <!-- List Approvals-->
                        <div class="col-md-12 col-xs-12">
                          <div class="x_panel">
                            <div class="x_title">
                              <h2><?php echo $this->escapeHtml("Search By OVC/College")?></h2>
                                <ul class="nav navbar-right panel_toolbox">
                                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                  </li>
                                </ul>
                             <div class="clearfix"></div>
                          
                            </div>
                               
                            <div class="x_content">
                               <?php
                                // Opening of the form tag
                                $form->prepare();
                                echo $this->form()->openTag($form);
                                $form->get('organisation_id')->setValueOptions($this->organisationList);
                              ?>
                            
                              <div class="row">
                                  <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                                    <label>Student Name</label>
                                    <?php echo $this->formRow($form->get('organisation_id')); ?>
                                  </div>
                               </div>
                             
                             <div class="row">
                                <div class="ln_solid"></div>
                                <div class="form-group">
                                    <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                                      <?php
                                       echo $this->formHidden($form->get('csrf'));
                                       echo $this->formSubmit($form->get('submit')); 
                                       echo $this->form()->closeTag(); 
                                    ?>
                                </div>
                            </div>
                              
                          </div>
                        </div>
                       </div> 
                <div class="col-md-12 col-sm-12 col-xs-12">      
                <div class="x_panel">
                     <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                     <div class="clearfix"></div>
                    </div><br/>
                    <?php if($this->message == NULL && $this->flashMessenger()->hasMessages()) {
							echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
							echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
							$messages = $this->flashMessenger()->getMessages();
							foreach($messages as $message) {
								echo '<strong>Success!</strong>'. $message;
							}
							echo '</div>';
                    	} else if($this->message =='Failure' && $this->flashMessenger()->hasMessages()) {
                            echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                            echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                            $messages = $this->flashMessenger()->getMessages();
                            foreach($messages as $message) {
                                echo '<strong>Warning!</strong>'. $message;
                            }
                            echo '</div>';
                     }  ?>
                    <br/>
                     <div class="table-responsive">
                      <table id="datatable-buttons" class="table table-striped jambo_table table-bordered">
                        <thead>
                          <tr class="headings">     
                            <th class="column-title">Sl.No. </th>
                            <th class="column-title">Working Agency </th>
                            <th class="column-title">Course Title </th>
                        	<th class="column-title">Slots</th>
                        	<th class="column-title">Duration</th>
                            <th class="column-title">Funding Source</th>
                            <th class="column-title">Target Group</th>
                            <th class="column-title"></th>
                            <th class="column-title"></th>
                          </tr>
                        </thead>
                        <tbody>
                        <?php $i = 1; foreach ($this->approvals as $approval) : ?>
                            <tr>
                                  <td class=" "><?php echo $this->escapeHtml($i++);?></td>
                                  <td class=" "><?php echo $this->escapeHtml($this->organisationList[$approval->getWorking_Agency()]);?></td>
                                   <td class=" "><?php echo $this->escapeHtml($approval->getCourse_Title());?></td>
                                   <td class=" "><?php echo $this->escapeHtml($approval->getTotal_No_Slots());?></td>
                                   <td class=" "><?php echo $this->escapeHtml($approval->getDuration());?></td>
                                   <td class=" "><?php echo $this->escapeHtml($approval->getSource_Of_Funding());?></td>
                                   <td class=" "><?php echo $this->escapeHtml($approval->getTarget_Group());?></td>
                                   <td><a href="<?php echo $this->url('viewhrdapproval', array('id' => my_encrypt($approval->getId(), $key)));?>" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i>View</a>
                                   
                                   <a href="<?php echo $this->url('edithrdapproval', array('id' => my_encrypt($approval->getId(), $key)));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a></td>
                                <td><a href="<?php echo $this->url('approvehrdproposal', array('id' => my_encrypt($approval->getId(), $key)));?>" class="btn btn-success btn-xs">Approve</a>
                                   <a href="<?php echo $this->url('rejecthrdproposal', array('id' => my_encrypt($approval->getId(), $key)));?>" class="btn btn-danger btn-xs">Reject</a></td>
                                   
                            </tr>
                         <?php endforeach; ?>
                        </tbody>
                      </table>
                        <div class="ln_solid"></div>

               </div>
            </div>
          </div>
        </div>
      </div>
     </div>
    </div>
</div>
</div>
          
                     