<?php
/**
 * 
 * View -- of Accounts/MasterController/addbankreftypeAction
 * 
 */
 $title = 'Add Bank Reference Type';
 $this->headTitle($title);
?>
<div class="right_col" role="main">
    <div class="">
        <div class="col-md-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
					<ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </ul>
					<div class="clearfix"></div>
                </div><!--end of x-title-->
                <div class="pull-right"></div>			
				<?php echo $this->partial('accounts/master/partial.phtml', array('active' => 'bankref')); ?>
				<div class="x_content">
					<form id="form" method="post" action="<?php echo $this->url('master', array('action' => 'addbankreftype')); ?>" enctype="multipart/form-data" >
						<div class ="row">
                            <div class="col-lg-2"></div>	
                            <div class ="col-xs-8">	
								<div class="form-group col-lg-6">
								<label for="bankref" class="control-label"> Bank Reference Type</label>
								<input type="text" class="form-control" name="bankref" id="bankref" placeholder="Enter Bank Reference Type" required>
							    </div>
						    </div>
							<div class="col-lg-2"></div>
						</div>
                        <div class ="x_title"></div>
						<div class ="row">
						    <div class ="col-lg-2"></div>
						    <div class ="col-lg-8">
							    <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
                                <button type="reset" class="btn btn-warning" onclick="javascript:history.back();"><i class="fa fa-times"></i> Cancel </button>    
							</div>
						    <div class ="col-lg-2"></div>
						</div>
					</form>
                </div>  
            </div>  
        </div>  
    </div>  
</div>  
<script>
	$('document').ready(function(){
		$('form').formValidation({
			excluded: ':disabled',
			message: 'Please enter a value.',
			fields: {
				bankref: {
					validators: {
						notEmpty: {
							message: 'Please provide bank reference type.'
						}
					}
				},
			}
		});
	});
</script>







