<?php
/**
 * 
 *  Hr/MasterController/addpayslabAction
 * 
 */
 $title = 'Add Pay Slab';
 $this->headTitle($title);
?>
<div class="right_col" role="main">
    <div class="">
        <div class="col-md-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
					<ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </ul>
					<div class="clearfix"></div>
                </div><!--end of x-title-->
                <div class="pull-right"></div>			
				<?php echo $this->partial('accounts/master/partial.phtml', array('active' => 'payslab')); ?>
				<div class="x_content">
                    <form role="form" action="<?php echo $this->url('master', array('action' => 'addpayslab')); ?>" enctype="multipart/form-data" method="post" >
						<div class ="row">
                            <div class ="col-lg-2"></div>
                            <div class ="col-lg-8">							
								<div class="form-group col-lg-6">
									<label for="pay_head" class="control-label">Pay Head</label>
									<select class="form-control" style="width:100%" placeholder="Select Pay Head Type" name="pay_head" id="pay_head" required onchange>
										<option value="">-Select pay head-</option>
											<?php
											foreach ($payhead as $rowset):
											?>
												<?php if($rowset['type']==3): ?>
													<option value="<?php echo $rowset['id'];?>">
													<?php echo $rowset['pay_head']; ?>
												</option>
											<?php 
													endif;
												endforeach;
											?>					
									</select>
								</div>
								<div class="form-group col-lg-6">
									<label for="formula" class="control-label"> Formula</label>
									<div class="radio">
										<label>
											<input type="radio" name="formula" id="formula" value="1" required>
											&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Yes
										</label>
										<label>
											<input type="radio" name="formula" id="formula" value="0" required>
											&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;No
										</label>
									</div>
								</div>
								<div class="form-group">
									<label>Monthly Salary Range:</label>
								</div>
								<div class="form-group col-lg-6">
									<label for="from" class="control-label">From</label>
									<input type="text" class="form-control" name="from" id="from" placeholder="From" required/> 
								</div>
								<div class="form-group col-lg-6">
									<label for="to" class="control-label">To</label>
									<input type="text" class="form-control" name="to" id="to" placeholder="To" required/>
								</div>
								<div class="form-group col-lg-4">
									<div class="form-group" id="rate_container">
										<label for="rate" class="control-label">Rate</label>
										<input type="text" class="form-control" name="rate" id="rate" placeholder="Rate" required/> 
									</div>
								</div>
								<div class="form-group col-lg-4">
									<div class="form-group" id="base_container">
										<label for="base" class="control-label">Base</label>
										<input type="text" class="form-control" name="base" id="base" placeholder="Base" required/> 
									</div>
								</div>
								<div class="form-group col-lg-4">
									<div class="form-group" id="value_container">
										<label for="value" class="control-label">Value</label>
										<input type="text" class="form-control" name="value" id="value" placeholder="Value" required/> 
									</div>
								</div>
							</div>
							<div class="col-lg-2"></div>
						</div>
						<div class ="x_title"></div>
						<div class ="row">
						    <div class ="col-lg-2"></div>
						    <div class ="col-lg-8">
							    <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
                                <button type="reset" class="btn btn-warning" onclick="javascript:history.back();"><i class="fa fa-times"></i> Cancel </button>    
							</div>
						    <div class ="col-lg-2"></div>
						</div>
					</form>
                </div>  
            </div>  
        </div>  
    </div>  
</div>  
<script>
	$('document').ready(function(){
		$('form select').chosen({ allow_single_deselect: true });
		$('form').formValidation({
			excluded: ':disabled',
			message: 'Please enter a value.',
			fields: {
				pay_head: {
					validators: {
						notEmpty: {
							message: 'Please select pay head.'
						}
					}
				},
				from: {
					validators: {
						notEmpty: {
							message: 'Provide min limit of range'
						},
						regexp: {
		                    regexp: /^\d*\.?\d*$/,
		                    message: 'Please enter valid amount'
		                }		
					}
				},
				to: {
					validators: {
						notEmpty: {
							message: 'Provide max limit of range.'
						},	
						regexp: {
		                    regexp: /^\d*\.?\d*$/,
		                    message: 'Please enter valid amount'
		                }	
					}
				},
				formula: {
					validators: {
						notEmpty: {
							message: 'Is there formula for this slab?'
						}
					}
				},
				rate: {
					validators: {
						notEmpty: {
							message: 'Provide rate.'
						},
						regexp: {
		                    regexp: /^\d*\.?\d*$/,
		                    message: 'Please enter valid amount'
		                }
					}
				},
				base: {
					validators: {
						notEmpty: {
							message: 'Please provide base amount.'
						},
						regexp: {
		                    regexp: /^\d*\.?\d*$/,
		                    message: 'Please enter valid amount'
		                }	
					}
				},
				value: {
					validators: {
						notEmpty: {
							message: 'Please enter amount.'
						},
						regexp: {
		                    regexp: /^\d*\.?\d*$/,
		                    message: 'Please enter valid amount'
		                }		
					}
				},
			}
		});

		$("input[name='formula']").change(function(e){
		    if($(this).val() == '1') {
		        $("#value").prop('disabled','disabled');
		        $("#rate").prop('disabled',false);
		        $("#base").prop('disabled',false);
		    } else {
		    	$("#rate").prop('disabled','disabled');
		        $("#base").prop('disabled','disabled');
		        $("#value").prop('disabled',false);
		    }

		});
	});
</script>






		