<?php 
$title = 'Payment Modes';
$this->headTitle($title);
?>
<div class="right_col" role="main">
	<div class=" ">
		<div class="col-md-12 col-xs-12">
			<div class="x_panel">
				<div class="x_title">
					<h2><?php echo $this->escapeHtml($title);?></h2>
					<ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </ul>
					<div class="clearfix"></div>
				</div>
						
				<div class="pull-right"></div>			
                <a class="pull-right btn btn-primary" href="<?php echo $this->url('master', array('action'=>'addbankreftype'));?>">
				<span class="white"><i class="fa fa-plus"></i> <span class="hidden-sm hidden-xs">&nbsp;Add  Bank Reference Type </span></span>
				</a>
				<?php echo $this->partial('accounts/master/partial.phtml', array('active' => 'bankref')); ?>
				<div class="x_content">
					<div class="table-responsive">
						<table id="datatable" class="table table-striped jambo_table bulk_action">
							<thead>
								<tr class="headings">
									<th class="column-title">Sl No</th>
									<th class="column-title">Bank Reference Type</th>
									<th class="column-title">Action</th>
								</tr>
							</thead>
							<tbody>
							<?php
								$i = 1; 
								foreach ($this->bankref as $br):
							?>
									<tr class="even pointer">
										<td><?php echo $i++; ?> </td>
										<td><b><?php echo $br['bank_ref_type'];?></b></td> 
										<td><div class="btn-group">
											<a class="btn btn-xs btn-info " href="<?php echo $this->url('master', array('action'=>'editbankreftype', 'id'=>$br['id']));?>" >
												<span class="white"><i class="fa fa-pencil bigger-120"> Edit</i> <span class="hidden-lg hidden-xs"></span></span>
											</a>
										</div></td>								
									</tr>
							<?php endforeach;?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>