<?php
/**
 * 
 * View -- of Hr/MasterController/payheadAction
 * 
 */
	$this->headTitle($this->title);
?>
<div class="right_col" role="main">
	<div class=" ">
		<div class="col-md-12 col-xs-12">
			<div class="x_panel">
				<div class="x_title">
					<h2><?php echo $this->escapeHtml($title);?></h2>
					<ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </ul>
					<div class="clearfix"></div>
				</div>
				<div class="pull-right tableTools-container"></div>			
				<a class="pull-right btn btn-primary" href="<?php echo $this->url('master', array('action'=>'addpaygroup'));?>">
				<span class="white"><i class="fa fa-plus"></i> <span class="hidden-sm hidden-xs">&nbsp;Add Group</span></span>
				</a>
				<div class="pull-right"></div>			
				<?php echo $this->partial('accounts/master/partial.phtml', array('active' => 'paygroup')); ?>
				<div class="x_content">
					<div class="table-responsive">
						<table id="datatable" class="table table-striped jambo_table bulk_action">
							<thead>
								<tr class="headings">
									<th>#</th>
									<th>Pay Group</th>
									<th>Value</th>
									<th>Pay Head</th>
									<th >Action</th>
								</tr>
							</thead>
							<tbody>
								<?php
								$i = 1; 
								foreach ($this->paygroups as $rows): ?>
									<tr>
										<td><?php echo $i; ?> </td>
										<td><b><?php echo $rows['group']; ?></b></td>
										<td><?php echo $rows['value']; ?></td>
										<td><?php echo $rows['pay_head']; ?></td>
										<td>
									    <a class="btn btn-xs btn-info " href="<?php echo $this->url('master', array('action'=>'editpaygroup', 'id'=>$rows['id']));?>" >
											<span class="white"><i class="fa fa-pencil bigger-120"> Edit</i> <span class="hidden-lg hidden-xs"></span></span>
										</a>
									    </div></td>
									</tr>
								<?php 
								$i++;
								endforeach;  
								?>                        
							</tbody>
						</table>
					</div>
	            </div>
	        </div>
	    </div>
	</div>
</div>
<!--for modal -->
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content"> </div>
    </div>
</div>