<?php 
$title = 'Pay Head';
$this->headTitle($title);
?>
<div class="right_col" role="main">
	<div class=" ">
		<div class="col-md-12 col-xs-12">
			<div class="x_panel">
				<div class="x_title">
					<h2><?php echo $this->escapeHtml($title);?></h2>
					<ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </ul>
					<div class="clearfix"></div>
				</div>
				<div class="pull-right"></div>	
                <a class="pull-right btn btn-primary" href="<?php echo $this->url('master', array('action'=>'addpayhead'));?>">
				<span class="white"><i class="fa fa-plus"></i> <span class="hidden-sm hidden-xs">&nbsp;Add Payhead</span></span>
				</a>				
				<?php echo $this->partial('accounts/master/partial.phtml', array('active' => 'payhead')); ?>
			    <div class="x_content">
					<div class="table-responsive">
						<table id="datatable" class="table table-striped jambo_table bulk_action">
							<thead>
								<tr class="headings">
									<th class="column-title" >Sl No</th>
									<th class="column-title" >Pay Head</th>
									<th class="column-title" >DLWP</th>
									<th class="column-title" >RoundUp</th>
									<th class="column-title" >Deduction</th>
									<th class="column-title">Type</th>
									<th class="column-title">Percentage</th>
									<th class="column-title">Against</th>
									<th class="column-title">Action</th>
								</tr>
							</thead>
							<tbody>
							<?php
								$i = 1; 
								foreach ($this->rowset as $rows): 
									$deduction = ($rows['deduction'] == 1)?"Yes":"No";
									if(($rows['against'] > 0 )):
										$against = $this->payheadObj->getColumn(array('id'=>$rows['against']),'pay_head');
									elseif($rows['against'] == '-1'):
										$against = "Gross Pay";
									elseif($rows['against'] == '-2'):
										$against = "PIT Net Pay";
									else:
										$against = "";
									endif;
									
									if($rows['type'] == 1):
										$type = "Actual amount";
									elseif($rows['type'] == 2):
										$type = "Percentage";
									elseif($rows['type'] == 3):
										$type = "Slab";
									elseif($rows['type'] == 4):
										$type = "Group";
									endif;?>
								<tr class="">
									<td><?php echo $i; ?> </td>
									<td><b><?php echo $rows['code']; ?></b> (<?php echo $rows['pay_head']; ?>) </td>
									<td><?php echo $dlwp = ($rows['dlwp']=='1')?'Yes':'No';?></td>
									<td><?php echo $roundup = ($rows['roundup']=='1')?'Yes':'No';?></td>
									<td><?php echo $deduction; ?></td>
									<td><?php echo $type ?></td>
									<td><?php echo $rows['percentage'];?></td>
									<td><?php echo $against;?></td>
									<td><div class="btn-group">
										<a class="btn btn-xs btn-info " href="<?php echo $this->url('master', array('action'=>'editpayhead', 'id'=>$rows['id']));?>" >
											<span class="white"><i class="fa fa-pencil bigger-120"> Edit</i> <span class="hidden-lg hidden-xs"></span></span>
										</a>
									</div></td>
								</tr>
							<?php 
							$i++;
							endforeach;  
							?>                        
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>