<?php

 $title = 'Student Leave Category';
 $this->headTitle($title);
 
 $leaveCategory = array();
 foreach($this->viewCategory as $leave)
 {
	 $leaveCategory['leave_category'] = $leave['leave_category'];
	 $leaveCategory['approval_by'] = $leave['rolename'];
	 $leaveCategory['remarks'] = $leave['remarks'];
 }
 ?>
<div class="right_col" role="main">
          <div class="">
              <div class="col-md-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                  </div>
                    
                  <div class="x_content">
                    <br/>
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				  ?> 
                  <div class="row">
                   <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Leave Category<span class="required">*</span></label>
                      <div class="col-md-6 col-md-6 col-xs-12">
                      <input type="text" class="form-control" disabled="disabled" placeholder="<?php echo $leaveCategory['leave_category']; ?>">
                       </div>
                    </div>  
                  </div>  
                    
                 <div class="row">
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Approval By<span class="required">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                        <input type="text" class="form-control" disabled="disabled" placeholder="<?php echo $leaveCategory['approval_by']; ?>">
                        </div>
                      </div>  
                 </div> 
                 <div class="row">
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Brief Description</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                        <textarea class="form-control" disabled="disabled" rows="3" placeholder='<?php echo $leaveCategory['remarks']; ?>'></textarea>
                        </div>
                      </div>  
                 </div>
                 <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
						<?php
							echo $this->form()->closeTag();
                          ?>
                    </div>
                    </div>
                </div>

                       
                    
                  </div>
                </div>
              </div>
              <?php
				 $title = 'Leave Category';
				 $this->headTitle($title);
			  ?>
              <div class="col-md-12 col-xs-12">
                  <div class="x_panel">
                      <div class="x_title">
                    <h2><?php echo $this->escapeHtml($title); ?></h2>
                    <div class="clearfix"></div>
                  </div>
                
                    <div class="x_content">
                        <div class="table-responsive">
                      <table class="table table-striped jambo_table bulk_action"> 
                         <div class="form-group">      
                      </div> 
                        <thead>
                          <tr class="headings">
                            <th class="column-title">Sl. No</th>
                            <th class="column-title">Leave Category </th>
                            <th class="column-title">Approval By</th>
                            </th>
                            <th class="bulk-actions" colspan="7">
                              <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                            </th>
                          </tr>
                        </thead>
                        <tbody>
                          <?php $i=1; foreach ($this->leaveCategories as $category) : ?>
                          <tr class="even pointer">
                            <td class=" "><?php echo $i++;?></td>
                            <td class=" "><?php echo $this->escapeHtml($category['leave_category']);?></td>
                            <td class=" "><?php echo $this->escapeHtml($category['rolename']);?></td>
                          </tr>
                          <?php endforeach; ?>
                        </tbody>
                     </table>
                    </div>
                    </div>
                
                </div>
              </div>
            </div>
          </div>
            
         
              
       
                