<?php
/**
 * View -- of Accounts/ChequeController/indexAction
 */
$title = "Cheque Book";
?>
<?php $minYear = date('Y', strtotime($data['minYear'])); ?> 
<div class="right_col" role="main">
	<div class=" ">
		<div class="col-md-12 col-xs-12">
			<div class="x_panel">
				<div class="x_title">
					<h2><?php echo $this->escapeHtml($title);?></h2>
					<ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </ul>
					<div class="clearfix"></div>
				</div>
				<div class="pull-right tableTools-container"></div>			
				<a class="pull-right btn btn-primary" href="<?php echo $this->url('cheque', array('action'=>'addcheque'));?>">
				<span class="white"><i class="fa fa-plus"></i> <span class="hidden-sm hidden-xs">&nbsp;Add  Cheque Book </span></span>
				</a>
			    <form method="post" action="<?php echo $this->url('cheque'); ?>"  enctype="multipart/form-data" >
					<div class="form-group col-lg-2">
						<label class="control-label" for="year">Year</label>
						<select class="form-control" id="year" name="year" data-placeholder="Select" onchange='this.form.submit()'>
							<option value=""></option>
							<?php 
								for($year=date('Y');$year>=$minYear;$year--):
									$selected = ($year == $data['year'])?"selected":"";
							?>
								<option value="<?php echo $year;?>" <?php echo $selected;?> >
									<?php echo $year;?> 
								</option>
							<?php endfor; ?>
						</select>
					</div>
					<div class="form-group col-lg-2">
						<label class="control-label" for="month">Month</label>
						<select class="form-control" id="month" name="month" data-placeholder="Select" onchange='this.form.submit()'>
							<?php for($month=1; $month<=12; $month++):?>
								<?php $selected = ($month == $data['month'])?'selected':'';?>
								<option value="<?php echo $month;?>" <?php echo $selected; ?>>
									<?php echo DateTime::createFromFormat('!m', $month)->format('F');?>
								</option> 
							<?php endfor;?>
						</select>
					</div>
					<div class="form-group col-lg-3">
						<label class="control-label" for="organisation">Organisation</label>
						<select class="form-control" name="organisation" id="organisation" data-placeholder="select" onchange='this.form.submit()'>
							<?php $selected_org = ($data['userorg'] == '-1')?"selected":"";?>
							<option value=""></option>
								<?php  
									$results = $this->orgObj->get(array('id'=>$data['userorg']));
									foreach ($results as $result):
										$selected_org = ($result['id']==$data['userorg'])?"selected":"";
								?>
									<option value="<?php echo $result['id']; ?>" <?php echo $selected_org;?>>
										<?php echo $result['organisation_name']; ?>
									</option>
							<?php endforeach;  ?>									
						</select>
					</div>
				</form>
				<div class="x_content">
					<div class="table-responsive">
						<table id="datatable" class="table table-striped jambo_table bulk_action">
							<thead>
								<tr class="headings">
								<th>SL. No. </th>
									<th>Cheque Code</th>
									<th>Organisation</th>
									<th>Bank Account</th>
								</tr>
							</thead>
							<tbody>
								<?php $sl = 1;?>
								<?php foreach($this->cheques as $row):?>
								
									<tr data-href="<?php echo $this->url('cheque', array('action'=>'viewcheque', 'id'=>$row['id']));?>">
										<td><?php echo $sl++;?></td>
										<td><b><?php echo $row['cheque_code'];?></b></td>
										<td><b><?php echo $this->orgObj->getcolumn($row['organisation_id'],'organisation_name');?></b></td>
										<td><b><?php echo $this->BAObj->getColumn($row['bank_account'],'bank_account');?></b></td>
									</tr>
								<?php endforeach;?>
							</tbody>
				        </table>
			        </div>
			    </div>
			</div>
		</div>
	</div>
</div>
<script>		
	$("tr[data-href]").each(function(){
		$(this).find('td').not('td.action').each(function(){
			$(this).css('cursor','pointer');
			$(this).bind('click',function() {
				window.document.location = $(this).closest('tr').attr("data-href");
			});
		});
	});
</script>
