<?php
/**
 * View -- of Accounts/AdvancesalaryController/viewadvancesalaryAction
 */
   $this->headTitle($this->title);
?>
<?php 
	foreach($this->cheque as $row):
		extract($row);
	endforeach;
?>
<div class="right_col" role="main">
	<div class=" ">
		<div class="col-md-12 col-xs-12">
			<div class="x_panel">
	            <div class="x_title">
					<h2><?php echo $this->escapeHtml($title);?></h2>
					<ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </ul>
					<div class="clearfix"></div>
				</div>
				<div class="x_content">
					<div class="row" id="convert-tb0">
						<div class="col-lg-9" id="convert-tb1">
							<ul class="list-unstyled spaced">
								<li>
									<i class="ace-icon fa fa-caret-right blue"></i>Cheque Code: <b class="red"><?php echo $cheque_code?></b>
								</li>

								<li>
									<i class="ace-icon fa fa-caret-right blue"></i>Receive Date: <b class="red"><?php echo $receive_date; ?> </b>
								</li>

								<li>
									<i class="ace-icon fa fa-caret-right blue"></i>No of Cheque:	<b class="red"><?php echo $no_of_cheque;?> </b>
								</li>
							</ul>
						</div>
                        <div class="col-lg-3" id="convert-tb2">
							<ul class="list-unstyled spaced">
								<li>
									<i class="ace-icon fa fa-caret-right blue"></i>Start Cheque No:	<b class="red"><?php echo $start_cheque_no;?> </b>
								</li>
								<li>
									<i class="ace-icon fa fa-caret-right blue"></i>End Cheque No:	<b class="red"><?php echo $end_cheque_no;?> </b>
								</li>
							</ul>
						</div>
					</div>
					<div class="row">
						<table class="table table-striped table-bordered table-condensed">	
							<thead>
								<th>#</th>
								<th>Instrument No.</th>
								<th>Status</th>
								<th class="no-sort no-printpdf">Action</th>            
							</thead>
							<tbody>
								<?php $sl = 1;
									foreach($this->CBObj->get(array('cd.cheque_id'=>$id,'cd.status'=>array(12,2,4))) as $tdrow):?>
									<?php if(sizeof($this->CBObj->get(array('cd.cheque_id'=>$id,'cd.status'=>array(12,2,4)))) > 0):?>
									<tr>
										<td><?php echo $sl++;?></td>
										<td><?php echo $tdrow['instrument_no'];?></td>
										<td><?php echo $this->status($tdrow['status']);?></td>
										<?php $disabled_button = ($tdrow['status'] == 12 || $tdrow['status'] == 4)? 'disabled':'';?>
										<td><div class="btn-group">
										<a class="btn btn-xs btn-info " href="<?php echo $this->url('cheque', array('action'=>'addchequecancel', 'id'=>$tdrow['id']));?>"<?php echo $disabled_button;?>  >
											<span class="white"><i class="fa fa-pencil bigger-120"> Cancel Cheque</i> <span class="hidden-lg hidden-xs"></span></span>
										</a>
									    </div></td>
									</tr>
									<?php endif;?>
								<?php endforeach;?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>