<?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'My Appraisal Form (Academic Staff)';
 $this->headTitle($title);
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                   <?php
                   $form->prepare();
                   echo $this->form()->openTag($form);

                  // echo $this->formHidden($form->get('id'));   
                ?>
                  
                <div class="row">    
                 <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Five Year Plan
                    </label>
               <input type="text" class="form-control" placeholder="11th five year plan" >
                </div>
                    <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Objectives
                    </label>
               <input type="text" class="form-control" placeholder="Improve student education quality" >
                </div>
            
                 <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Financial Year 
                    </label>
                <input type="text" class="form-control" placeholder="2017-2018" >
                    </div>
                   <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Department / Division
                    </label>
                <input type="text" class="form-control" placeholder="Academic" >
                    </div>   
                    <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Activity
                    </label>
                <?php  //echo $this->formRow($form->get('training_type')); ?>
                    </div> 
                </div>  
               
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                </div>
              </div>
        </div>
              
     <?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Activity:..........................................';
 $this->headTitle($title);
?>     
              
        <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                     <h2><?php echo $this->escapeHtml($title); ?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>

                <div class="x_content">

                  <table class="table   table-striped responsive-utilities jambo_table bulk_action table-bordered">
                    <thead>
                      <tr class="headings">
                        </th>
                         <th class="column-title">Sl.No </th>
                          <th class="column-title">Sub Activity </th>
                          <th class="column-title">Category </th>
                        <th class="column-title">Maximum API</th>
                        <th class="column-title">Action</th>
                        
                        
                        <th class="bulk-actions" colspan="7">
                          <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                        </th>
                      </tr>
                    </thead>

                    <tbody>
                      <tr class="even pointer">
                       <td class=" ">1</td>
                      <td><input type="text" class="form-control" placeholder=""></td>
                       <td>
                           <select class="form-control">
                                <option>Teaching & Learning</option>
                                <option>Research & Innovation</option>
                                <option>Professional Services</option>
                            </select>
                                </td>
                      <td><input type="text" class="form-control" placeholder=""></td>
                       <td><button class="btn btn-success">Add</button></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
                  
            </div>
            </div>      
                   <?php
 // module/Album/view/album/album/edit.phtml:

 $title = '';
 $this->headTitle($title);
?>     
              
        <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                  <div class="x_content">
                  <br />
                   <div class="" role="tabpanel" data-example-id="togglable-tabs">
                    <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                      <li role="presentation" class=""><a href="#tab_content2" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false">Peer</a>
                      </li>
                      <li role="presentation" class=""><a href="#tab_content3" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false">Subordinate</a>
                      </li>
                      <li role="presentation" class=""><a href="#tab_content4" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false">Beneficiary</a>
                      </li>
                      <li role="presentation" class=""><a href="#tab_content5" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false">Students</a>
                      </li>
                    </ul>
                    <div id="myTabContent" class="tab-content">
                      <div role="tabpanel" class="tab-pane fade" id="tab_content2" aria-labelledby="profile-tab">
                        <p>
                         
                        <div class="x_panel"> 
            <div class="x_content">
                      <table class="table table-striped jambo_table bulk_action"> 
                        <thead>
                          <tr class="headings">
                           <th>
                              <input type="checkbox" id="check-all" class="flat">
                            </th>
                             <th class="column-title">Sl.No. </th>
                            <th class="column-title">Employee Name</th>
                            <th class="column-title">EID </th>
                            <th class="column-title">Designation</th>
                            <th class="column-title">Remarks</th>
                            <th class="bulk-actions" colspan="7">
                              <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                            </th>
                          </tr>
                        </thead>
                        
                        <tbody>
                          <tr>
                           <td><input type="checkbox" id="check-all" class="flat"></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                          </tr>
                        </tbody>
                          </table>    <div class="row">
                      <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <button class="btn btn-success">Add</button></div></div>
            </div></div>
                </div>
                        <div role="tabpanel" class="tab-pane fade" id="tab_content3" aria-labelledby="profile-tab">
                        <p>
                         
                        <div class="x_panel"> 
            <div class="x_content">
                 <br/> 
                      <table class="table table-striped jambo_table bulk_action"> 
                        <thead>
                          <tr class="headings">
                           <th>
                              <input type="checkbox" id="check-all" class="flat">
                            </th>
                             <th class="column-title">Sl.No. </th>
                            <th class="column-title">Employee Name</th>
                            <th class="column-title">EID </th>
                            <th class="column-title">Designation</th>
                            <th class="column-title">Remarks</th>
                            <th class="bulk-actions" colspan="7">
                              <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                            </th>
                          </tr>
                        </thead>
                        
                        <tbody>
                          <tr>
                           <td><input type="checkbox" id="check-all" class="flat"></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                          </tr>
                        </tbody>
                          </table>
                           <div class="row">
                      <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <button class="btn btn-success">Add</button></div></div>
            </div></div>
                </div>
                        
                        <div role="tabpanel" class="tab-pane fade" id="tab_content4" aria-labelledby="profile-tab">
                        <p>
                          <div class="x_panel">  
                        <div class="x_content">
                 <br/> 
                      <table class="table table-striped jambo_table bulk_action"> 
                        <thead>
                          <tr class="headings">
                           <th>
                              <input type="checkbox" id="check-all" class="flat">
                            </th>
                             <th class="column-title">Sl.No. </th>
                            <th class="column-title">Employee Name</th>
                            <th class="column-title">EID </th>
                            <th class="column-title">Designation</th>
                            <th class="column-title">Remarks</th>
                            <th class="bulk-actions" colspan="7">
                              <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                            </th>
                          </tr>
                        </thead>
                        
                        <tbody>
                          <tr>
                           <td><input type="checkbox" id="check-all" class="flat"></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                          </tr>
                        </tbody>
                          </table>
                           <div class="row">
                      <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <button class="btn btn-success">Add</button></div></div>
            </div></div>
                </div>
                        <div role="tabpanel" class="tab-pane fade" id="tab_content5" aria-labelledby="profile-tab">
                        <p>
                          <div class="x_panel">  
                        <div class="x_content">
                 <br/> 
                      <table class="table table-striped jambo_table bulk_action"> 
                        <thead>
                          <tr class="headings">
                           <th>
                              <input type="checkbox" id="check-all" class="flat">
                            </th>
                             <th class="column-title">Sl.No. </th>
                            <th class="column-title">Module Name</th>
                            <th class="column-title">Programme</th>
                            <th class="column-title">Semester</th>
                            <th class="column-title">Academic Year</th>
                            <th class="bulk-actions" colspan="7">
                              <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                            </th>
                          </tr>
                        </thead>
                        
                        <tbody>
                          <tr>
                           <td><input type="checkbox" id="check-all" class="flat"></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                          </tr>
                        </tbody>
                          </table>
                           <div class="row">
                      <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      <button class="btn btn-success">Add</button></div></div>
            </div></div>
                </div>
                </div>
              </p>
              
             </div>
          </div>
                  <div class="x_content">
                   <div class="row"><div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">Date:
                    </label>
                <?php  //echo $this->formRow($form->get('course_title')); ?>
                </div>
                </div>  
                 <div class="row">
                        <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                    <button class="btn btn-default">Save & Close</button>
                    <button class="btn btn-success">Submit</button>
                 </div>
                </div>
               </div>
                </div>
              </div>
            </div>
         
          </div>
        </div> 

              
              
   
            
    