<?php
 $title = 'Edit Nature of Activity';
 $this->headTitle($title);
 $activity_detail = array();
 foreach($this->activityDetail as $detail){
	 $activity_detail = $detail;
 }
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
               <div class="" role="tabpanel" data-example-id="togglable-tabs">
                <div id="myTabContent" class="tab-content">
                  <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="profile-tab">
                   <br/> 
                   <p> 
                   <div class="x_panel"> 
                     <h2>Organisation/Colleges</h2>   
                    <div class="x_content">
                  <br />
                   
                <?php
					// Opening of the form tag
					$activityForm->prepare();
					echo $this->form()->openTag($activityForm);
					$activity = $activityForm->get('natureactivity');
					$activity->get('id')->setValue($activity_detail['id']);
					$activity->get('nature_of_activity')->setValue($activity_detail['nature_of_activity']);
					$activity->get('maximum_score')->setValue($activity_detail['maximum_score']);
					echo $this->formHidden($activity->get('id'));  
				  ?>
				
				  <div class="form-group">
					<label class="control-label col-md-3 col-sm-3 col-xs-12" >Nature of Activity<span class="required">*</span></label>
					<div class="col-md-6 col-sm-6 col-xs-12">
					  <?php  echo $this->formRow($activity->get('nature_of_activity')); ?>
					</div>
				  </div>
				  <div class="form-group">
					<label class="control-label col-md-3 col-sm-3 col-xs-12">Maximum Score<span class="required">*</span></label>
					<div class="col-md-6 col-sm-6 col-xs-12">
					  <?php echo $this->formRow($activity->get('maximum_score')); ?>
					</div>
				  </div>
				 <div class="row">
					<div class="ln_solid"></div>
					<div class="form-group">
						<label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
						  <?php
						   echo $this->formHidden($activityForm->get('csrf'));
						   echo $this->formSubmit($activity->get('submitactivity')); 
						   echo $this->form()->closeTag(); 
						?>
					</div>
				</div>
                <br /><br />
				<div class="x_panel">
                <div class="x_content">
                     <div class="table-responsive">
                      <table class="table   table-striped responsive-utilities jambo_table bulk_action table-bordered">
                        <thead>
                          <tr class="headings">
                             <th class="column-title">Sl.No.</th>
                             <th class="column-title">Nature of Activity</th>
                             <th class="column-title">Maximum Score</th>
                             <th class="column-title">Action</th>
                          </tr>
                        </thead>
    
                        <tbody>
                          <?php
                          $i=1;  foreach($this->natureActivity as $activity): ?>
                          <tr class="even pointer">
                            <td class=" "><?php echo $i++;?></td>
                            <td class=" "><?php echo $activity['nature_of_activity'];?></td>
                            <td class=" "><?php echo $activity['maximum_score'];?></td>
                            <td class=" "><a href="<?php echo $this->url('editnatureofactivity', array('id' => $activity['id']));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a></td>
                          </tr>
                          <?php endforeach; ?>
                        </tbody>
                      </table>
					</div>
				</div>
			</div> 
                
   		 </div>
 		</div>
	</div>
  </div>
</div>
            
