<?php
 $title = 'Performance Management System - Administrative Appraisal';
 $this->headTitle($title);
 $appraisal_details = array();
 foreach($this->appraisalDetail as $detail){
	 $appraisal_details = $detail;
 }
?>
<div class="right_col" role="main">
          <div class="">
              
         <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title)?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                
                    </ul>
                 <div class="clearfix"></div>
              
                </div>
                   
                <div class="x_content">
                  <br />
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				            $awpa = $form->get('iwpactivities');
					         //get the objectives with their id
					          $data = $this->selectData;
                    echo $this->form()->openTag($form);
          					$awpa->get('employee_details_id')->setValue($this->employee_details_id);
          					$awpa->get('status')->setValue($appraisal_details['status']);
          					//get details
          					$awpa->get('id')->setValue($appraisal_details['id']);
                    $awpa->get('appraisal_period')->setValue($appraisal_details['appraisal_period']);
          					$awpa->get('subactivity_name')->setValue($appraisal_details['subactivity_name']);
          					$awpa->get('outstanding_description')->setValue($appraisal_details['outstanding_description']);
          					$awpa->get('very_good_description')->setValue($appraisal_details['very_good_description']);
          					$awpa->get('good_description')->setValue($appraisal_details['good_description']);
          					$awpa->get('needs_improvement_description')->setValue($appraisal_details['needs_improvement_description']);
                    echo $this->formHidden($awpa->get('id')); 
          					echo $this->formHidden($awpa->get('employee_details_id'));
          					echo $this->formHidden($awpa->get('status'));
                    echo $this->formHidden($awpa->get('appraisal_period'));
          					$awpa->get('awpa_objectives_activity_id')->setValueOptions($data);
          					$awpa->get('awpa_objectives_activity_id')->setValue($appraisal_details['awpa_objectives_activity_id']);
                    $awpa->get('submit')->setValue('Update Activity');
          				  ?>

                    <?php 
                            if ($this->message == NULL && $this->flashMessenger()->hasMessages()) {
                                echo '<div class="alert alert-success alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                $messages = $this->flashMessenger()->getMessages();
                                foreach($messages as $message) {
                                    echo '<strong>Success!</strong>'. $message;
                                }
                                echo '</div>';
                            }

                            else if($this->message == 'Failure' && $this->flashMessenger()->hasMessages()){
                                echo '<div class="alert alert-danger alert-dismissible fade in" role="alert">';
                                echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>';
                                $messages = $this->flashMessenger()->getMessages();
                                foreach($messages as $message) {
                                    echo '<strong>Failure!</strong>'. $message;
                                }
                                echo '</div>';
                            }
                        ?>
                
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">New Activity<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($awpa->get('awpa_objectives_activity_id')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Sub Activity Name<span class="required">*</span></label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($awpa->get('subactivity_name')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12"> Brief Description for Success Indicator</label>
                    <label class="control-label col-md-1 col-sm-3 col-xs-12">Outstanding</label>
                    <div class="col-md-5 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($awpa->get('outstanding_description')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12"> </label>
                    <label class="control-label col-md-1 col-sm-3 col-xs-12">Very Good</label>
                    <div class="col-md-5 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($awpa->get('very_good_description')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12"> </label>
                    <label class="control-label col-md-1 col-sm-3 col-xs-12">Good</label>
                    <div class="col-md-5 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($awpa->get('good_description')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12"> </label>
                    <label class="control-label col-md-1 col-sm-3 col-xs-12">Needs Improvement</label>
                    <div class="col-md-5 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($awpa->get('needs_improvement_description')); ?>
                    </div>
                  </div>
                 
                 <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-4 col-sm-4 col-xs-12"></label>
                          <?php
						   echo $this->formHidden($form->get('csrf'));
						   echo $this->formSubmit($awpa->get('submit')); 
						   echo $this->form()->closeTag(); 
                        ?>
                    </div>
                </div>
                  
          </div>
        </div>
                  </div>     
                  
              
        <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml("Success Indicators"); ?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>

                <div class="x_content">
                  <table class="table   table-striped responsive-utilities jambo_table bulk_action table-bordered">
                    <thead>
                      <tr class="headings">
                         <th style="width:20%" rowspan="2" class="column-title">College /OVC/Section Outputs.</th>
                         <th style="width:20%" rowspan="2" class="column-title">Sub Activity Name</th>
                         <th style="width:40%" colspan="4" class="column-title">Target Values</th>
                         <th style="width:10%" rowspan="2" class="column-title">Status</th>
                         <th style="width:10%" rowspan="2" class="column-title">Action</th>
                      </tr>
                      <tr class="headings">
                         <th style="width:10%" class="column-title">Outstanding</th>
                         <th style="width:10%" class="column-title">Very Good</th>
                         <th style="width:10%" class="column-title">Good</th>
                         <th style="width:10%" class="column-title">Needs Improvement</th>
                      </tr>
                    </thead>

                    <tbody>
                      <?php
					  	$i=0;
						$activity = NULL;
						foreach($this->kpi as $kpi){ 
					  ?>
                      <tr class="even pointer">
                        <td class=" "><?php if($activity != $kpi['activity_name']) { echo ++$i.'. '.$kpi['activity_name']; $activity=$kpi['activity_name']; $j=1;}?></td>
                        <td class=" "><?php echo $i.'.'.$j++.' '.$kpi['subactivity_name'];?></td>
                        <td class=" "><?php echo $kpi['outstanding_description'];?></td>
                        <td class=" "><?php echo $kpi['very_good_description'];?></td>
                        <td class=" "><?php echo $kpi['good_description'];?></td>
                        <td class=" "><?php echo $kpi['needs_improvement_description'];?></td>
                        <td class=" "><?php echo $kpi['status']; ?></td>
                        <td><a href="<?php echo $this->url('viewadministrativeappraisal', array('id' => $kpi['id']));?>" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i>View</a><br />
                            <?php if($kpi['status'] != "Approved") { ?>
                            <a href="<?php echo $this->url('editadministrativeappraisal', array('id' => $kpi['id']));?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>Edit</a><br />
                            <?php  } if($kpi['status'] == "Pending for Approval") {?>
                            <a href="<?php echo $this->url('deleteadministrativeappraisal', array('id' => $kpi['id']));?>" class="btn btn-danger btn-xs"><i class="fa fa-thrash-o"></i>Delete</a><?php } ?></td>
                      </tr>
                      <?php  } ?>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
         </div>
        </div>