<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
<div class="menu_section">
<br><br><br>
<ul class="nav side-menu">
	<li><a><i class="fa fa-home"></i>Home<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a href="<?php echo $this->url('index') ?>">Dashboard</a></li>
		</ul>
	</li>
	<li><a><i class="fa fa-users"></i>Human Resource<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>HR Planning<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>HRD Planning<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('hrdapprovedlist') ?>">HRD Plan Approved List</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>HRM Planning<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('hrmapprovedlist') ?>">Work Force Approved List</a></li>
					</ul>
					</li>
			</ul>
			</li>
			<li><a><i class=""></i>HR Administration<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>Leave<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('leavestatus') ?>">Apply Leave</a></li>
						<li><a href="<?php echo $this->url('empleaveapproval') ?>">Leave Approval</a></li>
						<li><a href="<?php echo $this->url('staffleavestatus') ?>">My Leave Status</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Leave Encashment<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('empleaveencashmentapplication') ?>">Leave Encashment</a></li>
					</ul>
					</li>
					<li><a href="<?php echo $this->url('empassignofficiatingsupervisor') ?>">Assign Officiating Supervisor</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>HR Development<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>Long Term Trainings<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('longtermplannedlist') ?>">Planned</a></li>
					</ul>
					</li>
					<li><a href="<?php echo $this->url('applytrainings') ?>">Apply Trainings & Workshops</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Staff Lifecycle<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>Transfer<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('applytransferform') ?>">Apply Transfer</a></li>
						<li><a href="<?php echo $this->url('stafftransferstatus') ?>">My Transfer Status</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Promotion<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('empapplypromotion') ?>">Apply Promotion</a></li>
						<li><a href="<?php echo $this->url('empmeritoriouspromotion') ?>">Meritorious Promotion</a></li>
						<li><a href="<?php echo $this->url('staffpromotionstatus') ?>">My Promotion Status</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Separation<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('empresignation') ?>">Apply Resignation</a></li>
						<li><a href="<?php echo $this->url('resignationrecord') ?>">Dues Record</a></li>
						<li><a href="<?php echo $this->url('staffresignationstatus') ?>">My Resignation Status</a></li>
					</ul>
					</li>
			</ul>
			</li>
			<li><a><i class=""></i>PMS<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>Appraisals<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('administrativeappraisal') ?>">Administrative Appraisal</a></li>
						<li><a href="<?php echo $this->url('academicappraisal') ?>">Academic Appraisal</a></li>
						<li><a href="<?php echo $this->url('appraisalapprovallist') ?>">Appraisal Approval Lists</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Review<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('feedbacks') ?>">Feedbacks</a></li>
					</ul>
					</li>
					<li><a href="<?php echo $this->url('listnominations') ?>">Nominations</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Recruitment<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('listvacancy') ?>">List Job Vacancies</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Staff Tour<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('emptravelauthorization') ?>">Travel Authorization</a></li>
					<li><a href="<?php echo $this->url('emptravellist') ?>">Travel Approval</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Staff Management<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('empprofilepicture') ?>">Staff Profile Picture</a></li>
					<li><a href="<?php echo $this->url('updateempinitialdetails') ?>">Update Staff Details</a></li>
					<li><a href="<?php echo $this->url('emprelationdetail') ?>">Staff Relation Details</a></li>
					<li><a href="<?php echo $this->url('empworkexperience') ?>">Staff Work Experience</a></li>
					<li><a href="<?php echo $this->url('empeducation') ?>">Staff Education</a></li>
					<li><a href="<?php echo $this->url('emptrainingdetail') ?>">Staff Trainings</a></li>
					<li><a href="<?php echo $this->url('emppublication') ?>">Staff Publications</a></li>
					<li><a href="<?php echo $this->url('empresponsibility') ?>">Staff Responsibilities</a></li>
					<li><a href="<?php echo $this->url('empcontribution') ?>">Staff Contributions</a></li>
					<li><a href="<?php echo $this->url('empaward') ?>">Staff Awards</a></li>
					<li><a href="<?php echo $this->url('empcommunityservice') ?>">Staff Community Service</a></li>
			</ul>
			</li>
		</ul>
	</li>
	<li><a><i class="fa fa-bank"></i>Admission<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>Student Details<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('studentlists') ?>">Student Lists</a></li>
					<li><a href="<?php echo $this->url('studentpersonaldetails') ?>">Student Personal Details</a></li>
					<li><a href="<?php echo $this->url('studentpermanentaddressdetails') ?>">Student Permanent Address</a></li>
					<li><a href="<?php echo $this->url('studentrelationdetails') ?>">Student Relation Details</a></li>
					<li><a href="<?php echo $this->url('studentpreviousschooldetails') ?>">Student Previous School Details</a></li>
			</ul>
			</li>
		</ul>
	</li>
	<li><a><i class="fa fa-graduation-cap"></i>Academic<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>Assessment Mark Allocation<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('addallocationmark') ?>">Allocate Assessment Marks</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Academic Assessment<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('academicassessment') ?>">Continuous Assessment</a></li>
					<li><a href="<?php echo $this->url('viewassessmentmarks') ?>">View Continuous Assessment</a></li>
					<li><a href="<?php echo $this->url('editassessmentmarks') ?>">Edit Continuous Assessment</a></li>
					<li><a href="<?php echo $this->url('viewsemestermarks') ?>">View Semester Marks</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Timetable<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('addtimetable') ?>">Add Timetable</a></li>
					<li><a href="<?php echo $this->url('viewtimetable') ?>">View Student Timetable</a></li>
					<li><a href="<?php echo $this->url('viewtutortimetable') ?>">View Tutor Timetable</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Student Attendance<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('studentattendance') ?>">Attendance Entry</a></li>
					<li><a href="<?php echo $this->url('extraclassattendance') ?>">Extra Class Attendance</a></li>
					<li><a href="<?php echo $this->url('cancelledlectures') ?>">Cancelled/Called Off Lectures</a></li>
					<li><a href="<?php echo $this->url('editstudentattendance') ?>">Edit Attendance</a></li>
					<li><a href="<?php echo $this->url('viewextracurricularattendance') ?>">View Attendance</a></li>
			</ul>
			</li>
		</ul>
	</li>
	<li><a><i class="fa fa-user"></i>Student Service<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>Responsibility<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('responsibilitycategory') ?>">Add New Category</a></li>
					<li><a href="<?php echo $this->url('viewstdresponsibility') ?>">View Responsibility</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Student Disciplinary<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('disciplinarycategory') ?>">Offence Category</a></li>
					<li><a href="<?php echo $this->url('viewdisciplinaryrecord') ?>">View Disciplinary Record</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Character Certificate<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('viewcharactercert') ?>">View Character Certificate</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Extra Curricular Attendance<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('editextracurricularattendance') ?>">Edit Extra Curricular Attendance</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Achievement<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('addachievementcategory') ?>">Add Category</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Student Participation<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('stdparticipationcategory') ?>">Add Category</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Contribution<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('stdcontributioncategory') ?>">Add Category</a></li>
					<li><a href="<?php echo $this->url('viewstdcontribution') ?>">View Contribition</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Medical Record<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('viewstdmedicalrecord') ?>">View Medical Record</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Leave Management<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('stdleavecategory') ?>">Leave Category</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Student Suggestion<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('viewstdsuggestions') ?>">View Suggestion</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Clubs and Units<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('clubmembershipstatus') ?>">Club Membership Status</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Student Reports<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('studentfeedbackreports') ?>">Student Feedbacks Report</a></li>
					<li><a href="<?php echo $this->url('studentreports') ?>">Student Related Reports</a></li>
			</ul>
			</li>
			<li><a href="<?php echo $this->url('studentprofilepicture') ?>">Student Profile Picture</a></li>
			<li><a href="<?php echo $this->url('studentlists') ?>">Student Lists</a></li>
		</ul>
	</li>
</ul>
</div>
</div>
