<?php
 $title = 'Capital Budget Proposal';
 $this->headTitle($title);
 
 $budgetProposal = array();
 foreach($this->budgetDetails as $detail){
	 $budgetProposal['id'] = $detail['id'];
	 $budgetProposal['five_year_plan'] = $detail['five_year_plan'];
	 $budgetProposal['financial_year'] = $detail['financial_year'];
	 $budgetProposal['activity_name'] = $detail['activity_name'];
	 $budgetProposal['proposed_budget_amount'] = $detail['proposed_budget_amount'];
	 $budgetProposal['write_up'] = $detail['write_up'];
	 $budgetProposal['organisation_id'] = $detail['organisation_id'];
	 $budgetProposal['departments_id'] = $detail['departments_id'];
	 $budgetProposal['object_code_id'] = $detail['object_code_id'];
	 $budgetProposal['broad_head_name_id'] = $detail['broad_head_name_id'];
 }
?>
<div class="right_col" role="main">
          <div class="">
            <div class="col-md-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                  </ul>
                 <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                   <?php
                    // Opening of the form tag
                    $form->prepare();
                    echo $this->form()->openTag($form);
				            $proposal = $form->get('capitalbudgetproposal');
                    echo $this->form()->openTag($form);
                    $proposal->get('five_year_plan')->setValue('12th Five Year Plan');
                    $proposal->get('departments_id')->setValueOptions($this->departments);
                    $proposal->get('activity_id')->setValueOptions($this->activities);
                    $proposal->get('budget_proposal_status')->setValue('Not Submitted');
                    $proposal->get('id')->setValue($budgetProposal['id']);
                    $proposal->get('five_year_plan')->setValue($budgetProposal['five_year_plan']);
                    $proposal->get('departments_id')->setValue($budgetProposal['departments_id']);
                    $proposal->get('organisation_id')->setValue($budgetProposal['organisation_id']);
                    $proposal->get('financial_year')->setValue($budgetProposal['financial_year']);
                    $proposal->get('activity_name')->setValue($budgetProposal['activity_name']);
                    $proposal->get('proposed_budget_amount')->setValue($budgetProposal['proposed_budget_amount']);
                    $form->get('broad_head_name_id')->setValue($budgetProposal['broad_head_name_id']);
                    $proposal->get('write_up')->setValue($budgetProposal['write_up']);
                    echo $this->formHidden($proposal->get('id')); 
                    $proposal->get('submit')->setValue('Update Proposal');
					
				  ?>  
                <div class="row">    
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Five Year Plan</label>
                    <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($proposal->get('five_year_plan')); ?>
                    </div>
                    <label class="control-label col-md-2 col-sm-3 col-xs-12">Financial Year</label>
                    <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($proposal->get('financial_year')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">OVC/College</label>
                    <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($proposal->get('organisation_id')); ?>
                    </div>
                    <label class="control-label col-md-2 col-sm-3 col-xs-12">Office/Department</label>
                    <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($proposal->get('departments_id')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Activity List<span class="required">*</span></label>
                    <div class="col-md-7 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($proposal->get('activity_id')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Activity Name<span class="required">*</span><br  /></label>
                    <div class="col-md-7 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($proposal->get('activity_name')); ?>
                      <i>(If activity is not listed, then please select "Others" from the list and
                    			write the activity here. Please note, choosing an activity from above will ignore this field)</i>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Broad Head Name<span class="required">*</span></label>
                    <div class="col-md-7 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($form->get('broad_head_name_id')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Object Code<span class="required">*</span></label>
                    <div class="col-md-7 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($form->get('object_code_id')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Budget Type<span class="required">*</span></label>
                    <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($proposal->get('budget_type')); ?>
                    </div>
                    <label class="control-label col-md-2 col-sm-3 col-xs-12">Proposed Budget (Amount)<span class="required">*</span></label>
                    <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <?php  echo $this->formRow($proposal->get('proposed_budget_amount')); ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Write Up<span class="required">*</span></label>
                    <div class="col-md-7 col-sm-6 col-xs-12">
                      <?php  echo $this->formRow($proposal->get('write_up')); ?>
                    </div>
                  </div>
                </div> 
                  
                <div class="row">
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
						<?php
                           echo $this->formHidden($proposal->get('budget_proposal_status'));
						   echo $this->formHidden($proposal->get('organisation_id'));
						   echo $this->formHidden($form->get('csrf'));
						   echo $this->formSubmit($proposal->get('submit')); 
                        ?>
                    	</div>
                    </div>
               </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                </div>
              </div>
        </div> 
     </div>
     </div>
     </div>